/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_pmapmdieee_rdb.h
    @brief RDB File for BRPHY1GV2_PMAPMDIEEE

    @version Orion_A0_20201104_SWDEV
*/

#ifndef BRPHY1GV2_PMAPMDIEEE_RDB_H
#define BRPHY1GV2_PMAPMDIEEE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_TYPE;
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_RESET_MASK (0x8000U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_RESET_SHIFT (15U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_SPEED_SEL_0_MASK (0x2000U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_SPEED_SEL_0_SHIFT (13U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_LOW_POWER_MASK (0x800U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_LOW_POWER_SHIFT (11U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_SPEED_SEL_1_MASK (0x40U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_SPEED_SEL_1_SHIFT (6U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_SPEED_SELECT_MASK (0x3cU)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_SPEED_SELECT_SHIFT (2U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_REMOTE_LOOPBACK_MASK (0x2U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_REMOTE_LOOPBACK_SHIFT (1U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_LOCAL_LOOPBACK_MASK (0x1U)
#define BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_LOCAL_LOOPBACK_SHIFT (0U)




typedef uint16_t BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_TYPE;
#define BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_PIASA_MASK (0x200U)
#define BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_PIASA_SHIFT (9U)
#define BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_PEASA_MASK (0x100U)
#define BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_PEASA_SHIFT (8U)
#define BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_FAULT_MASK (0x80U)
#define BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_FAULT_SHIFT (7U)
#define BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_RECEIVE_LINK_STATUS_MASK (0x4U)
#define BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_RECEIVE_LINK_STATUS_SHIFT (2U)
#define BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_LOW_POWER_ABILITY_MASK (0x2U)
#define BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_LOW_POWER_ABILITY_SHIFT (1U)




typedef uint8_t BRPHY1GV2_PMAPMDIEEE_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_PMAPMDIEEE_B1PPC_TYPE;
#define BRPHY1GV2_PMAPMDIEEE_B1PPC_BASET1_PMA_PMD_CONTROL_BIT_15_MASK (0x8000U)
#define BRPHY1GV2_PMAPMDIEEE_B1PPC_BASET1_PMA_PMD_CONTROL_BIT_15_SHIFT (15U)
#define BRPHY1GV2_PMAPMDIEEE_B1PPC_MASTER_SLAVE_MASK (0x4000U)
#define BRPHY1GV2_PMAPMDIEEE_B1PPC_MASTER_SLAVE_SHIFT (14U)
#define BRPHY1GV2_PMAPMDIEEE_B1PPC_T1_BASE_SEL_MASK (0xfU)
#define BRPHY1GV2_PMAPMDIEEE_B1PPC_T1_BASE_SEL_SHIFT (0U)




typedef volatile struct COMP_PACKED sBRPHY1GV2_PMAPMDIEEE_RDBType {
    BRPHY1GV2_PMAPMDIEEE_CONTROL_REG1_TYPE control_reg1; /* OFFSET: 0x0 */
    BRPHY1GV2_PMAPMDIEEE_STATUS_REG1_TYPE status_reg1; /* OFFSET: 0x2 */
    BRPHY1GV2_PMAPMDIEEE_RESERVED_TYPE rsvd0[4196]; /* OFFSET: 0x4 */
    BRPHY1GV2_PMAPMDIEEE_B1PPC_TYPE baset1_pma_pmd_control; /* OFFSET: 0x1068 */
    BRPHY1GV2_PMAPMDIEEE_RESERVED_TYPE rsvd1[416]; /* OFFSET: 0x106a */
} BRPHY1GV2_PMAPMDIEEE_RDBType;


#define BRPHY1GV2_PMAPMDIEEE_BASE       (0x49020000UL)



#define BRPHY1GV2_PMAPMDIEEE_MAX_HW_ID  (1UL)


#define BRPHY1GV2_PMAPMD_BASET1_CTRL_T1_BASE_SEL_1000  (0x1U)

#endif /* BRPHY1GV2_PMAPMDIEEE_RDB_H */
