/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy_cl45dev7_rdb.h
    @brief RDB File for BRPHY_CL45DEV7

    @version Orion_A0_20201104_SWDEV
*/

#ifndef BRPHY_CL45DEV7_RDB_H
#define BRPHY_CL45DEV7_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY_CL45DEV7_AN_CTRL_TYPE;
#define BRPHY_CL45DEV7_AN_CTRL_AN_RESET_MASK (0x8000U)
#define BRPHY_CL45DEV7_AN_CTRL_AN_RESET_SHIFT (15U)
#define BRPHY_CL45DEV7_AN_CTRL_EXTENDED_NEXT_PAGE_CONTROL_MASK (0x2000U)
#define BRPHY_CL45DEV7_AN_CTRL_EXTENDED_NEXT_PAGE_CONTROL_SHIFT (13U)
#define BRPHY_CL45DEV7_AN_CTRL_AUTO_NEGOTIATION_ENABLE_MASK (0x1000U)
#define BRPHY_CL45DEV7_AN_CTRL_AUTO_NEGOTIATION_ENABLE_SHIFT (12U)
#define BRPHY_CL45DEV7_AN_CTRL_RESTART_AUTO_NEGOTIATION_MASK (0x200U)
#define BRPHY_CL45DEV7_AN_CTRL_RESTART_AUTO_NEGOTIATION_SHIFT (9U)




typedef uint16_t BRPHY_CL45DEV7_AN_STAT_TYPE;
#define BRPHY_CL45DEV7_AN_STAT_EXTENDED_NEXT_PAGE_STATUS_MASK (0x80U)
#define BRPHY_CL45DEV7_AN_STAT_EXTENDED_NEXT_PAGE_STATUS_SHIFT (7U)
#define BRPHY_CL45DEV7_AN_STAT_PAGE_RECEIVED_MASK (0x40U)
#define BRPHY_CL45DEV7_AN_STAT_PAGE_RECEIVED_SHIFT (6U)
#define BRPHY_CL45DEV7_AN_STAT_AN_COMPLETE_MASK (0x20U)
#define BRPHY_CL45DEV7_AN_STAT_AN_COMPLETE_SHIFT (5U)
#define BRPHY_CL45DEV7_AN_STAT_REMODT_FAULT_MASK (0x10U)
#define BRPHY_CL45DEV7_AN_STAT_REMODT_FAULT_SHIFT (4U)
#define BRPHY_CL45DEV7_AN_STAT_AN_ABILITY_MASK (0x8U)
#define BRPHY_CL45DEV7_AN_STAT_AN_ABILITY_SHIFT (3U)
#define BRPHY_CL45DEV7_AN_STAT_LINK_STATUS_MASK (0x4U)
#define BRPHY_CL45DEV7_AN_STAT_LINK_STATUS_SHIFT (2U)
#define BRPHY_CL45DEV7_AN_STAT_LINK_PARTNER_AN_ABILITY_MASK (0x1U)
#define BRPHY_CL45DEV7_AN_STAT_LINK_PARTNER_AN_ABILITY_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_AN_DEV_ID_LSB_TYPE;
#define BRPHY_CL45DEV7_AN_DEV_ID_LSB_CU_DEVICE_IDENTIFIER_MASK (0xffffU)
#define BRPHY_CL45DEV7_AN_DEV_ID_LSB_CU_DEVICE_IDENTIFIER_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_AN_DEV_ID_MSB_TYPE;
#define BRPHY_CL45DEV7_AN_DEV_ID_MSB_CU_DEVICE_IDENTIFIER_MASK (0xffffU)
#define BRPHY_CL45DEV7_AN_DEV_ID_MSB_CU_DEVICE_IDENTIFIER_SHIFT (0U)




typedef uint8_t BRPHY_CL45DEV7_RESERVED_TYPE;




typedef uint16_t BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_TYPE;
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_AUTONEG_PRE_MASK (0x80U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_AUTONEG_PRE_SHIFT (7U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_TC_PRE_MASK (0x40U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_TC_PRE_SHIFT (6U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_DTEXS_PRE_MASK (0x20U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_DTEXS_PRE_SHIFT (5U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_PHYXS_PRE_MASK (0x10U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_PHYXS_PRE_SHIFT (4U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_PCS_PRE_MASK (0x8U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_PCS_PRE_SHIFT (3U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_WIS_PRE_MASK (0x4U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_WIS_PRE_SHIFT (2U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_PMD_PRE_MASK (0x2U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_PMD_PRE_SHIFT (1U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_CLA22_PRE_MASK (0x1U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_CLA22_PRE_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_AN_DEV_IN_PKG_MSB_TYPE;
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_MSB_VENSP_DEV2_PRE_MASK (0x8000U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_MSB_VENSP_DEV2_PRE_SHIFT (15U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_MSB_VENSP_DEV1_PRE_MASK (0x4000U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_MSB_VENSP_DEV1_PRE_SHIFT (14U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_MSB_CLA22_EXT_PRE_MASK (0x2000U)
#define BRPHY_CL45DEV7_AN_DEV_IN_PKG_MSB_CLA22_EXT_PRE_SHIFT (13U)




typedef uint16_t BRPHY_CL45DEV7_AN_DEV_PKG_ID_LSB_TYPE;
#define BRPHY_CL45DEV7_AN_DEV_PKG_ID_LSB_CU_DEVICE_PACKAGE_ID_MASK (0xffffU)
#define BRPHY_CL45DEV7_AN_DEV_PKG_ID_LSB_CU_DEVICE_PACKAGE_ID_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_AN_DEV_PKG_ID_MSB_TYPE;
#define BRPHY_CL45DEV7_AN_DEV_PKG_ID_MSB_CU_DEVICE_PACKAGE_ID_MASK (0xffffU)
#define BRPHY_CL45DEV7_AN_DEV_PKG_ID_MSB_CU_DEVICE_PACKAGE_ID_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_AN_AD_TYPE;
#define BRPHY_CL45DEV7_AN_AD_LD_NEXT_PAGE_MASK (0x8000U)
#define BRPHY_CL45DEV7_AN_AD_LD_NEXT_PAGE_SHIFT (15U)
#define BRPHY_CL45DEV7_AN_AD_LD_ACKNOWLEDGE_MASK (0x4000U)
#define BRPHY_CL45DEV7_AN_AD_LD_ACKNOWLEDGE_SHIFT (14U)
#define BRPHY_CL45DEV7_AN_AD_LD_REMOTE_FAULT_MASK (0x2000U)
#define BRPHY_CL45DEV7_AN_AD_LD_REMOTE_FAULT_SHIFT (13U)
#define BRPHY_CL45DEV7_AN_AD_LD_EXTENDED_NEXT_PAGE_ABILITY_MASK (0x1000U)
#define BRPHY_CL45DEV7_AN_AD_LD_EXTENDED_NEXT_PAGE_ABILITY_SHIFT (12U)
#define BRPHY_CL45DEV7_AN_AD_LD_ASYMMETRIC_PAUSE_MASK (0x800U)
#define BRPHY_CL45DEV7_AN_AD_LD_ASYMMETRIC_PAUSE_SHIFT (11U)
#define BRPHY_CL45DEV7_AN_AD_LD_PAUSE_CAPABLE_MASK (0x400U)
#define BRPHY_CL45DEV7_AN_AD_LD_PAUSE_CAPABLE_SHIFT (10U)
#define BRPHY_CL45DEV7_AN_AD_LD_100BASE_T4_CAPABLE_MASK (0x200U)
#define BRPHY_CL45DEV7_AN_AD_LD_100BASE_T4_CAPABLE_SHIFT (9U)
#define BRPHY_CL45DEV7_AN_AD_LD_100BASE_TX_FULL_DUPLEX_CAPABLE_MASK (0x100U)
#define BRPHY_CL45DEV7_AN_AD_LD_100BASE_TX_FULL_DUPLEX_CAPABLE_SHIFT (8U)
#define BRPHY_CL45DEV7_AN_AD_LD_100BASE_TX_HALF_DUPLEX_CAPABLE_MASK (0x80U)
#define BRPHY_CL45DEV7_AN_AD_LD_100BASE_TX_HALF_DUPLEX_CAPABLE_SHIFT (7U)
#define BRPHY_CL45DEV7_AN_AD_LD_10BASE_T_FULL_DUPLEX_CAPABLE_MASK (0x40U)
#define BRPHY_CL45DEV7_AN_AD_LD_10BASE_T_FULL_DUPLEX_CAPABLE_SHIFT (6U)
#define BRPHY_CL45DEV7_AN_AD_LD_10BASE_T_HALF_DUPLEX_CAPABLE_MASK (0x20U)
#define BRPHY_CL45DEV7_AN_AD_LD_10BASE_T_HALF_DUPLEX_CAPABLE_SHIFT (5U)
#define BRPHY_CL45DEV7_AN_AD_LD_PROTOCOL_SELECTOR_MASK (0x1fU)
#define BRPHY_CL45DEV7_AN_AD_LD_PROTOCOL_SELECTOR_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_AN_LPA_TYPE;
#define BRPHY_CL45DEV7_AN_LPA_LP_NEXT_PAGE_MASK (0x8000U)
#define BRPHY_CL45DEV7_AN_LPA_LP_NEXT_PAGE_SHIFT (15U)
#define BRPHY_CL45DEV7_AN_LPA_LP_ACKNOWLEDGE_MASK (0x4000U)
#define BRPHY_CL45DEV7_AN_LPA_LP_ACKNOWLEDGE_SHIFT (14U)
#define BRPHY_CL45DEV7_AN_LPA_LP_REMOTE_FAULT_MASK (0x2000U)
#define BRPHY_CL45DEV7_AN_LPA_LP_REMOTE_FAULT_SHIFT (13U)
#define BRPHY_CL45DEV7_AN_LPA_LP_EXTENDED_NEXT_PAGE_ABILITY_MASK (0x1000U)
#define BRPHY_CL45DEV7_AN_LPA_LP_EXTENDED_NEXT_PAGE_ABILITY_SHIFT (12U)
#define BRPHY_CL45DEV7_AN_LPA_LP_ASYMMETRIC_PAUSE_MASK (0x800U)
#define BRPHY_CL45DEV7_AN_LPA_LP_ASYMMETRIC_PAUSE_SHIFT (11U)
#define BRPHY_CL45DEV7_AN_LPA_LP_PAUSE_CAPABLE_MASK (0x400U)
#define BRPHY_CL45DEV7_AN_LPA_LP_PAUSE_CAPABLE_SHIFT (10U)
#define BRPHY_CL45DEV7_AN_LPA_LP_100BASE_T4_CAPABLE_MASK (0x200U)
#define BRPHY_CL45DEV7_AN_LPA_LP_100BASE_T4_CAPABLE_SHIFT (9U)
#define BRPHY_CL45DEV7_AN_LPA_LP_100BASE_TX_FULL_DUPLEX_CAPABLE_MASK (0x100U)
#define BRPHY_CL45DEV7_AN_LPA_LP_100BASE_TX_FULL_DUPLEX_CAPABLE_SHIFT (8U)
#define BRPHY_CL45DEV7_AN_LPA_LP_100BASE_TX_HALF_DUPLEX_CAPABLE_MASK (0x80U)
#define BRPHY_CL45DEV7_AN_LPA_LP_100BASE_TX_HALF_DUPLEX_CAPABLE_SHIFT (7U)
#define BRPHY_CL45DEV7_AN_LPA_LP_10BASE_T_FULL_DUPLEX_CAPABLE_MASK (0x40U)
#define BRPHY_CL45DEV7_AN_LPA_LP_10BASE_T_FULL_DUPLEX_CAPABLE_SHIFT (6U)
#define BRPHY_CL45DEV7_AN_LPA_LP_10BASE_T_HALF_DUPLEX_CAPABLE_MASK (0x20U)
#define BRPHY_CL45DEV7_AN_LPA_LP_10BASE_T_HALF_DUPLEX_CAPABLE_SHIFT (5U)
#define BRPHY_CL45DEV7_AN_LPA_LP_PROTOCOL_SELECTOR_MASK (0x1fU)
#define BRPHY_CL45DEV7_AN_LPA_LP_PROTOCOL_SELECTOR_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_AN_XNPA_TYPE;
#define BRPHY_CL45DEV7_AN_XNPA_NEXT_PAGE_MASK (0x8000U)
#define BRPHY_CL45DEV7_AN_XNPA_NEXT_PAGE_SHIFT (15U)
#define BRPHY_CL45DEV7_AN_XNPA_MESSAGE_PAGE_MASK (0x2000U)
#define BRPHY_CL45DEV7_AN_XNPA_MESSAGE_PAGE_SHIFT (13U)
#define BRPHY_CL45DEV7_AN_XNPA_ACKNOWLEDGE_2_MASK (0x1000U)
#define BRPHY_CL45DEV7_AN_XNPA_ACKNOWLEDGE_2_SHIFT (12U)
#define BRPHY_CL45DEV7_AN_XNPA_TOGGLE_MASK (0x800U)
#define BRPHY_CL45DEV7_AN_XNPA_TOGGLE_SHIFT (11U)
#define BRPHY_CL45DEV7_AN_XNPA_UNFORMATTED_CODE_FIELD_MASK (0x7ffU)
#define BRPHY_CL45DEV7_AN_XNPA_UNFORMATTED_CODE_FIELD_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_AN_XNPB_TYPE;
#define BRPHY_CL45DEV7_AN_XNPB_UNFORMATTED_CODE_FIELD1_MASK (0xffffU)
#define BRPHY_CL45DEV7_AN_XNPB_UNFORMATTED_CODE_FIELD1_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_AN_XNPC_TYPE;
#define BRPHY_CL45DEV7_AN_XNPC_UNFORMATTED_CODE_FIELD2_MASK (0xffffU)
#define BRPHY_CL45DEV7_AN_XNPC_UNFORMATTED_CODE_FIELD2_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_LP_XNPA_TYPE;
#define BRPHY_CL45DEV7_LP_XNPA_NEXT_PAGE_MASK (0x8000U)
#define BRPHY_CL45DEV7_LP_XNPA_NEXT_PAGE_SHIFT (15U)
#define BRPHY_CL45DEV7_LP_XNPA_ACKNOWLEDGE_MASK (0x4000U)
#define BRPHY_CL45DEV7_LP_XNPA_ACKNOWLEDGE_SHIFT (14U)
#define BRPHY_CL45DEV7_LP_XNPA_MESSAGE_PAGE_MASK (0x2000U)
#define BRPHY_CL45DEV7_LP_XNPA_MESSAGE_PAGE_SHIFT (13U)
#define BRPHY_CL45DEV7_LP_XNPA_ACKNOWLEDGE_2_MASK (0x1000U)
#define BRPHY_CL45DEV7_LP_XNPA_ACKNOWLEDGE_2_SHIFT (12U)
#define BRPHY_CL45DEV7_LP_XNPA_TOGGLE_MASK (0x800U)
#define BRPHY_CL45DEV7_LP_XNPA_TOGGLE_SHIFT (11U)
#define BRPHY_CL45DEV7_LP_XNPA_UNFORMATTED_CODE_FIELD_MASK (0x7ffU)
#define BRPHY_CL45DEV7_LP_XNPA_UNFORMATTED_CODE_FIELD_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_LP_XNPB_TYPE;
#define BRPHY_CL45DEV7_LP_XNPB_UNFORMATTED_CODE_FIELD1_MASK (0xffffU)
#define BRPHY_CL45DEV7_LP_XNPB_UNFORMATTED_CODE_FIELD1_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_LP_XNPC_TYPE;
#define BRPHY_CL45DEV7_LP_XNPC_UNFORMATTED_CODE_FIELD2_MASK (0xffffU)
#define BRPHY_CL45DEV7_LP_XNPC_UNFORMATTED_CODE_FIELD2_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_TENG_AN_CTRL_TYPE;
#define BRPHY_CL45DEV7_TENG_AN_CTRL_MSTR_SLV_MAN_CONFIG_EN_MASK (0x8000U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_MSTR_SLV_MAN_CONFIG_EN_SHIFT (15U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_MSTR_SLV_CONFIG_VAL_MASK (0x4000U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_MSTR_SLV_CONFIG_VAL_SHIFT (14U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_PORT_TYPE_MASK (0x2000U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_PORT_TYPE_SHIFT (13U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_PHY_10GBASE_T_ABLE_MASK (0x1000U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_PHY_10GBASE_T_ABLE_SHIFT (12U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_PHY_5GBASE_T_ABLE_MASK (0x100U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_PHY_5GBASE_T_ABLE_SHIFT (8U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_PHY_2P5GBASE_T_ABLE_MASK (0x80U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_PHY_2P5GBASE_T_ABLE_SHIFT (7U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_FAST_RETRAIN_CAPABLE_5G_MASK (0x40U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_FAST_RETRAIN_CAPABLE_5G_SHIFT (6U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_FAST_RETRAIN_CAPABLE_2P5G_MASK (0x20U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_FAST_RETRAIN_CAPABLE_2P5G_SHIFT (5U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_PMA_TRAIN_RST_SEQ_MASK (0x4U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_PMA_TRAIN_RST_SEQ_SHIFT (2U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_FAST_RETRAIN_CAPABLE_10G_MASK (0x2U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_FAST_RETRAIN_CAPABLE_10G_SHIFT (1U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_LOOP_TIMING_ABLE_MASK (0x1U)
#define BRPHY_CL45DEV7_TENG_AN_CTRL_LD_LOOP_TIMING_ABLE_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_TENG_AN_STAT_TYPE;
#define BRPHY_CL45DEV7_TENG_AN_STAT_MSTR_SLV_CONFIG_FAULT_MASK (0x8000U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_MSTR_SLV_CONFIG_FAULT_SHIFT (15U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_MSTR_SLV_CONFIG_RES_MASK (0x4000U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_MSTR_SLV_CONFIG_RES_SHIFT (14U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LOCAL_RCVR_STAT_MASK (0x2000U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LOCAL_RCVR_STAT_SHIFT (13U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_REMOTE_RCVR_STAT_MASK (0x1000U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_REMOTE_RCVR_STAT_SHIFT (12U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_PHY_10GBASE_T_ABLE_MASK (0x800U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_PHY_10GBASE_T_ABLE_SHIFT (11U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_LOOP_TIMING_ABLE_MASK (0x400U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_LOOP_TIMING_ABLE_SHIFT (10U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_PMA_TRAIN_RST_REQ_MASK (0x200U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_PMA_TRAIN_RST_REQ_SHIFT (9U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_PHY_5GBASE_T_ABLE_MASK (0x40U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_PHY_5GBASE_T_ABLE_SHIFT (6U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_PHY_2P5GBASE_T_ABLE_MASK (0x20U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_PHY_2P5GBASE_T_ABLE_SHIFT (5U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_FAST_RETRAIN_CAPABLE_5G_MASK (0x10U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_FAST_RETRAIN_CAPABLE_5G_SHIFT (4U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_FAST_RETRAIN_CAPABLE_2P5G_MASK (0x8U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_FAST_RETRAIN_CAPABLE_2P5G_SHIFT (3U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_FAST_RETRAIN_CAPABLE_10G_MASK (0x2U)
#define BRPHY_CL45DEV7_TENG_AN_STAT_LP_FAST_RETRAIN_CAPABLE_10G_SHIFT (1U)




typedef uint16_t BRPHY_CL45DEV7_EEE_ADV_TYPE;
#define BRPHY_CL45DEV7_EEE_ADV_PHY_10GBASE_KR_EEE_MASK (0x40U)
#define BRPHY_CL45DEV7_EEE_ADV_PHY_10GBASE_KR_EEE_SHIFT (6U)
#define BRPHY_CL45DEV7_EEE_ADV_PHY_10GBASE_KX4_EEE_MASK (0x20U)
#define BRPHY_CL45DEV7_EEE_ADV_PHY_10GBASE_KX4_EEE_SHIFT (5U)
#define BRPHY_CL45DEV7_EEE_ADV_PHY_10GBASE_T_EEE_MASK (0x8U)
#define BRPHY_CL45DEV7_EEE_ADV_PHY_10GBASE_T_EEE_SHIFT (3U)
#define BRPHY_CL45DEV7_EEE_ADV_PHY_1000BASE_T_EEE_MASK (0x4U)
#define BRPHY_CL45DEV7_EEE_ADV_PHY_1000BASE_T_EEE_SHIFT (2U)
#define BRPHY_CL45DEV7_EEE_ADV_PHY_100BASE_T_EEE_MASK (0x2U)
#define BRPHY_CL45DEV7_EEE_ADV_PHY_100BASE_T_EEE_SHIFT (1U)




typedef uint16_t BRPHY_CL45DEV7_EEE_LP_ADV_TYPE;
#define BRPHY_CL45DEV7_EEE_LP_ADV_PHY_10GBASE_KR_EEE_MASK (0x40U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_PHY_10GBASE_KR_EEE_SHIFT (6U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_PHY_10GBASE_KX4_EEE_MASK (0x20U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_PHY_10GBASE_KX4_EEE_SHIFT (5U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_PHY_10GBASE_T_EEE_MASK (0x8U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_PHY_10GBASE_T_EEE_SHIFT (3U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_PHY_1000BASE_T_EEE_MASK (0x4U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_PHY_1000BASE_T_EEE_SHIFT (2U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_PHY_100BASE_T_EEE_MASK (0x2U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_PHY_100BASE_T_EEE_SHIFT (1U)




typedef uint16_t BRPHY_CL45DEV7_EEE_ADV_2_TYPE;
#define BRPHY_CL45DEV7_EEE_ADV_2_PHY_5GBASE_T_EEE_MASK (0x2U)
#define BRPHY_CL45DEV7_EEE_ADV_2_PHY_5GBASE_T_EEE_SHIFT (1U)
#define BRPHY_CL45DEV7_EEE_ADV_2_PHY_2P5GBASE_T_EEE_MASK (0x1U)
#define BRPHY_CL45DEV7_EEE_ADV_2_PHY_2P5GBASE_T_EEE_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_EEE_LP_ADV_2_TYPE;
#define BRPHY_CL45DEV7_EEE_LP_ADV_2_PHY_5GBASE_T_EEE_MASK (0x2U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_2_PHY_5GBASE_T_EEE_SHIFT (1U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_2_PHY_2P5GBASE_T_EEE_MASK (0x1U)
#define BRPHY_CL45DEV7_EEE_LP_ADV_2_PHY_2P5GBASE_T_EEE_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_MGAC2_TYPE;
#define BRPHY_CL45DEV7_MGAC2_LD_2P5GBASE_T_THP_BYPASS_REQUEST_MASK (0x8U)
#define BRPHY_CL45DEV7_MGAC2_LD_2P5GBASE_T_THP_BYPASS_REQUEST_SHIFT (3U)
#define BRPHY_CL45DEV7_MGAC2_LD_5GBASE_T_THP_BYPASS_REQUEST_MASK (0x4U)
#define BRPHY_CL45DEV7_MGAC2_LD_5GBASE_T_THP_BYPASS_REQUEST_SHIFT (2U)




typedef uint16_t BRPHY_CL45DEV7_MGAS2_TYPE;
#define BRPHY_CL45DEV7_MGAS2_LP_2P5GBASE_T_THP_BYPASS_REQUEST_MASK (0x8U)
#define BRPHY_CL45DEV7_MGAS2_LP_2P5GBASE_T_THP_BYPASS_REQUEST_SHIFT (3U)
#define BRPHY_CL45DEV7_MGAS2_LP_5GBASE_T_THP_BYPASS_REQUEST_MASK (0x4U)
#define BRPHY_CL45DEV7_MGAS2_LP_5GBASE_T_THP_BYPASS_REQUEST_SHIFT (2U)




typedef uint16_t BRPHY_CL45DEV7_AB1AC_TYPE;
#define BRPHY_CL45DEV7_AB1AC_AUTONEG_RESET_MASK (0x8000U)
#define BRPHY_CL45DEV7_AB1AC_AUTONEG_RESET_SHIFT (15U)
#define BRPHY_CL45DEV7_AB1AC_AUTONEG_ENABLE_MASK (0x1000U)
#define BRPHY_CL45DEV7_AB1AC_AUTONEG_ENABLE_SHIFT (12U)
#define BRPHY_CL45DEV7_AB1AC_RESTART_AUTO_NEGOTIATION_MASK (0x200U)
#define BRPHY_CL45DEV7_AB1AC_RESTART_AUTO_NEGOTIATION_SHIFT (9U)




typedef uint16_t BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_TYPE;
#define BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_PAGE_RECEIVED_MASK (0x40U)
#define BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_PAGE_RECEIVED_SHIFT (6U)
#define BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_AUTONEG_COMPLETE_MASK (0x20U)
#define BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_AUTONEG_COMPLETE_SHIFT (5U)
#define BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_REMOTE_FAULT_MASK (0x10U)
#define BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_REMOTE_FAULT_SHIFT (4U)
#define BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_AUTONEG_ABILITY_MASK (0x8U)
#define BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_AUTONEG_ABILITY_SHIFT (3U)
#define BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_LINK_STATUS_MASK (0x4U)
#define BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_LINK_STATUS_SHIFT (2U)




typedef uint16_t BRPHY_CL45DEV7_B1AAR0_TYPE;
#define BRPHY_CL45DEV7_B1AAR0_NEXT_PAGE_MASK (0x8000U)
#define BRPHY_CL45DEV7_B1AAR0_NEXT_PAGE_SHIFT (15U)
#define BRPHY_CL45DEV7_B1AAR0_ACKNOWLEDGE_MASK (0x4000U)
#define BRPHY_CL45DEV7_B1AAR0_ACKNOWLEDGE_SHIFT (14U)
#define BRPHY_CL45DEV7_B1AAR0_REMOTE_FAULT_MASK (0x2000U)
#define BRPHY_CL45DEV7_B1AAR0_REMOTE_FAULT_SHIFT (13U)
#define BRPHY_CL45DEV7_B1AAR0_FORCE_MASTER_SLAVE_MASK (0x1000U)
#define BRPHY_CL45DEV7_B1AAR0_FORCE_MASTER_SLAVE_SHIFT (12U)
#define BRPHY_CL45DEV7_B1AAR0_PAUSE_CAPABILITIES_MASK (0xc00U)
#define BRPHY_CL45DEV7_B1AAR0_PAUSE_CAPABILITIES_SHIFT (10U)
#define BRPHY_CL45DEV7_B1AAR0_ECHOED_NONCE_FIELD_MASK (0x3e0U)
#define BRPHY_CL45DEV7_B1AAR0_ECHOED_NONCE_FIELD_SHIFT (5U)
#define BRPHY_CL45DEV7_B1AAR0_SELECTOR_FIELD_MASK (0x1fU)
#define BRPHY_CL45DEV7_B1AAR0_SELECTOR_FIELD_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_B1AAR1_TYPE;
#define BRPHY_CL45DEV7_B1AAR1_D31_D24_MASK (0xff00U)
#define BRPHY_CL45DEV7_B1AAR1_D31_D24_SHIFT (8U)
#define BRPHY_CL45DEV7_B1AAR1_ADVERISE_1000BASE_T1_MASK (0x80U)
#define BRPHY_CL45DEV7_B1AAR1_ADVERISE_1000BASE_T1_SHIFT (7U)
#define BRPHY_CL45DEV7_B1AAR1_D22_MASK (0x40U)
#define BRPHY_CL45DEV7_B1AAR1_D22_SHIFT (6U)
#define BRPHY_CL45DEV7_B1AAR1_ADVERISE_100BASE_T1_MASK (0x20U)
#define BRPHY_CL45DEV7_B1AAR1_ADVERISE_100BASE_T1_SHIFT (5U)
#define BRPHY_CL45DEV7_B1AAR1_MASTER_SLAVE_MASK (0x10U)
#define BRPHY_CL45DEV7_B1AAR1_MASTER_SLAVE_SHIFT (4U)
#define BRPHY_CL45DEV7_B1AAR1_TRANSMITTED_NONCE_FIELD_MASK (0xfU)
#define BRPHY_CL45DEV7_B1AAR1_TRANSMITTED_NONCE_FIELD_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_BASET1_AN_ADVERTISEMENT_REG2_TYPE;
#define BRPHY_CL45DEV7_BASET1_AN_ADVERTISEMENT_REG2_D47_D32_MASK (0xffffU)
#define BRPHY_CL45DEV7_BASET1_AN_ADVERTISEMENT_REG2_D47_D32_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_BASET1_AN_LP_BASE_PAGE_ABILITY_REG0_TYPE;
#define BRPHY_CL45DEV7_BASET1_AN_LP_BASE_PAGE_ABILITY_REG0_D15_D0_MASK (0xffffU)
#define BRPHY_CL45DEV7_BASET1_AN_LP_BASE_PAGE_ABILITY_REG0_D15_D0_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_B1ALBPAR1_TYPE;
#define BRPHY_CL45DEV7_B1ALBPAR1_D31_D16_MASK (0xffffU)
#define BRPHY_CL45DEV7_B1ALBPAR1_D31_D16_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_B1ALBPAR2_TYPE;
#define BRPHY_CL45DEV7_B1ALBPAR2_D47_D32_MASK (0xffffU)
#define BRPHY_CL45DEV7_B1ALBPAR2_D47_D32_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_B1ANPTR0_TYPE;
#define BRPHY_CL45DEV7_B1ANPTR0_NEXT_PAGE_MASK (0x8000U)
#define BRPHY_CL45DEV7_B1ANPTR0_NEXT_PAGE_SHIFT (15U)
#define BRPHY_CL45DEV7_B1ANPTR0_MESSAGE_PAGE_MASK (0x2000U)
#define BRPHY_CL45DEV7_B1ANPTR0_MESSAGE_PAGE_SHIFT (13U)
#define BRPHY_CL45DEV7_B1ANPTR0_ACKNOWLEDGE2_MASK (0x1000U)
#define BRPHY_CL45DEV7_B1ANPTR0_ACKNOWLEDGE2_SHIFT (12U)
#define BRPHY_CL45DEV7_B1ANPTR0_TOGGLE_MASK (0x800U)
#define BRPHY_CL45DEV7_B1ANPTR0_TOGGLE_SHIFT (11U)
#define BRPHY_CL45DEV7_B1ANPTR0_MESSAGE_UNFORMATTED_CODE_FIELD_MASK (0x7ffU)
#define BRPHY_CL45DEV7_B1ANPTR0_MESSAGE_UNFORMATTED_CODE_FIELD_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_B1ANPTR1_TYPE;
#define BRPHY_CL45DEV7_B1ANPTR1_UNFORMATTED_CODE_FIELD_1_MASK (0xffffU)
#define BRPHY_CL45DEV7_B1ANPTR1_UNFORMATTED_CODE_FIELD_1_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_B1ANPTR2_TYPE;
#define BRPHY_CL45DEV7_B1ANPTR2_UNFORMATTED_CODE_FIELD_2_MASK (0xffffU)
#define BRPHY_CL45DEV7_B1ANPTR2_UNFORMATTED_CODE_FIELD_2_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_B1ALNPAR0_TYPE;
#define BRPHY_CL45DEV7_B1ALNPAR0_NEXT_PAGE_MASK (0x8000U)
#define BRPHY_CL45DEV7_B1ALNPAR0_NEXT_PAGE_SHIFT (15U)
#define BRPHY_CL45DEV7_B1ALNPAR0_ACKNOWLEDGE_MASK (0x4000U)
#define BRPHY_CL45DEV7_B1ALNPAR0_ACKNOWLEDGE_SHIFT (14U)
#define BRPHY_CL45DEV7_B1ALNPAR0_MESSAGE_PAGE_MASK (0x2000U)
#define BRPHY_CL45DEV7_B1ALNPAR0_MESSAGE_PAGE_SHIFT (13U)
#define BRPHY_CL45DEV7_B1ALNPAR0_ACKNOWLEDGE2_MASK (0x1000U)
#define BRPHY_CL45DEV7_B1ALNPAR0_ACKNOWLEDGE2_SHIFT (12U)
#define BRPHY_CL45DEV7_B1ALNPAR0_TOGGLE_MASK (0x800U)
#define BRPHY_CL45DEV7_B1ALNPAR0_TOGGLE_SHIFT (11U)
#define BRPHY_CL45DEV7_B1ALNPAR0_MESSAGE_UNFORMATTED_CODE_FIELD_MASK (0x7ffU)
#define BRPHY_CL45DEV7_B1ALNPAR0_MESSAGE_UNFORMATTED_CODE_FIELD_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_B1ALNPAR1_TYPE;
#define BRPHY_CL45DEV7_B1ALNPAR1_UNFORMATTED_CODE_FIELD_1_MASK (0xffffU)
#define BRPHY_CL45DEV7_B1ALNPAR1_UNFORMATTED_CODE_FIELD_1_SHIFT (0U)




typedef uint16_t BRPHY_CL45DEV7_B1ALNPAR2_TYPE;
#define BRPHY_CL45DEV7_B1ALNPAR2_UNFORMATTED_CODE_FIELD_2_MASK (0xffffU)
#define BRPHY_CL45DEV7_B1ALNPAR2_UNFORMATTED_CODE_FIELD_2_SHIFT (0U)




typedef volatile struct COMP_PACKED sBRPHY_CL45DEV7_RDBType {
    BRPHY_CL45DEV7_AN_CTRL_TYPE an_ctrl; /* OFFSET: 0x0 */
    BRPHY_CL45DEV7_AN_STAT_TYPE an_stat; /* OFFSET: 0x2 */
    BRPHY_CL45DEV7_AN_DEV_ID_LSB_TYPE an_dev_id_lsb; /* OFFSET: 0x4 */
    BRPHY_CL45DEV7_AN_DEV_ID_MSB_TYPE an_dev_id_msb; /* OFFSET: 0x6 */
    BRPHY_CL45DEV7_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x8 */
    BRPHY_CL45DEV7_AN_DEV_IN_PKG_LSB_TYPE an_dev_in_pkg_lsb; /* OFFSET: 0xa */
    BRPHY_CL45DEV7_AN_DEV_IN_PKG_MSB_TYPE an_dev_in_pkg_msb; /* OFFSET: 0xc */
    BRPHY_CL45DEV7_RESERVED_TYPE rsvd1[14]; /* OFFSET: 0xe */
    BRPHY_CL45DEV7_AN_DEV_PKG_ID_LSB_TYPE an_dev_pkg_id_lsb; /* OFFSET: 0x1c */
    BRPHY_CL45DEV7_AN_DEV_PKG_ID_MSB_TYPE an_dev_pkg_id_msb; /* OFFSET: 0x1e */
    BRPHY_CL45DEV7_AN_AD_TYPE an_ad; /* OFFSET: 0x20 */
    BRPHY_CL45DEV7_RESERVED_TYPE rsvd2[4]; /* OFFSET: 0x22 */
    BRPHY_CL45DEV7_AN_LPA_TYPE an_lpa; /* OFFSET: 0x26 */
    BRPHY_CL45DEV7_RESERVED_TYPE rsvd3[4]; /* OFFSET: 0x28 */
    BRPHY_CL45DEV7_AN_XNPA_TYPE an_xnpa; /* OFFSET: 0x2c */
    BRPHY_CL45DEV7_AN_XNPB_TYPE an_xnpb; /* OFFSET: 0x2e */
    BRPHY_CL45DEV7_AN_XNPC_TYPE an_xnpc; /* OFFSET: 0x30 */
    BRPHY_CL45DEV7_LP_XNPA_TYPE lp_xnpa; /* OFFSET: 0x32 */
    BRPHY_CL45DEV7_LP_XNPB_TYPE lp_xnpb; /* OFFSET: 0x34 */
    BRPHY_CL45DEV7_LP_XNPC_TYPE lp_xnpc; /* OFFSET: 0x36 */
    BRPHY_CL45DEV7_RESERVED_TYPE rsvd4[8]; /* OFFSET: 0x38 */
    BRPHY_CL45DEV7_TENG_AN_CTRL_TYPE teng_an_ctrl; /* OFFSET: 0x40 */
    BRPHY_CL45DEV7_TENG_AN_STAT_TYPE teng_an_stat; /* OFFSET: 0x42 */
    BRPHY_CL45DEV7_RESERVED_TYPE rsvd5[52]; /* OFFSET: 0x44 */
    BRPHY_CL45DEV7_EEE_ADV_TYPE eee_adv; /* OFFSET: 0x78 */
    BRPHY_CL45DEV7_EEE_LP_ADV_TYPE eee_lp_adv; /* OFFSET: 0x7a */
    BRPHY_CL45DEV7_EEE_ADV_2_TYPE eee_adv_2; /* OFFSET: 0x7c */
    BRPHY_CL45DEV7_EEE_LP_ADV_2_TYPE eee_lp_adv_2; /* OFFSET: 0x7e */
    BRPHY_CL45DEV7_MGAC2_TYPE multi_gbaset_an_ctrl_2; /* OFFSET: 0x80 */
    BRPHY_CL45DEV7_MGAS2_TYPE multi_gbaset_an_status_2; /* OFFSET: 0x82 */
    BRPHY_CL45DEV7_RESERVED_TYPE rsvd6[892]; /* OFFSET: 0x84 */
    BRPHY_CL45DEV7_AB1AC_TYPE autoneg_baset1_an_control; /* OFFSET: 0x400 */
    BRPHY_CL45DEV7_AUTONEG_BASET1_AN_STATUS_TYPE autoneg_baset1_an_status; /* OFFSET: 0x402 */
    BRPHY_CL45DEV7_B1AAR0_TYPE baset1_an_advertisement_reg0; /* OFFSET: 0x404 */
    BRPHY_CL45DEV7_B1AAR1_TYPE baset1_an_advertisement_reg1; /* OFFSET: 0x406 */
    BRPHY_CL45DEV7_BASET1_AN_ADVERTISEMENT_REG2_TYPE baset1_an_advertisement_reg2; /* OFFSET: 0x408 */
    BRPHY_CL45DEV7_BASET1_AN_LP_BASE_PAGE_ABILITY_REG0_TYPE baset1_an_lp_base_page_ability_reg0; /* OFFSET: 0x40a */
    BRPHY_CL45DEV7_B1ALBPAR1_TYPE baset1_an_lp_base_page_ability_reg1; /* OFFSET: 0x40c */
    BRPHY_CL45DEV7_B1ALBPAR2_TYPE baset1_an_lp_base_page_ability_reg2; /* OFFSET: 0x40e */
    BRPHY_CL45DEV7_B1ANPTR0_TYPE baset1_an_next_page_transmit_reg0; /* OFFSET: 0x410 */
    BRPHY_CL45DEV7_B1ANPTR1_TYPE baset1_an_next_page_transmit_reg1; /* OFFSET: 0x412 */
    BRPHY_CL45DEV7_B1ANPTR2_TYPE baset1_an_next_page_transmit_reg2; /* OFFSET: 0x414 */
    BRPHY_CL45DEV7_B1ALNPAR0_TYPE baset1_an_lp_next_page_ability_reg0; /* OFFSET: 0x416 */
    BRPHY_CL45DEV7_B1ALNPAR1_TYPE baset1_an_lp_next_page_ability_reg1; /* OFFSET: 0x418 */
    BRPHY_CL45DEV7_B1ALNPAR2_TYPE baset1_an_lp_next_page_ability_reg2; /* OFFSET: 0x41a */
} BRPHY_CL45DEV7_RDBType;


#define BRPHY0_CL45DEV7_BASE            (0x4A4E0000UL)

#define BRPHY1_CL45DEV7_BASE            (0x494E0000UL)

#define BRPHY2_CL45DEV7_BASE            (0x498E0000UL)

#define BRPHY3_CL45DEV7_BASE            (0x49CE0000UL)

#define BRPHY4_CL45DEV7_BASE            (0x4A0E0000UL)



#define BRPHY_CL45DEV7_MAX_HW_ID        (5UL)


#define BRPHY_CL45DEV7_AN_AD_LD_PROTOCOL_SELECTOR_VALUE  (0x1U)


#define BRPHY_CL45DEV7_B1AAR0_SELECTOR_FIELD_VALUE  (0x1)


#define BRPHY0_CL45DEV7_CTRL_BASE       (BRPHY0_CL45DEV7_BASE)


#define BRPHY1_CL45DEV7_CTRL_BASE       (BRPHY1_CL45DEV7_BASE)


#define BRPHY2_CL45DEV7_CTRL_BASE       (BRPHY2_CL45DEV7_BASE)


#define BRPHY3_CL45DEV7_CTRL_BASE       (BRPHY3_CL45DEV7_BASE)


#define BRPHY4_CL45DEV7_CTRL_BASE       (BRPHY4_CL45DEV7_BASE)

#endif /* BRPHY_CL45DEV7_RDB_H */
