/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy1gv2_autonegieee_rdb.h
    @brief RDB File for BRPHY1GV2_AUTONEGIEEE

    @version Orion_A0_20201104_SWDEV
*/

#ifndef BRPHY1GV2_AUTONEGIEEE_RDB_H
#define BRPHY1GV2_AUTONEGIEEE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t BRPHY1GV2_AUTONEGIEEE_RESERVED_TYPE;




typedef uint16_t BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_TYPE;
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_MSTR_SLV_CONFIG_FAULT_MASK (0x8000U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_MSTR_SLV_CONFIG_FAULT_SHIFT (15U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_MSTR_SLV_CONFIG_RES_MASK (0x4000U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_MSTR_SLV_CONFIG_RES_SHIFT (14U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LOCAL_RCVR_STAT_MASK (0x2000U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LOCAL_RCVR_STAT_SHIFT (13U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_REMOTE_RCVR_STAT_MASK (0x1000U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_REMOTE_RCVR_STAT_SHIFT (12U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LP_PHY_10GBASE_T_ABLE_MASK (0x800U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LP_PHY_10GBASE_T_ABLE_SHIFT (11U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LP_LOOP_TIMING_ABLE_MASK (0x400U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LP_LOOP_TIMING_ABLE_SHIFT (10U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LP_PMA_TRAIN_RST_REQ_MASK (0x200U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LP_PMA_TRAIN_RST_REQ_SHIFT (9U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LP_PHY_5GBASE_T_ABLE_MASK (0x40U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LP_PHY_5GBASE_T_ABLE_SHIFT (6U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LP_PHY_2P5GBASE_T_ABLE_MASK (0x20U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LP_PHY_2P5GBASE_T_ABLE_SHIFT (5U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LFRC5_MASK (0x10U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LFRC5_SHIFT (4U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LFRC25_MASK (0x8U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LFRC25_SHIFT (3U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LFRC10_MASK (0x2U)
#define BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_LFRC10_SHIFT (1U)




typedef uint16_t BRPHY1GV2_AUTONEGIEEE_AB1AC_TYPE;
#define BRPHY1GV2_AUTONEGIEEE_AB1AC_AUTONEG_RESET_MASK (0x8000U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AC_AUTONEG_RESET_SHIFT (15U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AC_AUTONEG_ENABLE_MASK (0x1000U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AC_AUTONEG_ENABLE_SHIFT (12U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AC_RESTART_AUTO_NEGOTIATION_MASK (0x200U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AC_RESTART_AUTO_NEGOTIATION_SHIFT (9U)




typedef uint16_t BRPHY1GV2_AUTONEGIEEE_AB1AS_TYPE;
#define BRPHY1GV2_AUTONEGIEEE_AB1AS_PAGE_RECEIVED_MASK (0x40U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AS_PAGE_RECEIVED_SHIFT (6U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AS_AUTONEG_COMPLETE_MASK (0x20U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AS_AUTONEG_COMPLETE_SHIFT (5U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AS_REMOTE_FAULT_MASK (0x10U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AS_REMOTE_FAULT_SHIFT (4U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AS_AUTONEG_ABILITY_MASK (0x8U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AS_AUTONEG_ABILITY_SHIFT (3U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AS_LINK_STATUS_MASK (0x4U)
#define BRPHY1GV2_AUTONEGIEEE_AB1AS_LINK_STATUS_SHIFT (2U)




typedef uint16_t BRPHY1GV2_AUTONEGIEEE_B1AAR0_TYPE;
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_NEXT_PAGE_MASK (0x8000U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_NEXT_PAGE_SHIFT (15U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_ACKNOWLEDGE_MASK (0x4000U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_ACKNOWLEDGE_SHIFT (14U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_REMOTE_FAULT_MASK (0x2000U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_REMOTE_FAULT_SHIFT (13U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_FORCE_MASTER_SLAVE_MASK (0x1000U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_FORCE_MASTER_SLAVE_SHIFT (12U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_PAUSE_CAPABILITIES_MASK (0xc00U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_PAUSE_CAPABILITIES_SHIFT (10U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_ECHOED_NONCE_FIELD_MASK (0x3e0U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_ECHOED_NONCE_FIELD_SHIFT (5U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_SELECTOR_FIELD_MASK (0x1fU)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR0_SELECTOR_FIELD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEGIEEE_B1AAR1_TYPE;
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_D31_D24_MASK (0xff00U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_D31_D24_SHIFT (8U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_ADVERISE_1000BASE_T1_MASK (0x80U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_ADVERISE_1000BASE_T1_SHIFT (7U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_D22_MASK (0x40U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_D22_SHIFT (6U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_ADVERISE_100BASE_T1_MASK (0x20U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_ADVERISE_100BASE_T1_SHIFT (5U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_MASTER_SLAVE_MASK (0x10U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_MASTER_SLAVE_SHIFT (4U)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_TRANSMITTED_NONCE_FIELD_MASK (0xfU)
#define BRPHY1GV2_AUTONEGIEEE_B1AAR1_TRANSMITTED_NONCE_FIELD_SHIFT (0U)




typedef uint16_t BRPHY1GV2_AUTONEGIEEE_ATR2_TYPE;
#define BRPHY1GV2_AUTONEGIEEE_ATR2_MR_AUTONEG_COMPLETE_MASK (0x8000U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_MR_AUTONEG_COMPLETE_SHIFT (15U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_AUTONEG_WIRESPEED_COUNT_MASK (0x7000U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_AUTONEG_WIRESPEED_COUNT_SHIFT (12U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_AUTONEG_WIRESPEED_DOWNGRADE_MASK (0x800U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_AUTONEG_WIRESPEED_DOWNGRADE_SHIFT (11U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_AUTONEG_LINK_GOOD_CHECK_MASK (0x400U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_AUTONEG_LINK_GOOD_CHECK_SHIFT (10U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_CONFIGURATION_FAULT_MASK (0x200U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_CONFIGURATION_FAULT_SHIFT (9U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_MASTER_SLAVE_MASK (0x100U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_MASTER_SLAVE_SHIFT (8U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_ASMCS_MASK (0xf0U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_ASMCS_SHIFT (4U)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_HIGHEST_COMMON_DENOMINATOR_MASK (0xfU)
#define BRPHY1GV2_AUTONEGIEEE_ATR2_HIGHEST_COMMON_DENOMINATOR_SHIFT (0U)




typedef volatile struct COMP_PACKED sBRPHY1GV2_AUTONEGIEEE_RDBType {
    BRPHY1GV2_AUTONEGIEEE_RESERVED_TYPE rsvd0[66]; /* OFFSET: 0x0 */
    BRPHY1GV2_AUTONEGIEEE_TENG_AN_STAT_TYPE teng_an_stat; /* OFFSET: 0x42 */
    BRPHY1GV2_AUTONEGIEEE_RESERVED_TYPE rsvd1[956]; /* OFFSET: 0x44 */
    BRPHY1GV2_AUTONEGIEEE_AB1AC_TYPE autoneg_baset1_an_control; /* OFFSET: 0x400 */
    BRPHY1GV2_AUTONEGIEEE_AB1AS_TYPE autoneg_baset1_an_status; /* OFFSET: 0x402 */
    BRPHY1GV2_AUTONEGIEEE_B1AAR0_TYPE baset1_an_advertisement_reg0; /* OFFSET: 0x404 */
    BRPHY1GV2_AUTONEGIEEE_B1AAR1_TYPE baset1_an_advertisement_reg1; /* OFFSET: 0x406 */
    BRPHY1GV2_AUTONEGIEEE_RESERVED_TYPE rsvd2[64764]; /* OFFSET: 0x408 */
    BRPHY1GV2_AUTONEGIEEE_ATR2_TYPE autoneg_test_reg2; /* OFFSET: 0x10104 */
    BRPHY1GV2_AUTONEGIEEE_RESERVED_TYPE rsvd3[30]; /* OFFSET: 0x10106 */
} BRPHY1GV2_AUTONEGIEEE_RDBType;


#define BRPHY1GV2_AUTONEGIEEE_BASE      (0x490E0000UL)



#define BRPHY1GV2_AUTONEGIEEE_MAX_HW_ID  (1UL)


#define BRPHY1GV2_AUTONEGIEEE_TESTREG2_HCD_LEGACY_100BASET1  (0x9U)


#define BRPHY1GV2_AUTONEGIEEE_TESTREG2_HCD_1000BASET1  (0x2U)


#define BRPHY1GV2_AUTONEGIEEE_TESTREG2_HCD_100BASET1  (0x1U)


#define BRPHY1GV2_AUTONEGIEEE_TESTREG2_HCD_INPROGRESS  (0x0U)


#define BRPHY1GV2_AUTONEGIEEE_ADVREG0_SELECTOR_VAL  (0x1U)

#endif /* BRPHY1GV2_AUTONEGIEEE_RDB_H */
