/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy_eoc_rdb.h
    @brief RDB File for BRPHY_EOC

    @version Orion_A0_20201104_SWDEV
*/

#ifndef BRPHY_EOC_RDB_H
#define BRPHY_EOC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t BRPHY_EOC_EXP90_TYPE;
#define BRPHY_EOC_EXP90_DIG_HPF_EN_MASK (0x8000U)
#define BRPHY_EOC_EXP90_DIG_HPF_EN_SHIFT (15U)
#define BRPHY_EOC_EXP90_BR_SCR_STATUS_MASK (0x6000U)
#define BRPHY_EOC_EXP90_BR_SCR_STATUS_SHIFT (13U)
#define BRPHY_EOC_EXP90_BR_ALIGN_STATE_MASK (0x1c00U)
#define BRPHY_EOC_EXP90_BR_ALIGN_STATE_SHIFT (10U)
#define BRPHY_EOC_EXP90_BR_RX_STATE_MASK (0x3c0U)
#define BRPHY_EOC_EXP90_BR_RX_STATE_SHIFT (6U)
#define BRPHY_EOC_EXP90_BR_PCS_STATE_MASK (0x3cU)
#define BRPHY_EOC_EXP90_BR_PCS_STATE_SHIFT (2U)
#define BRPHY_EOC_EXP90_BR_FORCE_LINK_CTL_MASK (0x2U)
#define BRPHY_EOC_EXP90_BR_FORCE_LINK_CTL_SHIFT (1U)
#define BRPHY_EOC_EXP90_BR_EN_MASK (0x1U)
#define BRPHY_EOC_EXP90_BR_EN_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP91_TYPE;
#define BRPHY_EOC_EXP91_DIG_HPF_OV_MASK (0x8000U)
#define BRPHY_EOC_EXP91_DIG_HPF_OV_SHIFT (15U)
#define BRPHY_EOC_EXP91_BR_N_TOGGLE_DIS_OV_MASK (0x4000U)
#define BRPHY_EOC_EXP91_BR_N_TOGGLE_DIS_OV_SHIFT (14U)
#define BRPHY_EOC_EXP91_INV_LRE_GMII_TXC_MASK (0x2000U)
#define BRPHY_EOC_EXP91_INV_LRE_GMII_TXC_SHIFT (13U)
#define BRPHY_EOC_EXP91_AGC_AUTOSTAGING_DIS_MASK (0x1000U)
#define BRPHY_EOC_EXP91_AGC_AUTOSTAGING_DIS_SHIFT (12U)
#define BRPHY_EOC_EXP91_BRPGA_MASK (0xe00U)
#define BRPHY_EOC_EXP91_BRPGA_SHIFT (9U)
#define BRPHY_EOC_EXP91_BRCONFIG_MASK (0x1f0U)
#define BRPHY_EOC_EXP91_BRCONFIG_SHIFT (4U)
#define BRPHY_EOC_EXP91_ACQP_EN_ECO_DIS_MASK (0x8U)
#define BRPHY_EOC_EXP91_ACQP_EN_ECO_DIS_SHIFT (3U)
#define BRPHY_EOC_EXP91_BR_N_TOGGLE_DIS_OV_VAL_MASK (0x4U)
#define BRPHY_EOC_EXP91_BR_N_TOGGLE_DIS_OV_VAL_SHIFT (2U)
#define BRPHY_EOC_EXP91_TXSCR_ZERO_SEED_MASK (0x2U)
#define BRPHY_EOC_EXP91_TXSCR_ZERO_SEED_SHIFT (1U)
#define BRPHY_EOC_EXP91_RXSCR_ZERO_SEED_MASK (0x1U)
#define BRPHY_EOC_EXP91_RXSCR_ZERO_SEED_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP92_TYPE;
#define BRPHY_EOC_EXP92_DLLCONV_OV_EN_MASK (0x8000U)
#define BRPHY_EOC_EXP92_DLLCONV_OV_EN_SHIFT (15U)
#define BRPHY_EOC_EXP92_DLLCONV_OV_VAL_MASK (0x4000U)
#define BRPHY_EOC_EXP92_DLLCONV_OV_VAL_SHIFT (14U)
#define BRPHY_EOC_EXP92_BR_SLAVE_POL_COR_EN_MASK (0x2000U)
#define BRPHY_EOC_EXP92_BR_SLAVE_POL_COR_EN_SHIFT (13U)
#define BRPHY_EOC_EXP92_BR_EDGE_RATE_SEL_MASK (0x1800U)
#define BRPHY_EOC_EXP92_BR_EDGE_RATE_SEL_SHIFT (11U)
#define BRPHY_EOC_EXP92_BR_PCS_RRNOK_POL_EN_MASK (0x400U)
#define BRPHY_EOC_EXP92_BR_PCS_RRNOK_POL_EN_SHIFT (10U)
#define BRPHY_EOC_EXP92_LDS_LNK_CHK_ECO_DIS_MASK (0x200U)
#define BRPHY_EOC_EXP92_LDS_LNK_CHK_ECO_DIS_SHIFT (9U)
#define BRPHY_EOC_EXP92_BR_PCS_POL_EN_MASK (0x100U)
#define BRPHY_EOC_EXP92_BR_PCS_POL_EN_SHIFT (8U)
#define BRPHY_EOC_EXP92_JAB_MON_DIS_MASK (0x80U)
#define BRPHY_EOC_EXP92_JAB_MON_DIS_SHIFT (7U)
#define BRPHY_EOC_EXP92_BR_AGCSID_TMR_EN_MASK (0x40U)
#define BRPHY_EOC_EXP92_BR_AGCSID_TMR_EN_SHIFT (6U)
#define BRPHY_EOC_EXP92_BR_SYM_XSCR_EN_MASK (0x20U)
#define BRPHY_EOC_EXP92_BR_SYM_XSCR_EN_SHIFT (5U)
#define BRPHY_EOC_EXP92_CHK_DELIMITER_MASK (0x10U)
#define BRPHY_EOC_EXP92_CHK_DELIMITER_SHIFT (4U)
#define BRPHY_EOC_EXP92_TX_READ_DLY_MASK (0xcU)
#define BRPHY_EOC_EXP92_TX_READ_DLY_SHIFT (2U)
#define BRPHY_EOC_EXP92_RX_READ_DLY_MASK (0x3U)
#define BRPHY_EOC_EXP92_RX_READ_DLY_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP93_TYPE;
#define BRPHY_EOC_EXP93_LDS_CAP_DOWNGRADE_DIS_MASK (0x8000U)
#define BRPHY_EOC_EXP93_LDS_CAP_DOWNGRADE_DIS_SHIFT (15U)
#define BRPHY_EOC_EXP93_LDS_REORDER_DIS_MASK (0x4000U)
#define BRPHY_EOC_EXP93_LDS_REORDER_DIS_SHIFT (14U)
#define BRPHY_EOC_EXP93_LDS_SIM_MASK (0x2000U)
#define BRPHY_EOC_EXP93_LDS_SIM_SHIFT (13U)
#define BRPHY_EOC_EXP93_LDS_SCR_ON_MASK (0x1000U)
#define BRPHY_EOC_EXP93_LDS_SCR_ON_SHIFT (12U)
#define BRPHY_EOC_EXP93_LDS_PHASE_BYP_MASK (0x800U)
#define BRPHY_EOC_EXP93_LDS_PHASE_BYP_SHIFT (11U)
#define BRPHY_EOC_EXP93_LDS_PHASE_INIT_MASK (0x700U)
#define BRPHY_EOC_EXP93_LDS_PHASE_INIT_SHIFT (8U)
#define BRPHY_EOC_EXP93_LDS_PEAK_THR_MASK (0xffU)
#define BRPHY_EOC_EXP93_LDS_PEAK_THR_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP94_TYPE;
#define BRPHY_EOC_EXP94_LDS_LEN_THR1_MASK (0xff00U)
#define BRPHY_EOC_EXP94_LDS_LEN_THR1_SHIFT (8U)
#define BRPHY_EOC_EXP94_LDS_LEN_THR0_MASK (0xffU)
#define BRPHY_EOC_EXP94_LDS_LEN_THR0_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP95_TYPE;
#define BRPHY_EOC_EXP95_LDS_LEN_THR3_MASK (0xff00U)
#define BRPHY_EOC_EXP95_LDS_LEN_THR3_SHIFT (8U)
#define BRPHY_EOC_EXP95_LDS_LEN_THR2_MASK (0xffU)
#define BRPHY_EOC_EXP95_LDS_LEN_THR2_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP96_TYPE;
#define BRPHY_EOC_EXP96_LDS_TONE_FREQ_MASK (0x8000U)
#define BRPHY_EOC_EXP96_LDS_TONE_FREQ_SHIFT (15U)
#define BRPHY_EOC_EXP96_LDS_EXT_AB_DWNGRD_MASK (0x4000U)
#define BRPHY_EOC_EXP96_LDS_EXT_AB_DWNGRD_SHIFT (14U)
#define BRPHY_EOC_EXP96_LDS_SCAN_FSM_MASK (0x3000U)
#define BRPHY_EOC_EXP96_LDS_SCAN_FSM_SHIFT (12U)
#define BRPHY_EOC_EXP96_CUR_LOC_FNUM_MASK (0xff0U)
#define BRPHY_EOC_EXP96_CUR_LOC_FNUM_SHIFT (4U)
#define BRPHY_EOC_EXP96_LDS_SPD_MASK (0xfU)
#define BRPHY_EOC_EXP96_LDS_SPD_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP97_TYPE;
#define BRPHY_EOC_EXP97_LDS_TX_FSM_H_MASK (0xf000U)
#define BRPHY_EOC_EXP97_LDS_TX_FSM_H_SHIFT (12U)
#define BRPHY_EOC_EXP97_LDS_TX_FSM_L_MASK (0xf00U)
#define BRPHY_EOC_EXP97_LDS_TX_FSM_L_SHIFT (8U)
#define BRPHY_EOC_EXP97_LDS_ARB_FSM_H_MASK (0xf0U)
#define BRPHY_EOC_EXP97_LDS_ARB_FSM_H_SHIFT (4U)
#define BRPHY_EOC_EXP97_LDS_ARB_FSM_L_MASK (0xfU)
#define BRPHY_EOC_EXP97_LDS_ARB_FSM_L_SHIFT (0U)




typedef uint8_t BRPHY_EOC_RESERVED_TYPE;




typedef uint16_t BRPHY_EOC_EXP99_TYPE;
#define BRPHY_EOC_EXP99_LDS_PGACTRL_MASK (0xfc00U)
#define BRPHY_EOC_EXP99_LDS_PGACTRL_SHIFT (10U)
#define BRPHY_EOC_EXP99_TXDIS_TMR_OPT_MASK (0x380U)
#define BRPHY_EOC_EXP99_TXDIS_TMR_OPT_SHIFT (7U)
#define BRPHY_EOC_EXP99_LNK_TMR_OPT_MASK (0x70U)
#define BRPHY_EOC_EXP99_LNK_TMR_OPT_SHIFT (4U)
#define BRPHY_EOC_EXP99_BST_TMR_OPT_MASK (0xeU)
#define BRPHY_EOC_EXP99_BST_TMR_OPT_SHIFT (1U)
#define BRPHY_EOC_EXP99_FASTBST_MASK (0x1U)
#define BRPHY_EOC_EXP99_FASTBST_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP9A_TYPE;
#define BRPHY_EOC_EXP9A_LRE_REG_OV_EN_MASK (0x8000U)
#define BRPHY_EOC_EXP9A_LRE_REG_OV_EN_SHIFT (15U)
#define BRPHY_EOC_EXP9A_LRE_REG_OV_VAL_MASK (0x4000U)
#define BRPHY_EOC_EXP9A_LRE_REG_OV_VAL_SHIFT (14U)
#define BRPHY_EOC_EXP9A_LRE_REG_ACCESS_STAT_MASK (0x2000U)
#define BRPHY_EOC_EXP9A_LRE_REG_ACCESS_STAT_SHIFT (13U)
#define BRPHY_EOC_EXP9A_LDS_LINK_CHK_EN_MASK (0x1000U)
#define BRPHY_EOC_EXP9A_LDS_LINK_CHK_EN_SHIFT (12U)
#define BRPHY_EOC_EXP9A_BR_AGC_TAR_OV_EN_MASK (0x800U)
#define BRPHY_EOC_EXP9A_BR_AGC_TAR_OV_EN_SHIFT (11U)
#define BRPHY_EOC_EXP9A_LDS_TIMER_OV_EN_MASK (0x400U)
#define BRPHY_EOC_EXP9A_LDS_TIMER_OV_EN_SHIFT (10U)
#define BRPHY_EOC_EXP9A_BR_LOST_TOKEN_FIX_MASK (0x200U)
#define BRPHY_EOC_EXP9A_BR_LOST_TOKEN_FIX_SHIFT (9U)
#define BRPHY_EOC_EXP9A_DLLCONV_EN_MSTR_MASK (0x100U)
#define BRPHY_EOC_EXP9A_DLLCONV_EN_MSTR_SHIFT (8U)
#define BRPHY_EOC_EXP9A_BR_10M1P_HALFOUT_EN_MASK (0x80U)
#define BRPHY_EOC_EXP9A_BR_10M1P_HALFOUT_EN_SHIFT (7U)
#define BRPHY_EOC_EXP9A_BR_10M2P_HALFOUT_EN_MASK (0x40U)
#define BRPHY_EOC_EXP9A_BR_10M2P_HALFOUT_EN_SHIFT (6U)
#define BRPHY_EOC_EXP9A_BR_HALFOUT_EN_MASK (0x20U)
#define BRPHY_EOC_EXP9A_BR_HALFOUT_EN_SHIFT (5U)
#define BRPHY_EOC_EXP9A_CLK100T_ECO_DIS_MASK (0x10U)
#define BRPHY_EOC_EXP9A_CLK100T_ECO_DIS_SHIFT (4U)
#define BRPHY_EOC_EXP9A_CH_STATUS_MASK (0xfU)
#define BRPHY_EOC_EXP9A_CH_STATUS_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP9B_TYPE;
#define BRPHY_EOC_EXP9B_BR_RATE_OV_MASK (0xe000U)
#define BRPHY_EOC_EXP9B_BR_RATE_OV_SHIFT (13U)
#define BRPHY_EOC_EXP9B_BR_200MBPS_CLK_EN_MASK (0x1000U)
#define BRPHY_EOC_EXP9B_BR_200MBPS_CLK_EN_SHIFT (12U)
#define BRPHY_EOC_EXP9B_BR_TXCLK_EN_MASK (0x800U)
#define BRPHY_EOC_EXP9B_BR_TXCLK_EN_SHIFT (11U)
#define BRPHY_EOC_EXP9B_BR_TXRXICLK_EN_MASK (0x400U)
#define BRPHY_EOC_EXP9B_BR_TXRXICLK_EN_SHIFT (10U)
#define BRPHY_EOC_EXP9B_CLK_1G_DIV20_MASK (0x200U)
#define BRPHY_EOC_EXP9B_CLK_1G_DIV20_SHIFT (9U)
#define BRPHY_EOC_EXP9B_LVL1_PROG_FREQ_DIV_MASK (0x1e0U)
#define BRPHY_EOC_EXP9B_LVL1_PROG_FREQ_DIV_SHIFT (5U)
#define BRPHY_EOC_EXP9B_LVL2_PROG_FREQ_DIV_MASK (0x1eU)
#define BRPHY_EOC_EXP9B_LVL2_PROG_FREQ_DIV_SHIFT (1U)
#define BRPHY_EOC_EXP9B_BR_PLL_CTL_EN_MASK (0x1U)
#define BRPHY_EOC_EXP9B_BR_PLL_CTL_EN_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP9D_TYPE;
#define BRPHY_EOC_EXP9D_BR_IPR_BYPASS_MASK (0x8000U)
#define BRPHY_EOC_EXP9D_BR_IPR_BYPASS_SHIFT (15U)
#define BRPHY_EOC_EXP9D_BR_CLOCK_ON_OV_VAL_MASK (0x4000U)
#define BRPHY_EOC_EXP9D_BR_CLOCK_ON_OV_VAL_SHIFT (14U)
#define BRPHY_EOC_EXP9D_BR_CLOCK_ON_OV_EN_MASK (0x2000U)
#define BRPHY_EOC_EXP9D_BR_CLOCK_ON_OV_EN_SHIFT (13U)
#define BRPHY_EOC_EXP9D_LDS_SD_THR_MASK (0x1f00U)
#define BRPHY_EOC_EXP9D_LDS_SD_THR_SHIFT (8U)
#define BRPHY_EOC_EXP9D_LDS_PEAK_THR_T125_MASK (0xffU)
#define BRPHY_EOC_EXP9D_LDS_PEAK_THR_T125_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP9E_TYPE;
#define BRPHY_EOC_EXP9E_LDS_LEN_THR1_T125_MASK (0xff00U)
#define BRPHY_EOC_EXP9E_LDS_LEN_THR1_T125_SHIFT (8U)
#define BRPHY_EOC_EXP9E_LDS_LEN_THR0_T125_MASK (0xffU)
#define BRPHY_EOC_EXP9E_LDS_LEN_THR0_T125_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXP9F_TYPE;
#define BRPHY_EOC_EXP9F_LDS_LEN_THR3_T125_MASK (0xff00U)
#define BRPHY_EOC_EXP9F_LDS_LEN_THR3_T125_SHIFT (8U)
#define BRPHY_EOC_EXP9F_LDS_LEN_THR2_T125_MASK (0xffU)
#define BRPHY_EOC_EXP9F_LDS_LEN_THR2_T125_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXPA0_TYPE;
#define BRPHY_EOC_EXPA0_EPAGE_SPARE_MASK (0xfffcU)
#define BRPHY_EOC_EXPA0_EPAGE_SPARE_SHIFT (2U)
#define BRPHY_EOC_EXPA0_PAIR_1_250MBPS_MASK (0x2U)
#define BRPHY_EOC_EXPA0_PAIR_1_250MBPS_SHIFT (1U)
#define BRPHY_EOC_EXPA0_PAIR_1_200MBPS_MASK (0x1U)
#define BRPHY_EOC_EXPA0_PAIR_1_200MBPS_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXPA1_TYPE;
#define BRPHY_EOC_EXPA1_LP_EPAGE_SPARE_MASK (0xfffcU)
#define BRPHY_EOC_EXPA1_LP_EPAGE_SPARE_SHIFT (2U)
#define BRPHY_EOC_EXPA1_LP_PAIR_1_250MBPS_MASK (0x2U)
#define BRPHY_EOC_EXPA1_LP_PAIR_1_250MBPS_SHIFT (1U)
#define BRPHY_EOC_EXPA1_LP_PAIR_1_200MBPS_MASK (0x1U)
#define BRPHY_EOC_EXPA1_LP_PAIR_1_200MBPS_SHIFT (0U)




typedef uint16_t BRPHY_EOC_EXPA2_TYPE;
#define BRPHY_EOC_EXPA2_TFREQ_SEL_OV_EN_MASK (0x8000U)
#define BRPHY_EOC_EXPA2_TFREQ_SEL_OV_EN_SHIFT (15U)
#define BRPHY_EOC_EXPA2_TFREQ_SEL_OV_MASK (0x4000U)
#define BRPHY_EOC_EXPA2_TFREQ_SEL_OV_SHIFT (14U)
#define BRPHY_EOC_EXPA2_LOW_FREQ_TONE_MASK (0x2000U)
#define BRPHY_EOC_EXPA2_LOW_FREQ_TONE_SHIFT (13U)
#define BRPHY_EOC_EXPA2_BR_MAXWAIT_CTL_MASK (0x1800U)
#define BRPHY_EOC_EXPA2_BR_MAXWAIT_CTL_SHIFT (11U)
#define BRPHY_EOC_EXPA2_BR_M2S2_TMR_CTL_MASK (0x400U)
#define BRPHY_EOC_EXPA2_BR_M2S2_TMR_CTL_SHIFT (10U)
#define BRPHY_EOC_EXPA2_BR_SKIP_FIFO_FDX_S_MASK (0x200U)
#define BRPHY_EOC_EXPA2_BR_SKIP_FIFO_FDX_S_SHIFT (9U)
#define BRPHY_EOC_EXPA2_BR_SKIP_FIFO_HDX_MASK (0x100U)
#define BRPHY_EOC_EXPA2_BR_SKIP_FIFO_HDX_SHIFT (8U)
#define BRPHY_EOC_EXPA2_BR_PSD_TIMER_CTL_MASK (0xc0U)
#define BRPHY_EOC_EXPA2_BR_PSD_TIMER_CTL_SHIFT (6U)
#define BRPHY_EOC_EXPA2_MAN_PHASE_CK1X_MASK (0x38U)
#define BRPHY_EOC_EXPA2_MAN_PHASE_CK1X_SHIFT (3U)
#define BRPHY_EOC_EXPA2_LDS_PHASE_CK1X_MASK (0x7U)
#define BRPHY_EOC_EXPA2_LDS_PHASE_CK1X_SHIFT (0U)




typedef uint16_t BRPHY_EOC_BR_MISC_CONTROL_STATUS_TYPE;
#define BRPHY_EOC_BR_MISC_CONTROL_STATUS_ENABLE_2ND_FILTER_MASK (0x8000U)
#define BRPHY_EOC_BR_MISC_CONTROL_STATUS_ENABLE_2ND_FILTER_SHIFT (15U)
#define BRPHY_EOC_BR_MISC_CONTROL_STATUS_ENABLE_PR_DATAPATH_MASK (0x4000U)
#define BRPHY_EOC_BR_MISC_CONTROL_STATUS_ENABLE_PR_DATAPATH_SHIFT (14U)
#define BRPHY_EOC_BR_MISC_CONTROL_STATUS_BR_1P_PCS_SOL_MASK (0x7U)
#define BRPHY_EOC_BR_MISC_CONTROL_STATUS_BR_1P_PCS_SOL_SHIFT (0U)




typedef uint16_t BRPHY_EOC_BR_TC10_CTRL_TYPE;
#define BRPHY_EOC_BR_TC10_CTRL_PMS_FASTSIM_MODE_MASK (0x40U)
#define BRPHY_EOC_BR_TC10_CTRL_PMS_FASTSIM_MODE_SHIFT (6U)
#define BRPHY_EOC_BR_TC10_CTRL_PMS_RX_BLOCK_DIS_MASK (0x20U)
#define BRPHY_EOC_BR_TC10_CTRL_PMS_RX_BLOCK_DIS_SHIFT (5U)
#define BRPHY_EOC_BR_TC10_CTRL_CONTI_LP_DIS_MASK (0x10U)
#define BRPHY_EOC_BR_TC10_CTRL_CONTI_LP_DIS_SHIFT (4U)
#define BRPHY_EOC_BR_TC10_CTRL_TX_LPS_OPT_MASK (0xcU)
#define BRPHY_EOC_BR_TC10_CTRL_TX_LPS_OPT_SHIFT (2U)
#define BRPHY_EOC_BR_TC10_CTRL_SEND_Z_DET_OPT_MASK (0x3U)
#define BRPHY_EOC_BR_TC10_CTRL_SEND_Z_DET_OPT_SHIFT (0U)




typedef uint16_t BRPHY_EOC_BR_RSVD_TYPE;




typedef uint16_t BRPHY_EOC_BR250_CTL_TYPE;
#define BRPHY_EOC_BR250_CTL_BR_CURR_RATE_MASK (0xf000U)
#define BRPHY_EOC_BR250_CTL_BR_CURR_RATE_SHIFT (12U)
#define BRPHY_EOC_BR250_CTL_BR_CURR_PAIR_MASK (0xc00U)
#define BRPHY_EOC_BR250_CTL_BR_CURR_PAIR_SHIFT (10U)
#define BRPHY_EOC_BR250_CTL_BR_PAM5_200_SEL_MASK (0x80U)
#define BRPHY_EOC_BR250_CTL_BR_PAM5_200_SEL_SHIFT (7U)
#define BRPHY_EOC_BR250_CTL_LBKTST2_MASK (0x40U)
#define BRPHY_EOC_BR250_CTL_LBKTST2_SHIFT (6U)
#define BRPHY_EOC_BR250_CTL_CONF_GPLL_125_MASK (0x20U)
#define BRPHY_EOC_BR250_CTL_CONF_GPLL_125_SHIFT (5U)
#define BRPHY_EOC_BR250_CTL_RXDV_FIX_DIS_MASK (0x10U)
#define BRPHY_EOC_BR250_CTL_RXDV_FIX_DIS_SHIFT (4U)
#define BRPHY_EOC_BR250_CTL_INTRLV_CTL_MASK (0xcU)
#define BRPHY_EOC_BR250_CTL_INTRLV_CTL_SHIFT (2U)
#define BRPHY_EOC_BR250_CTL_PAIR_CFG_MASK (0x3U)
#define BRPHY_EOC_BR250_CTL_PAIR_CFG_SHIFT (0U)




typedef volatile struct COMP_PACKED sBRPHY_EOC_RDBType {
    BRPHY_EOC_EXP90_TYPE exp90; /* OFFSET: 0x0 */
    BRPHY_EOC_EXP91_TYPE exp91; /* OFFSET: 0x2 */
    BRPHY_EOC_EXP92_TYPE exp92; /* OFFSET: 0x4 */
    BRPHY_EOC_EXP93_TYPE exp93; /* OFFSET: 0x6 */
    BRPHY_EOC_EXP94_TYPE exp94; /* OFFSET: 0x8 */
    BRPHY_EOC_EXP95_TYPE exp95; /* OFFSET: 0xa */
    BRPHY_EOC_EXP96_TYPE exp96; /* OFFSET: 0xc */
    BRPHY_EOC_EXP97_TYPE exp97; /* OFFSET: 0xe */
    BRPHY_EOC_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x10 */
    BRPHY_EOC_EXP99_TYPE exp99; /* OFFSET: 0x12 */
    BRPHY_EOC_EXP9A_TYPE exp9a; /* OFFSET: 0x14 */
    BRPHY_EOC_EXP9B_TYPE exp9b; /* OFFSET: 0x16 */
    BRPHY_EOC_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x18 */
    BRPHY_EOC_EXP9D_TYPE exp9d; /* OFFSET: 0x1a */
    BRPHY_EOC_EXP9E_TYPE exp9e; /* OFFSET: 0x1c */
    BRPHY_EOC_EXP9F_TYPE exp9f; /* OFFSET: 0x1e */
    BRPHY_EOC_EXPA0_TYPE expa0; /* OFFSET: 0x20 */
    BRPHY_EOC_EXPA1_TYPE expa1; /* OFFSET: 0x22 */
    BRPHY_EOC_EXPA2_TYPE expa2; /* OFFSET: 0x24 */
    BRPHY_EOC_BR_MISC_CONTROL_STATUS_TYPE br_misc_control_status; /* OFFSET: 0x26 */
    BRPHY_EOC_BR_TC10_CTRL_TYPE tc10_ctrl; /* OFFSET: 0x28 */
    BRPHY_EOC_BR_RSVD_TYPE expa5; /* OFFSET: 0x2a */
    BRPHY_EOC_BR_RSVD_TYPE expa6; /* OFFSET: 0x2c */
    BRPHY_EOC_BR_RSVD_TYPE expa7; /* OFFSET: 0x2e */
    BRPHY_EOC_RESERVED_TYPE rsvd2[12]; /* OFFSET: 0x30 */
    BRPHY_EOC_BR250_CTL_TYPE br250_ctl; /* OFFSET: 0x3c */
} BRPHY_EOC_RDBType;


#define BRPHY0_BR_CTRL_BASE             (0x4A4F2600UL)

#define BRPHY1_BR_CTRL_BASE             (0x494F2600UL)

#define BRPHY2_BR_CTRL_BASE             (0x498F2600UL)

#define BRPHY3_BR_CTRL_BASE             (0x49CF2600UL)

#define BRPHY4_BR_CTRL_BASE             (0x4A0F2600UL)



#define BRPHY_EOC_MAX_HW_ID             (5UL)


#define BRPHY_BR_CTRL_EXP90_RESET       (0x0000U)


#define BRPHY0_BR_EOC_CTRL_BASE         (BRPHY0_BR_CTRL_BASE)


#define BRPHY1_BR_EOC_CTRL_BASE         (BRPHY1_BR_CTRL_BASE)


#define BRPHY2_BR_EOC_CTRL_BASE         (BRPHY2_BR_CTRL_BASE)


#define BRPHY3_BR_EOC_CTRL_BASE         (BRPHY3_BR_CTRL_BASE)


#define BRPHY4_BR_EOC_CTRL_BASE         (BRPHY4_BR_CTRL_BASE)

#endif /* BRPHY_EOC_RDB_H */
