/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file brphy_cl45ven_rdb.h
    @brief RDB File for BRPHY_CL45VEN

    @version Orion_A0_20201104_SWDEV
*/

#ifndef BRPHY_CL45VEN_RDB_H
#define BRPHY_CL45VEN_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t BRPHY_CL45VEN_RESERVED_TYPE;




typedef uint16_t BRPHY_CL45VEN_ATR2_TYPE;
#define BRPHY_CL45VEN_ATR2_MR_AUTONEG_COMPLETE_MASK (0x8000U)
#define BRPHY_CL45VEN_ATR2_MR_AUTONEG_COMPLETE_SHIFT (15U)
#define BRPHY_CL45VEN_ATR2_AUTONEG_WIRESPEED_COUNT_MASK (0x7000U)
#define BRPHY_CL45VEN_ATR2_AUTONEG_WIRESPEED_COUNT_SHIFT (12U)
#define BRPHY_CL45VEN_ATR2_AUTONEG_WIRESPEED_DOWNGRADE_MASK (0x800U)
#define BRPHY_CL45VEN_ATR2_AUTONEG_WIRESPEED_DOWNGRADE_SHIFT (11U)
#define BRPHY_CL45VEN_ATR2_AUTONEG_LINK_GOOD_CHECK_MASK (0x400U)
#define BRPHY_CL45VEN_ATR2_AUTONEG_LINK_GOOD_CHECK_SHIFT (10U)
#define BRPHY_CL45VEN_ATR2_CONFIGURATION_FAULT_MASK (0x200U)
#define BRPHY_CL45VEN_ATR2_CONFIGURATION_FAULT_SHIFT (9U)
#define BRPHY_CL45VEN_ATR2_MASTER_SLAVE_MASK (0x100U)
#define BRPHY_CL45VEN_ATR2_MASTER_SLAVE_SHIFT (8U)
#define BRPHY_CL45VEN_ATR2_ASMCS_MASK (0xf0U)
#define BRPHY_CL45VEN_ATR2_ASMCS_SHIFT (4U)
#define BRPHY_CL45VEN_ATR2_HIGHEST_COMMON_DENOMINATOR_MASK (0xfU)
#define BRPHY_CL45VEN_ATR2_HIGHEST_COMMON_DENOMINATOR_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_TC10_STATUS_TYPE;
#define BRPHY_CL45VEN_TC10_STATUS_SLP_WUP_STATE_MASK (0x700U)
#define BRPHY_CL45VEN_TC10_STATUS_SLP_WUP_STATE_SHIFT (8U)
#define BRPHY_CL45VEN_TC10_STATUS_WAKEUP_FAIL_STAT_MASK (0x80U)
#define BRPHY_CL45VEN_TC10_STATUS_WAKEUP_FAIL_STAT_SHIFT (7U)
#define BRPHY_CL45VEN_TC10_STATUS_LOC_WAKEUP_STAT_MASK (0x40U)
#define BRPHY_CL45VEN_TC10_STATUS_LOC_WAKEUP_STAT_SHIFT (6U)
#define BRPHY_CL45VEN_TC10_STATUS_WAKEUP_STAT_MASK (0x20U)
#define BRPHY_CL45VEN_TC10_STATUS_WAKEUP_STAT_SHIFT (5U)
#define BRPHY_CL45VEN_TC10_STATUS_INHIBIT_REAL_STAT_MASK (0x10U)
#define BRPHY_CL45VEN_TC10_STATUS_INHIBIT_REAL_STAT_SHIFT (4U)
#define BRPHY_CL45VEN_TC10_STATUS_INHIBIT_STAT_MASK (0x8U)
#define BRPHY_CL45VEN_TC10_STATUS_INHIBIT_STAT_SHIFT (3U)
#define BRPHY_CL45VEN_TC10_STATUS_SLEEP_STAT_MASK (0x4U)
#define BRPHY_CL45VEN_TC10_STATUS_SLEEP_STAT_SHIFT (2U)
#define BRPHY_CL45VEN_TC10_STATUS_SLEEP_FAIL_STAT_MASK (0x2U)
#define BRPHY_CL45VEN_TC10_STATUS_SLEEP_FAIL_STAT_SHIFT (1U)
#define BRPHY_CL45VEN_TC10_STATUS_AFE_WAKEUP_STAT_MASK (0x1U)
#define BRPHY_CL45VEN_TC10_STATUS_AFE_WAKEUP_STAT_SHIFT (0U)




typedef uint16_t BRPHY_CL45VEN_TC10_CONTROL_TYPE;
#define BRPHY_CL45VEN_TC10_CONTROL_TC10_SLEEP_CAP_DISABLE_MASK (0x8000U)
#define BRPHY_CL45VEN_TC10_CONTROL_TC10_SLEEP_CAP_DISABLE_SHIFT (15U)
#define BRPHY_CL45VEN_TC10_CONTROL_STRAP_GO2STNDBY_MASK (0x4000U)
#define BRPHY_CL45VEN_TC10_CONTROL_STRAP_GO2STNDBY_SHIFT (14U)
#define BRPHY_CL45VEN_TC10_CONTROL_RESERVED_MASK (0x3000U)
#define BRPHY_CL45VEN_TC10_CONTROL_RESERVED_SHIFT (12U)
#define BRPHY_CL45VEN_TC10_CONTROL_TC10_FSM_DISABLE_MASK (0x800U)
#define BRPHY_CL45VEN_TC10_CONTROL_TC10_FSM_DISABLE_SHIFT (11U)
#define BRPHY_CL45VEN_TC10_CONTROL_TC10_INTR_EN_MASK (0x400U)
#define BRPHY_CL45VEN_TC10_CONTROL_TC10_INTR_EN_SHIFT (10U)
#define BRPHY_CL45VEN_TC10_CONTROL_TC10_INTR_MASK_MASK (0x3f0U)
#define BRPHY_CL45VEN_TC10_CONTROL_TC10_INTR_MASK_SHIFT (4U)
#define BRPHY_CL45VEN_TC10_CONTROL_WAKEUP_REQ_MASK (0x8U)
#define BRPHY_CL45VEN_TC10_CONTROL_WAKEUP_REQ_SHIFT (3U)
#define BRPHY_CL45VEN_TC10_CONTROL_SLEEPABORT_REQ_MASK (0x4U)
#define BRPHY_CL45VEN_TC10_CONTROL_SLEEPABORT_REQ_SHIFT (2U)
#define BRPHY_CL45VEN_TC10_CONTROL_SLEEP_REQ_MASK (0x2U)
#define BRPHY_CL45VEN_TC10_CONTROL_SLEEP_REQ_SHIFT (1U)
#define BRPHY_CL45VEN_TC10_CONTROL_GO2SLEEP_AUTO_MASK (0x1U)
#define BRPHY_CL45VEN_TC10_CONTROL_GO2SLEEP_AUTO_SHIFT (0U)




typedef volatile struct COMP_PACKED sBRPHY_CL45VEN_RDBType {
    BRPHY_CL45VEN_RESERVED_TYPE rsvd0[260]; /* OFFSET: 0x0 */
    BRPHY_CL45VEN_ATR2_TYPE autoneg_test_reg2; /* OFFSET: 0x104 */
    BRPHY_CL45VEN_RESERVED_TYPE rsvd1[246]; /* OFFSET: 0x106 */
    BRPHY_CL45VEN_TC10_STATUS_TYPE tc10_status; /* OFFSET: 0x1fc */
    BRPHY_CL45VEN_TC10_CONTROL_TYPE tc10_control; /* OFFSET: 0x1fe */
} BRPHY_CL45VEN_RDBType;


#define BRPHY0_CL45VEN_BASE             (0x4A4F0000UL)

#define BRPHY1_CL45VEN_BASE             (0x494F0000UL)

#define BRPHY2_CL45VEN_BASE             (0x498F0000UL)

#define BRPHY3_CL45VEN_BASE             (0x49CF0000UL)

#define BRPHY4_CL45VEN_BASE             (0x4A0F0000UL)



#define BRPHY_CL45VEN_MAX_HW_ID         (5UL)


#define BRPHY0_CL45VEN_CTRL_BASE        (BRPHY0_CL45VEN_BASE)


#define BRPHY1_CL45VEN_CTRL_BASE        (BRPHY1_CL45VEN_BASE)


#define BRPHY2_CL45VEN_CTRL_BASE        (BRPHY2_CL45VEN_BASE)


#define BRPHY3_CL45VEN_CTRL_BASE        (BRPHY3_CL45VEN_BASE)


#define BRPHY4_CL45VEN_CTRL_BASE        (BRPHY4_CL45VEN_BASE)

#endif /* BRPHY_CL45VEN_RDB_H */
