/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file cfg_rdb.h
    @brief RDB File for CFG

    @version Orion_A0_20201104_SWDEV
*/

#ifndef CFG_RDB_H
#define CFG_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t CFG_RESERVED_TYPE;




typedef uint32_t CFG_CPUSYS_MISC_TYPE;
#define CFG_CPUSYS_MISC_M7_CORE_SOFT_RST_MASK (0x80000000UL)
#define CFG_CPUSYS_MISC_M7_CORE_SOFT_RST_SHIFT (31UL)
#define CFG_CPUSYS_MISC_M7_CPU_CLKGATE_EN_MASK (0x40000000UL)
#define CFG_CPUSYS_MISC_M7_CPU_CLKGATE_EN_SHIFT (30UL)
#define CFG_CPUSYS_MISC_MEM_INIT_DONE_CFG_MASK (0x20000000UL)
#define CFG_CPUSYS_MISC_MEM_INIT_DONE_CFG_SHIFT (29UL)
#define CFG_CPUSYS_MISC_ECC_ERR_CLEAR_CFG_MASK (0x10000000UL)
#define CFG_CPUSYS_MISC_ECC_ERR_CLEAR_CFG_SHIFT (28UL)
#define CFG_CPUSYS_MISC_NMI_CLEAR_CFG_MASK (0x8000000UL)
#define CFG_CPUSYS_MISC_NMI_CLEAR_CFG_SHIFT (27UL)
#define CFG_CPUSYS_MISC_CPU_LOCKUP_RST_EN_MASK (0x4000000UL)
#define CFG_CPUSYS_MISC_CPU_LOCKUP_RST_EN_SHIFT (26UL)
#define CFG_CPUSYS_MISC_CPU_SYSRSTREQ_RST_EN_MASK (0x2000000UL)
#define CFG_CPUSYS_MISC_CPU_SYSRSTREQ_RST_EN_SHIFT (25UL)
#define CFG_CPUSYS_MISC_SPARE_24_MASK (0x1000000UL)
#define CFG_CPUSYS_MISC_SPARE_24_SHIFT (24UL)
#define CFG_CPUSYS_MISC_SPI_ACC_IPC_DTCM_DIS_MASK (0x800000UL)
#define CFG_CPUSYS_MISC_SPI_ACC_IPC_DTCM_DIS_SHIFT (23UL)
#define CFG_CPUSYS_MISC_SPEED_UP_MEM_INIT_CFG_MASK (0x400000UL)
#define CFG_CPUSYS_MISC_SPEED_UP_MEM_INIT_CFG_SHIFT (22UL)
#define CFG_CPUSYS_MISC_SER_ACCESS_CTRL_CFG_MASK (0x200000UL)
#define CFG_CPUSYS_MISC_SER_ACCESS_CTRL_CFG_SHIFT (21UL)
#define CFG_CPUSYS_MISC_SPARE_MASK (0x100000UL)
#define CFG_CPUSYS_MISC_SPARE_SHIFT (20UL)
#define CFG_CPUSYS_MISC_M7_ADDR_REMAP_CFG_MASK (0x80000UL)
#define CFG_CPUSYS_MISC_M7_ADDR_REMAP_CFG_SHIFT (19UL)
#define CFG_CPUSYS_MISC_SPARE18TO04_MASK (0x7fff0UL)
#define CFG_CPUSYS_MISC_SPARE18TO04_SHIFT (4UL)
#define CFG_CPUSYS_MISC_NRESET_OV_MASK (0x8UL)
#define CFG_CPUSYS_MISC_NRESET_OV_SHIFT (3UL)
#define CFG_CPUSYS_MISC_NRESET_CFG_MASK (0x4UL)
#define CFG_CPUSYS_MISC_NRESET_CFG_SHIFT (2UL)
#define CFG_CPUSYS_MISC_NSYSPORESET_OV_MASK (0x2UL)
#define CFG_CPUSYS_MISC_NSYSPORESET_OV_SHIFT (1UL)
#define CFG_CPUSYS_MISC_NSYSPORESET_CFG_MASK (0x1UL)
#define CFG_CPUSYS_MISC_NSYSPORESET_CFG_SHIFT (0UL)




typedef uint32_t CFG_TM_0_TYPE;
#define CFG_TM_0_ALL_TM_MASK (0xffffUL)
#define CFG_TM_0_ALL_TM_SHIFT (0UL)




typedef uint32_t CFG_DEBUG_SEL_TYPE;
#define CFG_DEBUG_SEL_MUX_SEL_MASK (0x1eUL)
#define CFG_DEBUG_SEL_MUX_SEL_SHIFT (1UL)
#define CFG_DEBUG_SEL_ENABLE_MASK (0x1UL)
#define CFG_DEBUG_SEL_ENABLE_SHIFT (0UL)




typedef uint32_t CFG_DEBUG_EN_TYPE;
#define CFG_DEBUG_EN_JTAGICE_ENABLE_MASK (0x1UL)
#define CFG_DEBUG_EN_JTAGICE_ENABLE_SHIFT (0UL)




typedef uint32_t CFG_SW_IF_TYPE;
#define CFG_SW_IF_SW_INIT_DONE_MASK (0x40UL)
#define CFG_SW_IF_SW_INIT_DONE_SHIFT (6UL)
#define CFG_SW_IF_HOST_INTR_MASK (0x2UL)
#define CFG_SW_IF_HOST_INTR_SHIFT (1UL)




typedef uint32_t CFG_SW_INTR_CLR_TYPE;
#define CFG_SW_INTR_CLR_CLR_MASK (0xffffffffUL)
#define CFG_SW_INTR_CLR_CLR_SHIFT (0UL)




typedef uint32_t CFG_QSPI_IO_STATUS_TYPE;
#define CFG_QSPI_IO_STATUS_STRAP_IP_DISABLE_QSPI_MASK (0x8UL)
#define CFG_QSPI_IO_STATUS_STRAP_IP_DISABLE_QSPI_SHIFT (3UL)
#define CFG_QSPI_IO_STATUS_STRAP_4BYTE_ADDR_MODE_MASK (0x4UL)
#define CFG_QSPI_IO_STATUS_STRAP_4BYTE_ADDR_MODE_SHIFT (2UL)
#define CFG_QSPI_IO_STATUS_STRAP_QUAD_LANE_MASK (0x2UL)
#define CFG_QSPI_IO_STATUS_STRAP_QUAD_LANE_SHIFT (1UL)
#define CFG_QSPI_IO_STATUS_STRAP_DUAL_LANE_MASK (0x1UL)
#define CFG_QSPI_IO_STATUS_STRAP_DUAL_LANE_SHIFT (0UL)




typedef uint32_t CFG_QSPI_IO_CONTROL_TYPE;
#define CFG_QSPI_IO_CONTROL_ENABLE_ECC_DED_INTR_MASK (0x80000000UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_ECC_DED_INTR_SHIFT (31UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_ECC_SEC_INTR_MASK (0x40000000UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_ECC_SEC_INTR_SHIFT (30UL)
#define CFG_QSPI_IO_CONTROL_DISABLE_MSPI_FLUSH_MASK (0x400UL)
#define CFG_QSPI_IO_CONTROL_DISABLE_MSPI_FLUSH_SHIFT (10UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_RBUS_ARBITER_TIMER_MASK (0x200UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_RBUS_ARBITER_TIMER_SHIFT (9UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_MSPI_HALT_SET_TRANSACTION_DONE_MASK (0x100UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_MSPI_HALT_SET_TRANSACTION_DONE_SHIFT (8UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_MSPI_DONE_MASK (0x80UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_MSPI_DONE_SHIFT (7UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_OVERREAD_MASK (0x40UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_OVERREAD_SHIFT (6UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_SESSION_DONE_MASK (0x20UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_SESSION_DONE_SHIFT (5UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_IMPATIENT_MASK (0x10UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_IMPATIENT_SHIFT (4UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_TRUNCATED_MASK (0x8UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_TRUNCATED_SHIFT (3UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_FULLNESS_REACHED_MASK (0x4UL)
#define CFG_QSPI_IO_CONTROL_ENABLE_SPI_LR_FULLNESS_REACHED_SHIFT (2UL)
#define CFG_QSPI_IO_CONTROL_CLK_ENABLE_MASK (0x1UL)
#define CFG_QSPI_IO_CONTROL_CLK_ENABLE_SHIFT (0UL)




typedef uint32_t CFG_QSPI_IP_REVID_TYPE;
#define CFG_QSPI_IP_REVID_REVID_MASK (0xffUL)
#define CFG_QSPI_IP_REVID_REVID_SHIFT (0UL)




typedef uint32_t CFG_SPI_CRC_CONTROL_TYPE;
#define CFG_SPI_CRC_CONTROL_CLEAR_MASK (0x2UL)
#define CFG_SPI_CRC_CONTROL_CLEAR_SHIFT (1UL)
#define CFG_SPI_CRC_CONTROL_ENABLE_MASK (0x1UL)
#define CFG_SPI_CRC_CONTROL_ENABLE_SHIFT (0UL)




typedef uint32_t CFG_SPI_CRC_STATUS_TYPE;
#define CFG_SPI_CRC_STATUS_QSPI_OUTPUT_MASK (0xffffffffUL)
#define CFG_SPI_CRC_STATUS_QSPI_OUTPUT_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_CFG_TYPE;
#define CFG_CPU_INTR_CFG_SOFT2VIC_CFG_MASK (0x4UL)
#define CFG_CPU_INTR_CFG_SOFT2VIC_CFG_SHIFT (2UL)
#define CFG_CPU_INTR_CFG_PAD_N_SEL_MASK (0x2UL)
#define CFG_CPU_INTR_CFG_PAD_N_SEL_SHIFT (1UL)
#define CFG_CPU_INTR_CFG_PAD_N_MODE_MASK (0x1UL)
#define CFG_CPU_INTR_CFG_PAD_N_MODE_SHIFT (0UL)




typedef uint32_t CFG_SPI_CRC_IDLE_CYCLE_COUNT_TYPE;
#define CFG_SPI_CRC_IDLE_CYCLE_COUNT_COUNT_MASK (0xffffffffUL)
#define CFG_SPI_CRC_IDLE_CYCLE_COUNT_COUNT_SHIFT (0UL)




typedef uint32_t CFG_AHB2RDB_TIMEOUT_TYPE;
#define CFG_AHB2RDB_TIMEOUT_QSPI_MASK (0x40000UL)
#define CFG_AHB2RDB_TIMEOUT_QSPI_SHIFT (18UL)
#define CFG_AHB2RDB_TIMEOUT_RDB16_MASK (0x20000UL)
#define CFG_AHB2RDB_TIMEOUT_RDB16_SHIFT (17UL)
#define CFG_AHB2RDB_TIMEOUT_SRAB_MASK (0x10000UL)
#define CFG_AHB2RDB_TIMEOUT_SRAB_SHIFT (16UL)
#define CFG_AHB2RDB_TIMEOUT_TIME_MASK (0xffffUL)
#define CFG_AHB2RDB_TIMEOUT_TIME_SHIFT (0UL)




typedef uint32_t CFG_AMAC_CTRL_TYPE;
#define CFG_AMAC_CTRL_AMAC_MDIO_ENABLE_MASK (0x400000UL)
#define CFG_AMAC_CTRL_AMAC_MDIO_ENABLE_SHIFT (22UL)
#define CFG_AMAC_CTRL_TM_SP_MASK (0x3ff000UL)
#define CFG_AMAC_CTRL_TM_SP_SHIFT (12UL)
#define CFG_AMAC_CTRL_TM_RF_MASK (0xff0UL)
#define CFG_AMAC_CTRL_TM_RF_SHIFT (4UL)
#define CFG_AMAC_CTRL_OOB_FLOW_CTRL_EN_MASK (0x8UL)
#define CFG_AMAC_CTRL_OOB_FLOW_CTRL_EN_SHIFT (3UL)
#define CFG_AMAC_CTRL_EN_AUTOCONFIG_MASK (0x4UL)
#define CFG_AMAC_CTRL_EN_AUTOCONFIG_SHIFT (2UL)
#define CFG_AMAC_CTRL_EEE_EN_MASK (0x2UL)
#define CFG_AMAC_CTRL_EEE_EN_SHIFT (1UL)
#define CFG_AMAC_CTRL_DISABLE_AMAC_MASK (0x1UL)
#define CFG_AMAC_CTRL_DISABLE_AMAC_SHIFT (0UL)




typedef uint32_t CFG_AMAC_IO_CTRL_TYPE;
#define CFG_AMAC_IO_CTRL_ADDR_MSB_MASK (0x80000000UL)
#define CFG_AMAC_IO_CTRL_ADDR_MSB_SHIFT (31UL)
#define CFG_AMAC_IO_CTRL_ADDR_MSB_SEL_MASK (0x40000000UL)
#define CFG_AMAC_IO_CTRL_ADDR_MSB_SEL_SHIFT (30UL)
#define CFG_AMAC_IO_CTRL_ARUSER_MASK (0x3e000000UL)
#define CFG_AMAC_IO_CTRL_ARUSER_SHIFT (25UL)
#define CFG_AMAC_IO_CTRL_AWUSER_MASK (0x1f00000UL)
#define CFG_AMAC_IO_CTRL_AWUSER_SHIFT (20UL)
#define CFG_AMAC_IO_CTRL_ARCACHE_MASK (0xf0000UL)
#define CFG_AMAC_IO_CTRL_ARCACHE_SHIFT (16UL)
#define CFG_AMAC_IO_CTRL_RSVD_1_MASK (0xc000UL)
#define CFG_AMAC_IO_CTRL_RSVD_1_SHIFT (14UL)
#define CFG_AMAC_IO_CTRL_LEDSCAN_FLOP_STAGES_MASK (0x3800UL)
#define CFG_AMAC_IO_CTRL_LEDSCAN_FLOP_STAGES_SHIFT (11UL)
#define CFG_AMAC_IO_CTRL_AWCACHE_MASK (0x780UL)
#define CFG_AMAC_IO_CTRL_AWCACHE_SHIFT (7UL)
#define CFG_AMAC_IO_CTRL_INTERFACE_MODE_STRAP_MASK (0x7cUL)
#define CFG_AMAC_IO_CTRL_INTERFACE_MODE_STRAP_SHIFT (2UL)
#define CFG_AMAC_IO_CTRL_RSVD_0_MASK (0x2UL)
#define CFG_AMAC_IO_CTRL_RSVD_0_SHIFT (1UL)
#define CFG_AMAC_IO_CTRL_CLK_ENABLE_MASK (0x1UL)
#define CFG_AMAC_IO_CTRL_CLK_ENABLE_SHIFT (0UL)




typedef uint32_t CFG_AMAC_IO_STAT_TYPE;
#define CFG_AMAC_IO_STAT_STAT_MASK (0xffffffffUL)
#define CFG_AMAC_IO_STAT_STAT_SHIFT (0UL)




typedef uint32_t CFG_AMAC_IP_REVID_TYPE;
#define CFG_AMAC_IP_REVID_REVID_MASK (0xffUL)
#define CFG_AMAC_IP_REVID_REVID_SHIFT (0UL)




typedef uint32_t CFG_QSPI_FLASH_BASE_ADDR_TYPE;
#define CFG_QSPI_FLASH_BASE_ADDR_MEM_ADDR_MASK (0xffffffffUL)
#define CFG_QSPI_FLASH_BASE_ADDR_MEM_ADDR_SHIFT (0UL)




typedef uint32_t CFG_QSPI_FLASH_SIZE_TYPE;
#define CFG_QSPI_FLASH_SIZE_MEM_BYTE_SIZE_MASK (0xffffffffUL)
#define CFG_QSPI_FLASH_SIZE_MEM_BYTE_SIZE_SHIFT (0UL)




typedef uint32_t CFG_APB_MONITOR_CTRL_TYPE;
#define CFG_APB_MONITOR_CTRL_TIMEOUT_IRQ_MASK_MASK (0x40UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_IRQ_MASK_SHIFT (6UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_ERR_RESP_EN_MASK (0x20UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_ERR_RESP_EN_SHIFT (5UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_EN_MASK (0x10UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_EN_SHIFT (4UL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_SEL_MASK (0xfUL)
#define CFG_APB_MONITOR_CTRL_TIMEOUT_SEL_SHIFT (0UL)




typedef uint32_t CFG_APB_TIMEOUT_ADDRESS_TYPE;
#define CFG_APB_TIMEOUT_ADDRESS_ADDRESS_MASK (0xffffffffUL)
#define CFG_APB_TIMEOUT_ADDRESS_ADDRESS_SHIFT (0UL)




typedef uint32_t CFG_APB_TIMEOUT_IRQ_STATUS_TYPE;
#define CFG_APB_TIMEOUT_IRQ_STATUS_STATUS_MASK (0x1UL)
#define CFG_APB_TIMEOUT_IRQ_STATUS_STATUS_SHIFT (0UL)




typedef uint32_t CFG_NMI_STATUS_TYPE;
#define CFG_NMI_STATUS_STATUS_MASK (0xffffffffUL)
#define CFG_NMI_STATUS_STATUS_SHIFT (0UL)




typedef uint32_t CFG_DEBUG_STATUS_TYPE;
#define CFG_DEBUG_STATUS_STATUS_MASK (0xffffffUL)
#define CFG_DEBUG_STATUS_STATUS_SHIFT (0UL)




typedef uint32_t CFG_HSM_STATUS_TYPE;
#define CFG_HSM_STATUS_STATUS_MASK (0x7fUL)
#define CFG_HSM_STATUS_STATUS_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_RAW0_TYPE;
#define CFG_CPU_INTR_RAW0_RAW0_MASK (0xffffffffUL)
#define CFG_CPU_INTR_RAW0_RAW0_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_RAW1_TYPE;
#define CFG_CPU_INTR_RAW1_RAW1_MASK (0xffffffffUL)
#define CFG_CPU_INTR_RAW1_RAW1_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_RAW2_TYPE;
#define CFG_CPU_INTR_RAW2_RAW2_MASK (0xffffffffUL)
#define CFG_CPU_INTR_RAW2_RAW2_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_RAW3_TYPE;
#define CFG_CPU_INTR_RAW3_RAW3_MASK (0xffffffffUL)
#define CFG_CPU_INTR_RAW3_RAW3_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_STAT0_TYPE;
#define CFG_CPU_INTR_STAT0_STAT0_MASK (0xffffffffUL)
#define CFG_CPU_INTR_STAT0_STAT0_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_STAT1_TYPE;
#define CFG_CPU_INTR_STAT1_STAT1_MASK (0xffffffffUL)
#define CFG_CPU_INTR_STAT1_STAT1_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_STAT2_TYPE;
#define CFG_CPU_INTR_STAT2_STAT2_MASK (0xffffffffUL)
#define CFG_CPU_INTR_STAT2_STAT2_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_STAT3_TYPE;
#define CFG_CPU_INTR_STAT3_STAT3_MASK (0xffffffffUL)
#define CFG_CPU_INTR_STAT3_STAT3_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_MASK0_TYPE;
#define CFG_CPU_INTR_MASK0_MASK0_MASK (0xffffffffUL)
#define CFG_CPU_INTR_MASK0_MASK0_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_MASK1_TYPE;
#define CFG_CPU_INTR_MASK1_MASK1_MASK (0xffffffffUL)
#define CFG_CPU_INTR_MASK1_MASK1_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_MASK2_TYPE;
#define CFG_CPU_INTR_MASK2_MASK2_MASK (0xffffffffUL)
#define CFG_CPU_INTR_MASK2_MASK2_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_MASK3_TYPE;
#define CFG_CPU_INTR_MASK3_MASK3_MASK (0xffffffffUL)
#define CFG_CPU_INTR_MASK3_MASK3_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_FORCE0_TYPE;
#define CFG_CPU_INTR_FORCE0_FORCE0_MASK (0xffffffffUL)
#define CFG_CPU_INTR_FORCE0_FORCE0_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_FORCE1_TYPE;
#define CFG_CPU_INTR_FORCE1_FORCE1_MASK (0xffffffffUL)
#define CFG_CPU_INTR_FORCE1_FORCE1_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_FORCE2_TYPE;
#define CFG_CPU_INTR_FORCE2_FORCE2_MASK (0xffffffffUL)
#define CFG_CPU_INTR_FORCE2_FORCE2_SHIFT (0UL)




typedef uint32_t CFG_CPU_INTR_FORCE3_TYPE;
#define CFG_CPU_INTR_FORCE3_FORCE3_MASK (0xffffffffUL)
#define CFG_CPU_INTR_FORCE3_FORCE3_SHIFT (0UL)




typedef uint32_t CFG_ARM2PCIE_INTR_TYPE;
#define CFG_ARM2PCIE_INTR_SW_PCIE_FORCE_EN_MASK (0x4UL)
#define CFG_ARM2PCIE_INTR_SW_PCIE_FORCE_EN_SHIFT (2UL)
#define CFG_ARM2PCIE_INTR_ARM2PCIE_HOST_INTR_MASK (0x3UL)
#define CFG_ARM2PCIE_INTR_ARM2PCIE_HOST_INTR_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_STAT0_TYPE;
#define CFG_PCIE_INTR_STAT0_STAT0_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_STAT0_STAT0_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_STAT1_TYPE;
#define CFG_PCIE_INTR_STAT1_STAT1_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_STAT1_STAT1_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_STAT2_TYPE;
#define CFG_PCIE_INTR_STAT2_STAT2_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_STAT2_STAT2_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_STAT3_TYPE;
#define CFG_PCIE_INTR_STAT3_STAT3_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_STAT3_STAT3_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_MASK0_TYPE;
#define CFG_PCIE_INTR_MASK0_MASK0_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_MASK0_MASK0_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_MASK1_TYPE;
#define CFG_PCIE_INTR_MASK1_MASK1_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_MASK1_MASK1_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_MASK2_TYPE;
#define CFG_PCIE_INTR_MASK2_MASK2_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_MASK2_MASK2_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_MASK3_TYPE;
#define CFG_PCIE_INTR_MASK3_MASK3_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_MASK3_MASK3_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_FORCE0_TYPE;
#define CFG_PCIE_INTR_FORCE0_FORCE0_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_FORCE0_FORCE0_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_FORCE1_TYPE;
#define CFG_PCIE_INTR_FORCE1_FORCE1_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_FORCE1_FORCE1_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_FORCE2_TYPE;
#define CFG_PCIE_INTR_FORCE2_FORCE2_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_FORCE2_FORCE2_SHIFT (0UL)




typedef uint32_t CFG_PCIE_INTR_FORCE3_TYPE;
#define CFG_PCIE_INTR_FORCE3_FORCE3_MASK (0xffffffffUL)
#define CFG_PCIE_INTR_FORCE3_FORCE3_SHIFT (0UL)




typedef uint32_t CFG_HW_MEM_INIT_EN_TYPE;
#define CFG_HW_MEM_INIT_EN_EN_MASK (0x7ffUL)
#define CFG_HW_MEM_INIT_EN_EN_SHIFT (0UL)




typedef uint32_t CFG_HW_MEM_INIT_DONE_STS_TYPE;
#define CFG_HW_MEM_INIT_DONE_STS_DONE_MASK (0x7ffUL)
#define CFG_HW_MEM_INIT_DONE_STS_DONE_SHIFT (0UL)




typedef uint32_t CFG_SPIM_IF_CONTROL_TYPE;
#define CFG_SPIM_IF_CONTROL_CFG_SPIM_SSB_OEB_VAL_MASK (0x40000UL)
#define CFG_SPIM_IF_CONTROL_CFG_SPIM_SSB_OEB_VAL_SHIFT (18UL)
#define CFG_SPIM_IF_CONTROL_CFG_SPIM_SSB_VAL_MASK (0x20000UL)
#define CFG_SPIM_IF_CONTROL_CFG_SPIM_SSB_VAL_SHIFT (17UL)
#define CFG_SPIM_IF_CONTROL_CFG_SPIM_SSB_SW_OVERRIDE_MASK (0x10000UL)
#define CFG_SPIM_IF_CONTROL_CFG_SPIM_SSB_SW_OVERRIDE_SHIFT (16UL)
#define CFG_SPIM_IF_CONTROL_SPARE15TO12_MASK (0xf000UL)
#define CFG_SPIM_IF_CONTROL_SPARE15TO12_SHIFT (12UL)
#define CFG_SPIM_IF_CONTROL_BYPASS_SPI_SLAVE_DONE_FIX_MASK (0x800UL)
#define CFG_SPIM_IF_CONTROL_BYPASS_SPI_SLAVE_DONE_FIX_SHIFT (11UL)
#define CFG_SPIM_IF_CONTROL_RSVD_MASK (0x400UL)
#define CFG_SPIM_IF_CONTROL_RSVD_SHIFT (10UL)
#define CFG_SPIM_IF_CONTROL_DELAY_BEFORE_CS_IDLE_RST_MASK (0x3fcUL)
#define CFG_SPIM_IF_CONTROL_DELAY_BEFORE_CS_IDLE_RST_SHIFT (2UL)
#define CFG_SPIM_IF_CONTROL_CFG_SPI_CS_N_MASK (0x2UL)
#define CFG_SPIM_IF_CONTROL_CFG_SPI_CS_N_SHIFT (1UL)
#define CFG_SPIM_IF_CONTROL_CFG_FORCE_SPI_CS_N_MASK (0x1UL)
#define CFG_SPIM_IF_CONTROL_CFG_FORCE_SPI_CS_N_SHIFT (0UL)




typedef uint32_t CFG_PROC_SYS_AHB_MON_STS_TYPE;
#define CFG_PROC_SYS_AHB_MON_STS_MACSEC_IF_TIMEOUT_MASK (0x80UL)
#define CFG_PROC_SYS_AHB_MON_STS_MACSEC_IF_TIMEOUT_SHIFT (7UL)
#define CFG_PROC_SYS_AHB_MON_STS_SPI_10T1S_IF_TIMEOUT_MASK (0x40UL)
#define CFG_PROC_SYS_AHB_MON_STS_SPI_10T1S_IF_TIMEOUT_SHIFT (6UL)
#define CFG_PROC_SYS_AHB_MON_STS_DMA_10T1S_IF_TIMEOUT_MASK (0x20UL)
#define CFG_PROC_SYS_AHB_MON_STS_DMA_10T1S_IF_TIMEOUT_SHIFT (5UL)
#define CFG_PROC_SYS_AHB_MON_STS_HSM_IF_TIMEOUT_MASK (0x10UL)
#define CFG_PROC_SYS_AHB_MON_STS_HSM_IF_TIMEOUT_SHIFT (4UL)
#define CFG_PROC_SYS_AHB_MON_STS_SW_FA_IF_TIMEOUT_MASK (0x8UL)
#define CFG_PROC_SYS_AHB_MON_STS_SW_FA_IF_TIMEOUT_SHIFT (3UL)
#define CFG_PROC_SYS_AHB_MON_STS_TOP_BRIDGE_IF_TIMEOUT_MASK (0x4UL)
#define CFG_PROC_SYS_AHB_MON_STS_TOP_BRIDGE_IF_TIMEOUT_SHIFT (2UL)
#define CFG_PROC_SYS_AHB_MON_STS_APB_HUB_IF_TIMEOUT_MASK (0x2UL)
#define CFG_PROC_SYS_AHB_MON_STS_APB_HUB_IF_TIMEOUT_SHIFT (1UL)
#define CFG_PROC_SYS_AHB_MON_STS_AMAC_AHB_IF_TIMEOUT_MASK (0x1UL)
#define CFG_PROC_SYS_AHB_MON_STS_AMAC_AHB_IF_TIMEOUT_SHIFT (0UL)




typedef uint32_t CFG_SW_BOOTMODE_STRAP_TYPE;




typedef uint32_t CFG_PCIE_CONFIG_TYPE;
#define CFG_PCIE_CONFIG_ARM2PCIE_DMA_PER_FUNC_MASK (0xf0UL)
#define CFG_PCIE_CONFIG_ARM2PCIE_DMA_PER_FUNC_SHIFT (4UL)
#define CFG_PCIE_CONFIG_ARM2PCIE_NUM_FUNC_MASK (0xfUL)
#define CFG_PCIE_CONFIG_ARM2PCIE_NUM_FUNC_SHIFT (0UL)




typedef uint32_t CFG_SW_STRAP0_TYPE;
#define CFG_SW_STRAP0_STRAP0_MASK (0xffffffffUL)
#define CFG_SW_STRAP0_STRAP0_SHIFT (0UL)




typedef uint32_t CFG_SW_STRAP1_TYPE;
#define CFG_SW_STRAP1_STRAP1_MASK (0xffffffffUL)
#define CFG_SW_STRAP1_STRAP1_SHIFT (0UL)




typedef uint32_t CFG_SW_STRAP2_TYPE;
#define CFG_SW_STRAP2_STRAP2_MASK (0x3fffUL)
#define CFG_SW_STRAP2_STRAP2_SHIFT (0UL)




typedef uint32_t CFG_HSM_CTL_TYPE;
#define CFG_HSM_CTL_HSM_BLOCK_CLK_EN_MASK (0x20UL)
#define CFG_HSM_CTL_HSM_BLOCK_CLK_EN_SHIFT (5UL)
#define CFG_HSM_CTL_M3_CORE_CLK_EN_MASK (0x10UL)
#define CFG_HSM_CTL_M3_CORE_CLK_EN_SHIFT (4UL)
#define CFG_HSM_CTL_HSM_PROD_MODE_CFG_MASK (0x8UL)
#define CFG_HSM_CTL_HSM_PROD_MODE_CFG_SHIFT (3UL)
#define CFG_HSM_CTL_M7_PROD_MODE_CFG_MASK (0x4UL)
#define CFG_HSM_CTL_M7_PROD_MODE_CFG_SHIFT (2UL)
#define CFG_HSM_CTL_HSM_BLOCK_SOFT_RST_MASK (0x2UL)
#define CFG_HSM_CTL_HSM_BLOCK_SOFT_RST_SHIFT (1UL)
#define CFG_HSM_CTL_M3_CORE_SOFT_RST_MASK (0x1UL)
#define CFG_HSM_CTL_M3_CORE_SOFT_RST_SHIFT (0UL)




typedef volatile struct COMP_PACKED sCFG_RDBType {
    CFG_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x0 */
    CFG_CPUSYS_MISC_TYPE cfg_cpusys_misc; /* OFFSET: 0x4 */
    CFG_TM_0_TYPE tm_0; /* OFFSET: 0x8 */
    CFG_DEBUG_SEL_TYPE debug_sel; /* OFFSET: 0xc */
    CFG_DEBUG_EN_TYPE debug_en; /* OFFSET: 0x10 */
    CFG_RESERVED_TYPE rsvd1[44]; /* OFFSET: 0x14 */
    CFG_SW_IF_TYPE sw_if; /* OFFSET: 0x40 */
    CFG_SW_INTR_CLR_TYPE sw_intr_clr; /* OFFSET: 0x44 */
    CFG_QSPI_IO_STATUS_TYPE qspi_io_status; /* OFFSET: 0x48 */
    CFG_QSPI_IO_CONTROL_TYPE qspi_io_control; /* OFFSET: 0x4c */
    CFG_QSPI_IP_REVID_TYPE qspi_ip_revid; /* OFFSET: 0x50 */
    CFG_SPI_CRC_CONTROL_TYPE spi_crc_control; /* OFFSET: 0x54 */
    CFG_SPI_CRC_STATUS_TYPE spi_crc_status; /* OFFSET: 0x58 */
    CFG_RESERVED_TYPE rsvd2[16]; /* OFFSET: 0x5c */
    CFG_CPU_INTR_CFG_TYPE cpu_intr_cfg; /* OFFSET: 0x6c */
    CFG_SPI_CRC_IDLE_CYCLE_COUNT_TYPE spi_crc_idle_cycle_count; /* OFFSET: 0x70 */
    CFG_AHB2RDB_TIMEOUT_TYPE ahb2rdb_timeout; /* OFFSET: 0x74 */
    CFG_AMAC_CTRL_TYPE amac_ctrl; /* OFFSET: 0x78 */
    CFG_AMAC_IO_CTRL_TYPE amac_io_ctrl; /* OFFSET: 0x7c */
    CFG_AMAC_IO_STAT_TYPE amac_io_stat; /* OFFSET: 0x80 */
    CFG_AMAC_IP_REVID_TYPE amac_ip_revid; /* OFFSET: 0x84 */
    CFG_QSPI_FLASH_BASE_ADDR_TYPE qspi_flash_base_addr; /* OFFSET: 0x88 */
    CFG_QSPI_FLASH_SIZE_TYPE qspi_flash_size; /* OFFSET: 0x8c */
    CFG_APB_MONITOR_CTRL_TYPE apb_monitor_ctrl; /* OFFSET: 0x90 */
    CFG_APB_TIMEOUT_ADDRESS_TYPE apb_timeout_address; /* OFFSET: 0x94 */
    CFG_APB_TIMEOUT_IRQ_STATUS_TYPE apb_timeout_irq_status; /* OFFSET: 0x98 */
    CFG_NMI_STATUS_TYPE nmi_status; /* OFFSET: 0x9c */
    CFG_DEBUG_STATUS_TYPE debug_status; /* OFFSET: 0xa0 */
    CFG_HSM_STATUS_TYPE hsm_status; /* OFFSET: 0xa4 */
    CFG_CPU_INTR_RAW0_TYPE cpu_intr_raw0; /* OFFSET: 0xa8 */
    CFG_CPU_INTR_RAW1_TYPE cpu_intr_raw1; /* OFFSET: 0xac */
    CFG_CPU_INTR_RAW2_TYPE cpu_intr_raw2; /* OFFSET: 0xb0 */
    CFG_CPU_INTR_RAW3_TYPE cpu_intr_raw3; /* OFFSET: 0xb4 */
    CFG_CPU_INTR_STAT0_TYPE cpu_intr_stat0; /* OFFSET: 0xb8 */
    CFG_CPU_INTR_STAT1_TYPE cpu_intr_stat1; /* OFFSET: 0xbc */
    CFG_CPU_INTR_STAT2_TYPE cpu_intr_stat2; /* OFFSET: 0xc0 */
    CFG_CPU_INTR_STAT3_TYPE cpu_intr_stat3; /* OFFSET: 0xc4 */
    CFG_CPU_INTR_MASK0_TYPE cpu_intr_mask0; /* OFFSET: 0xc8 */
    CFG_CPU_INTR_MASK1_TYPE cpu_intr_mask1; /* OFFSET: 0xcc */
    CFG_CPU_INTR_MASK2_TYPE cpu_intr_mask2; /* OFFSET: 0xd0 */
    CFG_CPU_INTR_MASK3_TYPE cpu_intr_mask3; /* OFFSET: 0xd4 */
    CFG_CPU_INTR_FORCE0_TYPE cpu_intr_force0; /* OFFSET: 0xd8 */
    CFG_CPU_INTR_FORCE1_TYPE cpu_intr_force1; /* OFFSET: 0xdc */
    CFG_CPU_INTR_FORCE2_TYPE cpu_intr_force2; /* OFFSET: 0xe0 */
    CFG_CPU_INTR_FORCE3_TYPE cpu_intr_force3; /* OFFSET: 0xe4 */
    CFG_ARM2PCIE_INTR_TYPE arm2pcie_intr; /* OFFSET: 0xe8 */
    CFG_PCIE_INTR_STAT0_TYPE pcie_intr_stat0; /* OFFSET: 0xec */
    CFG_PCIE_INTR_STAT1_TYPE pcie_intr_stat1; /* OFFSET: 0xf0 */
    CFG_PCIE_INTR_STAT2_TYPE pcie_intr_stat2; /* OFFSET: 0xf4 */
    CFG_PCIE_INTR_STAT3_TYPE pcie_intr_stat3; /* OFFSET: 0xf8 */
    CFG_PCIE_INTR_MASK0_TYPE pcie_intr_mask0; /* OFFSET: 0xfc */
    CFG_PCIE_INTR_MASK1_TYPE pcie_intr_mask1; /* OFFSET: 0x100 */
    CFG_PCIE_INTR_MASK2_TYPE pcie_intr_mask2; /* OFFSET: 0x104 */
    CFG_PCIE_INTR_MASK3_TYPE pcie_intr_mask3; /* OFFSET: 0x108 */
    CFG_PCIE_INTR_FORCE0_TYPE pcie_intr_force0; /* OFFSET: 0x10c */
    CFG_PCIE_INTR_FORCE1_TYPE pcie_intr_force1; /* OFFSET: 0x110 */
    CFG_PCIE_INTR_FORCE2_TYPE pcie_intr_force2; /* OFFSET: 0x114 */
    CFG_PCIE_INTR_FORCE3_TYPE pcie_intr_force3; /* OFFSET: 0x118 */
    CFG_HW_MEM_INIT_EN_TYPE hw_mem_init_en; /* OFFSET: 0x11c */
    CFG_HW_MEM_INIT_DONE_STS_TYPE hw_mem_init_done_sts; /* OFFSET: 0x120 */
    CFG_SPIM_IF_CONTROL_TYPE spim_if_control; /* OFFSET: 0x124 */
    CFG_PROC_SYS_AHB_MON_STS_TYPE proc_sys_ahb_mon_sts; /* OFFSET: 0x128 */
    CFG_SW_BOOTMODE_STRAP_TYPE sw_bootmode_strap; /* OFFSET: 0x12c */
    CFG_PCIE_CONFIG_TYPE pcie_config; /* OFFSET: 0x130 */
    CFG_SW_STRAP0_TYPE sw_strap0; /* OFFSET: 0x134 */
    CFG_SW_STRAP1_TYPE sw_strap1; /* OFFSET: 0x138 */
    CFG_SW_STRAP2_TYPE sw_strap2; /* OFFSET: 0x13c */
    CFG_RESERVED_TYPE rsvd3[188]; /* OFFSET: 0x140 */
    CFG_HSM_CTL_TYPE hsm_ctl; /* OFFSET: 0x1fc */
} CFG_RDBType;


#define CFG_BASE                        (0x40148000UL)



#define CFG_MAX_HW_ID                   (1UL)


#define CFG_SW_INTR_CLR_CTF_MASK        (0x00200000UL)


#define CFG_SW_INTR_CLR_PSFP_MASK       (0x00020000UL)


#define CFG_SW_INTR_CLR_DOS_MASK        (0x00010000UL)


#define CFG_SW_INTR_CLR_CFP_OUTOFPROF_MASK  (0x00008000UL)


#define CFG_SW_INTR_CLR_LINKSTATUS6_MASK  (0x00004000UL)


#define CFG_SW_INTR_CLR_MEM_DED_MASK    (0x00002000UL)


#define CFG_SW_INTR_CLR_EEE_LPI_MASK    (0x00001000UL)


#define CFG_SW_INTR_CLR_WAKEUP5_MASK    (0x00000800UL)


#define CFG_SW_INTR_CLR_WAKEUP8_MASK    (0x00000400UL)


#define CFG_SW_INTR_CLR_WAKEUP7_MASK    (0x00000200UL)


#define CFG_SW_INTR_CLR_CFP_TCAM_MASK   (0x00000100UL)


#define CFG_SW_INTR_CLR_LINKSTATUS8_MASK  (0x00000080UL)


#define CFG_SW_INTR_CLR_LINKSTATUS7_MASK  (0x00000040UL)


#define CFG_SW_INTR_CLR_LINKSTATUS5_MASK  (0x00000020UL)


#define CFG_SW_INTR_CLR_LINKSTATUS4_MASK  (0x00000010UL)


#define CFG_SW_INTR_CLR_LINKSTATUS3_MASK  (0x00000008UL)


#define CFG_SW_INTR_CLR_LINKSTATUS2_MASK  (0x00000004UL)


#define CFG_SW_INTR_CLR_LINKSTATUS1_MASK  (0x00000002UL)


#define CFG_SW_INTR_CLR_LINKSTATUS0_MASK  (0x00000001UL)

#endif /* CFG_RDB_H */
