/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file chipmisc_rdb.h
    @brief RDB File for CHIPMISC

    @version Orion_A0_20201104_SWDEV
*/

#ifndef CHIPMISC_RDB_H
#define CHIPMISC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t CHIPMISC_MODEL_REV_NUM_TYPE;
#define CHIPMISC_MODEL_REV_NUM_MODEL_NUM_MASK (0x3f0U)
#define CHIPMISC_MODEL_REV_NUM_MODEL_NUM_SHIFT (4U)
#define CHIPMISC_MODEL_REV_NUM_REV_NUM_MASK (0xfU)
#define CHIPMISC_MODEL_REV_NUM_REV_NUM_SHIFT (0U)




typedef uint16_t CHIPMISC_DEVICEID_LO_TYPE;
#define CHIPMISC_DEVICEID_LO_DEVICE_ID_LO_MASK (0xfffU)
#define CHIPMISC_DEVICEID_LO_DEVICE_ID_LO_SHIFT (0U)




typedef uint16_t CHIPMISC_DEVICEID_HI_TYPE;
#define CHIPMISC_DEVICEID_HI_DEVICE_ID_HI_MASK (0xffU)
#define CHIPMISC_DEVICEID_HI_DEVICE_ID_HI_SHIFT (0U)




typedef uint16_t CHIPMISC_SWITCH_MISC_CTRL_TYPE;
#define CHIPMISC_SWITCH_MISC_CTRL_PDA_ALL_MEM_FOR_SWITCH_MASK (0x8000U)
#define CHIPMISC_SWITCH_MISC_CTRL_PDA_ALL_MEM_FOR_SWITCH_SHIFT (15U)
#define CHIPMISC_SWITCH_MISC_CTRL_DIRECT_GATE_PORT_MASK (0x1ffU)
#define CHIPMISC_SWITCH_MISC_CTRL_DIRECT_GATE_PORT_SHIFT (0U)




typedef uint8_t CHIPMISC_RESERVED_TYPE;




typedef uint16_t CHIPMISC_LDO_PWRDN_TYPE;
#define CHIPMISC_LDO_PWRDN_PWRDN_MASK (0x1U)
#define CHIPMISC_LDO_PWRDN_PWRDN_SHIFT (0U)




typedef uint16_t CHIPMISC_LDO_VREG_1_TYPE;
#define CHIPMISC_LDO_VREG_1_BG_REF_VOLTAGE_TRIMMING_MASK (0x7800U)
#define CHIPMISC_LDO_VREG_1_BG_REF_VOLTAGE_TRIMMING_SHIFT (11U)
#define CHIPMISC_LDO_VREG_1_INRUSH_CURRENT_ADJUSTMENT_MASK (0x400U)
#define CHIPMISC_LDO_VREG_1_INRUSH_CURRENT_ADJUSTMENT_SHIFT (10U)
#define CHIPMISC_LDO_VREG_1_CURRENT_LIMIT_ADJUSTMENT_MASK (0x200U)
#define CHIPMISC_LDO_VREG_1_CURRENT_LIMIT_ADJUSTMENT_SHIFT (9U)
#define CHIPMISC_LDO_VREG_1_LEAKAGE_SENSING_CONTROL_MASK (0x100U)
#define CHIPMISC_LDO_VREG_1_LEAKAGE_SENSING_CONTROL_SHIFT (8U)
#define CHIPMISC_LDO_VREG_1_OUTPUT_VOLTAGE_TUNING_MASK (0xf0U)
#define CHIPMISC_LDO_VREG_1_OUTPUT_VOLTAGE_TUNING_SHIFT (4U)
#define CHIPMISC_LDO_VREG_1_BTCT_MASK (0xfU)
#define CHIPMISC_LDO_VREG_1_BTCT_SHIFT (0U)




typedef uint16_t CHIPMISC_LDO_VREGCNTL_2_TYPE;
#define CHIPMISC_LDO_VREGCNTL_2_ZERO_POSITION_ADJUSTMENT_MASK (0xcU)
#define CHIPMISC_LDO_VREGCNTL_2_ZERO_POSITION_ADJUSTMENT_SHIFT (2U)
#define CHIPMISC_LDO_VREGCNTL_2_LEAKAGE_SENSING_ADJUSTMENT_MASK (0x3U)
#define CHIPMISC_LDO_VREGCNTL_2_LEAKAGE_SENSING_ADJUSTMENT_SHIFT (0U)




typedef uint16_t CHIPMISC_LDO_VREGCNTLEN_TYPE;
#define CHIPMISC_LDO_VREGCNTLEN_VREGCNTLEN_MASK (0x1U)
#define CHIPMISC_LDO_VREGCNTLEN_VREGCNTLEN_SHIFT (0U)




typedef uint16_t CHIPMISC_SWREG_CTRL_REG0_TYPE;
#define CHIPMISC_SWREG_CTRL_REG0_SWREG_SOFTRESET_MASK (0x1U)
#define CHIPMISC_SWREG_CTRL_REG0_SWREG_SOFTRESET_SHIFT (0U)
#define CHIPMISC_SWREG_CTRL_REG0_UPDATE_CTRL_REG_POSEDGE_MASK (0x2U)
#define CHIPMISC_SWREG_CTRL_REG0_UPDATE_CTRL_REG_POSEDGE_SHIFT (1U)
#define CHIPMISC_SWREG_CTRL_REG0_COMP_LP_CTRL_MASK (0x4U)
#define CHIPMISC_SWREG_CTRL_REG0_COMP_LP_CTRL_SHIFT (2U)
#define CHIPMISC_SWREG_CTRL_REG0_COMP_LOOP_GAIN1_CTRL_MASK (0x8U)
#define CHIPMISC_SWREG_CTRL_REG0_COMP_LOOP_GAIN1_CTRL_SHIFT (3U)
#define CHIPMISC_SWREG_CTRL_REG0_COMP_LOOP_GAIN2_CTRL_MASK (0x70U)
#define CHIPMISC_SWREG_CTRL_REG0_COMP_LOOP_GAIN2_CTRL_SHIFT (4U)
#define CHIPMISC_SWREG_CTRL_REG0_BURST_R_CTRL_MASK (0x600U)
#define CHIPMISC_SWREG_CTRL_REG0_BURST_R_CTRL_SHIFT (9U)
#define CHIPMISC_SWREG_CTRL_REG0_SD_DITHER_DIS_MASK (0x800U)
#define CHIPMISC_SWREG_CTRL_REG0_SD_DITHER_DIS_SHIFT (11U)
#define CHIPMISC_SWREG_CTRL_REG0_FAULT_0_ILIM_DUTYCYCLE_EN_MASK (0x1000U)
#define CHIPMISC_SWREG_CTRL_REG0_FAULT_0_ILIM_DUTYCYCLE_EN_SHIFT (12U)
#define CHIPMISC_SWREG_CTRL_REG0_FAULT_1_ILIM_ADCOUT_EN_MASK (0x2000U)
#define CHIPMISC_SWREG_CTRL_REG0_FAULT_1_ILIM_ADCOUT_EN_SHIFT (13U)
#define CHIPMISC_SWREG_CTRL_REG0_FAULT_OV_EN_MASK (0x4000U)
#define CHIPMISC_SWREG_CTRL_REG0_FAULT_OV_EN_SHIFT (14U)
#define CHIPMISC_SWREG_CTRL_REG0_JITTERFILTER_DIS_MASK (0x8000U)
#define CHIPMISC_SWREG_CTRL_REG0_JITTERFILTER_DIS_SHIFT (15U)




typedef uint16_t CHIPMISC_SWREG_CTRL_REG1_TYPE;
#define CHIPMISC_SWREG_CTRL_REG1_COMP_SS_CTRL_MASK (0x3U)
#define CHIPMISC_SWREG_CTRL_REG1_COMP_SS_CTRL_SHIFT (0U)
#define CHIPMISC_SWREG_CTRL_REG1_SD_FREQ_CTRL_MASK (0xcU)
#define CHIPMISC_SWREG_CTRL_REG1_SD_FREQ_CTRL_SHIFT (2U)
#define CHIPMISC_SWREG_CTRL_REG1_FAULT_DUTYCYCLE_MASK (0x30U)
#define CHIPMISC_SWREG_CTRL_REG1_FAULT_DUTYCYCLE_SHIFT (4U)
#define CHIPMISC_SWREG_CTRL_REG1_FAULT_ADCOUT_CTRL_MASK (0xc0U)
#define CHIPMISC_SWREG_CTRL_REG1_FAULT_ADCOUT_CTRL_SHIFT (6U)
#define CHIPMISC_SWREG_CTRL_REG1_COMP_COEF1_SEL_MASK (0xff00U)
#define CHIPMISC_SWREG_CTRL_REG1_COMP_COEF1_SEL_SHIFT (8U)




typedef uint16_t CHIPMISC_SWREG_CTRL_REG2_TYPE;
#define CHIPMISC_SWREG_CTRL_REG2_COMP_COEF1_SEL_MASK (0x3U)
#define CHIPMISC_SWREG_CTRL_REG2_COMP_COEF1_SEL_SHIFT (0U)
#define CHIPMISC_SWREG_CTRL_REG2_COMP_COEF2_SEL_MASK (0xffcU)
#define CHIPMISC_SWREG_CTRL_REG2_COMP_COEF2_SEL_SHIFT (2U)
#define CHIPMISC_SWREG_CTRL_REG2_SD_DUTYMIN_3_0_MASK (0xf000U)
#define CHIPMISC_SWREG_CTRL_REG2_SD_DUTYMIN_3_0_SHIFT (12U)




typedef uint16_t CHIPMISC_SWREG_CTRL_REG3_TYPE;
#define CHIPMISC_SWREG_CTRL_REG3_SD_DUTYMIN_6_4_MASK (0x7U)
#define CHIPMISC_SWREG_CTRL_REG3_SD_DUTYMIN_6_4_SHIFT (0U)
#define CHIPMISC_SWREG_CTRL_REG3_SD_DUTYMAX_MASK (0xff8U)
#define CHIPMISC_SWREG_CTRL_REG3_SD_DUTYMAX_SHIFT (3U)
#define CHIPMISC_SWREG_CTRL_REG3_FAULT_ADCOUT_REF_3_0_MASK (0xf000U)
#define CHIPMISC_SWREG_CTRL_REG3_FAULT_ADCOUT_REF_3_0_SHIFT (12U)




typedef uint16_t CHIPMISC_SWREG_CTRL_REG4_TYPE;
#define CHIPMISC_SWREG_CTRL_REG4_FAULT_ADCOUT_REF_9_4_MASK (0x3fU)
#define CHIPMISC_SWREG_CTRL_REG4_FAULT_ADCOUT_REF_9_4_SHIFT (0U)
#define CHIPMISC_SWREG_CTRL_REG4_ILIM_DUTYCYCLE_REF_MASK (0xffc0U)
#define CHIPMISC_SWREG_CTRL_REG4_ILIM_DUTYCYCLE_REF_SHIFT (6U)




typedef uint16_t CHIPMISC_SWREG_CTRL_REG5_TYPE;
#define CHIPMISC_SWREG_CTRL_REG5_PMU_STABLE_OVERRIDE_BSTI_MASK (0x1U)
#define CHIPMISC_SWREG_CTRL_REG5_PMU_STABLE_OVERRIDE_BSTI_SHIFT (0U)
#define CHIPMISC_SWREG_CTRL_REG5_FETS_ENB_DELAY_CTRL_MASK (0xcU)
#define CHIPMISC_SWREG_CTRL_REG5_FETS_ENB_DELAY_CTRL_SHIFT (2U)
#define CHIPMISC_SWREG_CTRL_REG5_NOVL_CTRL_MASK (0x70U)
#define CHIPMISC_SWREG_CTRL_REG5_NOVL_CTRL_SHIFT (4U)
#define CHIPMISC_SWREG_CTRL_REG5_DUTYCYCLE_ILIM_FAULT_0_MASK_MASK (0x80U)
#define CHIPMISC_SWREG_CTRL_REG5_DUTYCYCLE_ILIM_FAULT_0_MASK_SHIFT (7U)
#define CHIPMISC_SWREG_CTRL_REG5_ADCOUT_ILIM_FAULT_1_MASK_MASK (0x100U)
#define CHIPMISC_SWREG_CTRL_REG5_ADCOUT_ILIM_FAULT_1_MASK_SHIFT (8U)
#define CHIPMISC_SWREG_CTRL_REG5_ANALOG_COMP_ILIM_FAULT2_MASK_MASK (0x200U)
#define CHIPMISC_SWREG_CTRL_REG5_ANALOG_COMP_ILIM_FAULT2_MASK_SHIFT (9U)
#define CHIPMISC_SWREG_CTRL_REG5_OV_FAULT_MASK_MASK (0x400U)
#define CHIPMISC_SWREG_CTRL_REG5_OV_FAULT_MASK_SHIFT (10U)
#define CHIPMISC_SWREG_CTRL_REG5_PLL_EN_MASK (0x800U)
#define CHIPMISC_SWREG_CTRL_REG5_PLL_EN_SHIFT (11U)
#define CHIPMISC_SWREG_CTRL_REG5_BURST_MODE_EN_MASK (0x1000U)
#define CHIPMISC_SWREG_CTRL_REG5_BURST_MODE_EN_SHIFT (12U)
#define CHIPMISC_SWREG_CTRL_REG5_BURST_D_CTRL_2_0_MASK (0xe000U)
#define CHIPMISC_SWREG_CTRL_REG5_BURST_D_CTRL_2_0_SHIFT (13U)




typedef uint16_t CHIPMISC_SWREG_CTRL_REG6_TYPE;
#define CHIPMISC_SWREG_CTRL_REG6_DVDD_CTRL_MASK (0x3U)
#define CHIPMISC_SWREG_CTRL_REG6_DVDD_CTRL_SHIFT (0U)
#define CHIPMISC_SWREG_CTRL_REG6_BG_TRIM_CTRL_MASK (0xfcU)
#define CHIPMISC_SWREG_CTRL_REG6_BG_TRIM_CTRL_SHIFT (2U)
#define CHIPMISC_SWREG_CTRL_REG6_REF_CTRL_MASK (0xff00U)
#define CHIPMISC_SWREG_CTRL_REG6_REF_CTRL_SHIFT (8U)




typedef uint16_t CHIPMISC_SWREG_CTRL_REG7_TYPE;
#define CHIPMISC_SWREG_CTRL_REG7_NDRIVE_PFET_MASK (0x7U)
#define CHIPMISC_SWREG_CTRL_REG7_NDRIVE_PFET_SHIFT (0U)
#define CHIPMISC_SWREG_CTRL_REG7_NDRIVE_NFET_MASK (0x38U)
#define CHIPMISC_SWREG_CTRL_REG7_NDRIVE_NFET_SHIFT (3U)
#define CHIPMISC_SWREG_CTRL_REG7_PDRIVE_PFET_MASK (0x1c0U)
#define CHIPMISC_SWREG_CTRL_REG7_PDRIVE_PFET_SHIFT (6U)
#define CHIPMISC_SWREG_CTRL_REG7_PDRIVE_NFET_MASK (0xe00U)
#define CHIPMISC_SWREG_CTRL_REG7_PDRIVE_NFET_SHIFT (9U)
#define CHIPMISC_SWREG_CTRL_REG7_ADAPT_NOVL_MASK (0x3000U)
#define CHIPMISC_SWREG_CTRL_REG7_ADAPT_NOVL_SHIFT (12U)
#define CHIPMISC_SWREG_CTRL_REG7_PULSE_WIDTH_LIMIT_MASK (0xc000U)
#define CHIPMISC_SWREG_CTRL_REG7_PULSE_WIDTH_LIMIT_SHIFT (14U)




typedef uint16_t CHIPMISC_SWREG_CTRL_REG8_TYPE;
#define CHIPMISC_SWREG_CTRL_REG8_RGM_CTRL_MASK (0x7U)
#define CHIPMISC_SWREG_CTRL_REG8_RGM_CTRL_SHIFT (0U)
#define CHIPMISC_SWREG_CTRL_REG8_OSC_ADJ_MASK (0x38U)
#define CHIPMISC_SWREG_CTRL_REG8_OSC_ADJ_SHIFT (3U)
#define CHIPMISC_SWREG_CTRL_REG8_PHASE_CNTRL_EN_MASK (0x40U)
#define CHIPMISC_SWREG_CTRL_REG8_PHASE_CNTRL_EN_SHIFT (6U)
#define CHIPMISC_SWREG_CTRL_REG8_GMBIAS_CTRL_MASK (0x80U)
#define CHIPMISC_SWREG_CTRL_REG8_GMBIAS_CTRL_SHIFT (7U)
#define CHIPMISC_SWREG_CTRL_REG8_PHASE_CNTRL_COMP_WIDTH_MASK (0x100U)
#define CHIPMISC_SWREG_CTRL_REG8_PHASE_CNTRL_COMP_WIDTH_SHIFT (8U)
#define CHIPMISC_SWREG_CTRL_REG8_IVCO_CTRL_MASK (0xe00U)
#define CHIPMISC_SWREG_CTRL_REG8_IVCO_CTRL_SHIFT (9U)
#define CHIPMISC_SWREG_CTRL_REG8_BURST_D_CTRL_6_3_MASK (0xf000U)
#define CHIPMISC_SWREG_CTRL_REG8_BURST_D_CTRL_6_3_SHIFT (12U)




typedef uint16_t CHIPMISC_SWREG_CTRL_REG9_TYPE;
#define CHIPMISC_SWREG_CTRL_REG9_TEST_MODE_ADC_MASK (0x1U)
#define CHIPMISC_SWREG_CTRL_REG9_TEST_MODE_ADC_SHIFT (0U)
#define CHIPMISC_SWREG_CTRL_REG9_TEST_MODE_VBG_MASK (0x2U)
#define CHIPMISC_SWREG_CTRL_REG9_TEST_MODE_VBG_SHIFT (1U)
#define CHIPMISC_SWREG_CTRL_REG9_OVERCUR_REF_CTRL_MASK (0xcU)
#define CHIPMISC_SWREG_CTRL_REG9_OVERCUR_REF_CTRL_SHIFT (2U)
#define CHIPMISC_SWREG_CTRL_REG9_ADAPTIVE_DEADTIME_DIS_MASK (0x10U)
#define CHIPMISC_SWREG_CTRL_REG9_ADAPTIVE_DEADTIME_DIS_SHIFT (4U)
#define CHIPMISC_SWREG_CTRL_REG9_ADAPTIVE_DEADTIME_CTRL_MASK (0x60U)
#define CHIPMISC_SWREG_CTRL_REG9_ADAPTIVE_DEADTIME_CTRL_SHIFT (5U)
#define CHIPMISC_SWREG_CTRL_REG9_NON_LINEAR_GAIN_MASK (0x100U)
#define CHIPMISC_SWREG_CTRL_REG9_NON_LINEAR_GAIN_SHIFT (8U)
#define CHIPMISC_SWREG_CTRL_REG9_NON_LINEAR_GAIN_EN_MASK (0x200U)
#define CHIPMISC_SWREG_CTRL_REG9_NON_LINEAR_GAIN_EN_SHIFT (9U)
#define CHIPMISC_SWREG_CTRL_REG9_ADC_GAIN_MASK (0xc00U)
#define CHIPMISC_SWREG_CTRL_REG9_ADC_GAIN_SHIFT (10U)
#define CHIPMISC_SWREG_CTRL_REG9_SYS_CLK_FREQ_MASK (0x3000U)
#define CHIPMISC_SWREG_CTRL_REG9_SYS_CLK_FREQ_SHIFT (12U)
#define CHIPMISC_SWREG_CTRL_REG9_ADC_FREQ_MASK (0xc000U)
#define CHIPMISC_SWREG_CTRL_REG9_ADC_FREQ_SHIFT (14U)




typedef uint16_t CHIPMISC_SWREG_STAT_REG12_TYPE;
#define CHIPMISC_SWREG_STAT_REG12_ADC_COMP_IN_MASK (0xffU)
#define CHIPMISC_SWREG_STAT_REG12_ADC_COMP_IN_SHIFT (0U)
#define CHIPMISC_SWREG_STAT_REG12_DUTY_CYCLE_MASK (0x100U)
#define CHIPMISC_SWREG_STAT_REG12_DUTY_CYCLE_SHIFT (8U)
#define CHIPMISC_SWREG_STAT_REG12_UNDERVOLTAGE_FAULT_MASK (0x200U)
#define CHIPMISC_SWREG_STAT_REG12_UNDERVOLTAGE_FAULT_SHIFT (9U)
#define CHIPMISC_SWREG_STAT_REG12_OVERVOLTAGE_FAULT_MASK (0x800U)
#define CHIPMISC_SWREG_STAT_REG12_OVERVOLTAGE_FAULT_SHIFT (11U)




typedef uint16_t CHIPMISC_SWREG_STAT_REG13_TYPE;
#define CHIPMISC_SWREG_STAT_REG13_ILIM_DUTYCYCLE_MASK (0x3ffU)
#define CHIPMISC_SWREG_STAT_REG13_ILIM_DUTYCYCLE_SHIFT (0U)




typedef uint16_t CHIPMISC_SWREG_STAT_REG14_TYPE;
#define CHIPMISC_SWREG_STAT_REG14_ILIM_ADCOUT_MASK (0x7ffU)
#define CHIPMISC_SWREG_STAT_REG14_ILIM_ADCOUT_SHIFT (0U)




typedef uint16_t CHIPMISC_SWREG_STAT_REG15_TYPE;
#define CHIPMISC_SWREG_STAT_REG15_ANA_CURR_LIMIT_MASK (0x1U)
#define CHIPMISC_SWREG_STAT_REG15_ANA_CURR_LIMIT_SHIFT (0U)
#define CHIPMISC_SWREG_STAT_REG15_PVIN_SELECT_1P5_MASK (0x6U)
#define CHIPMISC_SWREG_STAT_REG15_PVIN_SELECT_1P5_SHIFT (1U)
#define CHIPMISC_SWREG_STAT_REG15_VIN_SELECT_1P5_MASK (0x18U)
#define CHIPMISC_SWREG_STAT_REG15_VIN_SELECT_1P5_SHIFT (3U)
#define CHIPMISC_SWREG_STAT_REG15_DIG_DUTY_CYCLE_CURR_LIMIT_FAULT_MASK (0x2000U)
#define CHIPMISC_SWREG_STAT_REG15_DIG_DUTY_CYCLE_CURR_LIMIT_FAULT_SHIFT (13U)
#define CHIPMISC_SWREG_STAT_REG15_DIG_UV_FAULT_MASK (0x4000U)
#define CHIPMISC_SWREG_STAT_REG15_DIG_UV_FAULT_SHIFT (14U)
#define CHIPMISC_SWREG_STAT_REG15_DIG_OV_FAULT_MASK (0x8000U)
#define CHIPMISC_SWREG_STAT_REG15_DIG_OV_FAULT_SHIFT (15U)




typedef uint16_t CHIPMISC_SWREG_ACCESS_CTRL_1_TYPE;
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_9_MASK (0x200U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_9_SHIFT (9U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_8_MASK (0x100U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_8_SHIFT (8U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_7_MASK (0x80U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_7_SHIFT (7U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_6_MASK (0x40U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_6_SHIFT (6U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_5_MASK (0x20U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_5_SHIFT (5U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_4_MASK (0x10U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_4_SHIFT (4U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_3_MASK (0x8U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_3_SHIFT (3U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_2_MASK (0x4U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_2_SHIFT (2U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_1_MASK (0x2U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_1_SHIFT (1U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_0_MASK (0x1U)
#define CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_0_SHIFT (0U)




typedef uint16_t CHIPMISC_SWREG_ACCESS_CTRL_2_TYPE;
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_15_MASK (0x8000U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_15_SHIFT (15U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_14_MASK (0x4000U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_14_SHIFT (14U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_13_MASK (0x2000U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_13_SHIFT (13U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_12_MASK (0x1000U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_12_SHIFT (12U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_9_MASK (0x200U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_9_SHIFT (9U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_8_MASK (0x100U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_8_SHIFT (8U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_7_MASK (0x80U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_7_SHIFT (7U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_6_MASK (0x40U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_6_SHIFT (6U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_5_MASK (0x20U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_5_SHIFT (5U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_4_MASK (0x10U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_4_SHIFT (4U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_3_MASK (0x8U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_3_SHIFT (3U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_2_MASK (0x4U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_2_SHIFT (2U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_1_MASK (0x2U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_1_SHIFT (1U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_0_MASK (0x1U)
#define CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_0_SHIFT (0U)




typedef uint16_t CHIPMISC_SWREG_CONTROL_STATUS_TYPE;
#define CHIPMISC_SWREG_CONTROL_STATUS_PMU_STABLE_STATUS_MASK (0x1U)
#define CHIPMISC_SWREG_CONTROL_STATUS_PMU_STABLE_STATUS_SHIFT (0U)
#define CHIPMISC_SWREG_CONTROL_STATUS_EXT_PLLCLK_EN_MASK (0x2U)
#define CHIPMISC_SWREG_CONTROL_STATUS_EXT_PLLCLK_EN_SHIFT (1U)




typedef uint16_t CHIPMISC_SGMII_PLUS2_PWRDWN_TYPE;
#define CHIPMISC_SGMII_PLUS2_PWRDWN_PWRDWN_MASK (0x1U)
#define CHIPMISC_SGMII_PLUS2_PWRDWN_PWRDWN_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PLUS2_HW_RST_DLY_VAL_TYPE;
#define CHIPMISC_SGMII_PLUS2_HW_RST_DLY_VAL_VAL_MASK (0x7fffU)
#define CHIPMISC_SGMII_PLUS2_HW_RST_DLY_VAL_VAL_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PLUS2_MDIO_RST_DLY_VAL_TYPE;
#define CHIPMISC_SGMII_PLUS2_MDIO_RST_DLY_VAL_VAL_MASK (0x1fffU)
#define CHIPMISC_SGMII_PLUS2_MDIO_RST_DLY_VAL_VAL_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PLUS2_PLL_RST_DLY_VAL_TYPE;
#define CHIPMISC_SGMII_PLUS2_PLL_RST_DLY_VAL_VAL_MASK (0xfffU)
#define CHIPMISC_SGMII_PLUS2_PLL_RST_DLY_VAL_VAL_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PLUS2_EXT_CTL_TYPE;
#define CHIPMISC_SGMII_PLUS2_EXT_CTL_RESCAL_AUTOLOAD_EN_MASK (0x800U)
#define CHIPMISC_SGMII_PLUS2_EXT_CTL_RESCAL_AUTOLOAD_EN_SHIFT (11U)
#define CHIPMISC_SGMII_PLUS2_EXT_CTL_REFSEL_MASK (0x300U)
#define CHIPMISC_SGMII_PLUS2_EXT_CTL_REFSEL_SHIFT (8U)
#define CHIPMISC_SGMII_PLUS2_EXT_CTL_RESCAL_MASK (0xf0U)
#define CHIPMISC_SGMII_PLUS2_EXT_CTL_RESCAL_SHIFT (4U)
#define CHIPMISC_SGMII_PLUS2_EXT_CTL_SPARE_MASK (0xfU)
#define CHIPMISC_SGMII_PLUS2_EXT_CTL_SPARE_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PLUS2_MDIO_CTL_TYPE;
#define CHIPMISC_SGMII_PLUS2_MDIO_CTL_SGMII_BROADCAST_EN_MASK (0x200U)
#define CHIPMISC_SGMII_PLUS2_MDIO_CTL_SGMII_BROADCAST_EN_SHIFT (9U)
#define CHIPMISC_SGMII_PLUS2_MDIO_CTL_MD_DEVAD_MASK (0x1fU)
#define CHIPMISC_SGMII_PLUS2_MDIO_CTL_MD_DEVAD_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PLUS2_STATUS_TYPE;
#define CHIPMISC_SGMII_PLUS2_STATUS_STATUS_MASK (0xffffU)
#define CHIPMISC_SGMII_PLUS2_STATUS_STATUS_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PCIE_PWRDWN_TYPE;
#define CHIPMISC_SGMII_PCIE_PWRDWN_PWRDWN_MASK (0x1U)
#define CHIPMISC_SGMII_PCIE_PWRDWN_PWRDWN_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PCIE_HW_RST_DLY_VAL_TYPE;
#define CHIPMISC_SGMII_PCIE_HW_RST_DLY_VAL_VAL_MASK (0x7fffU)
#define CHIPMISC_SGMII_PCIE_HW_RST_DLY_VAL_VAL_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_TYPE;
#define CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_PCB_RD_ACK_POS_SEL_MASK (0x4000U)
#define CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_PCB_RD_ACK_POS_SEL_SHIFT (14U)
#define CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_PCB_RD_CYCLE_LEN_SEL_MASK (0x2000U)
#define CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_PCB_RD_CYCLE_LEN_SEL_SHIFT (13U)
#define CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_MDIO_RST_DLY_VAL_MASK (0x1fffU)
#define CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_MDIO_RST_DLY_VAL_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_TYPE;
#define CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PCB_WR_ACK_POS_SEL_MASK (0x4000U)
#define CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PCB_WR_ACK_POS_SEL_SHIFT (14U)
#define CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PCB_WR_CYCLE_LEN_SEL_MASK (0x3000U)
#define CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PCB_WR_CYCLE_LEN_SEL_SHIFT (12U)
#define CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PLL_RST_DLY_VAL_MASK (0xfffU)
#define CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PLL_RST_DLY_VAL_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PCIE_EXT_CTL_TYPE;
#define CHIPMISC_SGMII_PCIE_EXT_CTL_RESCAL_AUTOLOAD_EN_MASK (0x800U)
#define CHIPMISC_SGMII_PCIE_EXT_CTL_RESCAL_AUTOLOAD_EN_SHIFT (11U)
#define CHIPMISC_SGMII_PCIE_EXT_CTL_REFSEL_MASK (0x300U)
#define CHIPMISC_SGMII_PCIE_EXT_CTL_REFSEL_SHIFT (8U)
#define CHIPMISC_SGMII_PCIE_EXT_CTL_SPARE2_MASK (0xe0U)
#define CHIPMISC_SGMII_PCIE_EXT_CTL_SPARE2_SHIFT (5U)
#define CHIPMISC_SGMII_PCIE_EXT_CTL_RESCAL_MASK (0x1eU)
#define CHIPMISC_SGMII_PCIE_EXT_CTL_RESCAL_SHIFT (1U)
#define CHIPMISC_SGMII_PCIE_EXT_CTL_SPARE_MASK (0x1U)
#define CHIPMISC_SGMII_PCIE_EXT_CTL_SPARE_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PCIE_MDIO_CTL_TYPE;
#define CHIPMISC_SGMII_PCIE_MDIO_CTL_MD_DEVAD_MASK (0x1fU)
#define CHIPMISC_SGMII_PCIE_MDIO_CTL_MD_DEVAD_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PCIE_STATUS_TYPE;
#define CHIPMISC_SGMII_PCIE_STATUS_STATUS_MASK (0xffffU)
#define CHIPMISC_SGMII_PCIE_STATUS_STATUS_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_AFE_STATUS_TYPE;
#define CHIPMISC_SGMII_AFE_STATUS_SPARE15TO5_MASK (0xffe0U)
#define CHIPMISC_SGMII_AFE_STATUS_SPARE15TO5_SHIFT (5U)
#define CHIPMISC_SGMII_AFE_STATUS_AFE_CAL_DONE_MASK (0x10U)
#define CHIPMISC_SGMII_AFE_STATUS_AFE_CAL_DONE_SHIFT (4U)
#define CHIPMISC_SGMII_AFE_STATUS_SPARE3_MASK (0x8U)
#define CHIPMISC_SGMII_AFE_STATUS_SPARE3_SHIFT (3U)
#define CHIPMISC_SGMII_AFE_STATUS_SGMII_TXPLL_LOCK1_MASK (0x4U)
#define CHIPMISC_SGMII_AFE_STATUS_SGMII_TXPLL_LOCK1_SHIFT (2U)
#define CHIPMISC_SGMII_AFE_STATUS_SGMII_PCIE_TXPLL_LOCK_MASK (0x2U)
#define CHIPMISC_SGMII_AFE_STATUS_SGMII_PCIE_TXPLL_LOCK_SHIFT (1U)
#define CHIPMISC_SGMII_AFE_STATUS_SGMII_TXPLL_LOCK0_MASK (0x1U)
#define CHIPMISC_SGMII_AFE_STATUS_SGMII_TXPLL_LOCK0_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PLUSR_PWRDWN_TYPE;
#define CHIPMISC_SGMII_PLUSR_PWRDWN_PWRDWN_MASK (0x1U)
#define CHIPMISC_SGMII_PLUSR_PWRDWN_PWRDWN_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PLUSR_HW_RST_DLY_VAL_TYPE;
#define CHIPMISC_SGMII_PLUSR_HW_RST_DLY_VAL_VAL_MASK (0x7fffU)
#define CHIPMISC_SGMII_PLUSR_HW_RST_DLY_VAL_VAL_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PLUSR_PLL_RST_DLY_VAL_TYPE;
#define CHIPMISC_SGMII_PLUSR_PLL_RST_DLY_VAL_VAL_MASK (0xfffU)
#define CHIPMISC_SGMII_PLUSR_PLL_RST_DLY_VAL_VAL_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PLUSR_EXT_CTL_TYPE;
#define CHIPMISC_SGMII_PLUSR_EXT_CTL_RESCAL_AUTOLOAD_EN_MASK (0x800U)
#define CHIPMISC_SGMII_PLUSR_EXT_CTL_RESCAL_AUTOLOAD_EN_SHIFT (11U)
#define CHIPMISC_SGMII_PLUSR_EXT_CTL_REFSEL_MASK (0x300U)
#define CHIPMISC_SGMII_PLUSR_EXT_CTL_REFSEL_SHIFT (8U)
#define CHIPMISC_SGMII_PLUSR_EXT_CTL_RESCAL_MASK (0xf0U)
#define CHIPMISC_SGMII_PLUSR_EXT_CTL_RESCAL_SHIFT (4U)
#define CHIPMISC_SGMII_PLUSR_EXT_CTL_SPARE_MASK (0xfU)
#define CHIPMISC_SGMII_PLUSR_EXT_CTL_SPARE_SHIFT (0U)




typedef uint16_t CHIPMISC_SGMII_PLUSR_MDIO_CTL_TYPE;
#define CHIPMISC_SGMII_PLUSR_MDIO_CTL_FAST_MODE_MASK (0x400U)
#define CHIPMISC_SGMII_PLUSR_MDIO_CTL_FAST_MODE_SHIFT (10U)




typedef uint16_t CHIPMISC_SGMII_PLUSR_STATUS_TYPE;
#define CHIPMISC_SGMII_PLUSR_STATUS_STATUS_MASK (0xffffU)
#define CHIPMISC_SGMII_PLUSR_STATUS_STATUS_SHIFT (0U)




typedef uint16_t CHIPMISC_BOOTROM_STATUS_TYPE;
#define CHIPMISC_BOOTROM_STATUS_FIRMWARE_EXECUTED_MASK (0x8000U)
#define CHIPMISC_BOOTROM_STATUS_FIRMWARE_EXECUTED_SHIFT (15U)
#define CHIPMISC_BOOTROM_STATUS_BOOTROM_LOADED_MASK (0x4000U)
#define CHIPMISC_BOOTROM_STATUS_BOOTROM_LOADED_SHIFT (14U)
#define CHIPMISC_BOOTROM_STATUS_SPARE_MASK (0x3c00U)
#define CHIPMISC_BOOTROM_STATUS_SPARE_SHIFT (10U)
#define CHIPMISC_BOOTROM_STATUS_CRC_STATUS_MASK (0x200U)
#define CHIPMISC_BOOTROM_STATUS_CRC_STATUS_SHIFT (9U)
#define CHIPMISC_BOOTROM_STATUS_IMAGE_KEY_MASK (0x100U)
#define CHIPMISC_BOOTROM_STATUS_IMAGE_KEY_SHIFT (8U)
#define CHIPMISC_BOOTROM_STATUS_IMAGE_TYPE_MASK (0xc0U)
#define CHIPMISC_BOOTROM_STATUS_IMAGE_TYPE_SHIFT (6U)
#define CHIPMISC_BOOTROM_STATUS_IMAGE_COUNT_MASK (0x3cU)
#define CHIPMISC_BOOTROM_STATUS_IMAGE_COUNT_SHIFT (2U)
#define CHIPMISC_BOOTROM_STATUS_FINAL_IMAGE_MASK (0x2U)
#define CHIPMISC_BOOTROM_STATUS_FINAL_IMAGE_SHIFT (1U)
#define CHIPMISC_BOOTROM_STATUS_CRC_CHECK_ENABLE_MASK (0x1U)
#define CHIPMISC_BOOTROM_STATUS_CRC_CHECK_ENABLE_SHIFT (0U)




typedef uint16_t CHIPMISC_BOOTROM_VERSION_TYPE;
#define CHIPMISC_BOOTROM_VERSION_FIRMWARE_VERSION_MASK (0xe000U)
#define CHIPMISC_BOOTROM_VERSION_FIRMWARE_VERSION_SHIFT (13U)
#define CHIPMISC_BOOTROM_VERSION_MONTH_MASK (0x1e00U)
#define CHIPMISC_BOOTROM_VERSION_MONTH_SHIFT (9U)
#define CHIPMISC_BOOTROM_VERSION_DAY_MASK (0x1f0U)
#define CHIPMISC_BOOTROM_VERSION_DAY_SHIFT (4U)
#define CHIPMISC_BOOTROM_VERSION_YEAR_MASK (0xfU)
#define CHIPMISC_BOOTROM_VERSION_YEAR_SHIFT (0U)




typedef uint16_t CHIPMISC_SPARE_HW_REG_TYPE;
#define CHIPMISC_SPARE_HW_REG_REG_MASK (0xffffU)
#define CHIPMISC_SPARE_HW_REG_REG_SHIFT (0U)




typedef uint16_t CHIPMISC_F1_VERSION_TYPE;
#define CHIPMISC_F1_VERSION_VERSION_MASK (0xffffU)
#define CHIPMISC_F1_VERSION_VERSION_SHIFT (0U)




typedef uint16_t CHIPMISC_PKG_MODEL_TYPE;
#define CHIPMISC_PKG_MODEL_SPARE_MASK (0xffc0U)
#define CHIPMISC_PKG_MODEL_SPARE_SHIFT (6U)
#define CHIPMISC_PKG_MODEL_PKG_MODEL_MASK (0x3fU)
#define CHIPMISC_PKG_MODEL_PKG_MODEL_SHIFT (0U)




typedef uint16_t CHIPMISC_SPARE_SW_REG_TYPE;
#define CHIPMISC_SPARE_SW_REG_REG_MASK (0xffffU)
#define CHIPMISC_SPARE_SW_REG_REG_SHIFT (0U)




typedef uint16_t CHIPMISC_CPUSYS_MISC_TYPE;
#define CHIPMISC_CPUSYS_MISC_SPARE_MASK (0xfff0U)
#define CHIPMISC_CPUSYS_MISC_SPARE_SHIFT (4U)
#define CHIPMISC_CPUSYS_MISC_ACCESS_INT_SLV_THRO_MDIO_MST_MASK (0x8U)
#define CHIPMISC_CPUSYS_MISC_ACCESS_INT_SLV_THRO_MDIO_MST_SHIFT (3U)
#define CHIPMISC_CPUSYS_MISC_INTR_OUT_EN_PCIE_MASK (0x4U)
#define CHIPMISC_CPUSYS_MISC_INTR_OUT_EN_PCIE_SHIFT (2U)
#define CHIPMISC_CPUSYS_MISC_INTR_OUT_EN_PAD_MASK (0x2U)
#define CHIPMISC_CPUSYS_MISC_INTR_OUT_EN_PAD_SHIFT (1U)
#define CHIPMISC_CPUSYS_MISC_SOFT_INTR_MASK (0x1U)
#define CHIPMISC_CPUSYS_MISC_SOFT_INTR_SHIFT (0U)




typedef uint16_t CHIPMISC_BRPHYS_MISC_TYPE;
#define CHIPMISC_BRPHYS_MISC_SPARE_MASK (0xffc0U)
#define CHIPMISC_BRPHYS_MISC_SPARE_SHIFT (6U)
#define CHIPMISC_BRPHYS_MISC_BRPHY_1G_1P_SOURCE_SYNC_MII_MASK (0x20U)
#define CHIPMISC_BRPHYS_MISC_BRPHY_1G_1P_SOURCE_SYNC_MII_SHIFT (5U)
#define CHIPMISC_BRPHYS_MISC_BR5P_TC10_RDB_MDIO_SEL_MASK (0x10U)
#define CHIPMISC_BRPHYS_MISC_BR5P_TC10_RDB_MDIO_SEL_SHIFT (4U)
#define CHIPMISC_BRPHYS_MISC_BRPHY_1G_1PORT_CLEAR_ON_READ_MASK (0x8U)
#define CHIPMISC_BRPHYS_MISC_BRPHY_1G_1PORT_CLEAR_ON_READ_SHIFT (3U)
#define CHIPMISC_BRPHYS_MISC_CFG_TC10_SL_M7_INTR_EN_MASK (0x4U)
#define CHIPMISC_BRPHYS_MISC_CFG_TC10_SL_M7_INTR_EN_SHIFT (2U)
#define CHIPMISC_BRPHYS_MISC_BR_AUTO_NEG_EN_STRAP_DEF_MASK (0x2U)
#define CHIPMISC_BRPHYS_MISC_BR_AUTO_NEG_EN_STRAP_DEF_SHIFT (1U)
#define CHIPMISC_BRPHYS_MISC_CLEAR_ON_READ_EN_MASK (0x1U)
#define CHIPMISC_BRPHYS_MISC_CLEAR_ON_READ_EN_SHIFT (0U)




typedef uint16_t CHIPMISC_BRPHYS_TC10_CTRL_REG_TYPE;
#define CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_BR1G_MASK (0x20U)
#define CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_BR1G_SHIFT (5U)
#define CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_BR5_MASK (0x10U)
#define CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_BR5_SHIFT (4U)
#define CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_MASK (0xfU)
#define CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_SHIFT (0U)




typedef uint16_t CHIPMISC_BRPHYS_TC10_STATUS_REG_TYPE;
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_SPARE_MASK (0xe000U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_SPARE_SHIFT (13U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_BR1G_MASK (0x1000U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_BR1G_SHIFT (12U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_BR1G_MASK (0x800U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_BR1G_SHIFT (11U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_BR5_MASK (0x400U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_BR5_SHIFT (10U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_BR5_MASK (0x200U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_BR5_SHIFT (9U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_AFE_WAKE_VIA_WAKE_MASK (0x100U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_AFE_WAKE_VIA_WAKE_SHIFT (8U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_MASK (0xf0U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_SHIFT (4U)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_MASK (0xfU)
#define CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_SHIFT (0U)




typedef uint16_t CHIPMISC_LRV18T28ANXESC_TYPE;
#define CHIPMISC_LRV18T28ANXESC_RING_OSC_SEL_CTRL_MASK (0xfU)
#define CHIPMISC_LRV18T28ANXESC_RING_OSC_SEL_CTRL_SHIFT (0U)




typedef uint16_t CHIPMISC_LRV18T28ANXEEC_TYPE;
#define CHIPMISC_LRV18T28ANXEEC_RING_OSC_OUTPUT_EN_MASK (0x1000U)
#define CHIPMISC_LRV18T28ANXEEC_RING_OSC_OUTPUT_EN_SHIFT (12U)
#define CHIPMISC_LRV18T28ANXEEC_RING_OSC_EN_CTRL_MASK (0xfffU)
#define CHIPMISC_LRV18T28ANXEEC_RING_OSC_EN_CTRL_SHIFT (0U)




typedef uint16_t CHIPMISC_SCRATCH_REG_TYPE;
#define CHIPMISC_SCRATCH_REG_SCRATCH_MASK (0xffffU)
#define CHIPMISC_SCRATCH_REG_SCRATCH_SHIFT (0U)




typedef volatile struct COMP_PACKED sCHIPMISC_RDBType {
    CHIPMISC_MODEL_REV_NUM_TYPE model_rev_num; /* OFFSET: 0x0 */
    CHIPMISC_DEVICEID_LO_TYPE deviceid_lo; /* OFFSET: 0x2 */
    CHIPMISC_DEVICEID_HI_TYPE deviceid_hi; /* OFFSET: 0x4 */
    CHIPMISC_SWITCH_MISC_CTRL_TYPE switch_misc_ctrl; /* OFFSET: 0x6 */
    CHIPMISC_RESERVED_TYPE rsvd0[248]; /* OFFSET: 0x8 */
    CHIPMISC_LDO_PWRDN_TYPE ldo_pwrdn; /* OFFSET: 0x100 */
    CHIPMISC_LDO_VREG_1_TYPE ldo_vregcntl_1; /* OFFSET: 0x102 */
    CHIPMISC_LDO_VREGCNTL_2_TYPE ldo_vregcntl_2; /* OFFSET: 0x104 */
    CHIPMISC_LDO_VREGCNTLEN_TYPE ldo_vregcntlen; /* OFFSET: 0x106 */
    CHIPMISC_RESERVED_TYPE rsvd1[8]; /* OFFSET: 0x108 */
    CHIPMISC_SWREG_CTRL_REG0_TYPE swreg_ctrl_reg0; /* OFFSET: 0x110 */
    CHIPMISC_SWREG_CTRL_REG1_TYPE swreg_ctrl_reg1; /* OFFSET: 0x112 */
    CHIPMISC_SWREG_CTRL_REG2_TYPE swreg_ctrl_reg2; /* OFFSET: 0x114 */
    CHIPMISC_SWREG_CTRL_REG3_TYPE swreg_ctrl_reg3; /* OFFSET: 0x116 */
    CHIPMISC_SWREG_CTRL_REG4_TYPE swreg_ctrl_reg4; /* OFFSET: 0x118 */
    CHIPMISC_SWREG_CTRL_REG5_TYPE swreg_ctrl_reg5; /* OFFSET: 0x11a */
    CHIPMISC_SWREG_CTRL_REG6_TYPE swreg_ctrl_reg6; /* OFFSET: 0x11c */
    CHIPMISC_SWREG_CTRL_REG7_TYPE swreg_ctrl_reg7; /* OFFSET: 0x11e */
    CHIPMISC_SWREG_CTRL_REG8_TYPE swreg_ctrl_reg8; /* OFFSET: 0x120 */
    CHIPMISC_SWREG_CTRL_REG9_TYPE swreg_ctrl_reg9; /* OFFSET: 0x122 */
    CHIPMISC_SWREG_STAT_REG12_TYPE swreg_stat_reg12; /* OFFSET: 0x124 */
    CHIPMISC_SWREG_STAT_REG13_TYPE swreg_stat_reg13; /* OFFSET: 0x126 */
    CHIPMISC_SWREG_STAT_REG14_TYPE swreg_stat_reg14; /* OFFSET: 0x128 */
    CHIPMISC_SWREG_STAT_REG15_TYPE swreg_stat_reg15; /* OFFSET: 0x12a */
    CHIPMISC_SWREG_ACCESS_CTRL_1_TYPE swreg_access_ctrl_1; /* OFFSET: 0x12c */
    CHIPMISC_SWREG_ACCESS_CTRL_2_TYPE swreg_access_ctrl_2; /* OFFSET: 0x12e */
    CHIPMISC_SWREG_CONTROL_STATUS_TYPE swreg_control_status; /* OFFSET: 0x130 */
    CHIPMISC_RESERVED_TYPE rsvd2[14]; /* OFFSET: 0x132 */
    CHIPMISC_SGMII_PLUS2_PWRDWN_TYPE sgmii_plus2_pwrdwn; /* OFFSET: 0x140 */
    CHIPMISC_SGMII_PLUS2_HW_RST_DLY_VAL_TYPE sgmii_plus2_hw_rst_dly_val; /* OFFSET: 0x142 */
    CHIPMISC_SGMII_PLUS2_MDIO_RST_DLY_VAL_TYPE sgmii_plus2_mdio_rst_dly_val; /* OFFSET: 0x144 */
    CHIPMISC_SGMII_PLUS2_PLL_RST_DLY_VAL_TYPE sgmii_plus2_pll_rst_dly_val; /* OFFSET: 0x146 */
    CHIPMISC_SGMII_PLUS2_EXT_CTL_TYPE sgmii_plus2_ext_ctl; /* OFFSET: 0x148 */
    CHIPMISC_RESERVED_TYPE rsvd3[12]; /* OFFSET: 0x14a */
    CHIPMISC_SGMII_PLUS2_MDIO_CTL_TYPE sgmii_plus2_mdio_ctl; /* OFFSET: 0x156 */
    CHIPMISC_SGMII_PLUS2_STATUS_TYPE sgmii_plus2_status; /* OFFSET: 0x158 */
    CHIPMISC_RESERVED_TYPE rsvd4[6]; /* OFFSET: 0x15a */
    CHIPMISC_SGMII_PCIE_PWRDWN_TYPE sgmii_pcie_pwrdwn; /* OFFSET: 0x160 */
    CHIPMISC_SGMII_PCIE_HW_RST_DLY_VAL_TYPE sgmii_pcie_hw_rst_dly_val; /* OFFSET: 0x162 */
    CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_TYPE sgmii_pcie_mdio_rst_dly_val; /* OFFSET: 0x164 */
    CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_TYPE sgmii_pcie_pll_rst_dly_val; /* OFFSET: 0x166 */
    CHIPMISC_SGMII_PCIE_EXT_CTL_TYPE sgmii_pcie_ext_ctl; /* OFFSET: 0x168 */
    CHIPMISC_SGMII_PCIE_MDIO_CTL_TYPE sgmii_pcie_mdio_ctl; /* OFFSET: 0x16a */
    CHIPMISC_SGMII_PCIE_STATUS_TYPE sgmii_pcie_status; /* OFFSET: 0x16c */
    CHIPMISC_SGMII_AFE_STATUS_TYPE sgmii_afe_status; /* OFFSET: 0x16e */
    CHIPMISC_SGMII_PLUSR_PWRDWN_TYPE sgmii_plusr_pwrdwn; /* OFFSET: 0x170 */
    CHIPMISC_SGMII_PLUSR_HW_RST_DLY_VAL_TYPE sgmii_plusr_hw_rst_dly_val; /* OFFSET: 0x172 */
    CHIPMISC_RESERVED_TYPE rsvd5[2]; /* OFFSET: 0x174 */
    CHIPMISC_SGMII_PLUSR_PLL_RST_DLY_VAL_TYPE sgmii_plusr_pll_rst_dly_val; /* OFFSET: 0x176 */
    CHIPMISC_SGMII_PLUSR_EXT_CTL_TYPE sgmii_plusr_ext_ctl; /* OFFSET: 0x178 */
    CHIPMISC_SGMII_PLUSR_MDIO_CTL_TYPE sgmii_plusr_mdio_ctl; /* OFFSET: 0x17a */
    CHIPMISC_SGMII_PLUSR_STATUS_TYPE sgmii_plusr_status; /* OFFSET: 0x17c */
    CHIPMISC_RESERVED_TYPE rsvd6[386]; /* OFFSET: 0x17e */
    CHIPMISC_BOOTROM_STATUS_TYPE f1_image_status; /* OFFSET: 0x300 */
    CHIPMISC_BOOTROM_VERSION_TYPE f1_image_version; /* OFFSET: 0x302 */
    CHIPMISC_BOOTROM_STATUS_TYPE f2_image_status; /* OFFSET: 0x304 */
    CHIPMISC_BOOTROM_VERSION_TYPE f2_image_version; /* OFFSET: 0x306 */
    CHIPMISC_SPARE_HW_REG_TYPE spare_hw_reg4; /* OFFSET: 0x308 */
    CHIPMISC_SPARE_HW_REG_TYPE spare_hw_reg5; /* OFFSET: 0x30a */
    CHIPMISC_SPARE_HW_REG_TYPE spare_hw_reg6; /* OFFSET: 0x30c */
    CHIPMISC_SPARE_HW_REG_TYPE spare_hw_reg7; /* OFFSET: 0x30e */
    CHIPMISC_SPARE_HW_REG_TYPE spare_hw_reg8; /* OFFSET: 0x310 */
    CHIPMISC_SPARE_HW_REG_TYPE spare_hw_reg9; /* OFFSET: 0x312 */
    CHIPMISC_F1_VERSION_TYPE f1_version; /* OFFSET: 0x314 */
    CHIPMISC_SPARE_HW_REG_TYPE spare_hw_reg11; /* OFFSET: 0x316 */
    CHIPMISC_PKG_MODEL_TYPE pkg_model; /* OFFSET: 0x318 */
    CHIPMISC_SPARE_HW_REG_TYPE spare_hw_reg13; /* OFFSET: 0x31a */
    CHIPMISC_SPARE_HW_REG_TYPE spare_hw_reg14; /* OFFSET: 0x31c */
    CHIPMISC_SPARE_HW_REG_TYPE spare_hw_reg15; /* OFFSET: 0x31e */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg0; /* OFFSET: 0x320 */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg1; /* OFFSET: 0x322 */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg2; /* OFFSET: 0x324 */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg3; /* OFFSET: 0x326 */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg4; /* OFFSET: 0x328 */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg5; /* OFFSET: 0x32a */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg6; /* OFFSET: 0x32c */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg7; /* OFFSET: 0x32e */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg8; /* OFFSET: 0x330 */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg9; /* OFFSET: 0x332 */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg10; /* OFFSET: 0x334 */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg11; /* OFFSET: 0x336 */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg12; /* OFFSET: 0x338 */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg13; /* OFFSET: 0x33a */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg14; /* OFFSET: 0x33c */
    CHIPMISC_SPARE_SW_REG_TYPE spare_sw_reg15; /* OFFSET: 0x33e */
    CHIPMISC_CPUSYS_MISC_TYPE cpusys_misc; /* OFFSET: 0x340 */
    CHIPMISC_BRPHYS_MISC_TYPE brphys_misc; /* OFFSET: 0x342 */
    CHIPMISC_BRPHYS_TC10_CTRL_REG_TYPE brphys_tc10_ctrl_reg; /* OFFSET: 0x344 */
    CHIPMISC_BRPHYS_TC10_STATUS_REG_TYPE brphys_tc10_status_reg; /* OFFSET: 0x346 */
    CHIPMISC_LRV18T28ANXESC_TYPE ring_osc_sel_ctrl_reg; /* OFFSET: 0x348 */
    CHIPMISC_LRV18T28ANXEEC_TYPE ring_osc_en_ctrl_reg; /* OFFSET: 0x34a */
    CHIPMISC_RESERVED_TYPE rsvd7[3250]; /* OFFSET: 0x34c */
    CHIPMISC_SCRATCH_REG_TYPE scratch_reg; /* OFFSET: 0xffe */
} CHIPMISC_RDBType;


#define CHIPMISC_BASE                   (0x4A800000UL)



#define CHIPMISC_MAX_HW_ID              (1UL)


#define CHIPMISC_SWREG_CTRL_REG1_VALUE  (0x1804U)


#define CHIPMISC_SWREG_CTRL_REG2_VALUE  (0xEE8AU)


#define CHIPMISC_SWREG_CTRL_REG3_VALUE  (0x0601U)


#define CHIPMISC_SWREG_CTRL_REG4_VALUE  (0xCCD0U)


#define CHIPMISC_SWREG_CTRL_REG5_VALUE  (0x0580U)


#define CHIPMISC_SWREG_CTRL_REG6_VALUE  (0xB000U)


#define CHIPMISC_SWREG_CTRL_REG7_VALUE  (0x1FFFU)


#define CHIPMISC_SWREG_CTRL_REG8_VALUE  (0x0000U)


#define CHIPMISC_SWREG_CTRL_REG9_VALUE  (0x0A0CU)


#define CHIPMISC_SWREG_CTRL_REG0_VALUE0  (0x830U)


#define CHIPMISC_SWREG_CTRL_REG0_VALUE1  (0x832U)


#define CHIPMISC_SWREG_TIMEOUT_COUNT    (10000UL)

#endif /* CHIPMISC_RDB_H */
