/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file dwc_xgmac_rdb.h
    @brief RDB File for DWC_XGMAC

    @version Orion_A0_20201104_SWDEV
*/

#ifndef DWC_XGMAC_RDB_H
#define DWC_XGMAC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t DWC_XGMAC_MAC_TX_CONFIGURATION_TYPE;
#define DWC_XGMAC_MAC_TX_CONFIGURATION_TE_MASK (0x1UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_TE_SHIFT (0UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_DDIC_MASK (0x2UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_DDIC_SHIFT (1UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_ISM_MASK (0x8UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_ISM_SHIFT (3UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_ISR_MASK (0xf0UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_ISR_SHIFT (4UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_IPG_MASK (0x700UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_IPG_SHIFT (8UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_IFP_MASK (0x800UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_IFP_SHIFT (11UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_JD_MASK (0x10000UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_JD_SHIFT (16UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_SARC_MASK (0x700000UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_SARC_SHIFT (20UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_SS_MASK (0xe0000000UL)
#define DWC_XGMAC_MAC_TX_CONFIGURATION_SS_SHIFT (29UL)




typedef uint32_t DWC_XGMAC_MAC_RX_CONFIGURATION_TYPE;
#define DWC_XGMAC_MAC_RX_CONFIGURATION_RE_MASK (0x1UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_RE_SHIFT (0UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_ACS_MASK (0x2UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_ACS_SHIFT (1UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_CST_MASK (0x4UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_CST_SHIFT (2UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_DCRCC_MASK (0x8UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_DCRCC_SHIFT (3UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_SPEN_MASK (0x10UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_SPEN_SHIFT (4UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_USP_MASK (0x20UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_USP_SHIFT (5UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_GPSLCE_MASK (0x40UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_GPSLCE_SHIFT (6UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_WD_MASK (0x80UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_WD_SHIFT (7UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_JE_MASK (0x100UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_JE_SHIFT (8UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_IPC_MASK (0x200UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_IPC_SHIFT (9UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_LM_MASK (0x400UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_LM_SHIFT (10UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_S2KP_MASK (0x800UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_S2KP_SHIFT (11UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_HDSMS_MASK (0x7000UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_HDSMS_SHIFT (12UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_GPSL_MASK (0x3fff0000UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_GPSL_SHIFT (16UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_ARPEN_MASK (0x80000000UL)
#define DWC_XGMAC_MAC_RX_CONFIGURATION_ARPEN_SHIFT (31UL)




typedef uint8_t DWC_XGMAC_RESERVED_TYPE;




typedef uint32_t DWC_XGMAC_MAC_EXTENDED_CONFIGURATION_TYPE;
#define DWC_XGMAC_MAC_EXTENDED_CONFIGURATION_EIPG_MASK (0x7fUL)
#define DWC_XGMAC_MAC_EXTENDED_CONFIGURATION_EIPG_SHIFT (0UL)
#define DWC_XGMAC_MAC_EXTENDED_CONFIGURATION_TPRE_MASK (0x200UL)
#define DWC_XGMAC_MAC_EXTENDED_CONFIGURATION_TPRE_SHIFT (9UL)
#define DWC_XGMAC_MAC_EXTENDED_CONFIGURATION_ECRSFD_MASK (0x800000UL)
#define DWC_XGMAC_MAC_EXTENDED_CONFIGURATION_ECRSFD_SHIFT (23UL)
#define DWC_XGMAC_MAC_EXTENDED_CONFIGURATION_HD_MASK (0x1000000UL)
#define DWC_XGMAC_MAC_EXTENDED_CONFIGURATION_HD_SHIFT (24UL)




typedef volatile struct COMP_PACKED sDWC_XGMAC_RDBType {
    DWC_XGMAC_MAC_TX_CONFIGURATION_TYPE tx_configuration; /* OFFSET: 0x0 */
    DWC_XGMAC_MAC_RX_CONFIGURATION_TYPE rx_configuration; /* OFFSET: 0x4 */
    DWC_XGMAC_RESERVED_TYPE rsvd0[312]; /* OFFSET: 0x8 */
    DWC_XGMAC_MAC_EXTENDED_CONFIGURATION_TYPE extended_configuration; /* OFFSET: 0x140 */
    DWC_XGMAC_RESERVED_TYPE rsvd1[14268]; /* OFFSET: 0x144 */
} DWC_XGMAC_RDBType;


#define DWC_XGMAC_BASE                  (0x4C103000UL)



#define DWC_XGMAC_MAX_HW_ID             (1UL)


#define DWC_XGMAC_EXTENDED_MAC_CONFIGURATION_EIPG_VALUE  (0x2UL)


#define DWC_XGMAC_MAC_TX_CONFIGURATION_IPG_VALUE  (0x5UL)

#endif /* DWC_XGMAC_RDB_H */
