/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file hsm_misc_rdb.h
    @brief RDB File for HSM_MISC

    @version Orion_A0_20201104_SWDEV
*/

#ifndef HSM_MISC_RDB_H
#define HSM_MISC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t HSM_MISC_CLOCK_GATING_CONTROL_TYPE;
#define HSM_MISC_CLOCK_GATING_CONTROL_SPU_CLK_EN_MASK (0x1000000UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_SPU_CLK_EN_SHIFT (24UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_SPU_AXI_CLK_EN_MASK (0x800000UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_SPU_AXI_CLK_EN_SHIFT (23UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_DMA_AXI_CLK_EN_MASK (0x400000UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_DMA_AXI_CLK_EN_SHIFT (22UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_SRAM_CLK_EN_MASK (0x200000UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_SRAM_CLK_EN_SHIFT (21UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_IPC_CLK_EN_MASK (0x100000UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_IPC_CLK_EN_SHIFT (20UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_PKA_CLK_EN_MASK (0x80000UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_PKA_CLK_EN_SHIFT (19UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_RNG_CLK_EN_MASK (0x40000UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_RNG_CLK_EN_SHIFT (18UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_OTP_CLK_EN_MASK (0x20000UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_OTP_CLK_EN_SHIFT (17UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_WDG_CLK_EN_MASK (0x10000UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_WDG_CLK_EN_SHIFT (16UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_TIMER_REF_CLK_SEL_MASK (0x1f0UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_TIMER_REF_CLK_SEL_SHIFT (4UL)
#define HSM_MISC_CLOCK_GATING_CONTROL_TIMER_CLK_EN_MASK (0xfUL)
#define HSM_MISC_CLOCK_GATING_CONTROL_TIMER_CLK_EN_SHIFT (0UL)




typedef uint32_t HSM_MISC_BLOCK_RESET_TYPE;
#define HSM_MISC_BLOCK_RESET_SPU_RST_N_MASK (0x10UL)
#define HSM_MISC_BLOCK_RESET_SPU_RST_N_SHIFT (4UL)
#define HSM_MISC_BLOCK_RESET_IPC_RST_N_MASK (0x8UL)
#define HSM_MISC_BLOCK_RESET_IPC_RST_N_SHIFT (3UL)
#define HSM_MISC_BLOCK_RESET_WDG_RST_N_MASK (0x4UL)
#define HSM_MISC_BLOCK_RESET_WDG_RST_N_SHIFT (2UL)
#define HSM_MISC_BLOCK_RESET_TIMER23_RST_N_MASK (0x2UL)
#define HSM_MISC_BLOCK_RESET_TIMER23_RST_N_SHIFT (1UL)
#define HSM_MISC_BLOCK_RESET_TIMER01_RST_N_MASK (0x1UL)
#define HSM_MISC_BLOCK_RESET_TIMER01_RST_N_SHIFT (0UL)




typedef uint32_t HSM_MISC_PROC_MEM_TM_TYPE;
#define HSM_MISC_PROC_MEM_TM_IMEM_TM_MASK (0x3f80000UL)
#define HSM_MISC_PROC_MEM_TM_IMEM_TM_SHIFT (19UL)
#define HSM_MISC_PROC_MEM_TM_DMEM_TM_MASK (0xfe00UL)
#define HSM_MISC_PROC_MEM_TM_DMEM_TM_SHIFT (9UL)
#define HSM_MISC_PROC_MEM_TM_BOOTROM_TM_MASK (0x7fUL)
#define HSM_MISC_PROC_MEM_TM_BOOTROM_TM_SHIFT (0UL)




typedef uint32_t HSM_MISC_MISC_MEM_TM1_TYPE;
#define HSM_MISC_MISC_MEM_TM1_PKA_SRM_TM_MASK (0x3fc00000UL)
#define HSM_MISC_MISC_MEM_TM1_PKA_SRM_TM_SHIFT (22UL)
#define HSM_MISC_MISC_MEM_TM1_SRAM_TM_MASK (0x3fc00UL)
#define HSM_MISC_MISC_MEM_TM1_SRAM_TM_SHIFT (10UL)
#define HSM_MISC_MISC_MEM_TM1_SPUM_RF_TM_MASK (0x3ffUL)
#define HSM_MISC_MISC_MEM_TM1_SPUM_RF_TM_SHIFT (0UL)




typedef uint32_t HSM_MISC_MISC_MEM_TM2_TYPE;
#define HSM_MISC_MISC_MEM_TM2_SPUM_SP_TM_MASK (0x3fff000UL)
#define HSM_MISC_MISC_MEM_TM2_SPUM_SP_TM_SHIFT (12UL)
#define HSM_MISC_MISC_MEM_TM2_SPUM_SRF_TM_MASK (0xfffUL)
#define HSM_MISC_MISC_MEM_TM2_SPUM_SRF_TM_SHIFT (0UL)




typedef uint32_t HSM_MISC_MISC_MEM_CTRL_TYPE;
#define HSM_MISC_MISC_MEM_CTRL_PKA_SRF_STBY_MASK (0x40UL)
#define HSM_MISC_MISC_MEM_CTRL_PKA_SRF_STBY_SHIFT (6UL)
#define HSM_MISC_MISC_MEM_CTRL_SPUM_SRF_STBY_MASK (0x20UL)
#define HSM_MISC_MISC_MEM_CTRL_SPUM_SRF_STBY_SHIFT (5UL)
#define HSM_MISC_MISC_MEM_CTRL_SPUM_SP_STBY_MASK (0x18UL)
#define HSM_MISC_MISC_MEM_CTRL_SPUM_SP_STBY_SHIFT (3UL)
#define HSM_MISC_MISC_MEM_CTRL_SPUM_RF_STBY_MASK (0x4UL)
#define HSM_MISC_MISC_MEM_CTRL_SPUM_RF_STBY_SHIFT (2UL)
#define HSM_MISC_MISC_MEM_CTRL_MEM_STBY_MASK (0x2UL)
#define HSM_MISC_MISC_MEM_CTRL_MEM_STBY_SHIFT (1UL)
#define HSM_MISC_MISC_MEM_CTRL_MEM_LVM_MASK (0x1UL)
#define HSM_MISC_MISC_MEM_CTRL_MEM_LVM_SHIFT (0UL)




typedef uint32_t HSM_MISC_SPUM_MISC_CFG_REG_TYPE;
#define HSM_MISC_SPUM_MISC_CFG_REG_IDDQ_EN_MASK (0x4UL)
#define HSM_MISC_SPUM_MISC_CFG_REG_IDDQ_EN_SHIFT (2UL)
#define HSM_MISC_SPUM_MISC_CFG_REG_EXPORT_MODE_MASK (0x2UL)
#define HSM_MISC_SPUM_MISC_CFG_REG_EXPORT_MODE_SHIFT (1UL)
#define HSM_MISC_SPUM_MISC_CFG_REG_IS_SECURE_MASK (0x1UL)
#define HSM_MISC_SPUM_MISC_CFG_REG_IS_SECURE_SHIFT (0UL)




typedef uint32_t HSM_MISC_RNG_MISC_CFG_REG_TYPE;
#define HSM_MISC_RNG_MISC_CFG_REG_IDDQ_EN_MASK (0x1UL)
#define HSM_MISC_RNG_MISC_CFG_REG_IDDQ_EN_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0A_ICV_0A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0A_ICV_0A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0B_ICV_0B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0B_ICV_0B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0C_ICV_0C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0C_ICV_0C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0D_ICV_0D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0D_ICV_0D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1A_ICV_1A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1A_ICV_1A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1B_ICV_1B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1B_ICV_1B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1C_ICV_1C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1C_ICV_1C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1D_ICV_1D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1D_ICV_1D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2A_ICV_2A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2A_ICV_2A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2B_ICV_2B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2B_ICV_2B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2C_ICV_2C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2C_ICV_2C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2D_ICV_2D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2D_ICV_2D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3A_ICV_3A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3A_ICV_3A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3B_ICV_3B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3B_ICV_3B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3C_ICV_3C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3C_ICV_3C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3D_ICV_3D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3D_ICV_3D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0A_ICV_0A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0A_ICV_0A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0B_ICV_0B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0B_ICV_0B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0C_ICV_0C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0C_ICV_0C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0D_ICV_0D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0D_ICV_0D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1A_ICV_1A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1A_ICV_1A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1B_ICV_1B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1B_ICV_1B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1C_ICV_1C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1C_ICV_1C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1D_ICV_1D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1D_ICV_1D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2A_ICV_2A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2A_ICV_2A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2B_ICV_2B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2B_ICV_2B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2C_ICV_2C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2C_ICV_2C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2D_ICV_2D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2D_ICV_2D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3A_ICV_3A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3A_ICV_3A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3B_ICV_3B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3B_ICV_3B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3C_ICV_3C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3C_ICV_3C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3D_ICV_3D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3D_ICV_3D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0A_ICV_0A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0A_ICV_0A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0B_ICV_0B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0B_ICV_0B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0C_ICV_0C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0C_ICV_0C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0D_ICV_0D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0D_ICV_0D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1A_ICV_1A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1A_ICV_1A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1B_ICV_1B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1B_ICV_1B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1C_ICV_1C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1C_ICV_1C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1D_ICV_1D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1D_ICV_1D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2A_ICV_2A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2A_ICV_2A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2B_ICV_2B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2B_ICV_2B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2C_ICV_2C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2C_ICV_2C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2D_ICV_2D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2D_ICV_2D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3A_ICV_3A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3A_ICV_3A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3B_ICV_3B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3B_ICV_3B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3C_ICV_3C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3C_ICV_3C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3D_ICV_3D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3D_ICV_3D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0A_ICV_0A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0A_ICV_0A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0B_ICV_0B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0B_ICV_0B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0C_ICV_0C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0C_ICV_0C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0D_ICV_0D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0D_ICV_0D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1A_ICV_1A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1A_ICV_1A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1B_ICV_1B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1B_ICV_1B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1C_ICV_1C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1C_ICV_1C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1D_ICV_1D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1D_ICV_1D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2A_ICV_2A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2A_ICV_2A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2B_ICV_2B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2B_ICV_2B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2C_ICV_2C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2C_ICV_2C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2D_ICV_2D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2D_ICV_2D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3A_ICV_3A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3A_ICV_3A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3B_ICV_3B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3B_ICV_3B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3C_ICV_3C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3C_ICV_3C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3D_ICV_3D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3D_ICV_3D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3E_TYPE;




typedef uint8_t HSM_MISC_RESERVED_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0A_ICV_0A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0A_ICV_0A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0B_ICV_0B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0B_ICV_0B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0C_ICV_0C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0C_ICV_0C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0D_ICV_0D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0D_ICV_0D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1A_ICV_1A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1A_ICV_1A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1B_ICV_1B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1B_ICV_1B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1C_ICV_1C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1C_ICV_1C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1D_ICV_1D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1D_ICV_1D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2A_ICV_2A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2A_ICV_2A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2B_ICV_2B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2B_ICV_2B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2C_ICV_2C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2C_ICV_2C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2D_ICV_2D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2D_ICV_2D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3A_ICV_3A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3A_ICV_3A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3B_ICV_3B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3B_ICV_3B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3C_ICV_3C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3C_ICV_3C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3D_ICV_3D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3D_ICV_3D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0A_ICV_0A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0A_ICV_0A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0B_ICV_0B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0B_ICV_0B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0C_ICV_0C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0C_ICV_0C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0D_ICV_0D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0D_ICV_0D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1A_ICV_1A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1A_ICV_1A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1B_ICV_1B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1B_ICV_1B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1C_ICV_1C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1C_ICV_1C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1D_ICV_1D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1D_ICV_1D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2A_ICV_2A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2A_ICV_2A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2B_ICV_2B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2B_ICV_2B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2C_ICV_2C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2C_ICV_2C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2D_ICV_2D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2D_ICV_2D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2E_TYPE;




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3A_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3A_ICV_3A_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3A_ICV_3A_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3B_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3B_ICV_3B_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3B_ICV_3B_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3C_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3C_ICV_3C_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3C_ICV_3C_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3D_TYPE;
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3D_ICV_3D_MASK (0xffffffffUL)
#define HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3D_ICV_3D_SHIFT (0UL)




typedef uint32_t HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3E_TYPE;




typedef uint32_t HSM_MISC_INTERRUPT_TYPE;
#define HSM_MISC_INTERRUPT_SECURITY_COMPROMISE_INT_MASK (0x1UL)
#define HSM_MISC_INTERRUPT_SECURITY_COMPROMISE_INT_SHIFT (0UL)




typedef uint32_t HSM_MISC_INTERRUPT_EN_TYPE;
#define HSM_MISC_INTERRUPT_EN_SECURITY_COMPROMISE_INT_EN_MASK (0x1UL)
#define HSM_MISC_INTERRUPT_EN_SECURITY_COMPROMISE_INT_EN_SHIFT (0UL)




typedef uint32_t HSM_MISC_INTERRUPT_CLEAR_TYPE;
#define HSM_MISC_INTERRUPT_CLEAR_SECURITY_COMPROMISE_INT_CLR_MASK (0x1UL)
#define HSM_MISC_INTERRUPT_CLEAR_SECURITY_COMPROMISE_INT_CLR_SHIFT (0UL)




typedef uint32_t HSM_MISC_ASTMI_TYPE;
#define HSM_MISC_ASTMI_SPU_TIMOUT_MON_INT_MASK (0x20UL)
#define HSM_MISC_ASTMI_SPU_TIMOUT_MON_INT_SHIFT (5UL)
#define HSM_MISC_ASTMI_DMA_SLAVE_TIMOUT_MON_INT_MASK (0x10UL)
#define HSM_MISC_ASTMI_DMA_SLAVE_TIMOUT_MON_INT_SHIFT (4UL)
#define HSM_MISC_ASTMI_TO_CPU_SYS_TIMOUT_MON_INT_MASK (0x8UL)
#define HSM_MISC_ASTMI_TO_CPU_SYS_TIMOUT_MON_INT_SHIFT (3UL)
#define HSM_MISC_ASTMI_IPC_TIMOUT_MON_INT_MASK (0x4UL)
#define HSM_MISC_ASTMI_IPC_TIMOUT_MON_INT_SHIFT (2UL)
#define HSM_MISC_ASTMI_SRAM_TOP_TIMOUT_MON_INT_MASK (0x2UL)
#define HSM_MISC_ASTMI_SRAM_TOP_TIMOUT_MON_INT_SHIFT (1UL)
#define HSM_MISC_ASTMI_AHB_N_APB_TIMOUT_MON_INT_MASK (0x1UL)
#define HSM_MISC_ASTMI_AHB_N_APB_TIMOUT_MON_INT_SHIFT (0UL)




typedef uint32_t HSM_MISC_ASTMIE_TYPE;
#define HSM_MISC_ASTMIE_SPU_TIMOUT_MON_INT_EN_MASK (0x20UL)
#define HSM_MISC_ASTMIE_SPU_TIMOUT_MON_INT_EN_SHIFT (5UL)
#define HSM_MISC_ASTMIE_DMA_SLAVE_TIMOUT_MON_INT_EN_MASK (0x10UL)
#define HSM_MISC_ASTMIE_DMA_SLAVE_TIMOUT_MON_INT_EN_SHIFT (4UL)
#define HSM_MISC_ASTMIE_TO_CPU_SYS_TIMOUT_MON_INT_EN_MASK (0x8UL)
#define HSM_MISC_ASTMIE_TO_CPU_SYS_TIMOUT_MON_INT_EN_SHIFT (3UL)
#define HSM_MISC_ASTMIE_IPC_TIMOUT_MON_INT_EN_MASK (0x4UL)
#define HSM_MISC_ASTMIE_IPC_TIMOUT_MON_INT_EN_SHIFT (2UL)
#define HSM_MISC_ASTMIE_SRAM_TOP_TIMOUT_MON_INT_EN_MASK (0x2UL)
#define HSM_MISC_ASTMIE_SRAM_TOP_TIMOUT_MON_INT_EN_SHIFT (1UL)
#define HSM_MISC_ASTMIE_AHB_N_APB_TIMOUT_MON_INT_EN_MASK (0x1UL)
#define HSM_MISC_ASTMIE_AHB_N_APB_TIMOUT_MON_INT_EN_SHIFT (0UL)




typedef uint32_t HSM_MISC_ASTMIC_TYPE;
#define HSM_MISC_ASTMIC_SPU_TIMOUT_MON_INT_CLR_MASK (0x20UL)
#define HSM_MISC_ASTMIC_SPU_TIMOUT_MON_INT_CLR_SHIFT (5UL)
#define HSM_MISC_ASTMIC_DMA_SLAVE_TIMOUT_MON_INT_CLR_MASK (0x10UL)
#define HSM_MISC_ASTMIC_DMA_SLAVE_TIMOUT_MON_INT_CLR_SHIFT (4UL)
#define HSM_MISC_ASTMIC_TO_CPU_SYS_TIMOUT_MON_INT_CLR_MASK (0x8UL)
#define HSM_MISC_ASTMIC_TO_CPU_SYS_TIMOUT_MON_INT_CLR_SHIFT (3UL)
#define HSM_MISC_ASTMIC_IPC_TIMOUT_MON_INT_CLR_MASK (0x4UL)
#define HSM_MISC_ASTMIC_IPC_TIMOUT_MON_INT_CLR_SHIFT (2UL)
#define HSM_MISC_ASTMIC_SRAM_TOP_TIMOUT_MON_INT_CLR_MASK (0x2UL)
#define HSM_MISC_ASTMIC_SRAM_TOP_TIMOUT_MON_INT_CLR_SHIFT (1UL)
#define HSM_MISC_ASTMIC_AHB_N_APB_TIMOUT_MON_INT_CLR_MASK (0x1UL)
#define HSM_MISC_ASTMIC_AHB_N_APB_TIMOUT_MON_INT_CLR_SHIFT (0UL)




typedef uint32_t HSM_MISC_DASTM_TYPE;
#define HSM_MISC_DASTM_SPU_TIMOUT_MON_DISABLE_MASK (0x20UL)
#define HSM_MISC_DASTM_SPU_TIMOUT_MON_DISABLE_SHIFT (5UL)
#define HSM_MISC_DASTM_DMA_SLAVE_TIMOUT_MON_DISABLE_MASK (0x10UL)
#define HSM_MISC_DASTM_DMA_SLAVE_TIMOUT_MON_DISABLE_SHIFT (4UL)
#define HSM_MISC_DASTM_TO_CPU_SYS_TIMOUT_MON_DISABLE_MASK (0x8UL)
#define HSM_MISC_DASTM_TO_CPU_SYS_TIMOUT_MON_DISABLE_SHIFT (3UL)
#define HSM_MISC_DASTM_IPC_TIMOUT_MON_DISABLE_MASK (0x4UL)
#define HSM_MISC_DASTM_IPC_TIMOUT_MON_DISABLE_SHIFT (2UL)
#define HSM_MISC_DASTM_SRAM_TOP_TIMOUT_MON_DISABLE_MASK (0x2UL)
#define HSM_MISC_DASTM_SRAM_TOP_TIMOUT_MON_DISABLE_SHIFT (1UL)
#define HSM_MISC_DASTM_AHB_N_APB_TIMOUT_MON_DISABLE_MASK (0x1UL)
#define HSM_MISC_DASTM_AHB_N_APB_TIMOUT_MON_DISABLE_SHIFT (0UL)




typedef uint32_t HSM_MISC_ECC_INTERRUPT_TYPE;
#define HSM_MISC_ECC_INTERRUPT_SPUM_KEK_DED_FLAG_INT_MASK (0x2000000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_KEK_DED_FLAG_INT_SHIFT (25UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_KEK_SEC_FLAG_INT_MASK (0x1000000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_KEK_SEC_FLAG_INT_SHIFT (24UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_AUBPS_DED_FLAG_INT_MASK (0x800000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_AUBPS_DED_FLAG_INT_SHIFT (23UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_AUBPS_SEC_FLAG_INT_MASK (0x400000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_AUBPS_SEC_FLAG_INT_SHIFT (22UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_CREAES_DED_FLAG_INT_MASK (0x200000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_CREAES_DED_FLAG_INT_SHIFT (21UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_CREAES_SEC_FLAG_INT_MASK (0x100000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_CREAES_SEC_FLAG_INT_SHIFT (20UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_CRBPS_DED_FLAG_INT_MASK (0x80000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_CRBPS_DED_FLAG_INT_SHIFT (19UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_CRBPS_SEC_FLAG_INT_MASK (0x40000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_CRBPS_SEC_FLAG_INT_SHIFT (18UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PAFIFO_DED_FLAG_INT_MASK (0x20000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PAFIFO_DED_FLAG_INT_SHIFT (17UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PAFIFO_SEC_FLAG_INT_MASK (0x10000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PAFIFO_SEC_FLAG_INT_SHIFT (16UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PASCTX_DED_FLAG_INT_MASK (0x8000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PASCTX_DED_FLAG_INT_SHIFT (15UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PASCTX_SEC_FLAG_INT_MASK (0x4000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PASCTX_SEC_FLAG_INT_SHIFT (14UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PPSUPDT_DED_FLAG_INT_MASK (0x2000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PPSUPDT_DED_FLAG_INT_SHIFT (13UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PPSUPDT_SEC_FLAG_INT_MASK (0x1000UL)
#define HSM_MISC_ECC_INTERRUPT_SPUM_PPSUPDT_SEC_FLAG_INT_SHIFT (12UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_OPP_DED_FLAG_INT_MASK (0x800UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_OPP_DED_FLAG_INT_SHIFT (11UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_OPP_SEC_FLAG_INT_MASK (0x400UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_OPP_SEC_FLAG_INT_SHIFT (10UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_LIR1_DED_FLAG_INT_MASK (0x200UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_LIR1_DED_FLAG_INT_SHIFT (9UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_LIR1_SEC_FLAG_INT_MASK (0x100UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_LIR1_SEC_FLAG_INT_SHIFT (8UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_LIR0_DED_FLAG_INT_MASK (0x80UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_LIR0_DED_FLAG_INT_SHIFT (7UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_LIR0_SEC_FLAG_INT_MASK (0x40UL)
#define HSM_MISC_ECC_INTERRUPT_PKA_LIR0_SEC_FLAG_INT_SHIFT (6UL)
#define HSM_MISC_ECC_INTERRUPT_DMEM_DED_FLAG_INT_MASK (0x20UL)
#define HSM_MISC_ECC_INTERRUPT_DMEM_DED_FLAG_INT_SHIFT (5UL)
#define HSM_MISC_ECC_INTERRUPT_DMEM_SEC_FLAG_INT_MASK (0x10UL)
#define HSM_MISC_ECC_INTERRUPT_DMEM_SEC_FLAG_INT_SHIFT (4UL)
#define HSM_MISC_ECC_INTERRUPT_IMEM_DED_FLAG_INT_MASK (0x8UL)
#define HSM_MISC_ECC_INTERRUPT_IMEM_DED_FLAG_INT_SHIFT (3UL)
#define HSM_MISC_ECC_INTERRUPT_IMEM_SEC_FLAG_INT_MASK (0x4UL)
#define HSM_MISC_ECC_INTERRUPT_IMEM_SEC_FLAG_INT_SHIFT (2UL)
#define HSM_MISC_ECC_INTERRUPT_SRAM_DED_FLAG_INT_MASK (0x2UL)
#define HSM_MISC_ECC_INTERRUPT_SRAM_DED_FLAG_INT_SHIFT (1UL)
#define HSM_MISC_ECC_INTERRUPT_SRAM_SEC_FLAG_INT_MASK (0x1UL)
#define HSM_MISC_ECC_INTERRUPT_SRAM_SEC_FLAG_INT_SHIFT (0UL)




typedef uint32_t HSM_MISC_EIER_TYPE;
#define HSM_MISC_EIER_SPUM_KEK_ECC_DED_FLAG_INT_EN_MASK (0x2000000UL)
#define HSM_MISC_EIER_SPUM_KEK_ECC_DED_FLAG_INT_EN_SHIFT (25UL)
#define HSM_MISC_EIER_SPUM_KEK_ECC_SEC_FLAG_INT_EN_MASK (0x1000000UL)
#define HSM_MISC_EIER_SPUM_KEK_ECC_SEC_FLAG_INT_EN_SHIFT (24UL)
#define HSM_MISC_EIER_SPUM_AUBPS_ECC_DED_FLAG_INT_EN_MASK (0x800000UL)
#define HSM_MISC_EIER_SPUM_AUBPS_ECC_DED_FLAG_INT_EN_SHIFT (23UL)
#define HSM_MISC_EIER_SPUM_AUBPS_ECC_SEC_FLAG_INT_EN_MASK (0x400000UL)
#define HSM_MISC_EIER_SPUM_AUBPS_ECC_SEC_FLAG_INT_EN_SHIFT (22UL)
#define HSM_MISC_EIER_SPUM_CREAES_ECC_DED_FLAG_INT_EN_MASK (0x200000UL)
#define HSM_MISC_EIER_SPUM_CREAES_ECC_DED_FLAG_INT_EN_SHIFT (21UL)
#define HSM_MISC_EIER_SPUM_CREAES_ECC_SEC_FLAG_INT_EN_MASK (0x100000UL)
#define HSM_MISC_EIER_SPUM_CREAES_ECC_SEC_FLAG_INT_EN_SHIFT (20UL)
#define HSM_MISC_EIER_SPUM_CRBPS_ECC_DED_FLAG_INT_EN_MASK (0x80000UL)
#define HSM_MISC_EIER_SPUM_CRBPS_ECC_DED_FLAG_INT_EN_SHIFT (19UL)
#define HSM_MISC_EIER_SPUM_CRBPS_ECC_SEC_FLAG_INT_EN_MASK (0x40000UL)
#define HSM_MISC_EIER_SPUM_CRBPS_ECC_SEC_FLAG_INT_EN_SHIFT (18UL)
#define HSM_MISC_EIER_SPUM_PAFIFO_ECC_DED_FLAG_INT_EN_MASK (0x20000UL)
#define HSM_MISC_EIER_SPUM_PAFIFO_ECC_DED_FLAG_INT_EN_SHIFT (17UL)
#define HSM_MISC_EIER_SPUM_PAFIFO_ECC_SEC_FLAG_INT_EN_MASK (0x10000UL)
#define HSM_MISC_EIER_SPUM_PAFIFO_ECC_SEC_FLAG_INT_EN_SHIFT (16UL)
#define HSM_MISC_EIER_SPUM_PASCTX_ECC_DED_FLAG_INT_EN_MASK (0x8000UL)
#define HSM_MISC_EIER_SPUM_PASCTX_ECC_DED_FLAG_INT_EN_SHIFT (15UL)
#define HSM_MISC_EIER_SPUM_PASCTX_ECC_SEC_FLAG_INT_EN_MASK (0x4000UL)
#define HSM_MISC_EIER_SPUM_PASCTX_ECC_SEC_FLAG_INT_EN_SHIFT (14UL)
#define HSM_MISC_EIER_SPUM_PPSUPDT_ECC_DED_FLAG_INT_EN_MASK (0x2000UL)
#define HSM_MISC_EIER_SPUM_PPSUPDT_ECC_DED_FLAG_INT_EN_SHIFT (13UL)
#define HSM_MISC_EIER_SPUM_PPSUPDT_ECC_SEC_FLAG_INT_EN_MASK (0x1000UL)
#define HSM_MISC_EIER_SPUM_PPSUPDT_ECC_SEC_FLAG_INT_EN_SHIFT (12UL)
#define HSM_MISC_EIER_PKA_OPP_ECC_DED_FLAG_INT_EN_MASK (0x800UL)
#define HSM_MISC_EIER_PKA_OPP_ECC_DED_FLAG_INT_EN_SHIFT (11UL)
#define HSM_MISC_EIER_PKA_OPP_ECC_SEC_FLAG_INT_EN_MASK (0x400UL)
#define HSM_MISC_EIER_PKA_OPP_ECC_SEC_FLAG_INT_EN_SHIFT (10UL)
#define HSM_MISC_EIER_PKA_LIR1_ECC_DED_FLAG_INT_EN_MASK (0x200UL)
#define HSM_MISC_EIER_PKA_LIR1_ECC_DED_FLAG_INT_EN_SHIFT (9UL)
#define HSM_MISC_EIER_PKA_LIR1_ECC_SEC_FLAG_INT_EN_MASK (0x100UL)
#define HSM_MISC_EIER_PKA_LIR1_ECC_SEC_FLAG_INT_EN_SHIFT (8UL)
#define HSM_MISC_EIER_PKA_LIR0_ECC_DED_FLAG_INT_EN_MASK (0x80UL)
#define HSM_MISC_EIER_PKA_LIR0_ECC_DED_FLAG_INT_EN_SHIFT (7UL)
#define HSM_MISC_EIER_PKA_LIR0_ECC_SEC_FLAG_INT_EN_MASK (0x40UL)
#define HSM_MISC_EIER_PKA_LIR0_ECC_SEC_FLAG_INT_EN_SHIFT (6UL)
#define HSM_MISC_EIER_DMEM_ECC_DED_FLAG_INT_EN_MASK (0x20UL)
#define HSM_MISC_EIER_DMEM_ECC_DED_FLAG_INT_EN_SHIFT (5UL)
#define HSM_MISC_EIER_DMEM_ECC_SEC_FLAG_INT_EN_MASK (0x10UL)
#define HSM_MISC_EIER_DMEM_ECC_SEC_FLAG_INT_EN_SHIFT (4UL)
#define HSM_MISC_EIER_IMEM_ECC_DED_FLAG_INT_EN_MASK (0x8UL)
#define HSM_MISC_EIER_IMEM_ECC_DED_FLAG_INT_EN_SHIFT (3UL)
#define HSM_MISC_EIER_IMEM_ECC_SEC_FLAG_INT_EN_MASK (0x4UL)
#define HSM_MISC_EIER_IMEM_ECC_SEC_FLAG_INT_EN_SHIFT (2UL)
#define HSM_MISC_EIER_SRAM_ECC_DED_FLAG_INT_EN_MASK (0x2UL)
#define HSM_MISC_EIER_SRAM_ECC_DED_FLAG_INT_EN_SHIFT (1UL)
#define HSM_MISC_EIER_SRAM_ECC_SEC_FLAG_INT_EN_MASK (0x1UL)
#define HSM_MISC_EIER_SRAM_ECC_SEC_FLAG_INT_EN_SHIFT (0UL)




typedef uint32_t HSM_MISC_EICR_TYPE;
#define HSM_MISC_EICR_SPUM_KEK_ECC_DED_FLAG_INT_CLR_MASK (0x2000000UL)
#define HSM_MISC_EICR_SPUM_KEK_ECC_DED_FLAG_INT_CLR_SHIFT (25UL)
#define HSM_MISC_EICR_SPUM_KEK_ECC_SEC_FLAG_INT_CLR_MASK (0x1000000UL)
#define HSM_MISC_EICR_SPUM_KEK_ECC_SEC_FLAG_INT_CLR_SHIFT (24UL)
#define HSM_MISC_EICR_SPUM_AUBPS_ECC_DED_FLAG_INT_CLR_MASK (0x800000UL)
#define HSM_MISC_EICR_SPUM_AUBPS_ECC_DED_FLAG_INT_CLR_SHIFT (23UL)
#define HSM_MISC_EICR_SPUM_AUBPS_ECC_SEC_FLAG_INT_CLR_MASK (0x400000UL)
#define HSM_MISC_EICR_SPUM_AUBPS_ECC_SEC_FLAG_INT_CLR_SHIFT (22UL)
#define HSM_MISC_EICR_SPUM_CREAES_ECC_DED_FLAG_INT_CLR_MASK (0x200000UL)
#define HSM_MISC_EICR_SPUM_CREAES_ECC_DED_FLAG_INT_CLR_SHIFT (21UL)
#define HSM_MISC_EICR_SPUM_CREAES_ECC_SEC_FLAG_INT_CLR_MASK (0x100000UL)
#define HSM_MISC_EICR_SPUM_CREAES_ECC_SEC_FLAG_INT_CLR_SHIFT (20UL)
#define HSM_MISC_EICR_SPUM_CRBPS_ECC_DED_FLAG_INT_CLR_MASK (0x80000UL)
#define HSM_MISC_EICR_SPUM_CRBPS_ECC_DED_FLAG_INT_CLR_SHIFT (19UL)
#define HSM_MISC_EICR_SPUM_CRBPS_ECC_SEC_FLAG_INT_CLR_MASK (0x40000UL)
#define HSM_MISC_EICR_SPUM_CRBPS_ECC_SEC_FLAG_INT_CLR_SHIFT (18UL)
#define HSM_MISC_EICR_SPUM_PAFIFO_ECC_DED_FLAG_INT_CLR_MASK (0x20000UL)
#define HSM_MISC_EICR_SPUM_PAFIFO_ECC_DED_FLAG_INT_CLR_SHIFT (17UL)
#define HSM_MISC_EICR_SPUM_PAFIFO_ECC_SEC_FLAG_INT_CLR_MASK (0x10000UL)
#define HSM_MISC_EICR_SPUM_PAFIFO_ECC_SEC_FLAG_INT_CLR_SHIFT (16UL)
#define HSM_MISC_EICR_SPUM_PASCTX_ECC_DED_FLAG_INT_CLR_MASK (0x8000UL)
#define HSM_MISC_EICR_SPUM_PASCTX_ECC_DED_FLAG_INT_CLR_SHIFT (15UL)
#define HSM_MISC_EICR_SPUM_PASCTX_ECC_SEC_FLAG_INT_CLR_MASK (0x4000UL)
#define HSM_MISC_EICR_SPUM_PASCTX_ECC_SEC_FLAG_INT_CLR_SHIFT (14UL)
#define HSM_MISC_EICR_SPUM_PPSUPDT_ECC_DED_FLAG_INT_CLR_MASK (0x2000UL)
#define HSM_MISC_EICR_SPUM_PPSUPDT_ECC_DED_FLAG_INT_CLR_SHIFT (13UL)
#define HSM_MISC_EICR_SPUM_PPSUPDT_ECC_SEC_FLAG_INT_CLR_MASK (0x1000UL)
#define HSM_MISC_EICR_SPUM_PPSUPDT_ECC_SEC_FLAG_INT_CLR_SHIFT (12UL)
#define HSM_MISC_EICR_PKA_OPP_ECC_DED_FLAG_INT_CLR_MASK (0x800UL)
#define HSM_MISC_EICR_PKA_OPP_ECC_DED_FLAG_INT_CLR_SHIFT (11UL)
#define HSM_MISC_EICR_PKA_OPP_ECC_SEC_FLAG_INT_CLR_MASK (0x400UL)
#define HSM_MISC_EICR_PKA_OPP_ECC_SEC_FLAG_INT_CLR_SHIFT (10UL)
#define HSM_MISC_EICR_PKA_LIR1_ECC_DED_FLAG_INT_CLR_MASK (0x200UL)
#define HSM_MISC_EICR_PKA_LIR1_ECC_DED_FLAG_INT_CLR_SHIFT (9UL)
#define HSM_MISC_EICR_PKA_LIR1_ECC_SEC_FLAG_INT_CLR_MASK (0x100UL)
#define HSM_MISC_EICR_PKA_LIR1_ECC_SEC_FLAG_INT_CLR_SHIFT (8UL)
#define HSM_MISC_EICR_PKA_LIR0_ECC_DED_FLAG_INT_CLR_MASK (0x80UL)
#define HSM_MISC_EICR_PKA_LIR0_ECC_DED_FLAG_INT_CLR_SHIFT (7UL)
#define HSM_MISC_EICR_PKA_LIR0_ECC_SEC_FLAG_INT_CLR_MASK (0x40UL)
#define HSM_MISC_EICR_PKA_LIR0_ECC_SEC_FLAG_INT_CLR_SHIFT (6UL)
#define HSM_MISC_EICR_DMEM_ECC_DED_FLAG_INT_CLR_MASK (0x20UL)
#define HSM_MISC_EICR_DMEM_ECC_DED_FLAG_INT_CLR_SHIFT (5UL)
#define HSM_MISC_EICR_DMEM_ECC_SEC_FLAG_INT_CLR_MASK (0x10UL)
#define HSM_MISC_EICR_DMEM_ECC_SEC_FLAG_INT_CLR_SHIFT (4UL)
#define HSM_MISC_EICR_IMEM_ECC_DED_FLAG_INT_CLR_MASK (0x8UL)
#define HSM_MISC_EICR_IMEM_ECC_DED_FLAG_INT_CLR_SHIFT (3UL)
#define HSM_MISC_EICR_IMEM_ECC_SEC_FLAG_INT_CLR_MASK (0x4UL)
#define HSM_MISC_EICR_IMEM_ECC_SEC_FLAG_INT_CLR_SHIFT (2UL)
#define HSM_MISC_EICR_SRAM_ECC_DED_FLAG_INT_CLR_MASK (0x2UL)
#define HSM_MISC_EICR_SRAM_ECC_DED_FLAG_INT_CLR_SHIFT (1UL)
#define HSM_MISC_EICR_SRAM_ECC_SEC_FLAG_INT_CLR_MASK (0x1UL)
#define HSM_MISC_EICR_SRAM_ECC_SEC_FLAG_INT_CLR_SHIFT (0UL)




typedef uint32_t HSM_MISC_INIT_MEM_TYPE;
#define HSM_MISC_INIT_MEM_DTRIGGER_INIT_MASK (0x20UL)
#define HSM_MISC_INIT_MEM_DTRIGGER_INIT_SHIFT (5UL)
#define HSM_MISC_INIT_MEM_DDONE_INIT_MASK (0x10UL)
#define HSM_MISC_INIT_MEM_DDONE_INIT_SHIFT (4UL)
#define HSM_MISC_INIT_MEM_ITRIGGER_INIT_MASK (0x8UL)
#define HSM_MISC_INIT_MEM_ITRIGGER_INIT_SHIFT (3UL)
#define HSM_MISC_INIT_MEM_IDONE_INIT_MASK (0x4UL)
#define HSM_MISC_INIT_MEM_IDONE_INIT_SHIFT (2UL)
#define HSM_MISC_INIT_MEM_SRAM_TRIGGER_INIT_MASK (0x2UL)
#define HSM_MISC_INIT_MEM_SRAM_TRIGGER_INIT_SHIFT (1UL)
#define HSM_MISC_INIT_MEM_SRAM_DONE_INIT_MASK (0x1UL)
#define HSM_MISC_INIT_MEM_SRAM_DONE_INIT_SHIFT (0UL)




typedef uint32_t HSM_MISC_SPARE_REG0_TYPE;
#define HSM_MISC_SPARE_REG0_REG0_MASK (0xffffffffUL)
#define HSM_MISC_SPARE_REG0_REG0_SHIFT (0UL)




typedef uint32_t HSM_MISC_SPARE_REG1_TYPE;
#define HSM_MISC_SPARE_REG1_REG1_MASK (0xffffffffUL)
#define HSM_MISC_SPARE_REG1_REG1_SHIFT (0UL)




typedef uint32_t HSM_MISC_SPARE_REG2_TYPE;
#define HSM_MISC_SPARE_REG2_REG2_MASK (0xffffffffUL)
#define HSM_MISC_SPARE_REG2_REG2_SHIFT (0UL)




typedef uint32_t HSM_MISC_SPARE_REG3_TYPE;
#define HSM_MISC_SPARE_REG3_REG3_MASK (0xffffffffUL)
#define HSM_MISC_SPARE_REG3_REG3_SHIFT (0UL)




typedef volatile struct COMP_PACKED sHSM_MISC_RDBType {
    HSM_MISC_CLOCK_GATING_CONTROL_TYPE clock_gating_control; /* OFFSET: 0x0 */
    HSM_MISC_BLOCK_RESET_TYPE block_reset; /* OFFSET: 0x4 */
    HSM_MISC_PROC_MEM_TM_TYPE proc_mem_tm; /* OFFSET: 0x8 */
    HSM_MISC_MISC_MEM_TM1_TYPE misc_mem_tm1; /* OFFSET: 0xc */
    HSM_MISC_MISC_MEM_TM2_TYPE misc_mem_tm2; /* OFFSET: 0x10 */
    HSM_MISC_MISC_MEM_CTRL_TYPE misc_mem_ctrl; /* OFFSET: 0x14 */
    HSM_MISC_SPUM_MISC_CFG_REG_TYPE spum_misc_cfg_reg; /* OFFSET: 0x18 */
    HSM_MISC_RNG_MISC_CFG_REG_TYPE rng_misc_cfg_reg; /* OFFSET: 0x1c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0A_TYPE link_authenticaton_key_port0_0a; /* OFFSET: 0x20 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0B_TYPE link_authenticaton_key_port0_0b; /* OFFSET: 0x24 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0C_TYPE link_authenticaton_key_port0_0c; /* OFFSET: 0x28 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0D_TYPE link_authenticaton_key_port0_0d; /* OFFSET: 0x2c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_0E_TYPE link_authenticaton_key_port0_0e; /* OFFSET: 0x30 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1A_TYPE link_authenticaton_key_port0_1a; /* OFFSET: 0x34 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1B_TYPE link_authenticaton_key_port0_1b; /* OFFSET: 0x38 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1C_TYPE link_authenticaton_key_port0_1c; /* OFFSET: 0x3c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1D_TYPE link_authenticaton_key_port0_1d; /* OFFSET: 0x40 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_1E_TYPE link_authenticaton_key_port0_1e; /* OFFSET: 0x44 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2A_TYPE link_authenticaton_key_port0_2a; /* OFFSET: 0x48 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2B_TYPE link_authenticaton_key_port0_2b; /* OFFSET: 0x4c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2C_TYPE link_authenticaton_key_port0_2c; /* OFFSET: 0x50 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2D_TYPE link_authenticaton_key_port0_2d; /* OFFSET: 0x54 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_2E_TYPE link_authenticaton_key_port0_2e; /* OFFSET: 0x58 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3A_TYPE link_authenticaton_key_port0_3a; /* OFFSET: 0x5c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3B_TYPE link_authenticaton_key_port0_3b; /* OFFSET: 0x60 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3C_TYPE link_authenticaton_key_port0_3c; /* OFFSET: 0x64 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3D_TYPE link_authenticaton_key_port0_3d; /* OFFSET: 0x68 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT0_3E_TYPE link_authenticaton_key_port0_3e; /* OFFSET: 0x6c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0A_TYPE link_authenticaton_key_port1_0a; /* OFFSET: 0x70 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0B_TYPE link_authenticaton_key_port1_0b; /* OFFSET: 0x74 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0C_TYPE link_authenticaton_key_port1_0c; /* OFFSET: 0x78 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0D_TYPE link_authenticaton_key_port1_0d; /* OFFSET: 0x7c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_0E_TYPE link_authenticaton_key_port1_0e; /* OFFSET: 0x80 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1A_TYPE link_authenticaton_key_port1_1a; /* OFFSET: 0x84 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1B_TYPE link_authenticaton_key_port1_1b; /* OFFSET: 0x88 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1C_TYPE link_authenticaton_key_port1_1c; /* OFFSET: 0x8c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1D_TYPE link_authenticaton_key_port1_1d; /* OFFSET: 0x90 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_1E_TYPE link_authenticaton_key_port1_1e; /* OFFSET: 0x94 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2A_TYPE link_authenticaton_key_port1_2a; /* OFFSET: 0x98 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2B_TYPE link_authenticaton_key_port1_2b; /* OFFSET: 0x9c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2C_TYPE link_authenticaton_key_port1_2c; /* OFFSET: 0xa0 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2D_TYPE link_authenticaton_key_port1_2d; /* OFFSET: 0xa4 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_2E_TYPE link_authenticaton_key_port1_2e; /* OFFSET: 0xa8 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3A_TYPE link_authenticaton_key_port1_3a; /* OFFSET: 0xac */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3B_TYPE link_authenticaton_key_port1_3b; /* OFFSET: 0xb0 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3C_TYPE link_authenticaton_key_port1_3c; /* OFFSET: 0xb4 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3D_TYPE link_authenticaton_key_port1_3d; /* OFFSET: 0xb8 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT1_3E_TYPE link_authenticaton_key_port1_3e; /* OFFSET: 0xbc */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0A_TYPE link_authenticaton_key_port2_0a; /* OFFSET: 0xc0 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0B_TYPE link_authenticaton_key_port2_0b; /* OFFSET: 0xc4 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0C_TYPE link_authenticaton_key_port2_0c; /* OFFSET: 0xc8 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0D_TYPE link_authenticaton_key_port2_0d; /* OFFSET: 0xcc */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_0E_TYPE link_authenticaton_key_port2_0e; /* OFFSET: 0xd0 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1A_TYPE link_authenticaton_key_port2_1a; /* OFFSET: 0xd4 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1B_TYPE link_authenticaton_key_port2_1b; /* OFFSET: 0xd8 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1C_TYPE link_authenticaton_key_port2_1c; /* OFFSET: 0xdc */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1D_TYPE link_authenticaton_key_port2_1d; /* OFFSET: 0xe0 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_1E_TYPE link_authenticaton_key_port2_1e; /* OFFSET: 0xe4 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2A_TYPE link_authenticaton_key_port2_2a; /* OFFSET: 0xe8 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2B_TYPE link_authenticaton_key_port2_2b; /* OFFSET: 0xec */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2C_TYPE link_authenticaton_key_port2_2c; /* OFFSET: 0xf0 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2D_TYPE link_authenticaton_key_port2_2d; /* OFFSET: 0xf4 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_2E_TYPE link_authenticaton_key_port2_2e; /* OFFSET: 0xf8 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3A_TYPE link_authenticaton_key_port2_3a; /* OFFSET: 0xfc */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3B_TYPE link_authenticaton_key_port2_3b; /* OFFSET: 0x100 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3C_TYPE link_authenticaton_key_port2_3c; /* OFFSET: 0x104 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3D_TYPE link_authenticaton_key_port2_3d; /* OFFSET: 0x108 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT2_3E_TYPE link_authenticaton_key_port2_3e; /* OFFSET: 0x10c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0A_TYPE link_authenticaton_key_port3_0a; /* OFFSET: 0x110 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0B_TYPE link_authenticaton_key_port3_0b; /* OFFSET: 0x114 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0C_TYPE link_authenticaton_key_port3_0c; /* OFFSET: 0x118 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0D_TYPE link_authenticaton_key_port3_0d; /* OFFSET: 0x11c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_0E_TYPE link_authenticaton_key_port3_0e; /* OFFSET: 0x120 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1A_TYPE link_authenticaton_key_port3_1a; /* OFFSET: 0x124 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1B_TYPE link_authenticaton_key_port3_1b; /* OFFSET: 0x128 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1C_TYPE link_authenticaton_key_port3_1c; /* OFFSET: 0x12c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1D_TYPE link_authenticaton_key_port3_1d; /* OFFSET: 0x130 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_1E_TYPE link_authenticaton_key_port3_1e; /* OFFSET: 0x134 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2A_TYPE link_authenticaton_key_port3_2a; /* OFFSET: 0x138 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2B_TYPE link_authenticaton_key_port3_2b; /* OFFSET: 0x13c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2C_TYPE link_authenticaton_key_port3_2c; /* OFFSET: 0x140 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2D_TYPE link_authenticaton_key_port3_2d; /* OFFSET: 0x144 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_2E_TYPE link_authenticaton_key_port3_2e; /* OFFSET: 0x148 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3A_TYPE link_authenticaton_key_port3_3a; /* OFFSET: 0x14c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3B_TYPE link_authenticaton_key_port3_3b; /* OFFSET: 0x150 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3C_TYPE link_authenticaton_key_port3_3c; /* OFFSET: 0x154 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3D_TYPE link_authenticaton_key_port3_3d; /* OFFSET: 0x158 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT3_3E_TYPE link_authenticaton_key_port3_3e; /* OFFSET: 0x15c */
    HSM_MISC_RESERVED_TYPE rsvd0[160]; /* OFFSET: 0x160 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0A_TYPE link_authenticaton_key_port4_0a; /* OFFSET: 0x200 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0B_TYPE link_authenticaton_key_port4_0b; /* OFFSET: 0x204 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0C_TYPE link_authenticaton_key_port4_0c; /* OFFSET: 0x208 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0D_TYPE link_authenticaton_key_port4_0d; /* OFFSET: 0x20c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_0E_TYPE link_authenticaton_key_port4_0e; /* OFFSET: 0x210 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1A_TYPE link_authenticaton_key_port4_1a; /* OFFSET: 0x214 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1B_TYPE link_authenticaton_key_port4_1b; /* OFFSET: 0x218 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1C_TYPE link_authenticaton_key_port4_1c; /* OFFSET: 0x21c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1D_TYPE link_authenticaton_key_port4_1d; /* OFFSET: 0x220 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_1E_TYPE link_authenticaton_key_port4_1e; /* OFFSET: 0x224 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2A_TYPE link_authenticaton_key_port4_2a; /* OFFSET: 0x228 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2B_TYPE link_authenticaton_key_port4_2b; /* OFFSET: 0x22c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2C_TYPE link_authenticaton_key_port4_2c; /* OFFSET: 0x230 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2D_TYPE link_authenticaton_key_port4_2d; /* OFFSET: 0x234 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_2E_TYPE link_authenticaton_key_port4_2e; /* OFFSET: 0x238 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3A_TYPE link_authenticaton_key_port4_3a; /* OFFSET: 0x23c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3B_TYPE link_authenticaton_key_port4_3b; /* OFFSET: 0x240 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3C_TYPE link_authenticaton_key_port4_3c; /* OFFSET: 0x244 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3D_TYPE link_authenticaton_key_port4_3d; /* OFFSET: 0x248 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT4_3E_TYPE link_authenticaton_key_port4_3e; /* OFFSET: 0x24c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0A_TYPE link_authenticaton_key_port5_0a; /* OFFSET: 0x250 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0B_TYPE link_authenticaton_key_port5_0b; /* OFFSET: 0x254 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0C_TYPE link_authenticaton_key_port5_0c; /* OFFSET: 0x258 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0D_TYPE link_authenticaton_key_port5_0d; /* OFFSET: 0x25c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_0E_TYPE link_authenticaton_key_port5_0e; /* OFFSET: 0x260 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1A_TYPE link_authenticaton_key_port5_1a; /* OFFSET: 0x264 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1B_TYPE link_authenticaton_key_port5_1b; /* OFFSET: 0x268 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1C_TYPE link_authenticaton_key_port5_1c; /* OFFSET: 0x26c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1D_TYPE link_authenticaton_key_port5_1d; /* OFFSET: 0x270 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_1E_TYPE link_authenticaton_key_port5_1e; /* OFFSET: 0x274 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2A_TYPE link_authenticaton_key_port5_2a; /* OFFSET: 0x278 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2B_TYPE link_authenticaton_key_port5_2b; /* OFFSET: 0x27c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2C_TYPE link_authenticaton_key_port5_2c; /* OFFSET: 0x280 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2D_TYPE link_authenticaton_key_port5_2d; /* OFFSET: 0x284 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_2E_TYPE link_authenticaton_key_port5_2e; /* OFFSET: 0x288 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3A_TYPE link_authenticaton_key_port5_3a; /* OFFSET: 0x28c */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3B_TYPE link_authenticaton_key_port5_3b; /* OFFSET: 0x290 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3C_TYPE link_authenticaton_key_port5_3c; /* OFFSET: 0x294 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3D_TYPE link_authenticaton_key_port5_3d; /* OFFSET: 0x298 */
    HSM_MISC_LINK_AUTHENTICATON_KEY_PORT5_3E_TYPE link_authenticaton_key_port5_3e; /* OFFSET: 0x29c */
    HSM_MISC_INTERRUPT_TYPE interrupt; /* OFFSET: 0x2a0 */
    HSM_MISC_INTERRUPT_EN_TYPE interrupt_en; /* OFFSET: 0x2a4 */
    HSM_MISC_INTERRUPT_CLEAR_TYPE interrupt_clear; /* OFFSET: 0x2a8 */
    HSM_MISC_ASTMI_TYPE ahb_slave_timout_mon_interrupt; /* OFFSET: 0x2ac */
    HSM_MISC_ASTMIE_TYPE ahb_slave_timout_mon_interrupt_en; /* OFFSET: 0x2b0 */
    HSM_MISC_ASTMIC_TYPE ahb_slave_timout_mon_interrupt_clr; /* OFFSET: 0x2b4 */
    HSM_MISC_DASTM_TYPE disable_ahb_slave_timout_mon; /* OFFSET: 0x2b8 */
    HSM_MISC_ECC_INTERRUPT_TYPE ecc_interrupt; /* OFFSET: 0x2bc */
    HSM_MISC_EIER_TYPE ecc_interrupt_en_reg; /* OFFSET: 0x2c0 */
    HSM_MISC_EICR_TYPE ecc_interrupt_clr_reg; /* OFFSET: 0x2c4 */
    HSM_MISC_INIT_MEM_TYPE init_mem; /* OFFSET: 0x2c8 */
    HSM_MISC_SPARE_REG0_TYPE spare_reg0; /* OFFSET: 0x2cc */
    HSM_MISC_SPARE_REG1_TYPE spare_reg1; /* OFFSET: 0x2d0 */
    HSM_MISC_SPARE_REG2_TYPE spare_reg2; /* OFFSET: 0x2d4 */
    HSM_MISC_SPARE_REG3_TYPE spare_reg3; /* OFFSET: 0x2d8 */
} HSM_MISC_RDBType;


#define HSM_MISC_BASE                   (0x4C014000UL)



#define HSM_MISC_MAX_HW_ID              (1UL)

#endif /* HSM_MISC_RDB_H */
