/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file io_rdb.h
    @brief RDB File for IO

    @version Orion_A0_20201104_SWDEV
*/

#ifndef IO_RDB_H
#define IO_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t IO_MII1_CONFIG_TYPE;
#define IO_MII1_CONFIG_CLOCK_EN_MII1_MASK (0x8000U)
#define IO_MII1_CONFIG_CLOCK_EN_MII1_SHIFT (15U)
#define IO_MII1_CONFIG_TX_PADS_IND_MII1_MASK (0x4000U)
#define IO_MII1_CONFIG_TX_PADS_IND_MII1_SHIFT (14U)
#define IO_MII1_CONFIG_TXCLK_PAD_IND_MII1_MASK (0x2000U)
#define IO_MII1_CONFIG_TXCLK_PAD_IND_MII1_SHIFT (13U)
#define IO_MII1_CONFIG_SRC_MII1_MASK (0x60U)
#define IO_MII1_CONFIG_SRC_MII1_SHIFT (5U)
#define IO_MII1_CONFIG_AMP_ENABLE_MII1_MASK (0x10U)
#define IO_MII1_CONFIG_AMP_ENABLE_MII1_SHIFT (4U)
#define IO_MII1_CONFIG_SEL_MII1_MASK (0xeU)
#define IO_MII1_CONFIG_SEL_MII1_SHIFT (1U)
#define IO_MII1_CONFIG_SEL_GMII_MII1_MASK (0x1U)
#define IO_MII1_CONFIG_SEL_GMII_MII1_SHIFT (0U)




typedef uint16_t IO_MII2_CONFIG_TYPE;
#define IO_MII2_CONFIG_CLOCK_EN_MII2_MASK (0x8000U)
#define IO_MII2_CONFIG_CLOCK_EN_MII2_SHIFT (15U)
#define IO_MII2_CONFIG_TX_PADS_IND_MII2_MASK (0x4000U)
#define IO_MII2_CONFIG_TX_PADS_IND_MII2_SHIFT (14U)
#define IO_MII2_CONFIG_TXCLK_PAD_IND_MII2_MASK (0x2000U)
#define IO_MII2_CONFIG_TXCLK_PAD_IND_MII2_SHIFT (13U)
#define IO_MII2_CONFIG_SRC_MII2_MASK (0x60U)
#define IO_MII2_CONFIG_SRC_MII2_SHIFT (5U)
#define IO_MII2_CONFIG_AMP_ENABLE_MII2_MASK (0x10U)
#define IO_MII2_CONFIG_AMP_ENABLE_MII2_SHIFT (4U)
#define IO_MII2_CONFIG_SEL_MII2_MASK (0xeU)
#define IO_MII2_CONFIG_SEL_MII2_SHIFT (1U)
#define IO_MII2_CONFIG_SEL_GMII_MII2_MASK (0x1U)
#define IO_MII2_CONFIG_SEL_GMII_MII2_SHIFT (0U)




typedef uint16_t IO_HYSTERESIS_TYPE;
#define IO_HYSTERESIS_HYS_MASK (0x1ffU)
#define IO_HYSTERESIS_HYS_SHIFT (0U)




typedef uint16_t IO_SOURCE_TYPE;
#define IO_SOURCE_SRC_MASK (0x1ffU)
#define IO_SOURCE_SRC_SHIFT (0U)




typedef uint16_t IO_SEL_TYPE;
#define IO_SEL_FLASH_MASK (0x7000U)
#define IO_SEL_FLASH_SHIFT (12U)
#define IO_SEL_MISC_MASK (0xe00U)
#define IO_SEL_MISC_SHIFT (9U)
#define IO_SEL_I2C_MASK (0x1c0U)
#define IO_SEL_I2C_SHIFT (6U)
#define IO_SEL_GPIO_MASK (0x38U)
#define IO_SEL_GPIO_SHIFT (3U)
#define IO_SEL_SPI_SLV_MASK (0x7U)
#define IO_SEL_SPI_SLV_SHIFT (0U)




typedef uint16_t IO_MII1_MODEHV_TYPE;
#define IO_MII1_MODEHV_MODEHV_MASK (0x1U)
#define IO_MII1_MODEHV_MODEHV_SHIFT (0U)




typedef uint16_t IO_MII2_MODEHV_TYPE;
#define IO_MII2_MODEHV_MII1_MODEHV_MASK (0x1U)
#define IO_MII2_MODEHV_MII1_MODEHV_SHIFT (0U)




typedef uint16_t IO_SEL2_TYPE;
#define IO_SEL2_SEL_SPI_SLV_MASK (0x7U)
#define IO_SEL2_SEL_SPI_SLV_SHIFT (0U)




typedef uint8_t IO_RESERVED_TYPE;




typedef uint16_t IO_RGMII1_CTL_TYPE;
#define IO_RGMII1_CTL_DIS_IMP_MASK (0x8000U)
#define IO_RGMII1_CTL_DIS_IMP_SHIFT (15U)
#define IO_RGMII1_CTL_RGMII_RX_CHARACTERIZATION_MASK (0x20U)
#define IO_RGMII1_CTL_RGMII_RX_CHARACTERIZATION_SHIFT (5U)
#define IO_RGMII1_CTL_RMII_CLOCK_SHORTCUT_MASK (0x10U)
#define IO_RGMII1_CTL_RMII_CLOCK_SHORTCUT_SHIFT (4U)
#define IO_RGMII1_CTL_RMII_CLOCK_DIRECTION_MASK (0x8U)
#define IO_RGMII1_CTL_RMII_CLOCK_DIRECTION_SHIFT (3U)
#define IO_RGMII1_CTL_RGMII1_CTL_MASK (0x6U)
#define IO_RGMII1_CTL_RGMII1_CTL_SHIFT (1U)
#define IO_RGMII1_CTL_RGMII1_BYPASS_IMP_2NS_DEL_MASK (0x1U)
#define IO_RGMII1_CTL_RGMII1_BYPASS_IMP_2NS_DEL_SHIFT (0U)




typedef uint16_t IO_RGMII2_CTL_TYPE;
#define IO_RGMII2_CTL_DIS_IMP_MASK (0x8000U)
#define IO_RGMII2_CTL_DIS_IMP_SHIFT (15U)
#define IO_RGMII2_CTL_RGMII_RX_CHARACTERIZATION_MASK (0x20U)
#define IO_RGMII2_CTL_RGMII_RX_CHARACTERIZATION_SHIFT (5U)
#define IO_RGMII2_CTL_RMII_CLOCK_SHORTCUT_MASK (0x10U)
#define IO_RGMII2_CTL_RMII_CLOCK_SHORTCUT_SHIFT (4U)
#define IO_RGMII2_CTL_RMII_CLOCK_DIRECTION_MASK (0x8U)
#define IO_RGMII2_CTL_RMII_CLOCK_DIRECTION_SHIFT (3U)
#define IO_RGMII2_CTL_RGMII2_CTL_MASK (0x6U)
#define IO_RGMII2_CTL_RGMII2_CTL_SHIFT (1U)
#define IO_RGMII2_CTL_RGMII2_BYPASS_IMP_2NS_DEL_MASK (0x1U)
#define IO_RGMII2_CTL_RGMII2_BYPASS_IMP_2NS_DEL_SHIFT (0U)




typedef uint16_t IO_SGMII_RGMII_CTL_TYPE;
#define IO_SGMII_RGMII_CTL_SEL_P5_MASK (0x300U)
#define IO_SGMII_RGMII_CTL_SEL_P5_SHIFT (8U)
#define IO_SGMII_RGMII_CTL_SEL_P6P8_MAIN_MASK (0x70U)
#define IO_SGMII_RGMII_CTL_SEL_P6P8_MAIN_SHIFT (4U)
#define IO_SGMII_RGMII_CTL_SEL_P6P8_PCIE_MASK (0x8U)
#define IO_SGMII_RGMII_CTL_SEL_P6P8_PCIE_SHIFT (3U)
#define IO_SGMII_RGMII_CTL_SEL_P6P8_5GBR_MASK (0x4U)
#define IO_SGMII_RGMII_CTL_SEL_P6P8_5GBR_SHIFT (2U)
#define IO_SGMII_RGMII_CTL_SEL_P3_MASK (0x2U)
#define IO_SGMII_RGMII_CTL_SEL_P3_SHIFT (1U)
#define IO_SGMII_RGMII_CTL_SEL_P1_MASK (0x1U)
#define IO_SGMII_RGMII_CTL_SEL_P1_SHIFT (0U)




typedef uint16_t IO_RGMII1_GMII_CTL_TYPE;
#define IO_RGMII1_GMII_CTL_RGMII_RX_PAUSE_MASK (0x10U)
#define IO_RGMII1_GMII_CTL_RGMII_RX_PAUSE_SHIFT (4U)
#define IO_RGMII1_GMII_CTL_RGMII_TX_PAUSE_MASK (0x8U)
#define IO_RGMII1_GMII_CTL_RGMII_TX_PAUSE_SHIFT (3U)
#define IO_RGMII1_GMII_CTL_RGMII_LINK_MASK (0x4U)
#define IO_RGMII1_GMII_CTL_RGMII_LINK_SHIFT (2U)
#define IO_RGMII1_GMII_CTL_RGMII_SPD_MASK (0x3U)
#define IO_RGMII1_GMII_CTL_RGMII_SPD_SHIFT (0U)




typedef uint16_t IO_RGMII2_GMII_CTL_TYPE;
#define IO_RGMII2_GMII_CTL_RGMII_RX_PAUSE_MASK (0x10U)
#define IO_RGMII2_GMII_CTL_RGMII_RX_PAUSE_SHIFT (4U)
#define IO_RGMII2_GMII_CTL_RGMII_TX_PAUSE_MASK (0x8U)
#define IO_RGMII2_GMII_CTL_RGMII_TX_PAUSE_SHIFT (3U)
#define IO_RGMII2_GMII_CTL_RGMII_LINK_MASK (0x4U)
#define IO_RGMII2_GMII_CTL_RGMII_LINK_SHIFT (2U)
#define IO_RGMII2_GMII_CTL_RGMII_SPD_MASK (0x3U)
#define IO_RGMII2_GMII_CTL_RGMII_SPD_SHIFT (0U)




typedef uint16_t IO_CPU_GMII_CTL_TYPE;
#define IO_CPU_GMII_CTL_GMII3_LPBK_SEL_MASK (0x800U)
#define IO_CPU_GMII_CTL_GMII3_LPBK_SEL_SHIFT (11U)
#define IO_CPU_GMII_CTL_GMII2_LPBK_SEL_MASK (0x400U)
#define IO_CPU_GMII_CTL_GMII2_LPBK_SEL_SHIFT (10U)
#define IO_CPU_GMII_CTL_GMII1_LPBK_SEL_MASK (0x200U)
#define IO_CPU_GMII_CTL_GMII1_LPBK_SEL_SHIFT (9U)
#define IO_CPU_GMII_CTL_CPU_LPBK_SEL_MASK (0x100U)
#define IO_CPU_GMII_CTL_CPU_LPBK_SEL_SHIFT (8U)
#define IO_CPU_GMII_CTL_CPU_RX_PAUSE_MASK (0x10U)
#define IO_CPU_GMII_CTL_CPU_RX_PAUSE_SHIFT (4U)
#define IO_CPU_GMII_CTL_CPU_TX_PAUSE_MASK (0x8U)
#define IO_CPU_GMII_CTL_CPU_TX_PAUSE_SHIFT (3U)
#define IO_CPU_GMII_CTL_CPU_LINK_MASK (0x4U)
#define IO_CPU_GMII_CTL_CPU_LINK_SHIFT (2U)
#define IO_CPU_GMII_CTL_CPU_SPD_MASK (0x3U)
#define IO_CPU_GMII_CTL_CPU_SPD_SHIFT (0U)




typedef uint16_t IO_RGMII_RX_CHAR_PATTERN_EXP_TYPE;
#define IO_RGMII_RX_CHAR_PATTERN_EXP_EXP_MASK (0x3ffU)
#define IO_RGMII_RX_CHAR_PATTERN_EXP_EXP_SHIFT (0U)




typedef uint16_t IO_RGMII_RX_CHAR_PATTERN_GOT_TYPE;
#define IO_RGMII_RX_CHAR_PATTERN_GOT_GOT_MASK (0x3ffU)
#define IO_RGMII_RX_CHAR_PATTERN_GOT_GOT_SHIFT (0U)




typedef uint16_t IO_STRAPS_RAW_TYPE;
#define IO_STRAPS_RAW_SFT_DEBUG_MODE_B_MASK (0x8000U)
#define IO_STRAPS_RAW_SFT_DEBUG_MODE_B_SHIFT (15U)
#define IO_STRAPS_RAW_TC10_GO2STNDBY_MASK (0x4000U)
#define IO_STRAPS_RAW_TC10_GO2STNDBY_SHIFT (14U)
#define IO_STRAPS_RAW_TC10_DISABLE_MASK (0x2000U)
#define IO_STRAPS_RAW_TC10_DISABLE_SHIFT (13U)
#define IO_STRAPS_RAW_PHYADDR4_MASK (0x1000U)
#define IO_STRAPS_RAW_PHYADDR4_SHIFT (12U)
#define IO_STRAPS_RAW_PHYADDR3_MASK (0x800U)
#define IO_STRAPS_RAW_PHYADDR3_SHIFT (11U)
#define IO_STRAPS_RAW_MII2_MODE_2_MASK (0x400U)
#define IO_STRAPS_RAW_MII2_MODE_2_SHIFT (10U)
#define IO_STRAPS_RAW_MII1_MODE_2_MASK (0x200U)
#define IO_STRAPS_RAW_MII1_MODE_2_SHIFT (9U)
#define IO_STRAPS_RAW_HW_FWDG_EN_MASK (0x100U)
#define IO_STRAPS_RAW_HW_FWDG_EN_SHIFT (8U)
#define IO_STRAPS_RAW_MII2_MODE_1_MASK (0x80U)
#define IO_STRAPS_RAW_MII2_MODE_1_SHIFT (7U)
#define IO_STRAPS_RAW_MII2_MODE_0_MASK (0x40U)
#define IO_STRAPS_RAW_MII2_MODE_0_SHIFT (6U)
#define IO_STRAPS_RAW_MII1_MODE_1_MASK (0x20U)
#define IO_STRAPS_RAW_MII1_MODE_1_SHIFT (5U)
#define IO_STRAPS_RAW_MII1_MODE_0_MASK (0x10U)
#define IO_STRAPS_RAW_MII1_MODE_0_SHIFT (4U)
#define IO_STRAPS_RAW_SUPER_ISOLATE_STRAP_MASK (0x8U)
#define IO_STRAPS_RAW_SUPER_ISOLATE_STRAP_SHIFT (3U)
#define IO_STRAPS_RAW_SFT_FORCE_DWNLD_STRAP_MASK (0x4U)
#define IO_STRAPS_RAW_SFT_FORCE_DWNLD_STRAP_SHIFT (2U)
#define IO_STRAPS_RAW_BRPHY_MS_STRAP_MASK (0x2U)
#define IO_STRAPS_RAW_BRPHY_MS_STRAP_SHIFT (1U)
#define IO_STRAPS_RAW_STRAP_EN_EXTCLKB_MASK (0x1U)
#define IO_STRAPS_RAW_STRAP_EN_EXTCLKB_SHIFT (0U)




typedef uint16_t IO_STRAPS_OV_TYPE;
#define IO_STRAPS_OV_SFT_DEBUG_MODE_B_MASK (0x8000U)
#define IO_STRAPS_OV_SFT_DEBUG_MODE_B_SHIFT (15U)
#define IO_STRAPS_OV_TC10_GO2STNDBY_MASK (0x4000U)
#define IO_STRAPS_OV_TC10_GO2STNDBY_SHIFT (14U)
#define IO_STRAPS_OV_TC10_DISABLE_MASK (0x2000U)
#define IO_STRAPS_OV_TC10_DISABLE_SHIFT (13U)
#define IO_STRAPS_OV_PHYADDR4_MASK (0x1000U)
#define IO_STRAPS_OV_PHYADDR4_SHIFT (12U)
#define IO_STRAPS_OV_PHYADDR3_MASK (0x800U)
#define IO_STRAPS_OV_PHYADDR3_SHIFT (11U)
#define IO_STRAPS_OV_MII2_MODE_2_MASK (0x400U)
#define IO_STRAPS_OV_MII2_MODE_2_SHIFT (10U)
#define IO_STRAPS_OV_MII1_MODE_2_MASK (0x200U)
#define IO_STRAPS_OV_MII1_MODE_2_SHIFT (9U)
#define IO_STRAPS_OV_HW_FWDG_EN_MASK (0x100U)
#define IO_STRAPS_OV_HW_FWDG_EN_SHIFT (8U)
#define IO_STRAPS_OV_MII2_MODE_1_MASK (0x80U)
#define IO_STRAPS_OV_MII2_MODE_1_SHIFT (7U)
#define IO_STRAPS_OV_MII2_MODE_0_MASK (0x40U)
#define IO_STRAPS_OV_MII2_MODE_0_SHIFT (6U)
#define IO_STRAPS_OV_MII1_MODE_1_MASK (0x20U)
#define IO_STRAPS_OV_MII1_MODE_1_SHIFT (5U)
#define IO_STRAPS_OV_MII1_MODE_0_MASK (0x10U)
#define IO_STRAPS_OV_MII1_MODE_0_SHIFT (4U)
#define IO_STRAPS_OV_SUPER_ISOLATE_STRAP_MASK (0x8U)
#define IO_STRAPS_OV_SUPER_ISOLATE_STRAP_SHIFT (3U)
#define IO_STRAPS_OV_SFT_FORCE_DWNLD_STRAP_MASK (0x4U)
#define IO_STRAPS_OV_SFT_FORCE_DWNLD_STRAP_SHIFT (2U)
#define IO_STRAPS_OV_BRPHY_MS_STRAP_MASK (0x2U)
#define IO_STRAPS_OV_BRPHY_MS_STRAP_SHIFT (1U)
#define IO_STRAPS_OV_STRAP_EN_EXTCLKB_MASK (0x1U)
#define IO_STRAPS_OV_STRAP_EN_EXTCLKB_SHIFT (0U)




typedef uint16_t IO_STRAPS_RAW2_TYPE;
#define IO_STRAPS_RAW2_BRPHY_1G_ANEN_MASK (0x20U)
#define IO_STRAPS_RAW2_BRPHY_1G_ANEN_SHIFT (5U)
#define IO_STRAPS_RAW2_BRPHY_1G_SPEED_MASK (0x10U)
#define IO_STRAPS_RAW2_BRPHY_1G_SPEED_SHIFT (4U)
#define IO_STRAPS_RAW2_BRPHY_1G_MS_MASK (0x8U)
#define IO_STRAPS_RAW2_BRPHY_1G_MS_SHIFT (3U)
#define IO_STRAPS_RAW2_MII3_MODE_2_MASK (0x4U)
#define IO_STRAPS_RAW2_MII3_MODE_2_SHIFT (2U)
#define IO_STRAPS_RAW2_MII3_MODE_1_MASK (0x2U)
#define IO_STRAPS_RAW2_MII3_MODE_1_SHIFT (1U)
#define IO_STRAPS_RAW2_MII3_MODE_0_MASK (0x1U)
#define IO_STRAPS_RAW2_MII3_MODE_0_SHIFT (0U)




typedef uint16_t IO_STRAPS_OV2_TYPE;
#define IO_STRAPS_OV2_BRPHY_1G_ANEN_MASK (0x20U)
#define IO_STRAPS_OV2_BRPHY_1G_ANEN_SHIFT (5U)
#define IO_STRAPS_OV2_BRPHY_1G_SPEED_MASK (0x10U)
#define IO_STRAPS_OV2_BRPHY_1G_SPEED_SHIFT (4U)
#define IO_STRAPS_OV2_BRPHY_1G_MS_MASK (0x8U)
#define IO_STRAPS_OV2_BRPHY_1G_MS_SHIFT (3U)
#define IO_STRAPS_OV2_MII3_MODE_2_MASK (0x4U)
#define IO_STRAPS_OV2_MII3_MODE_2_SHIFT (2U)
#define IO_STRAPS_OV2_MII3_MODE_1_MASK (0x2U)
#define IO_STRAPS_OV2_MII3_MODE_1_SHIFT (1U)
#define IO_STRAPS_OV2_MII3_MODE_0_MASK (0x1U)
#define IO_STRAPS_OV2_MII3_MODE_0_SHIFT (0U)




typedef uint16_t IO_STRAP_TEST_TYPE;
#define IO_STRAP_TEST_INPUT_MODE_TEST_MASK (0x100U)
#define IO_STRAP_TEST_INPUT_MODE_TEST_SHIFT (8U)
#define IO_STRAP_TEST_VAL_LATCHED_MASK (0x70U)
#define IO_STRAP_TEST_VAL_LATCHED_SHIFT (4U)
#define IO_STRAP_TEST_VAL_MASK (0x7U)
#define IO_STRAP_TEST_VAL_SHIFT (0U)




typedef uint16_t IO_SW_RXC_INV_CTL_TYPE;
#define IO_SW_RXC_INV_CTL_CTL_MASK (0xffffU)
#define IO_SW_RXC_INV_CTL_CTL_SHIFT (0U)




typedef uint16_t IO_SW_TX_PIPELINE_CTL_TYPE;
#define IO_SW_TX_PIPELINE_CTL_EN_MASK (0x1ffU)
#define IO_SW_TX_PIPELINE_CTL_EN_SHIFT (0U)




typedef uint16_t IO_SW_RX_PIPELINE_CTL_TYPE;
#define IO_SW_RX_PIPELINE_CTL_EN_MASK (0x1ffU)
#define IO_SW_RX_PIPELINE_CTL_EN_SHIFT (0U)




typedef uint16_t IO_SW_OVRD_TYPE;
#define IO_SW_OVRD_RX_PAUSE_SEL_MASK (0x800U)
#define IO_SW_OVRD_RX_PAUSE_SEL_SHIFT (11U)
#define IO_SW_OVRD_TX_PAUSE_SEL_MASK (0x400U)
#define IO_SW_OVRD_TX_PAUSE_SEL_SHIFT (10U)
#define IO_SW_OVRD_LINK_SEL_MASK (0x200U)
#define IO_SW_OVRD_LINK_SEL_SHIFT (9U)
#define IO_SW_OVRD_SPD_SEL_MASK (0x100U)
#define IO_SW_OVRD_SPD_SEL_SHIFT (8U)
#define IO_SW_OVRD_RX_PAUSE_VAL_MASK (0x10U)
#define IO_SW_OVRD_RX_PAUSE_VAL_SHIFT (4U)
#define IO_SW_OVRD_TX_PAUSE_VAL_MASK (0x8U)
#define IO_SW_OVRD_TX_PAUSE_VAL_SHIFT (3U)
#define IO_SW_OVRD_LINK_VAL_MASK (0x4U)
#define IO_SW_OVRD_LINK_VAL_SHIFT (2U)
#define IO_SW_OVRD_SPD_VAL_MASK (0x3U)
#define IO_SW_OVRD_SPD_VAL_SHIFT (0U)




typedef uint16_t IO_TEST_BUS_SELECT_TYPE;
#define IO_TEST_BUS_SELECT_OVSTB_MASK (0x8000U)
#define IO_TEST_BUS_SELECT_OVSTB_SHIFT (15U)
#define IO_TEST_BUS_SELECT_BURNIN_CLK_ON_LEDCLK_EN_MASK (0x4000U)
#define IO_TEST_BUS_SELECT_BURNIN_CLK_ON_LEDCLK_EN_SHIFT (14U)
#define IO_TEST_BUS_SELECT_UNUSED_MASK (0x30U)
#define IO_TEST_BUS_SELECT_UNUSED_SHIFT (4U)
#define IO_TEST_BUS_SELECT_SELECT_TEST_BUS_MASK (0xfU)
#define IO_TEST_BUS_SELECT_SELECT_TEST_BUS_SHIFT (0U)




typedef uint16_t IO_P1588_CONFIG_TYPE;
#define IO_P1588_CONFIG_SYNC_OUT_OEB_MASK (0x4U)
#define IO_P1588_CONFIG_SYNC_OUT_OEB_SHIFT (2U)
#define IO_P1588_CONFIG_SYNC_OUT_SEL_MASK (0x3U)
#define IO_P1588_CONFIG_SYNC_OUT_SEL_SHIFT (0U)




typedef uint16_t IO_P1588_SYNC_GEN_TYPE;
#define IO_P1588_SYNC_GEN_IO_IN1_MASK (0x8U)
#define IO_P1588_SYNC_GEN_IO_IN1_SHIFT (3U)
#define IO_P1588_SYNC_GEN_IO_IN0_MASK (0x4U)
#define IO_P1588_SYNC_GEN_IO_IN0_SHIFT (2U)
#define IO_P1588_SYNC_GEN_BRPHY_IN1_MASK (0x2U)
#define IO_P1588_SYNC_GEN_BRPHY_IN1_SHIFT (1U)
#define IO_P1588_SYNC_GEN_BRPHY_IN0_MASK (0x1U)
#define IO_P1588_SYNC_GEN_BRPHY_IN0_SHIFT (0U)




typedef uint16_t IO_CTL_TYPE;
#define IO_CTL_CTL_MASK (0xffffU)
#define IO_CTL_CTL_SHIFT (0U)




typedef uint16_t IO_RGMII_FIFO_CTL_TYPE;
#define IO_RGMII_FIFO_CTL_CTL_MASK (0xffffU)
#define IO_RGMII_FIFO_CTL_CTL_SHIFT (0U)




typedef uint16_t IO_RGMII_DLL_CTL_TYPE;
#define IO_RGMII_DLL_CTL_CTRL_MASK (0xffffU)
#define IO_RGMII_DLL_CTL_CTRL_SHIFT (0U)




typedef uint16_t IO_RGMII_DLL_CFG_TYPE;
#define IO_RGMII_DLL_CFG_CFG_MASK (0xffffU)
#define IO_RGMII_DLL_CFG_CFG_SHIFT (0U)




typedef uint16_t IO_MII3_CONFIG_TYPE;
#define IO_MII3_CONFIG_CLOCK_EN_MII3_MASK (0x8000U)
#define IO_MII3_CONFIG_CLOCK_EN_MII3_SHIFT (15U)
#define IO_MII3_CONFIG_TX_PADS_IND_MII3_MASK (0x4000U)
#define IO_MII3_CONFIG_TX_PADS_IND_MII3_SHIFT (14U)
#define IO_MII3_CONFIG_TXCLK_PAD_IND_MII3_MASK (0x2000U)
#define IO_MII3_CONFIG_TXCLK_PAD_IND_MII3_SHIFT (13U)
#define IO_MII3_CONFIG_SRC_MII3_MASK (0x60U)
#define IO_MII3_CONFIG_SRC_MII3_SHIFT (5U)
#define IO_MII3_CONFIG_AMP_ENABLE_MII3_MASK (0x10U)
#define IO_MII3_CONFIG_AMP_ENABLE_MII3_SHIFT (4U)
#define IO_MII3_CONFIG_SEL_MII3_MASK (0xeU)
#define IO_MII3_CONFIG_SEL_MII3_SHIFT (1U)
#define IO_MII3_CONFIG_SEL_GMII_MII3_MASK (0x1U)
#define IO_MII3_CONFIG_SEL_GMII_MII3_SHIFT (0U)




typedef uint16_t IO_MII3_MODEHV_TYPE;
#define IO_MII3_MODEHV_MODEHV_MASK (0x1U)
#define IO_MII3_MODEHV_MODEHV_SHIFT (0U)




typedef uint16_t IO_RGMII3_CTL_TYPE;
#define IO_RGMII3_CTL_DIS_IMP_MASK (0x8000U)
#define IO_RGMII3_CTL_DIS_IMP_SHIFT (15U)
#define IO_RGMII3_CTL_RGMII_RX_CHARACTERIZATION_MASK (0x20U)
#define IO_RGMII3_CTL_RGMII_RX_CHARACTERIZATION_SHIFT (5U)
#define IO_RGMII3_CTL_RMII_CLOCK_SHORTCUT_MASK (0x10U)
#define IO_RGMII3_CTL_RMII_CLOCK_SHORTCUT_SHIFT (4U)
#define IO_RGMII3_CTL_RMII_CLOCK_DIRECTION_MASK (0x8U)
#define IO_RGMII3_CTL_RMII_CLOCK_DIRECTION_SHIFT (3U)
#define IO_RGMII3_CTL_RGMII3_CTL_MASK (0x6U)
#define IO_RGMII3_CTL_RGMII3_CTL_SHIFT (1U)
#define IO_RGMII3_CTL_RGMII3_BYPASS_IMP_2NS_DEL_MASK (0x1U)
#define IO_RGMII3_CTL_RGMII3_BYPASS_IMP_2NS_DEL_SHIFT (0U)




typedef uint16_t IO_RGMII3_GMII_CTL_TYPE;
#define IO_RGMII3_GMII_CTL_RGMII_RX_PAUSE_MASK (0x10U)
#define IO_RGMII3_GMII_CTL_RGMII_RX_PAUSE_SHIFT (4U)
#define IO_RGMII3_GMII_CTL_RGMII_TX_PAUSE_MASK (0x8U)
#define IO_RGMII3_GMII_CTL_RGMII_TX_PAUSE_SHIFT (3U)
#define IO_RGMII3_GMII_CTL_RGMII_LINK_MASK (0x4U)
#define IO_RGMII3_GMII_CTL_RGMII_LINK_SHIFT (2U)
#define IO_RGMII3_GMII_CTL_RGMII_SPD_MASK (0x3U)
#define IO_RGMII3_GMII_CTL_RGMII_SPD_SHIFT (0U)




typedef uint16_t IO_XGMII_RXFIFO_CTL_TYPE;
#define IO_XGMII_RXFIFO_CTL_XGMII_RXFIFO_ENABLE_MASK (0x8000U)
#define IO_XGMII_RXFIFO_CTL_XGMII_RXFIFO_ENABLE_SHIFT (15U)
#define IO_XGMII_RXFIFO_CTL_RXFIFO_RF_RAM_TM_NOT_USED_MASK (0x78U)
#define IO_XGMII_RXFIFO_CTL_RXFIFO_RF_RAM_TM_NOT_USED_SHIFT (3U)
#define IO_XGMII_RXFIFO_CTL_XGMII_RX_CLK_COMP_DIS_MASK (0x4U)
#define IO_XGMII_RXFIFO_CTL_XGMII_RX_CLK_COMP_DIS_SHIFT (2U)
#define IO_XGMII_RXFIFO_CTL_XGMII_RXFIFO_B2B_DEL_EN_MASK (0x2U)
#define IO_XGMII_RXFIFO_CTL_XGMII_RXFIFO_B2B_DEL_EN_SHIFT (1U)
#define IO_XGMII_RXFIFO_CTL_XGMII_RX_CLK_COMP_CNT_SAT_TEST_MASK (0x1U)
#define IO_XGMII_RXFIFO_CTL_XGMII_RX_CLK_COMP_CNT_SAT_TEST_SHIFT (0U)




typedef uint16_t IO_XGMII_RXFIFO_TRSHD_CTL_TYPE;
#define IO_XGMII_RXFIFO_TRSHD_CTL_ALMOST_FULL_TRSHD_MASK (0xf000U)
#define IO_XGMII_RXFIFO_TRSHD_CTL_ALMOST_FULL_TRSHD_SHIFT (12U)
#define IO_XGMII_RXFIFO_TRSHD_CTL_ALMOST_EMPTY_TRSHD_MASK (0xc00U)
#define IO_XGMII_RXFIFO_TRSHD_CTL_ALMOST_EMPTY_TRSHD_SHIFT (10U)
#define IO_XGMII_RXFIFO_TRSHD_CTL_DEL_TRSHD_MASK (0x3c0U)
#define IO_XGMII_RXFIFO_TRSHD_CTL_DEL_TRSHD_SHIFT (6U)
#define IO_XGMII_RXFIFO_TRSHD_CTL_INST_TRSHD_MASK (0x38U)
#define IO_XGMII_RXFIFO_TRSHD_CTL_INST_TRSHD_SHIFT (3U)
#define IO_XGMII_RXFIFO_TRSHD_CTL_STRD_TRSHD_MASK (0x7U)
#define IO_XGMII_RXFIFO_TRSHD_CTL_STRD_TRSHD_SHIFT (0U)




typedef uint16_t IO_XGMII_RXFIFO_DELETE_CNT_TYPE;
#define IO_XGMII_RXFIFO_DELETE_CNT_LAT_MASK (0x8000U)
#define IO_XGMII_RXFIFO_DELETE_CNT_LAT_SHIFT (15U)
#define IO_XGMII_RXFIFO_DELETE_CNT_CNT_MASK (0x7fffU)
#define IO_XGMII_RXFIFO_DELETE_CNT_CNT_SHIFT (0U)




typedef uint16_t IO_XGMII_RXFIFO_INSERT_CNT_TYPE;
#define IO_XGMII_RXFIFO_INSERT_CNT_LAT_MASK (0x8000U)
#define IO_XGMII_RXFIFO_INSERT_CNT_LAT_SHIFT (15U)
#define IO_XGMII_RXFIFO_INSERT_CNT_CNT_MASK (0x7fffU)
#define IO_XGMII_RXFIFO_INSERT_CNT_CNT_SHIFT (0U)




typedef uint16_t IO_XGMII_RXFIFO_LH_STS_TYPE;
#define IO_XGMII_RXFIFO_LH_STS_STS_LATCH_MASK (0x1000U)
#define IO_XGMII_RXFIFO_LH_STS_STS_LATCH_SHIFT (12U)
#define IO_XGMII_RXFIFO_LH_STS_INSERT_EVNT_LH_MASK (0x800U)
#define IO_XGMII_RXFIFO_LH_STS_INSERT_EVNT_LH_SHIFT (11U)
#define IO_XGMII_RXFIFO_LH_STS_DELETE_EVNT_LH_MASK (0x400U)
#define IO_XGMII_RXFIFO_LH_STS_DELETE_EVNT_LH_SHIFT (10U)
#define IO_XGMII_RXFIFO_LH_STS_FULL_LH_MASK (0x200U)
#define IO_XGMII_RXFIFO_LH_STS_FULL_LH_SHIFT (9U)
#define IO_XGMII_RXFIFO_LH_STS_EMPTY_LH_MASK (0x100U)
#define IO_XGMII_RXFIFO_LH_STS_EMPTY_LH_SHIFT (8U)
#define IO_XGMII_RXFIFO_LH_STS_ALMOST_FULL_LH_MASK (0x80U)
#define IO_XGMII_RXFIFO_LH_STS_ALMOST_FULL_LH_SHIFT (7U)
#define IO_XGMII_RXFIFO_LH_STS_ALMOST_EMPTY_LH_MASK (0x40U)
#define IO_XGMII_RXFIFO_LH_STS_ALMOST_EMPTY_LH_SHIFT (6U)
#define IO_XGMII_RXFIFO_LH_STS_RD_ERR_MASK (0x20U)
#define IO_XGMII_RXFIFO_LH_STS_RD_ERR_SHIFT (5U)
#define IO_XGMII_RXFIFO_LH_STS_RD_RF_MASK (0x10U)
#define IO_XGMII_RXFIFO_LH_STS_RD_RF_SHIFT (4U)
#define IO_XGMII_RXFIFO_LH_STS_RD_LF_MASK (0x8U)
#define IO_XGMII_RXFIFO_LH_STS_RD_LF_SHIFT (3U)
#define IO_XGMII_RXFIFO_LH_STS_WR_ERR_MASK (0x4U)
#define IO_XGMII_RXFIFO_LH_STS_WR_ERR_SHIFT (2U)
#define IO_XGMII_RXFIFO_LH_STS_WR_RF_MASK (0x2U)
#define IO_XGMII_RXFIFO_LH_STS_WR_RF_SHIFT (1U)
#define IO_XGMII_RXFIFO_LH_STS_WR_LF_MASK (0x1U)
#define IO_XGMII_RXFIFO_LH_STS_WR_LF_SHIFT (0U)




typedef uint16_t IO_XGMII_TXFIFO_CTL_TYPE;
#define IO_XGMII_TXFIFO_CTL_XGMII_TXFIFO_ENABLE_MASK (0x8000U)
#define IO_XGMII_TXFIFO_CTL_XGMII_TXFIFO_ENABLE_SHIFT (15U)
#define IO_XGMII_TXFIFO_CTL_TXFIFO_RF_RAM_TM_NOT_USED_MASK (0x78U)
#define IO_XGMII_TXFIFO_CTL_TXFIFO_RF_RAM_TM_NOT_USED_SHIFT (3U)
#define IO_XGMII_TXFIFO_CTL_XGMII_TX_CLK_COMP_DIS_MASK (0x4U)
#define IO_XGMII_TXFIFO_CTL_XGMII_TX_CLK_COMP_DIS_SHIFT (2U)
#define IO_XGMII_TXFIFO_CTL_XGMII_TXFIFO_B2B_DEL_EN_MASK (0x2U)
#define IO_XGMII_TXFIFO_CTL_XGMII_TXFIFO_B2B_DEL_EN_SHIFT (1U)
#define IO_XGMII_TXFIFO_CTL_XGMII_TX_CLK_COMP_CNT_SAT_TEST_MASK (0x1U)
#define IO_XGMII_TXFIFO_CTL_XGMII_TX_CLK_COMP_CNT_SAT_TEST_SHIFT (0U)




typedef uint16_t IO_XGMII_TXFIFO_TRSHD_CTL_TYPE;
#define IO_XGMII_TXFIFO_TRSHD_CTL_ALMOST_FULL_TRSHD_MASK (0xf000U)
#define IO_XGMII_TXFIFO_TRSHD_CTL_ALMOST_FULL_TRSHD_SHIFT (12U)
#define IO_XGMII_TXFIFO_TRSHD_CTL_ALMOST_EMPTY_TRSHD_MASK (0xc00U)
#define IO_XGMII_TXFIFO_TRSHD_CTL_ALMOST_EMPTY_TRSHD_SHIFT (10U)
#define IO_XGMII_TXFIFO_TRSHD_CTL_DEL_TRSHD_MASK (0x3c0U)
#define IO_XGMII_TXFIFO_TRSHD_CTL_DEL_TRSHD_SHIFT (6U)
#define IO_XGMII_TXFIFO_TRSHD_CTL_INST_TRSHD_MASK (0x38U)
#define IO_XGMII_TXFIFO_TRSHD_CTL_INST_TRSHD_SHIFT (3U)
#define IO_XGMII_TXFIFO_TRSHD_CTL_STRD_TRSHD_MASK (0x7U)
#define IO_XGMII_TXFIFO_TRSHD_CTL_STRD_TRSHD_SHIFT (0U)




typedef uint16_t IO_XGMII_TXFIFO_DELETE_CNT_TYPE;
#define IO_XGMII_TXFIFO_DELETE_CNT_LAT_MASK (0x8000U)
#define IO_XGMII_TXFIFO_DELETE_CNT_LAT_SHIFT (15U)
#define IO_XGMII_TXFIFO_DELETE_CNT_CNT_MASK (0x7fffU)
#define IO_XGMII_TXFIFO_DELETE_CNT_CNT_SHIFT (0U)




typedef uint16_t IO_XGMII_TXFIFO_INSERT_CNT_TYPE;
#define IO_XGMII_TXFIFO_INSERT_CNT_LAT_MASK (0x8000U)
#define IO_XGMII_TXFIFO_INSERT_CNT_LAT_SHIFT (15U)
#define IO_XGMII_TXFIFO_INSERT_CNT_CNT_MASK (0x7fffU)
#define IO_XGMII_TXFIFO_INSERT_CNT_CNT_SHIFT (0U)




typedef uint16_t IO_XGMII_TXFIFO_LH_STS_TYPE;
#define IO_XGMII_TXFIFO_LH_STS_STS_LATCH_MASK (0x1000U)
#define IO_XGMII_TXFIFO_LH_STS_STS_LATCH_SHIFT (12U)
#define IO_XGMII_TXFIFO_LH_STS_INSERT_EVNT_LH_MASK (0x800U)
#define IO_XGMII_TXFIFO_LH_STS_INSERT_EVNT_LH_SHIFT (11U)
#define IO_XGMII_TXFIFO_LH_STS_DELETE_EVNT_LH_MASK (0x400U)
#define IO_XGMII_TXFIFO_LH_STS_DELETE_EVNT_LH_SHIFT (10U)
#define IO_XGMII_TXFIFO_LH_STS_FULL_LH_MASK (0x200U)
#define IO_XGMII_TXFIFO_LH_STS_FULL_LH_SHIFT (9U)
#define IO_XGMII_TXFIFO_LH_STS_EMPTY_LH_MASK (0x100U)
#define IO_XGMII_TXFIFO_LH_STS_EMPTY_LH_SHIFT (8U)
#define IO_XGMII_TXFIFO_LH_STS_ALMOST_FULL_LH_MASK (0x80U)
#define IO_XGMII_TXFIFO_LH_STS_ALMOST_FULL_LH_SHIFT (7U)
#define IO_XGMII_TXFIFO_LH_STS_ALMOST_EMPTY_LH_MASK (0x40U)
#define IO_XGMII_TXFIFO_LH_STS_ALMOST_EMPTY_LH_SHIFT (6U)
#define IO_XGMII_TXFIFO_LH_STS_RD_ERR_MASK (0x20U)
#define IO_XGMII_TXFIFO_LH_STS_RD_ERR_SHIFT (5U)
#define IO_XGMII_TXFIFO_LH_STS_RD_RF_MASK (0x10U)
#define IO_XGMII_TXFIFO_LH_STS_RD_RF_SHIFT (4U)
#define IO_XGMII_TXFIFO_LH_STS_RD_LF_MASK (0x8U)
#define IO_XGMII_TXFIFO_LH_STS_RD_LF_SHIFT (3U)
#define IO_XGMII_TXFIFO_LH_STS_WR_ERR_MASK (0x4U)
#define IO_XGMII_TXFIFO_LH_STS_WR_ERR_SHIFT (2U)
#define IO_XGMII_TXFIFO_LH_STS_WR_RF_MASK (0x2U)
#define IO_XGMII_TXFIFO_LH_STS_WR_RF_SHIFT (1U)
#define IO_XGMII_TXFIFO_LH_STS_WR_LF_MASK (0x1U)
#define IO_XGMII_TXFIFO_LH_STS_WR_LF_SHIFT (0U)




typedef uint16_t IO_XGMIIGMII_CNVT_CTL_TYPE;
#define IO_XGMIIGMII_CNVT_CTL_SFT_RESET_N_MASK (0x4U)
#define IO_XGMIIGMII_CNVT_CTL_SFT_RESET_N_SHIFT (2U)
#define IO_XGMIIGMII_CNVT_CTL_CONV_EN_MASK (0x2U)
#define IO_XGMIIGMII_CNVT_CTL_CONV_EN_SHIFT (1U)
#define IO_XGMIIGMII_CNVT_CTL_LPI_FEATURE_EN_MASK (0x1U)
#define IO_XGMIIGMII_CNVT_CTL_LPI_FEATURE_EN_SHIFT (0U)




typedef uint16_t IO_BOOTROM_STRAP_TYPE;
#define IO_BOOTROM_STRAP_BYPASS_MASK (0x1U)
#define IO_BOOTROM_STRAP_BYPASS_SHIFT (0U)




typedef uint16_t IO_SPIM_SCK_IN_CTL_TYPE;
#define IO_SPIM_SCK_IN_CTL_SPARE_MASK (0xffe0U)
#define IO_SPIM_SCK_IN_CTL_SPARE_SHIFT (5U)
#define IO_SPIM_SCK_IN_CTL_SCK_IN_SEL_MASK (0x10U)
#define IO_SPIM_SCK_IN_CTL_SCK_IN_SEL_SHIFT (4U)
#define IO_SPIM_SCK_IN_CTL_SCK_BYPASS_MASK (0x8U)
#define IO_SPIM_SCK_IN_CTL_SCK_BYPASS_SHIFT (3U)
#define IO_SPIM_SCK_IN_CTL_SCK_IN_DLY_SEL_MASK (0x7U)
#define IO_SPIM_SCK_IN_CTL_SCK_IN_DLY_SEL_SHIFT (0U)




typedef uint16_t IO_FF_TYPE;
#define IO_FF_IOFF_MASK (0xffffU)
#define IO_FF_IOFF_SHIFT (0U)



#define IO_SW_OVRD_SIZE  (9UL)


typedef volatile struct COMP_PACKED sIO_RDBType {
    IO_MII1_CONFIG_TYPE mii1_config; /* OFFSET: 0x0 */
    IO_MII2_CONFIG_TYPE mii2_config; /* OFFSET: 0x2 */
    IO_HYSTERESIS_TYPE io_hysteresis; /* OFFSET: 0x4 */
    IO_SOURCE_TYPE io_source; /* OFFSET: 0x6 */
    IO_SEL_TYPE io_sel; /* OFFSET: 0x8 */
    IO_MII1_MODEHV_TYPE io_mii1_modehv; /* OFFSET: 0xa */
    IO_MII2_MODEHV_TYPE io_mii2_modehv; /* OFFSET: 0xc */
    IO_SEL2_TYPE io_sel2; /* OFFSET: 0xe */
    IO_RESERVED_TYPE rsvd0[16]; /* OFFSET: 0x10 */
    IO_RGMII1_CTL_TYPE rgmii1_ctl; /* OFFSET: 0x20 */
    IO_RGMII2_CTL_TYPE rgmii2_ctl; /* OFFSET: 0x22 */
    IO_SGMII_RGMII_CTL_TYPE sgmii_rgmii_ctl; /* OFFSET: 0x24 */
    IO_RGMII1_GMII_CTL_TYPE rgmii1_gmii_ctl; /* OFFSET: 0x26 */
    IO_RGMII2_GMII_CTL_TYPE rgmii2_gmii_ctl; /* OFFSET: 0x28 */
    IO_CPU_GMII_CTL_TYPE cpu_gmii_ctl; /* OFFSET: 0x2a */
    IO_RGMII_RX_CHAR_PATTERN_EXP_TYPE rgmii1_rx_char_pattern_exp; /* OFFSET: 0x2c */
    IO_RGMII_RX_CHAR_PATTERN_GOT_TYPE rgmii1_rx_char_pattern_got; /* OFFSET: 0x2e */
    IO_RGMII_RX_CHAR_PATTERN_EXP_TYPE rgmii2_rx_char_pattern_exp; /* OFFSET: 0x30 */
    IO_RGMII_RX_CHAR_PATTERN_GOT_TYPE rgmii2_rx_char_pattern_got; /* OFFSET: 0x32 */
    IO_RGMII_RX_CHAR_PATTERN_EXP_TYPE rgmii3_rx_char_pattern_exp; /* OFFSET: 0x34 */
    IO_RGMII_RX_CHAR_PATTERN_GOT_TYPE rgmii3_rx_char_pattern_got; /* OFFSET: 0x36 */
    IO_RESERVED_TYPE rsvd1[8]; /* OFFSET: 0x38 */
    IO_STRAPS_RAW_TYPE straps_raw; /* OFFSET: 0x40 */
    IO_STRAPS_OV_TYPE straps_ov; /* OFFSET: 0x42 */
    IO_STRAPS_RAW2_TYPE straps_raw2; /* OFFSET: 0x44 */
    IO_STRAPS_OV2_TYPE straps_ov2; /* OFFSET: 0x46 */
    IO_STRAP_TEST_TYPE strap_test; /* OFFSET: 0x48 */
    IO_SW_RXC_INV_CTL_TYPE sw_rxc_inv_ctl; /* OFFSET: 0x4a */
    IO_SW_TX_PIPELINE_CTL_TYPE sw_tx_pipeline_ctl; /* OFFSET: 0x4c */
    IO_SW_RX_PIPELINE_CTL_TYPE sw_rx_pipeline_ctl; /* OFFSET: 0x4e */
    IO_SW_OVRD_TYPE sw_ovrd[IO_SW_OVRD_SIZE]; /* OFFSET: 0x50 */
    IO_RESERVED_TYPE rsvd2[14]; /* OFFSET: 0x62 */
    IO_TEST_BUS_SELECT_TYPE test_bus_select; /* OFFSET: 0x70 */
    IO_P1588_CONFIG_TYPE p1588_config; /* OFFSET: 0x72 */
    IO_P1588_SYNC_GEN_TYPE p1588_sync_gen; /* OFFSET: 0x74 */
    IO_CTL_TYPE io_ctl; /* OFFSET: 0x76 */
    IO_RGMII_FIFO_CTL_TYPE rgmii1_fifo_ctl; /* OFFSET: 0x78 */
    IO_RGMII_FIFO_CTL_TYPE rgmii2_fifo_ctl; /* OFFSET: 0x7a */
    IO_RGMII_DLL_CTL_TYPE rgmii1_dll_ctrl; /* OFFSET: 0x7c */
    IO_RGMII_DLL_CFG_TYPE rgmii1_dll_cfg; /* OFFSET: 0x7e */
    IO_RGMII_DLL_CTL_TYPE rgmii2_dll_ctrl; /* OFFSET: 0x80 */
    IO_RGMII_DLL_CFG_TYPE rgmii2_dll_cfg; /* OFFSET: 0x82 */
    IO_MII3_CONFIG_TYPE mii3_config; /* OFFSET: 0x84 */
    IO_MII3_MODEHV_TYPE io_mii3_modehv; /* OFFSET: 0x86 */
    IO_RGMII3_CTL_TYPE rgmii3_ctl; /* OFFSET: 0x88 */
    IO_RGMII3_GMII_CTL_TYPE rgmii3_gmii_ctl; /* OFFSET: 0x8a */
    IO_RGMII_FIFO_CTL_TYPE rgmii3_fifo_ctl; /* OFFSET: 0x8c */
    IO_RGMII_DLL_CTL_TYPE rgmii3_dll_ctrl; /* OFFSET: 0x8e */
    IO_RGMII_DLL_CFG_TYPE rgmii3_dll_cfg; /* OFFSET: 0x90 */
    IO_XGMII_RXFIFO_CTL_TYPE xgmii_rxfifo_ctl; /* OFFSET: 0x92 */
    IO_XGMII_RXFIFO_TRSHD_CTL_TYPE xgmii_rxfifo_trshd_ctl; /* OFFSET: 0x94 */
    IO_XGMII_RXFIFO_DELETE_CNT_TYPE xgmii_rxfifo_delete_cnt; /* OFFSET: 0x96 */
    IO_XGMII_RXFIFO_INSERT_CNT_TYPE xgmii_rxfifo_insert_cnt; /* OFFSET: 0x98 */
    IO_XGMII_RXFIFO_LH_STS_TYPE xgmii_rxfifo_lh_sts; /* OFFSET: 0x9a */
    IO_XGMII_TXFIFO_CTL_TYPE xgmii_txfifo_ctl; /* OFFSET: 0x9c */
    IO_XGMII_TXFIFO_TRSHD_CTL_TYPE xgmii_txfifo_trshd_ctl; /* OFFSET: 0x9e */
    IO_XGMII_TXFIFO_DELETE_CNT_TYPE xgmii_txfifo_delete_cnt; /* OFFSET: 0xa0 */
    IO_XGMII_TXFIFO_INSERT_CNT_TYPE xgmii_txfifo_insert_cnt; /* OFFSET: 0xa2 */
    IO_XGMII_TXFIFO_LH_STS_TYPE xgmii_txfifo_lh_sts; /* OFFSET: 0xa4 */
    IO_XGMIIGMII_CNVT_CTL_TYPE xgmiigmii_cnvt_ctl; /* OFFSET: 0xa6 */
    IO_RESERVED_TYPE rsvd3[8]; /* OFFSET: 0xa8 */
    IO_BOOTROM_STRAP_TYPE bootrom_strap; /* OFFSET: 0xb0 */
    IO_RESERVED_TYPE rsvd4[3902]; /* OFFSET: 0xb2 */
    IO_SPIM_SCK_IN_CTL_TYPE spim_sck_in_ctl; /* OFFSET: 0xff0 */
    IO_RESERVED_TYPE rsvd5[12]; /* OFFSET: 0xff2 */
    IO_FF_TYPE ioff; /* OFFSET: 0xffe */
} IO_RDBType;


#define IO_BASE                         (0x4A840000UL)



#define IO_MAX_HW_ID                    (1UL)


#define IO_NUM_RGMII_PORTS              (3U )


#define IO_CTL_MDIO_DISABLE_MASK        (IO_CTL_MDIOM1_DISABLE_MASK)


#define IO_CPU_RX_PAUSE_MASK            (IO_CPU_GMII_CTL_CPU_RX_PAUSE_MASK)


#define IO_CPU_TX_PAUSE_MASK            (IO_CPU_GMII_CTL_CPU_TX_PAUSE_MASK)


#define IO_CPU_LINK_MASK                (IO_CPU_GMII_CTL_CPU_LINK_MASK)


#define IO_CPU_SPD_MASK                 (IO_CPU_GMII_CTL_CPU_SPD_MASK)


#define IO_CPU_SPD_1G                   (0x1UL)


#define IO_CPU_SPD_2G                   (0x2UL)


#define IO_STRAPS_RAW_SFT_FORCE_DWNLD_MASK  (IO_STRAPS_RAW_SFT_FORCE_DWNLD_STRAP_MASK)


#define IO_STRAPS_RAW_SFT_FORCE_DWNLD_SHIFT  (IO_STRAPS_RAW_SFT_FORCE_DWNLD_STRAP_SHIFT)


#define IO_CTL_SPIM_DISABLE_MASK        (0x1U)


#define IO_CTL_MDIOM1_DISABLE_MASK      (0x2U)


#define IO_SGMII_RGMII_CTL_SEL_P5_RGMII_MASK  (0x200U)


#define IO_SGMII_RGMII_CTL_SEL_P5_SGMII_MASK  (0x100U)


#define IO_SGMII_RGMII_CTL_SEL_P6P8_MAIN_BIT0_MASK  (0x10U)


#define IO_SGMII_RGMII_CTL_SEL_P6P8_MAIN_BIT1_MASK  (0x20U)


#define IO_SGMII_RGMII_CTL_SEL_P6P8_MAIN_BIT2_MASK  (0x40U)


#define IO_RGMII_ENABLE_2NS_RX_DELAY_MASK  (0x4U)


#define IO_RGMII_ENABLE_2NS_TX_DELAY_MASK  (0x2U)


#define IO_P1588_CONFIG_SYNCOUT_SEL_VAL  (0x2U)

#endif /* IO_RDB_H */
