/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_i_tcam_cntr_dbg_rdb.h
    @brief RDB File for MACSEC_I_TCAM_CNTR_DBG

    @version Orion_A0_20201104_SWDEV
*/

#ifndef MACSEC_I_TCAM_CNTR_DBG_RDB_H
#define MACSEC_I_TCAM_CNTR_DBG_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_I_TCAM_CNTR_DBG_RESERVED_TYPE;




typedef uint32_t MACSEC_I_TCAM_CNTR_DBG_TCD1_TYPE;
#define MACSEC_I_TCAM_CNTR_DBG_TCD1_INCREMENT_MASK_MASK (0x1UL)
#define MACSEC_I_TCAM_CNTR_DBG_TCD1_INCREMENT_MASK_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTR_DBG_TCD3_TYPE;
#define MACSEC_I_TCAM_CNTR_DBG_TCD3_GLOBAL_INCREMENT_MASK_MASK (0x7UL)
#define MACSEC_I_TCAM_CNTR_DBG_TCD3_GLOBAL_INCREMENT_MASK_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTR_DBG_TCD4_TYPE;
#define MACSEC_I_TCAM_CNTR_DBG_TCD4_TCAM_TEST_MASK (0x1UL)
#define MACSEC_I_TCAM_CNTR_DBG_TCD4_TCAM_TEST_SHIFT (0UL)
#define MACSEC_I_TCAM_CNTR_DBG_TCD4_GLOBAL_TEST_MASK (0x4UL)
#define MACSEC_I_TCAM_CNTR_DBG_TCD4_GLOBAL_TEST_SHIFT (2UL)
#define MACSEC_I_TCAM_CNTR_DBG_TCD4_TCAM_NR_MASK (0xf8UL)
#define MACSEC_I_TCAM_CNTR_DBG_TCD4_TCAM_NR_SHIFT (3UL)
#define MACSEC_I_TCAM_CNTR_DBG_TCD4_GLOBAL_OCTET_INCREMENT_MASK (0x7fff0000UL)
#define MACSEC_I_TCAM_CNTR_DBG_TCD4_GLOBAL_OCTET_INCREMENT_SHIFT (16UL)




typedef volatile struct COMP_PACKED sMACSEC_I_TCAM_CNTR_DBG_RDBType {
    MACSEC_I_TCAM_CNTR_DBG_RESERVED_TYPE rsvd0[17408]; /* OFFSET: 0x0 */
    MACSEC_I_TCAM_CNTR_DBG_TCD1_TYPE debug1; /* OFFSET: 0x4400 */
    MACSEC_I_TCAM_CNTR_DBG_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x4404 */
    MACSEC_I_TCAM_CNTR_DBG_TCD3_TYPE debug3; /* OFFSET: 0x4408 */
    MACSEC_I_TCAM_CNTR_DBG_TCD4_TYPE debug4; /* OFFSET: 0x440c */
} MACSEC_I_TCAM_CNTR_DBG_RDBType;


#define EIP165_IGEIP160_STATTCAM_TCAM_CNTR_DEBUG_REGS0_BASE  (0x4D010000UL)

#define EIP165_IGEIP160_STATTCAM_TCAM_CNTR_DEBUG_REGS1_BASE  (0x4D110000UL)

#define EIP165_IGEIP160_STATTCAM_TCAM_CNTR_DEBUG_REGS2_BASE  (0x4D210000UL)

#define EIP165_IGEIP160_STATTCAM_TCAM_CNTR_DEBUG_REGS3_BASE  (0x4D310000UL)

#define EIP165_IGEIP160_STATTCAM_TCAM_CNTR_DEBUG_REGS4_BASE  (0x4D410000UL)

#define EIP165_IGEIP160_STATTCAM_TCAM_CNTR_DEBUG_REGS5_BASE  (0x4D510000UL)



#define MACSEC_I_TCAM_CNTR_DBG_MAX_HW_ID  (6UL)

#endif /* MACSEC_I_TCAM_CNTR_DBG_RDB_H */
