/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_e_oppe_rdb.h
    @brief RDB File for MACSEC_E_OPPE

    @version Orion_A0_20201104_SWDEV
*/

#ifndef MACSEC_E_OPPE_RDB_H
#define MACSEC_E_OPPE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_E_OPPE_RESERVED_TYPE;




typedef uint32_t MACSEC_E_OPPE_SA_PN_THR_SUMMARY1_TYPE;
#define MACSEC_E_OPPE_SA_PN_THR_SUMMARY1_31_0_MASK (0xffffffffUL)
#define MACSEC_E_OPPE_SA_PN_THR_SUMMARY1_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_E_OPPE_PP_STAT_CTRL_TYPE;
#define MACSEC_E_OPPE_PP_STAT_CTRL_IF_TAGS_IN_CLEAR_MASK (0x1UL)
#define MACSEC_E_OPPE_PP_STAT_CTRL_IF_TAGS_IN_CLEAR_SHIFT (0UL)




typedef uint32_t MACSEC_E_OPPE_COUNT_SECFAIL1_TYPE;
#define MACSEC_E_OPPE_COUNT_SECFAIL1_SA_SECFAIL_MASK_MASK (0xfUL)
#define MACSEC_E_OPPE_COUNT_SECFAIL1_SA_SECFAIL_MASK_SHIFT (0UL)
#define MACSEC_E_OPPE_COUNT_SECFAIL1_ERROR_MASK_MASK (0xfffe0000UL)
#define MACSEC_E_OPPE_COUNT_SECFAIL1_ERROR_MASK_SHIFT (17UL)




typedef uint32_t MACSEC_E_OPPE_COUNT_SECFAIL2_TYPE;
#define MACSEC_E_OPPE_COUNT_SECFAIL2_SECY_SECFAIL_MASK_MASK (0x7UL)
#define MACSEC_E_OPPE_COUNT_SECFAIL2_SECY_SECFAIL_MASK_SHIFT (0UL)




typedef uint32_t MACSEC_E_OPPE_COUNT_SECFAIL3_TYPE;
#define MACSEC_E_OPPE_COUNT_SECFAIL3_GLOBAL_SECFAIL_MASK_MASK (0x7UL)
#define MACSEC_E_OPPE_COUNT_SECFAIL3_GLOBAL_SECFAIL_MASK_SHIFT (0UL)




typedef uint32_t MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_0_TYPE;
#define MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_0_RESULT_TOKEN_WORDS_MASK (0xffffffffUL)
#define MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_0_RESULT_TOKEN_WORDS_SHIFT (0UL)




typedef uint32_t MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_1_TYPE;
#define MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_1_RESULT_TOKEN_WORDS_MASK (0xffffffffUL)
#define MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_1_RESULT_TOKEN_WORDS_SHIFT (0UL)




typedef uint32_t MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_2_TYPE;
#define MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_2_RESULT_TOKEN_WORDS_MASK (0xffffffffUL)
#define MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_2_RESULT_TOKEN_WORDS_SHIFT (0UL)




typedef uint32_t MACSEC_E_OPPE_CRYPTO_DEBUG_CNTR_TYPE;
#define MACSEC_E_OPPE_CRYPTO_DEBUG_CNTR_PACKET_COUNT_MASK (0xffffffffUL)
#define MACSEC_E_OPPE_CRYPTO_DEBUG_CNTR_PACKET_COUNT_SHIFT (0UL)




typedef uint32_t MACSEC_E_OPPE_DBG_PP_DROP_ENABLE_TYPE;
#define MACSEC_E_OPPE_DBG_PP_DROP_ENABLE_IG_ENABLE_MASK (0x7UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_ENABLE_IG_ENABLE_SHIFT (0UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_ENABLE_EG_ENABLE_MASK (0x70000UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_ENABLE_EG_ENABLE_SHIFT (16UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_ENABLE_GL_ENABLE_MASK (0x3000000UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_ENABLE_GL_ENABLE_SHIFT (24UL)




typedef uint32_t MACSEC_E_OPPE_DBG_PP_DROP_STATUS_TYPE;
#define MACSEC_E_OPPE_DBG_PP_DROP_STATUS_IG_DROP_FLAGS_MASK (0x7UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_STATUS_IG_DROP_FLAGS_SHIFT (0UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_STATUS_EG_DROP_FLAGS_MASK (0x70000UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_STATUS_EG_DROP_FLAGS_SHIFT (16UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_STATUS_OID_DROP_OPERATION_MASK (0x1000000UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_STATUS_OID_DROP_OPERATION_SHIFT (24UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_STATUS_TRANSFORM_ERROR_MASK (0x2000000UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_STATUS_TRANSFORM_ERROR_SHIFT (25UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_STATUS_RES_OUT_MASK (0xe0000000UL)
#define MACSEC_E_OPPE_DBG_PP_DROP_STATUS_RES_OUT_SHIFT (29UL)




typedef uint32_t MACSEC_E_OPPE_MTU0_TYPE;
#define MACSEC_E_OPPE_MTU0_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU0_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU0_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU0_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU1_TYPE;
#define MACSEC_E_OPPE_MTU1_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU1_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU1_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU1_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU2_TYPE;
#define MACSEC_E_OPPE_MTU2_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU2_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU2_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU2_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU3_TYPE;
#define MACSEC_E_OPPE_MTU3_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU3_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU3_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU3_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU4_TYPE;
#define MACSEC_E_OPPE_MTU4_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU4_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU4_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU4_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU5_TYPE;
#define MACSEC_E_OPPE_MTU5_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU5_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU5_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU5_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU6_TYPE;
#define MACSEC_E_OPPE_MTU6_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU6_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU6_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU6_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU7_TYPE;
#define MACSEC_E_OPPE_MTU7_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU7_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU7_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU7_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU8_TYPE;
#define MACSEC_E_OPPE_MTU8_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU8_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU8_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU8_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU9_TYPE;
#define MACSEC_E_OPPE_MTU9_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU9_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU9_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU9_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU10_TYPE;
#define MACSEC_E_OPPE_MTU10_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU10_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU10_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU10_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU11_TYPE;
#define MACSEC_E_OPPE_MTU11_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU11_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU11_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU11_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU12_TYPE;
#define MACSEC_E_OPPE_MTU12_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU12_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU12_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU12_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU13_TYPE;
#define MACSEC_E_OPPE_MTU13_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU13_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU13_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU13_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU14_TYPE;
#define MACSEC_E_OPPE_MTU14_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU14_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU14_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU14_MTU_COMP_DROP_SHIFT (15UL)




typedef uint32_t MACSEC_E_OPPE_MTU15_TYPE;
#define MACSEC_E_OPPE_MTU15_MTU_COMPARE_MASK (0x7fffUL)
#define MACSEC_E_OPPE_MTU15_MTU_COMPARE_SHIFT (0UL)
#define MACSEC_E_OPPE_MTU15_MTU_COMP_DROP_MASK (0x8000UL)
#define MACSEC_E_OPPE_MTU15_MTU_COMP_DROP_SHIFT (15UL)




typedef volatile struct COMP_PACKED sMACSEC_E_OPPE_RDBType {
    MACSEC_E_OPPE_RESERVED_TYPE rsvd0[126976]; /* OFFSET: 0x0 */
    MACSEC_E_OPPE_SA_PN_THR_SUMMARY1_TYPE sa_pn_thr_summary1; /* OFFSET: 0x1f000 */
    MACSEC_E_OPPE_RESERVED_TYPE rsvd1[252]; /* OFFSET: 0x1f004 */
    MACSEC_E_OPPE_PP_STAT_CTRL_TYPE pp_stat_ctrl; /* OFFSET: 0x1f100 */
    MACSEC_E_OPPE_RESERVED_TYPE rsvd2[32]; /* OFFSET: 0x1f104 */
    MACSEC_E_OPPE_COUNT_SECFAIL1_TYPE count_secfail1; /* OFFSET: 0x1f124 */
    MACSEC_E_OPPE_COUNT_SECFAIL2_TYPE count_secfail2; /* OFFSET: 0x1f128 */
    MACSEC_E_OPPE_COUNT_SECFAIL3_TYPE count_secfail3; /* OFFSET: 0x1f12c */
    MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_0_TYPE crypto_rslt_debug_0; /* OFFSET: 0x1f130 */
    MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_1_TYPE crypto_rslt_debug_1; /* OFFSET: 0x1f134 */
    MACSEC_E_OPPE_CRYPTO_RSLT_DEBUG_2_TYPE crypto_rslt_debug_2; /* OFFSET: 0x1f138 */
    MACSEC_E_OPPE_CRYPTO_DEBUG_CNTR_TYPE crypto_debug_cntr; /* OFFSET: 0x1f13c */
    MACSEC_E_OPPE_DBG_PP_DROP_ENABLE_TYPE dbg_pp_drop_enable; /* OFFSET: 0x1f140 */
    MACSEC_E_OPPE_DBG_PP_DROP_STATUS_TYPE dbg_pp_drop_status; /* OFFSET: 0x1f144 */
    MACSEC_E_OPPE_RESERVED_TYPE rsvd3[184]; /* OFFSET: 0x1f148 */
    MACSEC_E_OPPE_MTU0_TYPE mtu0; /* OFFSET: 0x1f200 */
    MACSEC_E_OPPE_MTU1_TYPE mtu1; /* OFFSET: 0x1f204 */
    MACSEC_E_OPPE_MTU2_TYPE mtu2; /* OFFSET: 0x1f208 */
    MACSEC_E_OPPE_MTU3_TYPE mtu3; /* OFFSET: 0x1f20c */
    MACSEC_E_OPPE_MTU4_TYPE mtu4; /* OFFSET: 0x1f210 */
    MACSEC_E_OPPE_MTU5_TYPE mtu5; /* OFFSET: 0x1f214 */
    MACSEC_E_OPPE_MTU6_TYPE mtu6; /* OFFSET: 0x1f218 */
    MACSEC_E_OPPE_MTU7_TYPE mtu7; /* OFFSET: 0x1f21c */
    MACSEC_E_OPPE_MTU8_TYPE mtu8; /* OFFSET: 0x1f220 */
    MACSEC_E_OPPE_MTU9_TYPE mtu9; /* OFFSET: 0x1f224 */
    MACSEC_E_OPPE_MTU10_TYPE mtu10; /* OFFSET: 0x1f228 */
    MACSEC_E_OPPE_MTU11_TYPE mtu11; /* OFFSET: 0x1f22c */
    MACSEC_E_OPPE_MTU12_TYPE mtu12; /* OFFSET: 0x1f230 */
    MACSEC_E_OPPE_MTU13_TYPE mtu13; /* OFFSET: 0x1f234 */
    MACSEC_E_OPPE_MTU14_TYPE mtu14; /* OFFSET: 0x1f238 */
    MACSEC_E_OPPE_MTU15_TYPE mtu15; /* OFFSET: 0x1f23c */
} MACSEC_E_OPPE_RDBType;


#define EIP_160S_E_32_BRCM_OPPE0_BASE   (0x4D010000UL)

#define EIP_160S_E_32_BRCM_OPPE1_BASE   (0x4D110000UL)

#define EIP_160S_E_32_BRCM_OPPE2_BASE   (0x4D210000UL)

#define EIP_160S_E_32_BRCM_OPPE3_BASE   (0x4D310000UL)

#define EIP_160S_E_32_BRCM_OPPE4_BASE   (0x4D410000UL)

#define EIP_160S_E_32_BRCM_OPPE5_BASE   (0x4D510000UL)



#define MACSEC_E_OPPE_MAX_HW_ID         (6UL)

#endif /* MACSEC_E_OPPE_RDB_H */
