/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_mspu_mac_rdb.h
    @brief RDB File for MACSEC_MSPU_MAC

    @version Orion_A0_20201104_SWDEV
*/

#ifndef MACSEC_MSPU_MAC_RDB_H
#define MACSEC_MSPU_MAC_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_MSPU_MAC_RESERVED_TYPE;




typedef uint32_t MACSEC_MSPU_MAC_LUIHBC_TYPE;
#define MACSEC_MSPU_MAC_LUIHBC_IHBCIHBCR3_MASK (0xffffff80UL)
#define MACSEC_MSPU_MAC_LUIHBC_IHBCIHBCR3_SHIFT (7UL)
#define MACSEC_MSPU_MAC_LUIHBC_IPG_HD_BKP_CNTL_IPG_CONFIG_RX_MASK (0x7cUL)
#define MACSEC_MSPU_MAC_LUIHBC_IPG_HD_BKP_CNTL_IPG_CONFIG_RX_SHIFT (2UL)
#define MACSEC_MSPU_MAC_LUIHBC_IPG_HD_BKP_CNTL_HD_FC_BKOFF_OK_MASK (0x2UL)
#define MACSEC_MSPU_MAC_LUIHBC_IPG_HD_BKP_CNTL_HD_FC_BKOFF_OK_SHIFT (1UL)
#define MACSEC_MSPU_MAC_LUIHBC_IPG_HD_BKP_CNTL_HD_FC_ENA_MASK (0x1UL)
#define MACSEC_MSPU_MAC_LUIHBC_IPG_HD_BKP_CNTL_HD_FC_ENA_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUCC_TYPE;
#define MACSEC_MSPU_MAC_LUCC_CCCCR28_MASK (0x80000000UL)
#define MACSEC_MSPU_MAC_LUCC_CCCCR28_SHIFT (31UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_RUNT_FILTER_DIS_MASK (0x40000000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_RUNT_FILTER_DIS_SHIFT (30UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_OOB_EFC_EN_MASK (0x20000000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_OOB_EFC_EN_SHIFT (29UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_IGNORE_TX_PAUSE_MASK (0x10000000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_IGNORE_TX_PAUSE_SHIFT (28UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_FD_TX_URUN_FIX_EN_MASK (0x8000000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_FD_TX_URUN_FIX_EN_SHIFT (27UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_RX_ERR_DISC_MASK (0x4000000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_RX_ERR_DISC_SHIFT (26UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_LINE_LOOPBACK_MASK (0x2000000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_LINE_LOOPBACK_SHIFT (25UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_NO_LGTH_CHECK_MASK (0x1000000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_NO_LGTH_CHECK_SHIFT (24UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_CNTL_FRM_ENA_MASK (0x800000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_CNTL_FRM_ENA_SHIFT (23UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_ENA_EXT_CONFIG_MASK (0x400000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_ENA_EXT_CONFIG_SHIFT (22UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_EN_INTERNAL_TX_CRS_MASK (0x200000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_EN_INTERNAL_TX_CRS_SHIFT (21UL)
#define MACSEC_MSPU_MAC_LUCC_CCCCR18_MASK (0x180000UL)
#define MACSEC_MSPU_MAC_LUCC_CCCCR18_SHIFT (19UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_SW_OVERRIDE_RX_MASK (0x40000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_SW_OVERRIDE_RX_SHIFT (18UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_SW_OVERRIDE_TX_MASK (0x20000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_SW_OVERRIDE_TX_SHIFT (17UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_MAC_LOOP_CON_MASK (0x10000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_MAC_LOOP_CON_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_LOOP_ENA_MASK (0x8000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_LOOP_ENA_SHIFT (15UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_FCS_CORRUPT_URUN_EN_MASK (0x4000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_FCS_CORRUPT_URUN_EN_SHIFT (14UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_SW_RESET_MASK (0x2000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_SW_RESET_SHIFT (13UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_OVERFLOW_EN_MASK (0x1000UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_OVERFLOW_EN_SHIFT (12UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_RX_LOW_LATENCY_EN_MASK (0x800UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_RX_LOW_LATENCY_EN_SHIFT (11UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_HD_ENA_MASK (0x400UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_HD_ENA_SHIFT (10UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_TX_ADDR_INS_MASK (0x200UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_TX_ADDR_INS_SHIFT (9UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_PAUSE_IGNORE_MASK (0x100UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_PAUSE_IGNORE_SHIFT (8UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_PAUSE_FWD_MASK (0x80UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_PAUSE_FWD_SHIFT (7UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_CRC_FWD_MASK (0x40UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_CRC_FWD_SHIFT (6UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_PAD_EN_MASK (0x20UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_PAD_EN_SHIFT (5UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_PROMIS_EN_MASK (0x10UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_PROMIS_EN_SHIFT (4UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_ETH_SPEED_MASK (0xcUL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_ETH_SPEED_SHIFT (2UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_RX_ENA_MASK (0x2UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_RX_ENA_SHIFT (1UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_TX_ENA_MASK (0x1UL)
#define MACSEC_MSPU_MAC_LUCC_COMMAND_CONFIG_TX_ENA_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LINE_UNIMAC_MAC_0_TYPE;
#define MACSEC_MSPU_MAC_LINE_UNIMAC_MAC_0_ADDR0_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_LINE_UNIMAC_MAC_0_ADDR0_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LINE_UNIMAC_MAC_1_TYPE;
#define MACSEC_MSPU_MAC_LINE_UNIMAC_MAC_1_RSVD_1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_LINE_UNIMAC_MAC_1_RSVD_1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LINE_UNIMAC_MAC_1_ADDR1_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LINE_UNIMAC_MAC_1_ADDR1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUFL_TYPE;
#define MACSEC_MSPU_MAC_LUFL_FRM_LENGTH_FRM_LENGTH_RSVD_1_MASK (0xffffc000UL)
#define MACSEC_MSPU_MAC_LUFL_FRM_LENGTH_FRM_LENGTH_RSVD_1_SHIFT (14UL)
#define MACSEC_MSPU_MAC_LUFL_FRM_LENGTH_MAXFR_MASK (0x3fffUL)
#define MACSEC_MSPU_MAC_LUFL_FRM_LENGTH_MAXFR_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUPQ_TYPE;
#define MACSEC_MSPU_MAC_LUPQ_PAUSE_QUANT_PAUSE_QUANT_RSVD_1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_LUPQ_PAUSE_QUANT_PAUSE_QUANT_RSVD_1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUPQ_PAUSE_QUANT_STAD2_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUPQ_PAUSE_QUANT_STAD2_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUTTSI_TYPE;
#define MACSEC_MSPU_MAC_LUTTSI_TX_TS_SEQ_ID_TX_TS_SEQ_ID_RSVD_2_MASK (0xfffe0000UL)
#define MACSEC_MSPU_MAC_LUTTSI_TX_TS_SEQ_ID_TX_TS_SEQ_ID_RSVD_2_SHIFT (17UL)
#define MACSEC_MSPU_MAC_LUTTSI_TX_TS_SEQ_ID_TSTS_VALID_MASK (0x10000UL)
#define MACSEC_MSPU_MAC_LUTTSI_TX_TS_SEQ_ID_TSTS_VALID_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUTTSI_TX_TS_SEQ_ID_TSTS_SEQ_ID_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUTTSI_TX_TS_SEQ_ID_TSTS_SEQ_ID_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUSO_TYPE;
#define MACSEC_MSPU_MAC_LUSO_SFD_OFFSET_SFD_OFFSET_RSVD_1_MASK (0xfffffff0UL)
#define MACSEC_MSPU_MAC_LUSO_SFD_OFFSET_SFD_OFFSET_RSVD_1_SHIFT (4UL)
#define MACSEC_MSPU_MAC_LUSO_SFD_OFFSET_SFD_OFFSET_MASK (0xfUL)
#define MACSEC_MSPU_MAC_LUSO_SFD_OFFSET_SFD_OFFSET_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUMM_TYPE;
#define MACSEC_MSPU_MAC_LUMM_MODE_MODE_RSVD_5_MASK (0xffffffc0UL)
#define MACSEC_MSPU_MAC_LUMM_MODE_MODE_RSVD_5_SHIFT (6UL)
#define MACSEC_MSPU_MAC_LUMM_MODE_LINK_STATUS_MASK (0x20UL)
#define MACSEC_MSPU_MAC_LUMM_MODE_LINK_STATUS_SHIFT (5UL)
#define MACSEC_MSPU_MAC_LUMM_MODE_TX_PAUSE_MASK (0x10UL)
#define MACSEC_MSPU_MAC_LUMM_MODE_TX_PAUSE_SHIFT (4UL)
#define MACSEC_MSPU_MAC_LUMM_MODE_RX_PAUSE_MASK (0x8UL)
#define MACSEC_MSPU_MAC_LUMM_MODE_RX_PAUSE_SHIFT (3UL)
#define MACSEC_MSPU_MAC_LUMM_MODE_DUPLEX_MASK (0x4UL)
#define MACSEC_MSPU_MAC_LUMM_MODE_DUPLEX_SHIFT (2UL)
#define MACSEC_MSPU_MAC_LUMM_MODE_SPEED_MASK (0x3UL)
#define MACSEC_MSPU_MAC_LUMM_MODE_SPEED_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUT0_TYPE;
#define MACSEC_MSPU_MAC_LUT0_TAG_0_TAG_0_RSVD_2_MASK (0xfffe0000UL)
#define MACSEC_MSPU_MAC_LUT0_TAG_0_TAG_0_RSVD_2_SHIFT (17UL)
#define MACSEC_MSPU_MAC_LUT0_TAG_0_CONFIG_OUTER_TPID_ENABLE_MASK (0x10000UL)
#define MACSEC_MSPU_MAC_LUT0_TAG_0_CONFIG_OUTER_TPID_ENABLE_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUT0_TAG_0_FRM_TAG_0_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUT0_TAG_0_FRM_TAG_0_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUT1_TYPE;
#define MACSEC_MSPU_MAC_LUT1_TAG_1_TAG_1_RSVD_2_MASK (0xfffe0000UL)
#define MACSEC_MSPU_MAC_LUT1_TAG_1_TAG_1_RSVD_2_SHIFT (17UL)
#define MACSEC_MSPU_MAC_LUT1_TAG_1_CONFIG_INNER_TPID_ENABLE_MASK (0x10000UL)
#define MACSEC_MSPU_MAC_LUT1_TAG_1_CONFIG_INNER_TPID_ENABLE_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUT1_TAG_1_FRM_TAG_1_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUT1_TAG_1_FRM_TAG_1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LURPQS_TYPE;
#define MACSEC_MSPU_MAC_LURPQS_RPQSRPQSR3_MASK (0xfffc0000UL)
#define MACSEC_MSPU_MAC_LURPQS_RPQSRPQSR3_SHIFT (18UL)
#define MACSEC_MSPU_MAC_LURPQS_RX_PAUSE_QUANTA_SCALE_SCALE_FIX_MASK (0x20000UL)
#define MACSEC_MSPU_MAC_LURPQS_RX_PAUSE_QUANTA_SCALE_SCALE_FIX_SHIFT (17UL)
#define MACSEC_MSPU_MAC_LURPQS_RPQSSC_MASK (0x10000UL)
#define MACSEC_MSPU_MAC_LURPQS_RPQSSC_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LURPQS_RX_PAUSE_QUANTA_SCALE_SCALE_VALUE_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LURPQS_RX_PAUSE_QUANTA_SCALE_SCALE_VALUE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUTP_TYPE;
#define MACSEC_MSPU_MAC_LUTP_TX_PREAMBLE_TX_PREAMBLE_RSVD_1_MASK (0xfffffff8UL)
#define MACSEC_MSPU_MAC_LUTP_TX_PREAMBLE_TX_PREAMBLE_RSVD_1_SHIFT (3UL)
#define MACSEC_MSPU_MAC_LUTP_TX_PREAMBLE_TX_PREAMBLE_MASK (0x7UL)
#define MACSEC_MSPU_MAC_LUTP_TX_PREAMBLE_TX_PREAMBLE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUTIL_TYPE;
#define MACSEC_MSPU_MAC_LUTIL_TX_IPG_LENGTH_TX_IPG_LENGTH_RSVD_1_MASK (0xffffff80UL)
#define MACSEC_MSPU_MAC_LUTIL_TX_IPG_LENGTH_TX_IPG_LENGTH_RSVD_1_SHIFT (7UL)
#define MACSEC_MSPU_MAC_LUTIL_TX_IPG_LENGTH_TX_IPG_LENGTH_MASK (0x7fUL)
#define MACSEC_MSPU_MAC_LUTIL_TX_IPG_LENGTH_TX_IPG_LENGTH_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUPXT_TYPE;
#define MACSEC_MSPU_MAC_LUPXT_PXTPXTR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_LUPXT_PXTPXTR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUPXT_PFC_XOFF_TIMER_PFC_XOFF_TIMER_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUPXT_PFC_XOFF_TIMER_PFC_XOFF_TIMER_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUUEC_TYPE;
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_UMAC_EEE_CTRL_RSVD_5_MASK (0xffffff00UL)
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_UMAC_EEE_CTRL_RSVD_5_SHIFT (8UL)
#define MACSEC_MSPU_MAC_LUUEC_UECLIPM_MASK (0x80UL)
#define MACSEC_MSPU_MAC_LUUEC_UECLIPM_SHIFT (7UL)
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_DIS_EEE_10M_MASK (0x40UL)
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_DIS_EEE_10M_SHIFT (6UL)
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_EEE_TXCLK_DIS_MASK (0x20UL)
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_EEE_TXCLK_DIS_SHIFT (5UL)
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_RX_FIFO_CHECK_MASK (0x10UL)
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_RX_FIFO_CHECK_SHIFT (4UL)
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_EEE_EN_MASK (0x8UL)
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_EEE_EN_SHIFT (3UL)
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_UMAC_EEE_CTRL_RSVD_1_MASK (0x7UL)
#define MACSEC_MSPU_MAC_LUUEC_UMAC_EEE_CTRL_UMAC_EEE_CTRL_RSVD_1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUMEDET_TYPE;
#define MACSEC_MSPU_MAC_LUMEDET_MEDETMELT_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_LUMEDET_MEDETMELT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUGEDET_TYPE;
#define MACSEC_MSPU_MAC_LUGEDET_GEDETGELT_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_LUGEDET_GEDETGELT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUUERC_TYPE;
#define MACSEC_MSPU_MAC_LUUERC_UERCUERCR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_LUUERC_UERCUERCR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUUERC_UMAC_EEE_REF_COUNT_EEE_REF_COUNT_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUUERC_UMAC_EEE_REF_COUNT_EEE_REF_COUNT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUUTA_TYPE;
#define MACSEC_MSPU_MAC_LUUTA_LUUTAR_MASK (0xfffff800UL)
#define MACSEC_MSPU_MAC_LUUTA_LUUTAR_SHIFT (11UL)
#define MACSEC_MSPU_MAC_LUUTA_AUTO_ADJUST_MASK (0x400UL)
#define MACSEC_MSPU_MAC_LUUTA_AUTO_ADJUST_SHIFT (10UL)
#define MACSEC_MSPU_MAC_LUUTA_EN_1588_MASK (0x200UL)
#define MACSEC_MSPU_MAC_LUUTA_EN_1588_SHIFT (9UL)
#define MACSEC_MSPU_MAC_LUUTA_ADJUST_MASK (0x1ffUL)
#define MACSEC_MSPU_MAC_LUUTA_ADJUST_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUURPDS_TYPE;
#define MACSEC_MSPU_MAC_LUURPDS_URPDSURPDSR1_MASK (0xfffffffeUL)
#define MACSEC_MSPU_MAC_LUURPDS_URPDSURPDSR1_SHIFT (1UL)
#define MACSEC_MSPU_MAC_LUURPDS_URPDSRII_MASK (0x1UL)
#define MACSEC_MSPU_MAC_LUURPDS_URPDSRII_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUUSIT_TYPE;
#define MACSEC_MSPU_MAC_LUUSIT_USITUSITR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_LUUSIT_USITUSITR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUUSIT_USITTV_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUUSIT_USITTV_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUMEWT_TYPE;
#define MACSEC_MSPU_MAC_LUMEWT_MEWTMEWTR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_LUMEWT_MEWTMEWTR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUMEWT_MEWTMEWT_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUMEWT_MEWTMEWT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUGEWT_TYPE;
#define MACSEC_MSPU_MAC_LUGEWT_GEWTGEWTR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_LUGEWT_GEWTGEWTR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUGEWT_GEWTGEWT_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUGEWT_GEWTGEWT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUURI_TYPE;
#define MACSEC_MSPU_MAC_LUURI_UMAC_REV_ID_UMAC_REV_ID_RSVD_3_MASK (0xff000000UL)
#define MACSEC_MSPU_MAC_LUURI_UMAC_REV_ID_UMAC_REV_ID_RSVD_3_SHIFT (24UL)
#define MACSEC_MSPU_MAC_LUURI_UMAC_REV_ID_REVISION_ID_MAJOR_MASK (0xff0000UL)
#define MACSEC_MSPU_MAC_LUURI_UMAC_REV_ID_REVISION_ID_MAJOR_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUURI_UMAC_REV_ID_REVISION_ID_MINOR_MASK (0xff00UL)
#define MACSEC_MSPU_MAC_LUURI_UMAC_REV_ID_REVISION_ID_MINOR_SHIFT (8UL)
#define MACSEC_MSPU_MAC_LUURI_UMAC_REV_ID_PATCH_MASK (0xffUL)
#define MACSEC_MSPU_MAC_LUURI_UMAC_REV_ID_PATCH_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUMP_TYPE;
#define MACSEC_MSPU_MAC_LUMP_PFC_TYPE_PFC_TYPE_RSVD_1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_LUMP_PFC_TYPE_PFC_TYPE_RSVD_1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUMP_PFC_TYPE_PFC_ETH_TYPE_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUMP_PFC_TYPE_PFC_ETH_TYPE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUMPO_TYPE;
#define MACSEC_MSPU_MAC_LUMPO_MPOMPOR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_LUMPO_MPOMPOR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUMPO_MAC_PFC_OPCODE_PFC_OPCODE_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUMPO_MAC_PFC_OPCODE_PFC_OPCODE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUMPD0_TYPE;
#define MACSEC_MSPU_MAC_LUMPD0_PFC_DA_0_PFC_MACDA_0_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_LUMPD0_PFC_DA_0_PFC_MACDA_0_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUMPD1_TYPE;
#define MACSEC_MSPU_MAC_LUMPD1_PFC_DA_1_PFC_DA_1_RSVD_1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_LUMPD1_PFC_DA_1_PFC_DA_1_RSVD_1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUMPD1_PFC_DA_1_PFC_MACDA_1_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_LUMPD1_PFC_DA_1_PFC_MACDA_1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUMPTC_TYPE;
#define MACSEC_MSPU_MAC_LUMPTC_PROG_TX_CRC_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_LUMPTC_PROG_TX_CRC_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUMC_TYPE;
#define MACSEC_MSPU_MAC_LUMC_CNTRL_CNTRL_RSVD_4_MASK (0xfffffff0UL)
#define MACSEC_MSPU_MAC_LUMC_CNTRL_CNTRL_RSVD_4_SHIFT (4UL)
#define MACSEC_MSPU_MAC_LUMC_CNTRL_DIS_PAUSE_DATA_VAR_IPG_MASK (0x8UL)
#define MACSEC_MSPU_MAC_LUMC_CNTRL_DIS_PAUSE_DATA_VAR_IPG_SHIFT (3UL)
#define MACSEC_MSPU_MAC_LUMC_CNTRL_TX_CRC_PROGRAM_MASK (0x4UL)
#define MACSEC_MSPU_MAC_LUMC_CNTRL_TX_CRC_PROGRAM_SHIFT (2UL)
#define MACSEC_MSPU_MAC_LUMC_CNTRL_TX_CRC_CORUPT_EN_MASK (0x2UL)
#define MACSEC_MSPU_MAC_LUMC_CNTRL_TX_CRC_CORUPT_EN_SHIFT (1UL)
#define MACSEC_MSPU_MAC_LUMC_CNTRL_TX_LAUNCH_EN_MASK (0x1UL)
#define MACSEC_MSPU_MAC_LUMC_CNTRL_TX_LAUNCH_EN_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUTSC_TYPE;
#define MACSEC_MSPU_MAC_LUTSC_TSCTSCR3_MASK (0xffffffe0UL)
#define MACSEC_MSPU_MAC_LUTSC_TSCTSCR3_SHIFT (5UL)
#define MACSEC_MSPU_MAC_LUTSC_TS_STATUS_CNTRL_WORD_AVAIL_MASK (0x1cUL)
#define MACSEC_MSPU_MAC_LUTSC_TS_STATUS_CNTRL_WORD_AVAIL_SHIFT (2UL)
#define MACSEC_MSPU_MAC_LUTSC_TS_STATUS_CNTRL_TX_TS_FIFO_EMPTY_MASK (0x2UL)
#define MACSEC_MSPU_MAC_LUTSC_TS_STATUS_CNTRL_TX_TS_FIFO_EMPTY_SHIFT (1UL)
#define MACSEC_MSPU_MAC_LUTSC_TS_STATUS_CNTRL_TX_TS_FIFO_FULL_MASK (0x1UL)
#define MACSEC_MSPU_MAC_LUTSC_TS_STATUS_CNTRL_TX_TS_FIFO_FULL_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUTTD_TYPE;
#define MACSEC_MSPU_MAC_LUTTD_TX_TS_DATA_TX_TS_DATA_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_LUTTD_TX_TS_DATA_TX_TS_DATA_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUPC_TYPE;
#define MACSEC_MSPU_MAC_LUPC_PAUSE_CONTROL_PAUSE_CONTROL_RSVD_2_MASK (0xfffc0000UL)
#define MACSEC_MSPU_MAC_LUPC_PAUSE_CONTROL_PAUSE_CONTROL_RSVD_2_SHIFT (18UL)
#define MACSEC_MSPU_MAC_LUPC_PAUSE_CONTROL_ENABLE_MASK (0x20000UL)
#define MACSEC_MSPU_MAC_LUPC_PAUSE_CONTROL_ENABLE_SHIFT (17UL)
#define MACSEC_MSPU_MAC_LUPC_PAUSE_CONTROL_VALUE_MASK (0x1ffffUL)
#define MACSEC_MSPU_MAC_LUPC_PAUSE_CONTROL_VALUE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUFC_TYPE;
#define MACSEC_MSPU_MAC_LUFC_FLUSH_CONTROL_FLUSH_CONTROL_RSVD_1_MASK (0xfffffffeUL)
#define MACSEC_MSPU_MAC_LUFC_FLUSH_CONTROL_FLUSH_CONTROL_RSVD_1_SHIFT (1UL)
#define MACSEC_MSPU_MAC_LUFC_FLUSH_CONTROL_FLUSH_MASK (0x1UL)
#define MACSEC_MSPU_MAC_LUFC_FLUSH_CONTROL_FLUSH_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LURS_TYPE;
#define MACSEC_MSPU_MAC_LURS_RXFIFO_STAT_RXFIFO_STAT_RSVD_2_MASK (0xfffffffcUL)
#define MACSEC_MSPU_MAC_LURS_RXFIFO_STAT_RXFIFO_STAT_RSVD_2_SHIFT (2UL)
#define MACSEC_MSPU_MAC_LURS_RXFIFO_STAT_RXFIFO_OVERRUN_MASK (0x2UL)
#define MACSEC_MSPU_MAC_LURS_RXFIFO_STAT_RXFIFO_OVERRUN_SHIFT (1UL)
#define MACSEC_MSPU_MAC_LURS_RXFIFO_STAT_RXFIFO_UNDERRUN_MASK (0x1UL)
#define MACSEC_MSPU_MAC_LURS_RXFIFO_STAT_RXFIFO_UNDERRUN_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUTS_TYPE;
#define MACSEC_MSPU_MAC_LUTS_TXFIFO_STAT_TXFIFO_STAT_RSVD_2_MASK (0xfffffffcUL)
#define MACSEC_MSPU_MAC_LUTS_TXFIFO_STAT_TXFIFO_STAT_RSVD_2_SHIFT (2UL)
#define MACSEC_MSPU_MAC_LUTS_TXFIFO_STAT_TXFIFO_OVERRUN_MASK (0x2UL)
#define MACSEC_MSPU_MAC_LUTS_TXFIFO_STAT_TXFIFO_OVERRUN_SHIFT (1UL)
#define MACSEC_MSPU_MAC_LUTS_TXFIFO_STAT_TXFIFO_UNDERRUN_MASK (0x1UL)
#define MACSEC_MSPU_MAC_LUTS_TXFIFO_STAT_TXFIFO_UNDERRUN_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUMPC_TYPE;
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_PFC_CTRL_RSVD_5_MASK (0xffffffc0UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_PFC_CTRL_RSVD_5_SHIFT (6UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_PFC_STATS_EN_MASK (0x20UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_PFC_STATS_EN_SHIFT (5UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_RX_PASS_PFC_FRM_MASK (0x10UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_RX_PASS_PFC_FRM_SHIFT (4UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_PFC_CTRL_RSVD_3_MASK (0x8UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_PFC_CTRL_RSVD_3_SHIFT (3UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_FORCE_PFC_XON_MASK (0x4UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_FORCE_PFC_XON_SHIFT (2UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_PFC_RX_ENBL_MASK (0x2UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_PFC_RX_ENBL_SHIFT (1UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_PFC_TX_ENBL_MASK (0x1UL)
#define MACSEC_MSPU_MAC_LUMPC_PFC_CTRL_PFC_TX_ENBL_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_LUMPRC_TYPE;
#define MACSEC_MSPU_MAC_LUMPRC_MPRCPRT_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_LUMPRC_MPRCPRT_SHIFT (16UL)
#define MACSEC_MSPU_MAC_LUMPRC_MPRCMPRCR1_MASK (0xfffeUL)
#define MACSEC_MSPU_MAC_LUMPRC_MPRCMPRCR1_SHIFT (1UL)
#define MACSEC_MSPU_MAC_LUMPRC_MPRCPRE_MASK (0x1UL)
#define MACSEC_MSPU_MAC_LUMPRC_MPRCPRE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUIHBC_TYPE;
#define MACSEC_MSPU_MAC_SUIHBC_IHBCIHBCR3_MASK (0xffffff80UL)
#define MACSEC_MSPU_MAC_SUIHBC_IHBCIHBCR3_SHIFT (7UL)
#define MACSEC_MSPU_MAC_SUIHBC_IPG_HD_BKP_CNTL_IPG_CONFIG_RX_MASK (0x7cUL)
#define MACSEC_MSPU_MAC_SUIHBC_IPG_HD_BKP_CNTL_IPG_CONFIG_RX_SHIFT (2UL)
#define MACSEC_MSPU_MAC_SUIHBC_IPG_HD_BKP_CNTL_HD_FC_BKOFF_OK_MASK (0x2UL)
#define MACSEC_MSPU_MAC_SUIHBC_IPG_HD_BKP_CNTL_HD_FC_BKOFF_OK_SHIFT (1UL)
#define MACSEC_MSPU_MAC_SUIHBC_IPG_HD_BKP_CNTL_HD_FC_ENA_MASK (0x1UL)
#define MACSEC_MSPU_MAC_SUIHBC_IPG_HD_BKP_CNTL_HD_FC_ENA_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUCC_TYPE;
#define MACSEC_MSPU_MAC_SUCC_CCCCR28_MASK (0x80000000UL)
#define MACSEC_MSPU_MAC_SUCC_CCCCR28_SHIFT (31UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_RUNT_FILTER_DIS_MASK (0x40000000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_RUNT_FILTER_DIS_SHIFT (30UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_OOB_EFC_EN_MASK (0x20000000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_OOB_EFC_EN_SHIFT (29UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_IGNORE_TX_PAUSE_MASK (0x10000000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_IGNORE_TX_PAUSE_SHIFT (28UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_FD_TX_URUN_FIX_EN_MASK (0x8000000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_FD_TX_URUN_FIX_EN_SHIFT (27UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_RX_ERR_DISC_MASK (0x4000000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_RX_ERR_DISC_SHIFT (26UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_LINE_LOOPBACK_MASK (0x2000000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_LINE_LOOPBACK_SHIFT (25UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_NO_LGTH_CHECK_MASK (0x1000000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_NO_LGTH_CHECK_SHIFT (24UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_CNTL_FRM_ENA_MASK (0x800000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_CNTL_FRM_ENA_SHIFT (23UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_ENA_EXT_CONFIG_MASK (0x400000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_ENA_EXT_CONFIG_SHIFT (22UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_EN_INTERNAL_TX_CRS_MASK (0x200000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_EN_INTERNAL_TX_CRS_SHIFT (21UL)
#define MACSEC_MSPU_MAC_SUCC_CCCCR181_MASK (0x180000UL)
#define MACSEC_MSPU_MAC_SUCC_CCCCR181_SHIFT (19UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_SW_OVERRIDE_RX_MASK (0x40000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_SW_OVERRIDE_RX_SHIFT (18UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_SW_OVERRIDE_TX_MASK (0x20000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_SW_OVERRIDE_TX_SHIFT (17UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_MAC_LOOP_CON_MASK (0x10000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_MAC_LOOP_CON_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_LOOP_ENA_MASK (0x8000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_LOOP_ENA_SHIFT (15UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_FCS_CORRUPT_URUN_EN_MASK (0x4000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_FCS_CORRUPT_URUN_EN_SHIFT (14UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_SW_RESET_MASK (0x2000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_SW_RESET_SHIFT (13UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_OVERFLOW_EN_MASK (0x1000UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_OVERFLOW_EN_SHIFT (12UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_RX_LOW_LATENCY_EN_MASK (0x800UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_RX_LOW_LATENCY_EN_SHIFT (11UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_HD_ENA_MASK (0x400UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_HD_ENA_SHIFT (10UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_TX_ADDR_INS_MASK (0x200UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_TX_ADDR_INS_SHIFT (9UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_PAUSE_IGNORE_MASK (0x100UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_PAUSE_IGNORE_SHIFT (8UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_PAUSE_FWD_MASK (0x80UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_PAUSE_FWD_SHIFT (7UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_CRC_FWD_MASK (0x40UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_CRC_FWD_SHIFT (6UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_PAD_EN_MASK (0x20UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_PAD_EN_SHIFT (5UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_PROMIS_EN_MASK (0x10UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_PROMIS_EN_SHIFT (4UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_ETH_SPEED_MASK (0xcUL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_ETH_SPEED_SHIFT (2UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_RX_ENA_MASK (0x2UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_RX_ENA_SHIFT (1UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_TX_ENA_MASK (0x1UL)
#define MACSEC_MSPU_MAC_SUCC_COMMAND_CONFIG_TX_ENA_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SWITCH_UNIMAC_MAC_0_TYPE;
#define MACSEC_MSPU_MAC_SWITCH_UNIMAC_MAC_0_ADDR0_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_SWITCH_UNIMAC_MAC_0_ADDR0_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SWITCH_UNIMAC_MAC_1_TYPE;
#define MACSEC_MSPU_MAC_SWITCH_UNIMAC_MAC_1_RSVD_1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_SWITCH_UNIMAC_MAC_1_RSVD_1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SWITCH_UNIMAC_MAC_1_ADDR1_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SWITCH_UNIMAC_MAC_1_ADDR1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUFL_TYPE;
#define MACSEC_MSPU_MAC_SUFL_FRM_LENGTH_FRM_LENGTH_RSVD_1_MASK (0xffffc000UL)
#define MACSEC_MSPU_MAC_SUFL_FRM_LENGTH_FRM_LENGTH_RSVD_1_SHIFT (14UL)
#define MACSEC_MSPU_MAC_SUFL_FRM_LENGTH_MAXFR_MASK (0x3fffUL)
#define MACSEC_MSPU_MAC_SUFL_FRM_LENGTH_MAXFR_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUPQ_TYPE;
#define MACSEC_MSPU_MAC_SUPQ_PAUSE_QUANT_PAUSE_QUANT_RSVD_1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_SUPQ_PAUSE_QUANT_PAUSE_QUANT_RSVD_1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUPQ_PAUSE_QUANT_STAD2_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUPQ_PAUSE_QUANT_STAD2_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUTTSI_TYPE;
#define MACSEC_MSPU_MAC_SUTTSI_TX_TS_SEQ_ID_TX_TS_SEQ_ID_RSVD_2_MASK (0xfffe0000UL)
#define MACSEC_MSPU_MAC_SUTTSI_TX_TS_SEQ_ID_TX_TS_SEQ_ID_RSVD_2_SHIFT (17UL)
#define MACSEC_MSPU_MAC_SUTTSI_TX_TS_SEQ_ID_TSTS_VALID_MASK (0x10000UL)
#define MACSEC_MSPU_MAC_SUTTSI_TX_TS_SEQ_ID_TSTS_VALID_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUTTSI_TX_TS_SEQ_ID_TSTS_SEQ_ID_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUTTSI_TX_TS_SEQ_ID_TSTS_SEQ_ID_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUSO_TYPE;
#define MACSEC_MSPU_MAC_SUSO_SFD_OFFSET_SFD_OFFSET_RSVD_1_MASK (0xfffffff0UL)
#define MACSEC_MSPU_MAC_SUSO_SFD_OFFSET_SFD_OFFSET_RSVD_1_SHIFT (4UL)
#define MACSEC_MSPU_MAC_SUSO_SFD_OFFSET_SFD_OFFSET_MASK (0xfUL)
#define MACSEC_MSPU_MAC_SUSO_SFD_OFFSET_SFD_OFFSET_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUMM_TYPE;
#define MACSEC_MSPU_MAC_SUMM_MODE_MODE_RSVD_5_MASK (0xffffffc0UL)
#define MACSEC_MSPU_MAC_SUMM_MODE_MODE_RSVD_5_SHIFT (6UL)
#define MACSEC_MSPU_MAC_SUMM_MODE_LINK_STATUS_MASK (0x20UL)
#define MACSEC_MSPU_MAC_SUMM_MODE_LINK_STATUS_SHIFT (5UL)
#define MACSEC_MSPU_MAC_SUMM_MODE_TX_PAUSE_MASK (0x10UL)
#define MACSEC_MSPU_MAC_SUMM_MODE_TX_PAUSE_SHIFT (4UL)
#define MACSEC_MSPU_MAC_SUMM_MODE_RX_PAUSE_MASK (0x8UL)
#define MACSEC_MSPU_MAC_SUMM_MODE_RX_PAUSE_SHIFT (3UL)
#define MACSEC_MSPU_MAC_SUMM_MODE_DUPLEX_MASK (0x4UL)
#define MACSEC_MSPU_MAC_SUMM_MODE_DUPLEX_SHIFT (2UL)
#define MACSEC_MSPU_MAC_SUMM_MODE_SPEED_MASK (0x3UL)
#define MACSEC_MSPU_MAC_SUMM_MODE_SPEED_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUT0_TYPE;
#define MACSEC_MSPU_MAC_SUT0_TAG_0_TAG_0_RSVD_2_MASK (0xfffe0000UL)
#define MACSEC_MSPU_MAC_SUT0_TAG_0_TAG_0_RSVD_2_SHIFT (17UL)
#define MACSEC_MSPU_MAC_SUT0_TAG_0_CONFIG_OUTER_TPID_ENABLE_MASK (0x10000UL)
#define MACSEC_MSPU_MAC_SUT0_TAG_0_CONFIG_OUTER_TPID_ENABLE_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUT0_TAG_0_FRM_TAG_0_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUT0_TAG_0_FRM_TAG_0_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUT1_TYPE;
#define MACSEC_MSPU_MAC_SUT1_TAG_1_TAG_1_RSVD_2_MASK (0xfffe0000UL)
#define MACSEC_MSPU_MAC_SUT1_TAG_1_TAG_1_RSVD_2_SHIFT (17UL)
#define MACSEC_MSPU_MAC_SUT1_TAG_1_CONFIG_INNER_TPID_ENABLE_MASK (0x10000UL)
#define MACSEC_MSPU_MAC_SUT1_TAG_1_CONFIG_INNER_TPID_ENABLE_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUT1_TAG_1_FRM_TAG_1_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUT1_TAG_1_FRM_TAG_1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SURPQS_TYPE;
#define MACSEC_MSPU_MAC_SURPQS_RPQSRPQSR3_MASK (0xfffc0000UL)
#define MACSEC_MSPU_MAC_SURPQS_RPQSRPQSR3_SHIFT (18UL)
#define MACSEC_MSPU_MAC_SURPQS_RX_PAUSE_QUANTA_SCALE_SCALE_FIX_MASK (0x20000UL)
#define MACSEC_MSPU_MAC_SURPQS_RX_PAUSE_QUANTA_SCALE_SCALE_FIX_SHIFT (17UL)
#define MACSEC_MSPU_MAC_SURPQS_RPQSSC1_MASK (0x10000UL)
#define MACSEC_MSPU_MAC_SURPQS_RPQSSC1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SURPQS_RX_PAUSE_QUANTA_SCALE_SCALE_VALUE_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SURPQS_RX_PAUSE_QUANTA_SCALE_SCALE_VALUE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUTP_TYPE;
#define MACSEC_MSPU_MAC_SUTP_TX_PREAMBLE_TX_PREAMBLE_RSVD_1_MASK (0xfffffff8UL)
#define MACSEC_MSPU_MAC_SUTP_TX_PREAMBLE_TX_PREAMBLE_RSVD_1_SHIFT (3UL)
#define MACSEC_MSPU_MAC_SUTP_TX_PREAMBLE_TX_PREAMBLE_MASK (0x7UL)
#define MACSEC_MSPU_MAC_SUTP_TX_PREAMBLE_TX_PREAMBLE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUTIL_TYPE;
#define MACSEC_MSPU_MAC_SUTIL_TX_IPG_LENGTH_TX_IPG_LENGTH_RSVD_1_MASK (0xffffff80UL)
#define MACSEC_MSPU_MAC_SUTIL_TX_IPG_LENGTH_TX_IPG_LENGTH_RSVD_1_SHIFT (7UL)
#define MACSEC_MSPU_MAC_SUTIL_TX_IPG_LENGTH_TX_IPG_LENGTH_MASK (0x7fUL)
#define MACSEC_MSPU_MAC_SUTIL_TX_IPG_LENGTH_TX_IPG_LENGTH_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUPXT_TYPE;
#define MACSEC_MSPU_MAC_SUPXT_PXTPXTR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_SUPXT_PXTPXTR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUPXT_PFC_XOFF_TIMER_PFC_XOFF_TIMER_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUPXT_PFC_XOFF_TIMER_PFC_XOFF_TIMER_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUUEC_TYPE;
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_UMAC_EEE_CTRL_RSVD_5_MASK (0xffffff00UL)
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_UMAC_EEE_CTRL_RSVD_5_SHIFT (8UL)
#define MACSEC_MSPU_MAC_SUUEC_UECLIPM1_MASK (0x80UL)
#define MACSEC_MSPU_MAC_SUUEC_UECLIPM1_SHIFT (7UL)
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_DIS_EEE_10M_MASK (0x40UL)
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_DIS_EEE_10M_SHIFT (6UL)
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_EEE_TXCLK_DIS_MASK (0x20UL)
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_EEE_TXCLK_DIS_SHIFT (5UL)
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_RX_FIFO_CHECK_MASK (0x10UL)
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_RX_FIFO_CHECK_SHIFT (4UL)
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_EEE_EN_MASK (0x8UL)
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_EEE_EN_SHIFT (3UL)
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_UMAC_EEE_CTRL_RSVD_1_MASK (0x7UL)
#define MACSEC_MSPU_MAC_SUUEC_UMAC_EEE_CTRL_UMAC_EEE_CTRL_RSVD_1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUMEDET_TYPE;
#define MACSEC_MSPU_MAC_SUMEDET_MEDETMELT_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_SUMEDET_MEDETMELT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUGEDET_TYPE;
#define MACSEC_MSPU_MAC_SUGEDET_GEDETGELT_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_SUGEDET_GEDETGELT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUUERC_TYPE;
#define MACSEC_MSPU_MAC_SUUERC_UERCUERCR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_SUUERC_UERCUERCR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUUERC_UMAC_EEE_REF_COUNT_EEE_REF_COUNT_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUUERC_UMAC_EEE_REF_COUNT_EEE_REF_COUNT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUUTA_TYPE;
#define MACSEC_MSPU_MAC_SUUTA_SUUTAR_MASK (0xfffff800UL)
#define MACSEC_MSPU_MAC_SUUTA_SUUTAR_SHIFT (11UL)
#define MACSEC_MSPU_MAC_SUUTA_AUTO_ADJUST_MASK (0x400UL)
#define MACSEC_MSPU_MAC_SUUTA_AUTO_ADJUST_SHIFT (10UL)
#define MACSEC_MSPU_MAC_SUUTA_EN_1588_MASK (0x200UL)
#define MACSEC_MSPU_MAC_SUUTA_EN_1588_SHIFT (9UL)
#define MACSEC_MSPU_MAC_SUUTA_ADJUST_MASK (0x1ffUL)
#define MACSEC_MSPU_MAC_SUUTA_ADJUST_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUURPDS_TYPE;
#define MACSEC_MSPU_MAC_SUURPDS_URPDSURPDSR1_MASK (0xfffffffeUL)
#define MACSEC_MSPU_MAC_SUURPDS_URPDSURPDSR1_SHIFT (1UL)
#define MACSEC_MSPU_MAC_SUURPDS_URPDSRII1_MASK (0x1UL)
#define MACSEC_MSPU_MAC_SUURPDS_URPDSRII1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUUSIT_TYPE;
#define MACSEC_MSPU_MAC_SUUSIT_USITUSITR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_SUUSIT_USITUSITR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUUSIT_USITTV1_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUUSIT_USITTV1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUMEWT_TYPE;
#define MACSEC_MSPU_MAC_SUMEWT_MEWTMEWTR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_SUMEWT_MEWTMEWTR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUMEWT_MEWTMEWT1_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUMEWT_MEWTMEWT1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUGEWT_TYPE;
#define MACSEC_MSPU_MAC_SUGEWT_GEWTGEWTR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_SUGEWT_GEWTGEWTR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUGEWT_GEWTGEWT1_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUGEWT_GEWTGEWT1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUURI_TYPE;
#define MACSEC_MSPU_MAC_SUURI_UMAC_REV_ID_UMAC_REV_ID_RSVD_3_MASK (0xff000000UL)
#define MACSEC_MSPU_MAC_SUURI_UMAC_REV_ID_UMAC_REV_ID_RSVD_3_SHIFT (24UL)
#define MACSEC_MSPU_MAC_SUURI_UMAC_REV_ID_REVISION_ID_MAJOR_MASK (0xff0000UL)
#define MACSEC_MSPU_MAC_SUURI_UMAC_REV_ID_REVISION_ID_MAJOR_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUURI_UMAC_REV_ID_REVISION_ID_MINOR_MASK (0xff00UL)
#define MACSEC_MSPU_MAC_SUURI_UMAC_REV_ID_REVISION_ID_MINOR_SHIFT (8UL)
#define MACSEC_MSPU_MAC_SUURI_UMAC_REV_ID_PATCH_MASK (0xffUL)
#define MACSEC_MSPU_MAC_SUURI_UMAC_REV_ID_PATCH_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUMP_TYPE;
#define MACSEC_MSPU_MAC_SUMP_PFC_TYPE_PFC_TYPE_RSVD_1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_SUMP_PFC_TYPE_PFC_TYPE_RSVD_1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUMP_PFC_TYPE_PFC_ETH_TYPE_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUMP_PFC_TYPE_PFC_ETH_TYPE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUMPO_TYPE;
#define MACSEC_MSPU_MAC_SUMPO_MPOMPOR1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_SUMPO_MPOMPOR1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUMPO_MAC_PFC_OPCODE_PFC_OPCODE_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUMPO_MAC_PFC_OPCODE_PFC_OPCODE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUMPD0_TYPE;
#define MACSEC_MSPU_MAC_SUMPD0_PFC_DA_0_PFC_MACDA_0_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_SUMPD0_PFC_DA_0_PFC_MACDA_0_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUMPD1_TYPE;
#define MACSEC_MSPU_MAC_SUMPD1_PFC_DA_1_PFC_DA_1_RSVD_1_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_SUMPD1_PFC_DA_1_PFC_DA_1_RSVD_1_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUMPD1_PFC_DA_1_PFC_MACDA_1_MASK (0xffffUL)
#define MACSEC_MSPU_MAC_SUMPD1_PFC_DA_1_PFC_MACDA_1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUMPTC_TYPE;
#define MACSEC_MSPU_MAC_SUMPTC_PROG_TX_CRC_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_SUMPTC_PROG_TX_CRC_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUMC_TYPE;
#define MACSEC_MSPU_MAC_SUMC_CNTRL_CNTRL_RSVD_4_MASK (0xfffffff0UL)
#define MACSEC_MSPU_MAC_SUMC_CNTRL_CNTRL_RSVD_4_SHIFT (4UL)
#define MACSEC_MSPU_MAC_SUMC_CNTRL_DIS_PAUSE_DATA_VAR_IPG_MASK (0x8UL)
#define MACSEC_MSPU_MAC_SUMC_CNTRL_DIS_PAUSE_DATA_VAR_IPG_SHIFT (3UL)
#define MACSEC_MSPU_MAC_SUMC_CNTRL_TX_CRC_PROGRAM_MASK (0x4UL)
#define MACSEC_MSPU_MAC_SUMC_CNTRL_TX_CRC_PROGRAM_SHIFT (2UL)
#define MACSEC_MSPU_MAC_SUMC_CNTRL_TX_CRC_CORUPT_EN_MASK (0x2UL)
#define MACSEC_MSPU_MAC_SUMC_CNTRL_TX_CRC_CORUPT_EN_SHIFT (1UL)
#define MACSEC_MSPU_MAC_SUMC_CNTRL_TX_LAUNCH_EN_MASK (0x1UL)
#define MACSEC_MSPU_MAC_SUMC_CNTRL_TX_LAUNCH_EN_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUTSC_TYPE;
#define MACSEC_MSPU_MAC_SUTSC_TSCTSCR3_MASK (0xffffffe0UL)
#define MACSEC_MSPU_MAC_SUTSC_TSCTSCR3_SHIFT (5UL)
#define MACSEC_MSPU_MAC_SUTSC_TS_STATUS_CNTRL_WORD_AVAIL_MASK (0x1cUL)
#define MACSEC_MSPU_MAC_SUTSC_TS_STATUS_CNTRL_WORD_AVAIL_SHIFT (2UL)
#define MACSEC_MSPU_MAC_SUTSC_TS_STATUS_CNTRL_TX_TS_FIFO_EMPTY_MASK (0x2UL)
#define MACSEC_MSPU_MAC_SUTSC_TS_STATUS_CNTRL_TX_TS_FIFO_EMPTY_SHIFT (1UL)
#define MACSEC_MSPU_MAC_SUTSC_TS_STATUS_CNTRL_TX_TS_FIFO_FULL_MASK (0x1UL)
#define MACSEC_MSPU_MAC_SUTSC_TS_STATUS_CNTRL_TX_TS_FIFO_FULL_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUTTD_TYPE;
#define MACSEC_MSPU_MAC_SUTTD_TX_TS_DATA_TX_TS_DATA_MASK (0xffffffffUL)
#define MACSEC_MSPU_MAC_SUTTD_TX_TS_DATA_TX_TS_DATA_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUPC_TYPE;
#define MACSEC_MSPU_MAC_SUPC_PAUSE_CONTROL_PAUSE_CONTROL_RSVD_2_MASK (0xfffc0000UL)
#define MACSEC_MSPU_MAC_SUPC_PAUSE_CONTROL_PAUSE_CONTROL_RSVD_2_SHIFT (18UL)
#define MACSEC_MSPU_MAC_SUPC_PAUSE_CONTROL_ENABLE_MASK (0x20000UL)
#define MACSEC_MSPU_MAC_SUPC_PAUSE_CONTROL_ENABLE_SHIFT (17UL)
#define MACSEC_MSPU_MAC_SUPC_PAUSE_CONTROL_VALUE_MASK (0x1ffffUL)
#define MACSEC_MSPU_MAC_SUPC_PAUSE_CONTROL_VALUE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUFC_TYPE;
#define MACSEC_MSPU_MAC_SUFC_FLUSH_CONTROL_FLUSH_CONTROL_RSVD_1_MASK (0xfffffffeUL)
#define MACSEC_MSPU_MAC_SUFC_FLUSH_CONTROL_FLUSH_CONTROL_RSVD_1_SHIFT (1UL)
#define MACSEC_MSPU_MAC_SUFC_FLUSH_CONTROL_FLUSH_MASK (0x1UL)
#define MACSEC_MSPU_MAC_SUFC_FLUSH_CONTROL_FLUSH_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SURS_TYPE;
#define MACSEC_MSPU_MAC_SURS_RXFIFO_STAT_RXFIFO_STAT_RSVD_2_MASK (0xfffffffcUL)
#define MACSEC_MSPU_MAC_SURS_RXFIFO_STAT_RXFIFO_STAT_RSVD_2_SHIFT (2UL)
#define MACSEC_MSPU_MAC_SURS_RXFIFO_STAT_RXFIFO_OVERRUN_MASK (0x2UL)
#define MACSEC_MSPU_MAC_SURS_RXFIFO_STAT_RXFIFO_OVERRUN_SHIFT (1UL)
#define MACSEC_MSPU_MAC_SURS_RXFIFO_STAT_RXFIFO_UNDERRUN_MASK (0x1UL)
#define MACSEC_MSPU_MAC_SURS_RXFIFO_STAT_RXFIFO_UNDERRUN_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUTS_TYPE;
#define MACSEC_MSPU_MAC_SUTS_TXFIFO_STAT_TXFIFO_STAT_RSVD_2_MASK (0xfffffffcUL)
#define MACSEC_MSPU_MAC_SUTS_TXFIFO_STAT_TXFIFO_STAT_RSVD_2_SHIFT (2UL)
#define MACSEC_MSPU_MAC_SUTS_TXFIFO_STAT_TXFIFO_OVERRUN_MASK (0x2UL)
#define MACSEC_MSPU_MAC_SUTS_TXFIFO_STAT_TXFIFO_OVERRUN_SHIFT (1UL)
#define MACSEC_MSPU_MAC_SUTS_TXFIFO_STAT_TXFIFO_UNDERRUN_MASK (0x1UL)
#define MACSEC_MSPU_MAC_SUTS_TXFIFO_STAT_TXFIFO_UNDERRUN_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUMPC_TYPE;
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_PFC_CTRL_RSVD_5_MASK (0xffffffc0UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_PFC_CTRL_RSVD_5_SHIFT (6UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_PFC_STATS_EN_MASK (0x20UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_PFC_STATS_EN_SHIFT (5UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_RX_PASS_PFC_FRM_MASK (0x10UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_RX_PASS_PFC_FRM_SHIFT (4UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_PFC_CTRL_RSVD_3_MASK (0x8UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_PFC_CTRL_RSVD_3_SHIFT (3UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_FORCE_PFC_XON_MASK (0x4UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_FORCE_PFC_XON_SHIFT (2UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_PFC_RX_ENBL_MASK (0x2UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_PFC_RX_ENBL_SHIFT (1UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_PFC_TX_ENBL_MASK (0x1UL)
#define MACSEC_MSPU_MAC_SUMPC_PFC_CTRL_PFC_TX_ENBL_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_MAC_SUMPRC_TYPE;
#define MACSEC_MSPU_MAC_SUMPRC_MPRCPRT_MASK (0xffff0000UL)
#define MACSEC_MSPU_MAC_SUMPRC_MPRCPRT_SHIFT (16UL)
#define MACSEC_MSPU_MAC_SUMPRC_MPRCMPRCR11_MASK (0xfffeUL)
#define MACSEC_MSPU_MAC_SUMPRC_MPRCMPRCR11_SHIFT (1UL)
#define MACSEC_MSPU_MAC_SUMPRC_MPRCPRE1_MASK (0x1UL)
#define MACSEC_MSPU_MAC_SUMPRC_MPRCPRE1_SHIFT (0UL)




typedef volatile struct COMP_PACKED sMACSEC_MSPU_MAC_RDBType {
    MACSEC_MSPU_MAC_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x0 */
    MACSEC_MSPU_MAC_LUIHBC_TYPE line_ipg_hd_bkp_cntl; /* OFFSET: 0x4 */
    MACSEC_MSPU_MAC_LUCC_TYPE line_command_config; /* OFFSET: 0x8 */
    MACSEC_MSPU_MAC_LINE_UNIMAC_MAC_0_TYPE line_mac_0; /* OFFSET: 0xc */
    MACSEC_MSPU_MAC_LINE_UNIMAC_MAC_1_TYPE line_mac_1; /* OFFSET: 0x10 */
    MACSEC_MSPU_MAC_LUFL_TYPE line_frm_length; /* OFFSET: 0x14 */
    MACSEC_MSPU_MAC_LUPQ_TYPE line_pause_quant; /* OFFSET: 0x18 */
    MACSEC_MSPU_MAC_RESERVED_TYPE rsvd1[32]; /* OFFSET: 0x1c */
    MACSEC_MSPU_MAC_LUTTSI_TYPE line_tx_ts_seq_id; /* OFFSET: 0x3c */
    MACSEC_MSPU_MAC_LUSO_TYPE line_sfd_offset; /* OFFSET: 0x40 */
    MACSEC_MSPU_MAC_LUMM_TYPE line_mac_mode; /* OFFSET: 0x44 */
    MACSEC_MSPU_MAC_LUT0_TYPE line_tag_0; /* OFFSET: 0x48 */
    MACSEC_MSPU_MAC_LUT1_TYPE line_tag_1; /* OFFSET: 0x4c */
    MACSEC_MSPU_MAC_LURPQS_TYPE line_rx_pause_quanta_scale; /* OFFSET: 0x50 */
    MACSEC_MSPU_MAC_LUTP_TYPE line_tx_preamble; /* OFFSET: 0x54 */
    MACSEC_MSPU_MAC_RESERVED_TYPE rsvd2[4]; /* OFFSET: 0x58 */
    MACSEC_MSPU_MAC_LUTIL_TYPE line_tx_ipg_length; /* OFFSET: 0x5c */
    MACSEC_MSPU_MAC_LUPXT_TYPE line_pfc_xoff_timer; /* OFFSET: 0x60 */
    MACSEC_MSPU_MAC_LUUEC_TYPE line_umac_eee_ctrl; /* OFFSET: 0x64 */
    MACSEC_MSPU_MAC_LUMEDET_TYPE line_mii_eee_delay_entry_timer; /* OFFSET: 0x68 */
    MACSEC_MSPU_MAC_LUGEDET_TYPE line_gmii_eee_delay_entry_timer; /* OFFSET: 0x6c */
    MACSEC_MSPU_MAC_LUUERC_TYPE line_umac_eee_ref_count; /* OFFSET: 0x70 */
    MACSEC_MSPU_MAC_LUUTA_TYPE line_umac_timestamp_adjust; /* OFFSET: 0x74 */
    MACSEC_MSPU_MAC_LUURPDS_TYPE line_umac_rx_pkt_drop_status; /* OFFSET: 0x78 */
    MACSEC_MSPU_MAC_LUUSIT_TYPE line_umac_symmetric_idle_threshold; /* OFFSET: 0x7c */
    MACSEC_MSPU_MAC_LUMEWT_TYPE line_mii_eee_wake_timer; /* OFFSET: 0x80 */
    MACSEC_MSPU_MAC_LUGEWT_TYPE line_gmii_eee_wake_timer; /* OFFSET: 0x84 */
    MACSEC_MSPU_MAC_LUURI_TYPE line_umac_rev_id; /* OFFSET: 0x88 */
    MACSEC_MSPU_MAC_RESERVED_TYPE rsvd3[628]; /* OFFSET: 0x8c */
    MACSEC_MSPU_MAC_LUMP_TYPE line_mac_pfc_type; /* OFFSET: 0x300 */
    MACSEC_MSPU_MAC_LUMPO_TYPE line_mac_pfc_opcode; /* OFFSET: 0x304 */
    MACSEC_MSPU_MAC_LUMPD0_TYPE line_mac_pfc_da_0; /* OFFSET: 0x308 */
    MACSEC_MSPU_MAC_LUMPD1_TYPE line_mac_pfc_da_1; /* OFFSET: 0x30c */
    MACSEC_MSPU_MAC_LUMPTC_TYPE line_macsec_prog_tx_crc; /* OFFSET: 0x310 */
    MACSEC_MSPU_MAC_LUMC_TYPE line_macsec_cntrl; /* OFFSET: 0x314 */
    MACSEC_MSPU_MAC_LUTSC_TYPE line_ts_status_cntrl; /* OFFSET: 0x318 */
    MACSEC_MSPU_MAC_LUTTD_TYPE line_tx_ts_data; /* OFFSET: 0x31c */
    MACSEC_MSPU_MAC_RESERVED_TYPE rsvd4[16]; /* OFFSET: 0x320 */
    MACSEC_MSPU_MAC_LUPC_TYPE line_pause_control; /* OFFSET: 0x330 */
    MACSEC_MSPU_MAC_LUFC_TYPE line_flush_control; /* OFFSET: 0x334 */
    MACSEC_MSPU_MAC_LURS_TYPE line_rxfifo_stat; /* OFFSET: 0x338 */
    MACSEC_MSPU_MAC_LUTS_TYPE line_txfifo_stat; /* OFFSET: 0x33c */
    MACSEC_MSPU_MAC_LUMPC_TYPE line_mac_pfc_ctrl; /* OFFSET: 0x340 */
    MACSEC_MSPU_MAC_LUMPRC_TYPE line_mac_pfc_refresh_ctrl; /* OFFSET: 0x344 */
    MACSEC_MSPU_MAC_RESERVED_TYPE rsvd5[188]; /* OFFSET: 0x348 */
    MACSEC_MSPU_MAC_SUIHBC_TYPE switch_ipg_hd_bkp_cntl; /* OFFSET: 0x404 */
    MACSEC_MSPU_MAC_SUCC_TYPE switch_command_config; /* OFFSET: 0x408 */
    MACSEC_MSPU_MAC_SWITCH_UNIMAC_MAC_0_TYPE switch_mac_0; /* OFFSET: 0x40c */
    MACSEC_MSPU_MAC_SWITCH_UNIMAC_MAC_1_TYPE switch_mac_1; /* OFFSET: 0x410 */
    MACSEC_MSPU_MAC_SUFL_TYPE switch_frm_length; /* OFFSET: 0x414 */
    MACSEC_MSPU_MAC_SUPQ_TYPE switch_pause_quant; /* OFFSET: 0x418 */
    MACSEC_MSPU_MAC_RESERVED_TYPE rsvd6[32]; /* OFFSET: 0x41c */
    MACSEC_MSPU_MAC_SUTTSI_TYPE switch_tx_ts_seq_id; /* OFFSET: 0x43c */
    MACSEC_MSPU_MAC_SUSO_TYPE switch_sfd_offset; /* OFFSET: 0x440 */
    MACSEC_MSPU_MAC_SUMM_TYPE switch_mac_mode; /* OFFSET: 0x444 */
    MACSEC_MSPU_MAC_SUT0_TYPE switch_tag_0; /* OFFSET: 0x448 */
    MACSEC_MSPU_MAC_SUT1_TYPE switch_tag_1; /* OFFSET: 0x44c */
    MACSEC_MSPU_MAC_SURPQS_TYPE switch_rx_pause_quanta_scale; /* OFFSET: 0x450 */
    MACSEC_MSPU_MAC_SUTP_TYPE switch_tx_preamble; /* OFFSET: 0x454 */
    MACSEC_MSPU_MAC_RESERVED_TYPE rsvd7[4]; /* OFFSET: 0x458 */
    MACSEC_MSPU_MAC_SUTIL_TYPE switch_tx_ipg_length; /* OFFSET: 0x45c */
    MACSEC_MSPU_MAC_SUPXT_TYPE switch_pfc_xoff_timer; /* OFFSET: 0x460 */
    MACSEC_MSPU_MAC_SUUEC_TYPE switch_umac_eee_ctrl; /* OFFSET: 0x464 */
    MACSEC_MSPU_MAC_SUMEDET_TYPE switch_mii_eee_delay_entry_timer; /* OFFSET: 0x468 */
    MACSEC_MSPU_MAC_SUGEDET_TYPE switch_gmii_eee_delay_entry_timer; /* OFFSET: 0x46c */
    MACSEC_MSPU_MAC_SUUERC_TYPE switch_umac_eee_ref_count; /* OFFSET: 0x470 */
    MACSEC_MSPU_MAC_SUUTA_TYPE switch_umac_timestamp_adjust; /* OFFSET: 0x474 */
    MACSEC_MSPU_MAC_SUURPDS_TYPE switch_umac_rx_pkt_drop_status; /* OFFSET: 0x478 */
    MACSEC_MSPU_MAC_SUUSIT_TYPE switch_umac_symmetric_idle_threshold; /* OFFSET: 0x47c */
    MACSEC_MSPU_MAC_SUMEWT_TYPE switch_mii_eee_wake_timer; /* OFFSET: 0x480 */
    MACSEC_MSPU_MAC_SUGEWT_TYPE switch_gmii_eee_wake_timer; /* OFFSET: 0x484 */
    MACSEC_MSPU_MAC_SUURI_TYPE switch_umac_rev_id; /* OFFSET: 0x488 */
    MACSEC_MSPU_MAC_RESERVED_TYPE rsvd8[628]; /* OFFSET: 0x48c */
    MACSEC_MSPU_MAC_SUMP_TYPE switch_mac_pfc_type; /* OFFSET: 0x700 */
    MACSEC_MSPU_MAC_SUMPO_TYPE switch_mac_pfc_opcode; /* OFFSET: 0x704 */
    MACSEC_MSPU_MAC_SUMPD0_TYPE switch_mac_pfc_da_0; /* OFFSET: 0x708 */
    MACSEC_MSPU_MAC_SUMPD1_TYPE switch_mac_pfc_da_1; /* OFFSET: 0x70c */
    MACSEC_MSPU_MAC_SUMPTC_TYPE switch_macsec_prog_tx_crc; /* OFFSET: 0x710 */
    MACSEC_MSPU_MAC_SUMC_TYPE switch_macsec_cntrl; /* OFFSET: 0x714 */
    MACSEC_MSPU_MAC_SUTSC_TYPE switch_ts_status_cntrl; /* OFFSET: 0x718 */
    MACSEC_MSPU_MAC_SUTTD_TYPE switch_tx_ts_data; /* OFFSET: 0x71c */
    MACSEC_MSPU_MAC_RESERVED_TYPE rsvd9[16]; /* OFFSET: 0x720 */
    MACSEC_MSPU_MAC_SUPC_TYPE switch_pause_control; /* OFFSET: 0x730 */
    MACSEC_MSPU_MAC_SUFC_TYPE switch_flush_control; /* OFFSET: 0x734 */
    MACSEC_MSPU_MAC_SURS_TYPE switch_rxfifo_stat; /* OFFSET: 0x738 */
    MACSEC_MSPU_MAC_SUTS_TYPE switch_txfifo_stat; /* OFFSET: 0x73c */
    MACSEC_MSPU_MAC_SUMPC_TYPE switch_mac_pfc_ctrl; /* OFFSET: 0x740 */
    MACSEC_MSPU_MAC_SUMPRC_TYPE switch_mac_pfc_refresh_ctrl; /* OFFSET: 0x744 */
} MACSEC_MSPU_MAC_RDBType;


#define MSPU_MAC0_BASE                  (0x4D007800UL)

#define MSPU_MAC1_BASE                  (0x4D107800UL)

#define MSPU_MAC2_BASE                  (0x4D207800UL)

#define MSPU_MAC3_BASE                  (0x4D307800UL)

#define MSPU_MAC4_BASE                  (0x4D407800UL)

#define MSPU_MAC5_BASE                  (0x4D507800UL)



#define MACSEC_MSPU_MAC_MAX_HW_ID       (6UL)

#endif /* MACSEC_MSPU_MAC_RDB_H */
