/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_e_cls_ctrl_rdb.h
    @brief RDB File for MACSEC_E_CLS_CTRL

    @version Orion_A0_20201104_SWDEV
*/

#ifndef MACSEC_E_CLS_CTRL_RDB_H
#define MACSEC_E_CLS_CTRL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_E_CLS_CTRL_RESERVED_TYPE;




typedef uint32_t MACSEC_E_CLS_CTRL_SAM_CP_TAG_TYPE;
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_MAP_TBL_MASK (0xffffffUL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_MAP_TBL_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_DEF_UP_MASK (0x7000000UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_DEF_UP_SHIFT (24UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_STAG_UP_EN_MASK (0x8000000UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_STAG_UP_EN_SHIFT (27UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_QTAG_UP_EN_MASK (0x10000000UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_QTAG_UP_EN_SHIFT (28UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_PARSE_QINQ_MASK (0x20000000UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_PARSE_QINQ_SHIFT (29UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_PARSE_STAG_MASK (0x40000000UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_PARSE_STAG_SHIFT (30UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_PARSE_QTAG_MASK (0x80000000UL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG_PARSE_QTAG_SHIFT (31UL)




typedef uint32_t MACSEC_E_CLS_CTRL_SAM_PP_TAGS_TYPE;
#define MACSEC_E_CLS_CTRL_SAM_PP_TAGS_QTAG_VALUE_MASK (0xffffUL)
#define MACSEC_E_CLS_CTRL_SAM_PP_TAGS_QTAG_VALUE_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_SAM_PP_TAGS_STAG_VALUE_MASK (0xffff0000UL)
#define MACSEC_E_CLS_CTRL_SAM_PP_TAGS_STAG_VALUE_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_CTRL_SAM_PP_TAGS2_TYPE;
#define MACSEC_E_CLS_CTRL_SAM_PP_TAGS2_STAG_VALUE2_MASK (0xffffUL)
#define MACSEC_E_CLS_CTRL_SAM_PP_TAGS2_STAG_VALUE2_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_SAM_PP_TAGS2_STAG_VALUE3_MASK (0xffff0000UL)
#define MACSEC_E_CLS_CTRL_SAM_PP_TAGS2_STAG_VALUE3_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_CTRL_SAM_CP_TAG2_TYPE;
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG2_MAP_TBL2_MASK (0xffffffUL)
#define MACSEC_E_CLS_CTRL_SAM_CP_TAG2_MAP_TBL2_SHIFT (0UL)




typedef uint32_t MACSEC_E_CLS_CTRL_PBB_ETYPE_TYPE;
#define MACSEC_E_CLS_CTRL_PBB_ETYPE_BTAG_ETYPE_MASK (0xffffUL)
#define MACSEC_E_CLS_CTRL_PBB_ETYPE_BTAG_ETYPE_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_PBB_ETYPE_ITAG_ETYPE_MASK (0xffff0000UL)
#define MACSEC_E_CLS_CTRL_PBB_ETYPE_ITAG_ETYPE_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_CTRL_PBB_ENB_SELECT_TYPE;
#define MACSEC_E_CLS_CTRL_PBB_ENB_SELECT_PARSE_PBB_MASK (0x1000000UL)
#define MACSEC_E_CLS_CTRL_PBB_ENB_SELECT_PARSE_PBB_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_CTRL_ST_VLAN_ETYPE_TYPE;
#define MACSEC_E_CLS_CTRL_ST_VLAN_ETYPE_SPECIAL_TPID_MASK (0xffffUL)
#define MACSEC_E_CLS_CTRL_ST_VLAN_ETYPE_SPECIAL_TPID_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_ST_VLAN_ETYPE_PARSE_ST_VLAN_MASK (0x80000000UL)
#define MACSEC_E_CLS_CTRL_ST_VLAN_ETYPE_PARSE_ST_VLAN_SHIFT (31UL)




typedef uint32_t MACSEC_E_CLS_CTRL_EGRESS_HDR_ETYPE_TYPE;
#define MACSEC_E_CLS_CTRL_EGRESS_HDR_ETYPE_EGRESS_HDR_ETYPE_MASK (0xffffUL)
#define MACSEC_E_CLS_CTRL_EGRESS_HDR_ETYPE_EGRESS_HDR_ETYPE_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_EGRESS_HDR_ETYPE_ENABLE_MASK (0x80000000UL)
#define MACSEC_E_CLS_CTRL_EGRESS_HDR_ETYPE_ENABLE_SHIFT (31UL)




typedef uint32_t MACSEC_E_CLS_CTRL_MPLS_ETYPE1_TYPE;
#define MACSEC_E_CLS_CTRL_MPLS_ETYPE1_ETYPE1_MASK (0xffffUL)
#define MACSEC_E_CLS_CTRL_MPLS_ETYPE1_ETYPE1_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_MPLS_ETYPE1_ETYPE2_MASK (0xffff0000UL)
#define MACSEC_E_CLS_CTRL_MPLS_ETYPE1_ETYPE2_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_CTRL_MPLS_ETYPE2_TYPE;
#define MACSEC_E_CLS_CTRL_MPLS_ETYPE2_ETYPE3_MASK (0xffffUL)
#define MACSEC_E_CLS_CTRL_MPLS_ETYPE2_ETYPE3_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_MPLS_ETYPE2_ETYPE4_MASK (0xffff0000UL)
#define MACSEC_E_CLS_CTRL_MPLS_ETYPE2_ETYPE4_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_TYPE;
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS3_SELECT1_MASK (0x3UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS3_SELECT1_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS3_SELECT2_MASK (0xcUL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS3_SELECT2_SHIFT (2UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS4_SELECT1_MASK (0x30UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS4_SELECT1_SHIFT (4UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS4_SELECT2_MASK (0xc0UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS4_SELECT2_SHIFT (6UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS5_SELECT1_MASK (0x700UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS5_SELECT1_SHIFT (8UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS5_SELECT2_MASK (0x3800UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_MPLS5_SELECT2_SHIFT (11UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_BMPLS_PARSE_GT5LBL_MASK (0x8000UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_BMPLS_PARSE_GT5LBL_SHIFT (15UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_PARSE_MPLS1_MASK (0x1000000UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_PARSE_MPLS1_SHIFT (24UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_PARSE_MPLS2_MASK (0x2000000UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_PARSE_MPLS2_SHIFT (25UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_PARSE_MPLS3_MASK (0x4000000UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_PARSE_MPLS3_SHIFT (26UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_PARSE_MPLS4_MASK (0x8000000UL)
#define MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_PARSE_MPLS4_SHIFT (27UL)




typedef uint32_t MACSEC_E_CLS_CTRL_CP_EMAX_LEN_TYPE;
#define MACSEC_E_CLS_CTRL_CP_EMAX_LEN_ETYPE_MAX_LEN_MASK (0xffffUL)
#define MACSEC_E_CLS_CTRL_CP_EMAX_LEN_ETYPE_MAX_LEN_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_CP_EMAX_LEN_ENABLE_MASK (0x80000000UL)
#define MACSEC_E_CLS_CTRL_CP_EMAX_LEN_ENABLE_SHIFT (31UL)




typedef uint32_t MACSEC_E_CLS_CTRL_CP_EJUMBO_TYPE;
#define MACSEC_E_CLS_CTRL_CP_EJUMBO_ETYPE_JUMBO_MASK (0xffffUL)
#define MACSEC_E_CLS_CTRL_CP_EJUMBO_ETYPE_JUMBO_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_CP_EJUMBO_ENABLE_MASK (0x80000000UL)
#define MACSEC_E_CLS_CTRL_CP_EJUMBO_ENABLE_SHIFT (31UL)




typedef uint32_t MACSEC_E_CLS_CTRL_LLC_SNAP_VALUE_TYPE;
#define MACSEC_E_CLS_CTRL_LLC_SNAP_VALUE_VALUE_MASK (0xffffffUL)
#define MACSEC_E_CLS_CTRL_LLC_SNAP_VALUE_VALUE_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_LLC_SNAP_VALUE_FORCE_ETH_MASK (0x20000000UL)
#define MACSEC_E_CLS_CTRL_LLC_SNAP_VALUE_FORCE_ETH_SHIFT (29UL)
#define MACSEC_E_CLS_CTRL_LLC_SNAP_VALUE_PARSE_ETH_MASK (0x40000000UL)
#define MACSEC_E_CLS_CTRL_LLC_SNAP_VALUE_PARSE_ETH_SHIFT (30UL)
#define MACSEC_E_CLS_CTRL_LLC_SNAP_VALUE_PARSE_SNAP_MASK (0x80000000UL)
#define MACSEC_E_CLS_CTRL_LLC_SNAP_VALUE_PARSE_SNAP_SHIFT (31UL)




typedef uint32_t MACSEC_E_CLS_CTRL_LLC_SNAP_MASK_TYPE;
#define MACSEC_E_CLS_CTRL_LLC_SNAP_MASK_MASK_MASK (0xffffffUL)
#define MACSEC_E_CLS_CTRL_LLC_SNAP_MASK_MASK_SHIFT (0UL)




typedef uint32_t MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_TYPE;
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_COMP_ETYPE_MASK (0x1UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_COMP_ETYPE_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_V_MASK (0x2UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_V_SHIFT (1UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_KAY_MASK (0x4UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_KAY_SHIFT (2UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_C_E_MASK (0x8UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_C_E_SHIFT (3UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_SC_MASK (0x10UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_SC_SHIFT (4UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_SL_MASK (0x20UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_SL_SHIFT (5UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_PN_MASK (0x40UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_PN_SHIFT (6UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_SL_EXT_MASK (0x80UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_CHECK_SL_EXT_SHIFT (7UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_MSEC_TAG_VALUE_MASK (0xffff0000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_MSEC_TAG_VALUE_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_TYPE;
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_FLOW_TYPE0_MASK (0x1UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_FLOW_TYPE0_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DEST_PORT0_MASK (0xcUL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DEST_PORT0_SHIFT (2UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_NON_REDIR0_MASK (0x10UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_NON_REDIR0_SHIFT (4UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_ACTION0_MASK (0xc0UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_ACTION0_SHIFT (6UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_FLOW_TYPE1_MASK (0x100UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_FLOW_TYPE1_SHIFT (8UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DEST_PORT1_MASK (0xc00UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DEST_PORT1_SHIFT (10UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_NON_REDIR1_MASK (0x1000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_NON_REDIR1_SHIFT (12UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_ACTION1_MASK (0xc000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_ACTION1_SHIFT (14UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_FLOW_TYPE2_MASK (0x10000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_FLOW_TYPE2_SHIFT (16UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DEST_PORT2_MASK (0xc0000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DEST_PORT2_SHIFT (18UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_NON_REDIR2_MASK (0x100000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_NON_REDIR2_SHIFT (20UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_ACTION2_MASK (0xc00000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_ACTION2_SHIFT (22UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_FLOW_TYPE3_MASK (0x1000000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_FLOW_TYPE3_SHIFT (24UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DEST_PORT3_MASK (0xc000000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DEST_PORT3_SHIFT (26UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_NON_REDIR3_MASK (0x10000000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_NON_REDIR3_SHIFT (28UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_ACTION3_MASK (0xc0000000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_DROP_ACTION3_SHIFT (30UL)




typedef uint32_t MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_TYPE;
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_FLOW_TYPE0_MASK (0x1UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_FLOW_TYPE0_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DEST_PORT0_MASK (0xcUL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DEST_PORT0_SHIFT (2UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_NON_REDIR0_MASK (0x10UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_NON_REDIR0_SHIFT (4UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_ACTION0_MASK (0xc0UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_ACTION0_SHIFT (6UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_FLOW_TYPE1_MASK (0x100UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_FLOW_TYPE1_SHIFT (8UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DEST_PORT1_MASK (0xc00UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DEST_PORT1_SHIFT (10UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_NON_REDIR1_MASK (0x1000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_NON_REDIR1_SHIFT (12UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_ACTION1_MASK (0xc000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_ACTION1_SHIFT (14UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_FLOW_TYPE2_MASK (0x10000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_FLOW_TYPE2_SHIFT (16UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DEST_PORT2_MASK (0xc0000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DEST_PORT2_SHIFT (18UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_NON_REDIR2_MASK (0x100000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_NON_REDIR2_SHIFT (20UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_ACTION2_MASK (0xc00000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_ACTION2_SHIFT (22UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_FLOW_TYPE3_MASK (0x1000000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_FLOW_TYPE3_SHIFT (24UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DEST_PORT3_MASK (0xc000000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DEST_PORT3_SHIFT (26UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_NON_REDIR3_MASK (0x10000000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_NON_REDIR3_SHIFT (28UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_ACTION3_MASK (0xc0000000UL)
#define MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_DROP_ACTION3_SHIFT (30UL)




typedef uint32_t MACSEC_E_CLS_CTRL_SNFCR_TYPE;
#define MACSEC_E_CLS_CTRL_SNFCR_NCP_UT_CAPT_REASON_MASK (0xfUL)
#define MACSEC_E_CLS_CTRL_SNFCR_NCP_UT_CAPT_REASON_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_SNFCR_NCP_VT_CAPT_REASON_MASK (0xf0UL)
#define MACSEC_E_CLS_CTRL_SNFCR_NCP_VT_CAPT_REASON_SHIFT (4UL)
#define MACSEC_E_CLS_CTRL_SNFCR_NCP_BT_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_CLS_CTRL_SNFCR_NCP_BT_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_CLS_CTRL_SNFCR_NCP_KAY_CAPT_REASON_MASK (0xf000UL)
#define MACSEC_E_CLS_CTRL_SNFCR_NCP_KAY_CAPT_REASON_SHIFT (12UL)
#define MACSEC_E_CLS_CTRL_SNFCR_CP_UT_CAPT_REASON_MASK (0xf0000UL)
#define MACSEC_E_CLS_CTRL_SNFCR_CP_UT_CAPT_REASON_SHIFT (16UL)
#define MACSEC_E_CLS_CTRL_SNFCR_CP_VT_CAPT_REASON_MASK (0xf00000UL)
#define MACSEC_E_CLS_CTRL_SNFCR_CP_VT_CAPT_REASON_SHIFT (20UL)
#define MACSEC_E_CLS_CTRL_SNFCR_CP_BT_CAPT_REASON_MASK (0xf000000UL)
#define MACSEC_E_CLS_CTRL_SNFCR_CP_BT_CAPT_REASON_SHIFT (24UL)
#define MACSEC_E_CLS_CTRL_SNFCR_CP_KAY_CAPT_REASON_MASK (0xf0000000UL)
#define MACSEC_E_CLS_CTRL_SNFCR_CP_KAY_CAPT_REASON_SHIFT (28UL)




typedef uint32_t MACSEC_E_CLS_CTRL_DLC_TYPE;
#define MACSEC_E_CLS_CTRL_DLC_MC_DYN_LATENCY_WORDS_MASK (0x1fUL)
#define MACSEC_E_CLS_CTRL_DLC_MC_DYN_LATENCY_WORDS_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_DLC_DYN_LAT_ENABLE_MASK (0x80000000UL)
#define MACSEC_E_CLS_CTRL_DLC_DYN_LAT_ENABLE_SHIFT (31UL)




typedef uint32_t MACSEC_E_CLS_CTRL_MISC_CONTROL_TYPE;
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_MC_LATENCY_FIX_MASK (0xffUL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_MC_LATENCY_FIX_SHIFT (0UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_STATIC_BYPASS_MASK (0x100UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_STATIC_BYPASS_SHIFT (8UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_NM_MACSEC_EN_MASK (0x200UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_NM_MACSEC_EN_SHIFT (9UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_VALIDATE_FRAMES_MASK (0xc00UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_VALIDATE_FRAMES_SHIFT (10UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_BYPASS_NOCLASS_MASK (0x1000UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_BYPASS_NOCLASS_SHIFT (12UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_DROP_ON_PKTERR_MASK (0x4000UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_DROP_ON_PKTERR_SHIFT (14UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_DROP_ON_CRCERR_MASK (0x8000UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_DROP_ON_CRCERR_SHIFT (15UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_ERR_DROP_ACTION_MASK (0x30000UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_ERR_DROP_ACTION_SHIFT (16UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_ERR_DEST_PORT_MASK (0xc0000UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_ERR_DEST_PORT_SHIFT (18UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_ERR_CAPT_REASON_MASK (0x300000UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_ERR_CAPT_REASON_SHIFT (20UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_XFORM_REC_SIZE_MASK (0x3000000UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_XFORM_REC_SIZE_SHIFT (24UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_MC_LATENCY_FIX_HI_MASK (0xfc000000UL)
#define MACSEC_E_CLS_CTRL_MISC_CONTROL_MC_LATENCY_FIX_HI_SHIFT (26UL)




typedef uint32_t MACSEC_E_CLS_CTRL_CRYPT_AUTH_CTRL_TYPE;
#define MACSEC_E_CLS_CTRL_CRYPT_AUTH_CTRL_BYPASS_LEN_MASK (0xffUL)
#define MACSEC_E_CLS_CTRL_CRYPT_AUTH_CTRL_BYPASS_LEN_SHIFT (0UL)




typedef uint32_t MACSEC_E_CLS_CTRL_SA_EXP_SUMMARY1_TYPE;
#define MACSEC_E_CLS_CTRL_SA_EXP_SUMMARY1_31_0_MASK (0xffffffffUL)
#define MACSEC_E_CLS_CTRL_SA_EXP_SUMMARY1_31_0_SHIFT (0UL)




typedef volatile struct COMP_PACKED sMACSEC_E_CLS_CTRL_RDBType {
    MACSEC_E_CLS_CTRL_RESERVED_TYPE rsvd0[96512]; /* OFFSET: 0x0 */
    MACSEC_E_CLS_CTRL_SAM_CP_TAG_TYPE sam_cp_tag; /* OFFSET: 0x17900 */
    MACSEC_E_CLS_CTRL_SAM_PP_TAGS_TYPE sam_pp_tags; /* OFFSET: 0x17904 */
    MACSEC_E_CLS_CTRL_SAM_PP_TAGS2_TYPE sam_pp_tags2; /* OFFSET: 0x17908 */
    MACSEC_E_CLS_CTRL_SAM_CP_TAG2_TYPE sam_cp_tag2; /* OFFSET: 0x1790c */
    MACSEC_E_CLS_CTRL_PBB_ETYPE_TYPE pbb_etype; /* OFFSET: 0x17910 */
    MACSEC_E_CLS_CTRL_PBB_ENB_SELECT_TYPE pbb_enb_select; /* OFFSET: 0x17914 */
    MACSEC_E_CLS_CTRL_ST_VLAN_ETYPE_TYPE st_vlan_etype; /* OFFSET: 0x17918 */
    MACSEC_E_CLS_CTRL_EGRESS_HDR_ETYPE_TYPE egress_hdr_etype; /* OFFSET: 0x1791c */
    MACSEC_E_CLS_CTRL_MPLS_ETYPE1_TYPE mpls_etype1; /* OFFSET: 0x17920 */
    MACSEC_E_CLS_CTRL_MPLS_ETYPE2_TYPE mpls_etype2; /* OFFSET: 0x17924 */
    MACSEC_E_CLS_CTRL_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x17928 */
    MACSEC_E_CLS_CTRL_MPLS_ENB_SELECT_TYPE mpls_enb_select; /* OFFSET: 0x1792c */
    MACSEC_E_CLS_CTRL_CP_EMAX_LEN_TYPE cp_etype_max_len; /* OFFSET: 0x17930 */
    MACSEC_E_CLS_CTRL_CP_EJUMBO_TYPE cp_etype_jumbo; /* OFFSET: 0x17934 */
    MACSEC_E_CLS_CTRL_LLC_SNAP_VALUE_TYPE llc_snap_value; /* OFFSET: 0x17938 */
    MACSEC_E_CLS_CTRL_LLC_SNAP_MASK_TYPE llc_snap_mask; /* OFFSET: 0x1793c */
    MACSEC_E_CLS_CTRL_SAM_NM_PARAMS_TYPE sam_nm_params; /* OFFSET: 0x17940 */
    MACSEC_E_CLS_CTRL_SAM_NM_FLOW_NCP_TYPE sam_nm_flow_ncp; /* OFFSET: 0x17944 */
    MACSEC_E_CLS_CTRL_SAM_NM_FLOW_CP_TYPE sam_nm_flow_cp; /* OFFSET: 0x17948 */
    MACSEC_E_CLS_CTRL_SNFCR_TYPE sam_nm_flow_capt_reason; /* OFFSET: 0x1794c */
    MACSEC_E_CLS_CTRL_RESERVED_TYPE rsvd2[40]; /* OFFSET: 0x17950 */
    MACSEC_E_CLS_CTRL_DLC_TYPE dyn_latency_control; /* OFFSET: 0x17978 */
    MACSEC_E_CLS_CTRL_MISC_CONTROL_TYPE misc_control; /* OFFSET: 0x1797c */
    MACSEC_E_CLS_CTRL_RESERVED_TYPE rsvd3[4]; /* OFFSET: 0x17980 */
    MACSEC_E_CLS_CTRL_CRYPT_AUTH_CTRL_TYPE crypt_auth_ctrl; /* OFFSET: 0x17984 */
    MACSEC_E_CLS_CTRL_RESERVED_TYPE rsvd4[120]; /* OFFSET: 0x17988 */
    MACSEC_E_CLS_CTRL_SA_EXP_SUMMARY1_TYPE sa_exp_summary1; /* OFFSET: 0x17a00 */
} MACSEC_E_CLS_CTRL_RDBType;


#define EIP_160S_E_32_BRCM_CLASSIFIER_VARIOUS_CONTROL_REGS0_BASE  (0x4D010000UL)

#define EIP_160S_E_32_BRCM_CLASSIFIER_VARIOUS_CONTROL_REGS1_BASE  (0x4D110000UL)

#define EIP_160S_E_32_BRCM_CLASSIFIER_VARIOUS_CONTROL_REGS2_BASE  (0x4D210000UL)

#define EIP_160S_E_32_BRCM_CLASSIFIER_VARIOUS_CONTROL_REGS3_BASE  (0x4D310000UL)

#define EIP_160S_E_32_BRCM_CLASSIFIER_VARIOUS_CONTROL_REGS4_BASE  (0x4D410000UL)

#define EIP_160S_E_32_BRCM_CLASSIFIER_VARIOUS_CONTROL_REGS5_BASE  (0x4D510000UL)



#define MACSEC_E_CLS_CTRL_MAX_HW_ID     (6UL)

#endif /* MACSEC_E_CLS_CTRL_RDB_H */
