/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_e_cls_p_ctrl_rdb.h
    @brief RDB File for MACSEC_E_CLS_P_CTRL

    @version Orion_A0_20201104_SWDEV
*/

#ifndef MACSEC_E_CLS_P_CTRL_RDB_H
#define MACSEC_E_CLS_P_CTRL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_E_CLS_P_CTRL_RESERVED_TYPE;




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_0_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_0_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_0_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_0_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_0_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_0_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_0_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_0_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_0_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMDEM0_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMDEM0_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMDEM0_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM0_MAC_DA_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM0_MAC_DA_MATCH_7_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM0_ETHER_TYPE_MATCH_MASK (0xffff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM0_ETHER_TYPE_MATCH_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_1_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_1_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_1_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_1_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_1_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_1_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_1_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_1_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_1_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMDEM1_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMDEM1_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMDEM1_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM1_MAC_DA_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM1_MAC_DA_MATCH_7_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM1_ETHER_TYPE_MATCH_MASK (0xffff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM1_ETHER_TYPE_MATCH_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_2_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_2_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_2_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_2_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_2_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_2_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_2_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_2_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_2_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMDEM2_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMDEM2_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMDEM2_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM2_MAC_DA_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM2_MAC_DA_MATCH_7_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM2_ETHER_TYPE_MATCH_MASK (0xffff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM2_ETHER_TYPE_MATCH_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_3_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_3_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_3_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_3_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_3_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_3_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_3_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_3_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_3_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMDEM3_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMDEM3_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMDEM3_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM3_MAC_DA_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM3_MAC_DA_MATCH_7_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM3_ETHER_TYPE_MATCH_MASK (0xffff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM3_ETHER_TYPE_MATCH_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_4_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_4_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_4_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_4_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_4_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_4_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_4_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_4_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_4_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMDEM4_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMDEM4_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMDEM4_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM4_MAC_DA_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM4_MAC_DA_MATCH_7_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM4_ETHER_TYPE_MATCH_MASK (0xffff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM4_ETHER_TYPE_MATCH_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_5_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_5_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_5_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_5_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_5_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_5_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_5_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_5_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_5_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMDEM5_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMDEM5_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMDEM5_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM5_MAC_DA_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM5_MAC_DA_MATCH_7_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM5_ETHER_TYPE_MATCH_MASK (0xffff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM5_ETHER_TYPE_MATCH_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_6_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_6_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_6_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_6_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_6_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_6_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_6_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_6_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_6_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMDEM6_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMDEM6_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMDEM6_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM6_MAC_DA_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM6_MAC_DA_MATCH_7_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM6_ETHER_TYPE_MATCH_MASK (0xffff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM6_ETHER_TYPE_MATCH_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_7_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_7_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_7_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_7_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_7_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_7_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_7_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_7_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_7_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMDEM7_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMDEM7_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMDEM7_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM7_MAC_DA_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM7_MAC_DA_MATCH_7_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM7_ETHER_TYPE_MATCH_MASK (0xffff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMDEM7_ETHER_TYPE_MATCH_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMDS0L_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMDS0L_MAC_DA_MATCH_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMDS0L_MAC_DA_MATCH_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMDS0L_MAC_DA_MATCH_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMDS0L_MAC_DA_MATCH_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMDS0L_MAC_DA_MATCH_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMDS0L_MAC_DA_MATCH_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CMDS0L_MAC_DA_MATCH_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CMDS0L_MAC_DA_MATCH_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START0_HI_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START0_HI_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START0_HI_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START0_HI_MAC_DA_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START0_HI_MAC_DA_MATCH_7_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START0_HI_ETHER_TYPE_MATCH_MASK (0xffff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START0_HI_ETHER_TYPE_MATCH_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_LO_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_LO_MATCH_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_LO_MATCH_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_LO_MATCH_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_LO_MATCH_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_LO_MATCH_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_LO_MATCH_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_LO_MATCH_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_LO_MATCH_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_HI_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_HI_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_HI_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_HI_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_HI_MATCH_7_0_SHIFT (8UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMDS1L_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMDS1L_MAC_DA_MATCH_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMDS1L_MAC_DA_MATCH_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMDS1L_MAC_DA_MATCH_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMDS1L_MAC_DA_MATCH_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMDS1L_MAC_DA_MATCH_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMDS1L_MAC_DA_MATCH_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CMDS1L_MAC_DA_MATCH_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CMDS1L_MAC_DA_MATCH_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START1_HI_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START1_HI_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START1_HI_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START1_HI_MAC_DA_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START1_HI_MAC_DA_MATCH_7_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START1_HI_ETHER_TYPE_MATCH_MASK (0xffff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START1_HI_ETHER_TYPE_MATCH_SHIFT (16UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_LO_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_LO_MATCH_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_LO_MATCH_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_LO_MATCH_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_LO_MATCH_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_LO_MATCH_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_LO_MATCH_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_LO_MATCH_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_LO_MATCH_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_HI_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_HI_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_HI_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_HI_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END1_HI_MATCH_7_0_SHIFT (8UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_LO_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_LO_MATCH_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_LO_MATCH_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_LO_MATCH_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_LO_MATCH_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_LO_MATCH_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_LO_MATCH_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_LO_MATCH_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_LO_MATCH_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_HI_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_HI_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_HI_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_HI_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_HI_MATCH_7_0_SHIFT (8UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_LO_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_LO_MATCH_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_LO_MATCH_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_LO_MATCH_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_LO_MATCH_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_LO_MATCH_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_LO_MATCH_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_LO_MATCH_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_LO_MATCH_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_HI_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_HI_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_HI_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_HI_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_HI_MATCH_7_0_SHIFT (8UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMD44BL_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMD44BL_MAC_DA_MATCH_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMD44BL_MAC_DA_MATCH_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMD44BL_MAC_DA_MATCH_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMD44BL_MAC_DA_MATCH_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMD44BL_MAC_DA_MATCH_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMD44BL_MAC_DA_MATCH_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CMD44BL_MAC_DA_MATCH_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CMD44BL_MAC_DA_MATCH_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMD44BH_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMD44BH_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMD44BH_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMD44BH_MAC_DA_MATCH_7_4_MASK (0xf000UL)
#define MACSEC_E_CLS_P_CTRL_CMD44BH_MAC_DA_MATCH_7_4_SHIFT (12UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMD48BL_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMD48BL_MAC_DA_MATCH_47_40_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMD48BL_MAC_DA_MATCH_47_40_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMD48BL_MAC_DA_MATCH_39_32_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMD48BL_MAC_DA_MATCH_39_32_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CMD48BL_MAC_DA_MATCH_31_24_MASK (0xff0000UL)
#define MACSEC_E_CLS_P_CTRL_CMD48BL_MAC_DA_MATCH_31_24_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CMD48BL_MAC_DA_MATCH_23_16_MASK (0xff000000UL)
#define MACSEC_E_CLS_P_CTRL_CMD48BL_MAC_DA_MATCH_23_16_SHIFT (24UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CMD48BH_TYPE;
#define MACSEC_E_CLS_P_CTRL_CMD48BH_MAC_DA_MATCH_15_8_MASK (0xffUL)
#define MACSEC_E_CLS_P_CTRL_CMD48BH_MAC_DA_MATCH_15_8_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CMD48BH_MAC_DA_MATCH_7_0_MASK (0xff00UL)
#define MACSEC_E_CLS_P_CTRL_CMD48BH_MAC_DA_MATCH_7_0_SHIFT (8UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_TYPE;
#define MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_PARSE_STAG0_MASK (0x1UL)
#define MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_PARSE_STAG0_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_PARSE_STAG1_MASK (0x2UL)
#define MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_PARSE_STAG1_SHIFT (1UL)
#define MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_PARSE_STAG2_MASK (0x4UL)
#define MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_PARSE_STAG2_SHIFT (2UL)
#define MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_PARSE_STAG3_MASK (0x8UL)
#define MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_PARSE_STAG3_SHIFT (3UL)
#define MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_PARSE_QINQ_MASK (0x80000000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_PARSE_QINQ_SHIFT (31UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPE;
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_0_MASK (0x100UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_1_MASK (0x200UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_1_SHIFT (9UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_2_MASK (0x400UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_2_SHIFT (10UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_3_MASK (0x800UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_3_SHIFT (11UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_4_MASK (0x1000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_4_SHIFT (12UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_5_MASK (0x2000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_5_SHIFT (13UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_6_MASK (0x4000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_6_SHIFT (14UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_7_MASK (0x8000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_7_SHIFT (15UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_8_MASK (0x10000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_8_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_9_MASK (0x20000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPSEL_9_SHIFT (17UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_TYPE;
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_0_MASK (0x1UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_0_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_1_MASK (0x2UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_1_SHIFT (1UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_2_MASK (0x4UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_2_SHIFT (2UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_3_MASK (0x8UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_3_SHIFT (3UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_4_MASK (0x10UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_4_SHIFT (4UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_5_MASK (0x20UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_5_SHIFT (5UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_6_MASK (0x40UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_6_SHIFT (6UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_7_MASK (0x80UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MAC_DA_7_SHIFT (7UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_0_MASK (0x100UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_1_MASK (0x200UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_1_SHIFT (9UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_2_MASK (0x400UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_2_SHIFT (10UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_3_MASK (0x800UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_3_SHIFT (11UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_4_MASK (0x1000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_4_SHIFT (12UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_5_MASK (0x2000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_5_SHIFT (13UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_6_MASK (0x4000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_6_SHIFT (14UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_7_MASK (0x8000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_E_TYPE_7_SHIFT (15UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_COMB8_MASK (0x10000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_COMB8_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_COMB9_MASK (0x20000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_COMB9_SHIFT (17UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_RANGE_MASK (0x40000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_RANGE_SHIFT (18UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_CONST_44_MASK (0x80000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_CONST_44_SHIFT (19UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_CONST_48_MASK (0x100000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_CONST_48_SHIFT (20UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MACSEC_KAY_MASK (0x80000000UL)
#define MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_MACSEC_KAY_SHIFT (31UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_PARSE_STAG0_MASK (0x1UL)
#define MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_PARSE_STAG0_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_PARSE_STAG1_MASK (0x2UL)
#define MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_PARSE_STAG1_SHIFT (1UL)
#define MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_PARSE_STAG2_MASK (0x4UL)
#define MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_PARSE_STAG2_SHIFT (2UL)
#define MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_PARSE_STAG3_MASK (0x8UL)
#define MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_PARSE_STAG3_SHIFT (3UL)
#define MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_PARSE_QINQ_MASK (0x80000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_PARSE_QINQ_SHIFT (31UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_0_MASK (0x100UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_1_MASK (0x200UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_1_SHIFT (9UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_2_MASK (0x400UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_2_SHIFT (10UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_3_MASK (0x800UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_3_SHIFT (11UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_4_MASK (0x1000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_4_SHIFT (12UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_5_MASK (0x2000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_5_SHIFT (13UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_6_MASK (0x4000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_6_SHIFT (14UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_7_MASK (0x8000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_7_SHIFT (15UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_8_MASK (0x10000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_8_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_9_MASK (0x20000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPSEL_9_SHIFT (17UL)




typedef uint32_t MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_TYPE;
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_0_MASK (0x1UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_0_SHIFT (0UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_1_MASK (0x2UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_1_SHIFT (1UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_2_MASK (0x4UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_2_SHIFT (2UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_3_MASK (0x8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_3_SHIFT (3UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_4_MASK (0x10UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_4_SHIFT (4UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_5_MASK (0x20UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_5_SHIFT (5UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_6_MASK (0x40UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_6_SHIFT (6UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_7_MASK (0x80UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MAC_DA_7_SHIFT (7UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_0_MASK (0x100UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_0_SHIFT (8UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_1_MASK (0x200UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_1_SHIFT (9UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_2_MASK (0x400UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_2_SHIFT (10UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_3_MASK (0x800UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_3_SHIFT (11UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_4_MASK (0x1000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_4_SHIFT (12UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_5_MASK (0x2000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_5_SHIFT (13UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_6_MASK (0x4000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_6_SHIFT (14UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_7_MASK (0x8000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_E_TYPE_7_SHIFT (15UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_COMB8_MASK (0x10000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_COMB8_SHIFT (16UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_COMB9_MASK (0x20000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_COMB9_SHIFT (17UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_RANGE_MASK (0x40000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_RANGE_SHIFT (18UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_CONST_44_MASK (0x80000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_CONST_44_SHIFT (19UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_CONST_48_MASK (0x100000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_CONST_48_SHIFT (20UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MACSEC_KAY_MASK (0x80000000UL)
#define MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_MACSEC_KAY_SHIFT (31UL)


typedef volatile struct COMP_PACKED sMACSEC_E_CLS_P_CTRL_DAETMATCH_RDBType {
    MACSEC_E_CLS_P_CTRL_CP_MAC_DA_MATCH_0_TYPE cp_mac_da_match_0; /* OFFSET: 0x17800 */
    MACSEC_E_CLS_P_CTRL_CMDEM0_TYPE cp_mac_da_et_match_0; /* OFFSET: 0x17804 */
} MACSEC_E_CLS_P_CTRL_DAETMATCH_RDBType;

typedef volatile struct COMP_PACKED sMACSEC_E_CLS_P_CTRL_DAETRANGE_RDBType {
    MACSEC_E_CLS_P_CTRL_CMDS0L_TYPE cp_mac_da_start0_lo; /* OFFSET: 0x17860 */
    MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START0_HI_TYPE cp_mac_da_start0_hi; /* OFFSET: 0x17864 */
    MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_LO_TYPE cp_mac_da_end0_lo; /* OFFSET: 0x17868 */
    MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END0_HI_TYPE cp_mac_da_end0_hi; /* OFFSET: 0x1786c */
} MACSEC_E_CLS_P_CTRL_DAETRANGE_RDBType;


#define MACSEC_E_CLS_P_CTRL_DAETMATCH_REGS_SIZE  (8UL)

#define MACSEC_E_CLS_P_CTRL_DAETRANGE_REGS_SIZE  (2UL)


typedef volatile struct COMP_PACKED sMACSEC_E_CLS_P_CTRL_RDBType {
    MACSEC_E_CLS_P_CTRL_RESERVED_TYPE rsvd0[96256]; /* OFFSET: 0x0 */
    MACSEC_E_CLS_P_CTRL_DAETMATCH_RDBType daetmatch_regs[MACSEC_E_CLS_P_CTRL_DAETMATCH_REGS_SIZE]; /* OFFSET: 0x17800 */
    MACSEC_E_CLS_P_CTRL_RESERVED_TYPE rsvd1[32]; /* OFFSET: 0x17840 */
    MACSEC_E_CLS_P_CTRL_DAETRANGE_RDBType daetrange_regs[MACSEC_E_CLS_P_CTRL_DAETRANGE_REGS_SIZE]; /* OFFSET: 0x17860 */
    MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_LO_TYPE cp_mac_da_start_lo; /* OFFSET: 0x17880 */
    MACSEC_E_CLS_P_CTRL_CP_MAC_DA_START_HI_TYPE cp_mac_da_start_hi; /* OFFSET: 0x17884 */
    MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_LO_TYPE cp_mac_da_end_lo; /* OFFSET: 0x17888 */
    MACSEC_E_CLS_P_CTRL_CP_MAC_DA_END_HI_TYPE cp_mac_da_end_hi; /* OFFSET: 0x1788c */
    MACSEC_E_CLS_P_CTRL_CMD44BL_TYPE cp_mac_da_44_bits_lo; /* OFFSET: 0x17890 */
    MACSEC_E_CLS_P_CTRL_CMD44BH_TYPE cp_mac_da_44_bits_hi; /* OFFSET: 0x17894 */
    MACSEC_E_CLS_P_CTRL_CMD48BL_TYPE cp_mac_da_48_bits_lo; /* OFFSET: 0x17898 */
    MACSEC_E_CLS_P_CTRL_CMD48BH_TYPE cp_mac_da_48_bits_hi; /* OFFSET: 0x1789c */
    MACSEC_E_CLS_P_CTRL_RESERVED_TYPE rsvd2[64]; /* OFFSET: 0x178a0 */
    MACSEC_E_CLS_P_CTRL_SCP_TAG_ENB_TYPE scp_tag_enb; /* OFFSET: 0x178e0 */
    MACSEC_E_CLS_P_CTRL_RESERVED_TYPE rsvd3[4]; /* OFFSET: 0x178e4 */
    MACSEC_E_CLS_P_CTRL_SCP_MATCH_MODE_TYPE scp_match_mode; /* OFFSET: 0x178e8 */
    MACSEC_E_CLS_P_CTRL_SCP_MATCH_ENABLE_TYPE scp_match_enable; /* OFFSET: 0x178ec */
    MACSEC_E_CLS_P_CTRL_CP_TAG_ENB_TYPE cp_tag_enb; /* OFFSET: 0x178f0 */
    MACSEC_E_CLS_P_CTRL_RESERVED_TYPE rsvd4[4]; /* OFFSET: 0x178f4 */
    MACSEC_E_CLS_P_CTRL_CP_MATCH_MODE_TYPE cp_match_mode; /* OFFSET: 0x178f8 */
    MACSEC_E_CLS_P_CTRL_CP_MATCH_ENABLE_TYPE cp_match_enable; /* OFFSET: 0x178fc */
} MACSEC_E_CLS_P_CTRL_RDBType;


#define EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET0_BASE  (0x4D010000UL)

#define MACSEC_E_CLS_P_CTRL_DAETMATCH_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET0_OFFSET  (0x4d027800UL)

#define MACSEC_E_CLS_P_CTRL_DAETRANGE_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET0_OFFSET  (0x4d027860UL)

#define EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET1_BASE  (0x4D110000UL)

#define MACSEC_E_CLS_P_CTRL_DAETMATCH_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET1_OFFSET  (0x4d127800UL)

#define MACSEC_E_CLS_P_CTRL_DAETRANGE_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET1_OFFSET  (0x4d127860UL)

#define EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET2_BASE  (0x4D210000UL)

#define MACSEC_E_CLS_P_CTRL_DAETMATCH_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET2_OFFSET  (0x4d227800UL)

#define MACSEC_E_CLS_P_CTRL_DAETRANGE_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET2_OFFSET  (0x4d227860UL)

#define EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET3_BASE  (0x4D310000UL)

#define MACSEC_E_CLS_P_CTRL_DAETMATCH_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET3_OFFSET  (0x4d327800UL)

#define MACSEC_E_CLS_P_CTRL_DAETRANGE_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET3_OFFSET  (0x4d327860UL)

#define EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET4_BASE  (0x4D410000UL)

#define MACSEC_E_CLS_P_CTRL_DAETMATCH_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET4_OFFSET  (0x4d427800UL)

#define MACSEC_E_CLS_P_CTRL_DAETRANGE_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET4_OFFSET  (0x4d427860UL)

#define EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET5_BASE  (0x4D510000UL)

#define MACSEC_E_CLS_P_CTRL_DAETMATCH_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET5_OFFSET  (0x4d527800UL)

#define MACSEC_E_CLS_P_CTRL_DAETRANGE_RDBTYPE_EIP_160S_E_32_BRCM_CLASSIFIER_CONTROL_PACKET5_OFFSET  (0x4d527860UL)



#define MACSEC_E_CLS_P_CTRL_MAX_HW_ID   (6UL)

#endif /* MACSEC_E_CLS_P_CTRL_RDB_H */
