/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_i_fctrl_en_rdb.h
    @brief RDB File for MACSEC_I_FCTRL_EN

    @version Orion_A0_20201104_SWDEV
*/

#ifndef MACSEC_I_FCTRL_EN_RDB_H
#define MACSEC_I_FCTRL_EN_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_I_FCTRL_EN_RESERVED_TYPE;




typedef uint32_t MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE1_TYPE;
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE1_ENABLE_31_0_MASK (0xffffffffUL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE1_ENABLE_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_FCTRL_EN_SAM_ENTRY_TOGGLE1_TYPE;
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_TOGGLE1_TOGGLE_31_0_MASK (0xffffffffUL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_TOGGLE1_TOGGLE_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_FCTRL_EN_SAM_ENTRY_SET1_TYPE;
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_SET1_SET_31_0_MASK (0xffffffffUL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_SET1_SET_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_FCTRL_EN_SAM_ENTRY_CLEAR1_TYPE;
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_CLEAR1_CLEAR_31_0_MASK (0xffffffffUL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_CLEAR1_CLEAR_31_0_SHIFT (0UL)




typedef uint32_t MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_TYPE;
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_SAM_INDEX_SET_MASK (0x1fUL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_SAM_INDEX_SET_SHIFT (0UL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_SET_ENABLE_MASK (0x4000UL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_SET_ENABLE_SHIFT (14UL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_SET_ALL_MASK (0x8000UL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_SET_ALL_SHIFT (15UL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_SAM_INDEX_CLEAR_MASK (0x1f0000UL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_SAM_INDEX_CLEAR_SHIFT (16UL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_CLEAR_ENABLE_MASK (0x40000000UL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_CLEAR_ENABLE_SHIFT (30UL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_CLEAR_ALL_MASK (0x80000000UL)
#define MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_CLEAR_ALL_SHIFT (31UL)




typedef uint32_t MACSEC_I_FCTRL_EN_SAM_IN_FLIGHT_TYPE;
#define MACSEC_I_FCTRL_EN_SAM_IN_FLIGHT_UNSAFE_MASK (0x3fUL)
#define MACSEC_I_FCTRL_EN_SAM_IN_FLIGHT_UNSAFE_SHIFT (0UL)
#define MACSEC_I_FCTRL_EN_SAM_IN_FLIGHT_IN_FLIGHT_MASK (0x3f00UL)
#define MACSEC_I_FCTRL_EN_SAM_IN_FLIGHT_IN_FLIGHT_SHIFT (8UL)
#define MACSEC_I_FCTRL_EN_SAM_IN_FLIGHT_LOAD_UNSAFE_MASK (0x80000000UL)
#define MACSEC_I_FCTRL_EN_SAM_IN_FLIGHT_LOAD_UNSAFE_SHIFT (31UL)




typedef volatile struct COMP_PACKED sMACSEC_I_FCTRL_EN_RDBType {
    MACSEC_I_FCTRL_EN_RESERVED_TYPE rsvd0[24576]; /* OFFSET: 0x0 */
    MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE1_TYPE entry_enable1; /* OFFSET: 0x6000 */
    MACSEC_I_FCTRL_EN_RESERVED_TYPE rsvd1[60]; /* OFFSET: 0x6004 */
    MACSEC_I_FCTRL_EN_SAM_ENTRY_TOGGLE1_TYPE entry_toggle1; /* OFFSET: 0x6040 */
    MACSEC_I_FCTRL_EN_RESERVED_TYPE rsvd2[60]; /* OFFSET: 0x6044 */
    MACSEC_I_FCTRL_EN_SAM_ENTRY_SET1_TYPE entry_set1; /* OFFSET: 0x6080 */
    MACSEC_I_FCTRL_EN_RESERVED_TYPE rsvd3[60]; /* OFFSET: 0x6084 */
    MACSEC_I_FCTRL_EN_SAM_ENTRY_CLEAR1_TYPE entry_clear1; /* OFFSET: 0x60c0 */
    MACSEC_I_FCTRL_EN_RESERVED_TYPE rsvd4[60]; /* OFFSET: 0x60c4 */
    MACSEC_I_FCTRL_EN_SAM_ENTRY_ENABLE_CTRL_TYPE entry_enable_ctrl; /* OFFSET: 0x6100 */
    MACSEC_I_FCTRL_EN_SAM_IN_FLIGHT_TYPE in_flight; /* OFFSET: 0x6104 */
} MACSEC_I_FCTRL_EN_RDBType;


#define EIP_160S_I_32_BRCM_SAM_ENABLE_CTRL0_BASE  (0x4D010000UL)

#define EIP_160S_I_32_BRCM_SAM_ENABLE_CTRL1_BASE  (0x4D110000UL)

#define EIP_160S_I_32_BRCM_SAM_ENABLE_CTRL2_BASE  (0x4D210000UL)

#define EIP_160S_I_32_BRCM_SAM_ENABLE_CTRL3_BASE  (0x4D310000UL)

#define EIP_160S_I_32_BRCM_SAM_ENABLE_CTRL4_BASE  (0x4D410000UL)

#define EIP_160S_I_32_BRCM_SAM_ENABLE_CTRL5_BASE  (0x4D510000UL)



#define MACSEC_I_FCTRL_EN_MAX_HW_ID     (6UL)

#endif /* MACSEC_I_FCTRL_EN_RDB_H */
