/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_e_fctrl_rdb.h
    @brief RDB File for MACSEC_E_FCTRL

    @version Orion_A0_20201104_SWDEV
*/

#ifndef MACSEC_E_FCTRL_RDB_H
#define MACSEC_E_FCTRL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_E_FCTRL_RESERVED_TYPE;




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_0_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_0_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_0_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_0_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_0_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_0_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_0_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_0_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_0_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_1_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_1_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_1_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_1_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_1_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_1_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_1_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_1_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_1_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_1_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_2_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_2_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_2_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_2_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_2_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_2_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_2_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_2_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_2_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_2_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_3_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_3_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_3_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_3_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_3_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_3_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_3_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_3_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_3_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_3_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_4_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_4_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_4_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_4_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_4_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_4_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_4_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_4_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_4_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_4_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_5_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_5_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_5_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_5_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_5_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_5_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_5_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_5_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_5_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_5_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_6_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_6_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_6_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_6_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_6_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_6_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_6_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_6_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_6_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_6_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_7_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_7_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_7_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_7_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_7_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_7_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_7_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_7_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_7_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_7_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_8_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_8_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_8_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_8_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_8_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_8_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_8_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_8_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_8_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_8_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_9_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_9_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_9_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_9_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_9_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_9_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_9_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_9_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_9_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_9_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_10_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_10_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_10_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_10_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_10_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_10_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_10_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_10_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_10_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_10_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_11_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_11_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_11_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_11_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_11_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_11_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_11_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_11_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_11_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_11_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_12_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_12_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_12_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_12_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_12_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_12_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_12_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_12_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_12_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_12_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_13_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_13_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_13_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_13_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_13_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_13_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_13_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_13_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_13_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_13_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_14_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_14_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_14_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_14_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_14_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_14_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_14_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_14_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_14_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_14_CONFIDENTIALITY_OFFSET_SHIFT (24UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_FLOW_TYPE_MASK (0x3UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_FLOW_TYPE_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_DEST_PORT_MASK (0xcUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_DEST_PORT_SHIFT (2UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_DROP_NON_REDIR_MASK (0x10UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_DROP_NON_REDIR_SHIFT (4UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_FLOW_CRYPT_AUTH_MASK (0x20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_FLOW_CRYPT_AUTH_SHIFT (5UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_DROP_ACTION_MASK (0xc0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_DROP_ACTION_SHIFT (6UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_CAPT_REASON_MASK (0xf00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_CAPT_REASON_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_PROTECT_FRAME_MASK (0x10000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_PROTECT_FRAME_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_CONF_PROTECT_MASK (0x20000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_CONF_PROTECT_SHIFT (17UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_INCLUDE_SCI_MASK (0x40000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_INCLUDE_SCI_SHIFT (18UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_USE_ES_MASK (0x80000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_USE_ES_SHIFT (19UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_USE_SCB_MASK (0x100000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_USE_SCB_SHIFT (20UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_ALLOW_DATA_PACKETS_MASK (0x200000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_ALLOW_DATA_PACKETS_SHIFT (21UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_EOMPLS_CTRL_WORD_MASK (0x400000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_EOMPLS_CTRL_WORD_SHIFT (22UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_EOMPLS_SUBPORT_MASK (0x800000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL1_15_EOMPLS_SUBPORT_SHIFT (23UL)




typedef uint32_t MACSEC_E_FCTRL_SAM_FLOW_CTRL2_15_TYPE;
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_15_PRE_SECTAG_AUTH_START_MASK (0x3fUL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_15_PRE_SECTAG_AUTH_START_SHIFT (0UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_15_PRE_SECTAG_AUTH_LEN_MASK (0x3f00UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_15_PRE_SECTAG_AUTH_LEN_SHIFT (8UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_15_SECTAG_OFFSET_MASK (0x3f0000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_15_SECTAG_OFFSET_SHIFT (16UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_15_CONFIDENTIALITY_OFFSET_MASK (0xff000000UL)
#define MACSEC_E_FCTRL_SAM_FLOW_CTRL2_15_CONFIDENTIALITY_OFFSET_SHIFT (24UL)


typedef volatile struct COMP_PACKED sMACSEC_E_FCTRL_SAMFLOW_RDBType {
    MACSEC_E_FCTRL_SAM_FLOW_CTRL1_0_TYPE ctrl1_0; /* OFFSET: 0x17000 */
    MACSEC_E_FCTRL_SAM_FLOW_CTRL2_0_TYPE ctrl2_0; /* OFFSET: 0x17004 */
} MACSEC_E_FCTRL_SAMFLOW_RDBType;


#define MACSEC_E_FCTRL_SAMFLOW_REGS_SIZE  (16UL)


typedef volatile struct COMP_PACKED sMACSEC_E_FCTRL_RDBType {
    MACSEC_E_FCTRL_RESERVED_TYPE rsvd0[94208]; /* OFFSET: 0x0 */
    MACSEC_E_FCTRL_SAMFLOW_RDBType samflow_regs[MACSEC_E_FCTRL_SAMFLOW_REGS_SIZE]; /* OFFSET: 0x17000 */
} MACSEC_E_FCTRL_RDBType;


#define EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE00_BASE  (0x4D010000UL)

#define MACSEC_E_FCTRL_SAMFLOW_RDBTYPE_EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE00_OFFSET  (0x4d027000UL)

#define EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE01_BASE  (0x4D110000UL)

#define MACSEC_E_FCTRL_SAMFLOW_RDBTYPE_EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE01_OFFSET  (0x4d127000UL)

#define EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE02_BASE  (0x4D210000UL)

#define MACSEC_E_FCTRL_SAMFLOW_RDBTYPE_EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE02_OFFSET  (0x4d227000UL)

#define EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE03_BASE  (0x4D310000UL)

#define MACSEC_E_FCTRL_SAMFLOW_RDBTYPE_EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE03_OFFSET  (0x4d327000UL)

#define EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE04_BASE  (0x4D410000UL)

#define MACSEC_E_FCTRL_SAMFLOW_RDBTYPE_EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE04_OFFSET  (0x4d427000UL)

#define EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE05_BASE  (0x4D510000UL)

#define MACSEC_E_FCTRL_SAMFLOW_RDBTYPE_EIP_160S_E_32_BRCM_FLOW_CONTROL_PAGE05_OFFSET  (0x4d527000UL)



#define MACSEC_E_FCTRL_MAX_HW_ID        (6UL)

#endif /* MACSEC_E_FCTRL_RDB_H */
