/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_i_tcam_cntrs_rdb.h
    @brief RDB File for MACSEC_I_TCAM_CNTRS

    @version Orion_A0_20201104_SWDEV
*/

#ifndef MACSEC_I_TCAM_CNTRS_RDB_H
#define MACSEC_I_TCAM_CNTRS_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_I_TCAM_CNTRS_RESERVED_TYPE;




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_0_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_0_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_0_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_0_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_0_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_0_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_1_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_1_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_1_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_1_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_1_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_1_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_2_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_2_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_2_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_2_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_2_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_2_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_3_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_3_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_3_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_3_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_3_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_3_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_4_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_4_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_4_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_4_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_4_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_4_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_5_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_5_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_5_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_5_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_5_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_5_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_6_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_6_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_6_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_6_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_6_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_6_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_7_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_7_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_7_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_7_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_7_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_7_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_8_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_8_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_8_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_8_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_8_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_8_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_9_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_9_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_9_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_9_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_9_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_9_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_10_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_10_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_10_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_10_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_10_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_10_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_11_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_11_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_11_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_11_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_11_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_11_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_12_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_12_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_12_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_12_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_12_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_12_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_13_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_13_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_13_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_13_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_13_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_13_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_14_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_14_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_14_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_14_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_14_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_14_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_15_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_15_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_15_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_15_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_15_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_15_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_16_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_16_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_16_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_16_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_16_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_16_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_17_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_17_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_17_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_17_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_17_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_17_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_18_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_18_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_18_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_18_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_18_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_18_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_19_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_19_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_19_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_19_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_19_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_19_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_20_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_20_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_20_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_20_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_20_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_20_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_21_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_21_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_21_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_21_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_21_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_21_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_22_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_22_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_22_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_22_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_22_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_22_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_23_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_23_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_23_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_23_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_23_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_23_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_24_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_24_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_24_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_24_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_24_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_24_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_25_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_25_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_25_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_25_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_25_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_25_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_26_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_26_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_26_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_26_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_26_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_26_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_27_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_27_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_27_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_27_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_27_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_27_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_28_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_28_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_28_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_28_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_28_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_28_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_29_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_29_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_29_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_29_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_29_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_29_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_30_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_30_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_30_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_30_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_30_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_30_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_31_TCAMHIT_LO_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_31_TCAMHIT_LO_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_31_TCAMHIT_LO_COUNTER_SHIFT (0UL)




typedef uint32_t MACSEC_I_TCAM_CNTRS_TCAM_31_TCAMHIT_HI_TYPE;
#define MACSEC_I_TCAM_CNTRS_TCAM_31_TCAMHIT_HI_COUNTER_MASK (0xffffffffUL)
#define MACSEC_I_TCAM_CNTRS_TCAM_31_TCAMHIT_HI_COUNTER_SHIFT (0UL)




typedef volatile struct COMP_PACKED sMACSEC_I_TCAM_CNTRS_RDBType {
    MACSEC_I_TCAM_CNTRS_RESERVED_TYPE rsvd0[16384]; /* OFFSET: 0x0 */
    MACSEC_I_TCAM_CNTRS_TCAM_0_TCAMHIT_LO_TYPE m0_lo; /* OFFSET: 0x4000 */
    MACSEC_I_TCAM_CNTRS_TCAM_0_TCAMHIT_HI_TYPE m0_hi; /* OFFSET: 0x4004 */
    MACSEC_I_TCAM_CNTRS_TCAM_1_TCAMHIT_LO_TYPE m1_lo; /* OFFSET: 0x4008 */
    MACSEC_I_TCAM_CNTRS_TCAM_1_TCAMHIT_HI_TYPE m1_hi; /* OFFSET: 0x400c */
    MACSEC_I_TCAM_CNTRS_TCAM_2_TCAMHIT_LO_TYPE m2_lo; /* OFFSET: 0x4010 */
    MACSEC_I_TCAM_CNTRS_TCAM_2_TCAMHIT_HI_TYPE m2_hi; /* OFFSET: 0x4014 */
    MACSEC_I_TCAM_CNTRS_TCAM_3_TCAMHIT_LO_TYPE m3_lo; /* OFFSET: 0x4018 */
    MACSEC_I_TCAM_CNTRS_TCAM_3_TCAMHIT_HI_TYPE m3_hi; /* OFFSET: 0x401c */
    MACSEC_I_TCAM_CNTRS_TCAM_4_TCAMHIT_LO_TYPE m4_lo; /* OFFSET: 0x4020 */
    MACSEC_I_TCAM_CNTRS_TCAM_4_TCAMHIT_HI_TYPE m4_hi; /* OFFSET: 0x4024 */
    MACSEC_I_TCAM_CNTRS_TCAM_5_TCAMHIT_LO_TYPE m5_lo; /* OFFSET: 0x4028 */
    MACSEC_I_TCAM_CNTRS_TCAM_5_TCAMHIT_HI_TYPE m5_hi; /* OFFSET: 0x402c */
    MACSEC_I_TCAM_CNTRS_TCAM_6_TCAMHIT_LO_TYPE m6_lo; /* OFFSET: 0x4030 */
    MACSEC_I_TCAM_CNTRS_TCAM_6_TCAMHIT_HI_TYPE m6_hi; /* OFFSET: 0x4034 */
    MACSEC_I_TCAM_CNTRS_TCAM_7_TCAMHIT_LO_TYPE m7_lo; /* OFFSET: 0x4038 */
    MACSEC_I_TCAM_CNTRS_TCAM_7_TCAMHIT_HI_TYPE m7_hi; /* OFFSET: 0x403c */
    MACSEC_I_TCAM_CNTRS_TCAM_8_TCAMHIT_LO_TYPE m8_lo; /* OFFSET: 0x4040 */
    MACSEC_I_TCAM_CNTRS_TCAM_8_TCAMHIT_HI_TYPE m8_hi; /* OFFSET: 0x4044 */
    MACSEC_I_TCAM_CNTRS_TCAM_9_TCAMHIT_LO_TYPE m9_lo; /* OFFSET: 0x4048 */
    MACSEC_I_TCAM_CNTRS_TCAM_9_TCAMHIT_HI_TYPE m9_hi; /* OFFSET: 0x404c */
    MACSEC_I_TCAM_CNTRS_TCAM_10_TCAMHIT_LO_TYPE m10_lo; /* OFFSET: 0x4050 */
    MACSEC_I_TCAM_CNTRS_TCAM_10_TCAMHIT_HI_TYPE m10_hi; /* OFFSET: 0x4054 */
    MACSEC_I_TCAM_CNTRS_TCAM_11_TCAMHIT_LO_TYPE m11_lo; /* OFFSET: 0x4058 */
    MACSEC_I_TCAM_CNTRS_TCAM_11_TCAMHIT_HI_TYPE m11_hi; /* OFFSET: 0x405c */
    MACSEC_I_TCAM_CNTRS_TCAM_12_TCAMHIT_LO_TYPE m12_lo; /* OFFSET: 0x4060 */
    MACSEC_I_TCAM_CNTRS_TCAM_12_TCAMHIT_HI_TYPE m12_hi; /* OFFSET: 0x4064 */
    MACSEC_I_TCAM_CNTRS_TCAM_13_TCAMHIT_LO_TYPE m13_lo; /* OFFSET: 0x4068 */
    MACSEC_I_TCAM_CNTRS_TCAM_13_TCAMHIT_HI_TYPE m13_hi; /* OFFSET: 0x406c */
    MACSEC_I_TCAM_CNTRS_TCAM_14_TCAMHIT_LO_TYPE m14_lo; /* OFFSET: 0x4070 */
    MACSEC_I_TCAM_CNTRS_TCAM_14_TCAMHIT_HI_TYPE m14_hi; /* OFFSET: 0x4074 */
    MACSEC_I_TCAM_CNTRS_TCAM_15_TCAMHIT_LO_TYPE m15_lo; /* OFFSET: 0x4078 */
    MACSEC_I_TCAM_CNTRS_TCAM_15_TCAMHIT_HI_TYPE m15_hi; /* OFFSET: 0x407c */
    MACSEC_I_TCAM_CNTRS_TCAM_16_TCAMHIT_LO_TYPE m16_lo; /* OFFSET: 0x4080 */
    MACSEC_I_TCAM_CNTRS_TCAM_16_TCAMHIT_HI_TYPE m16_hi; /* OFFSET: 0x4084 */
    MACSEC_I_TCAM_CNTRS_TCAM_17_TCAMHIT_LO_TYPE m17_lo; /* OFFSET: 0x4088 */
    MACSEC_I_TCAM_CNTRS_TCAM_17_TCAMHIT_HI_TYPE m17_hi; /* OFFSET: 0x408c */
    MACSEC_I_TCAM_CNTRS_TCAM_18_TCAMHIT_LO_TYPE m18_lo; /* OFFSET: 0x4090 */
    MACSEC_I_TCAM_CNTRS_TCAM_18_TCAMHIT_HI_TYPE m18_hi; /* OFFSET: 0x4094 */
    MACSEC_I_TCAM_CNTRS_TCAM_19_TCAMHIT_LO_TYPE m19_lo; /* OFFSET: 0x4098 */
    MACSEC_I_TCAM_CNTRS_TCAM_19_TCAMHIT_HI_TYPE m19_hi; /* OFFSET: 0x409c */
    MACSEC_I_TCAM_CNTRS_TCAM_20_TCAMHIT_LO_TYPE m20_lo; /* OFFSET: 0x40a0 */
    MACSEC_I_TCAM_CNTRS_TCAM_20_TCAMHIT_HI_TYPE m20_hi; /* OFFSET: 0x40a4 */
    MACSEC_I_TCAM_CNTRS_TCAM_21_TCAMHIT_LO_TYPE m21_lo; /* OFFSET: 0x40a8 */
    MACSEC_I_TCAM_CNTRS_TCAM_21_TCAMHIT_HI_TYPE m21_hi; /* OFFSET: 0x40ac */
    MACSEC_I_TCAM_CNTRS_TCAM_22_TCAMHIT_LO_TYPE m22_lo; /* OFFSET: 0x40b0 */
    MACSEC_I_TCAM_CNTRS_TCAM_22_TCAMHIT_HI_TYPE m22_hi; /* OFFSET: 0x40b4 */
    MACSEC_I_TCAM_CNTRS_TCAM_23_TCAMHIT_LO_TYPE m23_lo; /* OFFSET: 0x40b8 */
    MACSEC_I_TCAM_CNTRS_TCAM_23_TCAMHIT_HI_TYPE m23_hi; /* OFFSET: 0x40bc */
    MACSEC_I_TCAM_CNTRS_TCAM_24_TCAMHIT_LO_TYPE m24_lo; /* OFFSET: 0x40c0 */
    MACSEC_I_TCAM_CNTRS_TCAM_24_TCAMHIT_HI_TYPE m24_hi; /* OFFSET: 0x40c4 */
    MACSEC_I_TCAM_CNTRS_TCAM_25_TCAMHIT_LO_TYPE m25_lo; /* OFFSET: 0x40c8 */
    MACSEC_I_TCAM_CNTRS_TCAM_25_TCAMHIT_HI_TYPE m25_hi; /* OFFSET: 0x40cc */
    MACSEC_I_TCAM_CNTRS_TCAM_26_TCAMHIT_LO_TYPE m26_lo; /* OFFSET: 0x40d0 */
    MACSEC_I_TCAM_CNTRS_TCAM_26_TCAMHIT_HI_TYPE m26_hi; /* OFFSET: 0x40d4 */
    MACSEC_I_TCAM_CNTRS_TCAM_27_TCAMHIT_LO_TYPE m27_lo; /* OFFSET: 0x40d8 */
    MACSEC_I_TCAM_CNTRS_TCAM_27_TCAMHIT_HI_TYPE m27_hi; /* OFFSET: 0x40dc */
    MACSEC_I_TCAM_CNTRS_TCAM_28_TCAMHIT_LO_TYPE m28_lo; /* OFFSET: 0x40e0 */
    MACSEC_I_TCAM_CNTRS_TCAM_28_TCAMHIT_HI_TYPE m28_hi; /* OFFSET: 0x40e4 */
    MACSEC_I_TCAM_CNTRS_TCAM_29_TCAMHIT_LO_TYPE m29_lo; /* OFFSET: 0x40e8 */
    MACSEC_I_TCAM_CNTRS_TCAM_29_TCAMHIT_HI_TYPE m29_hi; /* OFFSET: 0x40ec */
    MACSEC_I_TCAM_CNTRS_TCAM_30_TCAMHIT_LO_TYPE m30_lo; /* OFFSET: 0x40f0 */
    MACSEC_I_TCAM_CNTRS_TCAM_30_TCAMHIT_HI_TYPE m30_hi; /* OFFSET: 0x40f4 */
    MACSEC_I_TCAM_CNTRS_TCAM_31_TCAMHIT_LO_TYPE m31_lo; /* OFFSET: 0x40f8 */
    MACSEC_I_TCAM_CNTRS_TCAM_31_TCAMHIT_HI_TYPE m31_hi; /* OFFSET: 0x40fc */
} MACSEC_I_TCAM_CNTRS_RDBType;


#define EIP165_IGEIP160_STATTCAM_TCAM_TCAM_COUNTERS_0_310_BASE  (0x4D010000UL)

#define EIP165_IGEIP160_STATTCAM_TCAM_TCAM_COUNTERS_0_311_BASE  (0x4D110000UL)

#define EIP165_IGEIP160_STATTCAM_TCAM_TCAM_COUNTERS_0_312_BASE  (0x4D210000UL)

#define EIP165_IGEIP160_STATTCAM_TCAM_TCAM_COUNTERS_0_313_BASE  (0x4D310000UL)

#define EIP165_IGEIP160_STATTCAM_TCAM_TCAM_COUNTERS_0_314_BASE  (0x4D410000UL)

#define EIP165_IGEIP160_STATTCAM_TCAM_TCAM_COUNTERS_0_315_BASE  (0x4D510000UL)



#define MACSEC_I_TCAM_CNTRS_MAX_HW_ID   (6UL)

#endif /* MACSEC_I_TCAM_CNTRS_RDB_H */
