/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_e_eip62_rdb.h
    @brief RDB File for MACSEC_E_EIP62

    @version Orion_A0_20201104_SWDEV
*/

#ifndef MACSEC_E_EIP62_RDB_H
#define MACSEC_E_EIP62_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_E_EIP62_RESERVED_TYPE;




typedef uint32_t MACSEC_E_EIP62_E62TCS_TYPE;
#define MACSEC_E_EIP62_E62TCS_TOKEN_LOCATION_AVAILABLE_MASK (0x4UL)
#define MACSEC_E_EIP62_E62TCS_TOKEN_LOCATION_AVAILABLE_SHIFT (2UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_PROT_ALG_EN_TYPE;
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_HASH_ONLY_NULL_MASK (0x1UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_HASH_ONLY_NULL_SHIFT (0UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_ENCRYPT_ONLY_MASK (0x2UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_ENCRYPT_ONLY_SHIFT (1UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_HASH_ENCRYPT_MASK (0x4UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_HASH_ENCRYPT_SHIFT (2UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_HASH_DECRYPT_MASK (0x8UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_HASH_DECRYPT_SHIFT (3UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_ENCRYPT_HASH_MASK (0x10UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_ENCRYPT_HASH_SHIFT (4UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_DECRYPT_HASH_MASK (0x20UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_DECRYPT_HASH_SHIFT (5UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_KEY_128_BIT_MASK (0x40UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_KEY_128_BIT_SHIFT (6UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_KEY_256_BIT_MASK (0x80UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_KEY_256_BIT_SHIFT (7UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_ECB_MASK (0x100UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_ECB_SHIFT (8UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_CBC_MASK (0x200UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_CBC_SHIFT (9UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_CTR_ICM_MASK (0x400UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_CTR_ICM_SHIFT (10UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_OFB_MASK (0x800UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_OFB_SHIFT (11UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_CFB_MASK (0x1000UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_CFB_SHIFT (12UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_XCBC_MAC_MASK (0x40000000UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_AES_XCBC_MAC_SHIFT (30UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_GCM_HASH_MASK (0x80000000UL)
#define MACSEC_E_EIP62_EIP62_PROT_ALG_EN_GCM_HASH_SHIFT (31UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_TYPE;
#define MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_CONTEXT_SIZE_MASK (0x1fUL)
#define MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_CONTEXT_SIZE_SHIFT (0UL)
#define MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_ADDRESS_MODE_MASK (0x100UL)
#define MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_ADDRESS_MODE_SHIFT (8UL)
#define MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_CONTROL_MODE_MASK (0x200UL)
#define MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_CONTROL_MODE_SHIFT (9UL)
#define MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_PKT_NUM_THR_MODE_MASK (0x400UL)
#define MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_PKT_NUM_THR_MODE_SHIFT (10UL)
#define MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_MACSEC_ETHERTYPE_MASK (0xffff0000UL)
#define MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_MACSEC_ETHERTYPE_SHIFT (16UL)




typedef uint32_t MACSEC_E_EIP62_E62CS_TYPE;
#define MACSEC_E_EIP62_E62CS_ERROR_MASK (0x7fffUL)
#define MACSEC_E_EIP62_E62CS_ERROR_SHIFT (0UL)
#define MACSEC_E_EIP62_E62CS_ACTIVE_TOKENS_MASK (0x30000UL)
#define MACSEC_E_EIP62_E62CS_ACTIVE_TOKENS_SHIFT (16UL)
#define MACSEC_E_EIP62_E62CS_ACTIVE_CONTEXT_MASK (0x40000UL)
#define MACSEC_E_EIP62_E62CS_ACTIVE_CONTEXT_SHIFT (18UL)
#define MACSEC_E_EIP62_E62CS_NEXT_CONTEXT_MASK (0x80000UL)
#define MACSEC_E_EIP62_E62CS_NEXT_CONTEXT_SHIFT (19UL)
#define MACSEC_E_EIP62_E62CS_RESULT_CONTEXT_MASK (0x100000UL)
#define MACSEC_E_EIP62_E62CS_RESULT_CONTEXT_SHIFT (20UL)
#define MACSEC_E_EIP62_E62CS_ERROR_RECOVERY_MASK (0x200000UL)
#define MACSEC_E_EIP62_E62CS_ERROR_RECOVERY_SHIFT (21UL)
#define MACSEC_E_EIP62_E62CS_INPUT_FRAME_CURRENT_STATE_MASK (0xf0000000UL)
#define MACSEC_E_EIP62_E62CS_INPUT_FRAME_CURRENT_STATE_SHIFT (28UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_TYPE;
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_INPUT_ERROR_MASK (0x1UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_INPUT_ERROR_SHIFT (0UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_OUTPUT_ERROR_MASK (0x2UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_OUTPUT_ERROR_SHIFT (1UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_PROCESSING_ERROR_MASK (0x4UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_PROCESSING_ERROR_SHIFT (2UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_CONTEXT_ERROR_MASK (0x8UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_CONTEXT_ERROR_SHIFT (3UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_SEQNUM_THRESHOLD_MASK (0x10UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_SEQNUM_THRESHOLD_SHIFT (4UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_SEQNUM_ROLLOVER_MASK (0x20UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_SEQNUM_ROLLOVER_SHIFT (5UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_FATAL_ERROR_MASK (0x4000UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_FATAL_ERROR_SHIFT (14UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_INTERRUPT_OUT_MASK (0x8000UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_INTERRUPT_OUT_SHIFT (15UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_INPUT_ERROR_EN_MASK (0x10000UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_INPUT_ERROR_EN_SHIFT (16UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_OUTPUT_ERROR_EN_MASK (0x20000UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_OUTPUT_ERROR_EN_SHIFT (17UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_PROCESSING_ERROR_EN_MASK (0x40000UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_PROCESSING_ERROR_EN_SHIFT (18UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_CONTEXT_ERROR_EN_MASK (0x80000UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_CONTEXT_ERROR_EN_SHIFT (19UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_SEQNUM_THRESHOLD_EN_MASK (0x100000UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_SEQNUM_THRESHOLD_EN_SHIFT (20UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_SEQNUM_ROLLOVER_EN_MASK (0x200000UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_SEQNUM_ROLLOVER_EN_SHIFT (21UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_FATAL_ERROR_EN_MASK (0x40000000UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_FATAL_ERROR_EN_SHIFT (30UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_INTERRUPT_OUT_EN_MASK (0x80000000UL)
#define MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_INTERRUPT_OUT_EN_SHIFT (31UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_SW_INTERRUPT_TYPE;
#define MACSEC_E_EIP62_EIP62_SW_INTERRUPT_INTERRUPT_MASK (0xffffffffUL)
#define MACSEC_E_EIP62_EIP62_SW_INTERRUPT_INTERRUPT_SHIFT (0UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD_TYPE;
#define MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD_DUMMY_MASK (0xffffffffUL)
#define MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD_DUMMY_SHIFT (0UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD64_LO_TYPE;
#define MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD64_LO_DUMMY_MASK (0xffffffffUL)
#define MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD64_LO_DUMMY_SHIFT (0UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD64_HI_TYPE;
#define MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD64_HI_DUMMY_MASK (0xffffffffUL)
#define MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD64_HI_DUMMY_SHIFT (0UL)




typedef uint32_t MACSEC_E_EIP62_E62CUC_TYPE;
#define MACSEC_E_EIP62_E62CUC_BLOCK_CONTEXT_UPDATES_MASK (0x3UL)
#define MACSEC_E_EIP62_E62CUC_BLOCK_CONTEXT_UPDATES_SHIFT (0UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_NEXTPN_LO_TYPE;
#define MACSEC_E_EIP62_EIP62_NEXTPN_LO_DUMMY_MASK (0xffffffffUL)
#define MACSEC_E_EIP62_EIP62_NEXTPN_LO_DUMMY_SHIFT (0UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_NEXTPN_HI_TYPE;
#define MACSEC_E_EIP62_EIP62_NEXTPN_HI_DUMMY_MASK (0xffffffffUL)
#define MACSEC_E_EIP62_EIP62_NEXTPN_HI_DUMMY_SHIFT (0UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_NEXTPN_CTX_ID_TYPE;
#define MACSEC_E_EIP62_EIP62_NEXTPN_CTX_ID_DUMMY_MASK (0xffffffffUL)
#define MACSEC_E_EIP62_EIP62_NEXTPN_CTX_ID_DUMMY_SHIFT (0UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_NEXTPN_CTRL_TYPE;
#define MACSEC_E_EIP62_EIP62_NEXTPN_CTRL_ENABLE_UPDATE_MASK (0x1UL)
#define MACSEC_E_EIP62_EIP62_NEXTPN_CTRL_ENABLE_UPDATE_SHIFT (0UL)
#define MACSEC_E_EIP62_EIP62_NEXTPN_CTRL_NEXTPN_WRITTEN_MASK (0x2UL)
#define MACSEC_E_EIP62_EIP62_NEXTPN_CTRL_NEXTPN_WRITTEN_SHIFT (1UL)
#define MACSEC_E_EIP62_EIP62_NEXTPN_CTRL_SEQUENCE_NUMBER_SIZE_MASK (0x4UL)
#define MACSEC_E_EIP62_EIP62_NEXTPN_CTRL_SEQUENCE_NUMBER_SIZE_SHIFT (2UL)
#define MACSEC_E_EIP62_EIP62_NEXTPN_CTRL_NEXTPN_CONTEXT_ADDRESS_MASK (0xfffffff0UL)
#define MACSEC_E_EIP62_EIP62_NEXTPN_CTRL_NEXTPN_CONTEXT_ADDRESS_SHIFT (4UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_UPDATE_CTRL_TYPE;
#define MACSEC_E_EIP62_EIP62_UPDATE_CTRL_UPDATE_THRESHOLD_MASK (0xffUL)
#define MACSEC_E_EIP62_EIP62_UPDATE_CTRL_UPDATE_THRESHOLD_SHIFT (0UL)
#define MACSEC_E_EIP62_EIP62_UPDATE_CTRL_THRESHOLD_EN_MASK (0x80000000UL)
#define MACSEC_E_EIP62_EIP62_UPDATE_CTRL_THRESHOLD_EN_SHIFT (31UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_CONFIG_TYPE;
#define MACSEC_E_EIP62_EIP62_CONFIG_MINOR_VERSION_MASK (0xfUL)
#define MACSEC_E_EIP62_EIP62_CONFIG_MINOR_VERSION_SHIFT (0UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_MAJOR_VERSION_MASK (0xf0UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_MAJOR_VERSION_SHIFT (4UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_FPGA_SOLUTION_MASK (0x100UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_FPGA_SOLUTION_SHIFT (8UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_ASIC_AES_GF_SBOX_MASK (0x200UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_ASIC_AES_GF_SBOX_SHIFT (9UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_ASIC_AES_LU_SBOX_MASK (0x400UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_ASIC_AES_LU_SBOX_SHIFT (10UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_MACSEC_AES_ONLY_MASK (0x800UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_MACSEC_AES_ONLY_SHIFT (11UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_AES_MASK (0x1000UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_AES_SHIFT (12UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_AES_FB_MASK (0x2000UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_AES_FB_SHIFT (13UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_AES_SPEED_MASK (0x3c000UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_AES_SPEED_SHIFT (14UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_AES192_MASK (0x40000UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_AES192_SHIFT (18UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_AES256_MASK (0x80000UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_AES256_SHIFT (19UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_EOP_PARAM_BITS_MASK (0x1f00000UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_EOP_PARAM_BITS_SHIFT (20UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_IPSEC_MASK (0x2000000UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_IPSEC_SHIFT (25UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_HDR_EXTENSIONS_MASK (0x4000000UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_HDR_EXTENSIONS_SHIFT (26UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_GHASH_AVAILABLE_MASK (0x40000000UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_GHASH_AVAILABLE_SHIFT (30UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_GHASH_SPEED_MASK (0x80000000UL)
#define MACSEC_E_EIP62_EIP62_CONFIG_GHASH_SPEED_SHIFT (31UL)




typedef uint32_t MACSEC_E_EIP62_EIP62_VERSION_TYPE;
#define MACSEC_E_EIP62_EIP62_VERSION_EIP_NUMBER_MASK (0xffUL)
#define MACSEC_E_EIP62_EIP62_VERSION_EIP_NUMBER_SHIFT (0UL)
#define MACSEC_E_EIP62_EIP62_VERSION_EIP_NUMBER_COMPL_MASK (0xff00UL)
#define MACSEC_E_EIP62_EIP62_VERSION_EIP_NUMBER_COMPL_SHIFT (8UL)
#define MACSEC_E_EIP62_EIP62_VERSION_PATCH_LEVEL_MASK (0xf0000UL)
#define MACSEC_E_EIP62_EIP62_VERSION_PATCH_LEVEL_SHIFT (16UL)
#define MACSEC_E_EIP62_EIP62_VERSION_MINOR_VERSION_MASK (0xf00000UL)
#define MACSEC_E_EIP62_EIP62_VERSION_MINOR_VERSION_SHIFT (20UL)
#define MACSEC_E_EIP62_EIP62_VERSION_MAJOR_VERSION_MASK (0xf000000UL)
#define MACSEC_E_EIP62_EIP62_VERSION_MAJOR_VERSION_SHIFT (24UL)




typedef volatile struct COMP_PACKED sMACSEC_E_EIP62_RDBType {
    MACSEC_E_EIP62_RESERVED_TYPE rsvd0[128000]; /* OFFSET: 0x0 */
    MACSEC_E_EIP62_E62TCS_TYPE token_ctrl_stat; /* OFFSET: 0x1f400 */
    MACSEC_E_EIP62_EIP62_PROT_ALG_EN_TYPE prot_alg_en; /* OFFSET: 0x1f404 */
    MACSEC_E_EIP62_EIP62_CONTEXT_CTRL_TYPE context_ctrl; /* OFFSET: 0x1f408 */
    MACSEC_E_EIP62_E62CS_TYPE context_stat; /* OFFSET: 0x1f40c */
    MACSEC_E_EIP62_EIP62_INT_CTRL_STAT_TYPE int_ctrl_stat; /* OFFSET: 0x1f410 */
    MACSEC_E_EIP62_EIP62_SW_INTERRUPT_TYPE sw_interrupt; /* OFFSET: 0x1f414 */
    MACSEC_E_EIP62_RESERVED_TYPE rsvd1[8]; /* OFFSET: 0x1f418 */
    MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD_TYPE seq_num_threshold; /* OFFSET: 0x1f420 */
    MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD64_LO_TYPE seq_num_threshold64_lo; /* OFFSET: 0x1f424 */
    MACSEC_E_EIP62_EIP62_SEQ_NUM_THRESHOLD64_HI_TYPE seq_num_threshold64_hi; /* OFFSET: 0x1f428 */
    MACSEC_E_EIP62_RESERVED_TYPE rsvd2[4]; /* OFFSET: 0x1f42c */
    MACSEC_E_EIP62_E62CUC_TYPE context_upd_ctrl; /* OFFSET: 0x1f430 */
    MACSEC_E_EIP62_RESERVED_TYPE rsvd3[76]; /* OFFSET: 0x1f434 */
    MACSEC_E_EIP62_EIP62_NEXTPN_LO_TYPE nextpn_lo; /* OFFSET: 0x1f480 */
    MACSEC_E_EIP62_EIP62_NEXTPN_HI_TYPE nextpn_hi; /* OFFSET: 0x1f484 */
    MACSEC_E_EIP62_EIP62_NEXTPN_CTX_ID_TYPE nextpn_ctx_id; /* OFFSET: 0x1f488 */
    MACSEC_E_EIP62_EIP62_NEXTPN_CTRL_TYPE nextpn_ctrl; /* OFFSET: 0x1f48c */
    MACSEC_E_EIP62_RESERVED_TYPE rsvd4[48]; /* OFFSET: 0x1f490 */
    MACSEC_E_EIP62_EIP62_UPDATE_CTRL_TYPE update_ctrl; /* OFFSET: 0x1f4c0 */
    MACSEC_E_EIP62_RESERVED_TYPE rsvd5[820]; /* OFFSET: 0x1f4c4 */
    MACSEC_E_EIP62_EIP62_CONFIG_TYPE config; /* OFFSET: 0x1f7f8 */
    MACSEC_E_EIP62_EIP62_VERSION_TYPE version; /* OFFSET: 0x1f7fc */
} MACSEC_E_EIP62_RDBType;


#define EIP165_EGEIP160_EIP62_EIP62_REGISTERS0_BASE  (0x4D010000UL)

#define EIP165_EGEIP160_EIP62_EIP62_REGISTERS1_BASE  (0x4D110000UL)

#define EIP165_EGEIP160_EIP62_EIP62_REGISTERS2_BASE  (0x4D210000UL)

#define EIP165_EGEIP160_EIP62_EIP62_REGISTERS3_BASE  (0x4D310000UL)

#define EIP165_EGEIP160_EIP62_EIP62_REGISTERS4_BASE  (0x4D410000UL)

#define EIP165_EGEIP160_EIP62_EIP62_REGISTERS5_BASE  (0x4D510000UL)



#define MACSEC_E_EIP62_MAX_HW_ID        (6UL)

#endif /* MACSEC_E_EIP62_RDB_H */
