/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_mspu_top_rdb.h
    @brief RDB File for MACSEC_MSPU_TOP

    @version Orion_A0_20201104_SWDEV
*/

#ifndef MACSEC_MSPU_TOP_RDB_H
#define MACSEC_MSPU_TOP_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t MACSEC_MSPU_TOP_MIB_CTRL_TYPE;
#define MACSEC_MSPU_TOP_MIB_CTRL_CNT_SATURATE_DIS_MASK (0x4UL)
#define MACSEC_MSPU_TOP_MIB_CTRL_CNT_SATURATE_DIS_SHIFT (2UL)
#define MACSEC_MSPU_TOP_MIB_CTRL_CNT_RD_CLR_DIS_MASK (0x2UL)
#define MACSEC_MSPU_TOP_MIB_CTRL_CNT_RD_CLR_DIS_SHIFT (1UL)
#define MACSEC_MSPU_TOP_MIB_CTRL_CLR_MIB_CNT_MASK (0x1UL)
#define MACSEC_MSPU_TOP_MIB_CTRL_CLR_MIB_CNT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_MIB_CNTMAXSIZE_TYPE;
#define MACSEC_MSPU_TOP_MIB_CNTMAXSIZE_R_GPORT_CNTMAXSIZE_MASK (0x3fffUL)
#define MACSEC_MSPU_TOP_MIB_CNTMAXSIZE_R_GPORT_CNTMAXSIZE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_LNMAC_R_GPORT_RSV_MASK_TYPE;
#define MACSEC_MSPU_TOP_LNMAC_R_GPORT_RSV_MASK_RESERVED_MASK (0xfffc0000UL)
#define MACSEC_MSPU_TOP_LNMAC_R_GPORT_RSV_MASK_RESERVED_SHIFT (18UL)
#define MACSEC_MSPU_TOP_LNMAC_R_GPORT_RSV_MASK_MASK_MASK (0x3ffffUL)
#define MACSEC_MSPU_TOP_LNMAC_R_GPORT_RSV_MASK_MASK_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_SWMAC_R_GPORT_RSV_MASK_TYPE;
#define MACSEC_MSPU_TOP_SWMAC_R_GPORT_RSV_MASK_RESERVED_MASK (0xfffc0000UL)
#define MACSEC_MSPU_TOP_SWMAC_R_GPORT_RSV_MASK_RESERVED_SHIFT (18UL)
#define MACSEC_MSPU_TOP_SWMAC_R_GPORT_RSV_MASK_MASK_MASK (0x3ffffUL)
#define MACSEC_MSPU_TOP_SWMAC_R_GPORT_RSV_MASK_MASK_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_LRGSUM_TYPE;
#define MACSEC_MSPU_TOP_LRGSUM_RESERVED_MASK (0xfffc0000UL)
#define MACSEC_MSPU_TOP_LRGSUM_RESERVED_SHIFT (18UL)
#define MACSEC_MSPU_TOP_LRGSUM_R_GPORT_STAT_UPDATE_MASK_MASK (0x3ffffUL)
#define MACSEC_MSPU_TOP_LRGSUM_R_GPORT_STAT_UPDATE_MASK_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_SRGSUM_TYPE;
#define MACSEC_MSPU_TOP_SRGSUM_RESERVED_MASK (0xfffc0000UL)
#define MACSEC_MSPU_TOP_SRGSUM_RESERVED_SHIFT (18UL)
#define MACSEC_MSPU_TOP_SRGSUM_R_GPORT_STAT_UPDATE_MASK_MASK (0x3ffffUL)
#define MACSEC_MSPU_TOP_SRGSUM_R_GPORT_STAT_UPDATE_MASK_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_INTERRUPT_STATUS0_TYPE;
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_0_MASK (0x1UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_0_SHIFT (0UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_1_MASK (0x2UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_1_SHIFT (1UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_2_MASK (0x4UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_2_SHIFT (2UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_3_MASK (0x8UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_3_SHIFT (3UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_4_MASK (0x10UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_4_SHIFT (4UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_5_MASK (0x20UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_5_SHIFT (5UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_6_MASK (0x40UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_6_SHIFT (6UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_7_MASK (0x80UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_7_SHIFT (7UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_8_MASK (0x100UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_8_SHIFT (8UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_9_MASK (0x200UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_9_SHIFT (9UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_10_MASK (0x400UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_10_SHIFT (10UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_11_MASK (0x800UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_11_SHIFT (11UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_12_MASK (0x1000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_12_SHIFT (12UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_13_MASK (0x2000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_13_SHIFT (13UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_14_MASK (0x4000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_14_SHIFT (14UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_15_MASK (0x8000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_15_SHIFT (15UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_16_MASK (0x10000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_16_SHIFT (16UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_17_MASK (0x20000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_17_SHIFT (17UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_18_MASK (0x40000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_18_SHIFT (18UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_19_MASK (0x80000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_19_SHIFT (19UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_20_MASK (0x100000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_20_SHIFT (20UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_21_MASK (0x200000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_21_SHIFT (21UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_22_MASK (0x400000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_22_SHIFT (22UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_23_MASK (0x800000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_23_SHIFT (23UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_24_MASK (0x1000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_24_SHIFT (24UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_25_MASK (0x2000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_25_SHIFT (25UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_26_MASK (0x4000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_26_SHIFT (26UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_27_MASK (0x8000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_27_SHIFT (27UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_28_MASK (0x10000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_28_SHIFT (28UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_29_MASK (0x20000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_29_SHIFT (29UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_30_MASK (0x40000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS0_30_SHIFT (30UL)




typedef uint32_t MACSEC_MSPU_TOP_INTERRUPT_STATUS1_TYPE;
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_0_MASK (0x1UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_0_SHIFT (0UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_1_MASK (0x2UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_1_SHIFT (1UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_2_MASK (0x4UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_2_SHIFT (2UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_3_MASK (0x8UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_3_SHIFT (3UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_4_MASK (0x10UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_4_SHIFT (4UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_5_MASK (0x20UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_5_SHIFT (5UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_6_MASK (0x40UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_6_SHIFT (6UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_7_MASK (0x80UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_7_SHIFT (7UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_8_MASK (0x100UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_8_SHIFT (8UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_9_MASK (0x200UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_9_SHIFT (9UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_10_MASK (0x400UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_10_SHIFT (10UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_11_MASK (0x800UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_11_SHIFT (11UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_12_MASK (0x1000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_12_SHIFT (12UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_13_MASK (0x2000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_13_SHIFT (13UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_14_MASK (0x4000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_14_SHIFT (14UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_15_MASK (0x8000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_15_SHIFT (15UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_16_MASK (0x10000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_16_SHIFT (16UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_17_MASK (0x20000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_17_SHIFT (17UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_18_MASK (0x40000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_18_SHIFT (18UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_19_MASK (0x80000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_19_SHIFT (19UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_20_MASK (0x100000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_20_SHIFT (20UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_21_MASK (0x200000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_21_SHIFT (21UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_22_MASK (0x400000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_22_SHIFT (22UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_23_MASK (0x800000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_23_SHIFT (23UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_24_MASK (0x1000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_24_SHIFT (24UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_25_MASK (0x2000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_25_SHIFT (25UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_26_MASK (0x4000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_26_SHIFT (26UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_27_MASK (0x8000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS1_27_SHIFT (27UL)




typedef uint32_t MACSEC_MSPU_TOP_INTERRUPT_STATUS2_TYPE;
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_0_MASK (0x1UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_0_SHIFT (0UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_1_MASK (0x2UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_1_SHIFT (1UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_2_MASK (0x4UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_2_SHIFT (2UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_3_MASK (0x8UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_3_SHIFT (3UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_4_MASK (0x10UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_4_SHIFT (4UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_5_MASK (0x20UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_5_SHIFT (5UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_6_MASK (0x40UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS2_6_SHIFT (6UL)




typedef uint32_t MACSEC_MSPU_TOP_INTERRUPT_ENABLE0_TYPE;
#define MACSEC_MSPU_TOP_INTERRUPT_ENABLE0_ENABLE0_MASK (0x7fffffffUL)
#define MACSEC_MSPU_TOP_INTERRUPT_ENABLE0_ENABLE0_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_INTERRUPT_ENABLE1_TYPE;
#define MACSEC_MSPU_TOP_INTERRUPT_ENABLE1_ENABLE1_MASK (0xfffffffUL)
#define MACSEC_MSPU_TOP_INTERRUPT_ENABLE1_ENABLE1_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_INTERRUPT_ENABLE2_TYPE;
#define MACSEC_MSPU_TOP_INTERRUPT_ENABLE2_ENABLE2_MASK (0x7fUL)
#define MACSEC_MSPU_TOP_INTERRUPT_ENABLE2_ENABLE2_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_FLUSH_MACSEC_BUFFERS_TYPE;
#define MACSEC_MSPU_TOP_FLUSH_MACSEC_BUFFERS_BUFFERS_MASK (0x1UL)
#define MACSEC_MSPU_TOP_FLUSH_MACSEC_BUFFERS_BUFFERS_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_MSPU_CRC_FWD_MODE_TYPE;
#define MACSEC_MSPU_TOP_MSPU_CRC_FWD_MODE_SHORT_PACK_PAD_EN_MASK (0x2UL)
#define MACSEC_MSPU_TOP_MSPU_CRC_FWD_MODE_SHORT_PACK_PAD_EN_SHIFT (1UL)
#define MACSEC_MSPU_TOP_MSPU_CRC_FWD_MODE_MSPU_CRC_FWD_MODE_MASK (0x1UL)
#define MACSEC_MSPU_TOP_MSPU_CRC_FWD_MODE_MSPU_CRC_FWD_MODE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_ME165FE_TYPE;
#define MACSEC_MSPU_TOP_ME165FE_EIP165_FLUSH_EVENT_MASK (0x10000UL)
#define MACSEC_MSPU_TOP_ME165FE_EIP165_FLUSH_EVENT_SHIFT (16UL)
#define MACSEC_MSPU_TOP_ME165FE_EIP165_FLUSH_EVENT_NUM_MASK (0xffffUL)
#define MACSEC_MSPU_TOP_ME165FE_EIP165_FLUSH_EVENT_NUM_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_ME165FCS_TYPE;
#define MACSEC_MSPU_TOP_ME165FCS_EIP165_FLUSH_STATUS_MASK (0x2UL)
#define MACSEC_MSPU_TOP_ME165FCS_EIP165_FLUSH_STATUS_SHIFT (1UL)
#define MACSEC_MSPU_TOP_ME165FCS_EIP165_FLUSH_ENABLE_MASK (0x1UL)
#define MACSEC_MSPU_TOP_ME165FCS_EIP165_FLUSH_ENABLE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR64_L_TYPE;
#define MACSEC_MSPU_TOP_GR64_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GR64_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR64_H_TYPE;
#define MACSEC_MSPU_TOP_GR64_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GR64_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR127_L_TYPE;
#define MACSEC_MSPU_TOP_GR127_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GR127_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR127_H_TYPE;
#define MACSEC_MSPU_TOP_GR127_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GR127_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR255_L_TYPE;
#define MACSEC_MSPU_TOP_GR255_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GR255_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR255_H_TYPE;
#define MACSEC_MSPU_TOP_GR255_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GR255_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR511_L_TYPE;
#define MACSEC_MSPU_TOP_GR511_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GR511_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR511_H_TYPE;
#define MACSEC_MSPU_TOP_GR511_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GR511_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR1023_L_TYPE;
#define MACSEC_MSPU_TOP_GR1023_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GR1023_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR1023_H_TYPE;
#define MACSEC_MSPU_TOP_GR1023_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GR1023_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR1518_L_TYPE;
#define MACSEC_MSPU_TOP_GR1518_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GR1518_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR1518_H_TYPE;
#define MACSEC_MSPU_TOP_GR1518_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GR1518_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRMGV_L_TYPE;
#define MACSEC_MSPU_TOP_GRMGV_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRMGV_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRMGV_H_TYPE;
#define MACSEC_MSPU_TOP_GRMGV_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRMGV_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR2047_L_TYPE;
#define MACSEC_MSPU_TOP_GR2047_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GR2047_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR2047_H_TYPE;
#define MACSEC_MSPU_TOP_GR2047_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GR2047_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR4095_L_TYPE;
#define MACSEC_MSPU_TOP_GR4095_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GR4095_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR4095_H_TYPE;
#define MACSEC_MSPU_TOP_GR4095_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GR4095_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR9216_L_TYPE;
#define MACSEC_MSPU_TOP_GR9216_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GR9216_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GR9216_H_TYPE;
#define MACSEC_MSPU_TOP_GR9216_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GR9216_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRPKT_L_TYPE;
#define MACSEC_MSPU_TOP_GRPKT_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRPKT_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRPKT_H_TYPE;
#define MACSEC_MSPU_TOP_GRPKT_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRPKT_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRUC_L_TYPE;
#define MACSEC_MSPU_TOP_GRUC_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRUC_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRUC_H_TYPE;
#define MACSEC_MSPU_TOP_GRUC_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRUC_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRMCA_L_TYPE;
#define MACSEC_MSPU_TOP_GRMCA_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRMCA_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRMCA_H_TYPE;
#define MACSEC_MSPU_TOP_GRMCA_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRMCA_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRBCA_L_TYPE;
#define MACSEC_MSPU_TOP_GRBCA_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRBCA_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRBCA_H_TYPE;
#define MACSEC_MSPU_TOP_GRBCA_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRBCA_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRFCS_L_TYPE;
#define MACSEC_MSPU_TOP_GRFCS_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRFCS_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRFCS_H_TYPE;
#define MACSEC_MSPU_TOP_GRFCS_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRFCS_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRXCF_L_TYPE;
#define MACSEC_MSPU_TOP_GRXCF_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRXCF_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRXCF_H_TYPE;
#define MACSEC_MSPU_TOP_GRXCF_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRXCF_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRXPF_L_TYPE;
#define MACSEC_MSPU_TOP_GRXPF_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRXPF_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRXPF_H_TYPE;
#define MACSEC_MSPU_TOP_GRXPF_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRXPF_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRXUO_L_TYPE;
#define MACSEC_MSPU_TOP_GRXUO_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRXUO_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRXUO_H_TYPE;
#define MACSEC_MSPU_TOP_GRXUO_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRXUO_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRALN_L_TYPE;
#define MACSEC_MSPU_TOP_GRALN_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRALN_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRALN_H_TYPE;
#define MACSEC_MSPU_TOP_GRALN_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRALN_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRPOK_L_TYPE;
#define MACSEC_MSPU_TOP_GRPOK_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRPOK_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRPOK_H_TYPE;
#define MACSEC_MSPU_TOP_GRPOK_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRPOK_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRCDE_L_TYPE;
#define MACSEC_MSPU_TOP_GRCDE_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRCDE_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRCDE_H_TYPE;
#define MACSEC_MSPU_TOP_GRCDE_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRCDE_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRFCR_L_TYPE;
#define MACSEC_MSPU_TOP_GRFCR_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRFCR_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRFCR_H_TYPE;
#define MACSEC_MSPU_TOP_GRFCR_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRFCR_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GROVR_L_TYPE;
#define MACSEC_MSPU_TOP_GROVR_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GROVR_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GROVR_H_TYPE;
#define MACSEC_MSPU_TOP_GROVR_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GROVR_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRJBR_L_TYPE;
#define MACSEC_MSPU_TOP_GRJBR_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRJBR_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRJBR_H_TYPE;
#define MACSEC_MSPU_TOP_GRJBR_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRJBR_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRMTUE_L_TYPE;
#define MACSEC_MSPU_TOP_GRMTUE_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRMTUE_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRMTUE_H_TYPE;
#define MACSEC_MSPU_TOP_GRMTUE_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRMTUE_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRCRCMATCH_L_TYPE;
#define MACSEC_MSPU_TOP_GRCRCMATCH_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRCRCMATCH_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRCRCMATCH_H_TYPE;
#define MACSEC_MSPU_TOP_GRCRCMATCH_H_GRCRCMATCH_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRCRCMATCH_H_GRCRCMATCH_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRBYT_L_TYPE;
#define MACSEC_MSPU_TOP_GRBYT_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRBYT_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRBYT_H_TYPE;
#define MACSEC_MSPU_TOP_GRBYT_H_H_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRBYT_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_RRPKT_L_TYPE;
#define MACSEC_MSPU_TOP_RRPKT_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_RRPKT_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_RRPKT_H_TYPE;
#define MACSEC_MSPU_TOP_RRPKT_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_RRPKT_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRUND_L_TYPE;
#define MACSEC_MSPU_TOP_GRUND_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRUND_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRUND_H_TYPE;
#define MACSEC_MSPU_TOP_GRUND_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRUND_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRFRG_L_TYPE;
#define MACSEC_MSPU_TOP_GRFRG_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GRFRG_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GRFRG_H_TYPE;
#define MACSEC_MSPU_TOP_GRFRG_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GRFRG_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_RRBYT_L_TYPE;
#define MACSEC_MSPU_TOP_RRBYT_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_RRBYT_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_RRBYT_H_TYPE;
#define MACSEC_MSPU_TOP_RRBYT_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_RRBYT_H_H_SHIFT (0UL)




typedef uint8_t MACSEC_MSPU_TOP_RESERVED_TYPE;




typedef uint32_t MACSEC_MSPU_TOP_GT64_L_TYPE;
#define MACSEC_MSPU_TOP_GT64_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GT64_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT64_H_TYPE;
#define MACSEC_MSPU_TOP_GT64_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GT64_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT127_L_TYPE;
#define MACSEC_MSPU_TOP_GT127_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GT127_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT127_H_TYPE;
#define MACSEC_MSPU_TOP_GT127_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GT127_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT255_L_TYPE;
#define MACSEC_MSPU_TOP_GT255_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GT255_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT255_H_TYPE;
#define MACSEC_MSPU_TOP_GT255_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GT255_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT511_L_TYPE;
#define MACSEC_MSPU_TOP_GT511_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GT511_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT511_H_TYPE;
#define MACSEC_MSPU_TOP_GT511_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GT511_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT1023_L_TYPE;
#define MACSEC_MSPU_TOP_GT1023_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GT1023_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT1023_H_TYPE;
#define MACSEC_MSPU_TOP_GT1023_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GT1023_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT1518_L_TYPE;
#define MACSEC_MSPU_TOP_GT1518_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GT1518_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT1518_H_TYPE;
#define MACSEC_MSPU_TOP_GT1518_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GT1518_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTMGV_L_TYPE;
#define MACSEC_MSPU_TOP_GTMGV_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTMGV_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTMGV_H_TYPE;
#define MACSEC_MSPU_TOP_GTMGV_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTMGV_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT2047_L_TYPE;
#define MACSEC_MSPU_TOP_GT2047_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GT2047_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT2047_H_TYPE;
#define MACSEC_MSPU_TOP_GT2047_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GT2047_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT4095_L_TYPE;
#define MACSEC_MSPU_TOP_GT4095_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GT4095_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT4095_H_TYPE;
#define MACSEC_MSPU_TOP_GT4095_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GT4095_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT9216_L_TYPE;
#define MACSEC_MSPU_TOP_GT9216_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GT9216_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GT9216_H_TYPE;
#define MACSEC_MSPU_TOP_GT9216_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GT9216_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTPKT_L_TYPE;
#define MACSEC_MSPU_TOP_GTPKT_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTPKT_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTPKT_H_TYPE;
#define MACSEC_MSPU_TOP_GTPKT_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTPKT_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTMCA_L_TYPE;
#define MACSEC_MSPU_TOP_GTMCA_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTMCA_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTMCA_H_TYPE;
#define MACSEC_MSPU_TOP_GTMCA_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTMCA_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTBCA_L_TYPE;
#define MACSEC_MSPU_TOP_GTBCA_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTBCA_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTBCA_H_TYPE;
#define MACSEC_MSPU_TOP_GTBCA_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTBCA_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTXPF_L_TYPE;
#define MACSEC_MSPU_TOP_GTXPF_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTXPF_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTXPF_H_TYPE;
#define MACSEC_MSPU_TOP_GTXPF_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTXPF_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTJBR_L_TYPE;
#define MACSEC_MSPU_TOP_GTJBR_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTJBR_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTJBR_H_TYPE;
#define MACSEC_MSPU_TOP_GTJBR_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTJBR_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTFCS_L_TYPE;
#define MACSEC_MSPU_TOP_GTFCS_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTFCS_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTFCS_H_TYPE;
#define MACSEC_MSPU_TOP_GTFCS_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTFCS_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTXCF_L_TYPE;
#define MACSEC_MSPU_TOP_GTXCF_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTXCF_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTXCF_H_TYPE;
#define MACSEC_MSPU_TOP_GTXCF_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTXCF_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTOVR_L_TYPE;
#define MACSEC_MSPU_TOP_GTOVR_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTOVR_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTOVR_H_TYPE;
#define MACSEC_MSPU_TOP_GTOVR_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTOVR_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTUC_L_TYPE;
#define MACSEC_MSPU_TOP_GTUC_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTUC_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTUC_H_TYPE;
#define MACSEC_MSPU_TOP_GTUC_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTUC_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTPOK_L_TYPE;
#define MACSEC_MSPU_TOP_GTPOK_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTPOK_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTPOK_H_TYPE;
#define MACSEC_MSPU_TOP_GTPOK_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTPOK_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTSCL_L_TYPE;
#define MACSEC_MSPU_TOP_GTSCL_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTSCL_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTSCL_H_TYPE;
#define MACSEC_MSPU_TOP_GTSCL_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTSCL_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTMCL_L_TYPE;
#define MACSEC_MSPU_TOP_GTMCL_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTMCL_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTMCL_H_TYPE;
#define MACSEC_MSPU_TOP_GTMCL_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTMCL_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTLCL_L_TYPE;
#define MACSEC_MSPU_TOP_GTLCL_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTLCL_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTLCL_H_TYPE;
#define MACSEC_MSPU_TOP_GTLCL_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTLCL_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTXCL_L_TYPE;
#define MACSEC_MSPU_TOP_GTXCL_L_GTXCL_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTXCL_L_GTXCL_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTXCL_H_TYPE;
#define MACSEC_MSPU_TOP_GTXCL_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTXCL_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTFRG_L_TYPE;
#define MACSEC_MSPU_TOP_GTFRG_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTFRG_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTFRG_H_TYPE;
#define MACSEC_MSPU_TOP_GTFRG_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTFRG_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTNCL_L_TYPE;
#define MACSEC_MSPU_TOP_GTNCL_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTNCL_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTNCL_H_TYPE;
#define MACSEC_MSPU_TOP_GTNCL_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTNCL_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTCRCCORRUPT_L_TYPE;
#define MACSEC_MSPU_TOP_GTCRCCORRUPT_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTCRCCORRUPT_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTCRCCORRUPT_H_TYPE;
#define MACSEC_MSPU_TOP_GTCRCCORRUPT_H_H_MASK (0xffUL)
#define MACSEC_MSPU_TOP_GTCRCCORRUPT_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTBYT_L_TYPE;
#define MACSEC_MSPU_TOP_GTBYT_L_L_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTBYT_L_L_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_GTBYT_H_TYPE;
#define MACSEC_MSPU_TOP_GTBYT_H_H_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_GTBYT_H_H_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_R1CUE_TYPE;
#define MACSEC_MSPU_TOP_R1CUE_RSC_1PORT_COUNTER_UPDATE_ENABLE_MASK (0x7fffffffUL)
#define MACSEC_MSPU_TOP_R1CUE_RSC_1PORT_COUNTER_UPDATE_ENABLE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_T1CUE_TYPE;
#define MACSEC_MSPU_TOP_T1CUE_TSC_1PORT_COUNTER_UPDATE_ENABLE_MASK (0xfffffffUL)
#define MACSEC_MSPU_TOP_T1CUE_TSC_1PORT_COUNTER_UPDATE_ENABLE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_SAF_MEM_TEST_MODE_TYPE;
#define MACSEC_MSPU_TOP_SAF_MEM_TEST_MODE_TM_MASK (0x3ffUL)
#define MACSEC_MSPU_TOP_SAF_MEM_TEST_MODE_TM_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_SRF_MEM_TEST_MODE_TYPE;
#define MACSEC_MSPU_TOP_SRF_MEM_TEST_MODE_TM_MASK (0x1fUL)
#define MACSEC_MSPU_TOP_SRF_MEM_TEST_MODE_TM_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_PD_MEM_TEST_MODE_TYPE;
#define MACSEC_MSPU_TOP_PD_MEM_TEST_MODE_TM_MASK (0x3ffUL)
#define MACSEC_MSPU_TOP_PD_MEM_TEST_MODE_TM_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_SD_MEM_TEST_MODE_TYPE;
#define MACSEC_MSPU_TOP_SD_MEM_TEST_MODE_TM_MASK (0x7fUL)
#define MACSEC_MSPU_TOP_SD_MEM_TEST_MODE_TM_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_LLSSO_TYPE;
#define MACSEC_MSPU_TOP_LLSSO_LNMAC_LINK_STAT_OVRD_EN_MASK (0x1UL)
#define MACSEC_MSPU_TOP_LLSSO_LNMAC_LINK_STAT_OVRD_EN_SHIFT (0UL)
#define MACSEC_MSPU_TOP_LLSSO_LNMAC_LINK_STAT_OVRD_VAL_MASK (0x2UL)
#define MACSEC_MSPU_TOP_LLSSO_LNMAC_LINK_STAT_OVRD_VAL_SHIFT (1UL)
#define MACSEC_MSPU_TOP_LLSSO_LNMAC_SPEED_OVRD_EN_MASK (0x4UL)
#define MACSEC_MSPU_TOP_LLSSO_LNMAC_SPEED_OVRD_EN_SHIFT (2UL)
#define MACSEC_MSPU_TOP_LLSSO_LNMAC_SPEED_OVRD_VAL_MASK (0x18UL)
#define MACSEC_MSPU_TOP_LLSSO_LNMAC_SPEED_OVRD_VAL_SHIFT (3UL)




typedef uint32_t MACSEC_MSPU_TOP_SLSSO_TYPE;
#define MACSEC_MSPU_TOP_SLSSO_SWMAC_LINK_STAT_OVRD_EN_MASK (0x1UL)
#define MACSEC_MSPU_TOP_SLSSO_SWMAC_LINK_STAT_OVRD_EN_SHIFT (0UL)
#define MACSEC_MSPU_TOP_SLSSO_SWMAC_LINK_STAT_OVRD_VAL_MASK (0x2UL)
#define MACSEC_MSPU_TOP_SLSSO_SWMAC_LINK_STAT_OVRD_VAL_SHIFT (1UL)
#define MACSEC_MSPU_TOP_SLSSO_SWMAC_SPEED_OVRD_EN_MASK (0x4UL)
#define MACSEC_MSPU_TOP_SLSSO_SWMAC_SPEED_OVRD_EN_SHIFT (2UL)
#define MACSEC_MSPU_TOP_SLSSO_SWMAC_SPEED_OVRD_VAL_MASK (0x18UL)
#define MACSEC_MSPU_TOP_SLSSO_SWMAC_SPEED_OVRD_VAL_SHIFT (3UL)




typedef uint32_t MACSEC_MSPU_TOP_SPARE0_TYPE;
#define MACSEC_MSPU_TOP_SPARE0_SPARE_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_SPARE0_SPARE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_SPARE1_TYPE;
#define MACSEC_MSPU_TOP_SPARE1_SPARE_MASK (0xffffffffUL)
#define MACSEC_MSPU_TOP_SPARE1_SPARE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_INGSAF_WM_STAT_TYPE;
#define MACSEC_MSPU_TOP_INGSAF_WM_STAT_RESERVED_MASK (0xfffffff0UL)
#define MACSEC_MSPU_TOP_INGSAF_WM_STAT_RESERVED_SHIFT (4UL)
#define MACSEC_MSPU_TOP_INGSAF_WM_STAT_INGRESS_SAF_BP_EVENT_MASK (0x8UL)
#define MACSEC_MSPU_TOP_INGSAF_WM_STAT_INGRESS_SAF_BP_EVENT_SHIFT (3UL)
#define MACSEC_MSPU_TOP_INGSAF_WM_STAT_INGRESS_SAF_BP_MASK (0x4UL)
#define MACSEC_MSPU_TOP_INGSAF_WM_STAT_INGRESS_SAF_BP_SHIFT (2UL)
#define MACSEC_MSPU_TOP_INGSAF_WM_STAT_INGRESS_SAF_HWM_MASK (0x2UL)
#define MACSEC_MSPU_TOP_INGSAF_WM_STAT_INGRESS_SAF_HWM_SHIFT (1UL)
#define MACSEC_MSPU_TOP_INGSAF_WM_STAT_INGRESS_SAF_LWM_MASK (0x1UL)
#define MACSEC_MSPU_TOP_INGSAF_WM_STAT_INGRESS_SAF_LWM_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_EGSAF_WM_STAT_TYPE;
#define MACSEC_MSPU_TOP_EGSAF_WM_STAT_RESERVED_MASK (0xfffffff0UL)
#define MACSEC_MSPU_TOP_EGSAF_WM_STAT_RESERVED_SHIFT (4UL)
#define MACSEC_MSPU_TOP_EGSAF_WM_STAT_EGRESS_SAF_BP_EVENT_MASK (0x8UL)
#define MACSEC_MSPU_TOP_EGSAF_WM_STAT_EGRESS_SAF_BP_EVENT_SHIFT (3UL)
#define MACSEC_MSPU_TOP_EGSAF_WM_STAT_EGRESS_SAF_BP_MASK (0x4UL)
#define MACSEC_MSPU_TOP_EGSAF_WM_STAT_EGRESS_SAF_BP_SHIFT (2UL)
#define MACSEC_MSPU_TOP_EGSAF_WM_STAT_EGRESS_SAF_HWM_MASK (0x2UL)
#define MACSEC_MSPU_TOP_EGSAF_WM_STAT_EGRESS_SAF_HWM_SHIFT (1UL)
#define MACSEC_MSPU_TOP_EGSAF_WM_STAT_EGRESS_SAF_LWM_MASK (0x1UL)
#define MACSEC_MSPU_TOP_EGSAF_WM_STAT_EGRESS_SAF_LWM_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_TYPE;
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_PP_NUM_PACKET_MASK (0xffff0000UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_PP_NUM_PACKET_SHIFT (16UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_RESERVED_MASK (0xffc0UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_RESERVED_SHIFT (6UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_CONT_COUNT_CLR_MASK (0x20UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_CONT_COUNT_CLR_SHIFT (5UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_START_CONT_LN_MASK (0x10UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_START_CONT_LN_SHIFT (4UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_PP_LAUNCH_EN_MASK (0x8UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_PP_LAUNCH_EN_SHIFT (3UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_LAUNCH_MODE_MASK (0x4UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_LAUNCH_MODE_SHIFT (2UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_PP_FIXEDLAT_EN_MASK (0x2UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_PP_FIXEDLAT_EN_SHIFT (1UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_PP_DEBUG_EN_MASK (0x1UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_PP_DEBUG_EN_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_STAT_TYPE;
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_STAT_NUM_PKT_SENT_MASK (0xffff0000UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_STAT_NUM_PKT_SENT_SHIFT (16UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_STAT_RESERVED_MASK (0xfffeUL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_STAT_RESERVED_SHIFT (1UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_STAT_ALL_PKT_DONE_MASK (0x1UL)
#define MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_STAT_ALL_PKT_DONE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_CONT_LNMAC_LAUNCH_STAT_TYPE;
#define MACSEC_MSPU_TOP_CONT_LNMAC_LAUNCH_STAT_RESERVED_MASK (0xffff0000UL)
#define MACSEC_MSPU_TOP_CONT_LNMAC_LAUNCH_STAT_RESERVED_SHIFT (16UL)
#define MACSEC_MSPU_TOP_CONT_LNMAC_LAUNCH_STAT_NUM_PKT_SENT_MASK (0xffffUL)
#define MACSEC_MSPU_TOP_CONT_LNMAC_LAUNCH_STAT_NUM_PKT_SENT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_TYPE;
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_PP_NUM_PACKET_MASK (0xffff0000UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_PP_NUM_PACKET_SHIFT (16UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_RESERVED_MASK (0xffc0UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_RESERVED_SHIFT (6UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_CONT_COUNT_CLR_MASK (0x20UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_CONT_COUNT_CLR_SHIFT (5UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_START_CONT_LN_MASK (0x10UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_START_CONT_LN_SHIFT (4UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_PP_LAUNCH_EN_MASK (0x8UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_PP_LAUNCH_EN_SHIFT (3UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_LAUNCH_MODE_MASK (0x4UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_LAUNCH_MODE_SHIFT (2UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_PP_FIXEDLAT_EN_MASK (0x2UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_PP_FIXEDLAT_EN_SHIFT (1UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_PP_DEBUG_EN_MASK (0x1UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_PP_DEBUG_EN_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_STAT_TYPE;
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_STAT_NUM_PKT_SENT_MASK (0xffff0000UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_STAT_NUM_PKT_SENT_SHIFT (16UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_STAT_RESERVED_MASK (0xfffeUL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_STAT_RESERVED_SHIFT (1UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_STAT_ALL_PKT_DONE_MASK (0x1UL)
#define MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_STAT_ALL_PKT_DONE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_CONT_SWMAC_LAUNCH_STAT_TYPE;
#define MACSEC_MSPU_TOP_CONT_SWMAC_LAUNCH_STAT_RESERVED_MASK (0xffff0000UL)
#define MACSEC_MSPU_TOP_CONT_SWMAC_LAUNCH_STAT_RESERVED_SHIFT (16UL)
#define MACSEC_MSPU_TOP_CONT_SWMAC_LAUNCH_STAT_NUM_PKT_SENT_MASK (0xffffUL)
#define MACSEC_MSPU_TOP_CONT_SWMAC_LAUNCH_STAT_NUM_PKT_SENT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_PFC_FAST_FORWARD_TYPE;
#define MACSEC_MSPU_TOP_PFC_FAST_FORWARD_RESERVED_MASK (0xfffffff0UL)
#define MACSEC_MSPU_TOP_PFC_FAST_FORWARD_RESERVED_SHIFT (4UL)
#define MACSEC_MSPU_TOP_PFC_FAST_FORWARD_EGRESS_FORCE_XON_MASK (0x8UL)
#define MACSEC_MSPU_TOP_PFC_FAST_FORWARD_EGRESS_FORCE_XON_SHIFT (3UL)
#define MACSEC_MSPU_TOP_PFC_FAST_FORWARD_EGRESS_PFC_EN_MASK (0x4UL)
#define MACSEC_MSPU_TOP_PFC_FAST_FORWARD_EGRESS_PFC_EN_SHIFT (2UL)
#define MACSEC_MSPU_TOP_PFC_FAST_FORWARD_INGRESS_FORCE_XON_MASK (0x2UL)
#define MACSEC_MSPU_TOP_PFC_FAST_FORWARD_INGRESS_FORCE_XON_SHIFT (1UL)
#define MACSEC_MSPU_TOP_PFC_FAST_FORWARD_INGRESS_PFC_EN_MASK (0x1UL)
#define MACSEC_MSPU_TOP_PFC_FAST_FORWARD_INGRESS_PFC_EN_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_RBUS_TCM_TIMEOUT_TYPE;
#define MACSEC_MSPU_TOP_RBUS_TCM_TIMEOUT_VALUE_MASK (0xffffUL)
#define MACSEC_MSPU_TOP_RBUS_TCM_TIMEOUT_VALUE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_EGRESS_TS_DELAY_TYPE;
#define MACSEC_MSPU_TOP_EGRESS_TS_DELAY_SW2LNMAC_DELAY_MASK (0xffffUL)
#define MACSEC_MSPU_TOP_EGRESS_TS_DELAY_SW2LNMAC_DELAY_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_INGRESS_TS_DELAY_TYPE;
#define MACSEC_MSPU_TOP_INGRESS_TS_DELAY_LN2SWMAC_DELAY_MASK (0xffffUL)
#define MACSEC_MSPU_TOP_INGRESS_TS_DELAY_LN2SWMAC_DELAY_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_SW_MIB_CTRL_TYPE;
#define MACSEC_MSPU_TOP_SW_MIB_CTRL_CNT_SATURATE_DIS_MASK (0x4UL)
#define MACSEC_MSPU_TOP_SW_MIB_CTRL_CNT_SATURATE_DIS_SHIFT (2UL)
#define MACSEC_MSPU_TOP_SW_MIB_CTRL_CNT_RD_CLR_DIS_MASK (0x2UL)
#define MACSEC_MSPU_TOP_SW_MIB_CTRL_CNT_RD_CLR_DIS_SHIFT (1UL)
#define MACSEC_MSPU_TOP_SW_MIB_CTRL_CLR_MIB_CNT_MASK (0x1UL)
#define MACSEC_MSPU_TOP_SW_MIB_CTRL_CLR_MIB_CNT_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_SW_MIB_CNTMAXSIZE_TYPE;
#define MACSEC_MSPU_TOP_SW_MIB_CNTMAXSIZE_R_GPORT_CNTMAXSIZE_MASK (0x3fffUL)
#define MACSEC_MSPU_TOP_SW_MIB_CNTMAXSIZE_R_GPORT_CNTMAXSIZE_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_INTERRUPT_STATUS3_TYPE;
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_0_MASK (0x1UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_0_SHIFT (0UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_1_MASK (0x2UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_1_SHIFT (1UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_2_MASK (0x4UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_2_SHIFT (2UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_3_MASK (0x8UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_3_SHIFT (3UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_4_MASK (0x10UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_4_SHIFT (4UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_5_MASK (0x20UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_5_SHIFT (5UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_6_MASK (0x40UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_6_SHIFT (6UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_7_MASK (0x80UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_7_SHIFT (7UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_8_MASK (0x100UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_8_SHIFT (8UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_9_MASK (0x200UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_9_SHIFT (9UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_10_MASK (0x400UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_10_SHIFT (10UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_11_MASK (0x800UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_11_SHIFT (11UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_12_MASK (0x1000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_12_SHIFT (12UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_13_MASK (0x2000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_13_SHIFT (13UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_14_MASK (0x4000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_14_SHIFT (14UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_15_MASK (0x8000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_15_SHIFT (15UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_16_MASK (0x10000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_16_SHIFT (16UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_17_MASK (0x20000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_17_SHIFT (17UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_18_MASK (0x40000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_18_SHIFT (18UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_19_MASK (0x80000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_19_SHIFT (19UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_20_MASK (0x100000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_20_SHIFT (20UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_21_MASK (0x200000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_21_SHIFT (21UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_22_MASK (0x400000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_22_SHIFT (22UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_23_MASK (0x800000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_23_SHIFT (23UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_24_MASK (0x1000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_24_SHIFT (24UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_25_MASK (0x2000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_25_SHIFT (25UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_26_MASK (0x4000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_26_SHIFT (26UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_27_MASK (0x8000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_27_SHIFT (27UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_28_MASK (0x10000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_28_SHIFT (28UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_29_MASK (0x20000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_29_SHIFT (29UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_30_MASK (0x40000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS3_30_SHIFT (30UL)




typedef uint32_t MACSEC_MSPU_TOP_INTERRUPT_STATUS4_TYPE;
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_0_MASK (0x1UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_0_SHIFT (0UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_1_MASK (0x2UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_1_SHIFT (1UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_2_MASK (0x4UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_2_SHIFT (2UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_3_MASK (0x8UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_3_SHIFT (3UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_4_MASK (0x10UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_4_SHIFT (4UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_5_MASK (0x20UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_5_SHIFT (5UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_6_MASK (0x40UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_6_SHIFT (6UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_7_MASK (0x80UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_7_SHIFT (7UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_8_MASK (0x100UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_8_SHIFT (8UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_9_MASK (0x200UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_9_SHIFT (9UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_10_MASK (0x400UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_10_SHIFT (10UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_11_MASK (0x800UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_11_SHIFT (11UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_12_MASK (0x1000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_12_SHIFT (12UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_13_MASK (0x2000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_13_SHIFT (13UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_14_MASK (0x4000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_14_SHIFT (14UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_15_MASK (0x8000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_15_SHIFT (15UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_16_MASK (0x10000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_16_SHIFT (16UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_17_MASK (0x20000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_17_SHIFT (17UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_18_MASK (0x40000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_18_SHIFT (18UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_19_MASK (0x80000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_19_SHIFT (19UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_20_MASK (0x100000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_20_SHIFT (20UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_21_MASK (0x200000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_21_SHIFT (21UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_22_MASK (0x400000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_22_SHIFT (22UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_23_MASK (0x800000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_23_SHIFT (23UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_24_MASK (0x1000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_24_SHIFT (24UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_25_MASK (0x2000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_25_SHIFT (25UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_26_MASK (0x4000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_26_SHIFT (26UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_27_MASK (0x8000000UL)
#define MACSEC_MSPU_TOP_INTERRUPT_STATUS4_27_SHIFT (27UL)




typedef uint32_t MACSEC_MSPU_TOP_INTERRUPT_ENABLE3_TYPE;
#define MACSEC_MSPU_TOP_INTERRUPT_ENABLE3_ENABLE3_MASK (0x7fffffffUL)
#define MACSEC_MSPU_TOP_INTERRUPT_ENABLE3_ENABLE3_SHIFT (0UL)




typedef uint32_t MACSEC_MSPU_TOP_INTERRUPT_ENABLE4_TYPE;
#define MACSEC_MSPU_TOP_INTERRUPT_ENABLE4_ENABLE4_MASK (0xfffffffUL)
#define MACSEC_MSPU_TOP_INTERRUPT_ENABLE4_ENABLE4_SHIFT (0UL)




typedef volatile struct COMP_PACKED sMACSEC_MSPU_TOP_RDBType {
    MACSEC_MSPU_TOP_MIB_CTRL_TYPE mib_ctrl; /* OFFSET: 0x0 */
    MACSEC_MSPU_TOP_MIB_CNTMAXSIZE_TYPE mib_cntmaxsize; /* OFFSET: 0x4 */
    MACSEC_MSPU_TOP_LNMAC_R_GPORT_RSV_MASK_TYPE lnmac_r_gport_rsv_mask; /* OFFSET: 0x8 */
    MACSEC_MSPU_TOP_SWMAC_R_GPORT_RSV_MASK_TYPE swmac_r_gport_rsv_mask; /* OFFSET: 0xc */
    MACSEC_MSPU_TOP_LRGSUM_TYPE lnmac_r_gport_stat_update_mask; /* OFFSET: 0x10 */
    MACSEC_MSPU_TOP_SRGSUM_TYPE swmac_r_gport_stat_update_mask; /* OFFSET: 0x14 */
    MACSEC_MSPU_TOP_INTERRUPT_STATUS0_TYPE interrupt_status0; /* OFFSET: 0x18 */
    MACSEC_MSPU_TOP_INTERRUPT_STATUS1_TYPE interrupt_status1; /* OFFSET: 0x1c */
    MACSEC_MSPU_TOP_INTERRUPT_STATUS2_TYPE interrupt_status2; /* OFFSET: 0x20 */
    MACSEC_MSPU_TOP_INTERRUPT_ENABLE0_TYPE interrupt_enable0; /* OFFSET: 0x24 */
    MACSEC_MSPU_TOP_INTERRUPT_ENABLE1_TYPE interrupt_enable1; /* OFFSET: 0x28 */
    MACSEC_MSPU_TOP_INTERRUPT_ENABLE2_TYPE interrupt_enable2; /* OFFSET: 0x2c */
    MACSEC_MSPU_TOP_FLUSH_MACSEC_BUFFERS_TYPE flush_macsec_buffers; /* OFFSET: 0x30 */
    MACSEC_MSPU_TOP_MSPU_CRC_FWD_MODE_TYPE mspu_crc_fwd_mode; /* OFFSET: 0x34 */
    MACSEC_MSPU_TOP_ME165FE_TYPE mspu_eip165_flush_event; /* OFFSET: 0x38 */
    MACSEC_MSPU_TOP_ME165FCS_TYPE mspu_eip165_flush_ctrl_status; /* OFFSET: 0x3c */
    MACSEC_MSPU_TOP_GR64_L_TYPE gr64_l; /* OFFSET: 0x40 */
    MACSEC_MSPU_TOP_GR64_H_TYPE gr64_h; /* OFFSET: 0x44 */
    MACSEC_MSPU_TOP_GR127_L_TYPE gr127_l; /* OFFSET: 0x48 */
    MACSEC_MSPU_TOP_GR127_H_TYPE gr127_h; /* OFFSET: 0x4c */
    MACSEC_MSPU_TOP_GR255_L_TYPE gr255_l; /* OFFSET: 0x50 */
    MACSEC_MSPU_TOP_GR255_H_TYPE gr255_h; /* OFFSET: 0x54 */
    MACSEC_MSPU_TOP_GR511_L_TYPE gr511_l; /* OFFSET: 0x58 */
    MACSEC_MSPU_TOP_GR511_H_TYPE gr511_h; /* OFFSET: 0x5c */
    MACSEC_MSPU_TOP_GR1023_L_TYPE gr1023_l; /* OFFSET: 0x60 */
    MACSEC_MSPU_TOP_GR1023_H_TYPE gr1023_h; /* OFFSET: 0x64 */
    MACSEC_MSPU_TOP_GR1518_L_TYPE gr1518_l; /* OFFSET: 0x68 */
    MACSEC_MSPU_TOP_GR1518_H_TYPE gr1518_h; /* OFFSET: 0x6c */
    MACSEC_MSPU_TOP_GRMGV_L_TYPE grmgv_l; /* OFFSET: 0x70 */
    MACSEC_MSPU_TOP_GRMGV_H_TYPE grmgv_h; /* OFFSET: 0x74 */
    MACSEC_MSPU_TOP_GR2047_L_TYPE gr2047_l; /* OFFSET: 0x78 */
    MACSEC_MSPU_TOP_GR2047_H_TYPE gr2047_h; /* OFFSET: 0x7c */
    MACSEC_MSPU_TOP_GR4095_L_TYPE gr4095_l; /* OFFSET: 0x80 */
    MACSEC_MSPU_TOP_GR4095_H_TYPE gr4095_h; /* OFFSET: 0x84 */
    MACSEC_MSPU_TOP_GR9216_L_TYPE gr9216_l; /* OFFSET: 0x88 */
    MACSEC_MSPU_TOP_GR9216_H_TYPE gr9216_h; /* OFFSET: 0x8c */
    MACSEC_MSPU_TOP_GRPKT_L_TYPE grpkt_l; /* OFFSET: 0x90 */
    MACSEC_MSPU_TOP_GRPKT_H_TYPE grpkt_h; /* OFFSET: 0x94 */
    MACSEC_MSPU_TOP_GRUC_L_TYPE gruc_l; /* OFFSET: 0x98 */
    MACSEC_MSPU_TOP_GRUC_H_TYPE gruc_h; /* OFFSET: 0x9c */
    MACSEC_MSPU_TOP_GRMCA_L_TYPE grmca_l; /* OFFSET: 0xa0 */
    MACSEC_MSPU_TOP_GRMCA_H_TYPE grmca_h; /* OFFSET: 0xa4 */
    MACSEC_MSPU_TOP_GRBCA_L_TYPE grbca_l; /* OFFSET: 0xa8 */
    MACSEC_MSPU_TOP_GRBCA_H_TYPE grbca_h; /* OFFSET: 0xac */
    MACSEC_MSPU_TOP_GRFCS_L_TYPE grfcs_l; /* OFFSET: 0xb0 */
    MACSEC_MSPU_TOP_GRFCS_H_TYPE grfcs_h; /* OFFSET: 0xb4 */
    MACSEC_MSPU_TOP_GRXCF_L_TYPE grxcf_l; /* OFFSET: 0xb8 */
    MACSEC_MSPU_TOP_GRXCF_H_TYPE grxcf_h; /* OFFSET: 0xbc */
    MACSEC_MSPU_TOP_GRXPF_L_TYPE grxpf_l; /* OFFSET: 0xc0 */
    MACSEC_MSPU_TOP_GRXPF_H_TYPE grxpf_h; /* OFFSET: 0xc4 */
    MACSEC_MSPU_TOP_GRXUO_L_TYPE grxuo_l; /* OFFSET: 0xc8 */
    MACSEC_MSPU_TOP_GRXUO_H_TYPE grxuo_h; /* OFFSET: 0xcc */
    MACSEC_MSPU_TOP_GRALN_L_TYPE graln_l; /* OFFSET: 0xd0 */
    MACSEC_MSPU_TOP_GRALN_H_TYPE graln_h; /* OFFSET: 0xd4 */
    MACSEC_MSPU_TOP_GRPOK_L_TYPE grpok_l; /* OFFSET: 0xd8 */
    MACSEC_MSPU_TOP_GRPOK_H_TYPE grpok_h; /* OFFSET: 0xdc */
    MACSEC_MSPU_TOP_GRCDE_L_TYPE grcde_l; /* OFFSET: 0xe0 */
    MACSEC_MSPU_TOP_GRCDE_H_TYPE grcde_h; /* OFFSET: 0xe4 */
    MACSEC_MSPU_TOP_GRFCR_L_TYPE grfcr_l; /* OFFSET: 0xe8 */
    MACSEC_MSPU_TOP_GRFCR_H_TYPE grfcr_h; /* OFFSET: 0xec */
    MACSEC_MSPU_TOP_GROVR_L_TYPE grovr_l; /* OFFSET: 0xf0 */
    MACSEC_MSPU_TOP_GROVR_H_TYPE grovr_h; /* OFFSET: 0xf4 */
    MACSEC_MSPU_TOP_GRJBR_L_TYPE grjbr_l; /* OFFSET: 0xf8 */
    MACSEC_MSPU_TOP_GRJBR_H_TYPE grjbr_h; /* OFFSET: 0xfc */
    MACSEC_MSPU_TOP_GRMTUE_L_TYPE grmtue_l; /* OFFSET: 0x100 */
    MACSEC_MSPU_TOP_GRMTUE_H_TYPE grmtue_h; /* OFFSET: 0x104 */
    MACSEC_MSPU_TOP_GRCRCMATCH_L_TYPE grcrcmatch_l; /* OFFSET: 0x108 */
    MACSEC_MSPU_TOP_GRCRCMATCH_H_TYPE grcrcmatch_h; /* OFFSET: 0x10c */
    MACSEC_MSPU_TOP_GRBYT_L_TYPE grbyt_l; /* OFFSET: 0x110 */
    MACSEC_MSPU_TOP_GRBYT_H_TYPE grbyt_h; /* OFFSET: 0x114 */
    MACSEC_MSPU_TOP_RRPKT_L_TYPE rrpkt_l; /* OFFSET: 0x118 */
    MACSEC_MSPU_TOP_RRPKT_H_TYPE rrpkt_h; /* OFFSET: 0x11c */
    MACSEC_MSPU_TOP_GRUND_L_TYPE grund_l; /* OFFSET: 0x120 */
    MACSEC_MSPU_TOP_GRUND_H_TYPE grund_h; /* OFFSET: 0x124 */
    MACSEC_MSPU_TOP_GRFRG_L_TYPE grfrg_l; /* OFFSET: 0x128 */
    MACSEC_MSPU_TOP_GRFRG_H_TYPE grfrg_h; /* OFFSET: 0x12c */
    MACSEC_MSPU_TOP_RRBYT_L_TYPE rrbyt_l; /* OFFSET: 0x130 */
    MACSEC_MSPU_TOP_RRBYT_H_TYPE rrbyt_h; /* OFFSET: 0x134 */
    MACSEC_MSPU_TOP_RESERVED_TYPE rsvd0[264]; /* OFFSET: 0x138 */
    MACSEC_MSPU_TOP_GT64_L_TYPE gt64_l; /* OFFSET: 0x240 */
    MACSEC_MSPU_TOP_GT64_H_TYPE gt64_h; /* OFFSET: 0x244 */
    MACSEC_MSPU_TOP_GT127_L_TYPE gt127_l; /* OFFSET: 0x248 */
    MACSEC_MSPU_TOP_GT127_H_TYPE gt127_h; /* OFFSET: 0x24c */
    MACSEC_MSPU_TOP_GT255_L_TYPE gt255_l; /* OFFSET: 0x250 */
    MACSEC_MSPU_TOP_GT255_H_TYPE gt255_h; /* OFFSET: 0x254 */
    MACSEC_MSPU_TOP_GT511_L_TYPE gt511_l; /* OFFSET: 0x258 */
    MACSEC_MSPU_TOP_GT511_H_TYPE gt511_h; /* OFFSET: 0x25c */
    MACSEC_MSPU_TOP_GT1023_L_TYPE gt1023_l; /* OFFSET: 0x260 */
    MACSEC_MSPU_TOP_GT1023_H_TYPE gt1023_h; /* OFFSET: 0x264 */
    MACSEC_MSPU_TOP_GT1518_L_TYPE gt1518_l; /* OFFSET: 0x268 */
    MACSEC_MSPU_TOP_GT1518_H_TYPE gt1518_h; /* OFFSET: 0x26c */
    MACSEC_MSPU_TOP_GTMGV_L_TYPE gtmgv_l; /* OFFSET: 0x270 */
    MACSEC_MSPU_TOP_GTMGV_H_TYPE gtmgv_h; /* OFFSET: 0x274 */
    MACSEC_MSPU_TOP_GT2047_L_TYPE gt2047_l; /* OFFSET: 0x278 */
    MACSEC_MSPU_TOP_GT2047_H_TYPE gt2047_h; /* OFFSET: 0x27c */
    MACSEC_MSPU_TOP_GT4095_L_TYPE gt4095_l; /* OFFSET: 0x280 */
    MACSEC_MSPU_TOP_GT4095_H_TYPE gt4095_h; /* OFFSET: 0x284 */
    MACSEC_MSPU_TOP_GT9216_L_TYPE gt9216_l; /* OFFSET: 0x288 */
    MACSEC_MSPU_TOP_GT9216_H_TYPE gt9216_h; /* OFFSET: 0x28c */
    MACSEC_MSPU_TOP_GTPKT_L_TYPE gtpkt_l; /* OFFSET: 0x290 */
    MACSEC_MSPU_TOP_GTPKT_H_TYPE gtpkt_h; /* OFFSET: 0x294 */
    MACSEC_MSPU_TOP_GTMCA_L_TYPE gtmca_l; /* OFFSET: 0x298 */
    MACSEC_MSPU_TOP_GTMCA_H_TYPE gtmca_h; /* OFFSET: 0x29c */
    MACSEC_MSPU_TOP_GTBCA_L_TYPE gtbca_l; /* OFFSET: 0x2a0 */
    MACSEC_MSPU_TOP_GTBCA_H_TYPE gtbca_h; /* OFFSET: 0x2a4 */
    MACSEC_MSPU_TOP_GTXPF_L_TYPE gtxpf_l; /* OFFSET: 0x2a8 */
    MACSEC_MSPU_TOP_GTXPF_H_TYPE gtxpf_h; /* OFFSET: 0x2ac */
    MACSEC_MSPU_TOP_GTJBR_L_TYPE gtjbr_l; /* OFFSET: 0x2b0 */
    MACSEC_MSPU_TOP_GTJBR_H_TYPE gtjbr_h; /* OFFSET: 0x2b4 */
    MACSEC_MSPU_TOP_GTFCS_L_TYPE gtfcs_l; /* OFFSET: 0x2b8 */
    MACSEC_MSPU_TOP_GTFCS_H_TYPE gtfcs_h; /* OFFSET: 0x2bc */
    MACSEC_MSPU_TOP_GTXCF_L_TYPE gtxcf_l; /* OFFSET: 0x2c0 */
    MACSEC_MSPU_TOP_GTXCF_H_TYPE gtxcf_h; /* OFFSET: 0x2c4 */
    MACSEC_MSPU_TOP_GTOVR_L_TYPE gtovr_l; /* OFFSET: 0x2c8 */
    MACSEC_MSPU_TOP_GTOVR_H_TYPE gtovr_h; /* OFFSET: 0x2cc */
    MACSEC_MSPU_TOP_GTUC_L_TYPE gtuc_l; /* OFFSET: 0x2d0 */
    MACSEC_MSPU_TOP_GTUC_H_TYPE gtuc_h; /* OFFSET: 0x2d4 */
    MACSEC_MSPU_TOP_GTPOK_L_TYPE gtpok_l; /* OFFSET: 0x2d8 */
    MACSEC_MSPU_TOP_GTPOK_H_TYPE gtpok_h; /* OFFSET: 0x2dc */
    MACSEC_MSPU_TOP_GTSCL_L_TYPE gtscl_l; /* OFFSET: 0x2e0 */
    MACSEC_MSPU_TOP_GTSCL_H_TYPE gtscl_h; /* OFFSET: 0x2e4 */
    MACSEC_MSPU_TOP_GTMCL_L_TYPE gtmcl_l; /* OFFSET: 0x2e8 */
    MACSEC_MSPU_TOP_GTMCL_H_TYPE gtmcl_h; /* OFFSET: 0x2ec */
    MACSEC_MSPU_TOP_GTLCL_L_TYPE gtlcl_l; /* OFFSET: 0x2f0 */
    MACSEC_MSPU_TOP_GTLCL_H_TYPE gtlcl_h; /* OFFSET: 0x2f4 */
    MACSEC_MSPU_TOP_GTXCL_L_TYPE gtxcl_l; /* OFFSET: 0x2f8 */
    MACSEC_MSPU_TOP_GTXCL_H_TYPE gtxcl_h; /* OFFSET: 0x2fc */
    MACSEC_MSPU_TOP_GTFRG_L_TYPE gtfrg_l; /* OFFSET: 0x300 */
    MACSEC_MSPU_TOP_GTFRG_H_TYPE gtfrg_h; /* OFFSET: 0x304 */
    MACSEC_MSPU_TOP_GTNCL_L_TYPE gtncl_l; /* OFFSET: 0x308 */
    MACSEC_MSPU_TOP_GTNCL_H_TYPE gtncl_h; /* OFFSET: 0x30c */
    MACSEC_MSPU_TOP_GTCRCCORRUPT_L_TYPE gtcrccorrupt_l; /* OFFSET: 0x310 */
    MACSEC_MSPU_TOP_GTCRCCORRUPT_H_TYPE gtcrccorrupt_h; /* OFFSET: 0x314 */
    MACSEC_MSPU_TOP_GTBYT_L_TYPE gtbyt_l; /* OFFSET: 0x318 */
    MACSEC_MSPU_TOP_GTBYT_H_TYPE gtbyt_h; /* OFFSET: 0x31c */
    MACSEC_MSPU_TOP_R1CUE_TYPE rsc_1port_counter_update_enable; /* OFFSET: 0x320 */
    MACSEC_MSPU_TOP_T1CUE_TYPE tsc_1port_counter_update_enable; /* OFFSET: 0x324 */
    MACSEC_MSPU_TOP_SAF_MEM_TEST_MODE_TYPE saf_mem_test_mode; /* OFFSET: 0x328 */
    MACSEC_MSPU_TOP_SRF_MEM_TEST_MODE_TYPE srf_mem_test_mode; /* OFFSET: 0x32c */
    MACSEC_MSPU_TOP_PD_MEM_TEST_MODE_TYPE pd_mem_test_mode; /* OFFSET: 0x330 */
    MACSEC_MSPU_TOP_SD_MEM_TEST_MODE_TYPE sd_mem_test_mode; /* OFFSET: 0x334 */
    MACSEC_MSPU_TOP_LLSSO_TYPE lnmac_link_stat_speed_ovrd; /* OFFSET: 0x338 */
    MACSEC_MSPU_TOP_SLSSO_TYPE swmac_link_stat_speed_ovrd; /* OFFSET: 0x33c */
    MACSEC_MSPU_TOP_SPARE0_TYPE spare0; /* OFFSET: 0x340 */
    MACSEC_MSPU_TOP_SPARE1_TYPE spare1; /* OFFSET: 0x344 */
    MACSEC_MSPU_TOP_RESERVED_TYPE rsvd1[132]; /* OFFSET: 0x348 */
    MACSEC_MSPU_TOP_INGSAF_WM_STAT_TYPE ingsaf_wm_stat; /* OFFSET: 0x3cc */
    MACSEC_MSPU_TOP_EGSAF_WM_STAT_TYPE egsaf_wm_stat; /* OFFSET: 0x3d0 */
    MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_DEBUG_TYPE pp_lnmac_launch_debug; /* OFFSET: 0x3d4 */
    MACSEC_MSPU_TOP_PP_LNMAC_LAUNCH_STAT_TYPE pp_lnmac_launch_stat; /* OFFSET: 0x3d8 */
    MACSEC_MSPU_TOP_CONT_LNMAC_LAUNCH_STAT_TYPE cont_lnmac_launch_stat; /* OFFSET: 0x3dc */
    MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_DEBUG_TYPE pp_swmac_launch_debug; /* OFFSET: 0x3e0 */
    MACSEC_MSPU_TOP_PP_SWMAC_LAUNCH_STAT_TYPE pp_swmac_launch_stat; /* OFFSET: 0x3e4 */
    MACSEC_MSPU_TOP_CONT_SWMAC_LAUNCH_STAT_TYPE cont_swmac_launch_stat; /* OFFSET: 0x3e8 */
    MACSEC_MSPU_TOP_RESERVED_TYPE rsvd2[4]; /* OFFSET: 0x3ec */
    MACSEC_MSPU_TOP_PFC_FAST_FORWARD_TYPE pfc_fast_forward; /* OFFSET: 0x3f0 */
    MACSEC_MSPU_TOP_RBUS_TCM_TIMEOUT_TYPE rbus_tcm_timeout; /* OFFSET: 0x3f4 */
    MACSEC_MSPU_TOP_EGRESS_TS_DELAY_TYPE egress_ts_delay; /* OFFSET: 0x3f8 */
    MACSEC_MSPU_TOP_INGRESS_TS_DELAY_TYPE ingress_ts_delay; /* OFFSET: 0x3fc */
    MACSEC_MSPU_TOP_SW_MIB_CTRL_TYPE sw_mib_ctrl; /* OFFSET: 0x400 */
    MACSEC_MSPU_TOP_SW_MIB_CNTMAXSIZE_TYPE sw_mib_cntmaxsize; /* OFFSET: 0x404 */
    MACSEC_MSPU_TOP_RESERVED_TYPE rsvd3[16]; /* OFFSET: 0x408 */
    MACSEC_MSPU_TOP_INTERRUPT_STATUS3_TYPE interrupt_status3; /* OFFSET: 0x418 */
    MACSEC_MSPU_TOP_INTERRUPT_STATUS4_TYPE interrupt_status4; /* OFFSET: 0x41c */
    MACSEC_MSPU_TOP_RESERVED_TYPE rsvd4[4]; /* OFFSET: 0x420 */
    MACSEC_MSPU_TOP_INTERRUPT_ENABLE3_TYPE interrupt_enable3; /* OFFSET: 0x424 */
    MACSEC_MSPU_TOP_INTERRUPT_ENABLE4_TYPE interrupt_enable4; /* OFFSET: 0x428 */
    MACSEC_MSPU_TOP_RESERVED_TYPE rsvd5[20]; /* OFFSET: 0x42c */
    MACSEC_MSPU_TOP_GR64_L_TYPE sw_gr64_l; /* OFFSET: 0x440 */
    MACSEC_MSPU_TOP_GR64_H_TYPE sw_gr64_h; /* OFFSET: 0x444 */
    MACSEC_MSPU_TOP_GR127_L_TYPE sw_gr127_l; /* OFFSET: 0x448 */
    MACSEC_MSPU_TOP_GR127_H_TYPE sw_gr127_h; /* OFFSET: 0x44c */
    MACSEC_MSPU_TOP_GR255_L_TYPE sw_gr255_l; /* OFFSET: 0x450 */
    MACSEC_MSPU_TOP_GR255_H_TYPE sw_gr255_h; /* OFFSET: 0x454 */
    MACSEC_MSPU_TOP_GR511_L_TYPE sw_gr511_l; /* OFFSET: 0x458 */
    MACSEC_MSPU_TOP_GR511_H_TYPE sw_gr511_h; /* OFFSET: 0x45c */
    MACSEC_MSPU_TOP_GR1023_L_TYPE sw_gr1023_l; /* OFFSET: 0x460 */
    MACSEC_MSPU_TOP_GR1023_H_TYPE sw_gr1023_h; /* OFFSET: 0x464 */
    MACSEC_MSPU_TOP_GR1518_L_TYPE sw_gr1518_l; /* OFFSET: 0x468 */
    MACSEC_MSPU_TOP_GR1518_H_TYPE sw_gr1518_h; /* OFFSET: 0x46c */
    MACSEC_MSPU_TOP_GRMGV_L_TYPE sw_grmgv_l; /* OFFSET: 0x470 */
    MACSEC_MSPU_TOP_GRMGV_H_TYPE sw_grmgv_h; /* OFFSET: 0x474 */
    MACSEC_MSPU_TOP_GR2047_L_TYPE sw_gr2047_l; /* OFFSET: 0x478 */
    MACSEC_MSPU_TOP_GR2047_H_TYPE sw_gr2047_h; /* OFFSET: 0x47c */
    MACSEC_MSPU_TOP_GR4095_L_TYPE sw_gr4095_l; /* OFFSET: 0x480 */
    MACSEC_MSPU_TOP_GR4095_H_TYPE sw_gr4095_h; /* OFFSET: 0x484 */
    MACSEC_MSPU_TOP_GR9216_L_TYPE sw_gr9216_l; /* OFFSET: 0x488 */
    MACSEC_MSPU_TOP_GR9216_H_TYPE sw_gr9216_h; /* OFFSET: 0x48c */
    MACSEC_MSPU_TOP_GRPKT_L_TYPE sw_grpkt_l; /* OFFSET: 0x490 */
    MACSEC_MSPU_TOP_GRPKT_H_TYPE sw_grpkt_h; /* OFFSET: 0x494 */
    MACSEC_MSPU_TOP_GRUC_L_TYPE sw_gruc_l; /* OFFSET: 0x498 */
    MACSEC_MSPU_TOP_GRUC_H_TYPE sw_gruc_h; /* OFFSET: 0x49c */
    MACSEC_MSPU_TOP_GRMCA_L_TYPE sw_grmca_l; /* OFFSET: 0x4a0 */
    MACSEC_MSPU_TOP_GRMCA_H_TYPE sw_grmca_h; /* OFFSET: 0x4a4 */
    MACSEC_MSPU_TOP_GRBCA_L_TYPE sw_grbca_l; /* OFFSET: 0x4a8 */
    MACSEC_MSPU_TOP_GRBCA_H_TYPE sw_grbca_h; /* OFFSET: 0x4ac */
    MACSEC_MSPU_TOP_GRFCS_L_TYPE sw_grfcs_l; /* OFFSET: 0x4b0 */
    MACSEC_MSPU_TOP_GRFCS_H_TYPE sw_grfcs_h; /* OFFSET: 0x4b4 */
    MACSEC_MSPU_TOP_GRXCF_L_TYPE sw_grxcf_l; /* OFFSET: 0x4b8 */
    MACSEC_MSPU_TOP_GRXCF_H_TYPE sw_grxcf_h; /* OFFSET: 0x4bc */
    MACSEC_MSPU_TOP_GRXPF_L_TYPE sw_grxpf_l; /* OFFSET: 0x4c0 */
    MACSEC_MSPU_TOP_GRXPF_H_TYPE sw_grxpf_h; /* OFFSET: 0x4c4 */
    MACSEC_MSPU_TOP_GRXUO_L_TYPE sw_grxuo_l; /* OFFSET: 0x4c8 */
    MACSEC_MSPU_TOP_GRXUO_H_TYPE sw_grxuo_h; /* OFFSET: 0x4cc */
    MACSEC_MSPU_TOP_GRALN_L_TYPE sw_graln_l; /* OFFSET: 0x4d0 */
    MACSEC_MSPU_TOP_GRALN_H_TYPE sw_graln_h; /* OFFSET: 0x4d4 */
    MACSEC_MSPU_TOP_GRPOK_L_TYPE sw_grpok_l; /* OFFSET: 0x4d8 */
    MACSEC_MSPU_TOP_GRPOK_H_TYPE sw_grpok_h; /* OFFSET: 0x4dc */
    MACSEC_MSPU_TOP_GRCDE_L_TYPE sw_grcde_l; /* OFFSET: 0x4e0 */
    MACSEC_MSPU_TOP_GRCDE_H_TYPE sw_grcde_h; /* OFFSET: 0x4e4 */
    MACSEC_MSPU_TOP_GRFCR_L_TYPE sw_grfcr_l; /* OFFSET: 0x4e8 */
    MACSEC_MSPU_TOP_GRFCR_H_TYPE sw_grfcr_h; /* OFFSET: 0x4ec */
    MACSEC_MSPU_TOP_GROVR_L_TYPE sw_grovr_l; /* OFFSET: 0x4f0 */
    MACSEC_MSPU_TOP_GROVR_H_TYPE sw_grovr_h; /* OFFSET: 0x4f4 */
    MACSEC_MSPU_TOP_GRJBR_L_TYPE sw_grjbr_l; /* OFFSET: 0x4f8 */
    MACSEC_MSPU_TOP_GRJBR_H_TYPE sw_grjbr_h; /* OFFSET: 0x4fc */
    MACSEC_MSPU_TOP_GRMTUE_L_TYPE sw_grmtue_l; /* OFFSET: 0x500 */
    MACSEC_MSPU_TOP_GRMTUE_H_TYPE sw_grmtue_h; /* OFFSET: 0x504 */
    MACSEC_MSPU_TOP_GRCRCMATCH_L_TYPE sw_grcrcmatch_l; /* OFFSET: 0x508 */
    MACSEC_MSPU_TOP_GRCRCMATCH_H_TYPE sw_grcrcmatch_h; /* OFFSET: 0x50c */
    MACSEC_MSPU_TOP_GRBYT_L_TYPE sw_grbyt_l; /* OFFSET: 0x510 */
    MACSEC_MSPU_TOP_GRBYT_H_TYPE sw_grbyt_h; /* OFFSET: 0x514 */
    MACSEC_MSPU_TOP_RRPKT_L_TYPE sw_rrpkt_l; /* OFFSET: 0x518 */
    MACSEC_MSPU_TOP_RRPKT_H_TYPE sw_rrpkt_h; /* OFFSET: 0x51c */
    MACSEC_MSPU_TOP_GRUND_L_TYPE sw_grund_l; /* OFFSET: 0x520 */
    MACSEC_MSPU_TOP_GRUND_H_TYPE sw_grund_h; /* OFFSET: 0x524 */
    MACSEC_MSPU_TOP_GRFRG_L_TYPE sw_grfrg_l; /* OFFSET: 0x528 */
    MACSEC_MSPU_TOP_GRFRG_H_TYPE sw_grfrg_h; /* OFFSET: 0x52c */
    MACSEC_MSPU_TOP_RRBYT_L_TYPE sw_rrbyt_l; /* OFFSET: 0x530 */
    MACSEC_MSPU_TOP_RRBYT_H_TYPE sw_rrbyt_h; /* OFFSET: 0x534 */
    MACSEC_MSPU_TOP_RESERVED_TYPE rsvd6[264]; /* OFFSET: 0x538 */
    MACSEC_MSPU_TOP_GT64_L_TYPE sw_gt64_l; /* OFFSET: 0x640 */
    MACSEC_MSPU_TOP_GT64_H_TYPE sw_gt64_h; /* OFFSET: 0x644 */
    MACSEC_MSPU_TOP_GT127_L_TYPE sw_gt127_l; /* OFFSET: 0x648 */
    MACSEC_MSPU_TOP_GT127_H_TYPE sw_gt127_h; /* OFFSET: 0x64c */
    MACSEC_MSPU_TOP_GT255_L_TYPE sw_gt255_l; /* OFFSET: 0x650 */
    MACSEC_MSPU_TOP_GT255_H_TYPE sw_gt255_h; /* OFFSET: 0x654 */
    MACSEC_MSPU_TOP_GT511_L_TYPE sw_gt511_l; /* OFFSET: 0x658 */
    MACSEC_MSPU_TOP_GT511_H_TYPE sw_gt511_h; /* OFFSET: 0x65c */
    MACSEC_MSPU_TOP_GT1023_L_TYPE sw_gt1023_l; /* OFFSET: 0x660 */
    MACSEC_MSPU_TOP_GT1023_H_TYPE sw_gt1023_h; /* OFFSET: 0x664 */
    MACSEC_MSPU_TOP_GT1518_L_TYPE sw_gt1518_l; /* OFFSET: 0x668 */
    MACSEC_MSPU_TOP_GT1518_H_TYPE sw_gt1518_h; /* OFFSET: 0x66c */
    MACSEC_MSPU_TOP_GTMGV_L_TYPE sw_gtmgv_l; /* OFFSET: 0x670 */
    MACSEC_MSPU_TOP_GTMGV_H_TYPE sw_gtmgv_h; /* OFFSET: 0x674 */
    MACSEC_MSPU_TOP_GT2047_L_TYPE sw_gt2047_l; /* OFFSET: 0x678 */
    MACSEC_MSPU_TOP_GT2047_H_TYPE sw_gt2047_h; /* OFFSET: 0x67c */
    MACSEC_MSPU_TOP_GT4095_L_TYPE sw_gt4095_l; /* OFFSET: 0x680 */
    MACSEC_MSPU_TOP_GT4095_H_TYPE sw_gt4095_h; /* OFFSET: 0x684 */
    MACSEC_MSPU_TOP_GT9216_L_TYPE sw_gt9216_l; /* OFFSET: 0x688 */
    MACSEC_MSPU_TOP_GT9216_H_TYPE sw_gt9216_h; /* OFFSET: 0x68c */
    MACSEC_MSPU_TOP_GTPKT_L_TYPE sw_gtpkt_l; /* OFFSET: 0x690 */
    MACSEC_MSPU_TOP_GTPKT_H_TYPE sw_gtpkt_h; /* OFFSET: 0x694 */
    MACSEC_MSPU_TOP_GTMCA_L_TYPE sw_gtmca_l; /* OFFSET: 0x698 */
    MACSEC_MSPU_TOP_GTMCA_H_TYPE sw_gtmca_h; /* OFFSET: 0x69c */
    MACSEC_MSPU_TOP_GTBCA_L_TYPE sw_gtbca_l; /* OFFSET: 0x6a0 */
    MACSEC_MSPU_TOP_GTBCA_H_TYPE sw_gtbca_h; /* OFFSET: 0x6a4 */
    MACSEC_MSPU_TOP_GTXPF_L_TYPE sw_gtxpf_l; /* OFFSET: 0x6a8 */
    MACSEC_MSPU_TOP_GTXPF_H_TYPE sw_gtxpf_h; /* OFFSET: 0x6ac */
    MACSEC_MSPU_TOP_GTJBR_L_TYPE sw_gtjbr_l; /* OFFSET: 0x6b0 */
    MACSEC_MSPU_TOP_GTJBR_H_TYPE sw_gtjbr_h; /* OFFSET: 0x6b4 */
    MACSEC_MSPU_TOP_GTFCS_L_TYPE sw_gtfcs_l; /* OFFSET: 0x6b8 */
    MACSEC_MSPU_TOP_GTFCS_H_TYPE sw_gtfcs_h; /* OFFSET: 0x6bc */
    MACSEC_MSPU_TOP_GTXCF_L_TYPE sw_gtxcf_l; /* OFFSET: 0x6c0 */
    MACSEC_MSPU_TOP_GTXCF_H_TYPE sw_gtxcf_h; /* OFFSET: 0x6c4 */
    MACSEC_MSPU_TOP_GTOVR_L_TYPE sw_gtovr_l; /* OFFSET: 0x6c8 */
    MACSEC_MSPU_TOP_GTOVR_H_TYPE sw_gtovr_h; /* OFFSET: 0x6cc */
    MACSEC_MSPU_TOP_GTUC_L_TYPE sw_gtuc_l; /* OFFSET: 0x6d0 */
    MACSEC_MSPU_TOP_GTUC_H_TYPE sw_gtuc_h; /* OFFSET: 0x6d4 */
    MACSEC_MSPU_TOP_GTPOK_L_TYPE sw_gtpok_l; /* OFFSET: 0x6d8 */
    MACSEC_MSPU_TOP_GTPOK_H_TYPE sw_gtpok_h; /* OFFSET: 0x6dc */
    MACSEC_MSPU_TOP_GTSCL_L_TYPE sw_gtscl_l; /* OFFSET: 0x6e0 */
    MACSEC_MSPU_TOP_GTSCL_H_TYPE sw_gtscl_h; /* OFFSET: 0x6e4 */
    MACSEC_MSPU_TOP_GTMCL_L_TYPE sw_gtmcl_l; /* OFFSET: 0x6e8 */
    MACSEC_MSPU_TOP_GTMCL_H_TYPE sw_gtmcl_h; /* OFFSET: 0x6ec */
    MACSEC_MSPU_TOP_GTLCL_L_TYPE sw_gtlcl_l; /* OFFSET: 0x6f0 */
    MACSEC_MSPU_TOP_GTLCL_H_TYPE sw_gtlcl_h; /* OFFSET: 0x6f4 */
    MACSEC_MSPU_TOP_GTXCL_L_TYPE sw_gtxcl_l; /* OFFSET: 0x6f8 */
    MACSEC_MSPU_TOP_GTXCL_H_TYPE sw_gtxcl_h; /* OFFSET: 0x6fc */
    MACSEC_MSPU_TOP_GTFRG_L_TYPE sw_gtfrg_l; /* OFFSET: 0x700 */
    MACSEC_MSPU_TOP_GTFRG_H_TYPE sw_gtfrg_h; /* OFFSET: 0x704 */
    MACSEC_MSPU_TOP_GTNCL_L_TYPE sw_gtncl_l; /* OFFSET: 0x708 */
    MACSEC_MSPU_TOP_GTNCL_H_TYPE sw_gtncl_h; /* OFFSET: 0x70c */
    MACSEC_MSPU_TOP_GTCRCCORRUPT_L_TYPE sw_gtcrccorrupt_l; /* OFFSET: 0x710 */
    MACSEC_MSPU_TOP_GTCRCCORRUPT_H_TYPE sw_gtcrccorrupt_h; /* OFFSET: 0x714 */
    MACSEC_MSPU_TOP_GTBYT_L_TYPE sw_gtbyt_l; /* OFFSET: 0x718 */
    MACSEC_MSPU_TOP_GTBYT_H_TYPE sw_gtbyt_h; /* OFFSET: 0x71c */
    MACSEC_MSPU_TOP_R1CUE_TYPE sw_rsc_1port_counter_update_enable; /* OFFSET: 0x720 */
    MACSEC_MSPU_TOP_T1CUE_TYPE sw_tsc_1port_counter_update_enable; /* OFFSET: 0x724 */
} MACSEC_MSPU_TOP_RDBType;


#define MSPU_TOP_REGS0_BASE             (0x4D000000UL)

#define MSPU_TOP_REGS1_BASE             (0x4D100000UL)

#define MSPU_TOP_REGS2_BASE             (0x4D200000UL)

#define MSPU_TOP_REGS3_BASE             (0x4D300000UL)

#define MSPU_TOP_REGS4_BASE             (0x4D400000UL)

#define MSPU_TOP_REGS5_BASE             (0x4D500000UL)



#define MACSEC_MSPU_TOP_MAX_HW_ID       (6UL)

#endif /* MACSEC_MSPU_TOP_RDB_H */
