/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file macsec_e_scsa_map_rdb.h
    @brief RDB File for MACSEC_E_SCSA_MAP

    @version Orion_A0_20201104_SWDEV
*/

#ifndef MACSEC_E_SCSA_MAP_RDB_H
#define MACSEC_E_SCSA_MAP_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t MACSEC_E_SCSA_MAP_RESERVED_TYPE;




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_0_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_0_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_0_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_0_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_0_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_0_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_0_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_0_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_0_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_1_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_1_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_1_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_1_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_1_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_1_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_1_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_1_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_1_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_2_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_2_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_2_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_2_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_2_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_2_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_2_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_2_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_2_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_3_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_3_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_3_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_3_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_3_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_3_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_3_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_3_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_3_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_4_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_4_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_4_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_4_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_4_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_4_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_4_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_4_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_4_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_5_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_5_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_5_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_5_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_5_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_5_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_5_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_5_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_5_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_6_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_6_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_6_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_6_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_6_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_6_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_6_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_6_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_6_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_7_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_7_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_7_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_7_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_7_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_7_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_7_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_7_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_7_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_8_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_8_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_8_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_8_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_8_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_8_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_8_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_8_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_8_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_9_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_9_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_9_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_9_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_9_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_9_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_9_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_9_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_9_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_10_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_10_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_10_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_10_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_10_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_10_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_10_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_10_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_10_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_11_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_11_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_11_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_11_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_11_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_11_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_11_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_11_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_11_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_12_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_12_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_12_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_12_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_12_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_12_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_12_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_12_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_12_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_13_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_13_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_13_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_13_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_13_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_13_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_13_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_13_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_13_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_14_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_14_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_14_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_14_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_14_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_14_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_14_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_14_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_14_SA_IN_USE0_SHIFT (15UL)




typedef uint32_t MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_15_TYPE;
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_15_SA_INDEX0_MASK (0x1fUL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_15_SA_INDEX0_SHIFT (0UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_15_SA_INDEX_UPDATE0_MASK (0x2000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_15_SA_INDEX_UPDATE0_SHIFT (13UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_15_UPDATE_TIME0_MASK (0x4000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_15_UPDATE_TIME0_SHIFT (14UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_15_SA_IN_USE0_MASK (0x8000UL)
#define MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_15_SA_IN_USE0_SHIFT (15UL)


typedef volatile struct COMP_PACKED sMACSEC_E_SCSA_MAP_SCMapRDBType {
    MACSEC_E_SCSA_MAP_SAM_SC_SA_MAP1_0_TYPE m0; /* OFFSET: 0x13800 */
    MACSEC_E_SCSA_MAP_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x13804 */
} MACSEC_E_SCSA_MAP_SCMapRDBType;


#define MACSEC_E_SCSA_MAP_SCSAMAP_REGS_SIZE  (16UL)


typedef volatile struct COMP_PACKED sMACSEC_E_SCSA_MAP_RDBType {
    MACSEC_E_SCSA_MAP_RESERVED_TYPE rsvd0[79872]; /* OFFSET: 0x0 */
    MACSEC_E_SCSA_MAP_SCMapRDBType scsamap_regs[MACSEC_E_SCSA_MAP_SCSAMAP_REGS_SIZE]; /* OFFSET: 0x13800 */
} MACSEC_E_SCSA_MAP_RDBType;


#define EIP_160S_E_32_BRCM_SC_SA_MAP0_BASE  (0x4D010000UL)

#define MACSEC_E_SCSA_MAP_SCMAPRDBTYPE_EIP_160S_E_32_BRCM_SC_SA_MAP0_OFFSET  (0x4d023800UL)

#define EIP_160S_E_32_BRCM_SC_SA_MAP1_BASE  (0x4D110000UL)

#define MACSEC_E_SCSA_MAP_SCMAPRDBTYPE_EIP_160S_E_32_BRCM_SC_SA_MAP1_OFFSET  (0x4d123800UL)

#define EIP_160S_E_32_BRCM_SC_SA_MAP2_BASE  (0x4D210000UL)

#define MACSEC_E_SCSA_MAP_SCMAPRDBTYPE_EIP_160S_E_32_BRCM_SC_SA_MAP2_OFFSET  (0x4d223800UL)

#define EIP_160S_E_32_BRCM_SC_SA_MAP3_BASE  (0x4D310000UL)

#define MACSEC_E_SCSA_MAP_SCMAPRDBTYPE_EIP_160S_E_32_BRCM_SC_SA_MAP3_OFFSET  (0x4d323800UL)

#define EIP_160S_E_32_BRCM_SC_SA_MAP4_BASE  (0x4D410000UL)

#define MACSEC_E_SCSA_MAP_SCMAPRDBTYPE_EIP_160S_E_32_BRCM_SC_SA_MAP4_OFFSET  (0x4d423800UL)

#define EIP_160S_E_32_BRCM_SC_SA_MAP5_BASE  (0x4D510000UL)

#define MACSEC_E_SCSA_MAP_SCMAPRDBTYPE_EIP_160S_E_32_BRCM_SC_SA_MAP5_OFFSET  (0x4d523800UL)



#define MACSEC_E_SCSA_MAP_MAX_HW_ID     (6UL)

#endif /* MACSEC_E_SCSA_MAP_RDB_H */
