/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_tx_x1_credit_gen2_rdb.h
    @brief RDB File for SGMIIPLUSR_TX_X1_CREDIT_GEN2

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_TX_X1_CREDIT_GEN2_RDB_H
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C0SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C0SX1_REG2P5G_CLOCKCOUNT0_MASK (0x3fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C0SX1_REG2P5G_CLOCKCOUNT0_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C1SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C1SX1_REG2P5G_CGC_MASK (0x1fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C1SX1_REG2P5G_CGC_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C2SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C2SX1_REG2P5G_LOOPCNT0_MASK (0xff00U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C2SX1_REG2P5G_LOOPCNT0_SHIFT (8U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C2SX1_REG2P5G_CLOCKCOUNT1_MASK (0xffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C2SX1_REG2P5G_CLOCKCOUNT1_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C3SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C3SX1_REG2P5G_LOOPCNT1_MASK (0x3fU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C3SX1_REG2P5G_LOOPCNT1_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C0SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C0SX1_REG10G_CLOCKCOUNT0_MASK (0x3fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C0SX1_REG10G_CLOCKCOUNT0_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C1SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C1SX1_REG10G_CGC_MASK (0x1fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C1SX1_REG10G_CGC_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C2SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C2SX1_REG10G_LOOPCNT0_MASK (0xff00U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C2SX1_REG10G_LOOPCNT0_SHIFT (8U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C2SX1_REG10G_CLOCKCOUNT1_MASK (0xffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C2SX1_REG10G_CLOCKCOUNT1_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C3SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C3SX1_REG10G_LOOPCNT1_MASK (0x3fU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C3SX1_REG10G_LOOPCNT1_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_RC0SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RC0SX1_REGU_CLOC0_MASK (0x3fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RC0SX1_REGU_CLOC0_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_RPC0SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RPC0SX1_RPC0_MASK (0x3fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RPC0SX1_RPC0_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_RCSX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RCSX1_REGUSERDEFINEDSPD_CGC_MASK (0x1fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RCSX1_REGUSERDEFINEDSPD_CGC_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_RPCSX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RPCSX1_RPC_MASK (0x1fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RPCSX1_RPC_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_RC1SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RC1SX1_REGU_CLOC1_MASK (0xffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RC1SX1_REGU_CLOC1_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_RLSX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RLSX1_REGU_LOOP0_MASK (0x3fc0U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RLSX1_REGU_LOOP0_SHIFT (6U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RLSX1_REGU_LOOP1_MASK (0x3fU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_RLSX1_REGU_LOOP1_SHIFT (0U)




typedef uint8_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN2_BSX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_BSX1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_BSX1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_TX_X1_CREDIT_GEN2_RDBType {
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C0SX1_TYPE reg2p5g_credit0; /* OFFSET: 0x0 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C1SX1_TYPE reg2p5g_credit1; /* OFFSET: 0x2 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C2SX1_TYPE reg2p5g_credit2; /* OFFSET: 0x4 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_R25C3SX1_TYPE reg2p5g_credit3; /* OFFSET: 0x6 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C0SX1_TYPE reg10g_credit0; /* OFFSET: 0x8 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C1SX1_TYPE reg10g_credit1; /* OFFSET: 0xa */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C2SX1_TYPE reg10g_credit2; /* OFFSET: 0xc */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_R10C3SX1_TYPE reg10g_credit3; /* OFFSET: 0xe */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_RC0SX1_TYPE reguserdefinedspd_clockcount0; /* OFFSET: 0x10 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_RPC0SX1_TYPE reguserdefinedspd_pcs_clockcount0; /* OFFSET: 0x12 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_RCSX1_TYPE reguserdefinedspd_cgc; /* OFFSET: 0x14 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_RPCSX1_TYPE reguserdefinedspd_pcs_cgc; /* OFFSET: 0x16 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_RC1SX1_TYPE reguserdefinedspd_clockcount1; /* OFFSET: 0x18 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_RLSX1_TYPE reguserdefinedspd_loopcnt; /* OFFSET: 0x1a */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x1c */
    SGMIIPLUSR_TX_X1_CREDIT_GEN2_BSX1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_TX_X1_CREDIT_GEN2_RDBType;


#define TX_X1_CREDIT_GEN2_BASE          (0x4AED24E0UL)



#define SGMIIPLUSR_TX_X1_CREDIT_GEN2_MAX_HW_ID  (1UL)


#define SGMIIPLUSR_TX_X1_CONST11        (0x0002U)


#define SGMIIPLUSR_TX_X1_CONST12        (0x0001U)

#endif /* SGMIIPLUSR_TX_X1_CREDIT_GEN2_RDB_H */
