/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_pmdcom_rdb.h
    @brief RDB File for SGMIIPLUSR_PMDCOM

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_PMDCOM_RDB_H
#define SGMIIPLUSR_PMDCOM_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPLUSR_PMDCOM_PMD_MASKDATA_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_PMDCOM_PMD_MASKDATA_SGMIIPLUSR_X1_MASKDATA_MASK (0xffffU)
#define SGMIIPLUSR_PMDCOM_PMD_MASKDATA_SGMIIPLUSR_X1_MASKDATA_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PMDCOM_PMCSX1_TYPE;
#define SGMIIPLUSR_PMDCOM_PMCSX1_PMD_MASKDATA_BUS_ASSIGN_MASK (0x3U)
#define SGMIIPLUSR_PMDCOM_PMCSX1_PMD_MASKDATA_BUS_ASSIGN_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PMDCOM_PLOSX1_TYPE;
#define SGMIIPLUSR_PMDCOM_PLOSX1_PMD_LN_OFFSET_MASK (0x1fU)
#define SGMIIPLUSR_PMDCOM_PLOSX1_PMD_LN_OFFSET_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PMDCOM_PCSX1_TYPE;
#define SGMIIPLUSR_PMDCOM_PCSX1_TX_FORCE_COMCLK_SEL_MASK (0x80U)
#define SGMIIPLUSR_PMDCOM_PCSX1_TX_FORCE_COMCLK_SEL_SHIFT (7U)
#define SGMIIPLUSR_PMDCOM_PCSX1_RX_FORCE_COMCLK_SEL_MASK (0x40U)
#define SGMIIPLUSR_PMDCOM_PCSX1_RX_FORCE_COMCLK_SEL_SHIFT (6U)
#define SGMIIPLUSR_PMDCOM_PCSX1_TOGGLE_FRACN_SEL_MASK (0x20U)
#define SGMIIPLUSR_PMDCOM_PCSX1_TOGGLE_FRACN_SEL_SHIFT (5U)
#define SGMIIPLUSR_PMDCOM_PCSX1_PLL_BYPASS_MASK (0x10U)
#define SGMIIPLUSR_PMDCOM_PCSX1_PLL_BYPASS_SHIFT (4U)
#define SGMIIPLUSR_PMDCOM_PCSX1_PWRDN_PLL_MASK (0x8U)
#define SGMIIPLUSR_PMDCOM_PCSX1_PWRDN_PLL_SHIFT (3U)
#define SGMIIPLUSR_PMDCOM_PCSX1_PWRDN_SAFE_DIS_MASK (0x4U)
#define SGMIIPLUSR_PMDCOM_PCSX1_PWRDN_SAFE_DIS_SHIFT (2U)
#define SGMIIPLUSR_PMDCOM_PCSX1_PWRDWN_CLKS_EN_MASK (0x2U)
#define SGMIIPLUSR_PMDCOM_PCSX1_PWRDWN_CLKS_EN_SHIFT (1U)
#define SGMIIPLUSR_PMDCOM_PCSX1_RESCAL_SEL_MASK (0x1U)
#define SGMIIPLUSR_PMDCOM_PCSX1_RESCAL_SEL_SHIFT (0U)




typedef uint8_t SGMIIPLUSR_PMDCOM_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_PMDCOM_BLOCKADDRESS_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_PMDCOM_BLOCKADDRESS_SGMIIPLUSR_X1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_PMDCOM_BLOCKADDRESS_SGMIIPLUSR_X1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_PMDCOM_RDBType {
    SGMIIPLUSR_PMDCOM_PMD_MASKDATA_SGMIIPLUSR_X1_TYPE pmd_maskdata; /* OFFSET: 0x0 */
    SGMIIPLUSR_PMDCOM_PMCSX1_TYPE pmd_maskdata_ctrl; /* OFFSET: 0x2 */
    SGMIIPLUSR_PMDCOM_PLOSX1_TYPE pmd_ln_offset; /* OFFSET: 0x4 */
    SGMIIPLUSR_PMDCOM_PCSX1_TYPE pmd_control; /* OFFSET: 0x6 */
    SGMIIPLUSR_PMDCOM_RESERVED_TYPE rsvd0[22]; /* OFFSET: 0x8 */
    SGMIIPLUSR_PMDCOM_BLOCKADDRESS_SGMIIPLUSR_X1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_PMDCOM_RDBType;


#define PMD_COM_SGMIIPLUSR_X1_BASE      (0x4AE50340UL)



#define SGMIIPLUSR_PMDCOM_MAX_HW_ID     (1UL)


#define SGMIIPLUSR_PMDCOM_CONST0        (0x0022U)

#endif /* SGMIIPLUSR_PMDCOM_RDB_H */
