/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_pll_afe_rdb.h
    @brief RDB File for SGMIIPLUSR_PLL_AFE

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_PLL_AFE_RDB_H
#define SGMIIPLUSR_PLL_AFE_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPLUSR_PLL_AFE_C0SX1_TYPE;
#define SGMIIPLUSR_PLL_AFE_C0SX1_EN_TEST_INTEGER_CLK_MASK (0x8000U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_EN_TEST_INTEGER_CLK_SHIFT (15U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_XTAL_BIAS_MASK (0x7000U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_XTAL_BIAS_SHIFT (12U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_CPAR_MASK (0xc00U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_CPAR_SHIFT (10U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_RPAR_MASK (0x3c0U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_RPAR_SHIFT (6U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_CURR_SEL_MASK (0x3cU)
#define SGMIIPLUSR_PLL_AFE_C0SX1_CURR_SEL_SHIFT (2U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_HIPASS_MASK (0x2U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_HIPASS_SHIFT (1U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_CM_SEL_MASK (0x1U)
#define SGMIIPLUSR_PLL_AFE_C0SX1_CM_SEL_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PLL_AFE_C1SX1_TYPE;
#define SGMIIPLUSR_PLL_AFE_C1SX1_LEAKAGE_TEST_MASK (0xc00U)
#define SGMIIPLUSR_PLL_AFE_C1SX1_LEAKAGE_TEST_SHIFT (10U)
#define SGMIIPLUSR_PLL_AFE_C1SX1_PLL_PON_MASK (0x3c0U)
#define SGMIIPLUSR_PLL_AFE_C1SX1_PLL_PON_SHIFT (6U)
#define SGMIIPLUSR_PLL_AFE_C1SX1_XTAL_CORE_BIAS_MASK (0x3cU)
#define SGMIIPLUSR_PLL_AFE_C1SX1_XTAL_CORE_BIAS_SHIFT (2U)
#define SGMIIPLUSR_PLL_AFE_C1SX1_LV_EN_MASK (0x2U)
#define SGMIIPLUSR_PLL_AFE_C1SX1_LV_EN_SHIFT (1U)
#define SGMIIPLUSR_PLL_AFE_C1SX1_EN_TEST_FRAC_CLK_MASK (0x1U)
#define SGMIIPLUSR_PLL_AFE_C1SX1_EN_TEST_FRAC_CLK_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_I_PLL_FRAC_MODE_MASK (0xc000U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_I_PLL_FRAC_MODE_SHIFT (14U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_VCO_ICTR_MASK (0x3800U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_VCO_ICTR_SHIFT (11U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_TEST_PLL_MODE_MASK (0x400U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_TEST_PLL_MODE_SHIFT (10U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_TEST_AMP_MASK (0x1e0U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_TEST_AMP_SHIFT (5U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_INTN_FB_EN_MASK (0x10U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_INTN_FB_EN_SHIFT (4U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_EN10T_MASK (0x8U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_EN10T_SHIFT (3U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_TEST_VC_MASK (0x4U)
#define SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_TEST_VC_SHIFT (2U)




typedef uint16_t SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_PLL_MODE_MASK (0x8000U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_PLL_MODE_SHIFT (15U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_REFCLK_IN_BIAS_MASK (0x7e00U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_REFCLK_IN_BIAS_SHIFT (9U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_INT_DIV_EN_MASK (0x100U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_INT_DIV_EN_SHIFT (8U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_MMD_EN_MASK (0x80U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_MMD_EN_SHIFT (7U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_TEST_SEL_MASK (0x70U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_TEST_SEL_SHIFT (4U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_TESTCLK_EN_MASK (0x8U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_TESTCLK_EN_SHIFT (3U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_TCEST_NEG_MASK (0x7U)
#define SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_TCEST_NEG_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PLL_AFE_C4SX1_TYPE;
#define SGMIIPLUSR_PLL_AFE_C4SX1_MMD_PRSC8OR9PWDB_MASK (0x8000U)
#define SGMIIPLUSR_PLL_AFE_C4SX1_MMD_PRSC8OR9PWDB_SHIFT (15U)
#define SGMIIPLUSR_PLL_AFE_C4SX1_ADJ_MASK (0x7000U)
#define SGMIIPLUSR_PLL_AFE_C4SX1_ADJ_SHIFT (12U)
#define SGMIIPLUSR_PLL_AFE_C4SX1_MMD_RESETB_MASK (0x800U)
#define SGMIIPLUSR_PLL_AFE_C4SX1_MMD_RESETB_SHIFT (11U)
#define SGMIIPLUSR_PLL_AFE_C4SX1_EN_CAP_MASK (0x70U)
#define SGMIIPLUSR_PLL_AFE_C4SX1_EN_CAP_SHIFT (4U)
#define SGMIIPLUSR_PLL_AFE_C4SX1_DIV_MASK (0xfU)
#define SGMIIPLUSR_PLL_AFE_C4SX1_DIV_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PLL_AFE_C5SX1_TYPE;
#define SGMIIPLUSR_PLL_AFE_C5SX1_I_NDIV_FRAC_3_0_MASK (0xf000U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_I_NDIV_FRAC_3_0_SHIFT (12U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_I_PFD_OFFSET_MASK (0xc00U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_I_PFD_OFFSET_SHIFT (10U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_REF_DOUBLER_EN_MASK (0x200U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_REF_DOUBLER_EN_SHIFT (9U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_I_PFD_OFFSET_ENLARGE_MASK (0x100U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_I_PFD_OFFSET_ENLARGE_SHIFT (8U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_EN_CUR_MASK (0xe0U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_EN_CUR_SHIFT (5U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_CALIB_ADJ_MASK (0xeU)
#define SGMIIPLUSR_PLL_AFE_C5SX1_CALIB_ADJ_SHIFT (1U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_MMD_PRSC4OR5PWDB_MASK (0x1U)
#define SGMIIPLUSR_PLL_AFE_C5SX1_MMD_PRSC4OR5PWDB_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PLL_AFE_C6SX1_TYPE;
#define SGMIIPLUSR_PLL_AFE_C6SX1_I_NDIV_INT_1_0_MASK (0xc000U)
#define SGMIIPLUSR_PLL_AFE_C6SX1_I_NDIV_INT_1_0_SHIFT (14U)
#define SGMIIPLUSR_PLL_AFE_C6SX1_I_NDIV_FRAC_17_4_MASK (0x3fffU)
#define SGMIIPLUSR_PLL_AFE_C6SX1_I_NDIV_FRAC_17_4_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PLL_AFE_C7SX1_TYPE;
#define SGMIIPLUSR_PLL_AFE_C7SX1_SEL_FP3CAP_MASK (0xf000U)
#define SGMIIPLUSR_PLL_AFE_C7SX1_SEL_FP3CAP_SHIFT (12U)
#define SGMIIPLUSR_PLL_AFE_C7SX1_I_PLL_SDM_PWRDNB_MASK (0x800U)
#define SGMIIPLUSR_PLL_AFE_C7SX1_I_PLL_SDM_PWRDNB_SHIFT (11U)
#define SGMIIPLUSR_PLL_AFE_C7SX1_INV_VCO_CAL_MASK (0x400U)
#define SGMIIPLUSR_PLL_AFE_C7SX1_INV_VCO_CAL_SHIFT (10U)
#define SGMIIPLUSR_PLL_AFE_C7SX1_I_NDIV_DITHER_EN_MASK (0x200U)
#define SGMIIPLUSR_PLL_AFE_C7SX1_I_NDIV_DITHER_EN_SHIFT (9U)
#define SGMIIPLUSR_PLL_AFE_C7SX1_MMD_DIV_RANGE_MASK (0x100U)
#define SGMIIPLUSR_PLL_AFE_C7SX1_MMD_DIV_RANGE_SHIFT (8U)
#define SGMIIPLUSR_PLL_AFE_C7SX1_I_NDIV_INT_9_2_MASK (0xffU)
#define SGMIIPLUSR_PLL_AFE_C7SX1_I_NDIV_INT_9_2_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PLL_AFE_CONTROL8_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_PLL_AFE_CONTROL8_SGMIIPLUSR_X1_VDD1P0_EN_MASK (0x1U)
#define SGMIIPLUSR_PLL_AFE_CONTROL8_SGMIIPLUSR_X1_VDD1P0_EN_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PLL_AFE_T0SX1_TYPE;
#define SGMIIPLUSR_PLL_AFE_T0SX1_TCA_TIMER_SEL_MASK (0xc000U)
#define SGMIIPLUSR_PLL_AFE_T0SX1_TCA_TIMER_SEL_SHIFT (14U)
#define SGMIIPLUSR_PLL_AFE_T0SX1_TCA_COARSE_TIMER_MASK (0x3fffU)
#define SGMIIPLUSR_PLL_AFE_T0SX1_TCA_COARSE_TIMER_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PLL_AFE_T1SX1_TYPE;
#define SGMIIPLUSR_PLL_AFE_T1SX1_XGXS_SEL_MASK (0x8000U)
#define SGMIIPLUSR_PLL_AFE_T1SX1_XGXS_SEL_SHIFT (15U)
#define SGMIIPLUSR_PLL_AFE_T1SX1_INTERP_OVERRIDE_MASK (0x4000U)
#define SGMIIPLUSR_PLL_AFE_T1SX1_INTERP_OVERRIDE_SHIFT (14U)
#define SGMIIPLUSR_PLL_AFE_T1SX1_TCA_FINE_TIMER_MASK (0x3fffU)
#define SGMIIPLUSR_PLL_AFE_T1SX1_TCA_FINE_TIMER_SHIFT (0U)




typedef uint8_t SGMIIPLUSR_PLL_AFE_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_PLL_AFE_BSX1_TYPE;
#define SGMIIPLUSR_PLL_AFE_BSX1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_PLL_AFE_BSX1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_PLL_AFE_RDBType {
    SGMIIPLUSR_PLL_AFE_C0SX1_TYPE ctrl0; /* OFFSET: 0x0 */
    SGMIIPLUSR_PLL_AFE_C1SX1_TYPE ctrl1; /* OFFSET: 0x2 */
    SGMIIPLUSR_PLL_AFE_CONTROL2_SGMIIPLUSR_X1_TYPE ctrl2; /* OFFSET: 0x4 */
    SGMIIPLUSR_PLL_AFE_CONTROL3_SGMIIPLUSR_X1_TYPE ctrl3; /* OFFSET: 0x6 */
    SGMIIPLUSR_PLL_AFE_C4SX1_TYPE ctrl4; /* OFFSET: 0x8 */
    SGMIIPLUSR_PLL_AFE_C5SX1_TYPE ctrl5; /* OFFSET: 0xa */
    SGMIIPLUSR_PLL_AFE_C6SX1_TYPE ctrl6; /* OFFSET: 0xc */
    SGMIIPLUSR_PLL_AFE_C7SX1_TYPE ctrl7; /* OFFSET: 0xe */
    SGMIIPLUSR_PLL_AFE_CONTROL8_SGMIIPLUSR_X1_TYPE ctrl8; /* OFFSET: 0x10 */
    SGMIIPLUSR_PLL_AFE_T0SX1_TYPE tcatimer0; /* OFFSET: 0x12 */
    SGMIIPLUSR_PLL_AFE_T1SX1_TYPE tcatimer1; /* OFFSET: 0x14 */
    SGMIIPLUSR_PLL_AFE_RESERVED_TYPE rsvd0[8]; /* OFFSET: 0x16 */
    SGMIIPLUSR_PLL_AFE_BSX1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_PLL_AFE_RDBType;


#define PLL_AFE_SGMIIPLUSR_X1_BASE      (0x4AE500A0UL)



#define SGMIIPLUSR_PLL_AFE_MAX_HW_ID    (1UL)


#define SGMIIPLUSR_PLL_AFE_CONST0       (0x5740U)


#define SGMIIPLUSR_PLL_AFE_CONST1       (0x01D1U)


#define SGMIIPLUSR_PLL_AFE_CONST2       (0x19E8U)


#define SGMIIPLUSR_PLL_AFE_CONST3       (0xAB80U)


#define SGMIIPLUSR_PLL_AFE_CONST4       (0x8821U)


#define SGMIIPLUSR_PLL_AFE_CONST5       (0x0044U)


#define SGMIIPLUSR_PLL_AFE_CONST6       (0x4000U)


#define SGMIIPLUSR_PLL_AFE_CONST7       (0x08F7U)


#define SGMIIPLUSR_PLL_AFE_CONST8       (0x0001U)


#define SGMIIPLUSR_PLL_AFE_CONST9       (0x8021U)


#define SGMIIPLUSR_PLL_AFE_CONST10      (0x59E8U)


#define SGMIIPLUSR_PLL_AFE_CONST11      (0x9000U)


#define SGMIIPLUSR_PLL_AFE_CONST12      (0x0833U)

#endif /* SGMIIPLUSR_PLL_AFE_RDB_H */
