/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_cl22_rdb.h
    @brief RDB File for SGMIIPLUSR_CL22

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_CL22_RDB_H
#define SGMIIPLUSR_CL22_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_RST_HW_MASK (0x8000U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_RST_HW_SHIFT (15U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_GLOOPBACK_MASK (0x4000U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_GLOOPBACK_SHIFT (14U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_MANUAL_SPEED0_MASK (0x2000U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_MANUAL_SPEED0_SHIFT (13U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_AUTONEG_ENABLE_MASK (0x1000U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_AUTONEG_ENABLE_SHIFT (12U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_PWRDWN_SW_MASK (0x800U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_PWRDWN_SW_SHIFT (11U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_RESTART_AUTONEG_MASK (0x200U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_RESTART_AUTONEG_SHIFT (9U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_DUPLEX_MASK (0x100U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_DUPLEX_SHIFT (8U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_COLLISION_TEST_EN_MASK (0x80U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_COLLISION_TEST_EN_SHIFT (7U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_MANUAL_SPEED1_MASK (0x40U)
#define SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_MANUAL_SPEED1_SHIFT (6U)




typedef uint16_t SGMIIPLUSR_CL22_MSX1_TYPE;
#define SGMIIPLUSR_CL22_MSX1_S100BASE_T4_CAPABLE_MASK (0x8000U)
#define SGMIIPLUSR_CL22_MSX1_S100BASE_T4_CAPABLE_SHIFT (15U)
#define SGMIIPLUSR_CL22_MSX1_S100BASE_X_FULL_DUPLEX_CAPABLE_MASK (0x4000U)
#define SGMIIPLUSR_CL22_MSX1_S100BASE_X_FULL_DUPLEX_CAPABLE_SHIFT (14U)
#define SGMIIPLUSR_CL22_MSX1_S100BASE_X_HALF_DUPLEX_CAPABLE_MASK (0x2000U)
#define SGMIIPLUSR_CL22_MSX1_S100BASE_X_HALF_DUPLEX_CAPABLE_SHIFT (13U)
#define SGMIIPLUSR_CL22_MSX1_S10BASE_T_FULL_DUPLEX_CAPABLE_MASK (0x1000U)
#define SGMIIPLUSR_CL22_MSX1_S10BASE_T_FULL_DUPLEX_CAPABLE_SHIFT (12U)
#define SGMIIPLUSR_CL22_MSX1_S10BASE_T_HALF_DUPLEX_CAPABLE_MASK (0x800U)
#define SGMIIPLUSR_CL22_MSX1_S10BASE_T_HALF_DUPLEX_CAPABLE_SHIFT (11U)
#define SGMIIPLUSR_CL22_MSX1_S100BASE_T2_FULL_DUPLEX_CAPABLE_MASK (0x400U)
#define SGMIIPLUSR_CL22_MSX1_S100BASE_T2_FULL_DUPLEX_CAPABLE_SHIFT (10U)
#define SGMIIPLUSR_CL22_MSX1_S100BASE_T2_HALF_DUPLEX_CAPABLE_MASK (0x200U)
#define SGMIIPLUSR_CL22_MSX1_S100BASE_T2_HALF_DUPLEX_CAPABLE_SHIFT (9U)
#define SGMIIPLUSR_CL22_MSX1_EXTENDED_STATUS_MASK (0x100U)
#define SGMIIPLUSR_CL22_MSX1_EXTENDED_STATUS_SHIFT (8U)
#define SGMIIPLUSR_CL22_MSX1_MF_PREAMBLE_SUPRESSION_MASK (0x40U)
#define SGMIIPLUSR_CL22_MSX1_MF_PREAMBLE_SUPRESSION_SHIFT (6U)
#define SGMIIPLUSR_CL22_MSX1_AUTONEG_COMPLETE_MASK (0x20U)
#define SGMIIPLUSR_CL22_MSX1_AUTONEG_COMPLETE_SHIFT (5U)
#define SGMIIPLUSR_CL22_MSX1_REMOTE_FAULT_MASK (0x10U)
#define SGMIIPLUSR_CL22_MSX1_REMOTE_FAULT_SHIFT (4U)
#define SGMIIPLUSR_CL22_MSX1_AUTONEG_ABILITY_MASK (0x8U)
#define SGMIIPLUSR_CL22_MSX1_AUTONEG_ABILITY_SHIFT (3U)
#define SGMIIPLUSR_CL22_MSX1_LINK_STATUS_MASK (0x4U)
#define SGMIIPLUSR_CL22_MSX1_LINK_STATUS_SHIFT (2U)
#define SGMIIPLUSR_CL22_MSX1_JABBER_DETECT_MASK (0x2U)
#define SGMIIPLUSR_CL22_MSX1_JABBER_DETECT_SHIFT (1U)
#define SGMIIPLUSR_CL22_MSX1_EXTENDED_CAPABILITY_MASK (0x1U)
#define SGMIIPLUSR_CL22_MSX1_EXTENDED_CAPABILITY_SHIFT (0U)




typedef uint8_t SGMIIPLUSR_CL22_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_NEXT_PAGE_MASK (0x8000U)
#define SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_NEXT_PAGE_SHIFT (15U)
#define SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_REMOTE_FAULT_2_1_MASK (0x3000U)
#define SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_REMOTE_FAULT_2_1_SHIFT (12U)
#define SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_PAUSE_MASK (0x180U)
#define SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_PAUSE_SHIFT (7U)
#define SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_HALF_DUPLEX_MASK (0x40U)
#define SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_HALF_DUPLEX_SHIFT (6U)
#define SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_FULL_DUPLEX_MASK (0x20U)
#define SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_FULL_DUPLEX_SHIFT (5U)




typedef uint16_t SGMIIPLUSR_CL22_ASX1_TYPE;
#define SGMIIPLUSR_CL22_ASX1_LP_NEXT_PAGE_MASK (0x8000U)
#define SGMIIPLUSR_CL22_ASX1_LP_NEXT_PAGE_SHIFT (15U)
#define SGMIIPLUSR_CL22_ASX1_LP_ACKNOWLEDGE_MASK (0x4000U)
#define SGMIIPLUSR_CL22_ASX1_LP_ACKNOWLEDGE_SHIFT (14U)
#define SGMIIPLUSR_CL22_ASX1_LP_REMOTE_FAULT_2_1_MASK (0x3000U)
#define SGMIIPLUSR_CL22_ASX1_LP_REMOTE_FAULT_2_1_SHIFT (12U)
#define SGMIIPLUSR_CL22_ASX1_LP_PAUSE_MASK (0x180U)
#define SGMIIPLUSR_CL22_ASX1_LP_PAUSE_SHIFT (7U)
#define SGMIIPLUSR_CL22_ASX1_LP_HALF_DUPLEX_MASK (0x40U)
#define SGMIIPLUSR_CL22_ASX1_LP_HALF_DUPLEX_SHIFT (6U)
#define SGMIIPLUSR_CL22_ASX1_LP_FULL_DUPLEX_MASK (0x20U)
#define SGMIIPLUSR_CL22_ASX1_LP_FULL_DUPLEX_SHIFT (5U)
#define SGMIIPLUSR_CL22_ASX1_LP_SGMII_MODE_MASK (0x1U)
#define SGMIIPLUSR_CL22_ASX1_LP_SGMII_MODE_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_CL22_ASX11_TYPE;
#define SGMIIPLUSR_CL22_ASX11_NEXT_PAGE_ABILITY_MASK (0x4U)
#define SGMIIPLUSR_CL22_ASX11_NEXT_PAGE_ABILITY_SHIFT (2U)
#define SGMIIPLUSR_CL22_ASX11_PAGE_RECEIVED_MASK (0x2U)
#define SGMIIPLUSR_CL22_ASX11_PAGE_RECEIVED_SHIFT (1U)




typedef uint16_t SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_NEXT_PAGE_MASK (0x8000U)
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_NEXT_PAGE_SHIFT (15U)
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_ACK_MASK (0x4000U)
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_ACK_SHIFT (14U)
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_MESSAGE_PAGE_MASK (0x2000U)
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_MESSAGE_PAGE_SHIFT (13U)
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_ACK2_MASK (0x1000U)
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_ACK2_SHIFT (12U)
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_TOGGLE_MASK (0x800U)
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_TOGGLE_SHIFT (11U)
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_MESSAGE_MASK (0x7ffU)
#define SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_MESSAGE_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPNEXT_PAGE_MASK (0x8000U)
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPNEXT_PAGE_SHIFT (15U)
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPACK_MASK (0x4000U)
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPACK_SHIFT (14U)
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPMESSAGE_PAGE_MASK (0x2000U)
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPMESSAGE_PAGE_SHIFT (13U)
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPACK2_MASK (0x1000U)
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPACK2_SHIFT (12U)
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPTOGGLE_MASK (0x800U)
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPTOGGLE_SHIFT (11U)
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPMESSAGE_MASK (0x7ffU)
#define SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_LPMESSAGE_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_CL22_MMDACCESSCNTL_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_CL22_MMDACCESSCNTL_SGMIIPLUSR_X1_FUNCTION_MASK (0xc000U)
#define SGMIIPLUSR_CL22_MMDACCESSCNTL_SGMIIPLUSR_X1_FUNCTION_SHIFT (14U)
#define SGMIIPLUSR_CL22_MMDACCESSCNTL_SGMIIPLUSR_X1_DEVAD_MASK (0x1fU)
#define SGMIIPLUSR_CL22_MMDACCESSCNTL_SGMIIPLUSR_X1_DEVAD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_CL22_MSX11_TYPE;
#define SGMIIPLUSR_CL22_MSX11_ADDR_OR_DATA_MASK (0xffffU)
#define SGMIIPLUSR_CL22_MSX11_ADDR_OR_DATA_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_CL22_MSX12_TYPE;
#define SGMIIPLUSR_CL22_MSX12_S1000BASE_X_FULL_DUPLEX_CAPABLE_MASK (0x8000U)
#define SGMIIPLUSR_CL22_MSX12_S1000BASE_X_FULL_DUPLEX_CAPABLE_SHIFT (15U)
#define SGMIIPLUSR_CL22_MSX12_S1000BASE_X_HALF_DUPLEX_CAPABLE_MASK (0x4000U)
#define SGMIIPLUSR_CL22_MSX12_S1000BASE_X_HALF_DUPLEX_CAPABLE_SHIFT (14U)
#define SGMIIPLUSR_CL22_MSX12_S1000BASE_T_FULL_DUPLEX_CAPABLE_MASK (0x2000U)
#define SGMIIPLUSR_CL22_MSX12_S1000BASE_T_FULL_DUPLEX_CAPABLE_SHIFT (13U)
#define SGMIIPLUSR_CL22_MSX12_S1000BASE_T_HALF_DUPLEX_CAPABLE_MASK (0x1000U)
#define SGMIIPLUSR_CL22_MSX12_S1000BASE_T_HALF_DUPLEX_CAPABLE_SHIFT (12U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_CL22_RDBType {
    SGMIIPLUSR_CL22_MIICNTL_SGMIIPLUSR_X1_TYPE miicntl; /* OFFSET: 0x0 */
    SGMIIPLUSR_CL22_MSX1_TYPE miistat; /* OFFSET: 0x2 */
    SGMIIPLUSR_CL22_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x4 */
    SGMIIPLUSR_CL22_AUTONEGADV_SGMIIPLUSR_X1_TYPE autonegadv; /* OFFSET: 0x8 */
    SGMIIPLUSR_CL22_ASX1_TYPE autoneglpabil; /* OFFSET: 0xa */
    SGMIIPLUSR_CL22_ASX11_TYPE autonegexp; /* OFFSET: 0xc */
    SGMIIPLUSR_CL22_AUTONEGNP_SGMIIPLUSR_X1_TYPE autonegnp; /* OFFSET: 0xe */
    SGMIIPLUSR_CL22_AUTONEGLPNP_SGMIIPLUSR_X1_TYPE autoneglpabil2; /* OFFSET: 0x10 */
    SGMIIPLUSR_CL22_RESERVED_TYPE rsvd1[8]; /* OFFSET: 0x12 */
    SGMIIPLUSR_CL22_MMDACCESSCNTL_SGMIIPLUSR_X1_TYPE mmdaccesscntl; /* OFFSET: 0x1a */
    SGMIIPLUSR_CL22_MSX11_TYPE mmdaddressdata; /* OFFSET: 0x1c */
    SGMIIPLUSR_CL22_MSX12_TYPE miiextstat; /* OFFSET: 0x1e */
} SGMIIPLUSR_CL22_RDBType;


#define CL22_B0_SGMIIPLUSR_X1_BASE      (0x4AE00000UL)



#define SGMIIPLUSR_CL22_MAX_HW_ID       (1UL)


#define SGMIIPLUSR_POWER_DOWN_BIT_TIMEOUT_CNT  (1000UL)

#endif /* SGMIIPLUSR_CL22_RDB_H */
