/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_tx_x1_credit_gen4_rdb.h
    @brief RDB File for SGMIIPLUSR_TX_X1_CREDIT_GEN4

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_TX_X1_CREDIT_GEN4_RDB_H
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C0SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C0SX1_R1K1C0_MASK (0x3fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C0SX1_R1K1C0_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C1SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C1SX1_REG1G_KR1_CGC_MASK (0x1fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C1SX1_REG1G_KR1_CGC_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C2SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C2SX1_REG1G_KR1_LOOPCNT0_MASK (0xff00U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C2SX1_REG1G_KR1_LOOPCNT0_SHIFT (8U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C2SX1_R1K1C1_MASK (0xffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C2SX1_R1K1C1_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C3SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C3SX1_REG1G_KR1_LOOPCNT1_MASK (0x3fU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C3SX1_REG1G_KR1_LOOPCNT1_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C0SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C0SX1_R25K1C0_MASK (0x3fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C0SX1_R25K1C0_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C1SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C1SX1_REG2P5G_KR1_CGC_MASK (0x1fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C1SX1_REG2P5G_KR1_CGC_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C2SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C2SX1_R25K1L0_MASK (0xff00U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C2SX1_R25K1L0_SHIFT (8U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C2SX1_R25K1C1_MASK (0xffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C2SX1_R25K1C1_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C3SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C3SX1_R25K1L1_MASK (0x3fU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C3SX1_R25K1L1_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C0SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C0SX1_R5K1C0_MASK (0x3fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C0SX1_R5K1C0_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C1SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C1SX1_REG5G_KR1_CGC_MASK (0x1fffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C1SX1_REG5G_KR1_CGC_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C2SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C2SX1_REG5G_KR1_LOOPCNT0_MASK (0xff00U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C2SX1_REG5G_KR1_LOOPCNT0_SHIFT (8U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C2SX1_R5K1C1_MASK (0xffU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C2SX1_R5K1C1_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C3SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C3SX1_R1C127L1_MASK (0x3fU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C3SX1_R1C127L1_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1C127C3SX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1C127C3SX1_R5K1L1_MASK (0x3fU)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1C127C3SX1_R5K1L1_SHIFT (0U)




typedef uint8_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_TX_X1_CREDIT_GEN4_BSX1_TYPE;
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_BSX1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_BSX1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_TX_X1_CREDIT_GEN4_RDBType {
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C0SX1_TYPE reg1g_kr1_credit0; /* OFFSET: 0x0 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C1SX1_TYPE reg1g_kr1_credit1; /* OFFSET: 0x2 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C2SX1_TYPE reg1g_kr1_credit2; /* OFFSET: 0x4 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1K1C3SX1_TYPE reg1g_kr1_credit3; /* OFFSET: 0x6 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C0SX1_TYPE reg2p5g_kr1_credit0; /* OFFSET: 0x8 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C1SX1_TYPE reg2p5g_kr1_credit1; /* OFFSET: 0xa */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C2SX1_TYPE reg2p5g_kr1_credit2; /* OFFSET: 0xc */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R25K1C3SX1_TYPE reg2p5g_kr1_credit3; /* OFFSET: 0xe */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C0SX1_TYPE reg5g_kr1_credit0; /* OFFSET: 0x10 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C1SX1_TYPE reg5g_kr1_credit1; /* OFFSET: 0x12 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C2SX1_TYPE reg5g_kr1_credit2; /* OFFSET: 0x14 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R5K1C3SX1_TYPE reg5g_kr1_credit3; /* OFFSET: 0x16 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_R1C127C3SX1_TYPE reg1g_cl127_credit3; /* OFFSET: 0x18 */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x1a */
    SGMIIPLUSR_TX_X1_CREDIT_GEN4_BSX1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_TX_X1_CREDIT_GEN4_RDBType;


#define TX_X1_CREDIT_GEN4_BASE          (0x4AED2520UL)



#define SGMIIPLUSR_TX_X1_CREDIT_GEN4_MAX_HW_ID  (1UL)


#define SGMIIPLUSR_TX_X1_CONST13        (0x0021U)


#define SGMIIPLUSR_TX_X1_CONST14        (0x0006U)

#endif /* SGMIIPLUSR_TX_X1_CREDIT_GEN4_RDB_H */
