/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_pcs_main0_rdb.h
    @brief RDB File for SGMIIPLUSR_PCS_MAIN0

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_PCS_MAIN0_RDB_H
#define SGMIIPLUSR_PCS_MAIN0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPLUSR_PCS_MAIN0_SSX1_TYPE;
#define SGMIIPLUSR_PCS_MAIN0_SSX1_REFCLK_SEL_MASK (0xf000U)
#define SGMIIPLUSR_PCS_MAIN0_SSX1_REFCLK_SEL_SHIFT (12U)
#define SGMIIPLUSR_PCS_MAIN0_SSX1_PORT_MODE_SEL_MASK (0x70U)
#define SGMIIPLUSR_PCS_MAIN0_SSX1_PORT_MODE_SEL_SHIFT (4U)
#define SGMIIPLUSR_PCS_MAIN0_SSX1_SINGLE_PORT_MODE_MASK (0x8U)
#define SGMIIPLUSR_PCS_MAIN0_SSX1_SINGLE_PORT_MODE_SHIFT (3U)
#define SGMIIPLUSR_PCS_MAIN0_SSX1_STAND_ALONE_MODE_MASK (0x4U)
#define SGMIIPLUSR_PCS_MAIN0_SSX1_STAND_ALONE_MODE_SHIFT (2U)
#define SGMIIPLUSR_PCS_MAIN0_SSX1_PMD_IEEE_RST_DECOUPLE_EN_MASK (0x2U)
#define SGMIIPLUSR_PCS_MAIN0_SSX1_PMD_IEEE_RST_DECOUPLE_EN_SHIFT (1U)
#define SGMIIPLUSR_PCS_MAIN0_SSX1_MDIOREG_RST_SW_MASK (0x1U)
#define SGMIIPLUSR_PCS_MAIN0_SSX1_MDIOREG_RST_SW_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PCS_MAIN0_S1SX1_TYPE;
#define SGMIIPLUSR_PCS_MAIN0_S1SX1_USXGMII_EN_OVERRIDE_VAL_MASK (0xf00U)
#define SGMIIPLUSR_PCS_MAIN0_S1SX1_USXGMII_EN_OVERRIDE_VAL_SHIFT (8U)
#define SGMIIPLUSR_PCS_MAIN0_S1SX1_USXGMII_PCS_SEL_CKGATE_DISABLE_MASK (0x80U)
#define SGMIIPLUSR_PCS_MAIN0_S1SX1_USXGMII_PCS_SEL_CKGATE_DISABLE_SHIFT (7U)
#define SGMIIPLUSR_PCS_MAIN0_S1SX1_UPORT_BAUD_OVERRIDE_EN_MASK (0x40U)
#define SGMIIPLUSR_PCS_MAIN0_S1SX1_UPORT_BAUD_OVERRIDE_EN_SHIFT (6U)
#define SGMIIPLUSR_PCS_MAIN0_S1SX1_USXGMII_PCS_SEL_MASK (0x20U)
#define SGMIIPLUSR_PCS_MAIN0_S1SX1_USXGMII_PCS_SEL_SHIFT (5U)
#define SGMIIPLUSR_PCS_MAIN0_S1SX1_UBAUD_OVERRIDE_VAL_MASK (0xfU)
#define SGMIIPLUSR_PCS_MAIN0_S1SX1_UBAUD_OVERRIDE_VAL_SHIFT (0U)




typedef uint8_t SGMIIPLUSR_PCS_MAIN0_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_PCS_MAIN0_TC1SX1_TYPE;
#define SGMIIPLUSR_PCS_MAIN0_TC1SX1_TICK_OVERRIDE_MASK (0x8000U)
#define SGMIIPLUSR_PCS_MAIN0_TC1SX1_TICK_OVERRIDE_SHIFT (15U)
#define SGMIIPLUSR_PCS_MAIN0_TC1SX1_TICK_NUMERATOR_UPPER_MASK (0x7fffU)
#define SGMIIPLUSR_PCS_MAIN0_TC1SX1_TICK_NUMERATOR_UPPER_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PCS_MAIN0_TC0SX1_TYPE;
#define SGMIIPLUSR_PCS_MAIN0_TC0SX1_TICK_NUMERATOR_LOWER_MASK (0xf000U)
#define SGMIIPLUSR_PCS_MAIN0_TC0SX1_TICK_NUMERATOR_LOWER_SHIFT (12U)
#define SGMIIPLUSR_PCS_MAIN0_TC0SX1_TICK_DENOMINATOR_MASK (0xffcU)
#define SGMIIPLUSR_PCS_MAIN0_TC0SX1_TICK_DENOMINATOR_SHIFT (2U)




typedef uint16_t SGMIIPLUSR_PCS_MAIN0_LCSX1_TYPE;
#define SGMIIPLUSR_PCS_MAIN0_LCSX1_REMOTE_PCS_LOOPBACK_ENABLE_MASK (0xf000U)
#define SGMIIPLUSR_PCS_MAIN0_LCSX1_REMOTE_PCS_LOOPBACK_ENABLE_SHIFT (12U)
#define SGMIIPLUSR_PCS_MAIN0_LCSX1_REMOTE_PMD_LOOPBACK_ENABLE_MASK (0xf00U)
#define SGMIIPLUSR_PCS_MAIN0_LCSX1_REMOTE_PMD_LOOPBACK_ENABLE_SHIFT (8U)
#define SGMIIPLUSR_PCS_MAIN0_LCSX1_LOCAL_PCS_LOOPBACK_ENABLE_MASK (0xf0U)
#define SGMIIPLUSR_PCS_MAIN0_LCSX1_LOCAL_PCS_LOOPBACK_ENABLE_SHIFT (4U)




typedef uint16_t SGMIIPLUSR_PCS_MAIN0_MCSX1_TYPE;
#define SGMIIPLUSR_PCS_MAIN0_MCSX1_PMI_LP_MERGE_METHOD2_EN_MASK (0x4U)
#define SGMIIPLUSR_PCS_MAIN0_MCSX1_PMI_LP_MERGE_METHOD2_EN_SHIFT (2U)
#define SGMIIPLUSR_PCS_MAIN0_MCSX1_PCS_DEVID_OVERRIDE_MASK (0x2U)
#define SGMIIPLUSR_PCS_MAIN0_MCSX1_PCS_DEVID_OVERRIDE_SHIFT (1U)
#define SGMIIPLUSR_PCS_MAIN0_MCSX1_PMD_DEVID_OVERRIDE_MASK (0x1U)
#define SGMIIPLUSR_PCS_MAIN0_MCSX1_PMD_DEVID_OVERRIDE_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PCS_MAIN0_TSSX1_TYPE;
#define SGMIIPLUSR_PCS_MAIN0_TSSX1_TLA_PLL_SEQUENCER_FSM_STATUS_MASK (0x1fU)
#define SGMIIPLUSR_PCS_MAIN0_TSSX1_TLA_PLL_SEQUENCER_FSM_STATUS_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_REV_LETTER_MASK (0xc000U)
#define SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_REV_LETTER_SHIFT (14U)
#define SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_REV_NUMBER_MASK (0x3800U)
#define SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_REV_NUMBER_SHIFT (11U)
#define SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_BONDING_MASK (0x600U)
#define SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_BONDING_SHIFT (9U)
#define SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_TECH_PROC_MASK (0x1c0U)
#define SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_TECH_PROC_SHIFT (6U)
#define SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_MODEL_NUMBER_MASK (0x3fU)
#define SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_MODEL_NUMBER_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_PCS_MAIN0_BSX1_TYPE;
#define SGMIIPLUSR_PCS_MAIN0_BSX1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_PCS_MAIN0_BSX1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_PCS_MAIN0_RDBType {
    SGMIIPLUSR_PCS_MAIN0_SSX1_TYPE setup; /* OFFSET: 0x0 */
    SGMIIPLUSR_PCS_MAIN0_S1SX1_TYPE setup_1; /* OFFSET: 0x2 */
    SGMIIPLUSR_PCS_MAIN0_RESERVED_TYPE rsvd0[10]; /* OFFSET: 0x4 */
    SGMIIPLUSR_PCS_MAIN0_TC1SX1_TYPE tick_control_1_sgmiiplusr_x1; /* OFFSET: 0xe */
    SGMIIPLUSR_PCS_MAIN0_TC0SX1_TYPE tick_control_0_sgmiiplusr_x1; /* OFFSET: 0x10 */
    SGMIIPLUSR_PCS_MAIN0_LCSX1_TYPE loopback_control_sgmiiplusr_x1; /* OFFSET: 0x12 */
    SGMIIPLUSR_PCS_MAIN0_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x14 */
    SGMIIPLUSR_PCS_MAIN0_MCSX1_TYPE misc_control; /* OFFSET: 0x18 */
    SGMIIPLUSR_PCS_MAIN0_TSSX1_TYPE tla_status; /* OFFSET: 0x1a */
    SGMIIPLUSR_PCS_MAIN0_SERDESID_SGMIIPLUSR_X1_TYPE serdesid; /* OFFSET: 0x1c */
    SGMIIPLUSR_PCS_MAIN0_BSX1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_PCS_MAIN0_RDBType;


#define MAIN0_BASE                      (0x4AED2200UL)



#define SGMIIPLUSR_PCS_MAIN0_MAX_HW_ID  (1UL)


#define SGMIIPLUSR_PCS_CONST            (0x0000U)

#endif /* SGMIIPLUSR_PCS_MAIN0_RDB_H */
