/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_tx_x4_rdb.h
    @brief RDB File for SGMIIPLUSR_TX_X4

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_TX_X4_RDB_H
#define SGMIIPLUSR_TX_X4_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t SGMIIPLUSR_TX_X4_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_TX_X4_E0SX1_TYPE;
#define SGMIIPLUSR_TX_X4_E0SX1_HG2_CODEC_MASK (0x1000U)
#define SGMIIPLUSR_TX_X4_E0SX1_HG2_CODEC_SHIFT (12U)
#define SGMIIPLUSR_TX_X4_E0SX1_HG2_MESSAGE_INVALID_CODE_ENABLE_MASK (0x800U)
#define SGMIIPLUSR_TX_X4_E0SX1_HG2_MESSAGE_INVALID_CODE_ENABLE_SHIFT (11U)
#define SGMIIPLUSR_TX_X4_E0SX1_HG2_ENABLE_MASK (0x400U)
#define SGMIIPLUSR_TX_X4_E0SX1_HG2_ENABLE_SHIFT (10U)
#define SGMIIPLUSR_TX_X4_E0SX1_CL49_BYPASS_TXSM_MASK (0x200U)
#define SGMIIPLUSR_TX_X4_E0SX1_CL49_BYPASS_TXSM_SHIFT (9U)
#define SGMIIPLUSR_TX_X4_E0SX1_CL49_TX_TL_MODE_MASK (0x60U)
#define SGMIIPLUSR_TX_X4_E0SX1_CL49_TX_TL_MODE_SHIFT (5U)
#define SGMIIPLUSR_TX_X4_E0SX1_ENCODEMODE_MASK (0x1cU)
#define SGMIIPLUSR_TX_X4_E0SX1_ENCODEMODE_SHIFT (2U)




typedef uint16_t SGMIIPLUSR_TX_X4_E1SX1_TYPE;
#define SGMIIPLUSR_TX_X4_E1SX1_CATCH_ALL_8B10B_DIS_MASK (0x200U)
#define SGMIIPLUSR_TX_X4_E1SX1_CATCH_ALL_8B10B_DIS_SHIFT (9U)
#define SGMIIPLUSR_TX_X4_E1SX1_PROG_TL_EN_MASK (0x100U)
#define SGMIIPLUSR_TX_X4_E1SX1_PROG_TL_EN_SHIFT (8U)
#define SGMIIPLUSR_TX_X4_E1SX1_PROG_TL_CHAR_MASK (0xffU)
#define SGMIIPLUSR_TX_X4_E1SX1_PROG_TL_CHAR_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_SCR_MODE_MASK (0xc000U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_SCR_MODE_SHIFT (14U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TX_GBOX_PRST_MASK (0x2000U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TX_GBOX_PRST_SHIFT (13U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TX_GBOX_ERR_DET_CLR_MASK (0x1000U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TX_GBOX_ERR_DET_CLR_SHIFT (12U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TX_GBOX_AFRST_EN_MASK (0x800U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TX_GBOX_AFRST_EN_SHIFT (11U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_FEC_ENABLE_MASK (0x400U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_FEC_ENABLE_SHIFT (10U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TX_GBOX_ERRDET_SEL_MASK (0x200U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TX_GBOX_ERRDET_SEL_SHIFT (9U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_CL49_TX_LI_ENABLE_MASK (0x100U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_CL49_TX_LI_ENABLE_SHIFT (8U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_CL49_TX_LF_ENABLE_MASK (0x80U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_CL49_TX_LF_ENABLE_SHIFT (7U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_CL49_TX_RF_ENABLE_MASK (0x40U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_CL49_TX_RF_ENABLE_SHIFT (6U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TX_FIFO_WATERMARK_MASK (0xcU)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TX_FIFO_WATERMARK_SHIFT (2U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_RSTB_TX_LANE_MASK (0x2U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_RSTB_TX_LANE_SHIFT (1U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_ENABLE_TX_LANE_MASK (0x1U)
#define SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_ENABLE_TX_LANE_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_TX_X4_C36T0SX1_TYPE;
#define SGMIIPLUSR_TX_X4_C36T0SX1_DISABLE_TRRR_TX_MASK (0x10U)
#define SGMIIPLUSR_TX_X4_C36T0SX1_DISABLE_TRRR_TX_SHIFT (4U)
#define SGMIIPLUSR_TX_X4_C36T0SX1_ENABLE_SFD_DETECT_MASK (0x8U)
#define SGMIIPLUSR_TX_X4_C36T0SX1_ENABLE_SFD_DETECT_SHIFT (3U)
#define SGMIIPLUSR_TX_X4_C36T0SX1_DISABLE_PACKET_MISALIGN_MASK (0x4U)
#define SGMIIPLUSR_TX_X4_C36T0SX1_DISABLE_PACKET_MISALIGN_SHIFT (2U)




typedef uint16_t SGMIIPLUSR_TX_X4_BLOCKADDRESS_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_TX_X4_BLOCKADDRESS_SGMIIPLUSR_X1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_TX_X4_BLOCKADDRESS_SGMIIPLUSR_X1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_TX_X4_RDBType {
    SGMIIPLUSR_TX_X4_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x0 */
    SGMIIPLUSR_TX_X4_E0SX1_TYPE encode_0; /* OFFSET: 0x2 */
    SGMIIPLUSR_TX_X4_E1SX1_TYPE encode_1; /* OFFSET: 0x4 */
    SGMIIPLUSR_TX_X4_MISC_SGMIIPLUSR_X1_TYPE misc; /* OFFSET: 0x6 */
    SGMIIPLUSR_TX_X4_C36T0SX1_TYPE cl36_tx_0; /* OFFSET: 0x8 */
    SGMIIPLUSR_TX_X4_RESERVED_TYPE rsvd1[20]; /* OFFSET: 0xa */
    SGMIIPLUSR_TX_X4_BLOCKADDRESS_SGMIIPLUSR_X1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_TX_X4_RDBType;


#define TX_X4_CONTROL0_BASE             (0x4AED8860UL)



#define SGMIIPLUSR_TX_X4_MAX_HW_ID      (1UL)

#endif /* SGMIIPLUSR_TX_X4_RDB_H */
