/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiipcie_digital_rdb.h
    @brief RDB File for SGMIIPCIE_DIGITAL

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPCIE_DIGITAL_RDB_H
#define SGMIIPCIE_DIGITAL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPCIE_DIGITAL_C10001SX1_TYPE;
#define SGMIIPCIE_DIGITAL_C10001SX1_REMOTE_LOOPBACK_MASK (0x400U)
#define SGMIIPCIE_DIGITAL_C10001SX1_REMOTE_LOOPBACK_SHIFT (10U)
#define SGMIIPCIE_DIGITAL_C10001SX1_COMMA_DET_EN_MASK (0x100U)
#define SGMIIPCIE_DIGITAL_C10001SX1_COMMA_DET_EN_SHIFT (8U)
#define SGMIIPCIE_DIGITAL_C10001SX1_DISABLE_PLL_PWRDWN_MASK (0x40U)
#define SGMIIPCIE_DIGITAL_C10001SX1_DISABLE_PLL_PWRDWN_SHIFT (6U)
#define SGMIIPCIE_DIGITAL_C10001SX1_SGMII_MASTER_MODE_MASK (0x20U)
#define SGMIIPCIE_DIGITAL_C10001SX1_SGMII_MASTER_MODE_SHIFT (5U)
#define SGMIIPCIE_DIGITAL_C10001SX1_FIBER_MODE_1000X_MASK (0x1U)
#define SGMIIPCIE_DIGITAL_C10001SX1_FIBER_MODE_1000X_SHIFT (0U)




typedef uint16_t SGMIIPCIE_DIGITAL_C10002SX1_TYPE;
#define SGMIIPCIE_DIGITAL_C10002SX1_AUTONEG_FAST_TIMERS_MASK (0x40U)
#define SGMIIPCIE_DIGITAL_C10002SX1_AUTONEG_FAST_TIMERS_SHIFT (6U)
#define SGMIIPCIE_DIGITAL_C10002SX1_FILTER_FORCE_LINK_MASK (0x4U)
#define SGMIIPCIE_DIGITAL_C10002SX1_FILTER_FORCE_LINK_SHIFT (2U)
#define SGMIIPCIE_DIGITAL_C10002SX1_DISABLE_FALSE_LINK_MASK (0x2U)
#define SGMIIPCIE_DIGITAL_C10002SX1_DISABLE_FALSE_LINK_SHIFT (1U)
#define SGMIIPCIE_DIGITAL_C10002SX1_ENABLE_PARALLEL_DETECTION_MASK (0x1U)
#define SGMIIPCIE_DIGITAL_C10002SX1_ENABLE_PARALLEL_DETECTION_SHIFT (0U)




typedef uint8_t SGMIIPCIE_DIGITAL_RESERVED_TYPE;




typedef uint16_t SGMIIPCIE_DIGITAL_S10001SX1_TYPE;
#define SGMIIPCIE_DIGITAL_S10001SX1_LINK_STATUS_CHANGE_MASK (0x80U)
#define SGMIIPCIE_DIGITAL_S10001SX1_LINK_STATUS_CHANGE_SHIFT (7U)
#define SGMIIPCIE_DIGITAL_S10001SX1_PAUSE_RESOLUTION_RXSIDE_MASK (0x40U)
#define SGMIIPCIE_DIGITAL_S10001SX1_PAUSE_RESOLUTION_RXSIDE_SHIFT (6U)
#define SGMIIPCIE_DIGITAL_S10001SX1_PAUSE_RESOLUTION_TXSIDE_MASK (0x20U)
#define SGMIIPCIE_DIGITAL_S10001SX1_PAUSE_RESOLUTION_TXSIDE_SHIFT (5U)
#define SGMIIPCIE_DIGITAL_S10001SX1_SPEED_STATUS_MASK (0x18U)
#define SGMIIPCIE_DIGITAL_S10001SX1_SPEED_STATUS_SHIFT (3U)
#define SGMIIPCIE_DIGITAL_S10001SX1_DUPLEX_STATUS_MASK (0x4U)
#define SGMIIPCIE_DIGITAL_S10001SX1_DUPLEX_STATUS_SHIFT (2U)
#define SGMIIPCIE_DIGITAL_S10001SX1_LINK_STATUS_MASK (0x2U)
#define SGMIIPCIE_DIGITAL_S10001SX1_LINK_STATUS_SHIFT (1U)
#define SGMIIPCIE_DIGITAL_S10001SX1_SGMII_MODE_MASK (0x1U)
#define SGMIIPCIE_DIGITAL_S10001SX1_SGMII_MODE_SHIFT (0U)




typedef uint16_t SGMIIPCIE_DIGITAL_MISC1_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_DIGITAL_MISC1_SGMIIPCIE_X1_REFCLK_SEL_MASK (0xe000U)
#define SGMIIPCIE_DIGITAL_MISC1_SGMIIPCIE_X1_REFCLK_SEL_SHIFT (13U)
#define SGMIIPCIE_DIGITAL_MISC1_SGMIIPCIE_X1_FORCE_SPEED_MASK (0x1fU)
#define SGMIIPCIE_DIGITAL_MISC1_SGMIIPCIE_X1_FORCE_SPEED_SHIFT (0U)




typedef uint16_t SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_RXCK_MII_GEN_SEL_VAL_MASK (0x2000U)
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_RXCK_MII_GEN_SEL_VAL_SHIFT (13U)
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_CLKSIGDET_BYPASS_MASK (0x400U)
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_CLKSIGDET_BYPASS_SHIFT (10U)
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_CLK41_BYPASS_MASK (0x200U)
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_CLK41_BYPASS_SHIFT (9U)
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_MIIGMIIDLY_EN_MASK (0x100U)
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_MIIGMIIDLY_EN_SHIFT (8U)
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_MIIGMIIMUX_EN_MASK (0x80U)
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_MIIGMIIMUX_EN_SHIFT (7U)
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_FIFO_ERR_CYA_MASK (0x10U)
#define SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_FIFO_ERR_CYA_SHIFT (4U)




typedef uint16_t SGMIIPCIE_DIGITAL_BLOCKADDRESS_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_DIGITAL_BLOCKADDRESS_SGMIIPCIE_X1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPCIE_DIGITAL_BLOCKADDRESS_SGMIIPCIE_X1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPCIE_DIGITAL_RDBType {
    SGMIIPCIE_DIGITAL_C10001SX1_TYPE control1000x1; /* OFFSET: 0x0 */
    SGMIIPCIE_DIGITAL_C10002SX1_TYPE control1000x2; /* OFFSET: 0x2 */
    SGMIIPCIE_DIGITAL_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x4 */
    SGMIIPCIE_DIGITAL_S10001SX1_TYPE status1000x1; /* OFFSET: 0x8 */
    SGMIIPCIE_DIGITAL_RESERVED_TYPE rsvd1[6]; /* OFFSET: 0xa */
    SGMIIPCIE_DIGITAL_MISC1_SGMIIPCIE_X1_TYPE misc1; /* OFFSET: 0x10 */
    SGMIIPCIE_DIGITAL_MISC2_SGMIIPCIE_X1_TYPE misc2; /* OFFSET: 0x12 */
    SGMIIPCIE_DIGITAL_RESERVED_TYPE rsvd2[10]; /* OFFSET: 0x14 */
    SGMIIPCIE_DIGITAL_BLOCKADDRESS_SGMIIPCIE_X1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPCIE_DIGITAL_RDBType;


#define DIGITAL_SGMIIPCIE_X1_BASE       (0x4ADD0600UL)



#define SGMIIPCIE_DIGITAL_MAX_HW_ID     (1UL)

#endif /* SGMIIPCIE_DIGITAL_RDB_H */
