/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_rx_x4_rdb.h
    @brief RDB File for SGMIIPLUSR_RX_X4

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_RX_X4_RDB_H
#define SGMIIPLUSR_RX_X4_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPLUSR_RX_X4_PCS_CONTROL_0_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_RX_X4_PCS_CONTROL_0_SGMIIPLUSR_X1_LPI_ENABLE_MASK (0x4U)
#define SGMIIPLUSR_RX_X4_PCS_CONTROL_0_SGMIIPLUSR_X1_LPI_ENABLE_SHIFT (2U)




typedef uint16_t SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_FEC_ERR_ENABLE_MASK (0x2000U)
#define SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_FEC_ERR_ENABLE_SHIFT (13U)
#define SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_ERROR_EN_OVR_MASK (0x1000U)
#define SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_ERROR_EN_OVR_SHIFT (12U)
#define SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_ERROR_EN_OVR_VAL_MASK (0x800U)
#define SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_ERROR_EN_OVR_VAL_SHIFT (11U)
#define SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_DBG_ENABLE_MASK (0x400U)
#define SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_DBG_ENABLE_SHIFT (10U)
#define SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_FAST_LOCK_EN_MASK (0x200U)
#define SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_FAST_LOCK_EN_SHIFT (9U)




typedef uint16_t SGMIIPLUSR_RX_X4_F1SX1_TYPE;
#define SGMIIPLUSR_RX_X4_F1SX1_FEC_ERROR_CODE_ALL_MASK (0x8000U)
#define SGMIIPLUSR_RX_X4_F1SX1_FEC_ERROR_CODE_ALL_SHIFT (15U)
#define SGMIIPLUSR_RX_X4_F1SX1_GOOD_PARITY_CNT_MASK (0x7000U)
#define SGMIIPLUSR_RX_X4_F1SX1_GOOD_PARITY_CNT_SHIFT (12U)
#define SGMIIPLUSR_RX_X4_F1SX1_INVALID_PARITY_CNT_MASK (0xf00U)
#define SGMIIPLUSR_RX_X4_F1SX1_INVALID_PARITY_CNT_SHIFT (8U)
#define SGMIIPLUSR_RX_X4_F1SX1_DEC_MAX_PM_MASK (0xfcU)
#define SGMIIPLUSR_RX_X4_F1SX1_DEC_MAX_PM_SHIFT (2U)
#define SGMIIPLUSR_RX_X4_F1SX1_BURST_ERR_STATUS_MODE_MASK (0x2U)
#define SGMIIPLUSR_RX_X4_F1SX1_BURST_ERR_STATUS_MODE_SHIFT (1U)
#define SGMIIPLUSR_RX_X4_F1SX1_DBG_ERR_MODE_MASK (0x1U)
#define SGMIIPLUSR_RX_X4_F1SX1_DBG_ERR_MODE_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_X4_F2SX1_TYPE;
#define SGMIIPLUSR_RX_X4_F2SX1_DEC_PM_MODE_MASK (0xf800U)
#define SGMIIPLUSR_RX_X4_F2SX1_DEC_PM_MODE_SHIFT (11U)
#define SGMIIPLUSR_RX_X4_F2SX1_DEC_18B_BURST_GAP_COUNT_MASK (0xe0U)
#define SGMIIPLUSR_RX_X4_F2SX1_DEC_18B_BURST_GAP_COUNT_SHIFT (5U)
#define SGMIIPLUSR_RX_X4_F2SX1_DEC_17B_BURST_GAP_COUNT_MASK (0x1cU)
#define SGMIIPLUSR_RX_X4_F2SX1_DEC_17B_BURST_GAP_COUNT_SHIFT (2U)
#define SGMIIPLUSR_RX_X4_F2SX1_DEC_GAP_COUNT_MODE_MASK (0x2U)
#define SGMIIPLUSR_RX_X4_F2SX1_DEC_GAP_COUNT_MODE_SHIFT (1U)




typedef uint16_t SGMIIPLUSR_RX_X4_DC0SX1_TYPE;
#define SGMIIPLUSR_RX_X4_DC0SX1_BYPASS_CL49RXSM_MASK (0x8000U)
#define SGMIIPLUSR_RX_X4_DC0SX1_BYPASS_CL49RXSM_SHIFT (15U)
#define SGMIIPLUSR_RX_X4_DC0SX1_R_TEST_MODE_CFG_MASK (0x4000U)
#define SGMIIPLUSR_RX_X4_DC0SX1_R_TEST_MODE_CFG_SHIFT (14U)
#define SGMIIPLUSR_RX_X4_DC0SX1_HG2_MESSAGE_INVALID_CODE_ENABLE_MASK (0x2000U)
#define SGMIIPLUSR_RX_X4_DC0SX1_HG2_MESSAGE_INVALID_CODE_ENABLE_SHIFT (13U)
#define SGMIIPLUSR_RX_X4_DC0SX1_HG2_ENABLE_MASK (0x1000U)
#define SGMIIPLUSR_RX_X4_DC0SX1_HG2_ENABLE_SHIFT (12U)
#define SGMIIPLUSR_RX_X4_DC0SX1_DISABLE_CL49_BERMON_MASK (0x100U)
#define SGMIIPLUSR_RX_X4_DC0SX1_DISABLE_CL49_BERMON_SHIFT (8U)
#define SGMIIPLUSR_RX_X4_DC0SX1_CL49_RX_LI_ENABLE_MASK (0x40U)
#define SGMIIPLUSR_RX_X4_DC0SX1_CL49_RX_LI_ENABLE_SHIFT (6U)
#define SGMIIPLUSR_RX_X4_DC0SX1_CL49_RX_LF_ENABLE_MASK (0x20U)
#define SGMIIPLUSR_RX_X4_DC0SX1_CL49_RX_LF_ENABLE_SHIFT (5U)
#define SGMIIPLUSR_RX_X4_DC0SX1_CL49_RX_RF_ENABLE_MASK (0x10U)
#define SGMIIPLUSR_RX_X4_DC0SX1_CL49_RX_RF_ENABLE_SHIFT (4U)
#define SGMIIPLUSR_RX_X4_DC0SX1_CL127_RX_ALIGN_FSM_RESET_MASK (0x8U)
#define SGMIIPLUSR_RX_X4_DC0SX1_CL127_RX_ALIGN_FSM_RESET_SHIFT (3U)
#define SGMIIPLUSR_RX_X4_DC0SX1_BLOCK_SYNC_MODE_MASK (0x7U)
#define SGMIIPLUSR_RX_X4_DC0SX1_BLOCK_SYNC_MODE_SHIFT (0U)




typedef uint8_t SGMIIPLUSR_RX_X4_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_RX_X4_C36R0SX1_TYPE;
#define SGMIIPLUSR_RX_X4_C36R0SX1_CL36_BER_EN_MASK (0x20U)
#define SGMIIPLUSR_RX_X4_C36R0SX1_CL36_BER_EN_SHIFT (5U)
#define SGMIIPLUSR_RX_X4_C36R0SX1_CL36_FORCE_COMMA_ALIGN_ENABLE_MASK (0x8U)
#define SGMIIPLUSR_RX_X4_C36R0SX1_CL36_FORCE_COMMA_ALIGN_ENABLE_SHIFT (3U)
#define SGMIIPLUSR_RX_X4_C36R0SX1_DISABLE_CARRIER_EXTEND_MASK (0x4U)
#define SGMIIPLUSR_RX_X4_C36R0SX1_DISABLE_CARRIER_EXTEND_SHIFT (2U)




typedef uint16_t SGMIIPLUSR_RX_X4_PC0SX1_TYPE;
#define SGMIIPLUSR_RX_X4_PC0SX1_RX_GBOX_DV_EDGE_CYA_MASK (0x40U)
#define SGMIIPLUSR_RX_X4_PC0SX1_RX_GBOX_DV_EDGE_CYA_SHIFT (6U)
#define SGMIIPLUSR_RX_X4_PC0SX1_RX_FIFO_WATERMARK_MASK (0x30U)
#define SGMIIPLUSR_RX_X4_PC0SX1_RX_FIFO_WATERMARK_SHIFT (4U)
#define SGMIIPLUSR_RX_X4_PC0SX1_RX_GBOX_PRST_MASK (0x8U)
#define SGMIIPLUSR_RX_X4_PC0SX1_RX_GBOX_PRST_SHIFT (3U)
#define SGMIIPLUSR_RX_X4_PC0SX1_RX_GBOX_ERR_DET_CLR_MASK (0x4U)
#define SGMIIPLUSR_RX_X4_PC0SX1_RX_GBOX_ERR_DET_CLR_SHIFT (2U)
#define SGMIIPLUSR_RX_X4_PC0SX1_RX_GBOX_AFRST_EN_MASK (0x2U)
#define SGMIIPLUSR_RX_X4_PC0SX1_RX_GBOX_AFRST_EN_SHIFT (1U)
#define SGMIIPLUSR_RX_X4_PC0SX1_RSTB_LANE_MASK (0x1U)
#define SGMIIPLUSR_RX_X4_PC0SX1_RSTB_LANE_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_X4_RSSX1_TYPE;
#define SGMIIPLUSR_RX_X4_RSSX1_ENABLE_EXT_SIGNAL_DETECT_FILTERING_MASK (0x200U)
#define SGMIIPLUSR_RX_X4_RSSX1_ENABLE_EXT_SIGNAL_DETECT_FILTERING_SHIFT (9U)
#define SGMIIPLUSR_RX_X4_RSSX1_USE_CX4_SIGNAL_DETECT_FILTER_SEL_MASK (0x100U)
#define SGMIIPLUSR_RX_X4_RSSX1_USE_CX4_SIGNAL_DETECT_FILTER_SEL_SHIFT (8U)
#define SGMIIPLUSR_RX_X4_RSSX1_EXTERNAL_SIGNAL_DETECT_INVERT_MASK (0x40U)
#define SGMIIPLUSR_RX_X4_RSSX1_EXTERNAL_SIGNAL_DETECT_INVERT_SHIFT (6U)
#define SGMIIPLUSR_RX_X4_RSSX1_AFE_SIGNAL_DETECT_INVERT_MASK (0x20U)
#define SGMIIPLUSR_RX_X4_RSSX1_AFE_SIGNAL_DETECT_INVERT_SHIFT (5U)
#define SGMIIPLUSR_RX_X4_RSSX1_EXTERNAL_SIGNAL_DETECT_ENABLE_MASK (0x10U)
#define SGMIIPLUSR_RX_X4_RSSX1_EXTERNAL_SIGNAL_DETECT_ENABLE_SHIFT (4U)
#define SGMIIPLUSR_RX_X4_RSSX1_AFE_SIGNAL_DETECT_ENABLE_MASK (0x8U)
#define SGMIIPLUSR_RX_X4_RSSX1_AFE_SIGNAL_DETECT_ENABLE_SHIFT (3U)
#define SGMIIPLUSR_RX_X4_RSSX1_OVERRIDE_SIGNAL_OK_MASK (0x4U)
#define SGMIIPLUSR_RX_X4_RSSX1_OVERRIDE_SIGNAL_OK_SHIFT (2U)
#define SGMIIPLUSR_RX_X4_RSSX1_OVERRIDE_VALUE_SIGNAL_OK_MASK (0x2U)
#define SGMIIPLUSR_RX_X4_RSSX1_OVERRIDE_VALUE_SIGNAL_OK_SHIFT (1U)
#define SGMIIPLUSR_RX_X4_RSSX1_ENABLE_AFE_SIGNAL_DETECT_FILTERING_MASK (0x1U)
#define SGMIIPLUSR_RX_X4_RSSX1_ENABLE_AFE_SIGNAL_DETECT_FILTERING_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_X4_LCSX1_TYPE;
#define SGMIIPLUSR_RX_X4_LCSX1_LATCH_LINKDOWN_ENABLE_MASK (0x1U)
#define SGMIIPLUSR_RX_X4_LCSX1_LATCH_LINKDOWN_ENABLE_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_X4_C722PSX1_TYPE;
#define SGMIIPLUSR_RX_X4_C722PSX1_AN_TX_DISABLE_EN_MASK (0x2U)
#define SGMIIPLUSR_RX_X4_C722PSX1_AN_TX_DISABLE_EN_SHIFT (1U)
#define SGMIIPLUSR_RX_X4_C722PSX1_CL72_RX_TRAINED_MASK (0x1U)
#define SGMIIPLUSR_RX_X4_C722PSX1_CL72_RX_TRAINED_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_X4_BLOCKADDRESS_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_RX_X4_BLOCKADDRESS_SGMIIPLUSR_X1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_RX_X4_BLOCKADDRESS_SGMIIPLUSR_X1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_RX_X4_RDBType {
    SGMIIPLUSR_RX_X4_PCS_CONTROL_0_SGMIIPLUSR_X1_TYPE pcs_control_0; /* OFFSET: 0x0 */
    SGMIIPLUSR_RX_X4_FEC_0_SGMIIPLUSR_X1_TYPE fec_0; /* OFFSET: 0x2 */
    SGMIIPLUSR_RX_X4_F1SX1_TYPE fec_1; /* OFFSET: 0x4 */
    SGMIIPLUSR_RX_X4_F2SX1_TYPE fec_2; /* OFFSET: 0x6 */
    SGMIIPLUSR_RX_X4_DC0SX1_TYPE decode_control_0; /* OFFSET: 0x8 */
    SGMIIPLUSR_RX_X4_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0xa */
    SGMIIPLUSR_RX_X4_C36R0SX1_TYPE cl36_rx_0; /* OFFSET: 0xc */
    SGMIIPLUSR_RX_X4_PC0SX1_TYPE pma_control_0; /* OFFSET: 0xe */
    SGMIIPLUSR_RX_X4_RSSX1_TYPE rx_sigdet; /* OFFSET: 0x10 */
    SGMIIPLUSR_RX_X4_LCSX1_TYPE link_control; /* OFFSET: 0x12 */
    SGMIIPLUSR_RX_X4_C722PSX1_TYPE cl72_2_pmd; /* OFFSET: 0x14 */
    SGMIIPLUSR_RX_X4_RESERVED_TYPE rsvd1[8]; /* OFFSET: 0x16 */
    SGMIIPLUSR_RX_X4_BLOCKADDRESS_SGMIIPLUSR_X1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_RX_X4_RDBType;


#define RX_X4_CONTROL0_BASE             (0x4AED88A0UL)



#define SGMIIPLUSR_RX_X4_MAX_HW_ID      (1UL)

#endif /* SGMIIPLUSR_RX_X4_RDB_H */
