/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_an_x4_rdb.h
    @brief RDB File for SGMIIPLUSR_AN_X4

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_AN_X4_RDB_H
#define SGMIIPLUSR_AN_X4_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPLUSR_AN_X4_ESX1_TYPE;
#define SGMIIPLUSR_AN_X4_ESX1_AN_SETUP_ENABLE_MASK (0x4000U)
#define SGMIIPLUSR_AN_X4_ESX1_AN_SETUP_ENABLE_SHIFT (14U)
#define SGMIIPLUSR_AN_X4_ESX1_NUM_ADVERTISED_LANES_MASK (0x3000U)
#define SGMIIPLUSR_AN_X4_ESX1_NUM_ADVERTISED_LANES_SHIFT (12U)
#define SGMIIPLUSR_AN_X4_ESX1_CL37_BAM_ENABLE_MASK (0x800U)
#define SGMIIPLUSR_AN_X4_ESX1_CL37_BAM_ENABLE_SHIFT (11U)
#define SGMIIPLUSR_AN_X4_ESX1_CL73_BAM_ENABLE_MASK (0x400U)
#define SGMIIPLUSR_AN_X4_ESX1_CL73_BAM_ENABLE_SHIFT (10U)
#define SGMIIPLUSR_AN_X4_ESX1_CL73_HPAM_ENABLE_MASK (0x200U)
#define SGMIIPLUSR_AN_X4_ESX1_CL73_HPAM_ENABLE_SHIFT (9U)
#define SGMIIPLUSR_AN_X4_ESX1_CL73_ENABLE_MASK (0x100U)
#define SGMIIPLUSR_AN_X4_ESX1_CL73_ENABLE_SHIFT (8U)
#define SGMIIPLUSR_AN_X4_ESX1_CL37_SGMII_ENABLE_MASK (0x80U)
#define SGMIIPLUSR_AN_X4_ESX1_CL37_SGMII_ENABLE_SHIFT (7U)
#define SGMIIPLUSR_AN_X4_ESX1_CL37_ENABLE_MASK (0x40U)
#define SGMIIPLUSR_AN_X4_ESX1_CL37_ENABLE_SHIFT (6U)
#define SGMIIPLUSR_AN_X4_ESX1_CL37_BAM_TO_SGMII_AUTO_ENABLE_MASK (0x20U)
#define SGMIIPLUSR_AN_X4_ESX1_CL37_BAM_TO_SGMII_AUTO_ENABLE_SHIFT (5U)
#define SGMIIPLUSR_AN_X4_ESX1_SGMII_TO_CL37_AUTO_ENABLE_MASK (0x10U)
#define SGMIIPLUSR_AN_X4_ESX1_SGMII_TO_CL37_AUTO_ENABLE_SHIFT (4U)
#define SGMIIPLUSR_AN_X4_ESX1_CL73_BAM_TO_HPAM_AUTO_ENABLE_MASK (0x8U)
#define SGMIIPLUSR_AN_X4_ESX1_CL73_BAM_TO_HPAM_AUTO_ENABLE_SHIFT (3U)
#define SGMIIPLUSR_AN_X4_ESX1_HPAM_TO_CL73_AUTO_ENABLE_MASK (0x4U)
#define SGMIIPLUSR_AN_X4_ESX1_HPAM_TO_CL73_AUTO_ENABLE_SHIFT (2U)
#define SGMIIPLUSR_AN_X4_ESX1_CL37_AN_RESTART_MASK (0x2U)
#define SGMIIPLUSR_AN_X4_ESX1_CL37_AN_RESTART_SHIFT (1U)
#define SGMIIPLUSR_AN_X4_ESX1_CL73_AN_RESTART_MASK (0x1U)
#define SGMIIPLUSR_AN_X4_ESX1_CL73_AN_RESTART_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X4_LDC37BASX1_TYPE;
#define SGMIIPLUSR_AN_X4_LDC37BASX1_SGMII_MASTER_MODE_MASK (0x200U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_SGMII_MASTER_MODE_SHIFT (9U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_CL37_NEXT_PAGE_MASK (0x100U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_CL37_NEXT_PAGE_SHIFT (8U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_CL37_PAUSE_MASK (0xc0U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_CL37_PAUSE_SHIFT (6U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_CL37_HALF_DUPLEX_MASK (0x20U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_CL37_HALF_DUPLEX_SHIFT (5U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_CL37_FULL_DUPLEX_MASK (0x10U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_CL37_FULL_DUPLEX_SHIFT (4U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_SGMII_FULL_DUPLEX_MASK (0x4U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_SGMII_FULL_DUPLEX_SHIFT (2U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_SGMII_SPEED_MASK (0x3U)
#define SGMIIPLUSR_AN_X4_LDC37BASX1_SGMII_SPEED_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X4_LDC37BASX11_TYPE;
#define SGMIIPLUSR_AN_X4_LDC37BASX11_CL37_BAM_CODE_MASK (0xff8U)
#define SGMIIPLUSR_AN_X4_LDC37BASX11_CL37_BAM_CODE_SHIFT (3U)
#define SGMIIPLUSR_AN_X4_LDC37BASX11_OVER1G_ABILITY_MASK (0x4U)
#define SGMIIPLUSR_AN_X4_LDC37BASX11_OVER1G_ABILITY_SHIFT (2U)
#define SGMIIPLUSR_AN_X4_LDC37BASX11_OVER1G_PAGE_COUNT_MASK (0x3U)
#define SGMIIPLUSR_AN_X4_LDC37BASX11_OVER1G_PAGE_COUNT_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X4_LDO1A1SX1_TYPE;
#define SGMIIPLUSR_AN_X4_LDO1A1SX1_HG2_MASK (0x8000U)
#define SGMIIPLUSR_AN_X4_LDO1A1SX1_HG2_SHIFT (15U)
#define SGMIIPLUSR_AN_X4_LDO1A1SX1_FEC_MASK (0x4000U)
#define SGMIIPLUSR_AN_X4_LDO1A1SX1_FEC_SHIFT (14U)




typedef uint16_t SGMIIPLUSR_AN_X4_LDO1A0SX1_TYPE;
#define SGMIIPLUSR_AN_X4_LDO1A0SX1_BAM_2P5GBASE_X_MASK (0x1U)
#define SGMIIPLUSR_AN_X4_LDO1A0SX1_BAM_2P5GBASE_X_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X4_LDC73BA1SX1_TYPE;
#define SGMIIPLUSR_AN_X4_LDC73BA1SX1_CL73_NONCE_MATCH_OVER_MASK (0x800U)
#define SGMIIPLUSR_AN_X4_LDC73BA1SX1_CL73_NONCE_MATCH_OVER_SHIFT (11U)
#define SGMIIPLUSR_AN_X4_LDC73BA1SX1_CL73_NONCE_MATCH_VAL_MASK (0x400U)
#define SGMIIPLUSR_AN_X4_LDC73BA1SX1_CL73_NONCE_MATCH_VAL_SHIFT (10U)
#define SGMIIPLUSR_AN_X4_LDC73BA1SX1_TRANSMIT_NONCE_MASK (0x3e0U)
#define SGMIIPLUSR_AN_X4_LDC73BA1SX1_TRANSMIT_NONCE_SHIFT (5U)
#define SGMIIPLUSR_AN_X4_LDC73BA1SX1_BASE_SELECTOR_MASK (0x1fU)
#define SGMIIPLUSR_AN_X4_LDC73BA1SX1_BASE_SELECTOR_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X4_LDC73BA0SX1_TYPE;
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_CL73_REMOTE_FAULT_MASK (0x800U)
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_CL73_REMOTE_FAULT_SHIFT (11U)
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_NEXT_PAGE_MASK (0x400U)
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_NEXT_PAGE_SHIFT (10U)
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_FEC_MASK (0x300U)
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_FEC_SHIFT (8U)
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_CL73_PAUSE_MASK (0xc0U)
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_CL73_PAUSE_SHIFT (6U)
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_BASE_1000BASE_KX_MASK (0x20U)
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_BASE_1000BASE_KX_SHIFT (5U)
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_BASE_10GBASE_KR_MASK (0x8U)
#define SGMIIPLUSR_AN_X4_LDC73BA0SX1_BASE_10GBASE_KR_SHIFT (3U)




typedef uint16_t SGMIIPLUSR_AN_X4_LDC73BASX1_TYPE;
#define SGMIIPLUSR_AN_X4_LDC73BASX1_CL73_BAM_CODE_MASK (0x7fcU)
#define SGMIIPLUSR_AN_X4_LDC73BASX1_CL73_BAM_CODE_SHIFT (2U)




typedef uint16_t SGMIIPLUSR_AN_X4_CSX1_TYPE;
#define SGMIIPLUSR_AN_X4_CSX1_OUI_CONTROL_MASK (0xfc00U)
#define SGMIIPLUSR_AN_X4_CSX1_OUI_CONTROL_SHIFT (10U)
#define SGMIIPLUSR_AN_X4_CSX1_AN_FAIL_COUNT_LIMIT_MASK (0x3c0U)
#define SGMIIPLUSR_AN_X4_CSX1_AN_FAIL_COUNT_LIMIT_SHIFT (6U)
#define SGMIIPLUSR_AN_X4_CSX1_LINKFAILTIMERQUAL_EN_MASK (0x20U)
#define SGMIIPLUSR_AN_X4_CSX1_LINKFAILTIMERQUAL_EN_SHIFT (5U)
#define SGMIIPLUSR_AN_X4_CSX1_LINKFAILTIMER_DIS_MASK (0x10U)
#define SGMIIPLUSR_AN_X4_CSX1_LINKFAILTIMER_DIS_SHIFT (4U)
#define SGMIIPLUSR_AN_X4_CSX1_AN_GOOD_CHECK_TRAP_MASK (0x8U)
#define SGMIIPLUSR_AN_X4_CSX1_AN_GOOD_CHECK_TRAP_SHIFT (3U)
#define SGMIIPLUSR_AN_X4_CSX1_AN_GOOD_TRAP_MASK (0x4U)
#define SGMIIPLUSR_AN_X4_CSX1_AN_GOOD_TRAP_SHIFT (2U)
#define SGMIIPLUSR_AN_X4_CSX1_PD_KX_EN_MASK (0x2U)
#define SGMIIPLUSR_AN_X4_CSX1_PD_KX_EN_SHIFT (1U)




typedef uint16_t SGMIIPLUSR_AN_X4_PLMSX1_TYPE;
#define SGMIIPLUSR_AN_X4_PLMSX1_AX4APLORO_MASK (0x200U)
#define SGMIIPLUSR_AN_X4_PLMSX1_AX4APLORO_SHIFT (9U)
#define SGMIIPLUSR_AN_X4_PLMSX1_PLMSX1O_MASK (0x100U)
#define SGMIIPLUSR_AN_X4_PLMSX1_PLMSX1O_SHIFT (8U)
#define SGMIIPLUSR_AN_X4_PLMSX1_PMD_LN_MODE_SGMIIPLUSR_X1_MASK (0xffU)
#define SGMIIPLUSR_AN_X4_PLMSX1_PMD_LN_MODE_SGMIIPLUSR_X1_SHIFT (0U)




typedef uint8_t SGMIIPLUSR_AN_X4_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_AN_X4_BLOCKADDRESS_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_AN_X4_BLOCKADDRESS_SGMIIPLUSR_X1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_AN_X4_BLOCKADDRESS_SGMIIPLUSR_X1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_AN_X4_RDBType {
    SGMIIPLUSR_AN_X4_ESX1_TYPE enables_sgmiiplusr_x1; /* OFFSET: 0x0 */
    SGMIIPLUSR_AN_X4_LDC37BASX1_TYPE local_device_cl37_base_abilities_sgmiiplusr_x1; /* OFFSET: 0x2 */
    SGMIIPLUSR_AN_X4_LDC37BASX11_TYPE local_device_cl37_bam_abilities_sgmiiplusr_x1; /* OFFSET: 0x4 */
    SGMIIPLUSR_AN_X4_LDO1A1SX1_TYPE local_device_over1g_abilities_1_sgmiiplusr_x1; /* OFFSET: 0x6 */
    SGMIIPLUSR_AN_X4_LDO1A0SX1_TYPE local_device_over1g_abilities_0_sgmiiplusr_x1; /* OFFSET: 0x8 */
    SGMIIPLUSR_AN_X4_LDC73BA1SX1_TYPE local_device_cl73_base_abilities_1_sgmiiplusr_x1; /* OFFSET: 0xa */
    SGMIIPLUSR_AN_X4_LDC73BA0SX1_TYPE local_device_cl73_base_abilities_0_sgmiiplusr_x1; /* OFFSET: 0xc */
    SGMIIPLUSR_AN_X4_LDC73BASX1_TYPE local_device_cl73_bam_abilities_sgmiiplusr_x1; /* OFFSET: 0xe */
    SGMIIPLUSR_AN_X4_CSX1_TYPE controls_sgmiiplusr_x1; /* OFFSET: 0x10 */
    SGMIIPLUSR_AN_X4_PLMSX1_TYPE pmd_ln_mode_sgmiiplusr_x1; /* OFFSET: 0x12 */
    SGMIIPLUSR_AN_X4_RESERVED_TYPE rsvd0[10]; /* OFFSET: 0x14 */
    SGMIIPLUSR_AN_X4_BLOCKADDRESS_SGMIIPLUSR_X1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_AN_X4_RDBType;


#define AN_X4_ABILITIES_BASE            (0x4AED8900UL)



#define SGMIIPLUSR_AN_X4_MAX_HW_ID      (1UL)

#endif /* SGMIIPLUSR_AN_X4_RDB_H */
