/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_an_x1_timers_rdb.h
    @brief RDB File for SGMIIPLUSR_AN_X1_TIMERS

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_AN_X1_TIMERS_RDB_H
#define SGMIIPLUSR_AN_X1_TIMERS_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_C37RSX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_C37RSX1_CL37_RESTART_TIMER_PERIOD_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_C37RSX1_CL37_RESTART_TIMER_PERIOD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_C37ASX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_C37ASX1_CL37_ACK_TIMER_PERIOD_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_C37ASX1_CL37_ACK_TIMER_PERIOD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_C37ESX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_C37ESX1_CL37_ERROR_TIMER_PERIOD_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_C37ESX1_CL37_ERROR_TIMER_PERIOD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_C73BLSX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_C73BLSX1_TX_DISABLE_TIMER_PERIOD_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_C73BLSX1_TX_DISABLE_TIMER_PERIOD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_C73ESX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_C73ESX1_CL73_ERROR_TIMER_PERIOD_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_C73ESX1_CL73_ERROR_TIMER_PERIOD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_C73DLSX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_C73DLSX1_PD_DME_LOCK_TIMER_PERIOD_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_C73DLSX1_PD_DME_LOCK_TIMER_PERIOD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_LUSX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_LUSX1_CL73_LINK_UP_TIMER_PERIOD_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_LUSX1_CL73_LINK_UP_TIMER_PERIOD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_LFITC72SX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_LFITC72SX1_LFITC72P_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_LFITC72SX1_LFITC72P_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_LFITNC72SX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_LFITNC72SX1_LFITN72P_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_LFITNC72SX1_LFITN72P_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_PSTSX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_PSTSX1_PD_SD_TIMER_PERIOD_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_PSTSX1_PD_SD_TIMER_PERIOD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_C72MWTSX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_C72MWTSX1_C72MWTP_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_C72MWTSX1_C72MWTP_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_C72WTSX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_C72WTSX1_CL72_WAIT_TIMER_PERIOD_MASK (0x1ffU)
#define SGMIIPLUSR_AN_X1_TIMERS_C72WTSX1_CL72_WAIT_TIMER_PERIOD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_ILTSX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_ILTSX1_IGNORE_LINK_TIMER_PERIOD_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_ILTSX1_IGNORE_LINK_TIMER_PERIOD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_DPTSX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_DPTSX1_CL73_PAGE_TEST_MAX_TIMER_MASK (0x3f80U)
#define SGMIIPLUSR_AN_X1_TIMERS_DPTSX1_CL73_PAGE_TEST_MAX_TIMER_SHIFT (7U)
#define SGMIIPLUSR_AN_X1_TIMERS_DPTSX1_CL73_PAGE_TEST_MIN_TIMER_MASK (0x7fU)
#define SGMIIPLUSR_AN_X1_TIMERS_DPTSX1_CL73_PAGE_TEST_MIN_TIMER_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_SC73TSX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_SC73TSX1_SGMII_TIMER_MASK (0xffffU)
#define SGMIIPLUSR_AN_X1_TIMERS_SC73TSX1_SGMII_TIMER_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_AN_X1_TIMERS_BSX1_TYPE;
#define SGMIIPLUSR_AN_X1_TIMERS_BSX1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_AN_X1_TIMERS_BSX1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_AN_X1_TIMERS_RDBType {
    SGMIIPLUSR_AN_X1_TIMERS_C37RSX1_TYPE cl37_restart; /* OFFSET: 0x0 */
    SGMIIPLUSR_AN_X1_TIMERS_C37ASX1_TYPE cl37_ack; /* OFFSET: 0x2 */
    SGMIIPLUSR_AN_X1_TIMERS_C37ESX1_TYPE cl37_error; /* OFFSET: 0x4 */
    SGMIIPLUSR_AN_X1_TIMERS_C73BLSX1_TYPE cl73_break_link; /* OFFSET: 0x6 */
    SGMIIPLUSR_AN_X1_TIMERS_C73ESX1_TYPE cl73_error; /* OFFSET: 0x8 */
    SGMIIPLUSR_AN_X1_TIMERS_C73DLSX1_TYPE cl73_dme_lock; /* OFFSET: 0xa */
    SGMIIPLUSR_AN_X1_TIMERS_LUSX1_TYPE link_up; /* OFFSET: 0xc */
    SGMIIPLUSR_AN_X1_TIMERS_LFITC72SX1_TYPE link_fail_inhibit_timer_cl72; /* OFFSET: 0xe */
    SGMIIPLUSR_AN_X1_TIMERS_LFITNC72SX1_TYPE link_fail_inhibit_timer_not_cl72; /* OFFSET: 0x10 */
    SGMIIPLUSR_AN_X1_TIMERS_PSTSX1_TYPE pd_sd_timer; /* OFFSET: 0x12 */
    SGMIIPLUSR_AN_X1_TIMERS_C72MWTSX1_TYPE cl72_max_wait_timer; /* OFFSET: 0x14 */
    SGMIIPLUSR_AN_X1_TIMERS_C72WTSX1_TYPE cl72_wait_timer; /* OFFSET: 0x16 */
    SGMIIPLUSR_AN_X1_TIMERS_ILTSX1_TYPE ignore_link_timer; /* OFFSET: 0x18 */
    SGMIIPLUSR_AN_X1_TIMERS_DPTSX1_TYPE dme_page_timer; /* OFFSET: 0x1a */
    SGMIIPLUSR_AN_X1_TIMERS_SC73TSX1_TYPE sgmii_cl73_timer_type_sgmiiplusr_x1; /* OFFSET: 0x1c */
    SGMIIPLUSR_AN_X1_TIMERS_BSX1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_AN_X1_TIMERS_RDBType;


#define AN_X1_TIMERS_BASE               (0x4AED24A0UL)



#define SGMIIPLUSR_AN_X1_TIMERS_MAX_HW_ID  (1UL)


#define SGMIIPLUSR_AN_X1_CONST0         (0x029AU)


#define SGMIIPLUSR_AN_X1_CONST3         (0xA000U)


#define SGMIIPLUSR_AN_X1_CONST4         (0x10EEU)


#define SGMIIPLUSR_AN_X1_CONST5         (0xA000U)


#define SGMIIPLUSR_AN_X1_CONST6         (0x0BBBU)


#define SGMIIPLUSR_AN_X1_CONST7         (0x1B00U)


#define SGMIIPLUSR_AN_X1_CONST8         (0x8235U)


#define SGMIIPLUSR_AN_X1_CONST9         (0x8235U)


#define SGMIIPLUSR_AN_X1_CONST10        (0x8235U)


#define SGMIIPLUSR_AN_X1_CONST11        (0x000FU)

#endif /* SGMIIPLUSR_AN_X1_TIMERS_RDB_H */
