/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiipcie_ctrl_rdb.h
    @brief RDB File for SGMIIPCIE_CTRL

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPCIE_CTRL_RDB_H
#define SGMIIPCIE_CTRL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t SGMIIPCIE_CTRL_RESERVED_TYPE;




typedef uint16_t SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_GLOOP1G_MASK (0x100U)
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_GLOOP1G_SHIFT (8U)
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_PMD_TXDISABLE_MASK (0x10U)
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_PMD_TXDISABLE_SHIFT (4U)
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_EDEN_MASK (0x8U)
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_EDEN_SHIFT (3U)
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_CDET_MASK (0x4U)
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_CDET_SHIFT (2U)
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_PCS_EN_RX_MASK (0x2U)
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_PCS_EN_RX_SHIFT (1U)
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_PCS_EN_TX_MASK (0x1U)
#define SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_PCS_EN_TX_SHIFT (0U)




typedef uint16_t SGMIIPCIE_CTRL_LANECTRLB_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_CTRL_LANECTRLB_SGMIIPCIE_X1_RX1G_MODE_MASK (0xcU)
#define SGMIIPCIE_CTRL_LANECTRLB_SGMIIPCIE_X1_RX1G_MODE_SHIFT (2U)
#define SGMIIPCIE_CTRL_LANECTRLB_SGMIIPCIE_X1_TX1G_MODE_MASK (0x3U)
#define SGMIIPCIE_CTRL_LANECTRLB_SGMIIPCIE_X1_TX1G_MODE_SHIFT (0U)




typedef uint16_t SGMIIPCIE_CTRL_LANECTRLC_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_CTRL_LANECTRLC_SGMIIPCIE_X1_RESET_RX_MASK (0x200U)
#define SGMIIPCIE_CTRL_LANECTRLC_SGMIIPCIE_X1_RESET_RX_SHIFT (9U)
#define SGMIIPCIE_CTRL_LANECTRLC_SGMIIPCIE_X1_PWRDN_RX_MASK (0x100U)
#define SGMIIPCIE_CTRL_LANECTRLC_SGMIIPCIE_X1_PWRDN_RX_SHIFT (8U)
#define SGMIIPCIE_CTRL_LANECTRLC_SGMIIPCIE_X1_RESET_TX_MASK (0x2U)
#define SGMIIPCIE_CTRL_LANECTRLC_SGMIIPCIE_X1_RESET_TX_SHIFT (1U)
#define SGMIIPCIE_CTRL_LANECTRLC_SGMIIPCIE_X1_PWRDN_TX_MASK (0x1U)
#define SGMIIPCIE_CTRL_LANECTRLC_SGMIIPCIE_X1_PWRDN_TX_SHIFT (0U)




typedef uint16_t SGMIIPCIE_CTRL_BLOCKADDRESS_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_CTRL_BLOCKADDRESS_SGMIIPCIE_X1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPCIE_CTRL_BLOCKADDRESS_SGMIIPCIE_X1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPCIE_CTRL_RDBType {
    SGMIIPCIE_CTRL_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x0 */
    SGMIIPCIE_CTRL_LANECTRLA_SGMIIPCIE_X1_TYPE lanectrl; /* OFFSET: 0x2 */
    SGMIIPCIE_CTRL_LANECTRLB_SGMIIPCIE_X1_TYPE mode1g; /* OFFSET: 0x4 */
    SGMIIPCIE_CTRL_LANECTRLC_SGMIIPCIE_X1_TYPE pwrrst; /* OFFSET: 0x6 */
    SGMIIPCIE_CTRL_RESERVED_TYPE rsvd1[22]; /* OFFSET: 0x8 */
    SGMIIPCIE_CTRL_BLOCKADDRESS_SGMIIPCIE_X1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPCIE_CTRL_RDBType;


#define CTRL_SGMIIPCIE_X1_BASE          (0x4ADD0C00UL)



#define SGMIIPCIE_CTRL_MAX_HW_ID        (1UL)

#endif /* SGMIIPCIE_CTRL_RDB_H */
