/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_rx_pmd_rdb.h
    @brief RDB File for SGMIIPLUSR_RX_PMD

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_RX_PMD_RDB_H
#define SGMIIPLUSR_RX_PMD_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPLUSR_RX_PMD_RTCSX1_TYPE;
#define SGMIIPLUSR_RX_PMD_RTCSX1_FPAT_MD_MASK (0x8000U)
#define SGMIIPLUSR_RX_PMD_RTCSX1_FPAT_MD_SHIFT (15U)
#define SGMIIPLUSR_RX_PMD_RTCSX1_PRBS_CLR_DIS_MASK (0x1000U)
#define SGMIIPLUSR_RX_PMD_RTCSX1_PRBS_CLR_DIS_SHIFT (12U)
#define SGMIIPLUSR_RX_PMD_RTCSX1_EMON_EN_MASK (0x200U)
#define SGMIIPLUSR_RX_PMD_RTCSX1_EMON_EN_SHIFT (9U)
#define SGMIIPLUSR_RX_PMD_RTCSX1_PRBSMON_EN_MASK (0x10U)
#define SGMIIPLUSR_RX_PMD_RTCSX1_PRBSMON_EN_SHIFT (4U)
#define SGMIIPLUSR_RX_PMD_RTCSX1_PRBSMON_INV_MASK (0x8U)
#define SGMIIPLUSR_RX_PMD_RTCSX1_PRBSMON_INV_SHIFT (3U)
#define SGMIIPLUSR_RX_PMD_RTCSX1_PRBSMON_ORDER_MASK (0x7U)
#define SGMIIPLUSR_RX_PMD_RTCSX1_PRBSMON_ORDER_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_PMD_RTSSX1_TYPE;
#define SGMIIPLUSR_RX_PMD_RTSSX1_PRBS_LOCK_MASK (0x8000U)
#define SGMIIPLUSR_RX_PMD_RTSSX1_PRBS_LOCK_SHIFT (15U)
#define SGMIIPLUSR_RX_PMD_RTSSX1_PRBS_STKY_MASK (0x4000U)
#define SGMIIPLUSR_RX_PMD_RTSSX1_PRBS_STKY_SHIFT (14U)
#define SGMIIPLUSR_RX_PMD_RTSSX1_PRBS_ERRORS_MASK (0x3fffU)
#define SGMIIPLUSR_RX_PMD_RTSSX1_PRBS_ERRORS_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_PMD_RC0SX1_TYPE;
#define SGMIIPLUSR_RX_PMD_RC0SX1_PMD_RLOOPBACK_MASK (0x8000U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_PMD_RLOOPBACK_SHIFT (15U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_PMD_GLOOPBACK_MASK (0x4000U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_PMD_GLOOPBACK_SHIFT (14U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_RXPOL_FLIP_SM_MASK (0x200U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_RXPOL_FLIP_SM_SHIFT (9U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_LOCK_REF_MASK (0x100U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_LOCK_REF_SHIFT (8U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_PHASE_SEL_SM_MASK (0x80U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_PHASE_SEL_SM_SHIFT (7U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_FREQ_SEL_MASK (0x40U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_FREQ_SEL_SHIFT (6U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_FREQ_SEL_FORCE_SM_MASK (0x20U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_FREQ_SEL_FORCE_SM_SHIFT (5U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_FREQ_SEL_SM_MASK (0x10U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_FREQ_SEL_SM_SHIFT (4U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_RXCK_MII_GEN_SEL_FORCE_MASK (0x8U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_RXCK_MII_GEN_SEL_FORCE_SHIFT (3U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_FORCERXSEQDONE_SM_MASK (0x4U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_FORCERXSEQDONE_SM_SHIFT (2U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_FLIP_EYEMON_POLARITY_MASK (0x2U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_FLIP_EYEMON_POLARITY_SHIFT (1U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_CRC_CHECKER_DISABLE_MASK (0x1U)
#define SGMIIPLUSR_RX_PMD_RC0SX1_CRC_CHECKER_DISABLE_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_PMD_RC1SX1_TYPE;
#define SGMIIPLUSR_RX_PMD_RC1SX1_RX_PF_CTRL_MASK (0xf000U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_RX_PF_CTRL_SHIFT (12U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_RXSEQRESTART_SM_MASK (0x800U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_RXSEQRESTART_SM_SHIFT (11U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_RXSIGDETPWRDN_OVERRIDE_VAL_MASK (0x400U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_RXSIGDETPWRDN_OVERRIDE_VAL_SHIFT (10U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_RXSIGDETPWRDN_OVERRIDE_MASK (0x200U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_RXSIGDETPWRDN_OVERRIDE_SHIFT (9U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_SIGDETECTED_EN_SM_MASK (0x100U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_SIGDETECTED_EN_SM_SHIFT (8U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_SIGDETRESTART_EN_SM_MASK (0x80U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_SIGDETRESTART_EN_SM_SHIFT (7U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_SIGDETMONITOR_EN_SM_MASK (0x40U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_SIGDETMONITOR_EN_SM_SHIFT (6U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_RXSEQDONE_CYA_MASK (0x20U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_RXSEQDONE_CYA_SHIFT (5U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_SPD_RSTB_DIS_SM_MASK (0x10U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_SPD_RSTB_DIS_SM_SHIFT (4U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_RTBI_MODE_MASK (0x8U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_RTBI_MODE_SHIFT (3U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_INDCK_MODE_EN_RX_MASK (0x4U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_INDCK_MODE_EN_RX_SHIFT (2U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_COMBO_MODE_EN_RX_MASK (0x2U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_COMBO_MODE_EN_RX_SHIFT (1U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_CL36_PCS_EN_RX_MASK (0x1U)
#define SGMIIPLUSR_RX_PMD_RC1SX1_CL36_PCS_EN_RX_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_PMD_RC2SX1_TYPE;
#define SGMIIPLUSR_RX_PMD_RC2SX1_SIGDET_MUX_SM_MASK (0xf000U)
#define SGMIIPLUSR_RX_PMD_RC2SX1_SIGDET_MUX_SM_SHIFT (12U)
#define SGMIIPLUSR_RX_PMD_RC2SX1_TPCTRL_SM_MASK (0x1f0U)
#define SGMIIPLUSR_RX_PMD_RC2SX1_TPCTRL_SM_SHIFT (4U)
#define SGMIIPLUSR_RX_PMD_RC2SX1_TESTMUXSELECT_SM_MASK (0xfU)
#define SGMIIPLUSR_RX_PMD_RC2SX1_TESTMUXSELECT_SM_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_PMD_RSC0SX1_TYPE;
#define SGMIIPLUSR_RX_PMD_RSC0SX1_INVERT_RX_SIGDET_MASK (0x20U)
#define SGMIIPLUSR_RX_PMD_RSC0SX1_INVERT_RX_SIGDET_SHIFT (5U)
#define SGMIIPLUSR_RX_PMD_RSC0SX1_CX4_SIGDET_CNT_LD_SM_MASK (0x10U)
#define SGMIIPLUSR_RX_PMD_RSC0SX1_CX4_SIGDET_CNT_LD_SM_SHIFT (4U)
#define SGMIIPLUSR_RX_PMD_RSC0SX1_CX4_SIGDET_EN_SM_MASK (0x8U)
#define SGMIIPLUSR_RX_PMD_RSC0SX1_CX4_SIGDET_EN_SM_SHIFT (3U)
#define SGMIIPLUSR_RX_PMD_RSC0SX1_EXT_SIGDET_EN_SM_MASK (0x4U)
#define SGMIIPLUSR_RX_PMD_RSC0SX1_EXT_SIGDET_EN_SM_SHIFT (2U)
#define SGMIIPLUSR_RX_PMD_RSC0SX1_OVERRIDE_SIGDET_EN_SM_MASK (0x2U)
#define SGMIIPLUSR_RX_PMD_RSC0SX1_OVERRIDE_SIGDET_EN_SM_SHIFT (1U)
#define SGMIIPLUSR_RX_PMD_RSC0SX1_OVERRIDE_SIGDET_VAL_SM_MASK (0x1U)
#define SGMIIPLUSR_RX_PMD_RSC0SX1_OVERRIDE_SIGDET_VAL_SM_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_PMD_RSC1SX1_TYPE;
#define SGMIIPLUSR_RX_PMD_RSC1SX1_CX4_SIGDET_CNT_MASK (0xffffU)
#define SGMIIPLUSR_RX_PMD_RSC1SX1_CX4_SIGDET_CNT_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_PMD_RSSSX1_TYPE;
#define SGMIIPLUSR_RX_PMD_RSSSX1_RX_OS_MODE_MUXVAL_MASK (0x3cU)
#define SGMIIPLUSR_RX_PMD_RSSSX1_RX_OS_MODE_MUXVAL_SHIFT (2U)
#define SGMIIPLUSR_RX_PMD_RSSSX1_OS_1X_MODE_MASK (0x2U)
#define SGMIIPLUSR_RX_PMD_RSSSX1_OS_1X_MODE_SHIFT (1U)
#define SGMIIPLUSR_RX_PMD_RSSSX1_PMD_SIGDET_STATUS_MASK (0x1U)
#define SGMIIPLUSR_RX_PMD_RSSSX1_PMD_SIGDET_STATUS_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_PMD_RC3SX1_TYPE;
#define SGMIIPLUSR_RX_PMD_RC3SX1_OS_1X_MODE_OVERRIDE_VAL_MASK (0x40U)
#define SGMIIPLUSR_RX_PMD_RC3SX1_OS_1X_MODE_OVERRIDE_VAL_SHIFT (6U)
#define SGMIIPLUSR_RX_PMD_RC3SX1_OS_1X_MODE_OVERRIDE_MASK (0x20U)
#define SGMIIPLUSR_RX_PMD_RC3SX1_OS_1X_MODE_OVERRIDE_SHIFT (5U)
#define SGMIIPLUSR_RX_PMD_RC3SX1_OS_MODE_RX_PMD_OVERRIDE_MASK (0x10U)
#define SGMIIPLUSR_RX_PMD_RC3SX1_OS_MODE_RX_PMD_OVERRIDE_SHIFT (4U)
#define SGMIIPLUSR_RX_PMD_RC3SX1_OS_MODE_RX_PMD_MASK (0xfU)
#define SGMIIPLUSR_RX_PMD_RC3SX1_OS_MODE_RX_PMD_SHIFT (0U)




typedef uint8_t SGMIIPLUSR_RX_PMD_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_RX_PMD_BLOCKADDRESS_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_RX_PMD_BLOCKADDRESS_SGMIIPLUSR_X1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_RX_PMD_BLOCKADDRESS_SGMIIPLUSR_X1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_RX_PMD_RDBType {
    SGMIIPLUSR_RX_PMD_RTCSX1_TYPE rxpmd_test_control; /* OFFSET: 0x0 */
    SGMIIPLUSR_RX_PMD_RTSSX1_TYPE rxpmd_test_status; /* OFFSET: 0x2 */
    SGMIIPLUSR_RX_PMD_RC0SX1_TYPE rxpmd_control0; /* OFFSET: 0x4 */
    SGMIIPLUSR_RX_PMD_RC1SX1_TYPE rxpmd_control1; /* OFFSET: 0x6 */
    SGMIIPLUSR_RX_PMD_RC2SX1_TYPE rxpmd_control2; /* OFFSET: 0x8 */
    SGMIIPLUSR_RX_PMD_RSC0SX1_TYPE rxpmd_sigdet_ctrl0; /* OFFSET: 0xa */
    SGMIIPLUSR_RX_PMD_RSC1SX1_TYPE rxpmd_sigdet_ctrl1; /* OFFSET: 0xc */
    SGMIIPLUSR_RX_PMD_RSSSX1_TYPE rxpmd_sigdet_status; /* OFFSET: 0xe */
    SGMIIPLUSR_RX_PMD_RC3SX1_TYPE rxpmd_control3; /* OFFSET: 0x10 */
    SGMIIPLUSR_RX_PMD_RESERVED_TYPE rsvd0[12]; /* OFFSET: 0x12 */
    SGMIIPLUSR_RX_PMD_BLOCKADDRESS_SGMIIPLUSR_X1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_RX_PMD_RDBType;


#define RX_PMD_TEST_BASE                (0x4AE50C40UL)



#define SGMIIPLUSR_RX_PMD_MAX_HW_ID     (1UL)

#endif /* SGMIIPLUSR_RX_PMD_RDB_H */
