/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_rx_afe_pmd_rdb.h
    @brief RDB File for SGMIIPLUSR_RX_AFE_PMD

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_RX_AFE_PMD_RDB_H
#define SGMIIPLUSR_RX_AFE_PMD_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t SGMIIPLUSR_RX_AFE_PMD_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_SLICER_PD_MASK (0x8000U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_SLICER_PD_SHIFT (15U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_RX_PON_MASK (0xf00U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_RX_PON_SHIFT (8U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_FILTER_BAND_MASK (0xc0U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_FILTER_BAND_SHIFT (6U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_PD_LMTNG_MASK (0x4U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_PD_LMTNG_SHIFT (2U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_PD_EQZ_MASK (0x2U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_PD_EQZ_SHIFT (1U)




typedef uint16_t SGMIIPLUSR_RX_AFE_PMD_C1SX1_TYPE;
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_DEMUX_EYEM_PD_MASK (0x8000U)
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_DEMUX_EYEM_PD_SHIFT (15U)
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_DEMUX_PD_MASK (0x4000U)
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_DEMUX_PD_SHIFT (14U)
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_DEMUX_PEAK_PD_MASK (0x2000U)
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_DEMUX_PEAK_PD_SHIFT (13U)
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_DEMUX_ZERO_PD_MASK (0x1000U)
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_DEMUX_ZERO_PD_SHIFT (12U)
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_DIV_4_DEMUX_ENABLE_MASK (0x800U)
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_DIV_4_DEMUX_ENABLE_SHIFT (11U)
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_EYEM_PD_MASK (0x1U)
#define SGMIIPLUSR_RX_AFE_PMD_C1SX1_EYEM_PD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_AFE_PMD_C2SX1_TYPE;
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_INPUTERM_LOWZVDD_EN_MASK (0x40U)
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_INPUTERM_LOWZVDD_EN_SHIFT (6U)
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_INPUTERM_LOWZGND_EN_MASK (0x20U)
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_INPUTERM_LOWZGND_EN_SHIFT (5U)
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_INPUTERM_CMULT_EN_MASK (0x10U)
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_INPUTERM_CMULT_EN_SHIFT (4U)
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_INPUTERM_CM_EN_MASK (0x8U)
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_INPUTERM_CM_EN_SHIFT (3U)
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_DIV10_PD_MASK (0x4U)
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_DIV10_PD_SHIFT (2U)
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_DIV4_PD_MASK (0x2U)
#define SGMIIPLUSR_RX_AFE_PMD_C2SX1_DIV4_PD_SHIFT (1U)




typedef uint16_t SGMIIPLUSR_RX_AFE_PMD_CTRL3_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_RX_AFE_PMD_CTRL3_SGMIIPLUSR_X1_PD_BIAS_MASK (0x200U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL3_SGMIIPLUSR_X1_PD_BIAS_SHIFT (9U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL3_SGMIIPLUSR_X1_DUTY_CYCLE_MASK (0x1c0U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL3_SGMIIPLUSR_X1_DUTY_CYCLE_SHIFT (6U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL3_SGMIIPLUSR_X1_DCC_EN_MASK (0x20U)
#define SGMIIPLUSR_RX_AFE_PMD_CTRL3_SGMIIPLUSR_X1_DCC_EN_SHIFT (5U)




typedef uint16_t SGMIIPLUSR_RX_AFE_PMD_C4SX1_TYPE;
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_EN_TESTMUX_MASK (0x8000U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_EN_TESTMUX_SHIFT (15U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_SIGDET_MODESELECT_MASK (0x4000U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_SIGDET_MODESELECT_SHIFT (14U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_SIGDET_PD_MASK (0x2000U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_SIGDET_PD_SHIFT (13U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_SIGDET_BYPASS_MASK (0x1000U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_SIGDET_BYPASS_SHIFT (12U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_BIAS_SIGDET_CTRL_MASK (0xe00U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_BIAS_SIGDET_CTRL_SHIFT (9U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_BIAS_EYEM_CTRL_MASK (0x1c0U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_BIAS_EYEM_CTRL_SHIFT (6U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_BIAS_LA_DAC_CTRL_MASK (0x38U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_BIAS_LA_DAC_CTRL_SHIFT (3U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_BIAS_LA_CTRL_MASK (0x7U)
#define SGMIIPLUSR_RX_AFE_PMD_C4SX1_BIAS_LA_CTRL_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_AFE_PMD_C5SX1_TYPE;
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_SIGDET_USB_EN_MASK (0x8000U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_SIGDET_USB_EN_SHIFT (15U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_PI_EYEM_ENABLE_MASK (0x4000U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_PI_EYEM_ENABLE_SHIFT (14U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_PI_MAIN_ENABLE_MASK (0x2000U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_PI_MAIN_ENABLE_SHIFT (13U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_EYEMONITOR_REF_ZERO_MASK (0x1000U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_EYEMONITOR_REF_ZERO_SHIFT (12U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_EYEMONITORREF_PD_MASK (0x800U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_EYEMONITORREF_PD_SHIFT (11U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_EYEM_REFADJUST_MASK (0x7c0U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_EYEM_REFADJUST_SHIFT (6U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_SEL_CLK_MASK (0x30U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_SEL_CLK_SHIFT (4U)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_SIGDET_THRESHOLD_MASK (0xfU)
#define SGMIIPLUSR_RX_AFE_PMD_C5SX1_SIGDET_THRESHOLD_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_RX_AFE_PMD_C6SX1_TYPE;
#define SGMIIPLUSR_RX_AFE_PMD_C6SX1_EYE_MONITOR_PI_BW_SEL_MASK (0x40U)
#define SGMIIPLUSR_RX_AFE_PMD_C6SX1_EYE_MONITOR_PI_BW_SEL_SHIFT (6U)
#define SGMIIPLUSR_RX_AFE_PMD_C6SX1_EYE_MONITOR_PI_PWD_LVL2PI_MASK (0x20U)
#define SGMIIPLUSR_RX_AFE_PMD_C6SX1_EYE_MONITOR_PI_PWD_LVL2PI_SHIFT (5U)
#define SGMIIPLUSR_RX_AFE_PMD_C6SX1_PI_LOWVDD_ENB_MASK (0x8U)
#define SGMIIPLUSR_RX_AFE_PMD_C6SX1_PI_LOWVDD_ENB_SHIFT (3U)
#define SGMIIPLUSR_RX_AFE_PMD_C6SX1_MAIN_PI_BW_SEL_MASK (0x4U)
#define SGMIIPLUSR_RX_AFE_PMD_C6SX1_MAIN_PI_BW_SEL_SHIFT (2U)
#define SGMIIPLUSR_RX_AFE_PMD_C6SX1_MAIN_PI_PWD_LVL2PI_MASK (0x2U)
#define SGMIIPLUSR_RX_AFE_PMD_C6SX1_MAIN_PI_PWD_LVL2PI_SHIFT (1U)




typedef uint16_t SGMIIPLUSR_RX_AFE_PMD_BSX1_TYPE;
#define SGMIIPLUSR_RX_AFE_PMD_BSX1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_RX_AFE_PMD_BSX1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_RX_AFE_PMD_RDBType {
    SGMIIPLUSR_RX_AFE_PMD_RESERVED_TYPE rsvd0[4]; /* OFFSET: 0x0 */
    SGMIIPLUSR_RX_AFE_PMD_CTRL0_SGMIIPLUSR_X1_TYPE ctrl0; /* OFFSET: 0x4 */
    SGMIIPLUSR_RX_AFE_PMD_C1SX1_TYPE ctrl1; /* OFFSET: 0x6 */
    SGMIIPLUSR_RX_AFE_PMD_RESERVED_TYPE rsvd1[2]; /* OFFSET: 0x8 */
    SGMIIPLUSR_RX_AFE_PMD_C2SX1_TYPE ctrl2; /* OFFSET: 0xa */
    SGMIIPLUSR_RX_AFE_PMD_CTRL3_SGMIIPLUSR_X1_TYPE ctrl3; /* OFFSET: 0xc */
    SGMIIPLUSR_RX_AFE_PMD_C4SX1_TYPE ctrl4; /* OFFSET: 0xe */
    SGMIIPLUSR_RX_AFE_PMD_RESERVED_TYPE rsvd2[8]; /* OFFSET: 0x10 */
    SGMIIPLUSR_RX_AFE_PMD_C5SX1_TYPE ctrl5; /* OFFSET: 0x18 */
    SGMIIPLUSR_RX_AFE_PMD_C6SX1_TYPE ctrl6; /* OFFSET: 0x1a */
    SGMIIPLUSR_RX_AFE_PMD_RESERVED_TYPE rsvd3[2]; /* OFFSET: 0x1c */
    SGMIIPLUSR_RX_AFE_PMD_BSX1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_RX_AFE_PMD_RDBType;


#define RX_AFE_BASE                     (0x4AE50160UL)



#define SGMIIPLUSR_RX_AFE_PMD_MAX_HW_ID  (1UL)

#endif /* SGMIIPLUSR_RX_AFE_PMD_RDB_H */
