/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiipcie_usercl22_rdb.h
    @brief RDB File for SGMIIPCIE_USERCL22

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPCIE_USERCL22_RDB_H
#define SGMIIPCIE_USERCL22_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_RST_HW_MASK (0x8000U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_RST_HW_SHIFT (15U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_GLOOPBACK_MASK (0x4000U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_GLOOPBACK_SHIFT (14U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_MANUAL_SPEED0_MASK (0x2000U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_MANUAL_SPEED0_SHIFT (13U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_AUTONEG_ENABLE_MASK (0x1000U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_AUTONEG_ENABLE_SHIFT (12U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_PWRDWN_SW_MASK (0x800U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_PWRDWN_SW_SHIFT (11U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_RESTART_AUTONEG_MASK (0x200U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_RESTART_AUTONEG_SHIFT (9U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_DUPLEX_MASK (0x100U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_DUPLEX_SHIFT (8U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_COLLISION_TEST_EN_MASK (0x80U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_COLLISION_TEST_EN_SHIFT (7U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_MANUAL_SPEED1_MASK (0x40U)
#define SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_MANUAL_SPEED1_SHIFT (6U)




typedef uint16_t SGMIIPCIE_USERCL22_MSX1_TYPE;
#define SGMIIPCIE_USERCL22_MSX1_S100BASE_T4_CAPABLE_MASK (0x8000U)
#define SGMIIPCIE_USERCL22_MSX1_S100BASE_T4_CAPABLE_SHIFT (15U)
#define SGMIIPCIE_USERCL22_MSX1_S100BASE_X_FULL_DUPLEX_CAPABLE_MASK (0x4000U)
#define SGMIIPCIE_USERCL22_MSX1_S100BASE_X_FULL_DUPLEX_CAPABLE_SHIFT (14U)
#define SGMIIPCIE_USERCL22_MSX1_S100BASE_X_HALF_DUPLEX_CAPABLE_MASK (0x2000U)
#define SGMIIPCIE_USERCL22_MSX1_S100BASE_X_HALF_DUPLEX_CAPABLE_SHIFT (13U)
#define SGMIIPCIE_USERCL22_MSX1_S10BASE_T_FULL_DUPLEX_CAPABLE_MASK (0x1000U)
#define SGMIIPCIE_USERCL22_MSX1_S10BASE_T_FULL_DUPLEX_CAPABLE_SHIFT (12U)
#define SGMIIPCIE_USERCL22_MSX1_S10BASE_T_HALF_DUPLEX_CAPABLE_MASK (0x800U)
#define SGMIIPCIE_USERCL22_MSX1_S10BASE_T_HALF_DUPLEX_CAPABLE_SHIFT (11U)
#define SGMIIPCIE_USERCL22_MSX1_S100BASE_T2_FULL_DUPLEX_CAPABLE_MASK (0x400U)
#define SGMIIPCIE_USERCL22_MSX1_S100BASE_T2_FULL_DUPLEX_CAPABLE_SHIFT (10U)
#define SGMIIPCIE_USERCL22_MSX1_S100BASE_T2_HALF_DUPLEX_CAPABLE_MASK (0x200U)
#define SGMIIPCIE_USERCL22_MSX1_S100BASE_T2_HALF_DUPLEX_CAPABLE_SHIFT (9U)
#define SGMIIPCIE_USERCL22_MSX1_EXTENDED_STATUS_MASK (0x100U)
#define SGMIIPCIE_USERCL22_MSX1_EXTENDED_STATUS_SHIFT (8U)
#define SGMIIPCIE_USERCL22_MSX1_MF_PREAMBLE_SUPRESSION_MASK (0x40U)
#define SGMIIPCIE_USERCL22_MSX1_MF_PREAMBLE_SUPRESSION_SHIFT (6U)
#define SGMIIPCIE_USERCL22_MSX1_AUTONEG_COMPLETE_MASK (0x20U)
#define SGMIIPCIE_USERCL22_MSX1_AUTONEG_COMPLETE_SHIFT (5U)
#define SGMIIPCIE_USERCL22_MSX1_REMOTE_FAULT_STAT_MASK (0x10U)
#define SGMIIPCIE_USERCL22_MSX1_REMOTE_FAULT_STAT_SHIFT (4U)
#define SGMIIPCIE_USERCL22_MSX1_AUTONEG_ABILITY_MASK (0x8U)
#define SGMIIPCIE_USERCL22_MSX1_AUTONEG_ABILITY_SHIFT (3U)
#define SGMIIPCIE_USERCL22_MSX1_LINK_STATUS_MASK (0x4U)
#define SGMIIPCIE_USERCL22_MSX1_LINK_STATUS_SHIFT (2U)
#define SGMIIPCIE_USERCL22_MSX1_JABBER_DETECT_MASK (0x2U)
#define SGMIIPCIE_USERCL22_MSX1_JABBER_DETECT_SHIFT (1U)
#define SGMIIPCIE_USERCL22_MSX1_EXTENDED_CAPABILITY_MASK (0x1U)
#define SGMIIPCIE_USERCL22_MSX1_EXTENDED_CAPABILITY_SHIFT (0U)




typedef uint16_t SGMIIPCIE_USERCL22_ID1_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_USERCL22_ID1_SGMIIPCIE_X1_REGID_MASK (0xffffU)
#define SGMIIPCIE_USERCL22_ID1_SGMIIPCIE_X1_REGID_SHIFT (0U)




typedef uint16_t SGMIIPCIE_USERCL22_ID2_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_USERCL22_ID2_SGMIIPCIE_X1_REGID_MASK (0xffffU)
#define SGMIIPCIE_USERCL22_ID2_SGMIIPCIE_X1_REGID_SHIFT (0U)




typedef uint16_t SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_NEXT_PAGE_MASK (0x8000U)
#define SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_NEXT_PAGE_SHIFT (15U)
#define SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_REMOTE_FAULT_MASK (0x3000U)
#define SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_REMOTE_FAULT_SHIFT (12U)
#define SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_PAUSE_MASK (0x180U)
#define SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_PAUSE_SHIFT (7U)
#define SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_HALF_DUPLEX_MASK (0x40U)
#define SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_HALF_DUPLEX_SHIFT (6U)
#define SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_FULL_DUPLEX_MASK (0x20U)
#define SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_FULL_DUPLEX_SHIFT (5U)




typedef uint16_t SGMIIPCIE_USERCL22_ASX1_TYPE;
#define SGMIIPCIE_USERCL22_ASX1_MR_LP_ADV_ABILITY_MASK (0xffffU)
#define SGMIIPCIE_USERCL22_ASX1_MR_LP_ADV_ABILITY_SHIFT (0U)




typedef uint16_t SGMIIPCIE_USERCL22_ASX11_TYPE;
#define SGMIIPCIE_USERCL22_ASX11_NEXT_PAGE_ABILITY_MASK (0x4U)
#define SGMIIPCIE_USERCL22_ASX11_NEXT_PAGE_ABILITY_SHIFT (2U)
#define SGMIIPCIE_USERCL22_ASX11_LATCH_PAGE_RX_MASK (0x2U)
#define SGMIIPCIE_USERCL22_ASX11_LATCH_PAGE_RX_SHIFT (1U)




typedef uint16_t SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_NEXT_PAGE_MASK (0x8000U)
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_NEXT_PAGE_SHIFT (15U)
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_ACK_MASK (0x4000U)
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_ACK_SHIFT (14U)
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_MESSAGE_PAGE_MASK (0x2000U)
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_MESSAGE_PAGE_SHIFT (13U)
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_ACK2_MASK (0x1000U)
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_ACK2_SHIFT (12U)
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_TOGGLE_MASK (0x800U)
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_TOGGLE_SHIFT (11U)
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_MESSAGE_MASK (0x7ffU)
#define SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_MESSAGE_SHIFT (0U)




typedef uint16_t SGMIIPCIE_USERCL22_AUTONEGLPNP_SGMIIPCIE_X1_TYPE;
#define SGMIIPCIE_USERCL22_AUTONEGLPNP_SGMIIPCIE_X1_MR_LP_NP_RX_O_MASK (0xffffU)
#define SGMIIPCIE_USERCL22_AUTONEGLPNP_SGMIIPCIE_X1_MR_LP_NP_RX_O_SHIFT (0U)




typedef volatile struct COMP_PACKED sSGMIIPCIE_USERCL22_RDBType {
    SGMIIPCIE_USERCL22_MIICNTL_SGMIIPCIE_X1_TYPE miicntl; /* OFFSET: 0x0 */
    SGMIIPCIE_USERCL22_MSX1_TYPE miistat; /* OFFSET: 0x2 */
    SGMIIPCIE_USERCL22_ID1_SGMIIPCIE_X1_TYPE id1; /* OFFSET: 0x4 */
    SGMIIPCIE_USERCL22_ID2_SGMIIPCIE_X1_TYPE id2; /* OFFSET: 0x6 */
    SGMIIPCIE_USERCL22_AUTONEGADV_SGMIIPCIE_X1_TYPE autonegadv; /* OFFSET: 0x8 */
    SGMIIPCIE_USERCL22_ASX1_TYPE autoneglpabil; /* OFFSET: 0xa */
    SGMIIPCIE_USERCL22_ASX11_TYPE autonegexp; /* OFFSET: 0xc */
    SGMIIPCIE_USERCL22_AUTONEGNP_SGMIIPCIE_X1_TYPE autonegnp; /* OFFSET: 0xe */
    SGMIIPCIE_USERCL22_AUTONEGLPNP_SGMIIPCIE_X1_TYPE autoneglpabil2; /* OFFSET: 0x10 */
} SGMIIPCIE_USERCL22_RDBType;


#define COMBO_IEEE0_SGMIIPCIE_X1_BASE   (0x4ADDFFC0UL)



#define SGMIIPCIE_USERCL22_MAX_HW_ID    (1UL)

#endif /* SGMIIPCIE_USERCL22_RDB_H */
