/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmii_usercl22_rdb.h
    @brief RDB File for SGMII_USERCL22

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMII_USERCL22_RDB_H
#define SGMII_USERCL22_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_TYPE;
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_RST_HW_MASK (0x8000U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_RST_HW_SHIFT (15U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_GLOOPBACK_MASK (0x4000U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_GLOOPBACK_SHIFT (14U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_MANUAL_SPEED0_MASK (0x2000U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_MANUAL_SPEED0_SHIFT (13U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_AUTONEG_ENABLE_MASK (0x1000U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_AUTONEG_ENABLE_SHIFT (12U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_PWRDWN_SW_MASK (0x800U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_PWRDWN_SW_SHIFT (11U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_RESTART_AUTONEG_MASK (0x200U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_RESTART_AUTONEG_SHIFT (9U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_DUPLEX_MASK (0x100U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_DUPLEX_SHIFT (8U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_COLLISION_TEST_EN_MASK (0x80U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_COLLISION_TEST_EN_SHIFT (7U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_MANUAL_SPEED1_MASK (0x40U)
#define SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_MANUAL_SPEED1_SHIFT (6U)




typedef uint16_t SGMII_USERCL22_MS2X2_TYPE;
#define SGMII_USERCL22_MS2X2_S100BASE_T4_CAPABLE_MASK (0x8000U)
#define SGMII_USERCL22_MS2X2_S100BASE_T4_CAPABLE_SHIFT (15U)
#define SGMII_USERCL22_MS2X2_S100BASE_X_FULL_DUPLEX_CAPABLE_MASK (0x4000U)
#define SGMII_USERCL22_MS2X2_S100BASE_X_FULL_DUPLEX_CAPABLE_SHIFT (14U)
#define SGMII_USERCL22_MS2X2_S100BASE_X_HALF_DUPLEX_CAPABLE_MASK (0x2000U)
#define SGMII_USERCL22_MS2X2_S100BASE_X_HALF_DUPLEX_CAPABLE_SHIFT (13U)
#define SGMII_USERCL22_MS2X2_S10BASE_T_FULL_DUPLEX_CAPABLE_MASK (0x1000U)
#define SGMII_USERCL22_MS2X2_S10BASE_T_FULL_DUPLEX_CAPABLE_SHIFT (12U)
#define SGMII_USERCL22_MS2X2_S10BASE_T_HALF_DUPLEX_CAPABLE_MASK (0x800U)
#define SGMII_USERCL22_MS2X2_S10BASE_T_HALF_DUPLEX_CAPABLE_SHIFT (11U)
#define SGMII_USERCL22_MS2X2_S100BASE_T2_FULL_DUPLEX_CAPABLE_MASK (0x400U)
#define SGMII_USERCL22_MS2X2_S100BASE_T2_FULL_DUPLEX_CAPABLE_SHIFT (10U)
#define SGMII_USERCL22_MS2X2_S100BASE_T2_HALF_DUPLEX_CAPABLE_MASK (0x200U)
#define SGMII_USERCL22_MS2X2_S100BASE_T2_HALF_DUPLEX_CAPABLE_SHIFT (9U)
#define SGMII_USERCL22_MS2X2_EXTENDED_STATUS_MASK (0x100U)
#define SGMII_USERCL22_MS2X2_EXTENDED_STATUS_SHIFT (8U)
#define SGMII_USERCL22_MS2X2_MF_PREAMBLE_SUPRESSION_MASK (0x40U)
#define SGMII_USERCL22_MS2X2_MF_PREAMBLE_SUPRESSION_SHIFT (6U)
#define SGMII_USERCL22_MS2X2_AUTONEG_COMPLETE_MASK (0x20U)
#define SGMII_USERCL22_MS2X2_AUTONEG_COMPLETE_SHIFT (5U)
#define SGMII_USERCL22_MS2X2_REMOTE_FAULT_STAT_MASK (0x10U)
#define SGMII_USERCL22_MS2X2_REMOTE_FAULT_STAT_SHIFT (4U)
#define SGMII_USERCL22_MS2X2_AUTONEG_ABILITY_MASK (0x8U)
#define SGMII_USERCL22_MS2X2_AUTONEG_ABILITY_SHIFT (3U)
#define SGMII_USERCL22_MS2X2_LINK_STATUS_MASK (0x4U)
#define SGMII_USERCL22_MS2X2_LINK_STATUS_SHIFT (2U)
#define SGMII_USERCL22_MS2X2_JABBER_DETECT_MASK (0x2U)
#define SGMII_USERCL22_MS2X2_JABBER_DETECT_SHIFT (1U)
#define SGMII_USERCL22_MS2X2_EXTENDED_CAPABILITY_MASK (0x1U)
#define SGMII_USERCL22_MS2X2_EXTENDED_CAPABILITY_SHIFT (0U)




typedef uint16_t SGMII_USERCL22_ID1_SGMIIPLUS2_X2_TYPE;
#define SGMII_USERCL22_ID1_SGMIIPLUS2_X2_REGID_MASK (0xffffU)
#define SGMII_USERCL22_ID1_SGMIIPLUS2_X2_REGID_SHIFT (0U)




typedef uint16_t SGMII_USERCL22_ID2_SGMIIPLUS2_X2_TYPE;
#define SGMII_USERCL22_ID2_SGMIIPLUS2_X2_REGID_MASK (0xffffU)
#define SGMII_USERCL22_ID2_SGMIIPLUS2_X2_REGID_SHIFT (0U)




typedef uint16_t SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_TYPE;
#define SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_NEXT_PAGE_MASK (0x8000U)
#define SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_NEXT_PAGE_SHIFT (15U)
#define SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_REMOTE_FAULT_MASK (0x3000U)
#define SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_REMOTE_FAULT_SHIFT (12U)
#define SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_PAUSE_MASK (0x180U)
#define SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_PAUSE_SHIFT (7U)
#define SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_HALF_DUPLEX_MASK (0x40U)
#define SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_HALF_DUPLEX_SHIFT (6U)
#define SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_FULL_DUPLEX_MASK (0x20U)
#define SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_FULL_DUPLEX_SHIFT (5U)




typedef uint16_t SGMII_USERCL22_AS2X2_TYPE;
#define SGMII_USERCL22_AS2X2_MR_LP_ADV_ABILITY_MASK (0xffffU)
#define SGMII_USERCL22_AS2X2_MR_LP_ADV_ABILITY_SHIFT (0U)




typedef uint16_t SGMII_USERCL22_AUTONEGEXP_SGMIIPLUS2_X2_TYPE;
#define SGMII_USERCL22_AUTONEGEXP_SGMIIPLUS2_X2_NEXT_PAGE_ABILITY_MASK (0x4U)
#define SGMII_USERCL22_AUTONEGEXP_SGMIIPLUS2_X2_NEXT_PAGE_ABILITY_SHIFT (2U)
#define SGMII_USERCL22_AUTONEGEXP_SGMIIPLUS2_X2_LATCH_PAGE_RX_MASK (0x2U)
#define SGMII_USERCL22_AUTONEGEXP_SGMIIPLUS2_X2_LATCH_PAGE_RX_SHIFT (1U)




typedef uint16_t SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_TYPE;
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_NEXT_PAGE_MASK (0x8000U)
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_NEXT_PAGE_SHIFT (15U)
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_ACK_MASK (0x4000U)
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_ACK_SHIFT (14U)
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_MESSAGE_PAGE_MASK (0x2000U)
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_MESSAGE_PAGE_SHIFT (13U)
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_ACK2_MASK (0x1000U)
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_ACK2_SHIFT (12U)
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_TOGGLE_MASK (0x800U)
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_TOGGLE_SHIFT (11U)
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_MESSAGE_MASK (0x7ffU)
#define SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_MESSAGE_SHIFT (0U)




typedef uint16_t SGMII_USERCL22_AUTONEGLPNP_SGMIIPLUS2_X2_TYPE;
#define SGMII_USERCL22_AUTONEGLPNP_SGMIIPLUS2_X2_MR_LP_NP_RX_O_MASK (0xffffU)
#define SGMII_USERCL22_AUTONEGLPNP_SGMIIPLUS2_X2_MR_LP_NP_RX_O_SHIFT (0U)




typedef uint8_t SGMII_USERCL22_RESERVED_TYPE;




typedef uint16_t SGMII_USERCL22_MAS2X2_TYPE;
#define SGMII_USERCL22_MAS2X2_INCREMENT_CTRL_MASK (0xc000U)
#define SGMII_USERCL22_MAS2X2_INCREMENT_CTRL_SHIFT (14U)
#define SGMII_USERCL22_MAS2X2_DEVAD_MASK (0x1fU)
#define SGMII_USERCL22_MAS2X2_DEVAD_SHIFT (0U)




typedef uint16_t SGMII_USERCL22_MMD_ACCESSADDRDATA_SGMIIPLUS2_X2_TYPE;
#define SGMII_USERCL22_MMD_ACCESSADDRDATA_SGMIIPLUS2_X2_ADDRDATA_MASK (0xffffU)
#define SGMII_USERCL22_MMD_ACCESSADDRDATA_SGMIIPLUS2_X2_ADDRDATA_SHIFT (0U)




typedef uint16_t SGMII_USERCL22_MS2X21_TYPE;
#define SGMII_USERCL22_MS2X21_S1000BASE_X_FULL_DUPLEX_CAPABLE_MASK (0x8000U)
#define SGMII_USERCL22_MS2X21_S1000BASE_X_FULL_DUPLEX_CAPABLE_SHIFT (15U)
#define SGMII_USERCL22_MS2X21_S1000BASE_X_HALF_DUPLEX_CAPABLE_MASK (0x4000U)
#define SGMII_USERCL22_MS2X21_S1000BASE_X_HALF_DUPLEX_CAPABLE_SHIFT (14U)
#define SGMII_USERCL22_MS2X21_S1000BASE_T_FULL_DUPLEX_CAPABLE_MASK (0x2000U)
#define SGMII_USERCL22_MS2X21_S1000BASE_T_FULL_DUPLEX_CAPABLE_SHIFT (13U)
#define SGMII_USERCL22_MS2X21_S1000BASE_T_HALF_DUPLEX_CAPABLE_MASK (0x1000U)
#define SGMII_USERCL22_MS2X21_S1000BASE_T_HALF_DUPLEX_CAPABLE_SHIFT (12U)




typedef volatile struct COMP_PACKED sSGMII_USERCL22_RDBType {
    SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_TYPE miicntl; /* OFFSET: 0x0 */
    SGMII_USERCL22_MS2X2_TYPE miistat; /* OFFSET: 0x2 */
    SGMII_USERCL22_ID1_SGMIIPLUS2_X2_TYPE id1; /* OFFSET: 0x4 */
    SGMII_USERCL22_ID2_SGMIIPLUS2_X2_TYPE id2; /* OFFSET: 0x6 */
    SGMII_USERCL22_AUTONEGADV_SGMIIPLUS2_X2_TYPE autonegadv; /* OFFSET: 0x8 */
    SGMII_USERCL22_AS2X2_TYPE autoneglpabil; /* OFFSET: 0xa */
    SGMII_USERCL22_AUTONEGEXP_SGMIIPLUS2_X2_TYPE autonegexp; /* OFFSET: 0xc */
    SGMII_USERCL22_AUTONEGNP_SGMIIPLUS2_X2_TYPE autonegnp; /* OFFSET: 0xe */
    SGMII_USERCL22_AUTONEGLPNP_SGMIIPLUS2_X2_TYPE autoneglpabil2; /* OFFSET: 0x10 */
    SGMII_USERCL22_RESERVED_TYPE rsvd0[8]; /* OFFSET: 0x12 */
    SGMII_USERCL22_MAS2X2_TYPE mmd_accesscontrol; /* OFFSET: 0x1a */
    SGMII_USERCL22_MMD_ACCESSADDRDATA_SGMIIPLUS2_X2_TYPE mmd_accessad; /* OFFSET: 0x1c */
    SGMII_USERCL22_MS2X21_TYPE miiextstat; /* OFFSET: 0x1e */
} SGMII_USERCL22_RDBType;


#define CL22_B0_LANE0_BASE              (0x4AC00000UL)

#define CL22_B0_LANE1_BASE              (0x4AC20000UL)



#define SGMII_USERCL22_MAX_HW_ID        (2UL)


#define ENABLE_HWSCORPIO569_WORKAROUND  (0x0U)


#define SGMII0_USERCL22_BASE            (CL22_B0_LANE0_BASE)


#define SGMII1_USERCL22_BASE            (CL22_B0_LANE1_BASE)


#define SGMII2_USERCL22_BASE            (COMBO_IEEE0_SGMIIPCIE_X1_BASE)


#define SGMII3_USERCL22_BASE            (UNDEFINED)


#define SGMII4_USERCL22_BASE            (UNDEFINED)


#define SGMII_USERCL22_MIICNTL_DUPLEX_MASK  (SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_DUPLEX_MASK)


#define SGMII_USERCL22_MIICNTL_MANUAL_SPEED0_MASK  (SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_MANUAL_SPEED0_MASK)


#define SGMII_USERCL22_MIICNTL_MANUAL_SPEED1_MASK  (SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_MANUAL_SPEED1_MASK)


#define SGMII_USERCL22_MIICNTL_AUTONEG_ENABLE_MASK  (SGMII_USERCL22_MIICNTL_SGMIIPLUS2_X2_AUTONEG_ENABLE_MASK)

#endif /* SGMII_USERCL22_RDB_H */
