/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file sgmiiplusr_digital_rdb.h
    @brief RDB File for SGMIIPLUSR_DIGITAL

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SGMIIPLUSR_DIGITAL_RDB_H
#define SGMIIPLUSR_DIGITAL_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t SGMIIPLUSR_DIGITAL_RESERVED_TYPE;




typedef uint16_t SGMIIPLUSR_DIGITAL_C10002SX1_TYPE;
#define SGMIIPLUSR_DIGITAL_C10002SX1_DISABLE_EXTEND_FDX_ONLY_MASK (0x8000U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_DISABLE_EXTEND_FDX_ONLY_SHIFT (15U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_CLEAR_BER_COUNTER_MASK (0x4000U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_CLEAR_BER_COUNTER_SHIFT (14U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_DISABLE_TRRR_GENERATION_MASK (0x100U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_DISABLE_TRRR_GENERATION_SHIFT (8U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_DISABLE_CARRIER_EXTEND_MASK (0x80U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_DISABLE_CARRIER_EXTEND_SHIFT (7U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_DRFR_MASK (0x10U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_DRFR_SHIFT (4U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_ENABLE_AUTONEG_ERR_TIMER_MASK (0x8U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_ENABLE_AUTONEG_ERR_TIMER_SHIFT (3U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_FILTER_FORCE_LINK_MASK (0x4U)
#define SGMIIPLUSR_DIGITAL_C10002SX1_FILTER_FORCE_LINK_SHIFT (2U)




typedef uint16_t SGMIIPLUSR_DIGITAL_S10001SX1_TYPE;
#define SGMIIPLUSR_DIGITAL_S10001SX1_TX_ERR_DETECTED_MASK (0x800U)
#define SGMIIPLUSR_DIGITAL_S10001SX1_TX_ERR_DETECTED_SHIFT (11U)
#define SGMIIPLUSR_DIGITAL_S10001SX1_RX_ERR_DETECTED_MASK (0x400U)
#define SGMIIPLUSR_DIGITAL_S10001SX1_RX_ERR_DETECTED_SHIFT (10U)
#define SGMIIPLUSR_DIGITAL_S10001SX1_LINK_STATUS_CHANGE_MASK (0x80U)
#define SGMIIPLUSR_DIGITAL_S10001SX1_LINK_STATUS_CHANGE_SHIFT (7U)




typedef uint16_t SGMIIPLUSR_DIGITAL_SPARE_SGMIIPLUSR_X1_TYPE;
#define SGMIIPLUSR_DIGITAL_SPARE_SGMIIPLUSR_X1_SPARE_MASK (0xffU)
#define SGMIIPLUSR_DIGITAL_SPARE_SGMIIPLUSR_X1_SPARE_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_DIGITAL_MSX1_TYPE;
#define SGMIIPLUSR_DIGITAL_MSX1_FORCE_IEEE_SPEEDSEL_EN_MASK (0x8000U)
#define SGMIIPLUSR_DIGITAL_MSX1_FORCE_IEEE_SPEEDSEL_EN_SHIFT (15U)
#define SGMIIPLUSR_DIGITAL_MSX1_FORCE_IEEE_CL22_SPEEDSEL_EN_MASK (0x4000U)
#define SGMIIPLUSR_DIGITAL_MSX1_FORCE_IEEE_CL22_SPEEDSEL_EN_SHIFT (14U)
#define SGMIIPLUSR_DIGITAL_MSX1_USE_IEEE_REG_CTRL_SEL_MASK (0x3000U)
#define SGMIIPLUSR_DIGITAL_MSX1_USE_IEEE_REG_CTRL_SEL_SHIFT (12U)
#define SGMIIPLUSR_DIGITAL_MSX1_CREDIT_SW_EN_MASK (0x800U)
#define SGMIIPLUSR_DIGITAL_MSX1_CREDIT_SW_EN_SHIFT (11U)
#define SGMIIPLUSR_DIGITAL_MSX1_REPLICATION_CNT_MASK (0x400U)
#define SGMIIPLUSR_DIGITAL_MSX1_REPLICATION_CNT_SHIFT (10U)
#define SGMIIPLUSR_DIGITAL_MSX1_SGMII_SPD_SWITCH_MASK (0x200U)
#define SGMIIPLUSR_DIGITAL_MSX1_SGMII_SPD_SWITCH_SHIFT (9U)
#define SGMIIPLUSR_DIGITAL_MSX1_PCS_CREDITENABLE_MASK (0x100U)
#define SGMIIPLUSR_DIGITAL_MSX1_PCS_CREDITENABLE_SHIFT (8U)
#define SGMIIPLUSR_DIGITAL_MSX1_MAC_CREDITENABLE_MASK (0x80U)
#define SGMIIPLUSR_DIGITAL_MSX1_MAC_CREDITENABLE_SHIFT (7U)
#define SGMIIPLUSR_DIGITAL_MSX1_SW_ACTUAL_SPEED_FORCE_EN_MASK (0x40U)
#define SGMIIPLUSR_DIGITAL_MSX1_SW_ACTUAL_SPEED_FORCE_EN_SHIFT (6U)
#define SGMIIPLUSR_DIGITAL_MSX1_SW_ACTUAL_SPEED_MASK (0x3fU)
#define SGMIIPLUSR_DIGITAL_MSX1_SW_ACTUAL_SPEED_SHIFT (0U)




typedef uint16_t SGMIIPLUSR_DIGITAL_C49BSX1_TYPE;
#define SGMIIPLUSR_DIGITAL_C49BSX1_IDLEERRORCOUNT_EN_MASK (0x400U)
#define SGMIIPLUSR_DIGITAL_C49BSX1_IDLEERRORCOUNT_EN_SHIFT (10U)




typedef uint16_t SGMIIPLUSR_DIGITAL_BSX1_TYPE;
#define SGMIIPLUSR_DIGITAL_BSX1_BLOCKADDRESS_MASK (0x7ff0U)
#define SGMIIPLUSR_DIGITAL_BSX1_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sSGMIIPLUSR_DIGITAL_RDBType {
    SGMIIPLUSR_DIGITAL_RESERVED_TYPE rsvd0[2]; /* OFFSET: 0x0 */
    SGMIIPLUSR_DIGITAL_C10002SX1_TYPE control1000x2; /* OFFSET: 0x2 */
    SGMIIPLUSR_DIGITAL_RESERVED_TYPE rsvd1[4]; /* OFFSET: 0x4 */
    SGMIIPLUSR_DIGITAL_S10001SX1_TYPE status1000x1; /* OFFSET: 0x8 */
    SGMIIPLUSR_DIGITAL_RESERVED_TYPE rsvd2[10]; /* OFFSET: 0xa */
    SGMIIPLUSR_DIGITAL_SPARE_SGMIIPLUSR_X1_TYPE spare; /* OFFSET: 0x14 */
    SGMIIPLUSR_DIGITAL_MSX1_TYPE miscdigcontrol; /* OFFSET: 0x16 */
    SGMIIPLUSR_DIGITAL_C49BSX1_TYPE cl49_bercnt; /* OFFSET: 0x18 */
    SGMIIPLUSR_DIGITAL_RESERVED_TYPE rsvd3[4]; /* OFFSET: 0x1a */
    SGMIIPLUSR_DIGITAL_BSX1_TYPE blockaddress; /* OFFSET: 0x1e */
} SGMIIPLUSR_DIGITAL_RDBType;


#define DIGITAL_SGMIIPLUSR_X1_BASE      (0x4AED8600UL)



#define SGMIIPLUSR_DIGITAL_MAX_HW_ID    (1UL)

#endif /* SGMIIPLUSR_DIGITAL_RDB_H */
