/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file spum_apb_rdb.h
    @brief RDB File for SPUM_APB

    @version Orion_A0_20201104_SWDEV
*/

#ifndef SPUM_APB_RDB_H
#define SPUM_APB_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t SPUM_APB_CTRL_TYPE;
#define SPUM_APB_CTRL_PEN_MODE_MASK (0xc0000000UL)
#define SPUM_APB_CTRL_PEN_MODE_SHIFT (30UL)
#define SPUM_APB_CTRL_BD_SUPPRESS_MASK (0x80000UL)
#define SPUM_APB_CTRL_BD_SUPPRESS_SHIFT (19UL)
#define SPUM_APB_CTRL_CLE_FORMAT_EN_MASK (0x40000UL)
#define SPUM_APB_CTRL_CLE_FORMAT_EN_SHIFT (18UL)
#define SPUM_APB_CTRL_OUT_ENDIAN_MASK (0x1000UL)
#define SPUM_APB_CTRL_OUT_ENDIAN_SHIFT (12UL)
#define SPUM_APB_CTRL_IN_ENDIAN_MASK (0x800UL)
#define SPUM_APB_CTRL_IN_ENDIAN_SHIFT (11UL)
#define SPUM_APB_CTRL_SOFT_RST_MASK (0x2UL)
#define SPUM_APB_CTRL_SOFT_RST_SHIFT (1UL)




typedef uint8_t SPUM_APB_RESERVED_TYPE;




typedef uint32_t SPUM_APB_KEK_CS_TYPE;
#define SPUM_APB_KEK_CS_KEY_CACHE_ERR_MASK (0x80000000UL)
#define SPUM_APB_KEK_CS_KEY_CACHE_ERR_SHIFT (31UL)
#define SPUM_APB_KEK_CS_KEY_CACHE_EN_MASK (0x800000UL)
#define SPUM_APB_KEK_CS_KEY_CACHE_EN_SHIFT (23UL)
#define SPUM_APB_KEK_CS_DISABLE_DOUT_MASK (0x400000UL)
#define SPUM_APB_KEK_CS_DISABLE_DOUT_SHIFT (22UL)
#define SPUM_APB_KEK_CS_FLUSH_KEY_CACHE_MASK (0x2UL)
#define SPUM_APB_KEK_CS_FLUSH_KEY_CACHE_SHIFT (1UL)




typedef uint32_t SPUM_APB_SPU2EXTKEK_CTRL_TYPE;
#define SPUM_APB_SPU2EXTKEK_CTRL_START_MASK (0x80000000UL)
#define SPUM_APB_SPU2EXTKEK_CTRL_START_SHIFT (31UL)




typedef uint32_t SPUM_APB_SPU2EXTKEK_PKT_DETAILS_TYPE;
#define SPUM_APB_SPU2EXTKEK_PKT_DETAILS_REQUEST_TYPE_MASK (0xc0000000UL)
#define SPUM_APB_SPU2EXTKEK_PKT_DETAILS_REQUEST_TYPE_SHIFT (30UL)
#define SPUM_APB_SPU2EXTKEK_PKT_DETAILS_KEY_USAGE_MASK (0xf000000UL)
#define SPUM_APB_SPU2EXTKEK_PKT_DETAILS_KEY_USAGE_SHIFT (24UL)
#define SPUM_APB_SPU2EXTKEK_PKT_DETAILS_KEY_KIND_MASK (0xff0000UL)
#define SPUM_APB_SPU2EXTKEK_PKT_DETAILS_KEY_KIND_SHIFT (16UL)
#define SPUM_APB_SPU2EXTKEK_PKT_DETAILS_KEY_CACHE_ENTRY_LOC_MASK (0xff00UL)
#define SPUM_APB_SPU2EXTKEK_PKT_DETAILS_KEY_CACHE_ENTRY_LOC_SHIFT (8UL)
#define SPUM_APB_SPU2EXTKEK_PKT_DETAILS_KEYLOC_MASK (0xffUL)
#define SPUM_APB_SPU2EXTKEK_PKT_DETAILS_KEYLOC_SHIFT (0UL)




typedef uint32_t SPUM_APB_SPU2EXTKEK_STS_TYPE;
#define SPUM_APB_SPU2EXTKEK_STS_OUT_BUSY_MASK (0x80000000UL)
#define SPUM_APB_SPU2EXTKEK_STS_OUT_BUSY_SHIFT (31UL)
#define SPUM_APB_SPU2EXTKEK_STS_DONE_MASK (0x40000000UL)
#define SPUM_APB_SPU2EXTKEK_STS_DONE_SHIFT (30UL)
#define SPUM_APB_SPU2EXTKEK_STS_TIMEOUT_ERR_FLG_MASK (0x20000000UL)
#define SPUM_APB_SPU2EXTKEK_STS_TIMEOUT_ERR_FLG_SHIFT (29UL)




typedef uint32_t SPUM_APB_SPU2EXTKEK_RSLT_STS_TYPE;
#define SPUM_APB_SPU2EXTKEK_RSLT_STS_SIZE_MASK (0xffffUL)
#define SPUM_APB_SPU2EXTKEK_RSLT_STS_SIZE_SHIFT (0UL)




typedef uint32_t SPUM_APB_SPU2EXTKEK_ERR_STS_TYPE;
#define SPUM_APB_SPU2EXTKEK_ERR_STS_KEK_FLG_MASK (0x20000UL)
#define SPUM_APB_SPU2EXTKEK_ERR_STS_KEK_FLG_SHIFT (17UL)
#define SPUM_APB_SPU2EXTKEK_ERR_STS_KEK_CODE_MASK (0xff00UL)
#define SPUM_APB_SPU2EXTKEK_ERR_STS_KEK_CODE_SHIFT (8UL)




typedef uint32_t SPUM_APB_SPU2EXTKEK_TIMEOUT_EN_TYPE;
#define SPUM_APB_SPU2EXTKEK_TIMEOUT_EN_DIS_MASK (0x40000000UL)
#define SPUM_APB_SPU2EXTKEK_TIMEOUT_EN_DIS_SHIFT (30UL)
#define SPUM_APB_SPU2EXTKEK_TIMEOUT_EN_DELAY_MASK (0xffffUL)
#define SPUM_APB_SPU2EXTKEK_TIMEOUT_EN_DELAY_SHIFT (0UL)




typedef uint32_t SPUM_APB_SPU2EXTKEK_APB_BUFFER_TYPE;
#define SPUM_APB_SPU2EXTKEK_APB_BUFFER_WORD_MASK (0xffffffffUL)
#define SPUM_APB_SPU2EXTKEK_APB_BUFFER_WORD_SHIFT (0UL)




typedef volatile struct COMP_PACKED sSPUM_APB_RDBType {
    SPUM_APB_CTRL_TYPE ctrl; /* OFFSET: 0x0 */
    SPUM_APB_RESERVED_TYPE rsvd0[12]; /* OFFSET: 0x4 */
    SPUM_APB_KEK_CS_TYPE kek_cs; /* OFFSET: 0x10 */
    SPUM_APB_RESERVED_TYPE rsvd1[1036]; /* OFFSET: 0x14 */
    SPUM_APB_SPU2EXTKEK_CTRL_TYPE spu2extkek_ctrl; /* OFFSET: 0x420 */
    SPUM_APB_RESERVED_TYPE rsvd2[12]; /* OFFSET: 0x424 */
    SPUM_APB_SPU2EXTKEK_PKT_DETAILS_TYPE spu2extkek_pkt_details; /* OFFSET: 0x430 */
    SPUM_APB_RESERVED_TYPE rsvd3[12]; /* OFFSET: 0x434 */
    SPUM_APB_SPU2EXTKEK_STS_TYPE spu2extkek_sts; /* OFFSET: 0x440 */
    SPUM_APB_RESERVED_TYPE rsvd4[12]; /* OFFSET: 0x444 */
    SPUM_APB_SPU2EXTKEK_RSLT_STS_TYPE spu2extkek_rslt_sts; /* OFFSET: 0x450 */
    SPUM_APB_RESERVED_TYPE rsvd5[12]; /* OFFSET: 0x454 */
    SPUM_APB_SPU2EXTKEK_ERR_STS_TYPE spu2extkek_err_sts; /* OFFSET: 0x460 */
    SPUM_APB_RESERVED_TYPE rsvd6[12]; /* OFFSET: 0x464 */
    SPUM_APB_SPU2EXTKEK_TIMEOUT_EN_TYPE spu2extkek_timeout_en; /* OFFSET: 0x470 */
    SPUM_APB_RESERVED_TYPE rsvd7[12]; /* OFFSET: 0x474 */
    SPUM_APB_SPU2EXTKEK_APB_BUFFER_TYPE spu2extkek_apb_buffer; /* OFFSET: 0x480 */
} SPUM_APB_RDBType;


#define SPUM_APB_BASE                   (0x4C013000UL)



#define SPUM_APB_MAX_HW_ID              (1UL)

#endif /* SPUM_APB_RDB_H */
