/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file tim64_rdb.h
    @brief RDB File for TIM64

    @version Orion_A0_20201104_SWDEV
*/

#ifndef TIM64_RDB_H
#define TIM64_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint32_t TIM64_TIMER1LOADMSB_TYPE;
#define TIM64_TIMER1LOADMSB_TIMER1LOAD_MSB_MASK (0xffffffffUL)
#define TIM64_TIMER1LOADMSB_TIMER1LOAD_MSB_SHIFT (0UL)




typedef uint32_t TIM64_TIMER1LOAD_TYPE;
#define TIM64_TIMER1LOAD_TIMER1LOAD_MASK (0xffffffffUL)
#define TIM64_TIMER1LOAD_TIMER1LOAD_SHIFT (0UL)




typedef uint32_t TIM64_TIMER1VALUEMSB_TYPE;
#define TIM64_TIMER1VALUEMSB_TIMER1VALUE_MSB_MASK (0xffffffffUL)
#define TIM64_TIMER1VALUEMSB_TIMER1VALUE_MSB_SHIFT (0UL)




typedef uint32_t TIM64_TIMER1VALUE_TYPE;
#define TIM64_TIMER1VALUE_TIMER1VALUE_MASK (0xffffffffUL)
#define TIM64_TIMER1VALUE_TIMER1VALUE_SHIFT (0UL)




typedef uint32_t TIM64_TIMER1CONTROL_TYPE;
#define TIM64_TIMER1CONTROL_TIMER1EN_MASK (0x80UL)
#define TIM64_TIMER1CONTROL_TIMER1EN_SHIFT (7UL)
#define TIM64_TIMER1CONTROL_TIMER1MODE_MASK (0x40UL)
#define TIM64_TIMER1CONTROL_TIMER1MODE_SHIFT (6UL)
#define TIM64_TIMER1CONTROL_INTENABLE1_MASK (0x20UL)
#define TIM64_TIMER1CONTROL_INTENABLE1_SHIFT (5UL)
#define TIM64_TIMER1CONTROL_TIMER1PRE_MASK (0xcUL)
#define TIM64_TIMER1CONTROL_TIMER1PRE_SHIFT (2UL)
#define TIM64_TIMER1CONTROL_ONESHOT_TIMER1_MASK (0x1UL)
#define TIM64_TIMER1CONTROL_ONESHOT_TIMER1_SHIFT (0UL)




typedef uint32_t TIM64_TIMER1INTCLR_TYPE;
#define TIM64_TIMER1INTCLR_TIMER1INTCLR_MASK (0x1UL)
#define TIM64_TIMER1INTCLR_TIMER1INTCLR_SHIFT (0UL)




typedef uint32_t TIM64_TIMER1RIS_TYPE;
#define TIM64_TIMER1RIS_TIMER1RIS_MASK (0x1UL)
#define TIM64_TIMER1RIS_TIMER1RIS_SHIFT (0UL)




typedef uint32_t TIM64_TIMER1MIS_TYPE;
#define TIM64_TIMER1MIS_TIMER1MIS_MASK (0x1UL)
#define TIM64_TIMER1MIS_TIMER1MIS_SHIFT (0UL)




typedef uint32_t TIM64_TIMER1BGLOADMSB_TYPE;
#define TIM64_TIMER1BGLOADMSB_TIMER1BGLOAD_MSB_MASK (0xffffffffUL)
#define TIM64_TIMER1BGLOADMSB_TIMER1BGLOAD_MSB_SHIFT (0UL)




typedef uint32_t TIM64_TIMER1BGLOAD_TYPE;
#define TIM64_TIMER1BGLOAD_TIMER1BGLOAD_MASK (0xffffffffUL)
#define TIM64_TIMER1BGLOAD_TIMER1BGLOAD_SHIFT (0UL)




typedef uint8_t TIM64_RESERVED_TYPE;




typedef uint32_t TIM64_TIMER2LOADMSB_TYPE;
#define TIM64_TIMER2LOADMSB_TIMER2LOAD_MSB_MASK (0xffffffffUL)
#define TIM64_TIMER2LOADMSB_TIMER2LOAD_MSB_SHIFT (0UL)




typedef uint32_t TIM64_TIMER2LOAD_TYPE;
#define TIM64_TIMER2LOAD_TIMER2LOAD_MASK (0xffffffffUL)
#define TIM64_TIMER2LOAD_TIMER2LOAD_SHIFT (0UL)




typedef uint32_t TIM64_TIMER2VALUEMSB_TYPE;
#define TIM64_TIMER2VALUEMSB_TIMER2VALUE_MSB_MASK (0xffffffffUL)
#define TIM64_TIMER2VALUEMSB_TIMER2VALUE_MSB_SHIFT (0UL)




typedef uint32_t TIM64_TIMER2VALUE_TYPE;
#define TIM64_TIMER2VALUE_TIMER2VALUE_MASK (0xffffffffUL)
#define TIM64_TIMER2VALUE_TIMER2VALUE_SHIFT (0UL)




typedef uint32_t TIM64_TIMER2CONTROL_TYPE;
#define TIM64_TIMER2CONTROL_TIMER2EN_MASK (0x80UL)
#define TIM64_TIMER2CONTROL_TIMER2EN_SHIFT (7UL)
#define TIM64_TIMER2CONTROL_TIMER2MODE_MASK (0x40UL)
#define TIM64_TIMER2CONTROL_TIMER2MODE_SHIFT (6UL)
#define TIM64_TIMER2CONTROL_INTENABLE2_MASK (0x20UL)
#define TIM64_TIMER2CONTROL_INTENABLE2_SHIFT (5UL)
#define TIM64_TIMER2CONTROL_TIMER2PRE_MASK (0xcUL)
#define TIM64_TIMER2CONTROL_TIMER2PRE_SHIFT (2UL)
#define TIM64_TIMER2CONTROL_ONESHOT_TIMER2_MASK (0x1UL)
#define TIM64_TIMER2CONTROL_ONESHOT_TIMER2_SHIFT (0UL)




typedef uint32_t TIM64_TIMER2INTCLR_TYPE;
#define TIM64_TIMER2INTCLR_TIMER2INTCLR_MASK (0x1UL)
#define TIM64_TIMER2INTCLR_TIMER2INTCLR_SHIFT (0UL)




typedef uint32_t TIM64_TIMER2RIS_TYPE;
#define TIM64_TIMER2RIS_TIMER2RIS_MASK (0x1UL)
#define TIM64_TIMER2RIS_TIMER2RIS_SHIFT (0UL)




typedef uint32_t TIM64_TIMER2MIS_TYPE;
#define TIM64_TIMER2MIS_TIMER2MIS_MASK (0x1UL)
#define TIM64_TIMER2MIS_TIMER2MIS_SHIFT (0UL)




typedef uint32_t TIM64_TIMER2BGLOADMSB_TYPE;
#define TIM64_TIMER2BGLOADMSB_TIMER2BGLOAD_MSB_MASK (0xffffffffUL)
#define TIM64_TIMER2BGLOADMSB_TIMER2BGLOAD_MSB_SHIFT (0UL)




typedef uint32_t TIM64_TIMER2BGLOAD_TYPE;
#define TIM64_TIMER2BGLOAD_TIMER2BGLOAD_MASK (0xffffffffUL)
#define TIM64_TIMER2BGLOAD_TIMER2BGLOAD_SHIFT (0UL)




typedef uint32_t TIM64_TIMERITCR_TYPE;
#define TIM64_TIMERITCR_ITEN_MASK (0x1UL)
#define TIM64_TIMERITCR_ITEN_SHIFT (0UL)




typedef uint32_t TIM64_TIMERITOP_TYPE;
#define TIM64_TIMERITOP_TIMINT2_MASK (0x2UL)
#define TIM64_TIMERITOP_TIMINT2_SHIFT (1UL)
#define TIM64_TIMERITOP_TIMINT1_MASK (0x1UL)
#define TIM64_TIMERITOP_TIMINT1_SHIFT (0UL)




typedef uint32_t TIM64_TIMERPERIPHID0_TYPE;
#define TIM64_TIMERPERIPHID0_PARTNUMBER0_MASK (0xffUL)
#define TIM64_TIMERPERIPHID0_PARTNUMBER0_SHIFT (0UL)




typedef uint32_t TIM64_TIMERPERIPHID1_TYPE;
#define TIM64_TIMERPERIPHID1_DESIGNER0_MASK (0xf0UL)
#define TIM64_TIMERPERIPHID1_DESIGNER0_SHIFT (4UL)
#define TIM64_TIMERPERIPHID1_PARTNUMBER1_MASK (0xfUL)
#define TIM64_TIMERPERIPHID1_PARTNUMBER1_SHIFT (0UL)




typedef uint32_t TIM64_TIMERPERIPHID2_TYPE;
#define TIM64_TIMERPERIPHID2_REVISION_MASK (0xf0UL)
#define TIM64_TIMERPERIPHID2_REVISION_SHIFT (4UL)
#define TIM64_TIMERPERIPHID2_DESIGNER1_MASK (0xfUL)
#define TIM64_TIMERPERIPHID2_DESIGNER1_SHIFT (0UL)




typedef uint32_t TIM64_TIMERPERIPHID3_TYPE;
#define TIM64_TIMERPERIPHID3_CONFIGURATION_MASK (0xffUL)
#define TIM64_TIMERPERIPHID3_CONFIGURATION_SHIFT (0UL)




typedef uint32_t TIM64_TIMERPCELLID0_TYPE;
#define TIM64_TIMERPCELLID0_TIMERPCELLID0_MASK (0xffUL)
#define TIM64_TIMERPCELLID0_TIMERPCELLID0_SHIFT (0UL)




typedef uint32_t TIM64_TIMERPCELLID1_TYPE;
#define TIM64_TIMERPCELLID1_TIMERPCELLID1_MASK (0xffUL)
#define TIM64_TIMERPCELLID1_TIMERPCELLID1_SHIFT (0UL)




typedef uint32_t TIM64_TIMERPCELLID2_TYPE;
#define TIM64_TIMERPCELLID2_TIMERPCELLID2_MASK (0xffUL)
#define TIM64_TIMERPCELLID2_TIMERPCELLID2_SHIFT (0UL)




typedef uint32_t TIM64_TIMERPCELLID3_TYPE;
#define TIM64_TIMERPCELLID3_TIMERPCELLID3_MASK (0xffUL)
#define TIM64_TIMERPCELLID3_TIMERPCELLID3_SHIFT (0UL)




typedef volatile struct COMP_PACKED sTIM64_RDBType {
    TIM64_TIMER1LOADMSB_TYPE timer1loadmsb; /* OFFSET: 0x0 */
    TIM64_TIMER1LOAD_TYPE timer1load; /* OFFSET: 0x4 */
    TIM64_TIMER1VALUEMSB_TYPE timer1valuemsb; /* OFFSET: 0x8 */
    TIM64_TIMER1VALUE_TYPE timer1value; /* OFFSET: 0xc */
    TIM64_TIMER1CONTROL_TYPE timer1control; /* OFFSET: 0x10 */
    TIM64_TIMER1INTCLR_TYPE timer1intclr; /* OFFSET: 0x14 */
    TIM64_TIMER1RIS_TYPE timer1ris; /* OFFSET: 0x18 */
    TIM64_TIMER1MIS_TYPE timer1mis; /* OFFSET: 0x1c */
    TIM64_TIMER1BGLOADMSB_TYPE timer1bgloadmsb; /* OFFSET: 0x20 */
    TIM64_TIMER1BGLOAD_TYPE timer1bgload; /* OFFSET: 0x24 */
    TIM64_RESERVED_TYPE rsvd0[24]; /* OFFSET: 0x28 */
    TIM64_TIMER2LOADMSB_TYPE timer2loadmsb; /* OFFSET: 0x40 */
    TIM64_TIMER2LOAD_TYPE timer2load; /* OFFSET: 0x44 */
    TIM64_TIMER2VALUEMSB_TYPE timer2valuemsb; /* OFFSET: 0x48 */
    TIM64_TIMER2VALUE_TYPE timer2value; /* OFFSET: 0x4c */
    TIM64_TIMER2CONTROL_TYPE timer2control; /* OFFSET: 0x50 */
    TIM64_TIMER2INTCLR_TYPE timer2intclr; /* OFFSET: 0x54 */
    TIM64_TIMER2RIS_TYPE timer2ris; /* OFFSET: 0x58 */
    TIM64_TIMER2MIS_TYPE timer2mis; /* OFFSET: 0x5c */
    TIM64_TIMER2BGLOADMSB_TYPE timer2bgloadmsb; /* OFFSET: 0x60 */
    TIM64_TIMER2BGLOAD_TYPE timer2bgload; /* OFFSET: 0x64 */
    TIM64_RESERVED_TYPE rsvd1[3480]; /* OFFSET: 0x68 */
    TIM64_TIMERITCR_TYPE timeritcr; /* OFFSET: 0xe00 */
    TIM64_TIMERITOP_TYPE timeritop; /* OFFSET: 0xe04 */
    TIM64_RESERVED_TYPE rsvd2[472]; /* OFFSET: 0xe08 */
    TIM64_TIMERPERIPHID0_TYPE timerperiphid0; /* OFFSET: 0xfe0 */
    TIM64_TIMERPERIPHID1_TYPE timerperiphid1; /* OFFSET: 0xfe4 */
    TIM64_TIMERPERIPHID2_TYPE timerperiphid2; /* OFFSET: 0xfe8 */
    TIM64_TIMERPERIPHID3_TYPE timerperiphid3; /* OFFSET: 0xfec */
    TIM64_TIMERPCELLID0_TYPE timerpcellid0; /* OFFSET: 0xff0 */
    TIM64_TIMERPCELLID1_TYPE timerpcellid1; /* OFFSET: 0xff4 */
    TIM64_TIMERPCELLID2_TYPE timerpcellid2; /* OFFSET: 0xff8 */
    TIM64_TIMERPCELLID3_TYPE timerpcellid3; /* OFFSET: 0xffc */
} TIM64_RDBType;


#define TIM64_BASE                      (0x40142000UL)

#define M3_TIMER01_BASE                 (0x4C016000UL)

#define M3_TIMER23_BASE                 (0x4C017000UL)



#define TIM64_MAX_HW_ID                 (3UL)

#endif /* TIM64_RDB_H */
