/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file vtmon_rdb.h
    @brief RDB File for VTMON

    @version Orion_A0_20201104_SWDEV
*/

#ifndef VTMON_RDB_H
#define VTMON_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint8_t VTMON_RESERVED_TYPE;




typedef uint16_t VTMON_PVTMON_CTRL_TYPE;
#define VTMON_PVTMON_CTRL_VMON_3P3_EN_MASK (0x8000U)
#define VTMON_PVTMON_CTRL_VMON_3P3_EN_SHIFT (15U)
#define VTMON_PVTMON_CTRL_VMON_1P8_EN_MASK (0x4000U)
#define VTMON_PVTMON_CTRL_VMON_1P8_EN_SHIFT (14U)
#define VTMON_PVTMON_CTRL_VMON_1V_EN_MASK (0x2000U)
#define VTMON_PVTMON_CTRL_VMON_1V_EN_SHIFT (13U)
#define VTMON_PVTMON_CTRL_TMON_EN_MASK (0x1000U)
#define VTMON_PVTMON_CTRL_TMON_EN_SHIFT (12U)
#define VTMON_PVTMON_CTRL_PVTMON_EXT_INTR_EN_MASK (0x800U)
#define VTMON_PVTMON_CTRL_PVTMON_EXT_INTR_EN_SHIFT (11U)
#define VTMON_PVTMON_CTRL_PVTMON_INTR_EN_MASK (0x400U)
#define VTMON_PVTMON_CTRL_PVTMON_INTR_EN_SHIFT (10U)
#define VTMON_PVTMON_CTRL_CLKSEL_MASK (0x300U)
#define VTMON_PVTMON_CTRL_CLKSEL_SHIFT (8U)
#define VTMON_PVTMON_CTRL_I_PVTMON_SEL_MASK (0x70U)
#define VTMON_PVTMON_CTRL_I_PVTMON_SEL_SHIFT (4U)
#define VTMON_PVTMON_CTRL_AUTO_MODE_MASK (0x2U)
#define VTMON_PVTMON_CTRL_AUTO_MODE_SHIFT (1U)
#define VTMON_PVTMON_CTRL_I_PWRDN_MASK (0x1U)
#define VTMON_PVTMON_CTRL_I_PWRDN_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_SAMPLE_NUM_TYPE;
#define VTMON_PVTMON_SAMPLE_NUM_VMON_NUM_MASK (0xf0U)
#define VTMON_PVTMON_SAMPLE_NUM_VMON_NUM_SHIFT (4U)
#define VTMON_PVTMON_SAMPLE_NUM_TMON_NUM_MASK (0xfU)
#define VTMON_PVTMON_SAMPLE_NUM_TMON_NUM_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_TMON_PERIOD_TYPE;
#define VTMON_PVTMON_TMON_PERIOD_PERIOD_MASK (0xfU)
#define VTMON_PVTMON_TMON_PERIOD_PERIOD_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_I_CTRL_31_16_TYPE;
#define VTMON_PVTMON_I_CTRL_31_16_16_MASK (0xffffU)
#define VTMON_PVTMON_I_CTRL_31_16_16_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_I_CTRL_15_0_TYPE;
#define VTMON_PVTMON_I_CTRL_15_0_0_MASK (0xffffU)
#define VTMON_PVTMON_I_CTRL_15_0_0_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_ADC_DATA_TYPE;
#define VTMON_PVTMON_ADC_DATA_DATA_MASK (0x3ffU)
#define VTMON_PVTMON_ADC_DATA_DATA_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_DAC_DATA_TYPE;
#define VTMON_PVTMON_DAC_DATA_DATA_MASK (0x3ffU)
#define VTMON_PVTMON_DAC_DATA_DATA_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_TMON_THRESH1_CTRL_TYPE;
#define VTMON_PVTMON_TMON_THRESH1_CTRL_RESET_EN_MASK (0x800U)
#define VTMON_PVTMON_TMON_THRESH1_CTRL_RESET_EN_SHIFT (11U)
#define VTMON_PVTMON_TMON_THRESH1_CTRL_INTR_EN_MASK (0x400U)
#define VTMON_PVTMON_TMON_THRESH1_CTRL_INTR_EN_SHIFT (10U)
#define VTMON_PVTMON_TMON_THRESH1_CTRL_THRESH1_MASK (0x3ffU)
#define VTMON_PVTMON_TMON_THRESH1_CTRL_THRESH1_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_TMON_THRESH2_CTRL_TYPE;
#define VTMON_PVTMON_TMON_THRESH2_CTRL_RESET_EN_MASK (0x800U)
#define VTMON_PVTMON_TMON_THRESH2_CTRL_RESET_EN_SHIFT (11U)
#define VTMON_PVTMON_TMON_THRESH2_CTRL_INTR_EN_MASK (0x400U)
#define VTMON_PVTMON_TMON_THRESH2_CTRL_INTR_EN_SHIFT (10U)
#define VTMON_PVTMON_TMON_THRESH2_CTRL_THRESH2_MASK (0x3ffU)
#define VTMON_PVTMON_TMON_THRESH2_CTRL_THRESH2_SHIFT (0U)




typedef uint16_t VTMON_PV1HT1C_TYPE;
#define VTMON_PV1HT1C_VMON_1V_H_THRESH1_RESET_EN_MASK (0x800U)
#define VTMON_PV1HT1C_VMON_1V_H_THRESH1_RESET_EN_SHIFT (11U)
#define VTMON_PV1HT1C_VMON_1V_H_THRESH1_INTR_EN_MASK (0x400U)
#define VTMON_PV1HT1C_VMON_1V_H_THRESH1_INTR_EN_SHIFT (10U)
#define VTMON_PV1HT1C_VMON_1V_H_THRESH1_MASK (0x3ffU)
#define VTMON_PV1HT1C_VMON_1V_H_THRESH1_SHIFT (0U)




typedef uint16_t VTMON_PV1HT2C_TYPE;
#define VTMON_PV1HT2C_VMON_1V_H_THRESH2_RESET_EN_MASK (0x800U)
#define VTMON_PV1HT2C_VMON_1V_H_THRESH2_RESET_EN_SHIFT (11U)
#define VTMON_PV1HT2C_VMON_1V_H_THRESH2_INTR_EN_MASK (0x400U)
#define VTMON_PV1HT2C_VMON_1V_H_THRESH2_INTR_EN_SHIFT (10U)
#define VTMON_PV1HT2C_VMON_1V_H_THRESH2_MASK (0x3ffU)
#define VTMON_PV1HT2C_VMON_1V_H_THRESH2_SHIFT (0U)




typedef uint16_t VTMON_PV1LT1C_TYPE;
#define VTMON_PV1LT1C_VMON_1V_L_THRESH1_RESET_EN_MASK (0x800U)
#define VTMON_PV1LT1C_VMON_1V_L_THRESH1_RESET_EN_SHIFT (11U)
#define VTMON_PV1LT1C_VMON_1V_L_THRESH1_INTR_EN_MASK (0x400U)
#define VTMON_PV1LT1C_VMON_1V_L_THRESH1_INTR_EN_SHIFT (10U)
#define VTMON_PV1LT1C_VMON_1V_L_THRESH1_MASK (0x3ffU)
#define VTMON_PV1LT1C_VMON_1V_L_THRESH1_SHIFT (0U)




typedef uint16_t VTMON_PV1LT2C_TYPE;
#define VTMON_PV1LT2C_VMON_1V_L_THRESH2_RESET_EN_MASK (0x800U)
#define VTMON_PV1LT2C_VMON_1V_L_THRESH2_RESET_EN_SHIFT (11U)
#define VTMON_PV1LT2C_VMON_1V_L_THRESH2_INTR_EN_MASK (0x400U)
#define VTMON_PV1LT2C_VMON_1V_L_THRESH2_INTR_EN_SHIFT (10U)
#define VTMON_PV1LT2C_VMON_1V_L_THRESH2_MASK (0x3ffU)
#define VTMON_PV1LT2C_VMON_1V_L_THRESH2_SHIFT (0U)




typedef uint16_t VTMON_PV18HT1C_TYPE;
#define VTMON_PV18HT1C_VMON_1P8V_H_THRESH1_RESET_EN_MASK (0x800U)
#define VTMON_PV18HT1C_VMON_1P8V_H_THRESH1_RESET_EN_SHIFT (11U)
#define VTMON_PV18HT1C_VMON_1P8V_H_THRESH1_INTR_EN_MASK (0x400U)
#define VTMON_PV18HT1C_VMON_1P8V_H_THRESH1_INTR_EN_SHIFT (10U)
#define VTMON_PV18HT1C_VMON_1P8V_H_THRESH1_MASK (0x3ffU)
#define VTMON_PV18HT1C_VMON_1P8V_H_THRESH1_SHIFT (0U)




typedef uint16_t VTMON_PV18HT2C_TYPE;
#define VTMON_PV18HT2C_VMON_1P8V_H_THRESH2_RESET_EN_MASK (0x800U)
#define VTMON_PV18HT2C_VMON_1P8V_H_THRESH2_RESET_EN_SHIFT (11U)
#define VTMON_PV18HT2C_VMON_1P8V_H_THRESH2_INTR_EN_MASK (0x400U)
#define VTMON_PV18HT2C_VMON_1P8V_H_THRESH2_INTR_EN_SHIFT (10U)
#define VTMON_PV18HT2C_VMON_1P8V_H_THRESH2_MASK (0x3ffU)
#define VTMON_PV18HT2C_VMON_1P8V_H_THRESH2_SHIFT (0U)




typedef uint16_t VTMON_PV18LT1C_TYPE;
#define VTMON_PV18LT1C_VMON_1P8V_L_THRESH1_RESET_EN_MASK (0x800U)
#define VTMON_PV18LT1C_VMON_1P8V_L_THRESH1_RESET_EN_SHIFT (11U)
#define VTMON_PV18LT1C_VMON_1P8V_L_THRESH1_INTR_EN_MASK (0x400U)
#define VTMON_PV18LT1C_VMON_1P8V_L_THRESH1_INTR_EN_SHIFT (10U)
#define VTMON_PV18LT1C_VMON_1P8V_L_THRESH1_MASK (0x3ffU)
#define VTMON_PV18LT1C_VMON_1P8V_L_THRESH1_SHIFT (0U)




typedef uint16_t VTMON_PV18LT2C_TYPE;
#define VTMON_PV18LT2C_VMON_1P8V_L_THRESH2_RESET_EN_MASK (0x800U)
#define VTMON_PV18LT2C_VMON_1P8V_L_THRESH2_RESET_EN_SHIFT (11U)
#define VTMON_PV18LT2C_VMON_1P8V_L_THRESH2_INTR_EN_MASK (0x400U)
#define VTMON_PV18LT2C_VMON_1P8V_L_THRESH2_INTR_EN_SHIFT (10U)
#define VTMON_PV18LT2C_VMON_1P8V_L_THRESH2_MASK (0x3ffU)
#define VTMON_PV18LT2C_VMON_1P8V_L_THRESH2_SHIFT (0U)




typedef uint16_t VTMON_PV33HT1C_TYPE;
#define VTMON_PV33HT1C_VMON_3P3V_H_THRESH1_RESET_EN_MASK (0x800U)
#define VTMON_PV33HT1C_VMON_3P3V_H_THRESH1_RESET_EN_SHIFT (11U)
#define VTMON_PV33HT1C_VMON_3P3V_H_THRESH1_INTR_EN_MASK (0x400U)
#define VTMON_PV33HT1C_VMON_3P3V_H_THRESH1_INTR_EN_SHIFT (10U)
#define VTMON_PV33HT1C_VMON_3P3V_H_THRESH1_MASK (0x3ffU)
#define VTMON_PV33HT1C_VMON_3P3V_H_THRESH1_SHIFT (0U)




typedef uint16_t VTMON_PV33HT2C_TYPE;
#define VTMON_PV33HT2C_VMON_3P3V_H_THRESH2_RESET_EN_MASK (0x800U)
#define VTMON_PV33HT2C_VMON_3P3V_H_THRESH2_RESET_EN_SHIFT (11U)
#define VTMON_PV33HT2C_VMON_3P3V_H_THRESH2_INTR_EN_MASK (0x400U)
#define VTMON_PV33HT2C_VMON_3P3V_H_THRESH2_INTR_EN_SHIFT (10U)
#define VTMON_PV33HT2C_VMON_3P3V_H_THRESH2_MASK (0x3ffU)
#define VTMON_PV33HT2C_VMON_3P3V_H_THRESH2_SHIFT (0U)




typedef uint16_t VTMON_PV33LT1C_TYPE;
#define VTMON_PV33LT1C_VMON_3P3V_L_THRESH1_RESET_EN_MASK (0x800U)
#define VTMON_PV33LT1C_VMON_3P3V_L_THRESH1_RESET_EN_SHIFT (11U)
#define VTMON_PV33LT1C_VMON_3P3V_L_THRESH1_INTR_EN_MASK (0x400U)
#define VTMON_PV33LT1C_VMON_3P3V_L_THRESH1_INTR_EN_SHIFT (10U)
#define VTMON_PV33LT1C_VMON_3P3V_L_THRESH1_MASK (0x3ffU)
#define VTMON_PV33LT1C_VMON_3P3V_L_THRESH1_SHIFT (0U)




typedef uint16_t VTMON_PV33LT2C_TYPE;
#define VTMON_PV33LT2C_VMON_3P3V_L_THRESH2_RESET_EN_MASK (0x800U)
#define VTMON_PV33LT2C_VMON_3P3V_L_THRESH2_RESET_EN_SHIFT (11U)
#define VTMON_PV33LT2C_VMON_3P3V_L_THRESH2_INTR_EN_MASK (0x400U)
#define VTMON_PV33LT2C_VMON_3P3V_L_THRESH2_INTR_EN_SHIFT (10U)
#define VTMON_PV33LT2C_VMON_3P3V_L_THRESH2_MASK (0x3ffU)
#define VTMON_PV33LT2C_VMON_3P3V_L_THRESH2_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_THRESHOLD_FILTER_TYPE;
#define VTMON_PVTMON_THRESHOLD_FILTER_FILTER_MASK (0xffU)
#define VTMON_PVTMON_THRESHOLD_FILTER_FILTER_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_VIOL_RAWSTS_TYPE;
#define VTMON_PVTMON_VIOL_RAWSTS_TMON_THRESH1_VIOL_MASK (0x1U)
#define VTMON_PVTMON_VIOL_RAWSTS_TMON_THRESH1_VIOL_SHIFT (0U)
#define VTMON_PVTMON_VIOL_RAWSTS_TMON_THRESH2_VIOL_MASK (0x2U)
#define VTMON_PVTMON_VIOL_RAWSTS_TMON_THRESH2_VIOL_SHIFT (1U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1V_H_THRESH1_VIOL_MASK (0x4U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1V_H_THRESH1_VIOL_SHIFT (2U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1V_H_THRESH2_VIOL_MASK (0x8U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1V_H_THRESH2_VIOL_SHIFT (3U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1V_L_THRESH1_VIOL_MASK (0x10U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1V_L_THRESH1_VIOL_SHIFT (4U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1V_L_THRESH2_VIOL_MASK (0x20U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1V_L_THRESH2_VIOL_SHIFT (5U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1P8V_H_THRESH1_VIOL_MASK (0x40U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1P8V_H_THRESH1_VIOL_SHIFT (6U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1P8V_H_THRESH2_VIOL_MASK (0x80U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1P8V_H_THRESH2_VIOL_SHIFT (7U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1P8V_L_THRESH1_VIOL_MASK (0x100U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1P8V_L_THRESH1_VIOL_SHIFT (8U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1P8V_L_THRESH2_VIOL_MASK (0x200U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_1P8V_L_THRESH2_VIOL_SHIFT (9U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_3P3V_H_THRESH1_VIOL_MASK (0x400U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_3P3V_H_THRESH1_VIOL_SHIFT (10U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_3P3V_H_THRESH2_VIOL_MASK (0x800U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_3P3V_H_THRESH2_VIOL_SHIFT (11U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_3P3V_L_THRESH1_VIOL_MASK (0x1000U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_3P3V_L_THRESH1_VIOL_SHIFT (12U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_3P3V_L_THRESH2_VIOL_MASK (0x2000U)
#define VTMON_PVTMON_VIOL_RAWSTS_VMON_3P3V_L_THRESH2_VIOL_SHIFT (13U)




typedef uint16_t VTMON_PVTMON_INTR_STATUS_TYPE;
#define VTMON_PVTMON_INTR_STATUS_TMON_THRESH1_INTR_MASK (0x1U)
#define VTMON_PVTMON_INTR_STATUS_TMON_THRESH1_INTR_SHIFT (0U)
#define VTMON_PVTMON_INTR_STATUS_TMON_THRESH2_INTR_MASK (0x2U)
#define VTMON_PVTMON_INTR_STATUS_TMON_THRESH2_INTR_SHIFT (1U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1V_H_THRESH1_INTR_MASK (0x4U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1V_H_THRESH1_INTR_SHIFT (2U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1V_H_THRESH2_INTR_MASK (0x8U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1V_H_THRESH2_INTR_SHIFT (3U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1V_L_THRESH1_INTR_MASK (0x10U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1V_L_THRESH1_INTR_SHIFT (4U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1V_L_THRESH2_INTR_MASK (0x20U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1V_L_THRESH2_INTR_SHIFT (5U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1P8V_H_THRESH1_INTR_MASK (0x40U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1P8V_H_THRESH1_INTR_SHIFT (6U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1P8V_H_THRESH2_INTR_MASK (0x80U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1P8V_H_THRESH2_INTR_SHIFT (7U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1P8V_L_THRESH1_INTR_MASK (0x100U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1P8V_L_THRESH1_INTR_SHIFT (8U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1P8V_L_THRESH2_INTR_MASK (0x200U)
#define VTMON_PVTMON_INTR_STATUS_VMON_1P8V_L_THRESH2_INTR_SHIFT (9U)
#define VTMON_PVTMON_INTR_STATUS_VMON_3P3V_H_THRESH1_INTR_MASK (0x400U)
#define VTMON_PVTMON_INTR_STATUS_VMON_3P3V_H_THRESH1_INTR_SHIFT (10U)
#define VTMON_PVTMON_INTR_STATUS_VMON_3P3V_H_THRESH2_INTR_MASK (0x800U)
#define VTMON_PVTMON_INTR_STATUS_VMON_3P3V_H_THRESH2_INTR_SHIFT (11U)
#define VTMON_PVTMON_INTR_STATUS_VMON_3P3V_L_THRESH1_INTR_MASK (0x1000U)
#define VTMON_PVTMON_INTR_STATUS_VMON_3P3V_L_THRESH1_INTR_SHIFT (12U)
#define VTMON_PVTMON_INTR_STATUS_VMON_3P3V_L_THRESH2_INTR_MASK (0x2000U)
#define VTMON_PVTMON_INTR_STATUS_VMON_3P3V_L_THRESH2_INTR_SHIFT (13U)




typedef uint16_t VTMON_PIC_TYPE;
#define VTMON_PIC_TMON_THRESH1_INTSTS_CLEAR_MASK (0x1U)
#define VTMON_PIC_TMON_THRESH1_INTSTS_CLEAR_SHIFT (0U)
#define VTMON_PIC_TMON_THRESH2_INTSTS_CLEAR_MASK (0x2U)
#define VTMON_PIC_TMON_THRESH2_INTSTS_CLEAR_SHIFT (1U)
#define VTMON_PIC_VMON_1V_H_THRESH1_INTSTS_CLEAR_MASK (0x4U)
#define VTMON_PIC_VMON_1V_H_THRESH1_INTSTS_CLEAR_SHIFT (2U)
#define VTMON_PIC_VMON_1V_H_THRESH2_INTSTS_CLEAR_MASK (0x8U)
#define VTMON_PIC_VMON_1V_H_THRESH2_INTSTS_CLEAR_SHIFT (3U)
#define VTMON_PIC_VMON_1V_L_THRESH1_INTSTS_CLEAR_MASK (0x10U)
#define VTMON_PIC_VMON_1V_L_THRESH1_INTSTS_CLEAR_SHIFT (4U)
#define VTMON_PIC_VMON_1V_L_THRESH2_INTSTS_CLEAR_MASK (0x20U)
#define VTMON_PIC_VMON_1V_L_THRESH2_INTSTS_CLEAR_SHIFT (5U)
#define VTMON_PIC_VMON_1P8V_H_THRESH1_INTSTS_CLEAR_MASK (0x40U)
#define VTMON_PIC_VMON_1P8V_H_THRESH1_INTSTS_CLEAR_SHIFT (6U)
#define VTMON_PIC_VMON_1P8V_H_THRESH2_INTSTS_CLEAR_MASK (0x80U)
#define VTMON_PIC_VMON_1P8V_H_THRESH2_INTSTS_CLEAR_SHIFT (7U)
#define VTMON_PIC_VMON_1P8V_L_THRESH1_INTSTS_CLEAR_MASK (0x100U)
#define VTMON_PIC_VMON_1P8V_L_THRESH1_INTSTS_CLEAR_SHIFT (8U)
#define VTMON_PIC_VMON_1P8V_L_THRESH2_INTSTS_CLEAR_MASK (0x200U)
#define VTMON_PIC_VMON_1P8V_L_THRESH2_INTSTS_CLEAR_SHIFT (9U)
#define VTMON_PIC_VMON_3P3V_H_THRESH1_INTSTS_CLEAR_MASK (0x400U)
#define VTMON_PIC_VMON_3P3V_H_THRESH1_INTSTS_CLEAR_SHIFT (10U)
#define VTMON_PIC_VMON_3P3V_H_THRESH2_INTSTS_CLEAR_MASK (0x800U)
#define VTMON_PIC_VMON_3P3V_H_THRESH2_INTSTS_CLEAR_SHIFT (11U)
#define VTMON_PIC_VMON_3P3V_L_THRESH1_INTSTS_CLEAR_MASK (0x1000U)
#define VTMON_PIC_VMON_3P3V_L_THRESH1_INTSTS_CLEAR_SHIFT (12U)
#define VTMON_PIC_VMON_3P3V_L_THRESH2_INTSTS_CLEAR_MASK (0x2000U)
#define VTMON_PIC_VMON_3P3V_L_THRESH2_INTSTS_CLEAR_SHIFT (13U)




typedef uint16_t VTMON_PVTMON_INTERRUPT_COUNT_TYPE;
#define VTMON_PVTMON_INTERRUPT_COUNT_COUNT_MASK (0xffffU)
#define VTMON_PVTMON_INTERRUPT_COUNT_COUNT_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_TMON_SAMPLE_TYPE;
#define VTMON_PVTMON_TMON_SAMPLE_SAMPLE_MASK (0x3ffU)
#define VTMON_PVTMON_TMON_SAMPLE_SAMPLE_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_VMON_1V_SAMPLE_TYPE;
#define VTMON_PVTMON_VMON_1V_SAMPLE_SAMPLE_MASK (0x3ffU)
#define VTMON_PVTMON_VMON_1V_SAMPLE_SAMPLE_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_VMON_1P8V_SAMPLE_TYPE;
#define VTMON_PVTMON_VMON_1P8V_SAMPLE_SAMPLE_MASK (0x3ffU)
#define VTMON_PVTMON_VMON_1P8V_SAMPLE_SAMPLE_SHIFT (0U)




typedef uint16_t VTMON_PVTMON_VMON_3P3V_SAMPLE_TYPE;
#define VTMON_PVTMON_VMON_3P3V_SAMPLE_SAMPLE_MASK (0x3ffU)
#define VTMON_PVTMON_VMON_3P3V_SAMPLE_SAMPLE_SHIFT (0U)




typedef volatile struct COMP_PACKED sVTMON_RDBType {
    VTMON_RESERVED_TYPE rsvd0[512]; /* OFFSET: 0x0 */
    VTMON_PVTMON_CTRL_TYPE ctrl; /* OFFSET: 0x200 */
    VTMON_PVTMON_SAMPLE_NUM_TYPE sample_num; /* OFFSET: 0x202 */
    VTMON_PVTMON_TMON_PERIOD_TYPE tmon_period; /* OFFSET: 0x204 */
    VTMON_PVTMON_I_CTRL_31_16_TYPE i_ctrl_31_16; /* OFFSET: 0x206 */
    VTMON_PVTMON_I_CTRL_15_0_TYPE i_ctrl_15_0; /* OFFSET: 0x208 */
    VTMON_PVTMON_ADC_DATA_TYPE adc_data; /* OFFSET: 0x20a */
    VTMON_PVTMON_DAC_DATA_TYPE dac_data; /* OFFSET: 0x20c */
    VTMON_PVTMON_TMON_THRESH1_CTRL_TYPE tmon_thresh1_ctrl; /* OFFSET: 0x20e */
    VTMON_PVTMON_TMON_THRESH2_CTRL_TYPE tmon_thresh2_ctrl; /* OFFSET: 0x210 */
    VTMON_PV1HT1C_TYPE vmon_1v_h_thresh1_ctrl; /* OFFSET: 0x212 */
    VTMON_PV1HT2C_TYPE vmon_1v_h_thresh2_ctrl; /* OFFSET: 0x214 */
    VTMON_PV1LT1C_TYPE vmon_1v_l_thresh1_ctrl; /* OFFSET: 0x216 */
    VTMON_PV1LT2C_TYPE vmon_1v_l_thresh2_ctrl; /* OFFSET: 0x218 */
    VTMON_PV18HT1C_TYPE vmon_1p8v_h_thresh1_ctrl; /* OFFSET: 0x21a */
    VTMON_PV18HT2C_TYPE vmon_1p8v_h_thresh2_ctrl; /* OFFSET: 0x21c */
    VTMON_PV18LT1C_TYPE vmon_1p8v_l_thresh1_ctrl; /* OFFSET: 0x21e */
    VTMON_PV18LT2C_TYPE vmon_1p8v_l_thresh2_ctrl; /* OFFSET: 0x220 */
    VTMON_PV33HT1C_TYPE vmon_3p3v_h_thresh1_ctrl; /* OFFSET: 0x222 */
    VTMON_PV33HT2C_TYPE vmon_3p3v_h_thresh2_ctrl; /* OFFSET: 0x224 */
    VTMON_PV33LT1C_TYPE vmon_3p3v_l_thresh1_ctrl; /* OFFSET: 0x226 */
    VTMON_PV33LT2C_TYPE vmon_3p3v_l_thresh2_ctrl; /* OFFSET: 0x228 */
    VTMON_PVTMON_THRESHOLD_FILTER_TYPE threshold_filter; /* OFFSET: 0x22a */
    VTMON_PVTMON_VIOL_RAWSTS_TYPE viol_rawsts; /* OFFSET: 0x22c */
    VTMON_PVTMON_INTR_STATUS_TYPE intr_status; /* OFFSET: 0x22e */
    VTMON_PIC_TYPE intsts_clear; /* OFFSET: 0x230 */
    VTMON_PVTMON_INTERRUPT_COUNT_TYPE interrupt_count; /* OFFSET: 0x232 */
    VTMON_PVTMON_TMON_SAMPLE_TYPE tmon_sample; /* OFFSET: 0x234 */
    VTMON_PVTMON_VMON_1V_SAMPLE_TYPE vmon_1v_sample; /* OFFSET: 0x236 */
    VTMON_PVTMON_VMON_1P8V_SAMPLE_TYPE vmon_1p8v_sample; /* OFFSET: 0x238 */
    VTMON_PVTMON_VMON_3P3V_SAMPLE_TYPE vmon_3p3v_sample; /* OFFSET: 0x23a */
    VTMON_RESERVED_TYPE rsvd1[3524]; /* OFFSET: 0x23c */
} VTMON_RDBType;


#define VTMON_BASE                      (0x4A800000UL)



#define VTMON_MAX_HW_ID                 (1UL)


#define VTMON_TEMP_BIAS                 (41335000L)


#define VTMON_TEMP_PRESCALE             (49055L)


#define VTMON_TEMP_DIV                  (100000L)


#define VTMON_TEMP_CLKSEL               (2L )


#define VTMON_I_PVTMON_SEL              (4L )


#define VTMON_VOLT_1                    (7168L)


#define VTMON_VOLT_2                    (8800L)


#define VTMON_TEMP(aVal)                (((int16_t)((VTMON_TEMP_BIAS - (((int32_t)(aVal)) * VTMON_TEMP_PRESCALE)) / VTMON_TEMP_DIV)))


#define VTMON_VOLT(aVal)                (((int16_t)((((int32_t)(aVal)) * VTMON_VOLT_2) / VTMON_VOLT_1)))

#endif /* VTMON_RDB_H */
