/*****************************************************************************
 Copyright 2022 Broadcom Limited.  All rights reserved.

 This program is the proprietary software of Broadcom Limited and/or its
 licensors, and may only be used, duplicated, modified or distributed pursuant
 to the terms and conditions of a separate, written license agreement executed
 between you and Broadcom (an "Authorized License").

 Except as set forth in an Authorized License, Broadcom grants no license
 (express or implied), right to use, or waiver of any kind with respect to the
 Software, and Broadcom expressly reserves all rights in and to the Software
 and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
 LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.

  Except as expressly set forth in the Authorized License,
 1. This program, including its structure, sequence and organization,
    constitutes the valuable trade secrets of Broadcom, and you shall use all
    reasonable efforts to protect the confidentiality thereof, and to use this
    information only in connection with your use of Broadcom integrated
    circuit products.

 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
    SOFTWARE.

 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
******************************************************************************/
/**
    @file xgxsblk0_rdb.h
    @brief RDB File for XGXSBLK0

    @version Orion_A0_20201104_SWDEV
*/

#ifndef XGXSBLK0_RDB_H
#define XGXSBLK0_RDB_H

#include <stdint.h>

#include <compiler.h>


typedef uint16_t XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_TYPE;
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_START_SEQUENCER_MASK (0x2000U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_START_SEQUENCER_SHIFT (13U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_MODE_MASK (0xf00U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_MODE_SHIFT (8U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_HSTL_MASK (0x20U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_HSTL_SHIFT (5U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_MDIO_CONT_EN_MASK (0x10U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_MDIO_CONT_EN_SHIFT (4U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_CDET_EN_MASK (0x8U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_CDET_EN_SHIFT (3U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_EDEN_MASK (0x4U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_EDEN_SHIFT (2U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_AFRST_EN_MASK (0x2U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_AFRST_EN_SHIFT (1U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_TXCKO_DIV_MASK (0x1U)
#define XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_TXCKO_DIV_SHIFT (0U)




typedef uint8_t XGXSBLK0_RESERVED_TYPE;




typedef uint16_t XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_TYPE;
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_MULTIPRTS_EN_MASK (0x8000U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_MULTIPRTS_EN_SHIFT (15U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_MULTIMMDS_EN_MASK (0x4000U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_MULTIMMDS_EN_SHIFT (14U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_PRTAD_BCST_DISABLE_MASK (0x2000U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_PRTAD_BCST_DISABLE_SHIFT (13U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_DEVAN_EN_MASK (0x8U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_DEVAN_EN_SHIFT (3U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_DEVPMD_EN_MASK (0x4U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_DEVPMD_EN_SHIFT (2U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_DEVDEVAD_EN_MASK (0x2U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_DEVDEVAD_EN_SHIFT (1U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_DEVCL22_EN_MASK (0x1U)
#define XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_DEVCL22_EN_SHIFT (0U)




typedef uint16_t XGXSBLK0_MISCCONTROL1_SGMIIPLUS2_X2_TYPE;
#define XGXSBLK0_MISCCONTROL1_SGMIIPLUS2_X2_IEEE_BLKSEL_AUTODET_MASK (0x2U)
#define XGXSBLK0_MISCCONTROL1_SGMIIPLUS2_X2_IEEE_BLKSEL_AUTODET_SHIFT (1U)
#define XGXSBLK0_MISCCONTROL1_SGMIIPLUS2_X2_IEEE_BLKSEL_VAL_MASK (0x1U)
#define XGXSBLK0_MISCCONTROL1_SGMIIPLUS2_X2_IEEE_BLKSEL_VAL_SHIFT (0U)




typedef uint16_t XGXSBLK0_BLOCKADDRESS_SGMIIPLUS2_X2_TYPE;
#define XGXSBLK0_BLOCKADDRESS_SGMIIPLUS2_X2_BLOCKADDRESS_MASK (0x7ff0U)
#define XGXSBLK0_BLOCKADDRESS_SGMIIPLUS2_X2_BLOCKADDRESS_SHIFT (4U)




typedef volatile struct COMP_PACKED sXGXSBLK0_RDBType {
    XGXSBLK0_XGXSCONTROL_SGMIIPLUS2_X2_TYPE xgxscontrol; /* OFFSET: 0x0 */
    XGXSBLK0_RESERVED_TYPE rsvd0[24]; /* OFFSET: 0x2 */
    XGXSBLK0_MMDSELECT_SGMIIPLUS2_X2_TYPE mmdselect; /* OFFSET: 0x1a */
    XGXSBLK0_MISCCONTROL1_SGMIIPLUS2_X2_TYPE misccontrol1; /* OFFSET: 0x1c */
    XGXSBLK0_BLOCKADDRESS_SGMIIPLUS2_X2_TYPE blockaddress; /* OFFSET: 0x1e */
} XGXSBLK0_RDBType;


#define BLK0_BASE                       (0x4ACD0000UL)



#define XGXSBLK0_MAX_HW_ID              (1UL)


#define XGXSBLK0_BLOCK_ADDRESS_VAL      (0x0U)

#endif /* XGXSBLK0_RDB_H */
