#!/usr/bin/python2

# $Id$
# $Copyright: Copyright 2021 Broadcom Limited.
# This program is the proprietary software of Broadcom Limited
# and/or its licensors, and may only be used, duplicated, modified
# or distributed pursuant to the terms and conditions of a separate,
# written license agreement executed between you and Broadcom
# = an "Authorized License").  Except as set forth in an Authorized
# License, Broadcom grants no license = express or implied), right
# to use, or waiver of any kind with respect to the Software, and
# Broadcom expressly reserves all rights in and to the Software
# and all intellectual property rights therein.  IF YOU HAVE
# NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
# IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
# ALL USE OF THE SOFTWARE.
#
# Except as expressly set forth in the Authorized License,
#
# 1.     This program, including its structure, sequence and organization,
# constitutes the valuable trade secrets of Broadcom, and you shall use
# all reasonable efforts to protect the confidentiality thereof,
# and to use this information only in connection with your use of
# Broadcom integrated circuit products.
#
# 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
# PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
# REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
# OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
# DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
# NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
# ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
# CORRESPONDENCE TO nameRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
# OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
#
# 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
# BROADCOM OR ITS LICENSORS BE LIABLE FOR = i) CONSEQUENTIAL,
# INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
# ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
# TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGES; OR = ii) ANY AMOUNT IN EXCESS OF
# THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
# WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
# ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
####################################################################################

CHIPMISC_MODEL_REV_NUM_MODEL_NUM_MASK     = 0x3f0
CHIPMISC_MODEL_REV_NUM_MODEL_NUM_SHIFT       = 4
CHIPMISC_MODEL_REV_NUM_REV_NUM_MASK       = 0xf
CHIPMISC_MODEL_REV_NUM_REV_NUM_SHIFT      = 0

CHIPMISC_DEVICEID_LO_DEVICE_ID_LO_MASK       = 0xfff
CHIPMISC_DEVICEID_LO_DEVICE_ID_LO_SHIFT      = 0

CHIPMISC_DEVICEID_HI_DEVICE_ID_HI_MASK       = 0xff
CHIPMISC_DEVICEID_HI_DEVICE_ID_HI_SHIFT      = 0

CHIPMISC_SWITCH_MISC_CTRL_PDA_ALL_MEM_FOR_SWITCH_MASK       = 0x8000
CHIPMISC_SWITCH_MISC_CTRL_PDA_ALL_MEM_FOR_SWITCH_SHIFT      = 15
CHIPMISC_SWITCH_MISC_CTRL_DIRECT_GATE_PORT_MASK       = 0x1ff
CHIPMISC_SWITCH_MISC_CTRL_DIRECT_GATE_PORT_SHIFT      = 0

CHIPMISC_LDO_PWRDN_PWRDN_MASK       = 0x1
CHIPMISC_LDO_PWRDN_PWRDN_SHIFT      = 0

CHIPMISC_LDO_VREG_1_BG_REF_VOLTAGE_TRIMMING_MASK      = 0x7800
CHIPMISC_LDO_VREG_1_BG_REF_VOLTAGE_TRIMMING_SHIFT     = 11
CHIPMISC_LDO_VREG_1_INRUSH_CURRENT_ADJUSTMENT_MASK       = 0x400
CHIPMISC_LDO_VREG_1_INRUSH_CURRENT_ADJUSTMENT_SHIFT      = 10
CHIPMISC_LDO_VREG_1_CURRENT_LIMIT_ADJUSTMENT_MASK     = 0x200
CHIPMISC_LDO_VREG_1_CURRENT_LIMIT_ADJUSTMENT_SHIFT       = 9
CHIPMISC_LDO_VREG_1_LEAKAGE_SENSING_CONTROL_MASK      = 0x100
CHIPMISC_LDO_VREG_1_LEAKAGE_SENSING_CONTROL_SHIFT     = 8
CHIPMISC_LDO_VREG_1_OUTPUT_VOLTAGE_TUNING_MASK     = 0xf0
CHIPMISC_LDO_VREG_1_OUTPUT_VOLTAGE_TUNING_SHIFT       = 4
CHIPMISC_LDO_VREG_1_BTCT_MASK       = 0xf
CHIPMISC_LDO_VREG_1_BTCT_SHIFT      = 0

CHIPMISC_LDO_VREGCNTL_2_ZERO_POSITION_ADJUSTMENT_MASK       = 0xc
CHIPMISC_LDO_VREGCNTL_2_ZERO_POSITION_ADJUSTMENT_SHIFT      = 2
CHIPMISC_LDO_VREGCNTL_2_LEAKAGE_SENSING_ADJUSTMENT_MASK     = 0x3
CHIPMISC_LDO_VREGCNTL_2_LEAKAGE_SENSING_ADJUSTMENT_SHIFT       = 0

CHIPMISC_LDO_VREGCNTLEN_VREGCNTLEN_MASK      = 0x1
CHIPMISC_LDO_VREGCNTLEN_VREGCNTLEN_SHIFT     = 0

CHIPMISC_SWREG_CTRL_REG0_SWREG_SOFTRESET_MASK      = 0x1
CHIPMISC_SWREG_CTRL_REG0_SWREG_SOFTRESET_SHIFT     = 0
CHIPMISC_SWREG_CTRL_REG0_UPDATE_CTRL_REG_POSEDGE_MASK       = 0x2
CHIPMISC_SWREG_CTRL_REG0_UPDATE_CTRL_REG_POSEDGE_SHIFT      = 1
CHIPMISC_SWREG_CTRL_REG0_COMP_LP_CTRL_MASK      = 0x4
CHIPMISC_SWREG_CTRL_REG0_COMP_LP_CTRL_SHIFT     = 2
CHIPMISC_SWREG_CTRL_REG0_COMP_LOOP_GAIN1_CTRL_MASK       = 0x8
CHIPMISC_SWREG_CTRL_REG0_COMP_LOOP_GAIN1_CTRL_SHIFT      = 3
CHIPMISC_SWREG_CTRL_REG0_COMP_LOOP_GAIN2_CTRL_MASK       = 0x70
CHIPMISC_SWREG_CTRL_REG0_COMP_LOOP_GAIN2_CTRL_SHIFT      = 4
CHIPMISC_SWREG_CTRL_REG0_BURST_R_CTRL_MASK      = 0x600
CHIPMISC_SWREG_CTRL_REG0_BURST_R_CTRL_SHIFT     = 9
CHIPMISC_SWREG_CTRL_REG0_SD_DITHER_DIS_MASK     = 0x800
CHIPMISC_SWREG_CTRL_REG0_SD_DITHER_DIS_SHIFT       = 11
CHIPMISC_SWREG_CTRL_REG0_FAULT_0_ILIM_DUTYCYCLE_EN_MASK     = 0x1000
CHIPMISC_SWREG_CTRL_REG0_FAULT_0_ILIM_DUTYCYCLE_EN_SHIFT       = 12
CHIPMISC_SWREG_CTRL_REG0_FAULT_1_ILIM_ADCOUT_EN_MASK     = 0x2000
CHIPMISC_SWREG_CTRL_REG0_FAULT_1_ILIM_ADCOUT_EN_SHIFT       = 13
CHIPMISC_SWREG_CTRL_REG0_FAULT_OV_EN_MASK       = 0x4000
CHIPMISC_SWREG_CTRL_REG0_FAULT_OV_EN_SHIFT      = 14
CHIPMISC_SWREG_CTRL_REG0_JITTERFILTER_DIS_MASK     = 0x8000
CHIPMISC_SWREG_CTRL_REG0_JITTERFILTER_DIS_SHIFT       = 15

CHIPMISC_SWREG_CTRL_REG1_COMP_SS_CTRL_MASK      = 0x3
CHIPMISC_SWREG_CTRL_REG1_COMP_SS_CTRL_SHIFT     = 0
CHIPMISC_SWREG_CTRL_REG1_SD_FREQ_CTRL_MASK      = 0xc
CHIPMISC_SWREG_CTRL_REG1_SD_FREQ_CTRL_SHIFT     = 2
CHIPMISC_SWREG_CTRL_REG1_FAULT_DUTYCYCLE_MASK      = 0x30
CHIPMISC_SWREG_CTRL_REG1_FAULT_DUTYCYCLE_SHIFT     = 4
CHIPMISC_SWREG_CTRL_REG1_FAULT_ADCOUT_CTRL_MASK       = 0xc0
CHIPMISC_SWREG_CTRL_REG1_FAULT_ADCOUT_CTRL_SHIFT      = 6
CHIPMISC_SWREG_CTRL_REG1_COMP_COEF1_SEL_MASK       = 0xff00
CHIPMISC_SWREG_CTRL_REG1_COMP_COEF1_SEL_SHIFT      = 8

CHIPMISC_SWREG_CTRL_REG2_COMP_COEF1_SEL_MASK       = 0x3
CHIPMISC_SWREG_CTRL_REG2_COMP_COEF1_SEL_SHIFT      = 0
CHIPMISC_SWREG_CTRL_REG2_COMP_COEF2_SEL_MASK       = 0xffc
CHIPMISC_SWREG_CTRL_REG2_COMP_COEF2_SEL_SHIFT      = 2
CHIPMISC_SWREG_CTRL_REG2_SD_DUTYMIN_3_0_MASK       = 0xf000
CHIPMISC_SWREG_CTRL_REG2_SD_DUTYMIN_3_0_SHIFT      = 12

CHIPMISC_SWREG_CTRL_REG3_SD_DUTYMIN_6_4_MASK       = 0x7
CHIPMISC_SWREG_CTRL_REG3_SD_DUTYMIN_6_4_SHIFT      = 0
CHIPMISC_SWREG_CTRL_REG3_SD_DUTYMAX_MASK     = 0xff8
CHIPMISC_SWREG_CTRL_REG3_SD_DUTYMAX_SHIFT       = 3
CHIPMISC_SWREG_CTRL_REG3_FAULT_ADCOUT_REF_3_0_MASK       = 0xf000
CHIPMISC_SWREG_CTRL_REG3_FAULT_ADCOUT_REF_3_0_SHIFT      = 12

CHIPMISC_SWREG_CTRL_REG4_FAULT_ADCOUT_REF_9_4_MASK       = 0x3f
CHIPMISC_SWREG_CTRL_REG4_FAULT_ADCOUT_REF_9_4_SHIFT      = 0
CHIPMISC_SWREG_CTRL_REG4_ILIM_DUTYCYCLE_REF_MASK      = 0xffc0
CHIPMISC_SWREG_CTRL_REG4_ILIM_DUTYCYCLE_REF_SHIFT     = 6

CHIPMISC_SWREG_CTRL_REG5_PMU_STABLE_OVERRIDE_BSTI_MASK      = 0x1
CHIPMISC_SWREG_CTRL_REG5_PMU_STABLE_OVERRIDE_BSTI_SHIFT     = 0
CHIPMISC_SWREG_CTRL_REG5_FETS_ENB_DELAY_CTRL_MASK     = 0xc
CHIPMISC_SWREG_CTRL_REG5_FETS_ENB_DELAY_CTRL_SHIFT       = 2
CHIPMISC_SWREG_CTRL_REG5_NOVL_CTRL_MASK      = 0x70
CHIPMISC_SWREG_CTRL_REG5_NOVL_CTRL_SHIFT     = 4
CHIPMISC_SWREG_CTRL_REG5_DUTYCYCLE_ILIM_FAULT_0_MASK_MASK      = 0x80
CHIPMISC_SWREG_CTRL_REG5_DUTYCYCLE_ILIM_FAULT_0_MASK_SHIFT     = 7
CHIPMISC_SWREG_CTRL_REG5_ADCOUT_ILIM_FAULT_1_MASK_MASK      = 0x100
CHIPMISC_SWREG_CTRL_REG5_ADCOUT_ILIM_FAULT_1_MASK_SHIFT     = 8
CHIPMISC_SWREG_CTRL_REG5_ANALOG_COMP_ILIM_FAULT2_MASK_MASK     = 0x200
CHIPMISC_SWREG_CTRL_REG5_ANALOG_COMP_ILIM_FAULT2_MASK_SHIFT       = 9
CHIPMISC_SWREG_CTRL_REG5_OV_FAULT_MASK_MASK     = 0x400
CHIPMISC_SWREG_CTRL_REG5_OV_FAULT_MASK_SHIFT       = 10
CHIPMISC_SWREG_CTRL_REG5_PLL_EN_MASK      = 0x800
CHIPMISC_SWREG_CTRL_REG5_PLL_EN_SHIFT     = 11
CHIPMISC_SWREG_CTRL_REG5_BURST_MODE_EN_MASK     = 0x1000
CHIPMISC_SWREG_CTRL_REG5_BURST_MODE_EN_SHIFT       = 12
CHIPMISC_SWREG_CTRL_REG5_BURST_D_CTRL_2_0_MASK     = 0xe000
CHIPMISC_SWREG_CTRL_REG5_BURST_D_CTRL_2_0_SHIFT       = 13

CHIPMISC_SWREG_CTRL_REG6_DVDD_CTRL_MASK      = 0x3
CHIPMISC_SWREG_CTRL_REG6_DVDD_CTRL_SHIFT     = 0
CHIPMISC_SWREG_CTRL_REG6_BG_TRIM_CTRL_MASK      = 0xfc
CHIPMISC_SWREG_CTRL_REG6_BG_TRIM_CTRL_SHIFT     = 2
CHIPMISC_SWREG_CTRL_REG6_REF_CTRL_MASK       = 0xff00
CHIPMISC_SWREG_CTRL_REG6_REF_CTRL_SHIFT      = 8

CHIPMISC_SWREG_CTRL_REG7_NDRIVE_PFET_MASK       = 0x7
CHIPMISC_SWREG_CTRL_REG7_NDRIVE_PFET_SHIFT      = 0
CHIPMISC_SWREG_CTRL_REG7_NDRIVE_NFET_MASK       = 0x38
CHIPMISC_SWREG_CTRL_REG7_NDRIVE_NFET_SHIFT      = 3
CHIPMISC_SWREG_CTRL_REG7_PDRIVE_PFET_MASK       = 0x1c0
CHIPMISC_SWREG_CTRL_REG7_PDRIVE_PFET_SHIFT      = 6
CHIPMISC_SWREG_CTRL_REG7_PDRIVE_NFET_MASK       = 0xe00
CHIPMISC_SWREG_CTRL_REG7_PDRIVE_NFET_SHIFT      = 9
CHIPMISC_SWREG_CTRL_REG7_ADAPT_NOVL_MASK     = 0x3000
CHIPMISC_SWREG_CTRL_REG7_ADAPT_NOVL_SHIFT       = 12
CHIPMISC_SWREG_CTRL_REG7_PULSE_WIDTH_LIMIT_MASK       = 0xc000
CHIPMISC_SWREG_CTRL_REG7_PULSE_WIDTH_LIMIT_SHIFT      = 14

CHIPMISC_SWREG_CTRL_REG8_RGM_CTRL_MASK       = 0x7
CHIPMISC_SWREG_CTRL_REG8_RGM_CTRL_SHIFT      = 0
CHIPMISC_SWREG_CTRL_REG8_OSC_ADJ_MASK     = 0x38
CHIPMISC_SWREG_CTRL_REG8_OSC_ADJ_SHIFT       = 3
CHIPMISC_SWREG_CTRL_REG8_PHASE_CNTRL_EN_MASK       = 0x40
CHIPMISC_SWREG_CTRL_REG8_PHASE_CNTRL_EN_SHIFT      = 6
CHIPMISC_SWREG_CTRL_REG8_GMBIAS_CTRL_MASK       = 0x80
CHIPMISC_SWREG_CTRL_REG8_GMBIAS_CTRL_SHIFT      = 7
CHIPMISC_SWREG_CTRL_REG8_PHASE_CNTRL_COMP_WIDTH_MASK     = 0x100
CHIPMISC_SWREG_CTRL_REG8_PHASE_CNTRL_COMP_WIDTH_SHIFT       = 8
CHIPMISC_SWREG_CTRL_REG8_IVCO_CTRL_MASK      = 0xe00
CHIPMISC_SWREG_CTRL_REG8_IVCO_CTRL_SHIFT     = 9
CHIPMISC_SWREG_CTRL_REG8_BURST_D_CTRL_6_3_MASK     = 0xf000
CHIPMISC_SWREG_CTRL_REG8_BURST_D_CTRL_6_3_SHIFT       = 12

CHIPMISC_SWREG_CTRL_REG9_TEST_MODE_ADC_MASK     = 0x1
CHIPMISC_SWREG_CTRL_REG9_TEST_MODE_ADC_SHIFT       = 0
CHIPMISC_SWREG_CTRL_REG9_TEST_MODE_VBG_MASK     = 0x2
CHIPMISC_SWREG_CTRL_REG9_TEST_MODE_VBG_SHIFT       = 1
CHIPMISC_SWREG_CTRL_REG9_OVERCUR_REF_CTRL_MASK     = 0xc
CHIPMISC_SWREG_CTRL_REG9_OVERCUR_REF_CTRL_SHIFT       = 2
CHIPMISC_SWREG_CTRL_REG9_ADAPTIVE_DEADTIME_DIS_MASK      = 0x10
CHIPMISC_SWREG_CTRL_REG9_ADAPTIVE_DEADTIME_DIS_SHIFT     = 4
CHIPMISC_SWREG_CTRL_REG9_ADAPTIVE_DEADTIME_CTRL_MASK     = 0x60
CHIPMISC_SWREG_CTRL_REG9_ADAPTIVE_DEADTIME_CTRL_SHIFT       = 5
CHIPMISC_SWREG_CTRL_REG9_NON_LINEAR_GAIN_MASK      = 0x100
CHIPMISC_SWREG_CTRL_REG9_NON_LINEAR_GAIN_SHIFT     = 8
CHIPMISC_SWREG_CTRL_REG9_NON_LINEAR_GAIN_EN_MASK      = 0x200
CHIPMISC_SWREG_CTRL_REG9_NON_LINEAR_GAIN_EN_SHIFT     = 9
CHIPMISC_SWREG_CTRL_REG9_ADC_GAIN_MASK       = 0xc00
CHIPMISC_SWREG_CTRL_REG9_ADC_GAIN_SHIFT      = 10
CHIPMISC_SWREG_CTRL_REG9_SYS_CLK_FREQ_MASK      = 0x3000
CHIPMISC_SWREG_CTRL_REG9_SYS_CLK_FREQ_SHIFT     = 12
CHIPMISC_SWREG_CTRL_REG9_ADC_FREQ_MASK       = 0xc000
CHIPMISC_SWREG_CTRL_REG9_ADC_FREQ_SHIFT      = 14

CHIPMISC_SWREG_STAT_REG12_ADC_COMP_IN_MASK      = 0xff
CHIPMISC_SWREG_STAT_REG12_ADC_COMP_IN_SHIFT     = 0
CHIPMISC_SWREG_STAT_REG12_DUTY_CYCLE_MASK       = 0x100
CHIPMISC_SWREG_STAT_REG12_DUTY_CYCLE_SHIFT      = 8
CHIPMISC_SWREG_STAT_REG12_UNDERVOLTAGE_FAULT_MASK     = 0x200
CHIPMISC_SWREG_STAT_REG12_UNDERVOLTAGE_FAULT_SHIFT       = 9
CHIPMISC_SWREG_STAT_REG12_OVERVOLTAGE_FAULT_MASK      = 0x800
CHIPMISC_SWREG_STAT_REG12_OVERVOLTAGE_FAULT_SHIFT     = 11

CHIPMISC_SWREG_STAT_REG13_ILIM_DUTYCYCLE_MASK      = 0x3ff
CHIPMISC_SWREG_STAT_REG13_ILIM_DUTYCYCLE_SHIFT     = 0

CHIPMISC_SWREG_STAT_REG14_ILIM_ADCOUT_MASK      = 0x7ff
CHIPMISC_SWREG_STAT_REG14_ILIM_ADCOUT_SHIFT     = 0

CHIPMISC_SWREG_STAT_REG15_ANA_CURR_LIMIT_MASK      = 0x1
CHIPMISC_SWREG_STAT_REG15_ANA_CURR_LIMIT_SHIFT     = 0
CHIPMISC_SWREG_STAT_REG15_PVIN_SELECT_1P5_MASK     = 0x6
CHIPMISC_SWREG_STAT_REG15_PVIN_SELECT_1P5_SHIFT       = 1
CHIPMISC_SWREG_STAT_REG15_VIN_SELECT_1P5_MASK      = 0x18
CHIPMISC_SWREG_STAT_REG15_VIN_SELECT_1P5_SHIFT     = 3
CHIPMISC_SWREG_STAT_REG15_DIG_DUTY_CYCLE_CURR_LIMIT_FAULT_MASK       = 0x2000
CHIPMISC_SWREG_STAT_REG15_DIG_DUTY_CYCLE_CURR_LIMIT_FAULT_SHIFT      = 13
CHIPMISC_SWREG_STAT_REG15_DIG_UV_FAULT_MASK     = 0x4000
CHIPMISC_SWREG_STAT_REG15_DIG_UV_FAULT_SHIFT       = 14
CHIPMISC_SWREG_STAT_REG15_DIG_OV_FAULT_MASK     = 0x8000
CHIPMISC_SWREG_STAT_REG15_DIG_OV_FAULT_SHIFT       = 15

CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_9_MASK       = 0x200
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_9_SHIFT      = 9
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_8_MASK       = 0x100
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_8_SHIFT      = 8
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_7_MASK       = 0x80
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_7_SHIFT      = 7
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_6_MASK       = 0x40
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_6_SHIFT      = 6
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_5_MASK       = 0x20
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_5_SHIFT      = 5
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_4_MASK       = 0x10
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_4_SHIFT      = 4
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_3_MASK       = 0x8
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_3_SHIFT      = 3
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_2_MASK       = 0x4
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_2_SHIFT      = 2
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_1_MASK       = 0x2
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_1_SHIFT      = 1
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_0_MASK       = 0x1
CHIPMISC_SWREG_ACCESS_CTRL_1_WRITE_0_SHIFT      = 0

CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_15_MASK     = 0x8000
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_15_SHIFT       = 15
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_14_MASK     = 0x4000
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_14_SHIFT       = 14
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_13_MASK     = 0x2000
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_13_SHIFT       = 13
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_12_MASK     = 0x1000
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_STAT_12_SHIFT       = 12
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_9_MASK      = 0x200
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_9_SHIFT     = 9
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_8_MASK      = 0x100
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_8_SHIFT     = 8
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_7_MASK      = 0x80
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_7_SHIFT     = 7
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_6_MASK      = 0x40
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_6_SHIFT     = 6
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_5_MASK      = 0x20
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_5_SHIFT     = 5
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_4_MASK      = 0x10
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_4_SHIFT     = 4
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_3_MASK      = 0x8
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_3_SHIFT     = 3
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_2_MASK      = 0x4
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_2_SHIFT     = 2
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_1_MASK      = 0x2
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_1_SHIFT     = 1
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_0_MASK      = 0x1
CHIPMISC_SWREG_ACCESS_CTRL_2_READ_CTRL_0_SHIFT     = 0

CHIPMISC_SWREG_CONTROL_STATUS_PMU_STABLE_STATUS_MASK     = 0x1
CHIPMISC_SWREG_CONTROL_STATUS_PMU_STABLE_STATUS_SHIFT       = 0
CHIPMISC_SWREG_CONTROL_STATUS_EXT_PLLCLK_EN_MASK      = 0x2
CHIPMISC_SWREG_CONTROL_STATUS_EXT_PLLCLK_EN_SHIFT     = 1

CHIPMISC_SGMII_PLUS2_PWRDWN_PWRDWN_MASK      = 0x1
CHIPMISC_SGMII_PLUS2_PWRDWN_PWRDWN_SHIFT     = 0

CHIPMISC_SGMII_PLUS2_HW_RST_DLY_VAL_VAL_MASK       = 0x7fff
CHIPMISC_SGMII_PLUS2_HW_RST_DLY_VAL_VAL_SHIFT      = 0

CHIPMISC_SGMII_PLUS2_MDIO_RST_DLY_VAL_VAL_MASK     = 0x1fff
CHIPMISC_SGMII_PLUS2_MDIO_RST_DLY_VAL_VAL_SHIFT       = 0

CHIPMISC_SGMII_PLUS2_PLL_RST_DLY_VAL_VAL_MASK      = 0xfff
CHIPMISC_SGMII_PLUS2_PLL_RST_DLY_VAL_VAL_SHIFT     = 0

CHIPMISC_SGMII_PLUS2_EXT_CTL_RESCAL_AUTOLOAD_EN_MASK     = 0x800
CHIPMISC_SGMII_PLUS2_EXT_CTL_RESCAL_AUTOLOAD_EN_SHIFT       = 11
CHIPMISC_SGMII_PLUS2_EXT_CTL_REFSEL_MASK     = 0x300
CHIPMISC_SGMII_PLUS2_EXT_CTL_REFSEL_SHIFT       = 8
CHIPMISC_SGMII_PLUS2_EXT_CTL_RESCAL_MASK     = 0xf0
CHIPMISC_SGMII_PLUS2_EXT_CTL_RESCAL_SHIFT       = 4
CHIPMISC_SGMII_PLUS2_EXT_CTL_SPARE_MASK      = 0xf
CHIPMISC_SGMII_PLUS2_EXT_CTL_SPARE_SHIFT     = 0

CHIPMISC_SGMII_PLUS2_MDIO_CTL_SGMII_BROADCAST_EN_MASK       = 0x200
CHIPMISC_SGMII_PLUS2_MDIO_CTL_SGMII_BROADCAST_EN_SHIFT      = 9
CHIPMISC_SGMII_PLUS2_MDIO_CTL_MD_DEVAD_MASK     = 0x1f
CHIPMISC_SGMII_PLUS2_MDIO_CTL_MD_DEVAD_SHIFT       = 0

CHIPMISC_SGMII_PLUS2_STATUS_STATUS_MASK      = 0xffff
CHIPMISC_SGMII_PLUS2_STATUS_STATUS_SHIFT     = 0

CHIPMISC_SGMII_PCIE_PWRDWN_PWRDWN_MASK       = 0x1
CHIPMISC_SGMII_PCIE_PWRDWN_PWRDWN_SHIFT      = 0

CHIPMISC_SGMII_PCIE_HW_RST_DLY_VAL_VAL_MASK     = 0x7fff
CHIPMISC_SGMII_PCIE_HW_RST_DLY_VAL_VAL_SHIFT       = 0

CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_PCB_RD_ACK_POS_SEL_MASK      = 0x4000
CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_PCB_RD_ACK_POS_SEL_SHIFT     = 14
CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_PCB_RD_CYCLE_LEN_SEL_MASK       = 0x2000
CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_PCB_RD_CYCLE_LEN_SEL_SHIFT      = 13
CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_MDIO_RST_DLY_VAL_MASK     = 0x1fff
CHIPMISC_SGMII_PCIE_MDIO_RST_DLY_VAL_MDIO_RST_DLY_VAL_SHIFT       = 0

CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PCB_WR_ACK_POS_SEL_MASK       = 0x4000
CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PCB_WR_ACK_POS_SEL_SHIFT      = 14
CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PCB_WR_CYCLE_LEN_SEL_MASK     = 0x3000
CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PCB_WR_CYCLE_LEN_SEL_SHIFT       = 12
CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PLL_RST_DLY_VAL_MASK       = 0xfff
CHIPMISC_SGMII_PCIE_PLL_RST_DLY_VAL_PLL_RST_DLY_VAL_SHIFT      = 0

CHIPMISC_SGMII_PCIE_EXT_CTL_RESCAL_AUTOLOAD_EN_MASK      = 0x800
CHIPMISC_SGMII_PCIE_EXT_CTL_RESCAL_AUTOLOAD_EN_SHIFT     = 11
CHIPMISC_SGMII_PCIE_EXT_CTL_REFSEL_MASK      = 0x300
CHIPMISC_SGMII_PCIE_EXT_CTL_REFSEL_SHIFT     = 8
CHIPMISC_SGMII_PCIE_EXT_CTL_SPARE2_MASK      = 0xe0
CHIPMISC_SGMII_PCIE_EXT_CTL_SPARE2_SHIFT     = 5
CHIPMISC_SGMII_PCIE_EXT_CTL_RESCAL_MASK      = 0x1e
CHIPMISC_SGMII_PCIE_EXT_CTL_RESCAL_SHIFT     = 1
CHIPMISC_SGMII_PCIE_EXT_CTL_SPARE_MASK       = 0x1
CHIPMISC_SGMII_PCIE_EXT_CTL_SPARE_SHIFT      = 0

CHIPMISC_SGMII_PCIE_MDIO_CTL_MD_DEVAD_MASK      = 0x1f
CHIPMISC_SGMII_PCIE_MDIO_CTL_MD_DEVAD_SHIFT     = 0

CHIPMISC_SGMII_PCIE_STATUS_STATUS_MASK       = 0xffff
CHIPMISC_SGMII_PCIE_STATUS_STATUS_SHIFT      = 0

CHIPMISC_SGMII_AFE_STATUS_SPARE15TO5_MASK       = 0xffe0
CHIPMISC_SGMII_AFE_STATUS_SPARE15TO5_SHIFT      = 5
CHIPMISC_SGMII_AFE_STATUS_AFE_CAL_DONE_MASK     = 0x10
CHIPMISC_SGMII_AFE_STATUS_AFE_CAL_DONE_SHIFT       = 4
CHIPMISC_SGMII_AFE_STATUS_SPARE3_MASK     = 0x8
CHIPMISC_SGMII_AFE_STATUS_SPARE3_SHIFT       = 3
CHIPMISC_SGMII_AFE_STATUS_SGMII_TXPLL_LOCK1_MASK      = 0x4
CHIPMISC_SGMII_AFE_STATUS_SGMII_TXPLL_LOCK1_SHIFT     = 2
CHIPMISC_SGMII_AFE_STATUS_SGMII_PCIE_TXPLL_LOCK_MASK     = 0x2
CHIPMISC_SGMII_AFE_STATUS_SGMII_PCIE_TXPLL_LOCK_SHIFT       = 1
CHIPMISC_SGMII_AFE_STATUS_SGMII_TXPLL_LOCK0_MASK      = 0x1
CHIPMISC_SGMII_AFE_STATUS_SGMII_TXPLL_LOCK0_SHIFT     = 0

CHIPMISC_SGMII_PLUSR_PWRDWN_PWRDWN_MASK      = 0x1
CHIPMISC_SGMII_PLUSR_PWRDWN_PWRDWN_SHIFT     = 0

CHIPMISC_SGMII_PLUSR_HW_RST_DLY_VAL_VAL_MASK       = 0x7fff
CHIPMISC_SGMII_PLUSR_HW_RST_DLY_VAL_VAL_SHIFT      = 0

CHIPMISC_SGMII_PLUSR_PLL_RST_DLY_VAL_VAL_MASK      = 0xfff
CHIPMISC_SGMII_PLUSR_PLL_RST_DLY_VAL_VAL_SHIFT     = 0

CHIPMISC_SGMII_PLUSR_EXT_CTL_RESCAL_AUTOLOAD_EN_MASK     = 0x800
CHIPMISC_SGMII_PLUSR_EXT_CTL_RESCAL_AUTOLOAD_EN_SHIFT       = 11
CHIPMISC_SGMII_PLUSR_EXT_CTL_REFSEL_MASK     = 0x300
CHIPMISC_SGMII_PLUSR_EXT_CTL_REFSEL_SHIFT       = 8
CHIPMISC_SGMII_PLUSR_EXT_CTL_RESCAL_MASK     = 0xf0
CHIPMISC_SGMII_PLUSR_EXT_CTL_RESCAL_SHIFT       = 4
CHIPMISC_SGMII_PLUSR_EXT_CTL_SPARE_MASK      = 0xf
CHIPMISC_SGMII_PLUSR_EXT_CTL_SPARE_SHIFT     = 0

CHIPMISC_SGMII_PLUSR_MDIO_CTL_FAST_MODE_MASK       = 0x400
CHIPMISC_SGMII_PLUSR_MDIO_CTL_FAST_MODE_SHIFT      = 10

CHIPMISC_SGMII_PLUSR_STATUS_STATUS_MASK      = 0xffff
CHIPMISC_SGMII_PLUSR_STATUS_STATUS_SHIFT     = 0

CHIPMISC_BOOTROM_STATUS_FIRMWARE_EXECUTED_MASK     = 0x8000
CHIPMISC_BOOTROM_STATUS_FIRMWARE_EXECUTED_SHIFT       = 15
CHIPMISC_BOOTROM_STATUS_BOOTROM_LOADED_MASK     = 0x4000
CHIPMISC_BOOTROM_STATUS_BOOTROM_LOADED_SHIFT       = 14
CHIPMISC_BOOTROM_STATUS_SPARE_MASK     = 0x3c00
CHIPMISC_BOOTROM_STATUS_SPARE_SHIFT       = 10
CHIPMISC_BOOTROM_STATUS_CRC_STATUS_MASK      = 0x200
CHIPMISC_BOOTROM_STATUS_CRC_STATUS_SHIFT     = 9
CHIPMISC_BOOTROM_STATUS_IMAGE_KEY_MASK       = 0x100
CHIPMISC_BOOTROM_STATUS_IMAGE_KEY_SHIFT      = 8
CHIPMISC_BOOTROM_STATUS_IMAGE_TYPE_MASK      = 0xc0
CHIPMISC_BOOTROM_STATUS_IMAGE_TYPE_SHIFT     = 6
CHIPMISC_BOOTROM_STATUS_IMAGE_COUNT_MASK     = 0x3c
CHIPMISC_BOOTROM_STATUS_IMAGE_COUNT_SHIFT       = 2
CHIPMISC_BOOTROM_STATUS_FINAL_IMAGE_MASK     = 0x2
CHIPMISC_BOOTROM_STATUS_FINAL_IMAGE_SHIFT       = 1
CHIPMISC_BOOTROM_STATUS_CRC_CHECK_ENABLE_MASK      = 0x1
CHIPMISC_BOOTROM_STATUS_CRC_CHECK_ENABLE_SHIFT     = 0

CHIPMISC_BOOTROM_VERSION_FIRMWARE_VERSION_MASK     = 0xe000
CHIPMISC_BOOTROM_VERSION_FIRMWARE_VERSION_SHIFT       = 13
CHIPMISC_BOOTROM_VERSION_MONTH_MASK       = 0x1e00
CHIPMISC_BOOTROM_VERSION_MONTH_SHIFT      = 9
CHIPMISC_BOOTROM_VERSION_DAY_MASK      = 0x1f0
CHIPMISC_BOOTROM_VERSION_DAY_SHIFT     = 4
CHIPMISC_BOOTROM_VERSION_YEAR_MASK     = 0xf
CHIPMISC_BOOTROM_VERSION_YEAR_SHIFT       = 0

CHIPMISC_SPARE_HW_REG_REG_MASK      = 0xffff
CHIPMISC_SPARE_HW_REG_REG_SHIFT     = 0

CHIPMISC_F1_VERSION_VERSION_MASK       = 0xffff
CHIPMISC_F1_VERSION_VERSION_SHIFT      = 0

CHIPMISC_PKG_MODEL_SPARE_MASK       = 0xffc0
CHIPMISC_PKG_MODEL_SPARE_SHIFT      = 6
CHIPMISC_PKG_MODEL_PKG_MODEL_MASK      = 0x3f
CHIPMISC_PKG_MODEL_PKG_MODEL_SHIFT     = 0

CHIPMISC_SPARE_SW_REG_REG_MASK      = 0xffff
CHIPMISC_SPARE_SW_REG_REG_SHIFT     = 0

CHIPMISC_CPUSYS_MISC_SPARE_MASK     = 0xfff0
CHIPMISC_CPUSYS_MISC_SPARE_SHIFT       = 4
CHIPMISC_CPUSYS_MISC_ACCESS_INT_SLV_THRO_MDIO_MST_MASK      = 0x8
CHIPMISC_CPUSYS_MISC_ACCESS_INT_SLV_THRO_MDIO_MST_SHIFT     = 3
CHIPMISC_CPUSYS_MISC_INTR_OUT_EN_PCIE_MASK      = 0x4
CHIPMISC_CPUSYS_MISC_INTR_OUT_EN_PCIE_SHIFT     = 2
CHIPMISC_CPUSYS_MISC_INTR_OUT_EN_PAD_MASK       = 0x2
CHIPMISC_CPUSYS_MISC_INTR_OUT_EN_PAD_SHIFT      = 1
CHIPMISC_CPUSYS_MISC_SOFT_INTR_MASK       = 0x1
CHIPMISC_CPUSYS_MISC_SOFT_INTR_SHIFT      = 0

CHIPMISC_BRPHYS_MISC_SPARE_MASK     = 0xffc0
CHIPMISC_BRPHYS_MISC_SPARE_SHIFT       = 6
CHIPMISC_BRPHYS_MISC_BRPHY_1G_1P_SOURCE_SYNC_MII_MASK       = 0x20
CHIPMISC_BRPHYS_MISC_BRPHY_1G_1P_SOURCE_SYNC_MII_SHIFT      = 5
CHIPMISC_BRPHYS_MISC_BR5P_TC10_RDB_MDIO_SEL_MASK      = 0x10
CHIPMISC_BRPHYS_MISC_BR5P_TC10_RDB_MDIO_SEL_SHIFT     = 4
CHIPMISC_BRPHYS_MISC_BRPHY_1G_1PORT_CLEAR_ON_READ_MASK      = 0x8
CHIPMISC_BRPHYS_MISC_BRPHY_1G_1PORT_CLEAR_ON_READ_SHIFT     = 3
CHIPMISC_BRPHYS_MISC_CFG_TC10_SL_M7_INTR_EN_MASK      = 0x4
CHIPMISC_BRPHYS_MISC_CFG_TC10_SL_M7_INTR_EN_SHIFT     = 2
CHIPMISC_BRPHYS_MISC_BR_AUTO_NEG_EN_STRAP_DEF_MASK       = 0x2
CHIPMISC_BRPHYS_MISC_BR_AUTO_NEG_EN_STRAP_DEF_SHIFT      = 1
CHIPMISC_BRPHYS_MISC_CLEAR_ON_READ_EN_MASK      = 0x1
CHIPMISC_BRPHYS_MISC_CLEAR_ON_READ_EN_SHIFT     = 0

CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_BR1G_MASK       = 0x20
CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_BR1G_SHIFT      = 5
CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_BR5_MASK     = 0x10
CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_BR5_SHIFT       = 4
CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_MASK      = 0xf
CHIPMISC_BRPHYS_TC10_CTRL_REG_WAKE_VIA_WAKE_SHIFT     = 0

CHIPMISC_BRPHYS_TC10_STATUS_REG_SPARE_MASK      = 0xe000
CHIPMISC_BRPHYS_TC10_STATUS_REG_SPARE_SHIFT     = 13
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_BR1G_MASK      = 0x1000
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_BR1G_SHIFT     = 12
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_BR1G_MASK     = 0x800
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_BR1G_SHIFT       = 11
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_BR5_MASK       = 0x400
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_BR5_SHIFT      = 10
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_BR5_MASK      = 0x200
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_BR5_SHIFT     = 9
CHIPMISC_BRPHYS_TC10_STATUS_REG_AFE_WAKE_VIA_WAKE_MASK      = 0x100
CHIPMISC_BRPHYS_TC10_STATUS_REG_AFE_WAKE_VIA_WAKE_SHIFT     = 8
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_MASK     = 0xf0
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_SLEEP_MODE_SHIFT       = 4
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_MASK       = 0xf
CHIPMISC_BRPHYS_TC10_STATUS_REG_TC10_INTR_STATUS_SHIFT      = 0

CHIPMISC_LRV18T28ANXESC_RING_OSC_SEL_CTRL_MASK     = 0xf
CHIPMISC_LRV18T28ANXESC_RING_OSC_SEL_CTRL_SHIFT       = 0

CHIPMISC_LRV18T28ANXEEC_RING_OSC_OUTPUT_EN_MASK       = 0x1000
CHIPMISC_LRV18T28ANXEEC_RING_OSC_OUTPUT_EN_SHIFT      = 12
CHIPMISC_LRV18T28ANXEEC_RING_OSC_EN_CTRL_MASK      = 0xfff
CHIPMISC_LRV18T28ANXEEC_RING_OSC_EN_CTRL_SHIFT     = 0

CHIPMISC_SCRATCH_REG_SCRATCH_MASK      = 0xffff
CHIPMISC_SCRATCH_REG_SCRATCH_SHIFT     = 0

class CHIPMISC_RDBType:
    model_rev_num = 0x0
    deviceid_lo = 0x2
    deviceid_hi = 0x4
    switch_misc_ctrl = 0x6
    rsvd0     = 0x8
    ldo_pwrdn = 0x100
    ldo_vregcntl_1 = 0x102
    ldo_vregcntl_2 = 0x104
    ldo_vregcntlen = 0x106
    rsvd1    = 0x108
    swreg_ctrl_reg0 = 0x110
    swreg_ctrl_reg1 = 0x112
    swreg_ctrl_reg2 = 0x114
    swreg_ctrl_reg3 = 0x116
    swreg_ctrl_reg4 = 0x118
    swreg_ctrl_reg5 = 0x11a
    swreg_ctrl_reg6 = 0x11c
    swreg_ctrl_reg7 = 0x11e
    swreg_ctrl_reg8 = 0x120
    swreg_ctrl_reg9 = 0x122
    swreg_stat_reg12 = 0x124
    swreg_stat_reg13 = 0x126
    swreg_stat_reg14 = 0x128
    swreg_stat_reg15 = 0x12a
    swreg_access_ctrl_1 = 0x12c
    swreg_access_ctrl_2 = 0x12e
    swreg_control_status = 0x130
    rsvd2 = 0x132
    sgmii_plus2_pwrdwn = 0x140
    sgmii_plus2_hw_rst_dly_val = 0x142
    sgmii_plus2_mdio_rst_dly_val = 0x144
    sgmii_plus2_pll_rst_dly_val = 0x146
    sgmii_plus2_ext_ctl = 0x148
    rsvd3  = 0x14a
    sgmii_plus2_mdio_ctl = 0x156
    sgmii_plus2_status = 0x158
    rsvd4 = 0x15a
    sgmii_pcie_pwrdwn = 0x160
    sgmii_pcie_hw_rst_dly_val = 0x162
    sgmii_pcie_mdio_rst_dly_val = 0x164
    sgmii_pcie_pll_rst_dly_val = 0x166
    sgmii_pcie_ext_ctl = 0x168
    sgmii_pcie_mdio_ctl = 0x16a
    sgmii_pcie_status = 0x16c
    sgmii_afe_status = 0x16e
    sgmii_plusr_pwrdwn = 0x170
    sgmii_plusr_hw_rst_dly_val = 0x172
    rsvd5  = 0x174
    sgmii_plusr_pll_rst_dly_val = 0x176
    sgmii_plusr_ext_ctl = 0x178
    sgmii_plusr_mdio_ctl = 0x17a
    sgmii_plusr_status = 0x17c
    rsvd6 = 0x17e
    f1_image_status = 0x300
    f1_image_version = 0x302
    f2_image_status = 0x304
    f2_image_version = 0x306
    spare_hw_reg4 = 0x308
    spare_hw_reg5 = 0x30a
    spare_hw_reg6 = 0x30c
    spare_hw_reg7 = 0x30e
    spare_hw_reg8 = 0x310
    spare_hw_reg9 = 0x312
    f1_version = 0x314
    spare_hw_reg11 = 0x316
    pkg_model = 0x318
    spare_hw_reg13 = 0x31a
    spare_hw_reg14 = 0x31c
    spare_hw_reg15 = 0x31e
    spare_sw_reg0 = 0x320
    spare_sw_reg1 = 0x322
    spare_sw_reg2 = 0x324
    spare_sw_reg3 = 0x326
    spare_sw_reg4 = 0x328
    spare_sw_reg5 = 0x32a
    spare_sw_reg6 = 0x32c
    spare_sw_reg7 = 0x32e
    spare_sw_reg8 = 0x330
    spare_sw_reg9 = 0x332
    spare_sw_reg10 = 0x334
    spare_sw_reg11 = 0x336
    spare_sw_reg12 = 0x338
    spare_sw_reg13 = 0x33a
    spare_sw_reg14 = 0x33c
    spare_sw_reg15 = 0x33e
    cpusys_misc = 0x340
    brphys_misc = 0x342
    brphys_tc10_ctrl_reg = 0x344
    brphys_tc10_status_reg = 0x346
    ring_osc_sel_ctrl_reg = 0x348
    ring_osc_en_ctrl_reg = 0x34a
    rsvd7  = 0x34c
    scratch_reg = 0xffe

CHIPMISC_BASE                   = 0x4A800000

CHIPMISC_MAX_HW_ID              = 1

CHIPMISC_SWREG_CTRL_REG1_VALUE  = 0x1801

CHIPMISC_SWREG_CTRL_REG2_VALUE  = 0xEE8A

CHIPMISC_SWREG_CTRL_REG3_VALUE  = 0x0300

CHIPMISC_SWREG_CTRL_REG4_VALUE  = 0xCCD0

CHIPMISC_SWREG_CTRL_REG5_VALUE  = 0x0580

CHIPMISC_SWREG_CTRL_REG6_VALUE  = 0xB000

CHIPMISC_SWREG_CTRL_REG7_VALUE  = 0x1FFF

CHIPMISC_SWREG_CTRL_REG8_VALUE  = 0x0000

CHIPMISC_SWREG_CTRL_REG9_VALUE  = 0x020C

CHIPMISC_SWREG_CTRL_REG0_VALUE0 = 0x830

CHIPMISC_SWREG_CTRL_REG0_VALUE1 = 0x832

CHIPMISC_SWREG_TIMEOUT_COUNT    = 10000

