# SPDX-License-Identifier: GPL-2.0
#
obj-m += brcm-xgbe.o

brcm-xgbe-objs := xgbe-main.o xgbe-drv.o xgbe-dev.o \
		xgbe-desc.o xgbe-ethtool.o \
		xgbe-ptp.o \
		xgbe-mbx.o xgbe-eli.o \
		xgbe-dcb.o xgbe-pci.o \
		xgbe-debugfs.o xgbe-sriov.o\
		xgbe-phy.o
