#
# Copyright 2020-2022 Broadcom Limited.  All rights reserved.
#
# This program is the proprietary software of Broadcom Limited and/or its
# licensors, and may only be used, duplicated, modified or distributed pursuant
# to the terms and conditions of a separate, written license agreement executed
# between you and Broadcom (an "Authorized License").
#
# Except as set forth in an Authorized License, Broadcom grants no license
# (express or implied), right to use, or waiver of any kind with respect to the
# Software, and Broadcom expressly reserves all rights in and to the Software
# and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
# LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
# IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
#
#  Except as expressly set forth in the Authorized License,
# 1. This program, including its structure, sequence and organization,
#    constitutes the valuable trade secrets of Broadcom, and you shall use all
#    reasonable efforts to protect the confidentiality thereof, and to use this
#    information only in connection with your use of Broadcom integrated
#    circuit products.
#
# 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
#    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
#    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
#    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
#    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
#    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
#    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
#    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
#    SOFTWARE.
#
# 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
#    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
#    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
#    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
#    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
#    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. \$1, WHICHEVER
#    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
#    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
#
####################################################################################



BRCM_COMP_NAME := bcm89572_evk_bl
BRCM_COMP_TYPE := bootloader
BRCM_COMP_DEPENDS += wdg
BRCM_COMP_DEPENDS += spum secureheap
BRCM_COMP_DEPENDS += mcudrv utils arm
BRCM_COMP_DEPENDS += otpm
BRCM_COMP_DEPENDS += timdrv vtmondrv
BRCM_COMP_DEPENDS += time
BRCM_COMP_DEPENDS += queue wdtdrv
BRCM_COMP_DEPENDS += ethsrv
BRCM_COMP_DEPENDS += rpc_v2 crypto_verify_hw


BRCM_COMP_APP_OPT += ENABLE_TIMER_SP804
BRCM_COMP_APP_OPT += ENABLE_RPC_V2
BRCM_COMP_APP_OPT += ENABLE_RPC_UDP
BRCM_COMP_APP_OPT += ENABLE_IPC
BRCM_COMP_APP_OPT += ENABLE_FLASH0
BRCM_COMP_APP_OPT += ENABLE_IMGL_MMAP_ASYNC_MODE
BRCM_COMP_APP_OPT += ENABLE_SYSTEM_SERVICE
BRCM_COMP_APP_OPT += ENABLE_ETH
BRCM_COMP_APP_OPT += ENABLE_NIF
BRCM_COMP_APP_OPT += ENABLE_INET
BRCM_COMP_APP_OPT += ENABLE_TIME_MODULE
BRCM_COMP_APP_OPT += ENABLE_OTP_MODULE
BRCM_COMP_APP_OPT += ENABLE_DEFAULT_NIF_CFG
BRCM_COMP_APP_OPT += ENABLE_NVM
BRCM_COMP_APP_OPT += ENABLE_OTP_MODULE
BRCM_COMP_APP_OPT += ENABLE_IMGL_V2
BRCM_COMP_APP_OPT += ENABLE_CRYPTO_SERVICE
BRCM_COMP_APP_OPT += ENABLE_ETH_SERVICE
BRCM_COMP_APP_OPT += ENABLE_WDG_MODULE

BRCM_CFLAGS += -DBASE_KERNEL
BRCM_CFLAGS += -D__BCM89572_EVK__
BRCM_COMP_APP_CFLAGS += -DIMGL_MODE_FUNC_TABLE_PRIO0=IMGL_MemoryMapModule
BRCM_CFLAGS += -DIMGL_MEMORY_SIZE_0=0x40000UL
BRCM_CFLAGS += -DIMGL_MEMORY_SIZE_1=0x28000UL
BRCM_CFLAGS += -DENABLE_TIMER_SP804
BRCM_CFLAGS += -DENABLE_TIM_CHANN0_CB
BRCM_CFLAGS += -DENABLE_HSM
BRCM_CFLAGS += -DENABLE_SYSTEM_MODULES

BRCM_CFLAGS += -DIMGL_MMAP_SIZE_0=0x200000UL
BRCM_CFLAGS += -DIMGL_MMAP_ADDR_0=0x60000000UL
BRCM_CFLAGS += -DCRYPTO_VERIFY_NUM_CTX_LOG2=2UL
BRCM_CFLAGS += -DCRYPTO_VERIFY_NUM_MSG_PER_CTX_LOG2=2UL

BRCM_COMP_LIB_CFLAGS += -DENABLE_WFI

BRCM_INC += $(BRCM_SDK_ROOT)/system
BRCM_INC += $(BRCM_SDK_ROOT)/system/imgl/inc
BRCM_INC += $(BRCM_SDK_ROOT)/system/imgl/inc/osil

BRCM_CFLAGS += -DENABLE_B0
BRCM_CFLAGS += -DNVM_SERVER_TASK_ID=NVM_Server
BRCM_CFLAGS += -DFLASH_IRQ_PROCESS_TASK=NVM_Server
BRCM_CFLAGS += -DFLASH0_EVENT=SystemEvent7
BRCM_CFLAGS += -DFLASH1_EVENT=SystemEvent8

BRCM_CFLAGS += -DSYS_TASK_NAME=SYSTEM_Task
BRCM_CFLAGS += -DCRYPTO_TASK_NAME=SYSTEM_Task
BRCM_CFLAGS += -DSYS_NOTIF_EVENT=SystemEvent6
BRCM_CFLAGS += -DIPC_SYS_MSGQ_EVENT=SystemEvent4

BRCM_CFLAGS += -DETHERNET_RPC_SERVER_TASK=RPC_ServerTask
BRCM_CFLAGS += -DMDIO_STATE_HANDLER_TASK=ETHERNET_Task
BRCM_CFLAGS += -DMDIO_STATE_HANDLER_EVENT=SystemEvent8

BRCM_INC += $(BRCM_SDK_ROOT)/ethernet/drivers/transceiver/inc/
BRCM_INC += $(BRCM_SDK_ROOT)/ethernet/drivers/transceiver/inc/osil

BRCM_INC += $(BRCM_SDK_ROOT)/bootloader/inc
BRCM_INC += $(BRCM_SDK_ROOT)/system/wdg/inc/
BRCM_INC += $(BRCM_SDK_ROOT)/system/console/inc/
BRCM_INC += $(BRCM_SDK_ROOT)/ethernet/common/ethsrv/inc
BRCM_INC += $(BRCM_SDK_ROOT)/ethernet/common/ethsrv/inc/osil
BRCM_INC += $(BRCM_SDK_ROOT)/ethernet/common/ethsrv/os/erika
BRCM_INC += $(BRCM_SDK_ROOT)/nvm/service/inc/
BRCM_INC += $(BRCM_SDK_ROOT)/nvm/service/inc/osil
BRCM_INC += $(BRCM_SDK_ROOT)/system/common/inc/
BRCM_INC += $(BRCM_SDK_ROOT)/init/bcm8957x/inc/
BRCM_INC += $(BRCM_SDK_ROOT)/init/bcm8957x/
BRCM_INC += $(BRCM_SDK_ROOT)/init/bcm8957x/chip
BRCM_INC += $(BRCM_SDK_ROOT)/drivers/include
BRCM_INC += $(BRCM_SDK_ROOT)/base/inc
BRCM_INC += $(BRCM_SDK_ROOT)/ethernet/common/rpc/inc/osil
BRCM_INC += $(BRCM_SDK_ROOT)/drivers/uart/inc
BRCM_INC += $(BRCM_SDK_ROOT)/drivers/dbgmem/inc
BRCM_INC += $(BRCM_SDK_ROOT)/drivers/uart/inc/osil
BRCM_INC += $(BRCM_SDK_ROOT)/nvm/drivers/flash/inc
BRCM_INC += $(BRCM_SDK_ROOT)/nvm/drivers/flash/inc/osil

BRCM_CFLAGS += -DSW_IMAGE_TYPE=\"$(SW_IMAGE_TYPE)\" -DSW_IMAGE_VERSION=\"$(SW_IMAGE_VERSION)\" -DBUILD_TIME=\"$(BUILD_TIME)\" -DBUILDING_USER=\"$(BUILDING_USER)\" -DBUILD_SERVER=\"$(BUILD_SERVER)\"
BRCM_CFLAGS += -DEE_BUILD_INFO=\"Base-$(comp)\ Ver:$(SW_IMAGE_TYPE)-$(SW_IMAGE_VERSION),$(BUILD_TIME)\" -DCOMPILER_VER_INFO=\"$(COMPILER_INFO)-$(COMPILER_VERSION)\"

BRCM_CFLAGS += -DNVM_MSGQ_EVENT=SystemEvent3
BRCM_CFLAGS += -DNVM_NOTIF_EVENT=SystemEvent9
BRCM_CFLAGS += -DNVM_FLS_0_CB_IND_EVENT=SystemEvent4
BRCM_CFLAGS += -DNVM_FLS_1_CB_IND_EVENT=SystemEvent6
BRCM_CFLAGS += -DRPC_LOADER_EVENT=SystemEvent6
BRCM_CFLAGS += -DRPC_LOCAL_CMDQ_EVENT=SystemEvent5
BRCM_CFLAGS += -DETHERNET_NOTIF_EVENT=SystemEvent11
BRCM_CFLAGS += -DIPC_CHANN1_EVENT=SystemEvent9
BRCM_CFLAGS += -DSYS_REBOOT_EVENT=SystemEvent12 # this is for system task
BRCM_CFLAGS += -DIMGL_MODE_FUNC_TABLE_PRIO0=IMGL_MemoryMapModule
BRCM_CFLAGS += -DRPC_MSGQ_MASTER_IFC_SYS=SYSTEM_Service
BRCM_CFLAGS += -DRPC_CMDQ_EVENT=SystemEvent7
BRCM_CFLAGS += -DIPC_MAX_CHANNELS=1

BRCM_CFLAGS += -DSYSTEM_MONITOR_ALARM_EVENT=SystemEvent11

BRCM_CFLAGS += -DENABLE_MSG_QUEUE
BRCM_CFLAGS += -DENABLE_RPC_V2
BRCM_CFLAGS += -DENABLE_IPC
BRCM_CFLAGS += -DENABLE_OTP
BRCM_CFLAGS += -DENABLE_DBGMEM
BRCM_CFLAGS += -DENABLE_FW_LOAD
BRCM_CFLAGS += -DENABLE_WATCHDOG_SP805

BRCM_INC += $(BRCM_SDK_ROOT)/security/sha/inc/
BRCM_INC += $(BRCM_SDK_ROOT)/security/rsa/inc/
BRCM_INC += $(BRCM_SDK_ROOT)/security/rsa_v2/inc/
BRCM_INC += $(BRCM_SDK_ROOT)/security/secutils/inc/

# BASE OS
BRCM_CFLAGS += -DENABLE_THREAD_PROTECTION

BRCM_COMP_APP_SRC += ../../ethernet/tcp_ip/inet/os/platform/switch/inet_cfg.c
