#
# Copyright 2021-2022 Broadcom Limited.  All rights reserved.
#
# This program is the proprietary software of Broadcom Limited and/or its
# licensors, and may only be used, duplicated, modified or distributed pursuant
# to the terms and conditions of a separate, written license agreement executed
# between you and Broadcom (an "Authorized License").
#
# Except as set forth in an Authorized License, Broadcom grants no license
# (express or implied), right to use, or waiver of any kind with respect to the
# Software, and Broadcom expressly reserves all rights in and to the Software
# and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
# LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
# IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
#
#  Except as expressly set forth in the Authorized License,
# 1. This program, including its structure, sequence and organization,
#    constitutes the valuable trade secrets of Broadcom, and you shall use all
#    reasonable efforts to protect the confidentiality thereof, and to use this
#    information only in connection with your use of Broadcom integrated
#    circuit products.
#
# 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
#    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
#    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
#    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
#    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
#    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
#    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
#    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
#    SOFTWARE.
#
# 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
#    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
#    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
#    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
#    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
#    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. \$1, WHICHEVER
#    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
#    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
#
####################################################################################


##  @defchapter grp_introduction Introduction
#
#   @addtogroup grp_introduction
#   @{
#
#   This manual documents Software Architecture, Design and Test specification for
#   Broadcom Automotive SDK.
#
#   <i>The manual is autogenerated for each chipset family and contents may be
#   limited to specific family of chipsets as per the Title. Broadcom internal
#   version of this contains Requirement specification and Traceability, hence
#   must never be shared outside of Broadcom.</i>
#
#   @section sec_doc_layout Document Layout
#   The manual is laid out into multiple chapters, as described below.
#
#   <b><i>Introduction (This Chapter)</i></b> provides a bird's eye view of SDK
#   Architecture, Flash Layout, Folder structure and References.
#   <i>Content of this chapter is generic to suit different Broadcom Automotive Chips.
#   Refer to Technical Reference Manual and Sections in individual chapters for
#   availability of the feature on specific chipset/SDK. </i>
#
#   <b><i>Getting Started</i></b> provides instructions to setup build machine,
#   setup host machine for flashing and debugging, board descriptions, building
#   and flashing applications etc
#
#   <b><i>Initialization</i></b> provides details about initialization of CPU
#   (Exception vectors, MPU, Privilege levels), Clearing and/or Copying of data segment
#   to appropriate location, MCU Initialization, Starting Operating System etc
#
#   <b><i>System Software</i></b> provides details about initialization of Time Module
#   Watchdog module, other services like IO, NVM, Crypto, Image loader etc
#
#   <b><i>Input-Output</i></b> provides framework for IO services, modules etc
#
#   <b><i>Cryptography</i></b> provides services including signature
#   verification/generation, bulk encryption/decryption, Secure Key exchange,
#   Random number generation etc
#
#   <b><i>Non-Volatile Memory</i></b> provides NVM Services, and NVM drivers
#   (Flash Memory access, OTP etc)
#
#   <b><i>Ethernet</i></b> provides services including various protocol stacks
#   (IPv4, UDP, TFTP, RTP, AVB), and Ethernet drivers (Controller, Transceiver,
#	Switch, MDIO etc)
#
#   <b><i>Multimedia</i></b> provides Media Framework, and Media components
#   including for Camera, Audio, Display, Video Encoding/Decoding,
#   Pre/Post processing etc
#
#   <b><i>Applications</i></b> provides configuration options to showcase the
#
#   @}
#
#   @defgroup grp_abstract Architecture
#   @ingroup grp_introduction
#
#   @addtogroup grp_abstract
#   @{
#   SDK architecture follows a modular and layered approach to address
#       -# portability across operating systems
#       -# reduced memory footprint for each use-case
#       -# Safety and Security at component and system level
#       -# Optimized power for each use-case
#
#   SDK architecture considers different RTOSes like @ref grp_base, OSEK
#   (Erika etc.), AUTOSAR, freeRTOS (excluding Heap) etc.
#   For demonstrating the use-cases,  @ref grp_base is chosen as it is
#   light-weight with a very small footprint. Further sections in this document
#   refers BASE OS extensively.
#
#   @image html sdk_architecture.png "SDK Architecture" width="200%"
#
#   Above picture depicts a bird's eye view of SDK Architecture. SDK architecture
#   follows a three layered approach viz. Drivers, Middleware and Application
#   layers.
#
#   Drivers is a thin layer of privileged software abstracting the hardware
#   details from the upper layers. Most drivers provide APIs in the unprivileged
#   space for middleware to access. Architecture mandates access restrictions to
#   hardware registers and driver data strucutres from unprivileged software.
#
#   Middleware layer consists of software logic dependent/independent of
#   underlying hardware and does not access hardware directly. For E.g. TCP/IP
#   stack is hardware independent, while the camera sub-system is hardware
#   dependent. Middleware and Drivers are further grouped based on functionality
#   viz. Initialization & System, IO Services, Non-Volatile Memory,
#   Security/Crypto, Ethernet, Multimedia, and Debug.
#
#   Application layer consists of use-case specific code which ties all
#   required components together with appropriate attributes. Application
#   configures and controls all the components in the system.
#   For media applications, Application selects needed media components
#   and sets up the media component connection graph, and Media Framework
#   performs intitialization, configuration and assists data flow as needed.
#
#   SDK Architecture attempts to minimize
#   -# interaction with hardware directly in the middleware/application layers
#   -# interaction between components directly
#   -# interaction between drivers directly
#   .
#
#   SDK provides below abstractions for easy porting to other operating systems
#   (OSEK like), compilers, switching privilege levels etc
#   -# Compiler abstractions for alignment, sections etc
#   -# Standard Library calls like memcpy, memset etc
#   -# Operating system calls for signalling and waiting, alarms etc
#   -# Supervisor mode switch request
#
#   @file architecture/abstract/comp.mk
#   @brief Abstractions
#   @version 0.1 Initial version
#   @}
#

BRCM_COMP_NAME := abstract
BRCM_COMP_DEPENDS :=
BRCM_COMP_TYPE := lib

BRCM_COMP_LIB_CFLAGS += -DCPU_CLOCK=$(BRCM_CPU_FREQUENCY)
BRCM_COMP_LIB_CFLAGS += -DTRUE=1UL
BRCM_COMP_LIB_CFLAGS += -DFALSE=0UL

BRCM_COMP_DOC_SRC += doc/arch_page.c

BRCM_COMP_EXPORT_HDR += inc/bcm_comp.h
BRCM_COMP_EXPORT_HDR += inc/bcm_err.h

BRCM_INC += $(BRCM_SDK_ROOT)/host/ns2/kernel/tools/include/tools

BRCM_COMP_APP_SRC  += os/common/error_str.c
BRCM_COMP_HOST_SRC += os/common/error_str.c

BRCM_COMP_DOC_SRC += doc/arch_common.vsd
BRCM_COMP_DOC_SRC += doc/arch_common.vsdx
BRCM_COMP_DOC_SRC += doc/images/arch_generic_component.jpg

BRCM_COMP_REQ_SRC += doc/abstract_req.c
BRCM_COMP_REQ_SRC += doc/cache_req.c
BRCM_COMP_REQ_SRC += doc/interrupt_req.c

BRCM_COMP_EXPORT_HDR += inc/compiler.h
BRCM_COMP_EXPORT_HDR += inc/bcm_utils.h
BRCM_COMP_EXPORT_HDR += inc/svc.h
BRCM_COMP_EXPORT_HDR += inc/bcm_os.h
BRCM_COMP_EXPORT_HDR += inc/bcm_thread_safety.h
BRCM_COMP_EXPORT_HDR += inc/osil/bcm_osil_svc.h
BRCM_COMP_EXPORT_HDR += inc/cpu.h
BRCM_COMP_EXPORT_HDR += inc/mpu.h
BRCM_COMP_EXPORT_HDR += inc/cache.h
BRCM_COMP_EXPORT_HDR += inc/interrupt.h

BRCM_COMP_LIB_SRC += lib/bcm_os.c
BRCM_COMP_LIB_SRC += lib/svc_request.c
BRCM_COMP_LIB_SRC += lib/cpu_delay.c

BRCM_COMP_APP_SRC += os/common/bcm_abstract_osil.c

BRCM_COMP_HOST_SRC += host/cpu_utils.c
ifeq ($(call isappopt,ENABLE_CPU_GENERIC),yes)
BRCM_COMP_HOST_SRC += host/cpu_generic.c
endif
