#
# Copyright 2019 Broadcom Limited.  All rights reserved.
#
# This program is the proprietary software of Broadcom Limited and/or its
# licensors, and may only be used, duplicated, modified or distributed pursuant
# to the terms and conditions of a separate, written license agreement executed
# between you and Broadcom (an "Authorized License").
#
# Except as set forth in an Authorized License, Broadcom grants no license
# (express or implied), right to use, or waiver of any kind with respect to the
# Software, and Broadcom expressly reserves all rights in and to the Software
# and all intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED
# LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
# IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
#
#  Except as expressly set forth in the Authorized License,
# 1. This program, including its structure, sequence and organization,
#    constitutes the valuable trade secrets of Broadcom, and you shall use all
#    reasonable efforts to protect the confidentiality thereof, and to use this
#    information only in connection with your use of Broadcom integrated
#    circuit products.
#
# 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
#    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
#    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
#    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
#    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
#    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS,
#    QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION.
#    YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE
#    SOFTWARE.
#
# 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
#    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
#    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
#    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
#    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
#    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
#    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
#    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
#
####################################################################################

##  @defgroup grp_otpdrv OTP Driver
#   @ingroup grp_nvm
#
#   @addtogroup grp_otpdrv
#   @{
#   @file nvm/drivers/otp/comp.mk
#   @brief Makefile for OTP Driver
#   @version 0.1 Initial version
#   @}

BRCM_COMP_NAME := otpdrv
BRCM_COMP_DEPENDS :=
BRCM_COMP_TYPE := lib

BRCM_COMP_REQ_SRC += doc/otp_req.c
BRCM_COMP_EXPORT_HDR += inc/otp.h
BRCM_COMP_EXPORT_HDR += inc/osil/otp_osil.h
BRCM_COMP_LIB_SRC += lib/otp.c
BRCM_COMP_CONFIG_SCRIPT += config/otp_config.py
BRCM_COMP_APP_OPT += ENABLE_OTP

ifeq ($(CHIP_FAMILY),bcm8953x)
BRCM_COMP_REQ_SRC += doc/otp_v1_req.c
BRCM_COMP_LIB_SRC += lib/otp_v1.c
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_END=255UL
BRCM_COMP_LIB_CFLAGS += -DOTP_BYTES_PER_ROW=3UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DATA_MASK_WITH_ECC=0x3FFFFFFUL
BRCM_COMP_LIB_CFLAGS += -DOTP_ECC_BITS=6UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_BRCM_REG_START=12UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_ROW=64UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_MASK=0x1UL
BRCM_COMP_LIB_CFLAGS += -DOTP_RSA_KEY_BYTES_PER_ROW=OTP_BYTES_PER_ROW
BRCM_COMP_LIB_CFLAGS += -DOTP_PUBKEY_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_START=65UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SECURE_KEY_SIZE=256UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_EN_ROW=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPTKEY_VALID_COUNT=8UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_KEY_SIZE=32UL
BRCM_COMP_LIB_CFLAGS += -DOTP_STACKINGINFO_ROW_ADDR=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_MAC0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET123_ADDR=151UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET456_ADDR=152UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET123_ADDR=153UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET456_ADDR=154UL
BRCM_COMP_LIB_CFLAGS += -DOTP_IPCFG_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_TC10_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_TC10_CONFIG_SIZE=144UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_XCVR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_XCVR_CONFIG_SIZE=1024UL
BRCM_COMP_APP_CFLAGS += $(BRCM_COMP_LIB_CFLAGS)
endif
ifeq ($(CHIP_FAMILY),bcm8910x)
BRCM_COMP_REQ_SRC += doc/otp_v2_req.c
BRCM_COMP_LIB_SRC += lib/otp_v2.c
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_END=255UL
BRCM_COMP_LIB_CFLAGS += -DOTP_BYTES_PER_ROW=3UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DATA_MASK_WITH_ECC=0x3FFFFFFUL
BRCM_COMP_LIB_CFLAGS += -DOTP_ECC_BITS=6UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_BRCM_REG_START=12UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_BRCM_REG_END=63UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_ROW=64UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_MASK=1UL
BRCM_COMP_LIB_CFLAGS += -DOTP_RSA_KEY_BYTES_PER_ROW=OTP_BYTES_PER_ROW
BRCM_COMP_LIB_CFLAGS += -DOTP_PUBKEY_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_START=65UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SECURE_KEY_SIZE=256UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_EN_ROW=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPTKEY_VALID_COUNT=8UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_KEY_SIZE=32UL
BRCM_COMP_LIB_CFLAGS += -DOTP_STACKINGINFO_ROW_ADDR=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_MAC0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET123_ADDR=151UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET456_ADDR=152UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET123_ADDR=153UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET456_ADDR=154UL
BRCM_COMP_LIB_CFLAGS += -DOTP_IPCFG_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_TC10_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_TC10_CONFIG_SIZE=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_XCVR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_XCVR_CONFIG_SIZE=0UL
BRCM_COMP_APP_CFLAGS += $(BRCM_COMP_LIB_CFLAGS)
endif
ifeq ($(CHIP_FAMILY),bcm8956x)
BRCM_COMP_IT_SRC += tests/integration/otp_it.h
ifeq ($(version),b0)
BRCM_COMP_REQ_SRC += doc/otp_v4_req.c
BRCM_COMP_LIB_SRC += lib/otp_v4.c
BRCM_COMP_LIB_CFLAGS += -DENABLE_OTP_WRITE_OPERATION=1UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_END=640UL
BRCM_COMP_LIB_CFLAGS += -DOTP_BYTES_PER_ROW=4UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DATA_MASK_WITH_ECC=0xFFFFFFFFUL
BRCM_COMP_LIB_CFLAGS += -DOTP_ECC_BITS=7UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_BRCM_REG_START=15UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_ROW=96UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_MASK=0x1UL
BRCM_COMP_LIB_CFLAGS += -DOTP_PUBKEY_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_INVAL=16UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_START=97UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_INVAL=17UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_START=161UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SECURE_KEY_SIZE=256UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_EN_ROW=225UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPTKEY_VALID_COUNT=8UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_INVAL=18UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_START=226UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_INVAL=19UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_START=234UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_INVAL=20UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_START=242UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_INVAL=21UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_START=250UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_INVAL=22UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_START=258UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_INVAL=23UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_START=266UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_INVAL=24UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_START=274UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_INVAL=25UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_START=282UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_KEY_SIZE=32UL
BRCM_COMP_LIB_CFLAGS += -DOTP_STACKINGINFO_ROW_ADDR=290UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_MAC0_INVAL=26UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET123_ADDR=294UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET456_ADDR=295UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET123_ADDR=296UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET456_ADDR=297UL
BRCM_COMP_LIB_CFLAGS += -DOTP_IPCFG_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_INVAL=27UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_START=298UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_INVAL=28UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_START=302UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_TC10_START=306UL
BRCM_COMP_LIB_CFLAGS += -DOTP_TC10_CONFIG_SIZE=144UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_XCVR_START=342UL
BRCM_COMP_LIB_CFLAGS += -DOTP_XCVR_CONFIG_SIZE=1024UL
else  # version == a0
BRCM_COMP_REQ_SRC += doc/otp_v3_req.c
BRCM_COMP_LIB_SRC += lib/otp_v3.c
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_END=255UL
BRCM_COMP_LIB_CFLAGS += -DOTP_BYTES_PER_ROW=3UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DATA_MASK_WITH_ECC=0x3FFFFFFUL
BRCM_COMP_LIB_CFLAGS += -DOTP_ECC_BITS=6UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_BRCM_REG_START=12UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_ROW=64UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_MASK=0x1UL
BRCM_COMP_LIB_CFLAGS += -DOTP_RSA_KEY_BYTES_PER_ROW=OTP_BYTES_PER_ROW
BRCM_COMP_LIB_CFLAGS += -DOTP_PUBKEY_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_START=65UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SECURE_KEY_SIZE=256UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_EN_ROW=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPTKEY_VALID_COUNT=8UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_KEY_SIZE=32UL
BRCM_COMP_LIB_CFLAGS += -DOTP_STACKINGINFO_ROW_ADDR=290UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_MAC0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET123_ADDR=151UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET456_ADDR=152UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET123_ADDR=153UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET456_ADDR=154UL
BRCM_COMP_LIB_CFLAGS += -DOTP_IPCFG_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_TC10_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_TC10_CONFIG_SIZE=144UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_XCVR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_XCVR_CONFIG_SIZE=1024UL
endif
BRCM_COMP_APP_CFLAGS += $(BRCM_COMP_LIB_CFLAGS)
endif

ifeq ($(CHIP_FAMILY),bcm8957x)
BRCM_COMP_REQ_SRC += doc/otp_v4_req.c
BRCM_COMP_LIB_SRC += lib/otp_v4.c
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_END=640UL
BRCM_COMP_LIB_CFLAGS += -DOTP_BYTES_PER_ROW=4UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DATA_MASK_WITH_ECC=0xFFFFFFFFUL
BRCM_COMP_LIB_CFLAGS += -DOTP_ECC_BITS=7UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_BRCM_REG_START=15UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_ROW=96UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_MASK=0x1UL
BRCM_COMP_LIB_CFLAGS += -DOTP_PUBKEY_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_INVAL=16UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_START=97UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_INVAL=17UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_START=161UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SECURE_KEY_SIZE=256UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_EN_ROW=225UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPTKEY_VALID_COUNT=8UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_INVAL=18UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_START=226UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_INVAL=19UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_START=234UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_INVAL=20UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_START=242UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_INVAL=21UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_START=250UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_INVAL=22UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_START=258UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_INVAL=23UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_START=266UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_INVAL=24UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_START=274UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_INVAL=25UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_START=282UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_KEY_SIZE=32UL
BRCM_COMP_LIB_CFLAGS += -DOTP_STACKINGINFO_ROW_ADDR=290UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_MAC0_INVAL=26UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET123_ADDR=294UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET456_ADDR=295UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET123_ADDR=296UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET456_ADDR=297UL
BRCM_COMP_LIB_CFLAGS += -DOTP_IPCFG_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_INVAL=27UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_START=298UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_INVAL=28UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_START=302UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_TC10_START=306UL
BRCM_COMP_LIB_CFLAGS += -DOTP_TC10_CONFIG_SIZE=144UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_XCVR_START=342UL
BRCM_COMP_LIB_CFLAGS += -DOTP_XCVR_CONFIG_SIZE=1024UL
BRCM_COMP_APP_CFLAGS += $(BRCM_COMP_LIB_CFLAGS)
endif

ifeq ($(CHIP_FAMILY),bcm8958x)
BRCM_COMP_REQ_SRC += doc/otp_v4_req.c
BRCM_COMP_LIB_SRC += lib/otp_v4.c
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_END=1024UL
BRCM_COMP_LIB_CFLAGS += -DOTP_BYTES_PER_ROW=4UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DATA_MASK_WITH_ECC=0xFFFFFFFFUL
BRCM_COMP_LIB_CFLAGS += -DOTP_ECC_BITS=7UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_BRCM_REG_START=28UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_ROW=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_MASK=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_PUBKEY_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SECURE_KEY_SIZE=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_EN_ROW=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPTKEY_VALID_COUNT=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_KEY_SIZE=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_STACKINGINFO_ROW_ADDR=29UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_MAC0_INVAL=839UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_MAC1_INVAL=840UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET123_ADDR=33UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET456_ADDR=34UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET123_ADDR=35UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET456_ADDR=36UL
BRCM_COMP_LIB_CFLAGS += -DOTP_IPCFG_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_INVAL=841UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_START=37UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_INVAL=842UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_START=41UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_TC10_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_TC10_CONFIG_SIZE=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_XCVR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_XCVR_CONFIG_SIZE=0UL
BRCM_COMP_APP_CFLAGS += $(BRCM_COMP_LIB_CFLAGS)
endif

ifeq ($(CHIP_FAMILY),bcm8908x)
BRCM_COMP_REQ_SRC += doc/otp_v2_req.c
BRCM_COMP_LIB_SRC += lib/otp_v2.c
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_END=255UL
BRCM_COMP_LIB_CFLAGS += -DOTP_BYTES_PER_ROW=3UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DATA_MASK_WITH_ECC=0x3FFFFFFUL
BRCM_COMP_LIB_CFLAGS += -DOTP_ECC_BITS=6UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_BRCM_REG_START=12UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_BRCM_REG_END=63UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_ROW=64UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SEC_BOOT_EN_MASK=1UL
BRCM_COMP_LIB_CFLAGS += -DOTP_RSA_KEY_BYTES_PER_ROW=OTP_BYTES_PER_ROW
BRCM_COMP_LIB_CFLAGS += -DOTP_PUBKEY_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY0_START=65UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_RSA_KEY1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SECURE_KEY_SIZE=256UL
BRCM_COMP_LIB_CFLAGS += -DOTP_SECURE_KEY_SHA_SIZE=32UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_EN_ROW=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPTKEY_VALID_COUNT=8UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY0_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY2_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY3_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY4_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY5_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY6_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_DECRYPT_KEY7_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DECRYPT_KEY_SIZE=32UL
BRCM_COMP_LIB_CFLAGS += -DOTP_STACKINGINFO_ROW_ADDR=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_MAC0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET123_ADDR=151UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_0_OCTET456_ADDR=152UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET123_ADDR=153UL
BRCM_COMP_LIB_CFLAGS += -DOTP_MAC_ADDR_1_OCTET456_ADDR=154UL
BRCM_COMP_LIB_CFLAGS += -DOTP_IPCFG_VALID_COUNT=2UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP0_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_INVAL=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_IP1_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_TC10_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_TC10_CONFIG_SIZE=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_ADDR_XCVR_START=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_XCVR_CONFIG_SIZE=0UL
BRCM_COMP_APP_CFLAGS += $(BRCM_COMP_LIB_CFLAGS)
endif

#OPT bits [163:160] store WDT
BRCM_COMP_LIB_CFLAGS += -DOTP_DISABLE_BIT_SHIFT_WDT=0UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DISABLE_BIT_SHIFT_FLASH=4UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DISABLE_BIT_SHIFT_TFTP=8UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DISABLE_BIT_SHIFT_IPC=12UL
BRCM_COMP_LIB_CFLAGS += -DOTP_DISABLE_BIT_MASK_4BIT=0xFUL
BRCM_COMP_LIB_CFLAGS += -DOTP_DISABLE_BIT_VAL_4BIT=0xAUL


BRCM_COMP_APP_SRC += os/erika/otp_osil.c
